Overhauls Observer UI
BeeStation/BeeStation-Hornet pull request #10050
Opened 2023-10-19 23:24 UTC by Tsar-Salat

Ports:
- https://github.com/tgstation/tgstation/pull/57471
- https://github.com/tgstation/tgstation/pull/61638

## About The Pull Request
Adds spawner and Minigames menu from /tg/

Removes "Jump to Mob" Button

## Why It's Good For The Game

The Spawners menu and CTF are both existing features that players can use, but its not obvious to new players because the former is hidden deep in the statpanel, and the latter requires you to know you can jump to it and click on it to request a CTF game to start.

I removed the Jump To Mob Button as it became redundant when we Converted the Orbit button to TGUI.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/855cbdc1-5b61-4a8c-887d-c573f30a84e6

</details>

## Changelog
:cl: rkz, NamelessFairy, Mothblocks
add: added spawners button to observer UI
add: added Minigames button to observer UI
remove: removed Jump To Mob button from Observer UI. The Orbit button already lists all mobs and is the superior tool anyway. Admins can use Jump to Key anyway.
/:cl:

2023-10-22 21:41 UTC, Tsar-Salat commented
IDIOT

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/9c9735e1-0872-4a5d-a776-b0484c513b89)

STUPID MORON

2023-10-22 21:44 UTC, Tsar-Salat commented
ohhh my fucking gooooood

2023-10-31 15:30 UTC, itsmeow requested changes
We don't have enough ghost minigames to warrant a whole button and menu for it. My suggestion is adding a tab to the spawners menu and removing the minigames button, or merge spawners into the minigames button.

2023-10-31 15:30 UTC, itsmeow commented on tgui/packages/tgui/interfaces/CTFPanel.js
> +    <Window title="CTF Panel" width={700} height={600}>
```suggestion
    <Window title="CTF Panel" width={700} height={600} theme="generic">
```

2023-10-31 15:30 UTC, itsmeow commented
Also remove the `mafia` icon that was added.

2023-10-31 15:40 UTC, Tsar-Salat commented
> We don't have enough ghost minigames to warrant a whole button and menu for i

Adding a button front and center so new players can see it and know CTF exists is a dealbreaker for me.

2023-10-31 15:40 UTC, closed without merging