Adds Bubble tea to the game / Fixes drinks name
BeeStation/BeeStation-Hornet pull request #10072
Opened 2023-10-22 11:44 UTC by ClownMoff

## About The Pull Request

Adds a new drink to the coffee vendor. 

## Why It's Good For The Game

White woman need more representation. Also it was requested here: 
https://forums.beestation13.com/t/add-bubble-tea/24274/20

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

![imagen](https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/cbf8042d-9ffa-47e2-beb0-e0d169f78b93)
https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/6c47d055-b585-414b-8043-9ed5ed99b25c

</details>

## Changelog
:cl:Varo
add: Added a new drink to the coffee vendor: Bubble tea.
fix: Capitalized all names from the coffee vendor.
/:cl:

2023-10-26 07:19 UTC, EvilDragonfiend requested changes
I would want to see some effects on this, but it's fine anyway even if it has no special effect.

2023-10-26 07:19 UTC, EvilDragonfiend commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	chem_flags = CHEMICAL_BASIC_DRINK
```suggestion
	chem_flags = CHEMICAL_RNG_GENERAL | CHEMICAL_RNG_BOTANY | CHEMICAL_GOAL_BARTENDER_SERVING
```
It isn't a basic drink if you can't get it from bartender's chem machine.

2023-10-26 07:19 UTC, EvilDragonfiend commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	color = "#dfc7ab"
capitalize please

2023-10-26 10:20 UTC, ClownMoff commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	color = "#dfc7ab"
I capitalize what?

2023-10-26 10:23 UTC, ClownMoff commented
Regular tea doesn't have any effect AFAIC, idk what should I give the Bubbtle tea that isn't making it coffee 2.0

2023-10-26 10:57 UTC, EvilDragonfiend commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	color = "#dfc7ab"
DFC7AB

2023-10-26 10:58 UTC, EvilDragonfiend commented
> Regular tea doesn't have any effect AFAIC, idk what should I give the Bubbtle tea that isn't making it coffee 2.0

If you don't have any special idea, it's okay. It's not that big deal.

2023-10-26 19:30 UTC, ClownMoff commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	color = "#dfc7ab"
Done

2023-10-27 04:20 UTC, EvilDragonfiend approved these changes

2023-10-27 04:31 UTC, merged