Space Dolphins from YogStation two
BeeStation/BeeStation-Hornet pull request #1007
Opened 2019-12-18 10:05 UTC by Cenrus

See #997

## About this pull request

dolphins

## Why it's good for the game

dolphins

:cl: Altoids1
imageadd: Space dolphin sprites.
add: Space dolphins and a new event which causes them to spawn in pods around the station.
/:cl:

2019-12-18 10:11 UTC, Baldir-Odensen commented
Are they hostile to crabs?

2019-12-18 19:51 UTC, Cenrus commented
No, because crabs are good

2019-12-19 23:52 UTC, Wilchenx commented
@Kmc2000 please kill this sprite

2019-12-20 02:12 UTC, boodaliboo commented
not nice

2019-12-20 02:27 UTC, ike709 commented
@boodaliboo Well he did in the original PR that he closed, at least. Which he links in this PR.

2019-12-20 02:28 UTC, ike709 commented
Also he gave credit to Altoids in the CL as the author of the change.

2019-12-20 04:55 UTC, eLeCtrOssSnake commented
Uhhhhh, what? Dolphins?

2019-12-20 04:59 UTC, eLeCtrOssSnake commented
Space Carp, now we have Space Dolphins uh, ok.

2019-12-20 05:00 UTC, eLeCtrOssSnake commented
But where did they come from?

2019-12-20 07:46 UTC, boodaliboo commented
> Also he gave credit to Altoids directly in the CL as the author of the change.

i know im just having fun

2019-12-20 16:57 UTC, eLeCtrOssSnake requested changes
Express your changes in a half-formal way, not "fun stuff don't touch"

2019-12-20 16:57 UTC, eLeCtrOssSnake commented on code/modules/mob/living/simple_animal/hostile/retaliate/dolphin.dm
> +	return TRUE	//No drifting in space for space dolphins!	//original comments do not steal //Too late.
What are these comments though? I think they aren't required

2019-12-20 16:57 UTC, eLeCtrOssSnake commented on code/modules/events/dolphin_migration.dm
> +//DOLPHIN PORT WOOOOOO
I think this ain't required too.

2019-12-20 16:57 UTC, eLeCtrOssSnake commented on code/modules/mob/living/simple_animal/hostile/retaliate/dolphin.dm
> +	pass_flags = PASSTABLE //secretly a tactical dolphin buff.
This is useless too.

2019-12-20 18:01 UTC, ike709 commented on code/modules/events/dolphin_migration.dm
> +	announceWhen	= 3
Bad whitespace

2019-12-20 18:03 UTC, ike709 commented on code/modules/mob/living/simple_animal/hostile/retaliate/dolphin.dm
> +		for(var/mob/living/simple_animal/hostile/carp/C in view(src, 10))
🤔

2019-12-20 18:04 UTC, ike709 commented on code/modules/mob/living/simple_animal/hostile/retaliate/dolphin.dm
> +	faction = list("dolphin")//why do carps not attack dolphins again? //i dunno now they do
So dolphins attack carp but carp don't attack dolphins...?

2019-12-22 00:19 UTC, Cenrus commented
Ready now.

2020-01-06 19:02 UTC, merged