Shadow Sect
BeeStation/BeeStation-Hornet pull request #10087
Opened 2023-10-24 14:36 UTC by ro5490

## About The Pull Request

A new sect dedicated to the expansion of darkness and shadows.
Race conversion to shadowperson
Shadow Obelisks that spread darkness
Altar spreads darkness

Gain Favor by putting the Obelisks in dark places, or feeding the altar flashlights.
Obelisks will automatically accrue favor, and is the main source of favor.
You start with 100 favor so you can summon your first Obelisk.

Rites - 
"Obelisk Manifestation" - 100 Favor
-Summons a Shadow Obelisk to help spread darkness.

"Shadow Expansion" - 175 Favor
- Increases the range of the darkness spread from the altar and Obelisks

"Shadowperson Conversion" - 500 Favor
- Self explanitory

...
Thats about it for now, I'll think up more interesting things eventually
Most of the original code is by DingoDongler and their Dark City sect

## Why It's Good For The Game

More sects good
Halloween shadow people sect, its hard for them to live on-station with all the lights

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/17776299/ff38fe89-9246-4b32-9ab7-6264ede15d46)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/17776299/75618561-d4ff-49de-9646-8b7d9bf924c7)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/17776299/69410762-4d79-421c-832f-cdb024dafafa)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/17776299/f65d378d-524c-4857-b06c-dae044aa8bb4)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/17776299/4c7b27a2-9ba4-4775-a18c-b4125f9c4616)

![favorgain](https://github.com/BeeStation/BeeStation-Hornet/assets/17776299/5f0f0bd4-6ce7-41ec-8627-9f3f203315b1)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/17776299/577152bd-cef2-4dae-957b-004915ab3a22)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/17776299/de48b7bd-2db3-4c67-8dae-983a5cb31427)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/17776299/19c1f393-0db3-460c-bdd1-99a55e997022)

(this was cut and edited so it wouldnt be forever, but essentially shows the spread range)
![spread](https://github.com/BeeStation/BeeStation-Hornet/assets/17776299/41b420ad-e9b1-42a6-ae77-f7860146f622)

</details>

## Changelog
:cl:
add: Shadow Sect - Expand the darkness across the station, and convert people to the dark.
add: Shadow Obelisk for the sect that eminates dark light
add: Shadow-Person race change rite on the altar, for the shadow sect
add: New Altar sprite
/:cl:

2023-10-24 22:32 UTC, EvilDragonfiend commented
🔑 I am sorry but I should put this.
While having more sects is cool, this sect gives a very shittery reason why chaplain would darken the whole station even if the space law restricts them to contain it in the chapel.
I wouldn't allow this to be in the game because of the general player behaviour. I will lift my key if you can make chaps can access this sect by unusual ways (i.e. being antag chaps, a chaplain being shadowpeople already, shadow sect unlocking tome from somewhere, admin interaction, or and so on)

2023-10-24 22:55 UTC, ro5490 commented
> 🔑 I am sorry but I should put this. While having more sects is cool, this sect gives a very shittery reason why chaplain would darken the whole station even if the space law restricts them to contain it in the chapel. I wouldn't allow this to be in the game because of the general player behaviour. I will lift my key if you can make chaps can access this sect by unusual ways (i.e. being antag chaps, a chaplain being shadowpeople already, shadow sect unlocking tome from somewhere, admin interaction, or and so on) so that people can tolerate that as it won't be introduced often.

Totally understandable, some others have already raised concerns about this so I'm implementing two main things here (excluding the two new rites that are in-progress)
This, for obvious reasons
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/17776299/33b9ad6e-f0b7-404e-b36b-67238cca86d8)
 and, if I can figure out how exactly, I'm planning on having a % chance of the sect appering in the list at all, but, gotta figure out how to do that first lmao

2023-10-25 02:19 UTC, ro5490 commented
Currently just building in a if species is shadow, then unlock sect
but brain hurty

2023-10-25 03:39 UTC, EvilDragonfiend commented
> Currently just building in a if species is shadow, then unlock sect but brain hurty

# TGUI part

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/b8a4fdd6-394f-45cb-80a5-b89dd9561d7c)

# generate_available_sects()

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/645c7288-4e9b-4d7c-b5dc-d817c5f2f74a)

there is `GLOB.religious_sect`. Replace for each loop in this proc using the glob, and adds a new proc to each sect datum `/proc/is_available()`

```dm
/datum/religion_sect/proc/is_available(mob/user)
// put don't call parent thing here
    return TRUE // basically all available

/datum/religion_sect/shadow/is_available(mob/user)
    if(!isshadowling(user))
        return FALSE
    return TRUE
````

2023-10-25 03:47 UTC, ro5490 commented
> > Currently just building in a if species is shadow, then unlock sect but brain hurty
> 
> # TGUI part
> 
> # generate_available_sects()
>  
> there is `GLOB.religious_sect`. Replace for each loop in this proc using the glob, and adds a new proc to each sect datum `/proc/is_available()`
> 
> ```dm
> /datum/religion_sect/proc/is_available(mob/user)
> // put don't call parent thing here
>     return TRUE // basically all available
> 
> /datum/religion_sect/shadow/is_available(mob/user)
>     if(!isshadowling(user))
>         return FALSE
>     return TRUE
> ```

So the issue is, that `easy_access_sect` gets set, and `generate_avaliable_sects()` doesnt get called, so I've been implementing a different route that should allow for "Requirements" per sect to actually unlock them-

```
/// Select the sect, called from [/datum/component/religious_tool/proc/AttemptActions]
/datum/component/religious_tool/proc/select_sect(mob/living/user, path)
	if(!ispath(text2path(path), /datum/religion_sect))
		message_admins("[ADMIN_LOOKUPFLW(usr)] has tried to spawn an item when selecting a sect.")
		return
	if(user.mind.holy_role != HOLY_ROLE_HIGHPRIEST)
		to_chat(user, "<span class='warning'>You are not the high priest, and therefore cannot select a religious sect.</span>")
		return
	if(!user.canUseTopic(parent, BE_CLOSE, FALSE, NO_TK))
		to_chat(user, "<span class='warning'>You cannot select a sect at this time.</span>")
		return
	var/mob/living/carbon/human/testsubject
	var/datum/religion_sect/pathed = path
	if(user == testsubject)
		if(testsubject.dna.species.id == pathed.req_species)
			pathed.starter = TRUE
			pathed.sect_requirements = "Unlocked"//////////////////////////////// work on this path shit ugh
			to_chat(user,"<span class='big notice'>Congratulations, you've unlocked [pathed.name]!</span>")
	if(!pathed.starter)
		to_chat(user, "<span class='warning'>You cannot select this sect until you complete its requirements.</span>")
		return
	if(GLOB.religious_sect)
		return
	GLOB.religious_sect = new path()
	for(var/i in GLOB.player_list)
		if(!isliving(i))
			continue
		var/mob/living/am_i_holy_living = i
		if(!am_i_holy_living.mind?.holy_role)
			continue
		GLOB.religious_sect.on_conversion(am_i_holy_living)
	easy_access_sect = GLOB.religious_sect
	after_sect_select_cb.Invoke()```
However I'm running into runtime issues where This or similar happens
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/17776299/6e63ff84-3720-4930-913e-2310cfa3dafc)
 and I've been trying to sortit for about 4 hours now lmao

2023-10-25 03:51 UTC, ro5490 commented
// Need to fix religious_tool.dm between line 122 and 154 - gotta figure out a fix for that runtime

2023-10-25 03:57 UTC, EvilDragonfiend commented
oh, actually I misunderstood the sect glob thing.
here's instruction.

1. declare `GLOBAL_LIST_EMPTY(religion_sect_datums)` in somwher. preferably in religion tool dm.
2. go to `global_lists.dm`, and do the thing here
```dm
/proc/init_religion_sects()
	for(var/path in subtypesof(/datum/religion_sect))
		var/datum/religion_sect/each_sect = new path()
		GLOB.religion_sect_datums += each_sect
```

2023-10-25 03:59 UTC, EvilDragonfiend commented
so, `for(var/path in GLOB.religious_sect)` was a wrong suggestion. It had to be a list that's initialized from somehow.

2023-10-25 04:18 UTC, EvilDragonfiend requested changes
Don't forget the solution I wrote above. `generate_available_sects()` needs a new global list datum for sects.

2023-10-25 04:18 UTC, EvilDragonfiend commented on code/datums/components/religious_tool.dm
> +		return
no, no, you can handle that in `generate_available_sects()` (but I suggested something wrong before.) Revoke this part fully.

2023-10-25 04:18 UTC, EvilDragonfiend commented on code/modules/religion/religion_sects.dm
> +	var/req_species = "Unlocked"
We don't need this. remove these.

2023-10-25 04:18 UTC, EvilDragonfiend commented on code/modules/religion/religion_sects.dm
> +/datum/religion_sect/proc/on_select(atom/religious_tool, mob/living/user)
Revert these changes.

2023-10-25 04:18 UTC, EvilDragonfiend commented on code/datums/components/religious_tool.dm
> +		sect["req"] = initial(not_a_real_instance_rs.sect_requirements)
remove this

2023-10-25 04:18 UTC, EvilDragonfiend commented on code/datums/components/religious_tool.dm
> +		data["req"] = easy_access_sect.sect_requirements
remove this

2023-10-25 04:26 UTC, EvilDragonfiend commented
Feel free to ping in discord if you still have a trouble

2023-10-25 17:00 UTC, ro5490 commented
Still unsure what I'm meant to be doing with the new Global list, and  `generate_available_sects()` 
I've added the `/is_available` proc to `/datum/religion_sect`, removed the things you mentioned, and added the `is_available` to the shadow sect
where/how should I be referencing the new Global list, because as far as I could tell from testing, `generate_available_sects` doesnt get called because `easy_access_sect` gets set and used instead

2023-10-26 02:35 UTC, ro5490 commented
tried 
```
        var/datum/religion_sect/checks = path
        if(checks.is_available())
```
which triggered 
```
/datum/component/religious_tool/proc/perform_rite(mob/living/user, path)
    if(!ispath(text2path(path), /datum/religion_rites))
        message_admins("[ADMIN_LOOKUPFLW(usr)] has tried to spawn an item when performing a rite.")
        return
```
Also, the list seems to default to showing the debug/base sect

2023-10-26 03:16 UTC, EvilDragonfiend requested changes, later dismissed

2023-10-26 03:16 UTC, EvilDragonfiend commented on code/datums/components/religious_tool.dm
> +	for(var/path in GLOB.religion_sect_datums)
```suggestion
	for(var/datum/religion_sect/each_sect in GLOB.religion_sect_datums)
		var/path = each_sect.type
```

2023-10-26 03:16 UTC, EvilDragonfiend commented on code/datums/components/religious_tool.dm
> +		if(easy_access_sect.is_available())
```suggestion
		if(!each_sect.is_available())
			continue
```

2023-10-26 03:16 UTC, EvilDragonfiend commented on code/datums/components/religious_tool.dm
> +					continue
You don't need this.
point of `is_available()` is doing this for each sect.

2023-10-26 03:16 UTC, EvilDragonfiend commented on code/__HELPERS/global_lists.dm
> +	init_religion_sects(GLOB.religion_sect_datums)
```suggestion
	init_religion_sects()
```
You don't need to send an augment.

2023-10-26 04:34 UTC, EvilDragonfiend commented
Since the sect is now only limited to specific cases, I lift my key.

2023-10-26 05:13 UTC, ro5490 commented
All set and ready for review(s) and hopefully approval before halloween

2023-10-26 06:05 UTC, EvilDragonfiend commented
Since I am heavily involved in the PR at this point, I'll avoid approving this to avoid a possible misunderstanding that It doesn't need any further review.

2023-10-28 00:44 UTC, ro5490 commented
Time to fish for reviewers and someone to merge ;-;
Hoping this can get added before the halloween species get taken out again

2023-10-29 16:11 UTC, Rukofamicom approved these changes
Not my area of expertise, but code seems fine to me. 

Given the heavy restriction of access (outside of halloween anyway) I think this is fine to merge as-is with the potential for tweaks later if something overpowered comes out of this.

2023-10-29 16:22 UTC, merged