Ports Nekomimetic (felinid language) from /TG/
BeeStation/BeeStation-Hornet pull request #10105
Opened 2023-10-29 23:56 UTC by ClownMoff

## About The Pull Request

Felinid language 

## Why It's Good For The Game
It's so bad it's good. And every non human race should have IMO it's own language

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/1ea5baec-87d2-4318-81af-775a3518380c

<details>

## Changelog
:cl: Varo
add: felinid language
/:cl:

2023-10-29 23:57 UTC, Rukofamicom commented
I approved this PR being made, with no guarantee that it would be merged.

2023-10-29 23:58 UTC, DrDuckedGoose commented
Don't take my ``f`` language key!
Truly the felind agenda.

2023-10-30 00:00 UTC, EvilDragonfiend requested changes
Don't give such name to this language. Give it something better or I will key it.

2023-10-30 00:18 UTC, EvilDragonfiend requested changes

2023-10-30 00:18 UTC, EvilDragonfiend commented on code/modules/language/nekomimetic.dm
> +	)
I am fine with felinid saying such weird syllables but the current pool shows too felinid-meme at high possibility. Adding more japanese-like syllables to lower awkward combination.
For example, having more syllables like `"itai", "omae", "akaiku"` bla bla would be more acceptive, and I hope that'll be less awkward. Such things shouldn't happen that often. It should come unexpectedly then strike you.

2023-10-30 01:42 UTC, itsmeow commented
Felinids in their current state are slightly modified humans. Why would they have a culture and language entirely separate from humans. We can assume most felinids are first-generation, that being, they used genetic mutation to get their felinid features rather than being born with it. Genetic research is relatively new.

Adding a unique culture/language to felinids is nonsensical within this context. This is the type of thing that needs hundreds of years to naturally form in the real world, at most, this advanced genetic research has existed for 50-100 years.

2023-10-30 08:46 UTC, Tyranicranger4 commented
This PR is in conflict with how we've enforced R1 (You Must Roleplay) in a handful cases. Felinid/owo speak - or whatever else you'd call this has, at times, been considered too out-of-character and memey when overused; people have been warned for it, and people have been banned for it. Best case scenario this adds absolutely nothing of value, worst case scenario it's actively detrimental to immersion.

2023-10-30 09:05 UTC, PowerfulBacon requested changes
Make the language syllables not annoying/LRP/memey

2023-10-30 11:10 UTC, Rukofamicom commented
> Felinids in their current state are slightly modified humans. Why would they have a culture and language entirely separate from humans. We can assume most felinids are first-generation, that being, they used genetic mutation to get their felinid features rather than being born with it. Genetic research is relatively new.

I will use this to block you from saying I can't merge felinids into humans if it's being used to prevent felinids from being split further from humans.

2023-10-30 11:12 UTC, Rukofamicom commented
> Make the language syllables not annoying/LRP/memey

I second this, but with more specifics:
Remove every nya and meow from the list.

If it looks like japanese gibberish it's good, if it looks like nyas and meows it's bad.

2023-10-30 11:12 UTC, Rukofamicom requested changes
> Make the language syllables not annoying/LRP/memey

I second this, but with more specifics:
Remove every nya and meow from the list.

If it looks like japanese gibberish it's good, if it looks like nyas and meows it's bad.

2023-10-30 11:28 UTC, ClownMoff commented
Don't key it! I will change it this afternoon

2023-10-30 11:32 UTC, ClownMoff commented
> Adding a unique culture/language to felinids is nonsensical within this context. This is the type of thing that needs hundreds of years to naturally form in the real world, at most, this advanced genetic research has existed for 50-100 years.

Saying a language can't form in 50-100 years is wrong. Also lore reasons for a game with limited lore don't make much sense to me

2023-10-30 23:49 UTC, ClownMoff commented
![imagen](https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/fc04ad27-1f5b-4655-be87-e159fa8f7cbf)


Every single cringe uwu owo reference has been removed (Except neko because I think it's pretty obvius the word representing felinids whould be in the language). Now. Do we have a problem with stuff like "sensei" or "sakura"?

2023-10-31 10:44 UTC, ClownMoff commented
https://cdn.discordapp.com/attachments/565330972707651584/1168862377064804422/Desktop_2023.10.31_-_10.40.34.03.mp4?ex=65534eeb&is=6540d9eb&hm=6794354ab83ccaf1d7214d99256cc4f07d0ce4731cba09db360ccba4a6ebc55c&

2023-11-01 18:25 UTC, llol111 commented
One of the worst PRs i have seen in a long time
Lets make the species known for being annoying and cringe (rightfully or not) even more cringe and annoying, big brain time

2023-11-01 19:15 UTC, ClownMoff commented
Random japanese words arent cringe. It doesnt have the nyaa stuff no more

2023-11-01 21:57 UTC, Fronsis commented
> > Random japanese words arent cringe. It doesnt have the nyaa stuff no more
> 
> It absolutley is my dude, get real. Maybe the maintainers will change their minds now that you've removed the worst of the worst, but this is still incredibly cringe and not in line with what i'd like for the roleplay on bee as an admin. Just thinking about all the catpeople puking their japanese gibberish all over common, eugh.

I'm not a fan of cat people in general but.. it's not that different to  when they start spamming moffic, oozeling, IPC, etc the only difference is that you can kinda see the words and have a direct association with japanese, which it's already the lore of catpeople, on the others it just looks strange because it's made up words that are inspired on some languages (i forgot which ones were used for moffic for example) but i'm sure someone native from those countries might go ???? everytime the radio gets spammed with moffic

And even if they do spam it, there's a crime for that and they can be charged with it, i'd rather have them saying random japanese words or made up japanese words than them continue with *licks themselves loudly in the mic.

Or.. just nuke the felinids

2023-11-01 22:16 UTC, ClownMoff commented
^^^^^^^^^^^^^^^^

2023-11-02 00:31 UTC, EvilDragonfiend commented
> ^^^^^^^^^^^^^^^^

> Or.. just nuke the felinids

this? :trollface:

2023-11-02 01:25 UTC, EvilDragonfiend commented
🔑 
Okay, I am sorry to close this with all given change requests, but I really don't think it's going to work in our community.
I would likely accept if the decryption part is more complex than this simple, which means I don't think I will accept this port.

I am really fine with felinids having their own language, but I don't like the original idea of this port.
So, I am denying this because it's a port with cringe contents, not because felinids get their own language.
You'll need to give them properly dedicated language rather than this that's made with cringe intent.

2023-11-02 01:25 UTC, closed without merging

2023-11-02 01:41 UTC, ClownMoff commented
https://cdn.discordapp.com/attachments/528596617641852928/928031818052173835/1984.mov