Fixes radio channels defaulting to common when no encryption key
BeeStation/BeeStation-Hornet pull request #10129
Opened 2023-11-02 04:22 UTC by BeeLover66

## About The Pull Request

When using a radio headset, if no encryption key was installed, the headset would transmit to its frequency (common channel by default) no matter the channel code (:e, :m, :n...) used. This PR makes it so the behaviour is the same as when an encryption key is installed, which is not transmitting at all if the channel is invalid.

## Why It's Good For The Game

It makes no sense for headsets to work differently if there is or isn't an encryption key installed. This can also cause problems in cases where a civilian crewmember (assistant, chaplain, curator...) has a traitor uplink in their headset, where they would transmit the password over common when unlocking their uplink.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/78232749/8e4f7b6e-ecaf-4b20-a6ed-a82b1a3c591a

</details>

## Changelog
:cl:
fix: Radio channels no longer always default to common when no encryption key is installed
/:cl:

2023-11-02 04:26 UTC, EvilDragonfiend requested changes
Good change, but I think it should send a simple warning message that you can't access a channel.

2023-11-02 05:44 UTC, BeeLover66 commented
> Good change, but I think it should send a simple warning message that you can't access a channel.

Done, including a condition for the uplink channel since the frequency isn't actually used as a radio channel.

2023-11-02 06:24 UTC, EvilDragonfiend approved these changes

2023-11-03 00:11 UTC, Rukofamicom commented
I think you just solved the mystery I couldn't so long ago. 

Before the bounty for removing common I tried to do it myself, but I couldn't find why or where the equipment was defaulting to the common channel when no keys were present.

2023-11-04 03:03 UTC, merged