Squidstyle
BeeStation/BeeStation-Hornet pull request #1014
Opened 2019-12-19 00:39 UTC by AsciiSquid

## About The Pull Request

Adds new customization options for squid people in the form of three new face styles.

## Why It's Good For The Game

Squid Gang Squid Gang

## Changelog
:cl:
add: Added squid face customization
/:cl:

2019-12-19 00:43 UTC, hackerjsimon commented
yes also give martial arts

2019-12-19 02:19 UTC, ike709 approved these changes

2019-12-20 19:19 UTC, eLeCtrOssSnake approved these changes

2019-12-27 02:58 UTC, ike709 commented
Conflicts.

2019-12-27 08:15 UTC, MarkSuckerberg requested changes
Fix the conflicts, then it'll be fine.

2020-01-02 22:39 UTC, ATH1909 commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +/datum/sprite_accessory/squid_face/ilithid
"illithid" is spelled with two "l"s, not one "l"
(don't forget to update the other mentionings of the word "illithid"!)

2020-01-05 02:36 UTC, ike709 commented
I don't expect this to be finished but I'll give it the benefit of the doubt and just mark it as stale for now.

2020-01-06 19:03 UTC, ike709 commented
Stale.

2020-01-06 19:03 UTC, closed without merging