BoxStation Chemistry and Armory small tweaks
BeeStation/BeeStation-Hornet pull request #10175
Opened 2023-11-12 17:07 UTC by ClownMoff

## About The Pull Request
This PR tweaks Boxstation chemistry around to add a door to access chemistry from the lobby. This PR also replaces the 2 windoors in the armory for airlocks.

## Why It's Good For The Game
BoxStation is a product of it's time. To access chemistry, you have to do a super uncomfortable walk inside medbay to get to chemistry every single time. That will be no longer the case! And for the armory, it's good for the game and players that the access to one of the most important areas in the game isn't protected by 2 small glass windoors (not even reinforced) that can be easily broken.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

![imagen](https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/b64df548-e78b-439a-83d9-eb850365d3c3)

</details>

## Changelog
:cl: Varo
add: A front desk facing the hallway in chemistry
tweak: Changes chemistry layout to add a new door.
/:cl:

2023-11-15 18:46 UTC, Rukofamicom commented
Not gonna review the mapping changes directly but I approve the gameplay impact these changes will have from the screenshots shown.

2023-11-18 14:20 UTC, PestoVerde322 requested changes
![immagine](https://github.com/BeeStation/BeeStation-Hornet/assets/75247747/4abca3e3-97dc-4f00-b73e-3a67d74824b1)
the power cable is not connected. (Hid the machines for clarity sake)

![immagine](https://github.com/BeeStation/BeeStation-Hornet/assets/75247747/7fac0c9f-d3ba-4799-9143-f4423c8734ee)
Redundant button for shutters.

2023-11-18 14:28 UTC, Rukofamicom commented
Are there shutters over the new windows?

2023-11-19 11:19 UTC, ClownMoff commented
Yes

2023-12-01 18:44 UTC, PowerfulBacon commented
Note a huge fan of the chemistry layout, I'd rather have the door up north and the desk on the left.

Armoury has a light inside of a door.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/2057b2ac-515d-4091-8839-54f4de846587)

2023-12-15 14:16 UTC, ClownMoff commented
The desk on the hallways??

2024-01-13 00:44 UTC, itsmeow commented
Frozen by genpop

2024-03-06 12:58 UTC, closed without merging