Adminsay color is now choices instead of color pick
BeeStation/BeeStation-Hornet pull request #10171
Opened 2023-11-12 05:03 UTC by EvilDragonfiend

## About The Pull Request
Adminsay color is now choices instead of color pick
* closes #10170
* a player chat color pick is bad. chat color should be standised.

## Why It's Good For The Game
bad chat readability bad

## Testing Photographs and Procedure

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/79898096-ee4e-42c9-b736-8112eceac3ed)

## Changelog
:cl:
code: Adminsay color is now choices instead of color pick
code: added cfc color defines.
/:cl:

2023-11-12 05:05 UTC, EvilDragonfiend commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/admin.tsx
> +    },
OOC chats should have this too, but I have no idea how I can make a module of this. I hate this.

2023-11-12 08:09 UTC, Tyranicranger4 commented
No fun allowed.

2023-11-12 08:59 UTC, Fronsis commented
Uhh why are you closing the kilo map pr? Typo i guess

2023-11-12 09:10 UTC, EvilDragonfiend commented
> Uhh why are you closing the kilo map pr? Typo i guess
> 
> #10159 this one i guess

oopsie accidentally wrote a wrong one. thaks

2023-11-12 10:39 UTC, PowerfulBacon commented
Theres probably better ways to do this, like allowing any colour but inverting it if the contrast against the background is too low.

2023-11-12 12:20 UTC, EvilDragonfiend commented
I am not certain if there's any way to adjust your color value dynamically.

2023-11-12 17:40 UTC, Rukofamicom commented
Add an accessibility option to override custom chat colors instead, let the people who like custom colors have and use them.

2023-11-12 17:42 UTC, Rukofamicom requested changes
🔑 

If you're struggling to see colors because of your dark/light mode differences, make an accessibility option rather than taking away customization from others. Add an option that overrides custom colors with a color of your choice.

2023-11-12 17:50 UTC, EvilDragonfiend commented
> 🔑
> 
> If you're struggling to see colors because of your dark/light mode differences, make an accessibility option rather than taking away customization from others. Add an option that overrides custom colors with a color of your choice.

That defeats the point of asay color.

2023-11-13 00:07 UTC, Rukofamicom commented
It's better than forcing someone else to use a color they don't like as much. 
If you don't like the color they picked you should be changing it only for yourself.

2023-11-13 00:32 UTC, EvilDragonfiend commented
> > That defeats the point of asay color.
> 
> Not any moreso than this PR does right now. If you have a problem with someone else's color it should only be changed for you rather than forcibly restricting others' choices.
> 
> We like the colors we have picked.

Yes, I know people like to pick the colors they like, but what you suggested with the key totally defeats the point of that.
The current design is to show "your color" to people. I am really not against this. The bad design here is that the color value is applied 100% to the system no matter how other people's background setting. The ideal solution is adjusting the value automatically by which background theme you're using, but I don't think that's possible.

and what you suggested is setting "a color of a chat" overriding which color you have. It's more destructive change. It's a different topic. If that option exists, what's the point of asay color picking?

another solution is to have 2 color settings for asay, but it's also needed thing to ooc chat (and perhaps more). This means doubled option for a single preference which requires a user to care how those look like in both of background themes.


Well, back to the main, I'd consider a way to adjust values dynamically based on a user's currently used background, but I really don't think that's possible for how the code works. It's the issue of the system design, not the user's behavior.
asay is a better place to start the approach rather than ooc, but actually ooc is where a solution is highly required. Imagine someone uses black font color. They might think their words are well visible if they think people only use light theme, but it's extremely disrupting to dark theme users.


By writing this by time, I realised that I didn't specify where the issue comes exactly.
The issue doesn't come from how user picks a color. It comes the game uses two themes, and that makes user's custom color an issue. `<font color='color_thing'>` isn't really compatible well with how TGUI chat works. That's why I implemented cfc colors with BB PR at first.

and for now, this is the solution as far as I can think and suggest.

2023-12-15 10:02 UTC, PowerfulBacon commented
This is admin only and I don't think any of the admins will want this. If you want to implement a seperation between light mode and dark mode asay colour then feel free to re-open.

2023-12-15 10:02 UTC, closed without merging