mass qdel proc to replace qdel_in(), batching all qdel timer into a single timer
BeeStation/BeeStation-Hornet pull request #10181
Opened 2023-11-15 03:00 UTC by EvilDragonfiend

## About The Pull Request
mass qdel proc to replace qdel_in(), batching all qdel timer into a single timer

Bacon didn't like #10178
but I don't like this in fact

## Why It's Good For The Game
performacne

## Testing Photographs and Procedure

Mainly the same to
* #10178

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/0d3dcc45-16ad-451e-bbb1-d87b3a1bf3d2)

## Changelog
:cl:
code: qdel_in() no longer uses addtimer() for each item to qdel. It sends an item to a list with scheduled time assoc item list.
/:cl:

2024-05-08 08:34 UTC, PowerfulBacon commented
Not a huge fan of this PR, seems like unnecessary jank to automate bad code.

2024-05-08 08:45 UTC, EvilDragonfiend commented
> Not a huge fan of this PR, seems like unnecessary jank to accomodate bad code, if something wants to delete 100000 items in 1 tick, then it should handle that internally.

It wouldn't be 100,000 items in a tick, but `qdel_in()` itself is already expensive because it uses `addtimer()`, but also there's no way to handle this internally because `qdel_in()` is massively used in everywhere.

2024-06-17 16:00 UTC, PowerfulBacon requested changes
This idea is okay, but it has no way to deal with object deletions and the implementation of timers under the hood is actually pretty efficient and effectively is just looping through a list anyway. I don't think this is necessary and I'm not convinced that this will provide large performance improvements.

The idea behind the PR is something that I spent a day coding before realising that the timer implementation was already really good for dealing with a lot of timers and that actually testing for improvement is very difficult.

2024-06-17 16:00 UTC, PowerfulBacon commented on code/__HELPERS/qdel.dm
> +		target_entry.len-- // fun fact: this removes the last item from the list. convenient.
What's the point of altering the size of the list? Just do a for loop

2024-06-17 16:00 UTC, PowerfulBacon commented on code/__HELPERS/qdel.dm
> +/proc/qdel_timer_cancle(datum/item, timer_key)
This is not how you spell cancel

2024-06-18 00:45 UTC, EvilDragonfiend commented
> This idea is okay, but it has no way to deal with object deletions and the implementation of timers under the hood is actually pretty efficient and effectively is just looping through a list anyway. I don't think this is necessary and I'm not convinced that this will provide large performance improvements.

The issue doesn't come from how SStimer is coded. The issue comes from how the timer system is used to qdel massive amount of stuff. For example, lighting flickering is one of examples that spams qdel timer.

2024-07-30 18:52 UTC, PowerfulBacon commented
The biggest difference isn't performance, its that the subsystem can't be TICK CHECKED mid-execution which will result in things being deleted on the same tick (rather than being deferred by timers) but it will also allow the subsystem to overrun its tick allocation to do that

2024-08-10 17:45 UTC, Rukofamicom commented
> the subsystem can't be TICK CHECKED mid-execution

Nope 🔑

2024-08-10 17:45 UTC, closed without merging