Adds Atmos Devices to Meta Chapel
BeeStation/BeeStation-Hornet pull request #10228
Opened 2023-11-26 23:47 UTC by Programs-The-Station

## About The Pull Request

Adds Vents and Scrubbers to Meta Chapel

## Why It's Good For The Game

Atmos devices in my atmos simulator? Shocking!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

**Tiles removed to show piping**

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/d467d2f8-62c8-4c3f-aa8e-9f9e093607c1)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/ff22cc3e-17d0-4554-9345-26b4e0fcea2b)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/68aec863-5087-4d76-96f0-302f84892bee)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/58a50eeb-3e38-45f3-b815-d809f9941f87)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/8aa775fe-03ed-4b5e-8bd2-008a99b1dd75)

</details>

## Changelog
:cl:
fix: NT Atmospherics Division have corrected the lack of atmospheric devices in Meta Chapel
/:cl:

2023-11-26 23:48 UTC, Tsar-Salat commented
> ## About The Pull Request
> Adds Vents and Scrubbers to Meta Chapel

add 'closes #prnumber" so it closes the issue you made

2023-11-26 23:53 UTC, Programs-The-Station commented
Yea, realized I forgot that right after hitting the submit button.

Oddly, I also didn't touch any area markers or APCs, yet the Map Merge tools added some of those changes.

2023-11-27 05:42 UTC, HowToLoLu reviewed
The looks like the apcs and stuff *have* been touched somehow, and there's a bunch of typeless areas now. I'd double check the map file.

2023-11-27 05:42 UTC, HowToLoLu commented on _maps/map_files/MetaStation/MetaStation.dmm
> +/area)
Strange for this to be like this... did you touch the areas

2023-11-27 05:42 UTC, HowToLoLu commented on _maps/map_files/MetaStation/MetaStation.dmm
> +/area)
Same here

2023-11-27 05:42 UTC, HowToLoLu commented on _maps/map_files/MetaStation/MetaStation.dmm
> +/area)
And here...

2023-11-27 05:42 UTC, HowToLoLu commented on _maps/map_files/MetaStation/MetaStation.dmm
> +/area)
Here too....

2023-11-27 05:42 UTC, HowToLoLu commented on _maps/map_files/MetaStation/MetaStation.dmm
> +/area)
And here.

2023-11-27 09:57 UTC, PestoVerde322 requested changes
Yep, something defineley went wrong with the zoning here:

![immagine](https://github.com/BeeStation/BeeStation-Hornet/assets/75247747/63982113-69d0-4af5-9448-ca86e9db5441)

2023-11-28 01:07 UTC, Programs-The-Station commented
Fixed the areas. First mapping PR, so figuring out the toolchain. I think I did accidentally delete the objects, probably when I was using my track pad.

2023-11-28 22:03 UTC, PestoVerde322 approved these changes
Now it's good ot go, approved.

2023-12-01 08:11 UTC, merged