Ports enhanced Reflector TGUI menu from aetherstation
BeeStation/BeeStation-Hornet pull request #10248
Opened 2023-12-01 05:14 UTC by Tsar-Salat

Ports:
- https://github.com/AetherStation/AetherStation13/pull/243

## About The Pull Request

Ports the TGUI menu

## Why It's Good For The Game

Reflectors are very irritating to aim going entirely off their rotation value

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/4ced4ae0-a508-4a3c-a2f8-6cf25130f367

</details>

## Changelog
:cl: rkz, Sparkezel, helg2
add: Adds advanced TGUI menu to Reflectors, from Aetherstation. Determine rotation with no flaws or guesswork!
/:cl:

2023-12-01 11:43 UTC, EvilDragonfiend approved these changes

2023-12-02 07:47 UTC, PowerfulBacon requested changes

2023-12-02 07:47 UTC, PowerfulBacon commented on code/game/objects/structures/reflector.dm
> +			var/new_angle = params["rotation_angle"]
This should do text2num and ensure that a number was passed to it

2023-12-02 07:47 UTC, PowerfulBacon commented on code/game/objects/structures/reflector.dm
> +			var/new_angle = rotation_angle + params["rotation_angle"]
This should also ensure that the passed value is a number and not something like a string

2023-12-02 14:33 UTC, Tsar-Salat commented on code/game/objects/structures/reflector.dm
> +			var/new_angle = params["rotation_angle"]
Does this work? 

I read text2num documentation and saw it spits out a null if a non-numeric value is inputted, so if it nulls, it just returns false & shoots a stack_trace.

Let me know if theres a better way to do this.

2023-12-02 14:33 UTC, Tsar-Salat commented on code/game/objects/structures/reflector.dm
> +			var/new_angle = rotation_angle + params["rotation_angle"]
see above

2023-12-03 11:14 UTC, PowerfulBacon requested changes

2023-12-03 11:14 UTC, PowerfulBacon commented on code/game/objects/structures/reflector.dm
> +				setAngle(SIMPLIFY_DEGREES(new_angle))
```suggestion
			if(isnull(new_angle))
				stack_trace("A string was inputted to [src] instead of a number while rotating, somehow.")
				return FALSE
			setAngle(SIMPLIFY_DEGREES(new_angle))
```
Redundant check, since you already check it before. Also I would recommend using the proc log_href_exploit for these kinds of href errors.

2023-12-03 22:39 UTC, itsmeow commented on code/game/objects/structures/reflector.dm
> +			var/new_angle = params["rotation_angle"]
just do `CRASH()` instead of `stack_trace()`. or just return false, we don't need to generate runtimes for an href exploit

2023-12-03 22:58 UTC, Tsar-Salat commented on code/game/objects/structures/reflector.dm
> +			var/new_angle = params["rotation_angle"]
ok

2023-12-03 22:59 UTC, Tsar-Salat commented on code/game/objects/structures/reflector.dm
> +				setAngle(SIMPLIFY_DEGREES(new_angle))
commited

2023-12-05 07:43 UTC, PowerfulBacon commented on code/game/objects/structures/reflector.dm
> +				CRASH("A string was inputted to [src] instead of a number while rotating, somehow.")
This isn't an error, this is an expected possibility resulted with TGUI exploitation. log_href_exploit is the correct logging for this.

2023-12-05 07:46 UTC, Tsar-Salat commented on code/game/objects/structures/reflector.dm
> +				CRASH("A string was inputted to [src] instead of a number while rotating, somehow.")
I got told by another maintainer to do CRASH() in the first review. The feedback is getting confusing.

I will change it to log href

2023-12-05 08:52 UTC, PowerfulBacon commented on code/game/objects/structures/reflector.dm
> +				CRASH("A string was inputted to [src] instead of a number while rotating, somehow.")
Crash should be used for exceptions which are things that should never happen. Since this is player input then we are expecting them to be wrong here, but the only way they can be wrong is if a href exploit is used. Log href exploit should be used in these cases, but be careful not to send the actual player input into the href exploit log otherwise the exploit will be sent to all admins and executed.

2023-12-05 08:54 UTC, PowerfulBacon commented on code/game/objects/structures/reflector.dm
> +			var/new_angle = params["rotation_angle"]
> just do `CRASH()` instead of `stack_trace()`. or just return false, we don't need to generate runtimes for an href exploit

@itsmeow Crash is what generates runtimes, stack_trace internally is just a proc that calls crash and abuses byond's error handling behaviour in order to not stop execution of the proc, compared to crash with ceases execution of the proc.

2023-12-05 09:35 UTC, PowerfulBacon commented on code/game/objects/structures/reflector.dm
> +				setAngle(SIMPLIFY_DEGREES(new_angle))
```suggestion
			if(new_angle == null)
				log_href_exploit(usr, " inputted a string to [src] instead of a number while interacting with the calculate UI, somehow.")
				return FALSE
			setAngle(SIMPLIFY_DEGREES(new_angle))
```

2023-12-10 08:44 UTC, PowerfulBacon approved these changes

2023-12-10 08:51 UTC, merged