The Dish-Drive no longer disembowels its stock parts upon attack_hand
BeeStation/BeeStation-Hornet pull request #10250
Opened 2023-12-01 07:01 UTC by Tsar-Salat

## About The Pull Request

Title.

closes #10249 

## Why It's Good For The Game

Unintended behavior.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/0ea2bc0a-fa67-4718-a805-1304f667c323

</details>

## Changelog
:cl: rkz
fix: Fixes Dish-drives dispensing their stock parts upon attack_hand
/:cl:

2023-12-09 07:46 UTC, PowerfulBacon requested changes
Remove from the list when exited it called, I'd something inside the dish drive is deleted then the reference should be cleared

2023-12-09 07:47 UTC, PowerfulBacon commented
Also the CL says the same thing twice, it should just be a simple description of the changes rather than any IC/in lore description with references

2023-12-15 18:15 UTC, Eric-01 commented
I'm not sure if this is related or not, but monkeys can dismantle sleepers from the inside as well.

2023-12-19 08:34 UTC, PowerfulBacon approved these changes

2023-12-19 08:42 UTC, merged