Gutlunch - Simplemob Coolification
BeeStation/BeeStation-Hornet pull request #10295
Opened 2023-12-09 17:39 UTC by Nakalon

## About The Pull Request

So I was playing and a chaplain produced a Gutlunch.
I tried feeding it raw meat because that's what was written in the description and couldn't.
Was very upset.

So I decided to make Gutlunches able to eat meat.
But then I realized, I could go much farther.
Much, much farther.

Made sprites for the baby and male gutlunch and dead sprites for all of them, so they wont just disappear on death anymore.
I gave them each their own type of udder, which means they create different chemicals.

Babies cant be milked, liquify what they eat and store the blood.
They will grow up only when their sac is full of blood.

Males produce mercury, acid and a tiny bit of blood.

Females produce the same milk they did before.

Gutlunches will now properly display the overlay for when they're full.

When killed they will pop like a balloon, releasing the contents of their udders and spawning gibs.

They can be butchered into crabmeat.

They will no longer continue to eat if their udder is full.

In the future I would like to have them lay eggs and other things but that's outside the scope of this PR.

## Why It's Good For The Game

Gutlunches were moderately forgotten.
This modernizes some of their code, fixes some things that were meant to work but didn't and reinforces sexual dimorphism.
Also hopefully gives the little bugs some use and makes it more interesting to be a sentient one, hopefully.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/94647521/a7c90b1d-b05a-44ee-b1fc-39108aa3b8ec)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/94647521/2201d244-9f07-4b9a-a688-225459244470)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/94647521/e63aba33-5805-4193-9d70-4df858de4917)

Here you can see a full male Gutlunch being popped open.
Do note I have since then updated the gibbing animation.

https://github.com/BeeStation/BeeStation-Hornet/assets/94647521/88ebbe51-6279-497e-97e7-37b794220a57

Gutlunch genocide before I updated the gibbing.

https://github.com/BeeStation/BeeStation-Hornet/assets/94647521/1483af11-3f09-4893-bc25-b52ce647965e

This is with the new gibbing animation.

https://github.com/BeeStation/BeeStation-Hornet/assets/94647521/5e1f8bb1-16f8-4550-a197-9910d03548ec

</details>

## Changelog
:cl: PinkSuzuki
tweak: Tweaked Gutlunches, reinforced sexual dimorphism, allow them to eat meat and be butchered.
tweak: Male Gutlunches and Baby Gutlunches now have their own udders.
tweak: Gutlunches also now pop like a balloon when they die, releasing the content of their udders.
imageadd: Adds sprites for dead, Male and Baby Gutlunch.
fix: Gutlunch sacs now look bigger when they're full, as was intended.
code: Minorly tweaked some Gutlunch code
/:cl:

2023-12-10 00:07 UTC, Fronsis commented
The secret ashlizard buff?? But yeah iirc the Gutmobs, at least the couple on the ashlizard nest only feed of gibs, organs and limbs left by the sacrifices, but this seems cool!

2023-12-10 01:08 UTC, Nakalon commented
> The secret ashlizard buff?? But yeah iirc the Gutmobs, at least the couple on the ashlizard nest only feed of gibs, organs and limbs left by the sacrifices, but this seems cool!

yeah! It was meant to give it some flavor and make it so you can actually feed them with something more common!

2023-12-11 03:56 UTC, itsmeow requested changes

2023-12-11 03:56 UTC, itsmeow commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
> +	comp = GetComponent(/datum/component/udder)
holding references to a component like this is a bad idea

2023-12-11 03:56 UTC, itsmeow commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
> +		if(udder.reagents.total_volume < udder.reagents.maximum_volume)
you should use signals for something like this instead to replace the need for a reference.

COMSIG_IS_UDDER_FULL or something

2023-12-11 03:56 UTC, itsmeow commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
> +	chem_splash(get_turf(src), 1, list(udder.reagents))
instead, make a subtype of udder component that listens for death (via the signal) and spills the reagents. Or just add it to all udders

2023-12-11 14:25 UTC, Nakalon commented
I'm going to need help to adress these @itsmeow because I have no idea how to do that

2024-01-05 22:55 UTC, Nakalon commented
converting this to draft while I don't fix what need fixing

2024-04-21 13:11 UTC, Rukofamicom commented
This user has moved on from Bee and I don't believe this will be salvaged. Ping me if I'm mistaken.

2024-04-21 13:11 UTC, closed without merging