Fixes SM throwing runtime when a ghost examines SM
BeeStation/BeeStation-Hornet pull request #10303
Opened 2023-12-12 00:05 UTC by EvilDragonfiend

## About The Pull Request
Fixes SM throwing runtime when a ghost examines SM
Ghosts don't need examine check for this.

## Why It's Good For The Game
bug fix

## Testing Photographs and Procedure

It's a simple fix

## Changelog
:cl:
fix: Fixes SM throwing runtime when a ghost examines SM
/:cl:

2023-12-12 11:58 UTC, Rukofamicom approved these changes

2023-12-15 09:26 UTC, PowerfulBacon requested changes, later dismissed

2023-12-15 09:26 UTC, PowerfulBacon commented on code/modules/power/supermatter/supermatter.dm
> +		return .
If the runtime is thrown by mobs that don't have a mind, then check for the user not having a mind and not if they are an observer or not

2024-02-15 18:44 UTC, PowerfulBacon commented
@EvilDragonfiend

2024-02-16 12:30 UTC, EvilDragonfiend commented
Sorry. Forgot to do this

2024-02-20 19:46 UTC, itsmeow approved these changes

2024-02-20 19:53 UTC, merged