Advanced stack_trace, better runtime view
BeeStation/BeeStation-Hornet pull request #10305
Opened 2023-12-12 03:41 UTC by EvilDragonfiend

## About The Pull Request
Code improverment to stack_trace, and runtime viewer.
* `stack_trace()` now needs 2 parameters. The first one is a unique key, the second one is actual message
  With this, stack_trace runtimes are no longer stacked together.
* Runtime viewer now tells how many times it happened.

## Why It's Good For The Game
Debugging qol

## Testing Photographs and Procedure

---------

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/b3c14a4f-1c30-49e8-8ad8-fd523f523800)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/dc14b7bd-85c1-43cc-b429-89b23d7ccd1e)

Organised v.s. Linear

-------------

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/74045697-b235-4c4a-8bb3-2608f75f56e6)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/2ff0db6a-d7ff-4a08-9db0-5d3bf44ed7ab)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/7cfc5b47-8e3b-45ea-b85c-4b5ab32b56b0)

----------

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/5e68adab-f323-4e15-bc79-90b60f7fc252)

standard runtime

## Changelog
:cl:
code: Improved stack_trace proc. It now needs 2 parameters. First one is a hint, and an id to stack together. Second one is the real crash message.
code: Runtime viewer now tells how many it happened.
/:cl:

2024-01-09 17:59 UTC, itsmeow requested changes
man there's a lot of these. I won't ask you to fix them all because I don't have time to find them all myself even, lol

2024-01-09 17:59 UTC, itsmeow commented on code/__HELPERS/mobs.dm
> +		stack_trace("mobs.dm/Init", "Warning: [src]([type]) initialized multiple times!")
is there not some way to get the current code file programatically? I feel that would make more sense in this case then requiring it to be manually specified

2024-01-09 17:59 UTC, itsmeow commented on code/__HELPERS/stack_trace.dm
> +// I hate to have this proc, but SHOULD_BE_PURE setting is angry without this
what?

2024-01-09 17:59 UTC, itsmeow commented on code/controllers/subsystem/movement/movement_types.dm
> +		stack_trace("movement_types.dm/1", "You tried to make a [moving.type] object move like a disposals holder, stop that!")
this can be a CRASH() with `. = FALSE`

2024-01-09 17:59 UTC, itsmeow commented on code/controllers/subsystem/processing/networks.dm
> +			stack_trace("networks.dm/3", "create_network: We only take text on [part] index [i]")
this can be a CRASH()

2024-01-09 17:59 UTC, itsmeow commented on code/datums/ai/_ai_controller.dm
> +				stack_trace("ai_controller.dm/1", "[pawn] wants to perform action type [current_behavior.type] which requires movement, but has no current movement target!")
CRASH()

2024-01-09 17:59 UTC, itsmeow commented on code/datums/ai_laws.dm
> +		stack_trace("ai_laws.dm/2", "AI law datum for [owner] has ignored Destroy() call; the owner variable must be cleared first!")
these both can be . = something, CRASH()

2024-01-09 17:59 UTC, itsmeow commented on code/datums/components/cult_ritual_item.dm
> +		stack_trace("cult_ritual_item.dm/1", "[type] - [cultist] attempted to scribe a rune, but did not have an associated [user_antag ? "cult team":"cult antag datum"]!")
all of these can be CRASH

2024-01-28 09:33 UTC, EvilDragonfiend commented
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/2ae2acda-fbd2-49d6-a8af-405e4aced0b9)

ye, it works

2024-01-29 01:28 UTC, EvilDragonfiend commented
will take a while. I didn't know __FILE__ and other macros were a thing lol

2024-01-29 04:25 UTC, EvilDragonfiend commented
Aww fuck... I thought I could use `__PROC__` but it was actually 515.
I am kinda pissed off for now to do this, so I will handle this later when we have 515...

2024-01-29 04:25 UTC, closed without merging