Finishes Newfood repathing, kills oldfood.
BeeStation/BeeStation-Hornet pull request #10332
Opened 2023-12-17 07:56 UTC by Tsar-Salat

## About The Pull Request

Fixes all instances of food not being accepted by vendors or any machine that was checking for the former typepath instead of the new one.

Replaces all remaining instance of the old food typepath with the new ones.

Removes all remaining customfood (Kebabs & Ashlander soups), all of which are to be readded in the next pr

Converts to newfood:
- snacks.dm
- snacks_other.dm
- snacks_vend.dm

Adds & adjusts protein values for all food in misc & snacks_vend

## Why It's Good For The Game

Newfood atomization

Its finally over.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Full conversion to the new food typepath
remove: removes all customfood, TBA in the next pr
fix: fixes all instances of machines checking for the old path instead of the new food path, incl. vendors & microwaves
tweak: converts misc.dm to use protein values
tweak: converts snacks_vend.dm to use protein values
/:cl:

2023-12-17 07:58 UTC, Tsar-Salat commented
Meat + Plants atomizations are approaching 3 & 1 month ages respectively, so I felt it prudent to just get this through the door.

Included are the commits from those prs, I will squash and rebase them out should either be merged.

2024-01-04 22:04 UTC, Tsar-Salat commented
Rebased to remove defunct pre-meat & pre-plants commits

2024-01-13 00:50 UTC, itsmeow commented
Can you fix all the UpdatePaths being reversed in all the newfood scripts?

2024-01-13 00:51 UTC, itsmeow commented on tools/UpdatePaths/Scripts/9951_NEWFOODmeats
> +/obj/item/food/spidereggsham : /obj/item/food/spidereggsham{@OLD}
this is a noop?

2024-01-22 19:01 UTC, Tsar-Salat commented
I hate my life

2024-03-03 05:44 UTC, Tsar-Salat commented
I'll keep this open for a bit longer

2024-03-03 21:29 UTC, Rukofamicom commented
Original PR author has deleted their account, impossible to reasonably give credit beyond linking the original PR

2024-03-03 21:37 UTC, Rukofamicom requested changes

2024-03-03 21:37 UTC, Rukofamicom commented on code/game/objects/items/food/snacks.dm
>  		/datum/reagent/consumable/maltodextrin = 2
Maltodextrin should be updated to 3, to keep it in line with the protein swap.

2024-03-03 21:43 UTC, Tsar-Salat commented on code/game/objects/items/food/snacks.dm
>  		/datum/reagent/consumable/maltodextrin = 2
```suggestion
		/datum/reagent/consumable/maltodextrin = 3
```

2024-03-03 21:50 UTC, Rukofamicom approved these changes

2024-03-03 21:57 UTC, merged