Ports the RBMK from NSV (for real this time)
BeeStation/BeeStation-Hornet pull request #10364
Opened 2023-12-20 21:51 UTC by XeonMations

## About The Pull Request

Adds in the RBMK nuclear reactor from NSV. (this time hopefully without pull breaking map changes)

All things are able to be ordered from cargo.

Wiki can be found here: https://wiki.beestation13.com/view/Guide_to_the_Nuclear_Reactor

(I accidentally created the wiki on the main wiki instead of a sandbox, I'm sorry)

RBMK Hum noise sourced from [here](https://www.youtube.com/watch?v=KNMU4575bMw), under CC BY 4.0 and edited by me.

## Why It's Good For The Game

More content for engineering!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/2d181621-f574-4d2d-8613-96c99216cce8)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/0fd41e2d-c8ec-4b18-9105-b4a649372b02)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/796dbead-8553-4dc5-a28a-9268346a8fc4)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/8a5d68e3-5de4-4605-a4ab-3bf78f2b61ff)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/6c0114fe-664a-4a6c-84e6-f0f261791c1e)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/02355081-754b-4454-94a1-f1b461175081)

</details>

## Changelog
:cl: XeonMations, Aramix, DungeonVR
add: Added the RBMK reactor, fuel rods and engine sealant, all orderable from cargo!
/:cl:

2024-05-17 04:43 UTC, BlueHNT commented
I fear what the people of bee will do with this. How their antags will inevitably abuse that nuclear fallout. This is going to be good.

2024-07-06 20:24 UTC, ClownMoff commented
I think the consequences of blowing up this shit are way to strong, it can fuck entire rounds to a point that is not funny at all

2024-07-07 08:25 UTC, EvilDragonfiend commented on code/modules/power/rbmk/_rbmk_defines.dm
> +#define REACTOR_DAMAGE_MAGIC_NUMBER 1.0056850991882220077025096652119341723277747452195921845851
as far as I know, Byond can't handle this long shit decimals. 
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/585034b6-0a28-4053-93e0-ac37cc99730d)

2024-07-07 12:43 UTC, MarkusLarsson421 commented
Allow items on top of it to be fried. I want my meat RBMK cooked.

2024-07-07 13:08 UTC, PestoVerde322 commented on code/modules/power/rbmk/_rbmk_defines.dm
> +#define RBMK_TEMPERATURE_OPERATING 640 //Celsius
Curious, but why not use kelvins?

2024-07-07 14:41 UTC, XeonMations commented on code/modules/power/rbmk/_rbmk_defines.dm
> +#define RBMK_TEMPERATURE_OPERATING 640 //Celsius
Helps with displaying correct temperatures, not like the reactor is going to be less than 0 either way

2024-09-13 19:38 UTC, PowerfulBacon commented
Not against this being merged, but I don't see the necessity for this feature nor the value that it actually brings.

2024-09-13 20:09 UTC, Therealdoooc213 commented
> Not against this being merged, but I don't see the necessity for this feature nor the value that it actually brings. We don't want to use this in place of the supermatter crystal which leaves it in a place where its going to be unmaintained and never used.

I don't get this, people aren't going to use a RBMK to replace a roundstart supermatter crystal, it's harder to get and its delamination effects are way worse

2024-09-14 09:02 UTC, MarkusLarsson421 commented
> We don't want to use this in place of the supermatter crystal which leaves it in a place where its going to be unmaintained and never used.

If it is hidden in some corner of the game, it will be unmaintained because no one will ever go to that corner and know of its existence. I would say we SHOULD allow the SM to be replaced with other engines if the situation desires it. Because then people will actually care for it and its functionality further into the feature. 

With how hidden Derelict Stations are, it is no wonder how unmaintained it is. Not because PRs are being shut down, but because no one knows of its existence to make the PRs to begin with.

2024-09-14 22:16 UTC, PowerfulBacon commented
A new mapping standard won't be set for stations to have their SM replaced with RBMK. We will suffer from having to maintain multiple engines, and the RBMK is not an appropriate option for a full SM replacement.

2024-09-23 20:14 UTC, Rukofamicom commented
I really love the RBMK, but I ultimately agree with Bacon.

I don't want to replace the supermatter crystals with it, and I don't believe this should be merged unless it is replacing them.

2024-09-24 19:45 UTC, Isaacnml commented
Please dont kill it, from initial thought it was supposed to replace the defunct antimatter reactor, which it does a pretty good job, never meant to replace the SM in any way and engineering desperately needs new content to well.. play around gameplay loop currently is really vague

It's a replacement incase the SM explodes, not a full replacement for the SM

2024-09-24 21:39 UTC, MarkusLarsson421 commented
Almost a year in development and now the close keys are coming in? Jesus Christ. A year of Xeons life wasted.

2024-09-25 06:55 UTC, XeonMations commented
> from initial thought it was supposed to replace the defunct antimatter reactor

But yes, the idea from the start was as a replacement for the now gone antimatter reactor.

As of current, if the SM explodes, the station only has solars as a power source unless they want to take a rather long time setting up a black hole (good luck with no power) or a tesla (Again, good luck without power).

Or engineering could just set up a second SM in the form of a shard, but I'm unsure if they'd put that much effort in before the shuttle is called.

2024-09-25 06:55 UTC, EvilDragonfiend commented
I am honestly fine with this, but I suppose we might need a kind of mapping tool to replace (or some ingame stuff to make a dedicated area quickly). Constructing a new engine for a whole round was tedious.

2024-09-25 06:56 UTC, XeonMations commented
> we might need a kind of mapping tool to replace (or some ingame stuff to make a dedicated area quickly). Constructing a new engine for a whole round was tedious.

Entirely fair, if wished, i am able to add one.

2024-09-25 07:08 UTC, EvilDragonfiend commented
> > we might need a kind of mapping tool to replace (or some ingame stuff to make a dedicated area quickly). Constructing a new engine for a whole round was tedious.
> 
> Entirely fair, if wished, i am able to add one.

not right now. we are in a mapping disaster rn.

2024-10-23 11:52 UTC, ClownMoff commented
> Not against this being merged, but I don't see the necessity for this feature nor the value that it actually brings. We don't want to use this in place of the supermatter crystal which leaves it in a place where its going to be unmaintained and never used.



> I really love the RBMK, but I ultimately agree with Bacon.
> 
> I don't want to replace the supermatter crystals with it, and I don't believe this should be merged unless it is replacing them.

This just reads as new content is le bad because it is. This isn't gonna replace the SM nor is what the PR attempted to, it's just another option for power. It looks like you guys would key a port of teslas and singulos if they weren't on the game already. Just give people more stuff to do. The server is getting stale. There aren't any big drops of content. We keep nerfing or removing shit and yet whenever anything different from the status quo attempts to get merged it's keyed. Either figure out what do you guys want BeeStation to be already or drop the "bloat" or "unnecesary" argument because while we keep waiting for that big BeeStation overhaul project ™️ it looks like nothing significant gets added to the game, but nerfs and removal keep going on. And this is not only me I'm talking I've seen enough people these last 2 day complaining about the state of the server and losing interest on the server and looking for alternatives, and a lot of complains came from the development sides of things. I will keep being here even though I feel what I do doesn't get appreciated because I like this community a lot, but I for sure will think twice before commiting to big projects if it's just gonna get keyed because "new content is bad because maybe it doesn't get used". I highly suggest you sit down, get your thoughts together as the development team and be trasnparent with the community with what you guys want BeeStation to be and what we can expect. I don't want to open NovemberStation PR after refining the map and seeing Ruko add a key 5 minutes later because urr "the map is not on space so maybe its too different". I want a clear direction or where we are going and what is expected of us. "Nothing is expected of you this is a open sourced project". Well, it doesn't look like it because you clearly have a bias on what to add and what to not add while we wait for this huge BeeStation big change and overhaul. You are on the verge losing old players that have poured heart and soul on this server over constant changes that are just "makes the game feel more tedious to play" while nothign new or refreshing gets added. There is no incentive from the development team to recruit new talent, no big projects that we can work on, no events, no nothing. Silence and waiting days, weeks or months for a review (I really understand we lack the manpower in maintenance) and then who knows, maybe a key because your new PR didn't allign with what we wanted to do.

2024-11-16 09:03 UTC, PowerfulBacon approved these changes
Eh whatever, this can replace the antimatter generator.

2024-11-21 11:32 UTC, EvilDragonfiend requested changes
Replace arbitrary names like R or N. It tells no context.

2024-11-22 05:29 UTC, EvilDragonfiend requested changes
Code looks alright as long as change requests are applied.

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_monitoring.dm
> +		next_stat_interval = world.time + 1 SECONDS //You only get a slow tick.
this can be cooldown macro.

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_monitoring.dm
> +		if(tempOutputdata.len > 100) //Only lets you track over a certain timeframe.
please replace len to length()

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +			to_chat(user, "<span class='warning'>[src] is already at maximum fuel load.</span>")
this len to length too please

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +			update_appearance()
```suggestion
			if(length(fuel_rods) == 0)
				activate(user) //That was the first fuel rod. Let's heat it up.
			else // Not the first fuel rod? Play the sound.
				playsound(src, pick('sound/effects/rbmk/switch1.ogg','sound/effects/rbmk/switch2.ogg','sound/effects/rbmk/switch3.ogg'), 100, FALSE)
			fuel_rods += attacked_item
			attacked_item.forceMove(src)
			update_appearance()
```

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +			if(critical_threshold_proximity <= 0.875*critical_threshold_proximity_archived)	//They might've stacked doafters
where did this `0.875` come from?
This should be a define macro.

also, why `0.5` too?

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +			critical_threshold_proximity = clamp(critical_threshold_proximity, 0, initial(critical_threshold_proximity))
```suggestion
			critical_threshold_proximity = clamp(critical_threshold_proximity - 10, 0, initial(critical_threshold_proximity))
```

and this 10 should be a macro. I know what this number means, but other code readers might not.
`#define SEALNANT_REPAIR_VALUE 10` like this?
or do `/sealant /var/repair_power = 10`, and `critical_threshold_proximity - sealant.repair_power`

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
at `power >= 20`, this 20 should be `#define SAFE_POWER_LEVEL 20` smh. I am not sure what's better name.

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +	return null
```suggestion
/obj/machinery/atmospherics/components/unary/rbmk/proc/get_held_buffer_item(mob/user)
	if(isAI(user))
		var/mob/living/silicon/ai/ai_user = user
		return ai_user.aiMulti.GetComponent(/datum/component/buffer)

	var/obj/item/held_item = user.get_active_held_item()
	var/found_component = held_item?.GetComponent(/datum/component/buffer)
	if(found_component && in_range(user, src))
		return found_component

	return nulll
```
If I understand this correctly, It should check `in_range` regardless of being cyborg or carbon whatever right?

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +	QDEL_NULL(src)
it's just `qdel`

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +	if(!length(fuel_rods))
```suggestion
	if(length(fuel_rods) == 0)
```
This reads better, I guess? nitpick.

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +		to_chat(user, "<span class='warning'>You cannot remove fuel from [src] when it is above 20% power.</span>")
reminder that this 20 needs a macro.

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +		return REACTOR_NOMINAL
```suggestion
	switch(get_integrity_percent())
		if(0 to REACTOR_MELTING_PERCENT)
			return REACTOR_MELTING
		if(REACTOR_MELTING_PERCENT to REACTOR_EMERGENCY_PERCENT)
			return REACTOR_EMERGENCY
		if(REACTOR_EMERGENCY_PERCENT to REACTOR_DANGER_PERCENT)
			return REACTOR_DANGER
		if(REACTOR_DANGER_PERCENT to REACTOR_WARNING_PERCENT)
			return REACTOR_NOMINAL
```
using switch is better when it is 0 to 100 condition.

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +		if(player_mob.get_virtual_z_level() == rbmkzlevel)
```suggestion
		if(compare_z(rbmkzlevel, player_mob.get_virtual_z_level())
```
This is a proper way to compare Zs. getting z value only tells the number, not checking if they're in the same z category. (i.e. station)

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +		if(src.get_virtual_z_level() == apc.get_virtual_z_level() && prob(70))
```suggestion
		if(prob(70) && compare_z(rbmkzlevel, apc.get_virtual_z_level())
```
reusing the variable `rbmkzlevel`.

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +		if(player_mob.get_virtual_z_level() == rbmkzlevel)
```suggestion
		if(compare_z(rbmkzlevel, player_mob.get_virtual_z_level())
```

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +			if(src.get_virtual_z_level() == nuclear_sludge_spawner.get_virtual_z_level()) //Begin the SLUDGING
```suggestion
			if(compare_z(rbmkzlevel, nuclear_sludge_spawner.get_virtual_z_level()) //Begin the SLUDGING
```

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_monitoring.dm
> +			if(user.get_virtual_z_level() == reactor_core.get_virtual_z_level())
```suggestion
		var/core_z_level = reactor_core.get_virtual_z_level()
		for(var/obj/machinery/atmospherics/components/unary/rbmk/core/reactor_core in GLOB.machines)
			if(compare_z(core_z_level , user.get_virtual_z_level())
```

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_monitoring.dm
> +				if(usr.get_virtual_z_level() != reactor_core.get_virtual_z_level())
```suggestion
			var/user_z_level = usr.get_virtual_z_level()
			for(var/obj/machinery/atmospherics/components/unary/rbmk/core/reactor_core in GLOB.machines)
				if(!compare_z(user_z_level, reactor_core.get_virtual_z_level())
```
I am not sure if doing `usr` is right here, but whatever. it won't be breaking the game...

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_parts.dm
> +		var/datum/component/buffer/heldmultitool = get_held_buffer_item(usr)
```suggestion
		var/datum/component/buffer/heldmultitool = get_held_buffer_item(user)
```
do not use `usr` when you can have `user`

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_parts.dm
> +	return null
```suggestion
/obj/machinery/computer/reactor/proc/get_held_buffer_item(mob/user)
	if(isAI(user))
		var/mob/living/silicon/ai/ai_user = user
		return ai_user.aiMulti.GetComponent(/datum/component/buffer)

	var/obj/item/held_item = user.get_active_held_item()
	var/found_component = held_item?.GetComponent(/datum/component/buffer)
	if(found_component && in_range(user, src))
		return found_component

	return nulll
```

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/fuel_rods.dm
> +		reactor_core.fuel_rods -= src
```suggestion
	if(istype(loc, /obj/machinery/atmospherics/components/unary/rbmk/core))
			var/obj/machinery/atmospherics/components/unary/rbmk/core/reactor_core = loc
		reactor_core.fuel_rods -= src
```

2024-11-22 05:29 UTC, EvilDragonfiend commented on code/modules/power/rbmk/fuel_rods.dm
> +	if(istype(reactor_core))
```suggestion
	// Rod conversion is moot when you can't find the reactor
	if(istype(loc, /obj/machinery/atmospherics/components/unary/rbmk/core))
		var/obj/machinery/atmospherics/components/unary/rbmk/core/reactor_core = loc
```

2024-11-23 11:04 UTC, EvilDragonfiend requested changes
Would be a final.

2024-11-23 11:04 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_monitoring.dm
> +			if(compare_z(core_z_level , user.get_virtual_z_level()))
```suggestion
		var/user_z_level = user.get_virtual_z_level())
		for(var/obj/machinery/atmospherics/components/unary/rbmk/core/reactor_core in GLOB.machines)
			if(compare_z(reactor_core.get_virtual_z_level(), user_z_level))
```
Sorry, my mistake. It's reversed.

2024-11-23 11:04 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_monitoring.dm
> +				choices += reactor_core
```suggestion
			var/user_z_level = usr.get_virtual_z_level()
			for(var/obj/machinery/atmospherics/components/unary/rbmk/core/reactor_core in GLOB.machines)
				if(!compare_z(reactor_core.get_virtual_z_level(), user_z_level))
					continue
				choices += reactor_core
```
Same mistake here too

2024-11-23 11:04 UTC, EvilDragonfiend commented on code/modules/power/rbmk/rbmk_procs.dm
> +				activate(user) //That was the first fuel rod. Let's heat it up.
```suggestion
			if(length(fuel_rods) >= 5)
				to_chat(user, "<span class='warning'>[src] is already at maximum fuel load.</span>")
				return FALSE
			else if(length(fuel_rods) == 0)
				activate(user) //That was the first fuel rod. Let's heat it up.
```
If multiple people trying this, It's possible to have +5 rods.

2024-11-23 16:22 UTC, EvilDragonfiend approved these changes
okay, we'll see how this goes.

2024-11-23 16:30 UTC, merged

2024-11-24 20:23 UTC, BarteG44 commented
YES YES YES YES