[WIP] server framework?
BeeStation/BeeStation-Hornet pull request #10413
Opened 2023-12-30 22:19 UTC by Dejaku51

## About The Pull Request
This PR makes it so servers (currently RnD and tcomms) generate heat and work with efficiency depending on their temperature

## Why It's Good For The Game
No more 4 part tcomms in random room without proper setup, tcomms cooling actually has sense now

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
refactor: Tcomms and RnD servers now generate heat and work with varying efficiency based on the temperature it is
tweak: Added cooling to tcomms in metastation
tweak: Added cooling to tcomms in kilostation
tweak: Added cooling to tcomms in radstation
code: changed typepaths of tcomms machines from /obj/machinery/telecomms to /obj/machinery/server/telecomms
code: Added starts_connected to portable atmos machines that will make it automatically connect to connector on the same tile when spawned
/:cl:

2023-12-31 01:45 UTC, Dejaku51 commented
TODO: convert RnD server to this

2024-01-02 17:15 UTC, EvilDragonfiend commented on code/__DEFINES/stat.dm
> +#define MAINT		(1<<2)		// under maintaince
since you're here fix the typo lol

2024-01-02 18:53 UTC, Dejaku51 commented on code/__DEFINES/stat.dm
> +#define MAINT		(1<<2)		// under maintaince
fixed

2024-01-04 11:16 UTC, Miliviu requested changes
Hi! I'm not a maintainer but I've checked the code and LGTM!

But I have a concern! I was testing the RnD Server Power consumption (And it works)
<details>
Before cool parts:

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/4594bf98-fd90-42dc-9242-c61196439cb4)

After cool parts:

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/8cf4466a-7b30-4361-9e9b-76a9eb907847)

</details>

But I couldn't upgrade the Servers, the only way it was to "destroy" the server and build it with new parts

<details>
Here, you can see I'm trying to deconstruct (or just open the latch with the screwdriver a turned off server and I can't 

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/3bcc80db-c30e-4582-99c6-313df4b27d29)
</details>

I'm not sure if this intended, if it is then I'd not see any issues with the PR :)

2024-01-04 11:22 UTC, BriggsIDP commented
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/107176252/30c17105-d241-48d1-9974-cf7fbeadfc79)
looks much nicer, tyty

2024-01-04 18:33 UTC, Dejaku51 commented
mean rnd servers in the commit guh

2024-01-04 18:41 UTC, Miliviu approved these changes
Yup! That should do it, LGTM!

2024-01-06 08:32 UTC, itsmeow requested changes
Please add an UpdatePaths script for the new servers. (in `tools/UpdatePaths/Scripts`)

2024-02-09 21:56 UTC, Dejaku51 commented
git is fuck

2024-02-09 21:56 UTC, closed without merging