Adds gene complexity to botany
BeeStation/BeeStation-Hornet pull request #10424
Opened 2024-01-05 21:08 UTC by ToasterBan

## About The Pull Request
Adds gene complexity, certain genes will add complexity to the plant, which will reduce from the total yield

## Why It's Good For The Game
certain traits are very powerful and I believe should be nerfed in their mass-producibility, the exact numbers of this however are  still a work in progress

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/54711687/5203a291-c5bf-452d-93c5-9a196ecf9f17)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/54711687/df3d71bb-39eb-4e0a-b276-7156300f5803)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/54711687/5c056c05-6214-4957-905e-a6db572ab706)

Unmodified plant:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/54711687/4cb86a39-4565-462b-9aed-c6121077c03f)

Modified plant:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/54711687/afd7def6-988a-4f3b-a383-ea59afc7659a)

</details>

## Changelog
:cl:
balance: Gene Complexity in botany
add: Certain trait genes in botany will have a complexity value
add: Every level of complexity a plant has, will reduce its yield by 1
/:cl:

2024-01-06 02:09 UTC, EvilDragonfiend requested changes
Need TGUI interface for complexity

2024-01-06 02:09 UTC, EvilDragonfiend commented on code/modules/hydroponics/seeds.dm
> +		return_yield -= complexity
I recommend rewriting the calculation of the whole proc returning yield. It will be easy.
1. should early return 0 if yield is 0 already. no need to calculate.
2. try to use `clamp(target_value, minimum, maximum)`

2024-01-06 12:07 UTC, EvilDragonfiend requested changes
The proc doesn't do early return 0

2024-01-06 12:10 UTC, BriggsIDP commented
What traits where you planning on adding complexity too?

2024-01-06 12:31 UTC, ToasterBan commented
> What traits where you planning on adding complexity too?

you can check in the changed files but currently (and probably not final, need more input from people):

- Electrical Activity 1
- Shadow Emission 1
- Bluespace Activity 1
- Densified Chemicals 2
- Perenial Growth 2
- Capacitive Cell Production 1
- Hypodermic Prickles 3
- Richer Juice 2

2024-01-06 14:01 UTC, BriggsIDP commented
Non github discussion would probably be best, my initial thoughts are that parental growth should not be complex as it is almost a prerequisite for doing botany, and that liquid content and gaseous composition should be added

2024-01-07 00:04 UTC, ToasterBan commented
converting to draft until I feel it is properly balanced

2024-01-08 15:58 UTC, closed without merging