Converts blob overmind shield to update_appearance
BeeStation/BeeStation-Hornet pull request #10450
Opened 2024-01-11 03:25 UTC by Tsar-Salat

## About The Pull Request

Converts blob overmind/shield to update_appearance

## Why It's Good For The Game

Apparently the air_update_turf code earned it some ire. This should be better.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/f5bfb6c5-7b84-4137-920f-c483ab800f50

</details>

## Changelog
:cl: rkz
code: converted blob shield code to update_appearance
/:cl:

2024-01-11 04:25 UTC, itsmeow approved these changes
yipeeee

2024-01-11 05:03 UTC, HowToLoLu commented on code/modules/antagonists/blob/structures/shield.dm
> +		air_update_turf(1, atmosblock)
`air_update_turf` doesn't take two arguments it only takes 1, no need to pass it `atmosblock`

2024-01-13 00:54 UTC, itsmeow requested changes
fix `air_update_turf` (and use TRUE instead of 1)

2024-01-13 00:57 UTC, Tsar-Salat commented on code/modules/antagonists/blob/structures/shield.dm
> +		air_update_turf(1, atmosblock)
```suggestion
		air_update_turf(TRUE)
```

2024-01-13 01:01 UTC, itsmeow approved these changes

2024-01-29 17:53 UTC, Penwin0 approved these changes

2024-01-29 18:13 UTC, merged