[BUG FIX] Fixed mapping error in Box Station detective's office.
BeeStation/BeeStation-Hornet pull request #10515
Opened 2024-01-21 10:07 UTC by JikkaJoestar

## About The Pull Request
A wall was previously missing in the Box Station detective's office, causing the room to be depressurized at roundstart. this PR fixes it.
This was created as a result of this bug report: https://github.com/BeeStation/BeeStation-Hornet/issues/10514

## Why It's Good For The Game

Suffocating at round start is bad. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/134568049/36922aaa-83ef-4844-962e-357116e29199)

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

2024-01-21 15:24 UTC, Crossedfall commented
You need to include a change log

2024-01-21 16:11 UTC, Tsar-Salat commented
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/4f8e5c0e-0888-4e11-9358-f63328bce741)

This is against mapping standards. All wallitems should be on a solid wall, not glass.

2024-01-21 17:40 UTC, MarkusLarsson421 commented
> This is against mapping standards.

Suffocating and depressurizing is already really, really bad.

Had Bombyx do this. lol
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/88c55f75-caef-4b82-bd91-6ca08f14ddcf)

2024-01-22 12:19 UTC, Rukofamicom requested changes
The placed wall needs to be a reinforced wall, not glass. 

Changelog must be filled out correctly, in this case it would look something like this:

```
:cl:
fix: Fixed a missing wall in Boxstation
/:cl:
```

2024-01-28 12:02 UTC, Penwin0 approved these changes, later dismissed

2024-01-28 15:04 UTC, Penwin0 commented
This can probably be closed

2024-01-28 16:51 UTC, Rukofamicom commented
This can definitely be closed, the same issue was resolved by another PR

2024-01-28 16:51 UTC, closed without merging