Screwdriver on Lathe - What she doin?
BeeStation/BeeStation-Hornet pull request #10539
Opened 2024-01-24 01:54 UTC by Nakalon

## About The Pull Request

Now you can put screwdriver in lathe.
Or beat lathe with screwdriver.
Life is fun

## Why It's Good For The Game

I want screwdriver in lathe.
Also if you aciddently printed lots of screwdrivers suddenly you have clutter you can't easily undo.

Screwdriver should go on lathe. Let me PUT IT IN THE LATHE.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/94647521/1f0260a3-6806-4923-80bc-fd24ee7f6978

</details>

## Changelog
:cl: Solene Yoon
tweak: Attacking a lathe with a screwdriver on help intent now recycles the screwdriver.
tweak: Attacking a lathe with a screwdriver on harm intent now beats the lathe's ass.
/:cl:

2024-01-24 06:48 UTC, JixS4v commented
How do you open the lathe then, to hack it?

2024-01-24 06:49 UTC, JixS4v commented
Making something intent based is hell

2024-01-24 07:27 UTC, PowerfulBacon requested changes
This would require disarm or grab intent to actually open the panel of the lathe, behaviours should be limited to other intents & harm. If anything then the intents should be
- Harm to insert the screwdriver into the lathe
- Other intends to open the panel of the lathe

Either way its going to cause some inconsistencies in the controls if we allow both

2024-01-24 09:24 UTC, Fronsis commented
Maybe.. Help: open the panel, as it's consistent with machinery interactions with screwdriver
Harm: Attack it
Disarm/shove: Recycle?

Unless you wanna go the cool dude way of Throw, similar to how you can land trash on the trash-chute if you throw it from distance(but this would work being on melee/standing next to it) so you just throw it and get a flavor text saying it perfectly went into the machine and is now recycled!

I'm liking the last one it has flavor and realistically no one will throw  a screwdriver to cause harm to the machinery.

Specially because the help=open panel is just so standard for everything and it will cause more annoyances and accidents than the very very rare case of throwing it and accidentally losing it.

2024-01-24 11:27 UTC, Nakalon commented
> This would require disarm or grab intent to actually open the panel of the lathe, behaviours should be limited to other intents & harm. If anything then the intents should be
> 
> * Harm to insert the screwdriver into the lathe
> * Other intends to open the panel of the lathe
> 
> Either way its going to cause some inconsistencies in the controls if we allow both

okay I'll do this instead.

I still do sincerely hope people end  up recycling their screwdriver by mistake as much as I do the other tools :trolled:

2024-01-24 11:28 UTC, Nakalon commented
> Maybe.. Help: open the panel, as it's consistent with machinery interactions with screwdriver Harm: Attack it Disarm/shove: Recycle?
> 
> Unless you wanna go the cool dude way of Throw, similar to how you can land trash on the trash-chute if you throw it from distance(but this would work being on melee/standing next to it) so you just throw it and get a flavor text saying it perfectly went into the machine and is now recycled!
> 
> I'm liking the last one it has flavor and realistically no one will throw a screwdriver to cause harm to the machinery.
> 
> Specially because the help=open panel is just so standard for everything and it will cause more annoyances and accidents than the very very rare case of throwing it and accidentally losing it.
> 
> Though Harm intent as Bacon said could work, 99% sure no one tries to bash a lathe with a screwdriver to.. destroy it

The idea is cool but it would take a lot of work for me to do.
I'm a lazy peon and just want to put my damn SCREWDRIVER IN LATHE PLEASE GOD

2024-01-24 21:19 UTC, MarkusLarsson421 commented
Honestly... just throw it in disposals or hit it with a toolbox like the rest of us.

2024-01-25 01:51 UTC, Nakalon commented
> This would require disarm or grab intent to actually open the panel of the lathe, behaviours should be limited to other intents & harm. If anything then the intents should be
> 
> * Harm to insert the screwdriver into the lathe
> * Other intends to open the panel of the lathe
> 
> Either way its going to cause some inconsistencies in the controls if we allow both

I just realized I have absolutely no idea how to do this.

2024-01-26 15:28 UTC, Nakalon commented
Closing this as I can't easily find a solution as to how to overide the attack on HARM intent and I'm not that passionate about this.

2024-01-26 15:28 UTC, closed without merging