Makes zombie infection a 50% chance on hit.
BeeStation/BeeStation-Hornet pull request #10544
Opened 2024-01-26 15:42 UTC by JixS4v

## About The Pull Request
Makes it so the zombie hand infects on a 50% chance instead of being a one hit infection.
## Why It's Good For The Game

Zombie infections are much more difficult to fight off now that the tumor deals brain damage, this makes it so getting hit once by a zombie doesn't mean you're instantly infected.

## Testing Photographs and Procedure
Literally just a probability early return, untested.

## Changelog
:cl: Ratón
tweak: Zombies infect on a 50% chance instead of instantly infecting on hit.
/:cl:

2024-01-26 15:43 UTC, Dejaku51 commented
ided?

2024-01-26 15:46 UTC, JixS4v commented
> ided?
Bold of you to assume I play the game.

2024-01-26 15:52 UTC, JixS4v commented
So apparently the game already had this, changed it to 80% minus armour so that unarmored chaps still get a chance

2024-01-26 15:52 UTC, Tsar-Salat requested changes

2024-01-26 15:52 UTC, Tsar-Salat commented on code/modules/zombie/items.dm
> +	var/base_infection_chance = 80
Document.

2024-01-26 15:53 UTC, JixS4v commented on code/modules/zombie/items.dm
> +	var/base_infection_chance = 80
In a comment?

2024-01-26 15:54 UTC, JixS4v commented on code/modules/zombie/items.dm
> +	var/base_infection_chance = 80
Sure, I guess

2024-01-26 16:13 UTC, Tsar-Salat commented on code/modules/zombie/items.dm
> +	var/base_infection_chance = 80
Thats not an autodoc you goober.

2024-01-27 14:03 UTC, Rukofamicom approved these changes

2024-01-27 14:14 UTC, merged