Customize your milk!
BeeStation/BeeStation-Hornet pull request #10555
Opened 2024-01-28 17:07 UTC by Tsar-Salat

## About The Pull Request
Removes hardcoding of the reagent in the milkable(udder) component

Adds snake udder "venom gland".

Fixes a few bad qdels with the component

Converts VV Component list to tgui because It's tedious to scroll through.

## Why It's Good For The Game

Modular things like components should be, y'know, modular.

This was requested by players in the discord. I think its funny & adds more stuff to ghetto chemistry/traitoring.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/68d8d334-895e-47bd-869a-80f79ef2e386)

</details>

## Changelog
:cl: rkz
code: Dehardcodes milkable component reagent
add: Snakes can now be milked for venom. They don't seem to mind.
fix: fixed bad qdels with milkable component
admin: converted VV component list input to TGUI
/:cl:

2024-01-28 19:32 UTC, PerishedFraud commented
What immediately came to mind is that you should be able to milk spiders too (namely HoS' pet).

Other than that, very cute PR.

2024-01-30 12:08 UTC, Rukofamicom approved these changes, later dismissed
This looks good to me. 

I second the idea of making HoS pet milkable for spider venom, but that can/should go in its own PR. Also enjoy the cursed pet " ' Spider ' " code.

2024-01-31 01:55 UTC, Rukofamicom requested changes
Why is there no credit for the original source of the majority of this PR's code?

2024-03-03 15:49 UTC, Rukofamicom approved these changes

2024-03-03 15:56 UTC, merged