Six new maintenance maps!
BeeStation/BeeStation-Hornet pull request #10571
Opened 2024-02-03 19:27 UTC by XeonMations

## About The Pull Request

This PR was made during the maintenance mapping marathon with @MarkusLarsson421 and @BriggsIDP 

## Why It's Good For The Game

More maintenance maps are good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/5e252e15-370a-4f30-8232-6433ef22cd5f)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/e1efa099-8c9f-45fb-841f-3a64da9a2c63)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/cc975209-6e38-4261-ab95-8e18b1e9a87b)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/7f3c38db-d1d0-4625-8158-b56bf2f58146)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/c5d4f284-b532-41b1-9929-7b7c9130f150)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/ac80d050-36d8-475f-b2d2-d7ede339cb39)

</details>

## Changelog
:cl: XeonMations
add: Added six more maintenance rooms!
/:cl:

2024-02-04 14:07 UTC, St0rmC4st3r commented
The shotgun is a toy, good.

2024-02-06 10:57 UTC, MarkusLarsson421 commented
Remember to add your maps to `code/modules/mapping/random_rooms.dm` so they actually spawn in.

2024-02-07 21:26 UTC, spockye requested changes
ALL your rooms are missing areas! Please add them <3

it should be:    /area/template_noop

2024-02-07 21:26 UTC, spockye commented on _maps/RandomRooms/10x10/sk_rdm170_laser_tag.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/e43d096b-a5f8-40fc-ab90-cb922c78ed62)

you NEED to give the Maint room the proper area

2024-02-07 21:26 UTC, spockye commented on _maps/RandomRooms/10x5/sk_rdm171_dead_bodies.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/ae9e1f93-66a7-431d-9fb3-f06128a811a1)

this might be a lil silly. Mabye try to make it more cult-y? add some tables, more varied
(again give it the proper area)

2024-02-08 10:19 UTC, PestoVerde322 approved these changes

2024-02-15 18:59 UTC, merged