Maintenance Mapping Marathon
BeeStation/BeeStation-Hornet pull request #10579
Opened 2024-02-06 12:14 UTC by MarkusLarsson421

## About The Pull Request
Adds a ton of more maintenance rooms.

## Why It's Good For The Game
Adds a ton of more variety and some opportunities to acquire things for antagonists.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>
Fast Maints

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/be37ce9d-861b-4bb4-8b71-9268ce6eeb13)

Vault storages

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/c9b0899d-b429-47e2-b177-76aa6d4295c9)

Captain quarters

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/40a09be9-4fb1-4552-bc2c-c524cf838b7b)

Bathroom

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/117ea154-b833-48dd-83ad-4c13a9fdb1fe)

Workout

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/d24d0809-f7b7-4342-aa9c-879ff7c6a8b5)

Blob (it won't spread)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/9ce79eb0-f6ce-4bd1-a65d-87e18d7a08e6)

Autolathe (minus all those boards)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/d350d19d-bdad-4566-bdb0-1457a6405cd2)

Mechbay now has a chance of spawning a ripley

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/f5e4dfdc-dacf-414a-b33c-6cbf369e2e02)

Organ harvesting room

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/c881a459-5d22-444e-a324-7b967480015f)

AI upload

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/5549a47b-a59f-48c2-9d6f-fe70f9e8d9ca)

</details>

## Changelog
:cl: Markus Larsson
add: Added almost 20 new maintenance rooms.
tweak: Added a chance for a ripley to spawn.
tweak: Added a sniffer to the Robotics maintenance room.
tweak: [BoxStation] Rearranged Cargo-Engi maints to not disrupt maintenance rooms.
tweak: [CorgStation] Rearranged Bridge-Science maints to not disrupt maintenance rooms.
/:cl:

2024-02-07 21:20 UTC, spockye requested changes
A lot of nice rooms!

2024-02-07 21:20 UTC, spockye commented on _maps/RandomRooms/10x10/rdm_dorms.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/5c9d0b4b-5f01-4674-a46e-c3007a645907)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/0a3ed7a6-c8a3-4ca0-a926-8321ad1ed99e)

pretty sure this will open and close normal dorms aswell. Give them more personalized ID's!

2024-02-07 21:20 UTC, spockye commented on _maps/RandomRooms/10x5/rdm_solars.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/a476b381-a0ac-4e25-bbfb-9c145dfe8ce2)

space tiles. This intended? 
i'd recommend covering them up in any case

2024-02-07 21:20 UTC, spockye commented on _maps/RandomRooms/5x4/rdm_captain_quarters.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/c0d520e0-c55a-47f0-851f-625ea2dba7fc)

The captain can spawn here. Probably a bad idea

also, adding another, possibly multiple Nuke pinpointers into the server balancing miiiight be a bad idea

2024-02-07 21:22 UTC, MarkusLarsson421 commented on _maps/RandomRooms/5x4/rdm_captain_quarters.dmm
The locker is locked to the Captain so only the Captain or an antag could reasonably get a hold of it. I'd like to hear from more people what they think of it.

2024-02-08 13:45 UTC, spockye commented on _maps/RandomRooms/5x4/rdm_captain_quarters.dmm
anyone could break it open with an axe, or some acid!

2024-02-08 15:34 UTC, MarkusLarsson421 commented on _maps/RandomRooms/5x4/rdm_captain_quarters.dmm
It'd fall under powergaming unless they got a really, really good reason for wanting to open up a locked locker belonging to the Captain.

2024-02-10 05:57 UTC, Fronsis commented on _maps/RandomRooms/5x4/rdm_captain_quarters.dmm
> It'd fall under powergaming unless they got a really, really good reason for wanting to open up a locked locker belonging to the Captain.

The thing is that no one would really ''know'' and think this is just a maintenance room loot.. it would make sec officers to prioritize hauling it back to bridge/brig and having a third pinpointer does bring balancing issues, i've seen rounds where an antag manages to get ahold of the two pinpointers and hide them just so they can keep the disky and it would be curious if said antag took an hour to get both HoS and Captain pinpointer only for him to get busted by a random third one

As for Captain spawning there, it could be fun, but that locker certainly shouldn't have cap gear on it, maybe some dark reference with a paper and some misc non power gamer stuff or that will immediatly get that player in trouble with sec

2024-05-27 09:29 UTC, MarkusLarsson421 commented on _maps/RandomRooms/5x4/rdm_captain_quarters.dmm
Removed the pin pointer, keeping the Captain spawn unless others also thinks it is a bad idea.

2024-05-27 09:32 UTC, Fronsis commented on _maps/RandomRooms/5x4/rdm_captain_quarters.dmm
> Removed the pin pointer, keeping the Captain spawn unless others also thinks it is a bad idea.

Oh i forgot that we had all those neat MMM entries, what about the gear? Remember Captain armor's one of the best in the game, so you should purge most of the items and slap a "ha gottem" of your liking with troll items

As for the spawn eh, up to the maintainers, as long as there's no bad rng where they can spawn trapped inside walls with no welders they should be fine

2024-05-27 09:33 UTC, MarkusLarsson421 commented on _maps/RandomRooms/5x4/rdm_captain_quarters.dmm
Its a reskinned closet. lol
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/e9837b4f-42e7-4d70-8062-8b8fce17fece)

2024-05-27 09:34 UTC, MarkusLarsson421 commented on _maps/RandomRooms/5x4/rdm_captain_quarters.dmm
It will only have one Security maintenance item.

2024-06-17 16:25 UTC, PowerfulBacon reviewed
Does maintception actually work properly?
Also remove the blob room and I'm fine with this.

2024-06-23 09:52 UTC, PestoVerde322 approved these changes

2024-06-25 08:21 UTC, merged