Bioscanners, Health analyzer scarcification, and more
BeeStation/BeeStation-Hornet pull request #10584
Opened 2024-02-08 10:33 UTC by TsunamiAnt

## About The Pull Request
### WIP This does the following:
**New Machine:**
- Adds a new machine, the Bioscanner. A sleeper-esque machine into which you put people, and after a small scanning duration it spits out a full body scan. It will do between 8 and 80 rads during the scan, at random.
- Bioscanners take scanner components and capacitors, upgrading the scanners decreases radiation, all the way to a max of 20 per scan, upgrading capacitors shortens scanning time, from 30 seconds at tier 1, to 7 seconds at tier 4.
- When not scanning, the bioscanner still reports basic damage types like the sleeper does.
- These will be placed as follows: likely 2 in every medical department, plus 1 for the brig phys.

**Health Analyzer Changes:**
- Advanced Health Analyzers have been soft-removed, and are only available to CC personnel or admins. The CMO starts with a regular one.
- While they work instantly, and are portable, Health Analyzers now do 50-100 rads per use. To stop murders, they will refuse to function if the patient is over 100 rads.
- All instances of the health analyzers existing roundstart will be removed, leaving only the CMOs locker.
- Medbots and similar will now use health sensors instead in their construction.
- Health Analyzer tech is now tier 5 and can only be found via research disks.
- PDAs will no longer be capable of doing healthscans. They can still do Reagent Scans.
- Borgs and PAIs are not affected.

<details>
<summary>TODO: DO NOT MERGE THIS TILL THIS IS ALL DONE I SWEAR TO GOD.</summary>

- [ ] Figure out how machines are powered and implement it to the bioscanner. I am talking people getting locked in depowered scanners and having to claw their way out of them, etc. Also different power uses during scanning and idling.
- [ ] Figure out how to make the button on the AI grey out when the scanner is scanning, for style.
- [ ] Finish the actual purpose of the thing, the printout.
- [ ] Have the techweb not mysteriously nonfunctioning
- [ ] Iron out bugs
- [ ] Map the thing into all the maps.

</details>

## Why It's Good For The Game
### So many reasons. Analyzers are such an integral part of the game. Here is some of what I think:

1. The entire medical department is an anomaly. It is a roundstart-optimized autism fortress with no RP in mind. All of the tools are collected in one big room and people just walk into it going "I am hurt." -get grabbed by a doc, wordlessly healed, then thrown out. This is not adressed in this PR. But something may be on it's way, depending on my motivation.
2. The health analyzer is the single most powerful tool in the game. It is a one click cheat to medicine. Really think about how absurd a handheld full body scanner really is. And there are no drawbacks to using it at all, you just keep smashing the mouse button and get a live feed of every single process that can happen with someone. It trivializes medicine to an insane degree.
3. **Medbay could work comfortably without a health analyzer at all, the bioscanner isn't even needed either. There are methods and tools available to diagnose basically all ailments in a much cooler way already. Check blood and heart with the stethoscope, eyes and mouth with the penlight. Use the diagnosis feature of the medhuds(Yes that exists, bet you didn't know. Why would you, You have analyzers.) It's insane.**

Disclaimer: Some hyperbole may have been used. Do not rip me apart for silly stuff that is obviously silly.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Empty
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/153900881/51219649-96bd-4f39-af53-bb05c6775cb4)

Occupied and interface
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/153900881/12bd12fe-d354-46ed-a114-6488c52758f9)

Scanning...
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/153900881/776c546e-f58a-4935-9a44-36ed83901a1a)

WIP: The resulting report, or what it's gonna look like somewhat once I am done doing the darn thing....
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/153900881/b132e53c-2be8-43d7-8dc4-5115117dda92)

Occupant dead
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/153900881/fbd393c2-7cd3-4043-98dd-908439043d0a)

</details>

## Changelog
:cl:
add: Added the Bioscanner
del: Removed most instances of health analyzers occurring
balance: Health Analyzers now do radiation damage
/:cl:

2024-02-08 10:54 UTC, MarkusLarsson421 commented
> Bioscanners take scanner components and capacitors, upgrading the scanners decreases radiation, all the way to a max of 20 per scan, upgrading capacitors shortens scanning time, from 30 seconds at tier 1, to 7 seconds at tier 4.

The interactions between components and their effects are incorrect. I'd mimic what the DNA scanner already does.

![Screenshot_20240208_115222_Chrome.png](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/bf8876c2-8185-4660-907a-e1e187bf0029)

I recommend using a manipulator to decide scan time and laser to decide radiation.

2024-02-12 03:28 UTC, SunShine214 commented
My opinion probably doesn’t matter here, but many of the best rp players are med mains, so meant being anti-rp doesn’t seem supported by evidence here. Secondly, the reason the health scanner exists at all is because having so many bizarre methods of diagnosis makes reading the wiki required, which most people don’t, or will actively avoid doing something that requires wiki reading. The med scanner, gameplay wise, does a good job of consolidating diagnosing into one tool, which is good design. Having too many tools with very specific purposes is not intuitive or fun, and leads to much frustration on the part of players. Only players who enjoy complex mechanics and wiki reading would like this, but those players are the cause of “forts.” This pr overall would simply make med players frustrated and new players avoid learning med even more.

2024-02-12 03:49 UTC, Tsar-Salat requested changes
Looks good so far. Just a few minor QOL requests that will occur during common use.

2024-02-12 03:49 UTC, Tsar-Salat commented on code/game/machinery/bioscanner.dm
> +/obj/machinery/bioscanner/AltClick(mob/user)
Nothing is printed if this fails, there should be some sort of warning to_chat to the user about not being able to open it.

2024-02-12 03:49 UTC, Tsar-Salat commented on code/game/machinery/bioscanner.dm
> +		return
Needs fail message when you can't put something in. Exception of Adjacency, those should just return.

2024-02-12 03:49 UTC, Tsar-Salat commented on code/game/machinery/bioscanner.dm
> +	name = "Bio-Scanner"
```suggestion
	name = "bio-scanner"
```

Recommend use of undercase for all uses of "bio-scanner" printed to chat. 

All the machines similiar to it: sleepers, cryopods, stasis beds, & cloning pods do it this way. Its a bit jarring otherwise imo.

2024-02-12 03:49 UTC, Tsar-Salat commented on code/game/machinery/bioscanner.dm
> +	var/enter_message = "<span class='notice'><b>You feel cool air surround you. You go numb as your senses turn inward.</b></span>"
Why are they being cooled like a cryopod or sleeper, and going numb? They are getting irradiated, not falling asleep.

Perhaps something like feeling a prickling & goosebumps as the scanning beam passes over them.

2024-02-12 23:37 UTC, Howluinb commented
> but many of the best rp players are med mains, so med being anti-rp doesn’t seem supported by evidence here.

Med players mostly RP among themselves, and do so because of the inevitable hour long downtime on slow shifts where there is nothing to do *but* RP, since anyone who walks in with any form of damage gets healed withing 2 minutes. 
The only time med ends up engaging is when they start getting overwhelmed or struggle to work for some reason.

RP shouldn't be confined within members of the same department, and I never get to interact with med docs who say anything, most of them just grabbing you, scanning you with the instant tool, healing then pushing you out.

The RP of med should involve a doc and its patient, have them interact and discuss the scan or do anything beyond optimising the fuck out of healing so that they spend the least amount of time with outside players.
As tsunami said, med docs/parameds already starts hyper optimised with very little to work for in the long run, thus leading to minimal interaction with the rest of the crew unless they just give up their post (and Bar RP can be done with any role other than med)

2024-02-13 04:13 UTC, TsunamiAnt commented
> IIRC, the detective's PDA cartridge comes with a health scanner capability to allow checking bodies for damage as evidence. I assume that functionality is removed here?

They keep the reagent scanner, healthscan is gone. They'll have to use the brig's bioscanner or ask a doctor.

2024-02-14 17:07 UTC, PerishedFraud commented
I like this but I hate the rad aspect of the PR and think it's just meanspirited. The rest is surprisingly neat!

2024-02-14 22:47 UTC, DarnTheMarn commented
I mentioned it on discord and I'm mentioning it here for posterity. The self aware quirk should really be changed in response to these changes, it's essentially a health scanner for yourself minus the reagent scan. As for how I don't think simply increasing the point cost is good. In my opinion outright removal or making the readout a ballpark estimate that's only slightly better than non-self aware self examining.

2024-02-15 07:38 UTC, TsunamiAnt commented
I don't think it's that bad+L+Out of scope+touch grass+i don't wanna have to touch quirkcode

2024-02-17 13:00 UTC, Rukofamicom requested changes
Please update your changelog to include more details - these are the player facing changes and should include every detail relevant to them

CMO having their analyzer downgraded, and medbot construction changing for instance.

2024-02-17 13:02 UTC, Rukofamicom commented
Also I'm shuffling this tag because this is a change large enough it should probably be discussed by maints as a whole instead of just two-approval.

2024-02-19 08:20 UTC, TsunamiAnt commented
> Please update your changelog to include more details - these are the player facing changes and should include every detail relevant to them
> 
> CMO having their analyzer downgraded, and medbot construction changing for instance.

Done!

2024-02-19 11:48 UTC, Rukofamicom approved these changes

2024-02-19 20:49 UTC, PowerfulBacon commented
I'm happy to sign off on this, although giving it a longer testing period (or at least the condition that changes may be requested to it within 1 week of merge) might be necessary.

2024-02-19 21:32 UTC, TsunamiAnt commented
Definitely yeah. Obviously a testmerge might be necessary too.

2024-03-05 18:49 UTC, ClownMoff commented
Why are we focused in making medbay more painful to play

2024-03-09 07:34 UTC, TsunamiAnt commented
> Why are we focused in making medbay more painful to play

We aren't, this doesn't. Keep non-technical discussion to the discord(or the forum if you must).

2024-03-15 02:15 UTC, Rukofamicom commented
> (or at least the condition that changes may be requested to it within 1 week of merge) might be necessary.

The author has shown commitment via both the forums and discord so I'm going with this option. I have faith that the author will adapt whatever is necessary post-merge, and will take responsibility myself if necessary. 

While I'd like to see a testing period a bit moreso than the straight merge, my opinion is pretty heavily soured by some bad faith actors and strawmans among the protesting side so I think it'll be more beneficial to just dive in and tweak at this point, with the hope that those who aren't acting in bad faith quickly realize that this isn't nearly as massive of a shift as they're being led into believing.

2024-03-15 02:22 UTC, merged