Fixes Incorrect IPC trait Description
BeeStation/BeeStation-Hornet pull request #10596
Opened 2024-02-10 21:32 UTC by MarkusLarsson421

## About The Pull Request
It says "Etheral" while you are looking at an IPC.

## Why It's Good For The Game
Minor oversight.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>
Before

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/bafad870-9270-4dc7-8643-181e6a9a5405)

After

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/ebda7ae0-a0a0-4045-bd67-591d2b281f4a)

Does not mess with the Etheral description.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/df3efb71-afc9-4dc1-adff-b096df92438f)

</details>

## Changelog
:cl:
fix: Fixes power hungry trait description.
/:cl:

2024-02-11 20:09 UTC, PestoVerde322 approved these changes

2024-02-12 12:34 UTC, Rukofamicom approved these changes

2024-02-12 12:35 UTC, Rukofamicom requested changes
Actually while we're here - can you fix the fact it says they can feed from lights? That is ethereal exclusive.

2024-02-12 18:23 UTC, Rukofamicom approved these changes

2024-02-12 18:36 UTC, merged