makes the chemical
BeeStation/BeeStation-Hornet pull request #10622
Opened 2024-02-19 17:06 UTC by RDS88-beeman

## About The Pull Request
Adds a new chemical that is functionally identical to atrophine except safe for oozelings, and replaces the atrophine and epinepherine in the heretic minigame with it.

## Why It's Good For The Game
Fixes  #9177. Winning the heretic minigame shouldn't kill you

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>
Testing? What testing? (I'll get to it, I'm trying to figure it out right now)

</details>

## Changelog
:cl:
fix: Escaping from a handshake with an elder god no longer causes oozelings toxin damage.
/:cl:

2024-02-23 00:56 UTC, EvilDragonfiend requested changes
Make it work to everyone (IPC, Undead too)

2024-02-25 01:49 UTC, RDS88-beeman commented
gimmie 200 years to actually figure out how to do that

2024-03-14 11:49 UTC, EvilDragonfiend requested changes
`self_consuming = TRUE` too

2024-03-15 05:43 UTC, RDS88-beeman commented
ding, thanks for the help. That everything?

2024-03-15 05:50 UTC, EvilDragonfiend commented
> ding, thanks for the help. That everything?

I guess so yeah. I will merge it after that.

2024-03-15 05:55 UTC, EvilDragonfiend approved these changes

2024-03-15 06:14 UTC, merged