Meta Brig rework
BeeStation/BeeStation-Hornet pull request #10625
Opened 2024-02-19 22:38 UTC by MarkusLarsson421

## About The Pull Request
Reworks the Brig to be better looking and more functional.

## Why It's Good For The Game
Existing Meta Station has a lot of issues and looks troubling.

The third Security hardsuit is to enable Security to combat pirates easier.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
fix: [MetaStation] Reworks the Brig post genpop.
balance: Added a third Security hardsuit.
add: [MetaStation] VIP prison room.
/:cl:

2024-02-20 02:41 UTC, Fronsis commented
Looks good! though not a fan of long corridors vertical corridors just seems.. empty, a couple of things:

- I would personally add another recharger where the secway key is or on the top right corner where those boxes and paper is for consistency with the original locker room

- Have you modified the contents of the brig phys locker or they have the usual things?

- What's up with that command-blue door on genpop? seems unecessary given it starts bolted, the general brig reworks makes it feel like genpop is taking way more space and the actual brig and the genpop is the central piece of brig, when it should be the other way around, hence why most maps have it shifted to a side

-Why do prisioners get the chance to break into execution room/view it? it's a restricted area that's not for public show which leads me to:

-AI can probably see if the curtains are not closed, but from what i'm seeing.. i don't see much AI coverage on genpop or for officers to watch cameras can't really tell from an image so i'm unsure how much dark spots the AI/Officers have on Genpop, there should be a camera focusing on the work area and surrounding areas while leaving no cameras near the bedrooms and bathrooms like the other stations also a camera on the radiation shellter as well to confirm the well being of the prisoners in the case of a storm

- I think the confinement room is lacking the console to put a timer and open the windoor

- They have.. six spots? where random loot can spawn

-I think the drink and smoke vendor are pretty much useless unless you made them free, which shouldn't be a thing, or.. unless they can link their random prisoner ID their bank account, if anything they should have the old school perma food vendor that didn't require a bank account

- I don't see the prisoner outfits on a rack, unless they're inside the lockers, you could add a few extra given it's common currency to run out of them from time to time

-To the left where the microwave and donk pockets are, i would personally be fan of a smokes vendor rather than coffee, loots of officers smoke

-Might want to double check there's enough camera coverage on brig i see that there's a lot of places without one (like the main equipment room)

That's all i can spot for now

2024-02-25 20:38 UTC, MarkusLarsson421 commented
> * Have you modified the contents of the brig phys locker or they have the usual things?

No, they have the regular things. Why?

> * What's up with that command-blue door on genpop?

It is the VIP room which is unlockable from the Warden office, the idea is that the prisoners will pay out of their own pocket an Officer to unlock it for them.

> -Why do prisioners get the chance to break into execution room/view it?

Good point, I'll make it reinforced walls. Was hoping you could hold an execution in front of the prisoners.

> * They have.. six spots? where random loot can spawn

Is this a bad thing or a good thing? So far every other remake of the Brig has added this and it seems somewhat fine. Don't like it? Clear it out on round start.

> -I think the drink and smoke vendor are pretty much useless unless you made them free, which shouldn't be a thing, or.. unless they can link their random prisoner ID their bank account,

Their prisoner IDs can be linked to their bank accounts. Every other Brig remake so far has vendors of some kind like smoking, drinking and or seeds.

>     * I don't see the prisoner outfits on a rack, unless they're inside the lockers, you could add a few extra given it's common currency to run out of them from time to time

Extra clothing and lockers are available in the Brig maints between the armoury and HoS office.

2024-04-07 18:22 UTC, Crossedfall commented
There are conflicts, but I'm closing/re-opening the PR anyways to fix the CI.

2024-05-27 10:37 UTC, MarkusLarsson421 commented
I had a bit of an odd issue I couldn't resolve. Unsure if it is worth dealing with or not.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/ba511b59-3c4d-439a-be1e-f00e47be44aa)

2024-05-28 21:37 UTC, Fronsis commented
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/57050500/ed408eca-886f-49a9-b24e-ed89f7e80eb4)
I think this part should be reinforced! Everything else seems fine

2024-06-17 16:40 UTC, PowerfulBacon requested changes

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/266a49f2-8a79-4334-bd00-84ef939754b0)
This room has no detail in it at all, no intercoms, no furnature. What's this room meant to be?

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/6176cb79-74f5-4ec4-8712-dc13f05f9fd1)

This new room lacks any atmosphere control vents.

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/17d3fa05-6843-4602-a403-6194153ab08f)

Move this wall in by 1 so that there isn't an awkward single tile hallway to a door.

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
Why do the prisoners have a doorway going into the execution room made of glass? Also use a standard execution room style, rather than a grille.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/b4b77985-1ca9-4267-80b9-5e3b7f168441)

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/310ddc81-34ea-4d67-a694-a29b1618117a)

Remove the highlighted wall

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
This room needs shutters for the brig physician to hide their activities from the prisoners (who might snitch on them)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/ac48c5b7-7e8f-46b2-af66-35a73568209d)

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/6b54653f-8526-4f8e-be74-09fe64b07f13)

Brig needs pepperspray fillters in the primary hallway and in the equipment room.

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/7817008a-32bb-4b26-b041-13bc8cd0a18e)

Chair in the airlock?

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/9291a050-958e-439f-9fa3-3db9c92ece7d)

Only 1 light in this room, add a second

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/c2f71126-bb12-4af4-8105-3f05b9806536)

No lights in this room

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/fe459d78-e765-431b-b9ce-885e8a382368)

There are no intercoms anywhere

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/65ef484d-cde7-4596-9001-2c3a3162a9e5)

The HOS' bedroom should not look like this. See other maps for some examples of how it should look.

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
What APC controls the power to this room?

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/055a47a3-e9fd-4c2a-8c43-9c4d098e0e1a)

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/44f29a0e-8f3c-4929-81dc-f354c1e846b0)

Are these using the weapon spawners that armouries should be using? It looks like there are multiple on a single tile, when there should only be a single armoury item spawner which spawns items according to the number of security players.

2024-06-17 16:40 UTC, PowerfulBacon commented on _maps/map_files/MetaStation/MetaStation.dmm
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/bb4882c0-503a-45d6-87cd-2f9d715f1ab2)

Why is there a captain's level bedroom just chilling in the back of the prison?

2024-06-17 16:44 UTC, MarkusLarsson421 commented on _maps/map_files/MetaStation/MetaStation.dmm
It was an idea by Kane as a bootleg electric chair.

2024-06-19 02:06 UTC, Fronsis commented on _maps/map_files/MetaStation/MetaStation.dmm
I agree, as long as the ''lethal injection'' and the other stuff on the table stay it still has like 90% of the ''default stuff' it's not bad to have mini creative execution rooms, some new maps already have small different alternatives than the boring ''suffocate'' one, though in hindsight i do agree this is just public viewing for the prisoners when it should be mostly for Command/Officers and it shouldn't be ran across the armory to reach there, specially since you're transporting the prisoner

2024-07-13 01:01 UTC, DarnTheMarn commented
If you get around to fixing the merge conflict, don't forget [https://github.com/BeeStation/BeeStation-Hornet/pull/11153](url) removed a lot of extra medical shit in the brig. To be like all the other maps aim for 1 first aid kit and gauze in the open, surgery tools and extra medicine are now in the brig phys locker so no need to place those.

2024-07-13 05:16 UTC, MarkusLarsson421 commented
Kind of dislike how long it turned out so I kind of lost interest for this, going to try again in the future unless someone else makes a Meta Brig PR.

2024-07-13 05:16 UTC, closed without merging