Adds a new Banning Panel made with TGUI
BeeStation/BeeStation-Hornet pull request #10635
Opened 2024-02-22 09:23 UTC by Miliviu

## About The Pull Request

Adds a new modern and cool Banning Panel done with TGUI

## Why It's Good For The Game

QOL for the Admin team, it's pretty and easy to use, and if anyone doesn't like the new panel (or TGUI dies) the old one is still available.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

New Banning Panel tests:

https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/3cb9e124-4157-4c32-9efa-3553341efe08

Old Banning Panel Tests:

https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/4a08d745-4e54-425c-b973-aad90fe9a718

</details>

## Changelog
:cl: jixs4v, Miliviu
admin: Added a new Banning Panel created with TGUI, old panel is still available with the verb old-banning-panel
/:cl:

2024-02-22 09:27 UTC, EvilDragonfiend requested changes, later dismissed
The special global bans like `BAN_ROLE_ALL_ANTAGONISTS` should be accessible without opening the list. I don't like our bans become bloated when there is a ban option for literally all antagonists.

2024-02-22 09:40 UTC, Miliviu commented
Now :>

2024-02-24 15:29 UTC, JixS4v requested changes
Needs force cryo after

https://github.com/Miliviu/BeeStation-Hornet/pull/1

2024-02-24 15:30 UTC, JixS4v commented
Taking a look at the full PR body, will come back with a more detailed review

2024-02-24 16:06 UTC, JixS4v approved these changes
LGTM after testing!

2024-02-25 03:01 UTC, itsmeow requested changes
Some layout feedback:

Move ban reason into its own section. It should be the first thing after Key/IP/CID
Move Duration, Type, Applies to Admins, suppression, and Force cryo after into its own section, after the reason.

The duration input should have a permanent checkbox that hides the time input that is off by default, rather than a dropdown to switch types.

Enabling Key, IP, etc should create input fields on a new line below, with a label correspond to what it is

```
- [X] IP
- [X] CID

...

IP: [INPUT HERE]
CID: [INPUT HERE]
```

"SUBMIT" Should be a big green fucking button, next to an equally big red CANCEL. It should be at the bottom of the banning panel. See TGUI inputs for this.

Role bans should use multiple columns if there is horizontal space to do so (you can use a flex with a 50% basis to do this)
Flip the order of the role ban category buttons. Pressing the name should expand it. There should be a color='transparent' checkbox on the right that expands and selects all for a category.

There should be some way to search for roles that filters the shown roles and expands all categories temporarily while searching.

If possible, move abstract roles to the top and make them always expanded rather than their own category. Mainly because Appearance bans are very common.

(No code review atm)

2024-02-26 02:53 UTC, itsmeow commented on code/modules/admin/sql_ban_system.dm
> +			"Other" = GLOB.other_bannable_roles,
We really, really should not have this in two places (it's also a static list on the tgui datum)

These things should be put in a global variable or something.

2024-02-26 20:41 UTC, JixS4v commented
Hello, admin (joelogbybolb) and original designer of the UI that was behind this here, with miliviu picking up where I left and finishing it (thankfully)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/61665800/624756a0-d78c-4e6b-b6bd-dc27c1994beb)
Here's a quick mockup of the proposed designed decisions (save the search bar because it's a bit less easy). I'll get into why I don't agree with some of these changes.
> Move ban reason into its own section. It should be the first thing after Key/IP/CID 

This is plain not needed, the ban reasons rarely exceed the space that was alloted in the original UI and it's just adding bulk to the window without much substance.
> Move Duration, Type, Applies to Admins, suppression, and Force cryo after into its own section, after the reason.

At risk of pulling the "legacy" card, this is how it was organized before so admins won't have to adjust to the change, furthermore the space alloted is plenty and we usually set these before actually writing the ban so it's not really needed.

> The duration input should have a permanent checkbox that hides the time input that is off by default, rather than a dropdown to switch types.

This makes the UI much less clear and intuitive to use, and usually temporary bans are the default anyways.

> Enabling Key, IP, etc should create input fields on a new line below, with a label correspond to what it is
> 
> ```
> - [X] IP
> - [X] CID
> 
> ...
> 
> IP: [INPUT HERE]
> CID: [INPUT HERE]
> ```
> 
I don't think this is a positive change, it spreads out the UI for no reason?
> "SUBMIT" Should be a big green fucking button, next to an equally big red CANCEL. It should be at the bottom of the banning panel. See TGUI inputs for this.

Why would you need a cancel button? This isn't a prompt, it's a panel you open and you will usually make several bans from the same panel instance, for instance when applying a combined server+role ban
> Role bans should use multiple columns if there is horizontal space to do so (you can use a flex with a 50% basis to do this)

This looks nicer! My original intention behind the single-column layout is that finding categories is much easier, since you can just hover your mouse while scrolling till you find the right one.

> Flip the order of the role ban category buttons. Pressing the name should expand it. There should be a color='transparent' checkbox on the right that expands and selects all for a category.

This is purely aesthetic but I do think it looks nicer the other way.

> There should be some way to search for roles that filters the shown roles and expands all categories temporarily while searching.

There's so few roles to ban and you're usually banning general categories anyways (as per admin policy!), so adding a search bar is pretty unecessary

> If possible, move abstract roles to the top and make them always expanded rather than their own category. Mainly because Appearance bans are very common.

Appearance bans are not common at all, I have only appearance banned someone once in my almost 5 months of adminning

All this being said, I will hold a poll with the rest of the admin team to see what they prefer.

2024-02-26 20:58 UTC, itsmeow commented
> I don't think this is a positive change, it spreads out the UI for no reason?

It's designed to reduce layout shift, where the UI moves buttons when you click something. It makes UI more difficult to use.

Alternatively, you could ensure each toggleable input is on a new line next to its checkbox and label.


Also, I think you misunderstood my duration request: It should be a checkbox labeled "Permanent" that is OFF by default. If it is off, it will show the duration input. So temp ban is the default.

2024-02-26 20:59 UTC, itsmeow commented
Also, for the Ban Details tab, you can move that into the top section as another column using flex.

2024-02-26 21:03 UTC, itsmeow commented
For role ban sections, I'll agree with you, the old one is better, although maybe try setting the icon position to right?

2024-02-26 21:05 UTC, JixS4v commented
> It's designed to reduce layout shift, where the UI moves buttons when you click something. It makes UI more difficult to use.

would there be a way to make it gray the input out instead of just making it dissapear? that'd be ideal, in my opinion.

2024-02-26 21:06 UTC, JixS4v commented
> For role ban sections, I'll agree with you, the old one is better, although maybe try setting the icon position to right?

The checkbox position you mean? I think it's fine to the left because otherwise the collapsible opening shifts it to the end of the contents.

2024-02-26 21:07 UTC, itsmeow commented
No, the arrow

2024-02-26 21:08 UTC, JixS4v commented
> No, the arrow

Don't think it's possible without changing the component

2024-02-26 21:08 UTC, itsmeow commented
> 
> > It's designed to reduce layout shift, where the UI moves buttons when you click something. It makes UI more difficult to use.
> 
> would there be a way to make it gray the input out instead of just making it dissapear? that'd be ideal, in my opinion.
> 

Yes, but the second goal is to reduce visual clutter, which the old one is chock full of.

Just do this;
Key [X] [______]
IP [ ]
CID [ ]

2024-02-26 21:09 UTC, itsmeow commented
The component already has an iconPosition prop.

2024-02-26 21:11 UTC, JixS4v commented
I still don't think permanent bans being a checkbox makes little sense, but I'll get to implementing this tomorrow, it's pretty late.

2024-02-27 20:28 UTC, PowerfulBacon commented
The old admin panel should just be removed. There is no reason to keep both, TGUI failing is uncommon and will result in the admin tools being unusable anyway

2024-02-27 21:09 UTC, JixS4v commented
> > > It's designed to reduce layout shift, where the UI moves buttons when you click something. It makes UI more difficult to use.
> > 
> > 
> > would there be a way to make it gray the input out instead of just making it dissapear? that'd be ideal, in my opinion.
> 
> Yes, but the second goal is to reduce visual clutter, which the old one is chock full of.
> 
> Just do this; Key [X] [______] IP [ ] CID [ ]

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/61665800/c8b256e1-859a-47b7-941a-6178b03487e1)

I think this is ideal

2024-02-27 21:48 UTC, Miliviu commented on code/modules/admin/sql_ban_system.dm
> +			"Other" = GLOB.other_bannable_roles,
Okay, I've checked this out, this kinda is in two places but not in the same way

Once in the tgui datum as a const list, I don't mind moving it into a glob variable it'd be fine, but this is in the OLD banning panel, I didn't plan touching it at all, I just changed the name to old_banning_panel...

It also doesn't have one list with all the jobs like our banning panel does, it has multiple lists with different jobs and stuff...

I can try to modify the old banning pannel but i'd honestly prefer not doing that!

2024-02-28 02:51 UTC, itsmeow commented
Use a NumberInput for the duration

2024-02-28 12:23 UTC, JixS4v commented on code/modules/admin/holder2.dm
> +	/// Bannig Panel
```suggestion
	/// Banning Panel
```

2024-02-28 19:31 UTC, JixS4v commented
> 🆑 jixs4v, Miliviu
Forgot ratón who helped out with a lot of the sql stuff.

2024-03-03 11:02 UTC, PowerfulBacon commented
Those checkboxes should really have no background, since they go green when they are checked which is confusing when the background is green to begin with

2024-03-04 21:38 UTC, Miliviu commented
@PowerfulBacon ^

2024-03-06 20:35 UTC, itsmeow requested changes
typo

2024-03-06 20:35 UTC, itsmeow commented on tgui/packages/tgui/interfaces/BanningPanel.js
> +                    content="Enable supression"
```suggestion
                    content="Enable suppression"
```

2024-03-06 20:36 UTC, itsmeow commented on tgui/packages/tgui/interfaces/BanningPanel.js
> +                  style={key_enabled ? { display: 'inline-block' } : { display: 'none' }}
add `fluid` to these so they grow to fill space. also adding a placeholder attribute makes it easier to parse at first glance

2024-03-06 21:14 UTC, Miliviu commented on tgui/packages/tgui/interfaces/BanningPanel.js
> +                    content="Enable supression"
Thanks!

2024-03-07 08:58 UTC, Miliviu commented
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/ef340875-da99-436d-bde1-3aa827ed2c86)

2024-03-08 16:59 UTC, Miliviu commented
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/0a4e1b5d-2daa-47ce-9dcc-1829d675c401)

New version

2024-03-10 16:49 UTC, itsmeow approved these changes
New one is good but imo remove the old panel

2024-03-10 17:54 UTC, Rukofamicom approved these changes
Removing the old panel should happen, but I'm alright with that being done in a future PR so admins have time to adapt.

2024-03-10 17:57 UTC, Miliviu commented
I commit to remove it in a future PR then!

2024-03-10 18:13 UTC, merged