New clothing
BeeStation/BeeStation-Hornet pull request #10640
Opened 2024-02-23 15:12 UTC by ClownMoff

## About The Pull Request

## Why It's Good For The Game

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-02-28 17:33 UTC, ClownMoff commented
The mapping label was a mistake hihi

2024-02-29 02:17 UTC, ClownMoff commented
"I have class at 2 am", am I an idiot? I meant 12pm

2024-02-29 19:19 UTC, PestoVerde322 requested changes

2024-02-29 19:19 UTC, PestoVerde322 commented on code/modules/clothing/head/misc.dm
> +	H.facial_hair_style = "Neckbeard"
Make it a subtipe of Fedora.

2024-02-29 19:19 UTC, PestoVerde322 commented on code/modules/clothing/shoes/miscellaneous.dm
> +		footstep++
This should be under either /obj/item/clothing/shoes/clown_shoes or /obj/item/clothing/shoes/cluwne and make the sound source a var, both are horribly cursed codewise anyway.

2024-02-29 19:19 UTC, PestoVerde322 commented on code/modules/clothing/suits/miscellaneous.dm
> +/obj/item/clothing/suit/underground_serpents_jacket // https://www.youtube.com/watch?v=S0ximxe4XtU&ab_channel=ElevatedLevel
Unnecessary long youtube link, while fine, anything post the & is not necessary.

2024-02-29 19:19 UTC, PestoVerde322 commented on code/modules/clothing/shoes/miscellaneous.dm
> +		footstep++
as in both the ducky shoes and the jesters, also the Jester shoes already exists under /obj/item/clothing/shoes/clown_shoes/jester

2024-04-03 08:39 UTC, PestoVerde322 approved these changes

2024-05-30 00:20 UTC, closed without merging