Cool New Cloaks!
BeeStation/BeeStation-Hornet pull request #10641
Opened 2024-02-23 16:47 UTC by RDS88-beeman

## About The Pull Request

This adds two new cloak skins, a skin for the HoS and a skin for the QM. It also adds colorizers for these cloaks to the beecoin shop, at 20,000 coins each.

## Why It's Good For The Game

Drip good, beecoin sinks good

## Testing Photographs and Procedure
<details>
<summary>Screenshots</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/66409077/9779bd3f-4064-4586-9ad1-c388ca0b21e8)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/66409077/475a1631-33b9-4509-8184-e8dead73b206)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/66409077/32375cfb-b118-4faf-896f-e83bab7845b3)

</details>

## Changelog
:cl:
add: You can now obtain cavalier cloak colorizers from your local beecoin vendor! QM and HOS varieties available!
/:cl:

2024-02-28 17:44 UTC, ClownMoff commented
No clown cloak :(

2024-02-29 03:39 UTC, RDS88-beeman commented
another time (along with chaplain)

2024-03-02 11:35 UTC, DrDuckedGoose requested changes

2024-03-02 11:35 UTC, DrDuckedGoose commented on code/modules/client/loadout/loadout_colorizers.dm
> +    path = /obj/item/colorizer/hoscloakknight
```suggestion
    /obj/item/colorizer/qmcloakknight
```

2024-03-04 18:40 UTC, RDS88-beeman commented
yeah good call i missed that

2024-03-10 09:09 UTC, PowerfulBacon commented
Not a huge fan of the sprites, they seem very unclear

2024-04-09 09:12 UTC, PowerfulBacon commented
Right now its too difficult to tell that the sprite is meant to represent a cape, and the colours on the HOS cape need work since it feels a bit coderspritey with the overly strong outline and grey body. They look too visually noisy

2024-05-07 22:39 UTC, EvilDragonfiend commented
@PestoVerde322 I delegate my key to you if you think the style doesn't belong to ours.

2024-05-14 04:29 UTC, BlueHNT commented
It looks nice, the colors are kind of missing its match for a lot of the HOS outfits. Still a lot better than the royal one by miles.

2024-08-05 00:22 UTC, closed without merging