Bioscanners 2 electric boogaloo
BeeStation/BeeStation-Hornet pull request #10781
Opened 2024-03-21 11:36 UTC by TsunamiAnt

## About The Pull Request

The old PR was fucked, here's the actual new one all in one package.
See:
#10751
#10749
#10584

## Why It's Good For The Game

Same thing as all the other ones. Go read those. Or don't.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Echo now has a bioscanner
add: Bioscanner board printing
tweak: Tweaked health analyzers to make them available again.
balance: Made health analyzers a bit weaker to compensate for their increased availability.
balance: Radiation scanning damage removed completely.
fix: Properly added health analyzers to the tech node.
fix: Added mutation and blind/deafness to the bioscanner readout.
fix: Color coded the damage readouts for the bioscanner.
add: Added the Bioscanner, a full-body medical scanning machine that can be ugraded and takes time to scan people.
balance: All medical scans now do slight radiation damage depending on the scanner used.
balance: switched out the CMOs advanced analyzer with a normal one, which will be the only handheld analyzer at shift start, same as the advanced one.
balance: removed advanced analyzer from the techtree and made them admin-only. Moved the normal one to tier 5 and research disk exclusive.
del: removed medical scanning functionality from PDA cartridges. Reagent scanning stays.
balance: medibots are now constructed with health sensors, not analyzers.
/:cl:

2024-03-21 11:39 UTC, TsunamiAnt commented
I swear to god don't merge this till It's ready, I gotta test and make the maps.

2024-03-21 12:05 UTC, TsunamiAnt commented
That went faster than expected. Please remember to testmerge before you merge it fully.

2024-03-21 12:22 UTC, Miliviu commented
If it's ready to be merged add Testing Evidence, if it's still a wip make it a draft pr!

2024-03-22 12:02 UTC, TsunamiAnt commented
> If it's ready to be merged add Testing Evidence, if it's still a wip make it a draft pr!

fine, but the evidence bites back!!

2024-03-23 15:16 UTC, Rukofamicom approved these changes
I still approve of this

👍

2024-03-24 16:13 UTC, PestoVerde322 approved these changes
Fine by me mapwise, approved.

2024-03-24 18:09 UTC, Rukofamicom commented
Medbay seems to operate largely the same as before, with exception to abnormal injuries going to the scanner.

2024-03-24 18:23 UTC, PestoVerde322 commented on code/modules/research/designs/medical_designs.dm
Honestly, i think Advanced Health analizers should be a diskette research rather than being gated off to admin only.

2024-03-24 18:25 UTC, PestoVerde322 commented on code/modules/research/designs/autolathe_designs.dm
> -/datum/design/healthanalyzer
Stealh change, the health analizer is no longer obtainable via autolathe, opt to replace it with the health sensor (like for medbots)

2024-03-24 18:30 UTC, PestoVerde322 commented on code/game/machinery/bioscanner.dm
> +	var/scan_timer
What's exactly the time to scan on a standard bioscanner?

2024-03-24 18:31 UTC, PestoVerde322 requested changes
Req. changes for the Stealth change, address that.

2024-03-24 18:45 UTC, PestoVerde322 commented on code/modules/research/designs/autolathe_designs.dm
> -/datum/design/healthanalyzer
Nevermind, the health sensor is there, just add the CL for the health analizer

2024-03-24 18:48 UTC, kiekatz commented
regarding health analyzer changes... i have raised this point before. and ive personally not seen other unrelated pr's that fix it by lucky chance so i will add it here

health analyzing without a health analyzer in emergency situations outside of medical... is scuffed... **(OUTSIDE OF SIMPLIFIED BODY TARGETING)** you cant see what bodypart is injured. just that... they are injured by some damage type... the defacto MOST basic medical check that even the most untrained assistant should be able to preform in emergency situations...

since this pr has decided to tap into health analyzing. its only fair for it to add. the ability to see what bodypart is injured by what damage type when examining a person... not even exact numbers just vauge (lightly/moderately/badly) (bashed/burned/[insert damage type])

2024-03-24 21:14 UTC, Rukofamicom commented
I maintain that health analyzers should be removed in favor of a good old fashioned examine text overhaul without exact numbers, but I know better than to push that right now.

2024-03-24 22:55 UTC, Miliviu commented
> I maintain that health analyzers should be removed in favor of a good old fashioned examine text overhaul without exact numbers, but I know better than to push that right now.

If the text is limb localized I'd go ahead!

2024-03-27 10:35 UTC, PestoVerde322 approved these changes

2024-03-27 10:35 UTC, PestoVerde322 commented
CL change has been adressed.

2024-04-16 15:24 UTC, TsunamiAnt commented
Yeah this is hella dead, I took some time to think about it and with the requested changes this is just useless.

2024-04-16 15:24 UTC, closed without merging