Echo fixes
BeeStation/BeeStation-Hornet pull request #10821
Opened 2024-04-01 13:15 UTC by BriggsIDP

## About The Pull Request

Fixes some issues with echo like lack of intercoms, removes gibtonite from echo station, and expands the minable area of echo

## Why It's Good For The Game

player feedback

## Testing Photographs and Procedure

<details>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/107176252/d008755a-e572-4354-8fc4-2d77d1aac3bd)

</details>

## Changelog
:cl:
tweak: [Echostation] removes gibtonite from echo station
tweak: [Echostation] expands the minable area of echo station by 75%~
tweak: [Echostation] fixes some minor map issues from player feedback on the forums
/:cl:

2024-04-01 13:47 UTC, Miliviu commented on code/game/turfs/closed/minerals.dm
> +/turf/closed/mineral/random/air/mineral_chances()
```suggestion


/turf/closed/mineral/random/air

/turf/closed/mineral/random/air
	turf_type = /turf/open/floor/plating/asteroid
	baseturfs = /turf/open/floor/plating/asteroid //the asteroid floor has air
	defer_change = 1

/turf/closed/mineral/random/air/mineral_chances()
```


I'd put it like this :)

2024-04-10 14:38 UTC, PowerfulBacon requested changes

2024-04-10 14:38 UTC, PowerfulBacon commented on code/game/turfs/closed/minerals.dm
> +/turf/closed/mineral/random/air
Why is there a random typepath declaration here, you have another declaration of the same typepath just below?

2024-04-17 18:40 UTC, PowerfulBacon commented on _maps/echostation.json
> +	"planet_radius":  "100",
```suggestion
	"planet_radius": "100",
```

2024-04-17 18:40 UTC, PowerfulBacon approved these changes

2024-04-30 08:03 UTC, PestoVerde322 approved these changes

2024-04-30 08:13 UTC, merged