NO more evil cryo
BeeStation/BeeStation-Hornet pull request #10833
Opened 2024-04-04 09:50 UTC by Miliviu

## About The Pull Request

fixes #10824

Now you can't put a mob without a key inside a cryo-chamber

## Why It's Good For The Game

Stop players from getting the Cryo-chambers full of mobs...

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/436ece61-9e62-4c1f-baf3-3618df3cbda7

</details>

## Changelog
:cl:
tweak: cryogenic freezer no longer accept mobs without a key attached to them
/:cl:

2024-04-04 09:55 UTC, Miliviu commented
> dont DC'd players no longer have a key attached to them? or ghosted ones? if that is the case this would make you unable to cryo them too, no?

Oh ffs, true, I did aghost, not ghost while I was testing this, smh

2024-04-04 09:57 UTC, PowerfulBacon commented
Check for no mind instead, since disconnected players that were once controlled by a player will still have a mind

2024-04-04 09:57 UTC, EvilDragonfiend commented
it should be mind based

2024-04-04 10:01 UTC, Miliviu commented
> Check for no mind instead, since disconnected players that were once controlled by a player will still have a mind

Not really, if you ghost the mind gets removed, if is a carbon you have last_mind tho
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/16dfb57a-3c8d-4dff-9fa0-8798659df55c)

2024-04-04 10:07 UTC, EvilDragonfiend commented
Bacon's point is preventing non-humans being cryo when they have no key.

2024-04-04 10:18 UTC, PowerfulBacon approved these changes
This should be fine

2024-04-04 20:36 UTC, Miliviu commented
> > Bacon's point is preventing non-humans being cryo when they have no key. But honestly, it should be just mind based because we sometimes want cryo someone
> 
> This will allow for Xenobio mobs/morphs/etc to cryo then?

If they have a mind yeah

2024-04-05 01:41 UTC, EvilDragonfiend requested changes
Last mind isn't necessary. Last mind without mind means it's a dead body, or a brain-swapped body, like a monkey brain having your original body, or vice versa.
so, `if(!iscarbon(target) && !target.mind)` will be enough

2024-04-05 07:13 UTC, Miliviu commented
> Last mind isn't necessary. Last mind without mind means it's a dead body, or a brain-swapped body, like a monkey brain having your original body, or vice versa. so, `if(!iscarbon(target) && !target.mind)` will be enough

If you use the verb ghost your mind gets erased
![319536397-16dfb57a-3c8d-4dff-9fa0-8798659df55c](https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/a0e382ef-6a4c-4cbb-965d-4b2766d8b900)

2024-04-05 07:23 UTC, Miliviu commented
I'll only check for mind, I think we should be able to cryo mobs (not only carbons) with a player inside them

2024-04-05 07:26 UTC, Miliviu commented
`if(!iscarbon(target) && !target.mind)`

Would allow people throwing in monkey cubes humans without a mind, we'd be having the same issue if someone decided to fill the Cryo Chambers

2024-04-05 07:49 UTC, EvilDragonfiend commented
Honestly, yeah, cryoing mindless isn't a thing. It's enough.

2024-04-05 07:49 UTC, EvilDragonfiend approved these changes

2024-04-06 08:20 UTC, merged