Separate turf flags from flags_1
BeeStation/BeeStation-Hornet pull request #10840
Opened 2024-04-04 15:23 UTC by Tsar-Salat

## About The Pull Request

Ports:
- https://github.com/tgstation/tgstation/pull/57263

Separates turf_flags bitfield from flags_1

## Why It's Good For The Game

Cleaner code, less bloated bitfields

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![Screenshot 2024-04-04 112024](https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/32ad9dd6-728d-4872-b397-1f48373b491f)

</details>

## Changelog
:cl: rkz, Fikou
code: separates turf_flags into its own bitfield
/:cl:

2024-04-04 15:32 UTC, EvilDragonfiend requested changes
I guess you need to recheck some

2024-04-04 15:32 UTC, EvilDragonfiend commented on code/game/mecha/mecha.dm
> +				if(target.flags_1 & NOJAUNT)
It still uses flags_1

2024-04-04 15:32 UTC, EvilDragonfiend commented on code/game/turfs/open/reebe_void.dm
> +	flags_1 = NOJAUNT
*shrug

2024-04-13 16:36 UTC, Tsar-Salat commented on code/game/turfs/open/reebe_void.dm
> +	flags_1 = NOJAUNT
intended

2024-04-13 16:38 UTC, Tsar-Salat commented on code/game/mecha/mecha.dm
> +				if(target.flags_1 & NOJAUNT)
Good catch. Fixed in fe35981

2024-04-14 13:23 UTC, EvilDragonfiend requested changes
Would you please take a look into your PR again? You are not separating flags correctly. The ones I told wasn't what really all.
You made 4 turf flags
```DM
#define NOJAUNT (1<<0)
#define UNUSED_RESERVATION_TURF (1<<1)
#define NO_LAVA_GEN (1<<3) //! Blocks lava rivers being generated on the turf
#define NO_RUINS (1<<4) //! Blocks ruins spawning on the turf
```
and these are supposed to go in `turf_flags` but still you're putting it into `flags_1`

2024-04-16 11:03 UTC, closed without merging