[PORT] Follows up TG's atom_hud system
BeeStation/BeeStation-Hornet pull request #10897
Opened 2024-04-17 03:19 UTC by EvilDragonfiend

## About The Pull Request

Follows up TG's atom_hud system

* Main PR
  https://github.com/tgstation/tgstation/pull/65189
* Additional PRS
  * https://github.com/tgstation/tgstation/pull/65604
  * https://github.com/tgstation/tgstation/pull/81338
    * This prolly fixes circuit overlay bugs
 
big amount of images being dumped into `client/list/images` has been an issue causing a lot of maptick.
This PR ports their atom_hud that prevents things being injected into a client needlessly when they can't see stuff from another z level

* Var name changes:
  * `show_to(mob)` is easier to understand than `add_hud_to(mob)`
  * `add_atom_to_hud()` than `add_to_hud()`
  * `remove_atom_from_hud()` than `remove_from_hud()`. it might be correct, but it's confusing grammarly. `remove SOMETHING from somewhere` is grammarly correct, so TG changed it to `remove_atom_from_hud()`. I am happy with it too.
  * hide_from()` than `remove_hud_from()`
  * again:
    `show_to(mob)`
    `add_atom_to_hud()`
    `hide_from()`
    `remove_atom_from_hud()`
* Single arbitrary var name like `M` or `S` for med_hud and sec_hud is a bad arbitrary usecase. We'd think `M` is an arbitrary var name for mob, not med_hud, and others too.
  * `H` (as hud) isn't that nice too

**Greatly good for performance**
## Why It's Good For The Game

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/e50691f0-ccf7-4dc3-b257-c6af5f6cb516)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/5cfbe5a9-f490-4f88-b978-e332ef9eb48d)

previously, it's 300 images
now it's cull down to 19 images

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/af6c2981-9220-498b-96e4-536a679e9cf2)

fine all as normal status

</details>

## Changelog
:cl: LemonInTheDark, MrMelbert, SmArtKar (Port by EvilDragon)
code: improved atom_hud system to greatly improve performance for maptick
fix: fixed some circuit overlay issues
/:cl:

2024-07-11 06:40 UTC, EvilDragonfiend commented
This needs more touches. The code is based on Plane Cube, and it isn't compatible well with z-mimics.

2024-10-25 05:32 UTC, EvilDragonfiend commented
closing for now. will bring it back someday

2024-10-25 05:37 UTC, EvilDragonfiend commented
ah, actually it was fine to review

2024-12-10 15:08 UTC, Crossedfall commented on _maps/_basemap.dm
> +#define LOWMEMORYMODE //uncomment this to load centcom and runtime station and thats it.
kek

2024-12-10 15:08 UTC, Crossedfall requested changes, later dismissed
Re-comment lowmem

2024-12-16 11:54 UTC, EvilDragonfiend commented
De-TM for now. I figured atom issue, I guess.

2024-12-30 07:24 UTC, EvilDragonfiend commented on code/modules/mob/mob.dm
> +			I.appearance_flags = RESET_COLOR|PIXEL_SCALE|KEEP_APART
eh, I need to track TG code why it's a thing

2024-12-30 07:25 UTC, EvilDragonfiend commented on code/modules/mob/mob.dm
> +			I.appearance_flags = RESET_COLOR|PIXEL_SCALE|KEEP_APART
eh, I need to track TG code why it's a thing

2025-03-13 02:52 UTC, EvilDragonfiend commented
:skull: speaking of the devil

2025-03-29 10:19 UTC, closed without merging