Fix blood cultists being able to place structures on survival pods
BeeStation/BeeStation-Hornet pull request #10925
Opened 2024-04-28 22:03 UTC by XeonMations

## About The Pull Request

Fixes an oversight in blood cultist metal structure creation.

## Why It's Good For The Game

Fixes an oversight that blood cultists could previously place structures on survivalpods due to them being considered on station premises and a valid blob area.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/2c5c6545-603f-4f60-a3ca-01adf3a07831

</details>

## Changelog
:cl:
fix: Fixed blood cultists being able to place structures on survival pods
/:cl:

2024-04-29 23:02 UTC, St0rmC4st3r commented
This was not intended????

2024-05-01 22:30 UTC, EvilDragonfiend requested changes

2024-05-01 22:30 UTC, EvilDragonfiend commented on code/game/objects/items/stacks/sheets/mineral/metals.dm
> +	if((!is_station_level(T.z) && !is_mining_level(T.z)) || (A && !(A.area_flags & BLOBS_ALLOWED)) || (A && !(A.area_flags & VALID_TERRITORY)))
```suggestion
	if((!is_station_level(T.z) && !is_mining_level(T.z)) || (A && !(A.area_flags & (BLOBS_ALLOWED | VALID_TERRITORY))))
```

2024-05-01 22:30 UTC, EvilDragonfiend commented
I am not sure which thing people generally like.

2024-05-03 07:14 UTC, EvilDragonfiend approved these changes
Code is fine but I am not sure the change. Maybe cultists should stop being asshole with this??

2024-05-08 09:11 UTC, merged