Makes BoxStation less clunky
BeeStation/BeeStation-Hornet pull request #10942
Opened 2024-05-07 15:10 UTC by ClownMoff

## About The Pull Request

Reworks some outdated Box shenanigans 

## Why It's Good For The Game

Clunkiness is le bad

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: Varo
tweak: BoxStation: Changed the following rooms around to update them to nowadays standards: Medbay Lobby, Chemistry, Bar, Hydroponics,Kitchen, Service Maintenance
tweak: Divided the bar in 2 areas so there is an APC for bartender room and bar and one for the rest of the bar room.
/:cl:

2024-05-07 15:47 UTC, PowerfulBacon commented
I don't like the changes to the hallway, since its just a perfectly straight hallway with no inlets, which tends to look amateurly mapped.

2024-05-07 22:34 UTC, MarkusLarsson421 commented
What is up with Chemistry? I'm sorry, but it looks horrendous.

2024-05-07 22:34 UTC, MarkusLarsson421 commented
The Botany backroom is a good change. Always such a tight room if there was more than one person on the server. lol

2024-06-28 00:20 UTC, spockye requested changes
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/e1ce5193-23d9-44b8-9d8a-8b35634943de)

misplaced cabling

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/bd5f74a2-3769-48a9-be1b-fbac5ed8a7f2)

misplaced cabling

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/61efa7b8-8856-4ea1-b9b6-916bfb1b0074)

atmos fuckery

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/b3c05799-7726-452f-9e19-893dea551730)

camera on windoor (windoor is also missnamed and ID'd for some reason?)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/b5ec0173-1d98-4162-b379-bc9b1c47cfac)

light on window

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/04388281-b6ad-456a-b4b8-290095b02a95)

why have two windoors here?

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/7f06e3a1-5ca1-40ca-9de6-53bb7a8e4893)

if your going to have only flower glass walls, try to vary them a little

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/4acf250a-cc67-4b3d-9b3a-f7a475f642d6)

no pete?

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/d08bd81e-bd8c-46be-b6f3-31431cf3658e)

having both the mourge and surgery theathre be connected to the all wooden breakroom feels a little off. mabye try moving the breakroom?


-------

in general, not too bad!  mabye try to use a few more different decals? it might be a good idea to re-organize the rooms and re-evaluate the amount of flower walls you use. a couple is always nice, but too many and it can turn into visual clutter

2024-07-02 11:44 UTC, spockye reviewed
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/c4ae5884-8c73-400f-a1c0-63d7d7deac90)

area fucked

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/155e2259-09bd-47f4-b76d-07a4ffbe428d)

you gotta decide if you want your maintenance doors to be part of their rooms or maintenance!!!

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/6b101d86-b200-489f-9c86-34552f153d0f)
piping error

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/4dcd1ab5-4fc1-47f3-a39b-549ce5e29eb8)
you forgot to move this

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/4cb3a5f7-9bef-41bd-a0fc-d852db16e9b9)

windows in walls

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/70154281-9502-450a-a469-0ac4a801840d)

window in wall

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/6a60fb3e-f295-48a2-aa1f-7e49476624d9)
wood borders spotted in the wild

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/b015a3bf-0c66-4757-9964-53ad0bb224f5)

you can rotate these decals!

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/f8511685-f4a6-4bad-ae8f-81298f0176e9)

missing decal

2024-07-02 11:57 UTC, spockye requested changes
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/67d87a1d-dfd3-41a8-8bc5-8d9744568380)
missing firelocks

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/5e18ea82-d18e-45e0-bd5f-e125ba219734)

wall in table

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/4beaddef-c5f3-4926-b269-5bf34b7ad4b6)

this hallway could use a airalarm

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/ddc0dbff-dd83-4ada-afe1-25714718ad51)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/3ad2094a-8d9b-4724-a146-4f7dddb1a20e)

these rooms need fire alarms

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/1fbc1677-b2a8-4a12-9e9e-bab4815f70dd)

this table could use a windoor

2024-07-02 12:38 UTC, MarkusLarsson421 commented
> you gotta decide if you want your maintenance doors to be part of their rooms or maintenance!!!

I think @PestoVerde322 made a decision regarding this. What it was I don't remember. Until then or if they don't respond it is probably better to stick to the current maps' standard by looking at other similar areas on Box Station.

2024-07-14 13:12 UTC, PowerfulBacon requested changes
Overall this is a big improvement, however I think the core medbay treatment area needs some slight changes to bring it away from the medical wings that are too centralised such as RadStation where its a pain to work since you are constantly being pushed due to the tight spaces between the placement of operating beds and sleepers.

We should aim for medicals which while compact, don't have crowding issues and aren't giant, empty open areas. My least favourite medbays are RadStation and the current Box since they have those issues.

2024-07-14 13:12 UTC, PowerfulBacon commented on _maps/map_files/BoxStation/BoxStation.dmm
![image](https://github.com/user-attachments/assets/dfc516d0-06ea-4b3d-bb33-dadc740df923)

Add the doors back

2024-07-14 13:12 UTC, PowerfulBacon commented on _maps/map_files/BoxStation/BoxStation.dmm
![image](https://github.com/user-attachments/assets/8516c54f-11cc-41c5-8610-66a8af248d1e)

I wouldn't want to sit on this toilet

2024-07-14 13:12 UTC, PowerfulBacon commented on _maps/map_files/BoxStation/BoxStation.dmm
![image](https://github.com/user-attachments/assets/2d1bea61-9cdb-4bc8-b874-46a380db7d8f)

Can you double check disposals still functions? Not sure if this is a diff rendering error

2024-07-14 13:12 UTC, PowerfulBacon commented on _maps/map_files/BoxStation/BoxStation.dmm
![image](https://github.com/user-attachments/assets/41b823b8-2337-4691-8996-374ac4ffa8fe)

Floating light bulb

2024-07-14 13:12 UTC, PowerfulBacon commented on _maps/map_files/BoxStation/BoxStation.dmm
![image](https://github.com/user-attachments/assets/41c2aa38-81cb-407c-bac1-411d208cba07)

Ngl I really dislike these open style medbay layouts where everything is just in 1 room. It feels chaotic, unorganised and is really annoying to have structure in medbay. This is an improvement over the current box medbay where everything was dumped into a single room with no regard to making it feel like an actual medical wing, but more needs to be done.

- There shouldn't be trees/wildlife in the middle of a sterile medical bay, especially a giant tree overhanging the operating areas.
- You should spread out the stasis beds and sleepers, everything in 1 place is a nightmare to work around.
- Anywhere where people will be operated on should use white, sterile tiles and not black tiles.

I would also make the following suggestion:
- Move the chemistry zone in a bit, shrink the storage room slightly, have a room for the stasis beds with tables surrounding them.

2024-07-14 13:12 UTC, PowerfulBacon commented on _maps/map_files/BoxStation/BoxStation.dmm
![image](https://github.com/user-attachments/assets/31e264d9-fe35-47c8-9192-62c9e260df57)

I know these were here already but remove these display cases, they serve no purpose for chemistry

2024-07-14 15:51 UTC, PestoVerde322 commented on _maps/map_files/BoxStation/BoxStation.dmm
To be fair, i prefeer an open style bar like this, altought it's its own location it also somewhat feels more like a proper cafeteria if anything (considering also the "separation" doors have been pushed back between kitchen and botany.

2024-07-14 16:10 UTC, ClownMoff commented on _maps/map_files/BoxStation/BoxStation.dmm
That last thing would mean redoing everything from scratch :S

2024-07-20 23:35 UTC, ClownMoff commented
This shit got broken to a point that I can't repair, time to create another branch and PR

2024-07-20 23:35 UTC, closed without merging