Fixes hub entry data collection
BeeStation/BeeStation-Hornet pull request #10958
Opened 2024-05-11 09:41 UTC by PowerfulBacon

## About The Pull Request

Changes the hub to use the special `&#8212;` character instead of the `-` character. This means data collection will be handled more gracefully.

@Crossedfall will need to take a look at this to ensure that the <a href... tags have no effect.

## Changelog
:cl:
fix: Fixes the hub entry not using the correct character to divide the station name.
/:cl:

2024-05-14 18:04 UTC, Crossedfall requested changes

2024-05-14 18:04 UTC, Crossedfall commented on code/game/world.dm
> +				s += "<a href='[discordurl]'><b>[server_name]&#8212;[copytext(station_name, 1, station_name_limit - 3)]...</b></a><br>"
```suggestion
				s += "<a href='[discordurl]'><b>[server_name] &#8212; [copytext(station_name, 1, station_name_limit - 3)]...</b></a><br>"
```

2024-05-14 18:04 UTC, Crossedfall commented on code/game/world.dm
> +				s += "<b>[server_name]&#8212;[copytext(station_name, 1, station_name_limit - 3)]...</b><br>"
```suggestion
				s += "<b>[server_name] &#8212; [copytext(station_name, 1, station_name_limit - 3)]...</b><br>"
```

2024-05-14 18:04 UTC, Crossedfall commented on code/game/world.dm
> +				s += "<a href='[discordurl]'><b>[server_name]&#8212;[station_name]</b></a><br>"
```suggestion
				s += "<a href='[discordurl]'><b>[server_name] &#8212; [station_name]</b></a><br>"
```

2024-05-14 18:04 UTC, Crossedfall commented on code/game/world.dm
> +				s += "<b>[server_name]&#8212;[station_name]</b><br>"
```suggestion
				s += "<b>[server_name] &#8212; [station_name]</b><br>"
```

2024-05-14 18:05 UTC, PowerfulBacon commented
Hold on, let me update the calculation to include the spaces (otherwise it doesn't know when to cut the station name)

2024-05-14 18:06 UTC, PowerfulBacon commented on code/game/world.dm
> +	var/character_usage = 90	// Base character usage
```suggestion
	var/character_usage = 92	// Base character usage
```

2024-05-14 18:06 UTC, PowerfulBacon commented
Ok, should be good now

2024-05-15 00:51 UTC, Crossedfall reviewed
It's the </b> that matters, not the special character. Character usage count shouldn't change I believe

2024-05-15 00:51 UTC, Crossedfall commented on code/game/world.dm
> +				s += "<a href='[discordurl]'><b>[server_name] &#8212; [copytext(station_name, 1, station_name_limit - 3)]...</b></a><br>"
```suggestion
				s += "<a href='[discordurl]'><b>[server_name]</b> - <b>[copytext(station_name, 1, station_name_limit - 3)]...</b></a><br>"
```

2024-05-15 00:51 UTC, Crossedfall commented on code/game/world.dm
> +				s += "<b>[server_name] &#8212; [copytext(station_name, 1, station_name_limit - 3)]...</b><br>"
```suggestion
				s += "<b>[server_name]</b> - <b>[copytext(station_name, 1, station_name_limit - 3)]...</b><br>"
```

2024-05-15 00:51 UTC, Crossedfall commented on code/game/world.dm
> +				s += "<a href='[discordurl]'><b>[server_name] &#8212; [station_name]</b></a><br>"
```suggestion
				s += "<a href='[discordurl]'><b>[server_name]</b> - <b>[station_name]</b></a><br>"
```

2024-05-15 00:51 UTC, Crossedfall commented on code/game/world.dm
> +				s += "<b>[server_name] &#8212; [station_name]</b><br>"
```suggestion
				s += "<b>[server_name]</b> - <b>[station_name]</b><br>"
```

2024-05-15 01:43 UTC, Crossedfall approved these changes

2024-05-15 01:45 UTC, Crossedfall commented
I'm good with it now. I verified that my data collection and other 3rd party collectors all appear to be functioning again. I'll merge it tomorrow to give time for any last minute changes.

We could probably adjust the character usage a bit 
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26130695/e159a569-2714-43e0-9edf-20f9cc7152c4)

2024-05-15 16:47 UTC, merged