Remove law change code extraction alert
BeeStation/BeeStation-Hornet pull request #11049
Opened 2024-06-05 18:24 UTC by ColonelOrion

## About The Pull Request

Removes the alert that occurs when the law change code is extracted without RD permissions.
also fixes minor spelling mistake

## Why It's Good For The Game

The last few months have seen a decrease in AI subversion to the point of it not even being tried anymore. The payoff does not appear to be worth the risk for almost all players. This change aims to reinvigorate this mechanic and see more use of secret code extraction and law upload without removing the checks on proximity etc.

PR made after the following thread on the forums:
https://forums.beestation13.com/t/ai-tired-of-being-round-removed-as-the-first-step-in-every-blood-cult-shift/

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/39484008/cb36326e-301f-4cac-b0be-e4efa5226762

</details>

## Changelog
:cl:
del: Removed law change code extraction alert when attempted by Non-RD staff
/:cl:

2024-06-05 18:39 UTC, Fronsis commented
I do believe it's important to keep it the old way, while Markus on his guide has showed how to do it "easily" not all players can do it 100% of the time and that's fine

It's a high risk - high reward move

In the past, subversions were proven to be extremely easily to do so and it often led to the usual "AI, turn off comms, suffocate chef and send a mediborg to steal the brain" "AI, plasmaflood sec and shock doors" which was.. unfun given it happened too frequently, Markus guide showcased it's still very much possible to easily subvert AI it just takes some time, thinking and positioning, i originally thought you could only print the paper on the RD office but it seems you can even print that, the lathe allows for pretty much everything both for Command and Antags alike.

The antag breaking into RD is not often the case, usually most  sec encounters a "; illegal extraction key detected location: somewhere extremely random" and don't have enough time to respond in time, which makes Command start considering how to fix it and gives the antag some temporary power that might or not be removed in time(depending on both the antag and command actions)

Since the antag can print everything on a lathe it's usually stealth up until the announcement and i think that's good enough, otherwise stealth subversions are .. eh. And too powerful

2024-06-05 18:45 UTC, tontyGH commented on code/game/machinery/computer/robot.dm
> +			say("commencing extraction.")
```suggestion
			say("Commencing extraction.")
```

2024-06-05 18:46 UTC, ColonelOrion commented
With command getting wise to the location data you're pretty much guaranteed to get caught unless you have already gained RD access, and if you've got RD access why bother subverting the AI?

When played correctly, following proper antag conduct (ie, the rules) subversions are fun for everyone, the AI player, the crew fighting to regain control of the AI, and the antag benefitting from an interesting advantage.

To judge a mechanic by the people that break rules and abuse it is unreasonable. This alert is a boring fix to a fun mechanic. Classic "no fun allowed" activity.

2024-06-05 18:54 UTC, tontyGH commented
To be honest... this seems like an "ided" PR that was made after one too many wraith deaths. 

The thing about AI is that it is inherently an incredibly powerful and disruptive role (as much as I like to complain). Access to every machine, pipe and radio channel on the station can let you cause some serious chaos if people don't catch on.

The other thing about AI subversion is that, like what Fronsis said, subversion isn't difficult. The problem is that it's **long**. Very long. There's so much prep that goes towards subversion that it basically isn't worth doing, and once you do subvert the AI, people will almost immediately catch on to it's inconsistent behaviour, so it isn't at all worth it.

I'm not against the idea of making it easier, but you have to really, _really_ understand the balance ramifications of doing so. I guess this PR is fine, though?

2024-06-05 19:04 UTC, Fronsis commented
> With command getting wise to the location data you're pretty much guaranteed to get caught unless you have already gained RD access, and if you've got RD access why bother subverting the AI?
> 
> When played correctly, following proper antag conduct (ie, the rules) subversions are fun for everyone, the AI player, the crew fighting to regain control of the AI, and the antag benefitting from an interesting advantage.
> 
> To judge a mechanic by the people that break rules and abuse it is unreasonable. This alert is a boring fix to a fun mechanic. Classic "no fun allowed" activity.

I have seen fun subversions from players, that i won't deny, however even in those cases most of the time we actually had a hard time finding them(the antag) and getting a fix on the AI(usually taking up to 20 minutes depending on Command) so it's not like the announcement makes it's a game over i concur it does "rush" things like the AI and Antag not being able to do X thing because of the pressure it puts, though if they do it during a comms outtage they're set but if they don't is like you mentioned it makes for an entertaining fight to regain control of AI while Sec tries to find the perpretator and the AI does what it's law tells her in the mean time


Also, i'm not judging the mechanic due to "bad apples" players, even if they're there, by the rules the antagonist is allowed to pre-emptively take care of Sec with no repercusion and they obviously have the right to use the AI to kill their target, the rare DAGD are different ofc since they can affect everybody so it does have high repercusions on balancing.

(Also i do agree on the ided they mentioned above, i don't blame you Orion i do get it, while some people might tell you "it comes with the perk of being an all seeing eye" perhaps the focus could be moved to the Wraith issue)

2024-06-05 20:08 UTC, MarkusLarsson421 commented
> Since the antag can print everything on a lathe it's usually stealth up until the announcement and i think that's good enough, otherwise stealth subversions are .. eh. And too powerful

Unless telecomms goes out which it does quite often, both disruptions will benefit you.

2024-06-05 20:47 UTC, MarkusLarsson421 commented
> With command getting wise to the location data you're pretty much guaranteed to get caught
There are still areas which are more obscure. You can do it in a shuttle which can be relocated to ANYWHERE, or you can get a mining shelter capsule which most miners will give you if you ask nicely or lie of a sufficient reason for it.

2024-06-06 00:47 UTC, Rukofamicom commented
> To be honest... this seems like an "ided" PR that was made after one too many wraith deaths

It's really not. 

There's a simple truth that was overlooked or ignored with the original concept: There are three ways to deal with an AI, one of which always depends on being an especially good natured player.

1) You kill or destroy the AI
2) You subvert or otherwise manipulate the laws of the AI
3) You try to reason the AI into unusual interpretations of their laws to work around them (this requires especially good natured players on both ends, willing to blindly trust the other)

The third option will be rare until the playerbase trusts each other as a whole and making the second option substantially more difficult than the first means players are usually going to choose the first.

2024-06-06 08:24 UTC, MarkusLarsson421 commented
One problem to make subversion easier is that the tech storage often uses random spawning of boards instead of consistants boards every round. This means that you can not guarantee that the two boards and the related law boards are in there. 

I propose making the all available boards static and moving the law boards in upload behind a bolted door and not in the same room as the lasers. How this is done on maps like Delta is difficult to say.

2024-06-06 14:05 UTC, BlueHNT commented
Being able to subvert the AI without anyone knowing will only lead to more AI killing from sec than it already is.

2024-06-06 14:32 UTC, ColonelOrion commented
I think actually trying the idea will prove you wrong.
That being said when security kills an ai they can card, law flush, and repair, so that wouldn't be the end of the world.

2024-06-06 14:33 UTC, Howluinb commented
I've not seen a single subversion of the AI since the alert was implemented. And this is for a reason - Even if you managed to upload your law, now sec knows that AI is compromised and will rush to disable them.
So why even bother getting the AI on your side instead of killing it ? Like, AI is the most oppressive and powerful force on the station if played right, and essentially soft-removing a way to let AI work with antags/be less of a threat, means that everyone will go for a kill.

There's 2 options to fix this : 
1 - Make AI less powerful, which would basically make AI lose a lot of its appeal.
2 - Remove the alert, so that it's feasible to subvert the AI discreetly or do gimmicks without sec being instantly aware of it.

I prefer the 2nd.

2024-06-06 17:51 UTC, MarkusLarsson421 commented
> I've not seen a single subversion of the AI since the alert was implemented.
Well... subverting the AI is easy mode. I used to do it every time, consistently, when I was somewhat new and was just starting out in Robotics. It was a guaranteed friend who was most likely more experienced than me. Nowadays I tend to leave the AI alone because it is one less threat. Do note that I play most during low-pop, so usually an AI is the only station "force" there is.

2024-06-07 01:46 UTC, Fronsis commented
> I think actually trying the idea will prove you wrong. That being said when security kills an ai they can card, law flush, and repair, so that wouldn't be the end of the world.

Correct, but when the AI plasmaflood security... good luck reviving the entire team.

Anyways, let's say we remove the alert... where's the.. counter-play? Or even the risk? How does Security or the Station knows that AI has been subverted other than until it's too late? It would become a very stealth 0 risk move with high reward strategy for the antagonist given the fact that in a long-round they can print everything from the Lathe.

I do believe we should make the AI-Upload relevant again or involve some special board on the RD office (instead of 5 metal or a computer and that's it) otherwise the antag is just gonna freely be able to subvert an AI without leaving any trace(unless they pick up a very dumb spot) and have a massive advantage without facing any possible consequences from short to medium term, it would become like a ''free'' thing to do, why even bother with the law 0 board from the TC if you can fully customize every single law thanks to a sci/engi Lathe and a private room in maintenance, and the solution is not to have an officer or an RD right above the lathe questioning ''hey why are you printing this'' to every scientist.

2024-06-07 06:36 UTC, MarkusLarsson421 commented
> and the solution is not to have an officer or an RD right above the lathe questioning ''hey why are you printing this'' to every scientist.

Fun fact, you can see a print history in the ore silo log from all ore silo connected machines. So good AIs, QMs or whoever can know exactly when a subvertion is about to happen.

2024-06-07 06:42 UTC, ColonelOrion commented
![IMG_20240607_074148](https://github.com/BeeStation/BeeStation-Hornet/assets/39484008/30c2a344-3532-4de7-b054-c9b10fa20d0e)

2024-06-08 20:20 UTC, Haliris commented
Seeing PRs like this is funny, because it usually showcases communal amnesia since the authors usually don't bother researching why the mechanics were implemented the way they currently are.

The change to subversion was made in a time when the opposite problem of the AI being subverted every two rounds was the norm. I played AI during that time, and the gameplay wasn't much better than now, unless you had admins constantly wacking people around to not metagame the AI.

A random forum thread made by loud people with like-minded opinions is way too weak to justify such a balance change.

Here's the relevant PR that implemented the current subversion mechanics for those who are actually interested in developping this proposal further to ultimately improve the game.

https://github.com/BeeStation/BeeStation-Hornet/pull/6795

2024-06-08 20:29 UTC, ColonelOrion commented
> authors usually don't bother researching

> random forum thread made by loud people with like-minded opinions

> are actually interested in developping

Nice to see you haven't changed, buddy.
Any constructive suggestions for how to improve the situation?

2024-06-09 02:01 UTC, ColonelOrion commented
I do respect your take, I would just rather have too many subversions over none at all.

2024-06-09 02:59 UTC, Howluinb commented
Haliris, why did you have to *instantly* go for the condescending tone, here ?
> for those who are actually interested in developping this proposal further to ultimately improve the game.
All this does is piss off people by implying anyone in their right mind should hate this idea. Why ? How does this improve the conversation in any way ?

The PR doesn't seek to make it as easy as before to subvert the AI, but make it possible to be stealthy about it without having to cut comms. You'd still need RD access or better in order to attempt to subvert it.

Like, there are other methods to ensure subversion leaves traces and helps sec know about it. Having only a few non printable law change boards in the station (RD/Cap office ?) or other such limitations helps force antags to break into places and leave info everywhere.
But a giant alarm screaming "SUBVERSION HAPPENING" is the most uninteresting way to add challenge and make it harder. All it does is force you to go through so many hoops that at this point it's easier just to do any other objective and kill the AI to be done with it.

2024-06-09 05:42 UTC, Fronsis commented
> I do respect your take, I would just rather have too many subversions over none at all.
Then again that's gonna shift the meta to one where subversion would be a common token that, as Haliris mentioned, caused #6795 to be created to adress the issues we had at the time. Not to mention that adding an easy subversion + dynameme would lead to a massive advantage for a very specific antagonist(the one that subverts it first) affecting the other antags momentum as well since they could be affected depending on the damage the antag tells the AI to do.

As i've mentioned, this current proposal offers a high reward for zero risk

> All it does is force you to go through so many hoops (breaking into RD, cutting comms, taking a _lot_ of time out of your round that'd be better spent elsewhere) that at this point it's easier just to do any other objective and kill the AI to be done with it.

Gaining a big advantage like a  personal AI that can control the entire station shouldn't be easy, if you checked Markus guide you can see that you can almost print everything **roundstart** except for the law boards(which you bypass if you're a regular traitor that purchases the law 0), you don't even need to break into RD you can get every single thing from a lathe and then you just wait for comms and that's it subversion done. So if you time it correctly its easy but if you take the long route then yes,  it's supposed to take time, be hard and create conflict. If the antagonist is ill prepared and didn't spend enough time or thought about everything then.. shit happens, not everything will go according to plan.

And from my experience while the Antagonist might not be able to instantly tell AI ''.b Plasmaflood X and kill Y and Z'' from the moment Security gets the message and Command start acting the antagonist usually can issue a few orders to gain an advantage, create conflict and antagonize the station and that point it's up for the wits of the Antag to outplay command and sec and for the later to react in time before it's too late.

2024-06-09 09:33 UTC, ColonelOrion commented
> zero risk

No need to hyperboliza, mate. Building a secret lab absolutely does bear a risk of being caught.

2024-06-09 09:45 UTC, MarkusLarsson421 commented
I might as well add my personal experience to this as it is somewhat related. As an Explorer on Box Station I arrived late and as soon as I became a mid-round antagonist, I asked to be reassigned to Engineering. I did some regular work and then tampered with the telecomms APC with a remote signaler on the power wire to allow me to disable comms at will. After which I then printed whatever boards I wanted without any consequences.

In a similar round, I started as an antagonist Engineer on Meta Station. I set up the SM and whatnot and then walked over to the AI satellite with three purposes and an antagonist fourth purpose. First to connect the satellite to the station, second to change the welcome message to something funny (and mean as I'm an antagonist), third to connect the AIs backup PACMAN and plasma supply for emergency power, and finally the fourth antagonistic reason (and the real reason I did the others); that being to tamper with the APC once again to allow me to disable comms at will. Shortly after that, I printed a Robotics console, disabled comms and got the code. No one suspected a thing and were only amused by the new welcome message.

I think overall Engineers shouldn't have access to telecomms as having a free and easy global jammer is very, very powerful. In the first round the Security stated over Security comms that I had a jammer, as I would use it when I was chased to prevent them calling for backup. It is VERY powerful.

2024-06-13 16:30 UTC, EvilDragonfiend commented
I know there are ways to bypass this radio alert, but that's the point already. You need to do extra works for _safe extraction_.

2024-08-04 08:11 UTC, PowerfulBacon requested changes
Making law extraction easier is something that I think is a very good idea, and I support the following changes:
- Change it so that instead of needing a key to upload, uploading is slower and has a message if you don't have the key (so the wait is done at the AI upload console and not at the RD console, meaning you only need 1 machine. The message wouldn't indicate the area, but AI upload boards have a GPS on them which makes this harder.

This still requires 2 machines which makes law subversion difficult, but now just makes it a process that is silent which sucks.

2024-08-04 08:11 UTC, PowerfulBacon commented
The PR in this state though won't be able to get in

2024-08-04 08:11 UTC, closed without merging