Legion core healing nerf + legion core fix
BeeStation/BeeStation-Hornet pull request #11068
Opened 2024-06-09 22:08 UTC by XeonMations

## About The Pull Request

Changes the legion core's healing buff down from 50 on station z level to 20 on station z level.

Also fixes being able to preserve inert legion cores.

## Why It's Good For The Game

Miners spamming out the basic equivelant of an aheal on station premises only to shrug it off by eating some mushrooms should not be okay to do. Also bugfix good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/d55ea541-14df-4fff-b8a9-2757265beafe

https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/cc163577-e9ed-4817-9ca2-633f7d80cc8e

</details>

## Changelog
:cl:XeonMations
balance: Changed legion core healing from 50 to 20 on station z level
balance: Made inert legion cores no longer able to be preserved and thus work
/:cl:

2024-06-10 17:33 UTC, JixS4v requested changes

2024-06-10 17:33 UTC, JixS4v commented on code/modules/mining/equipment/regenerative_core.dm
>  	inert = FALSE
Unecessary since you are already checking this is the case and early returning in the line above

2024-06-11 05:22 UTC, JixS4v commented on code/datums/status_effects/buffs.dm
> +	duration = rand(150, 450) * 2
Might wanna avoid hard coding this, so if you're not using power maybe make a new parameter?

2024-06-11 05:22 UTC, JixS4v commented on code/modules/mining/equipment/regenerative_core.dm
> +		return
Might wanna give some feedback to the player about the stabilizer being consumed without any effect or just not allow the stabilizer to be used on inert cores now that I think of it

2024-06-11 14:05 UTC, JixS4v approved these changes
LGTM! Not sure why you'd make them last less on station, but it doesn't really matter that much in the grand scheme of things

2024-06-12 00:47 UTC, EvilDragonfiend approved these changes
@JixS4v Nice review

2024-06-12 00:48 UTC, EvilDragonfiend requested changes
nitpick. I think `duration_mod` is a clearer var name.

2024-06-12 22:55 UTC, EvilDragonfiend approved these changes

2024-06-12 23:02 UTC, merged