[Port/Refactor] Job Refactor
BeeStation/BeeStation-Hornet pull request #11129
Opened 2024-06-28 12:04 UTC by XeonMations

## About The Pull Request

Requires:
- https://github.com/BeeStation/BeeStation-Hornet/pull/11209

Dehardcodes alot of stuff, bringing our jobs to updated TG standards.

Ports fully or bits of code from:
- https://github.com/tgstation/tgstation/pull/59841
- https://github.com/tgstation/tgstation/pull/57460
- https://github.com/tgstation/tgstation/pull/60578
- https://github.com/tgstation/tgstation/pull/60987
- https://github.com/tgstation/tgstation/pull/64193
- https://github.com/tgstation/tgstation/pull/64596
- https://github.com/tgstation/tgstation/pull/77075
- https://github.com/tgstation/tgstation/pull/79776 (job flags and stuff, not the actual cargorilla)
- https://github.com/tgstation/tgstation/pull/80415
- https://github.com/tgstation/tgstation/pull/82015
- https://github.com/tgstation/tgstation/pull/80415
- https://github.com/tgstation/tgstation/pull/80279 (Job flags, again, not the actual station trait)
- https://github.com/tgstation/tgstation/pull/56910 (acting captain assignment code)
- https://github.com/tgstation/tgstation/pull/60349
- https://github.com/tgstation/tgstation/pull/78647

## Why It's Good For The Game

QoL for custom jobs and  stuff like that, also helps to bring our code up to date.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Things for when there is noone in a command position:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/f76adca2-8bb7-4427-a708-5866c133d619)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/28434302-c6f6-4ee6-963a-e3314d5e5ab7)
(Departures lounge is the location of the communications console, in this case, on RuntimeStation: Departures Lounge)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/bb75ffc1-28b9-4e15-9004-cb48f44b9513)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/03ebc257-7585-43b3-a594-4d50e2734eeb)

</details>

## Changelog
:cl: EvilDragonfiend, Rohesie, Timberpoes, Fikou, JohnFulpWillard, Jacquerel, MrMelbert, Ghommie, XeonMations
refactor: Dehardcoded a lot of job code, added job flags, as well as making the code hopefully better
add: Communications Consoles now have the ability to request codes to the spare ID safe when there are no crew members in the chain of command on the shift. This can be done without logging into the comms console.
/:cl:

2024-06-28 18:52 UTC, EvilDragonfiend commented
TG's job code isn't really great so that I won't recommend porting it.

2024-06-29 03:23 UTC, EvilDragonfiend requested changes
I skimmed, but the majour problem comes from something that you really shouldn't port.
The port is trying to make ROLE into JOB codes, to merge ROLE and JOB codes into one. This isn't a good refactor, only increases the complexity of the code to maintain.

2024-06-29 03:23 UTC, EvilDragonfiend commented on code/__DEFINES/is_helpers.dm
> +#define is_head_of_personnel_job(job_type) (istype(job_type, /datum/job/head_of_personnel))
Do not port this. This doesn't really help improving job codes.

2024-06-29 03:23 UTC, EvilDragonfiend commented on beestation.dme
> +#include "code\modules\jobs\job_types\spawner\zombie.dm"
this doesn't help job codes, and only increases complexity. Do not port this.

2024-06-29 03:23 UTC, EvilDragonfiend commented on code/__DEFINES/jobs.dm
> +#define DEPARTMENT_UNASSIGNED "No department assigned"
unassigned shouldn't be a department.

2024-06-29 03:23 UTC, EvilDragonfiend commented on code/datums/mind.dm
> +	add_antag_datum(/datum/antagonist/wizard)
I don't think we really should port theirs.

2024-06-29 03:26 UTC, EvilDragonfiend commented
🔑With the reason said above, I put my key.

## Why Role and Job shouldn't be merged?
Simple. This means roles like Heretic, Traitor, something else as a job, while crews should have a job with such special role.
Many roles shouldn't be a job, but the code makes them as a job.

2024-06-29 06:05 UTC, EvilDragonfiend requested changes

2024-06-29 06:05 UTC, EvilDragonfiend commented on code/__DEFINES/jobs.dm
> +#define DEPARTMENT_CIVLIAN
like I said, no 'unassigned' shouldn't be a department.
and, second, you don't have to change the flags.

2024-06-29 06:05 UTC, EvilDragonfiend commented on code/controllers/subsystem/ticker.dm
> +		var/datum/job/player_assigned_role = new_player_living.mind.assigned_role
```suggestion
		var/datum/job/player_assigned_role = SSjob.GetJob(new_player_living.mind.assigned_role)
```
This is how you should do

2024-06-29 07:13 UTC, PowerfulBacon commented
Getting rid of special role is a good idea, does this mean that assigned_role is a list now so people can have multiple job role at one?

2024-06-29 11:37 UTC, EvilDragonfiend commented
Lifting the key since the majour concern has been resolved.

2024-07-01 06:11 UTC, EvilDragonfiend requested changes
For the department subsystem, I didn't mean that you should take the whole codes, but it will be managed anyway.

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/job.dm
> +/datum/controller/subsystem/job/proc/EquipRank(mob/M, datum/job/job, client/C,  joined_late = FALSE)
no arbitrary var name `C`. Should be `client`

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/__DEFINES/department.dm
> +#define DEPT_AUTHCHECK_BUDGET "budget"
redundant

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/__DEFINES/department.dm
> +))
should be accessed from department subsystem.

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> +#define ACCESS_TEMP_SETUP(temp, acclist) temp = acclist; acclist = list();
redundant

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> +
redundant

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> +	var/list/all_station_accesses = list()
redundant

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> +	refresh_all_station_accesses()
redundant

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> +	message_admins("stating department INIT") // remove this later
remove this later \*wink\*

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> +	message_admins("DEPARTMENT INIT DONE")// remove this later
this too

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> +		GLOB.syndicate_code_response_regex = codeword_match
There is the same code in `ticker.dm` afaik. You need to remove the code, and let this code do its purpose.

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> +	return ..()
remind for
* https://github.com/BeeStation/BeeStation-Hornet/pull/10933

Just in case.

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> +			all_station_accesses |= dept.custom_access
redundant

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> +	var/list/access_manifest_changer = list()
redundant

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> +	var/budget_bitflag = NONE
likely redundant. You won't want to do this because it touches economy code too.

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> +	return FALSE
redundant

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/modules/jobs/job_types/_job.dm
> +		SSticker.OnRoundstart(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(_addtimer), CALLBACK(pick(GLOB.announcement_systems), /obj/machinery/announcement_system/proc/announce, "NEWHEAD", H.real_name, job.title
1. This is a type path proc, not a global proc.
2. You should use `PROC_REF()`

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/controllers/subsystem/ticker.dm
> +			OnRoundstart(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(minor_announce), player_assigned_role.get_captaincy_announcement(new_player_living)))
I hate this code and `get_captaincy_announcement()` proc. It doesn't make sense it to be a proc(why do you need to have multiple proc that returns the same?), and you can just make a string in this loop for those who are command.

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/game/gamemodes/clock_cult/clockcult.dm
> +				else if(role in SSdepartment.get_jobs_by_dept_id(DEPARTMENT_SILICON))
These titles should be in job datum when you're going to make `var/datum/job/assigned_role` in this refactor,

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/modules/modular_computers/file_system/programs/card.dm
> +			CARDCON_DEPARTMENT_COMMAND = SSdepartment.get_jobs_by_dept_id(DEPARTMENT_COMMAND),
Remind that the previous code only had `list(captain)`, not calling command position glob.

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/modules/mob/dead/new_player/new_player.dm
> +	var/static/list/department_list = list(SSdepartment.get_jobs_by_dept_id(DEPARTMENT_COMMAND)) + list(SSdepartment.get_jobs_by_dept_id(DEPARTMENT_ENGINEERING)) + list(SSdepartment.get_jobs_by_dept_id(
This can be replaced.

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/modules/mob/dead/new_player/new_player.dm
>  	)
This can be replaced. Although `Gimmick` might need to be hardcoded here.

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/modules/jobs/jobs.dm
> +	return ((job in SSdepartment.get_jobs_by_dept_id(DEPARTMENT_COMMAND)) || (job in SSdepartment.get_jobs_by_dept_id(DEPARTMENT_SILICON)) || (job in SSdepartment.get_jobs_by_dept_id(DEPARTMENT_SECURITY
This just should be a job flag, not trying to find a job from lists. (when `/datum/job` is given.)

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/modules/jobs/job_types/cyborg.dm
> -
are you sure? I am not sure, but I need to know if the removal works.

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/modules/jobs/job_types/assistant.dm
> +	department_for_prefs = DEPT_BITFLAG_CIV
Why?

2024-07-01 06:11 UTC, EvilDragonfiend commented on code/modules/jobs/job_types/captain.dm
> +	department_for_prefs = DEPT_BITFLAG_COM
And this too. why?

2024-07-02 00:29 UTC, XeonMations commented on code/modules/jobs/job_types/cyborg.dm
> -
Am I?


No, I am not. The code did not work. I do not know why I removed that.

2024-07-02 01:03 UTC, XeonMations commented on code/modules/jobs/job_types/cyborg.dm
> -
Figured out why It was removed. It now uses after_equip instead of equip.

2024-07-02 02:37 UTC, EvilDragonfiend requested changes
sorry, I told wrong lines to remove, but these two should exist.

2024-07-02 02:37 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> -	get_departments_by_manifest_order()
My mistake. you should keep it.

2024-07-02 02:37 UTC, EvilDragonfiend commented on code/controllers/subsystem/department.dm
> -	var/list/sorted_department_for_pref = list()
this too.

2024-07-08 02:09 UTC, EvilDragonfiend requested changes
You did way more worse.
Making GLOB into a list macro is bad. you make a list for every time that macro is called.
it should be SSdepartment variables having those value

2024-07-08 02:09 UTC, EvilDragonfiend commented on code/modules/mob/dead/new_player/new_player.dm
> +	var/static/list/department_list = GLOB.dept_name_all_station_dept_list
It only takes department names, not department positions. (I addressed wrong line. see below)

2024-07-08 02:24 UTC, EvilDragonfiend commented on code/__DEFINES/department.dm
> +	DEPARTMENT_SILICON = "#ccffcc") // department order and its dept color
(I mean these changes.)

2024-08-06 21:36 UTC, Tsar-Salat commented
> * [Fully implements the ID Card design document tgstation/tgstation#56910](https://github.com/tgstation/tgstation/pull/56910) (acting captain assignment code)

This specifically is needed for modsuit code, particularly the AI control function.

You don't have to do it in this pr, I figure I should let it be known that it is needed, however.

2024-08-26 23:27 UTC, XeonMations commented
49 merge conflicts later....

2024-08-26 23:28 UTC, XeonMations commented
ARE YOU KIDDING ME

2024-09-21 04:08 UTC, XeonMations commented
okay this entire PR is a shitshow, im pretty sure starting from scratch will be better than... sorting this mess now that https://github.com/BeeStation/BeeStation-Hornet/pull/11209 is in

2024-09-21 04:08 UTC, closed without merging

2024-09-21 04:08 UTC, XeonMations commented
Will be continuing this in a clean PR.

2024-09-21 05:23 UTC, XeonMations commented
nevermind, time for actual TGUI i guess