Fixed space dragon's gust ability hitting people through walls
BeeStation/BeeStation-Hornet pull request #11121
Opened 2024-06-26 23:22 UTC by XeonMations

## About The Pull Request

Fixed the space dragon's wind ability hitting people through walls. Also fixes a runtime oversight that made people not properly launched.

## Why It's Good For The Game

Being launched from behind a wall bad. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/334a76c6-4941-4745-89bf-df04e8cd7258

</details>

## Changelog
:cl:XeonMations
balance: Made the space dragon's gust ability no longer hit people through walls.
fix: Also fixed a runtime happening with the space dragon's gust ability.
/:cl:

2024-07-01 22:32 UTC, Howluinb commented
Space dragon is already weak enough, dragging a locker/hiding behind a wall to kite it infinitely is a massive nerf, why is this needed ?

2024-07-15 01:40 UTC, Rukofamicom commented
I'm against this one. Space Dragon is already quite weak to ranged weaponry overall, and it's not implausible for the wind to go around corners in most cases due to the narrow space on stations.

2024-07-15 18:33 UTC, MarkusLarsson421 commented
Even if the dragon is weak against ranged weapons, being killed by "bullshit mechanics" will be annoying.

2024-07-18 16:20 UTC, PowerfulBacon requested changes
Cast the view from all adjacent tiles to the dragon. I don't want people to be able to move behind a single tile of cover while still being essentially next to the dragon to completely dodge the ability. The ability is relatively bad as-is due to the long charge period and your complete defenselessness while you charge.

2024-07-19 13:27 UTC, PowerfulBacon requested changes

2024-07-19 13:27 UTC, PowerfulBacon commented on code/modules/mob/living/simple_animal/hostile/space_dragon.dm
> +		for (var/mob/living/candidate in view(gust_distance, epicenter))
I'd add candidate to a list and check to prevent them being gusted 5 times in a row

2024-07-26 12:36 UTC, PowerfulBacon approved these changes

2024-07-26 12:45 UTC, merged