adds a floorlight to every abductor pod
BeeStation/BeeStation-Hornet pull request #11138
Opened 2024-06-30 21:35 UTC by spockye

## About The Pull Request
as the name says, adds lights to the abductor pods. they're currently completely devoid of lights

## Why It's Good For The Game
you should be able to see

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/5d7c5cf2-c4b7-44fa-a552-0e418655fcdd)
</details>

## Changelog
:cl:
fix: adds lights to the abductor pods
/:cl:

2024-07-01 10:05 UTC, EvilDragonfiend requested changes
It should be un-interactible, and indestructible.

2024-07-01 19:47 UTC, spockye commented
> It should be un-interactible, and indestructible.

Done. Replaced the lights with light emitters

2024-07-01 19:57 UTC, spockye commented
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/79304582/a8075745-58e5-4633-840e-6edfe00a6e42)

2024-07-02 01:01 UTC, EvilDragonfiend approved these changes

2024-07-03 02:04 UTC, merged