tonfa now paralyses rather than sleeps, stunbaton only shoves on disarm
BeeStation/BeeStation-Hornet pull request #11169
Opened 2024-07-10 14:36 UTC by ToasterBan

## About The Pull Request
as it says on the tin, tonfa aiming head now (with the exact same requirements and timer) paralyses rather than knocks out

stunbaton has their "shove" mechanic only apply on disarm intent

## Why It's Good For The Game
being forced to sleep is a really unfun mechanic, and being paralyzed is practically identical but at the very least you can see, listen and talk

I heard a lot of people disliked baton shoving so making it optional probably a good idea

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

[Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.
](https://github.com/BeeStation/BeeStation-Hornet/assets/54711687/646c28e0-db55-4907-b580-83aa6ac07a0e)
</details>

## Changelog
:cl:
tweak: Aiming head with a tonfa will paralyze rather than put the target to sleep
tweak: batons only shove while in disarm intent now
/:cl:

2024-07-10 14:43 UTC, TsunamiAnt commented
can you make them stammer and twitchy like the baton does? As it is it's really hard to tell when the effect wears off.

2024-07-10 22:42 UTC, tontyGH commented on code/game/objects/items/stunbaton.dm
Shoving someone back would also be helpful with harmbaton as well, but there are also situations where you want to use harmbaton without shoving them

Might be out of scope, but maybe you could make it so that grab intent also harms the target, then make harm intent push back? So it would be like
|       Intents          | Cannot Shove | Can Shove |
| :---:  | :---: | :---: |
| **Cannot Harm** | Help | Disarm
| **Can Harm** | Grab | Harm

Granted this also creates a problem with shuffling on help intent...

2024-07-10 23:00 UTC, DarnTheMarn commented on code/game/objects/items/stunbaton.dm
That seems needlessly convoluted for a rare situation. I would just leave it as is as it makes the most sense. Help is normal, disarm is aggressive with defense, harm is aggressive with offense, grab doesnt count because you cant grab with a weapon.

2024-07-10 23:10 UTC, ClownMoff commented
ANTI KEY PROTECTION COMMENT

THIS PR CAN'T BE KEYED

2024-07-11 04:20 UTC, ToasterBan commented on code/game/objects/items/stunbaton.dm
this is honestly just too complicated for the "simpler" weapon of the pair

2024-07-11 17:37 UTC, tontyGH commented on code/game/objects/items/stunbaton.dm
Fair enough

2024-07-11 18:30 UTC, ToasterBan commented
> Not a nerf so keyed

technically it is a nerf since tonfas now no longer prevent voice activated grenades and the sorts

2024-07-13 13:49 UTC, Rukofamicom commented
> can you make them stammer and twitchy like the baton does?

This is because of electrocution and wouldn't really make sense for the tonfa.

2024-07-13 13:49 UTC, Rukofamicom approved these changes
👍 

But waiting a bit for opposition if any exists to hear it out in this case.

2024-07-13 22:05 UTC, TsunamiAnt commented
> > can you make them stammer and twitchy like the baton does?
> 
> This is because of electrocution and wouldn't really make sense for the tonfa.

My man you are absolutely BEANING the guy over the head hard enough to crumple him to the ground instantly and keep him there for a few seconds.

He would be stammering as hell. 

Hell give him 20 brain damage or something.

2024-07-14 12:14 UTC, PowerfulBacon requested changes
Separate the stunbaton and tonfa changes. I want to merge the tonfa changes but not the stun-baton ones

2024-07-14 13:10 UTC, DarnTheMarn commented
Why wouldn't you want the stun baton change, security and non security people alike want that change

2024-07-14 13:27 UTC, PowerfulBacon requested changes
You removed the wrong part of this PR

2024-07-14 13:27 UTC, ToasterBan commented
whoops

2024-07-14 15:50 UTC, PowerfulBacon commented
Now you have the stun baton changes back

2024-07-14 18:20 UTC, PowerfulBacon approved these changes

2024-07-14 18:29 UTC, merged