MORE SHUTTLES
BeeStation/BeeStation-Hornet pull request #11189
Opened 2024-07-14 15:37 UTC by ClownMoff

## About The Pull Request

3 more shuttles

## Why It's Good For The Game

The rage cage and the casino are non antag alternatives to the regular shuttles.

The Ultra Raven shuttle is a EXPENSIVE shuttle you call when you are dealing with a major threat and you need a way to 1.- GTFO and 2.- Minimize damage and maximize recovering people. It's the ultimate big thing you can get as crew that doesnt involve admin intervention, but you need 70k to order it. Comes with a insanely equiped medbay and an armory in the brig. I'm down to increase the prize even more, but I think a shuttle like this is an unique addition to the game that would reward shifts that have tons of money

## Changelog
:cl: Varo
add: Added 3 shuttles: The Emergency Casino, THE RAGE CAGE and the Emergency Ultra Centcom Raven 
/:cl:

2024-07-14 15:51 UTC, TsunamiAnt commented
could you add some oxy canisters to the ultra raven? In case of shuttle bombings the damage itself is usually repaired quickly, but all the air lost cannot be refilled.
Specifically oxy cans, because there's no way you can get full pressure with just a few cans. So pure oxy at lower pressure must do.

2024-07-14 16:00 UTC, ClownMoff commented
![imagen](https://github.com/user-attachments/assets/b52448cb-dcf4-4295-92b2-89d40eb3d542)

Are 2 enogh?

2024-07-14 18:48 UTC, spockye requested changes
Starting with the casino.
im sorry but i really dont like it. its golden walls, golden floors, chairs and slot machines spammed everywhere, even infront of the doors, and a box on the side for medical. 
theres no lights, no decalling, no windows, its just a square. personally i think it might be best to remove it from the PR. if not that a complete redo. 

The Ragecage shuttle
im kinda having some of the same problems with this one as i have with the casino. little to no decalling, mostly empty, and its pretty plain. i dont think it really brings much to the table, since we already have the fighting arena on the ruski shuttle. 

Now, on the ultraraven it might just be personal opinions but. 
im not really a huge fan of the idea. its just a larger version of the raven, and the raven is already a amazing and powerful ship. i really dont think this version is necessary. a full armoury, two medbays. and im not a fan of how its laid out. i think it'll just end up being one of those things that cause a lot of issues at the end of rounds. 

im sorry that this review is pretty negative, but i just felt i should say my two cents on the matter. if people disagree with me then thats totally fine!. 

i'll include some issues not stated above under here:

<details>
<summary>requested changes</summary>
<br>

![image](https://github.com/user-attachments/assets/2e22ff39-cb43-48c4-834e-fc08b405b62f)
firelock in space

![image](https://github.com/user-attachments/assets/d403c02d-19de-4262-9f3b-20754948e74a)
i dont think airlocks need firelocks

![image](https://github.com/user-attachments/assets/f60147da-c8a6-44e0-85d9-36a13f2dfc26)
i think the turrets are facing the wrong way

![image](https://github.com/user-attachments/assets/c0f2bbe9-275c-4b92-ab29-b97c66ffb880)
something weird going on with the walls here

![image](https://github.com/user-attachments/assets/53d7d19e-83f8-4938-b1e8-f0825063b41e)
why is there a window here?

![image](https://github.com/user-attachments/assets/2f4fad67-f102-4291-80be-0284ab3e72b3)

one firelock shutter, one armoury shutter with a blast door under, one with just a shutter and one with just a door? something weird is going on here. 

![image](https://github.com/user-attachments/assets/be91cf6c-8fd1-4584-bb10-9e3baf77383a)
these buttons are floating off the table

![image](https://github.com/user-attachments/assets/5fb867fe-1624-46e5-a8a1-397928c05d69)
this room seems pretty empty and pointless, with there being another giant medbay in the middle. 

![image](https://github.com/user-attachments/assets/f2b68fd8-cab0-4176-9f44-509b2feb5d3e)
i'd recommend giving your Shutters more unique ID's. hard to find later, and im unsure if that might conflict with other buttons

![image](https://github.com/user-attachments/assets/564ff3c4-4b91-4084-9173-6a1734ed30ff)
wild pipe

![image](https://github.com/user-attachments/assets/e3f9e396-aa98-41a4-aaf5-f6b7d9beb03c)
airlock isnt access locked

![image](https://github.com/user-attachments/assets/c29ca259-8bf3-47e7-825e-75a972834f01)
this feels VERY empty

![image](https://github.com/user-attachments/assets/80b4eb01-348d-403c-96ed-90bd0e54fc73)
door stuck

![image](https://github.com/user-attachments/assets/8a8b6688-07c0-4f1f-940d-93fdf990cd32)
potentially moving around in this would be very akward. the floors also hurt my eyes



</details>

2024-07-16 15:07 UTC, ColonelOrion commented
Let's go gambling!

2024-07-16 21:43 UTC, MarkusLarsson421 commented on _maps/shuttles/emergency/emergency_ultraraven.dmm
> +	id = ""shuttleevashutter"";
The cause of the MapDiffBot2 error. Remove the double double quotation marks. Either in the editor or in the text file.

2024-08-25 11:15 UTC, PowerfulBacon commented on _maps/shuttles/emergency/emergency_casino.dmm
![image](https://github.com/user-attachments/assets/1f8b9c69-c154-4eb0-9d7c-1fc5569cb0f3)

Missing window

2024-08-25 11:15 UTC, PowerfulBacon commented on _maps/shuttles/emergency/emergency_casino.dmm
![image](https://github.com/user-attachments/assets/b8cf7355-0b33-48ed-9d93-cc613c55ecd3)

Not a fan of the design of this area, bring the right side in and make the room smaller

2024-08-25 11:15 UTC, PowerfulBacon commented on _maps/shuttles/emergency/emergency_casino.dmm
![image](https://github.com/user-attachments/assets/2eeeb531-0fd9-45be-a13c-17b6ca2a3926)

Window with a wall behind it

2024-08-25 11:15 UTC, PowerfulBacon commented on _maps/shuttles/emergency/emergency_casino.dmm
The engine layout and shape of this shuttle just don't really work very well, it doesn't look very... shuttle-y

2024-08-25 11:15 UTC, PowerfulBacon commented on code/datums/shuttles.dm
> +	credit_cost = 7500
This needs to be restricted.

2024-08-25 11:15 UTC, PowerfulBacon commented on code/datums/shuttles.dm
> +	description = "WE ARE RAGING! WE ARE CAGING! TIME TO UNLEASH ALL THE STRESS GENERATED DURING THE SHIFT! Comes with a Brig, Medbay and Cockpit included."
Tone down the text a little bit. This is a roleplay server and feature still need to make sense in the world.

2024-08-25 11:15 UTC, PowerfulBacon commented on _maps/shuttles/emergency/emergency_ragecage.dmm
Engine pods need a rework, would rather have walls separating them.

2024-08-25 11:15 UTC, PowerfulBacon commented on _maps/shuttles/emergency/emergency_ultraraven.dmm
Everything about this shuttle just seems so unnecessary, it's far too big and the shape looks like 3 shuttles strapped together.

2024-08-25 11:15 UTC, PowerfulBacon commented on _maps/shuttles/emergency/emergency_meta.dmm
Big fan of this shuttle, really like the changes and its a big improvement. Seems like there are some issues with the engine block having some missing engines.

2024-08-25 11:15 UTC, PowerfulBacon commented on _maps/shuttles/emergency/emergency_box.dmm
Going to go ahead and say that I don't like this new shuttle design as a default shuttle, default shuttles should be very blank and boring and exist for the purpose of escaping the station and that alone. The size needs to be significantly reduced and the shuttle needs to be more standard.

My immediate suggestions would be:
- Cut the width of the shuttle down from the bar point onwards.
- Move the bridge over into the space where the T shaped walkway is, to support the size reduction of the shuttle.
- Remove the middle seats, and have 2 rows of vertical seats.

2024-08-28 14:17 UTC, PestoVerde322 approved these changes
Seems all good to go, approved.

2024-09-26 15:27 UTC, merged

2024-09-27 22:51 UTC, Rukofamicom commented
This PR contains undocumented changes.

A fresh coat of paint should not include new items without documenting them for proper consideration. Making undocumented changes can result in repo bans if it is determined the information was intentionally withheld. 

I'm referring to the expansion of medbay capabilities via adding defib.