DeltaStation2 New Brig (and minor fixes/adjustments - Fluked PR edition
BeeStation/BeeStation-Hornet pull request #11218
Opened 2024-07-20 19:47 UTC by PestoVerde322

## About The Pull Request

_This is literally the same pr as  #10697, same ordeal really, I fluked up the original PR, so here we are._

This PR overhauls completely the brig for Delta2, and also rearrange some stuff to fit more the overall aesthetic and functionality of the brig, this also modifies the crew quarters a bit and the cargo dock, while also fixing some leftovers from other PRs.

## Why It's Good For The Game

Better map good? (and less Git flukery, hopefully so)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![309774377-958026ed-6b4e-4278-bb3f-1c3b983a5348](https://github.com/user-attachments/assets/b20ae6d0-3e01-4f48-8c1c-d811374ef357)

</details>

## Changelog
:cl:
add: [DeltaStation2] Rearranged essentially amost all of the brig surroundings and the brig itself
fix: [DeltaStation2] Removed some misc leftovers
/:cl:

2024-07-21 18:43 UTC, spockye requested changes
![image](https://github.com/user-attachments/assets/91694ced-ff5d-4eb9-b289-546dbf558138)

small cabling error. couldnt find anything else at the moment!

2024-07-22 16:55 UTC, spockye approved these changes

2024-08-01 17:27 UTC, spockye requested changes
![image](https://github.com/user-attachments/assets/6a3bbc4f-bba3-4958-b4fd-4af2e48d3bd5)

the button doesnt unbolt the door

![image](https://github.com/user-attachments/assets/1d04abbb-bc94-4f6b-85dc-501c5056a367)

now this cant be right...

![image](https://github.com/user-attachments/assets/2cb528b3-634c-43b7-ad5a-4d467708e142)

A lot of floating APC's around. 

![image](https://github.com/user-attachments/assets/de7eba5e-152e-4f5f-994c-d1f137112ae9)

three apc's in one area. 

everything else looks good though!

2024-08-31 21:02 UTC, PowerfulBacon commented
![image](https://github.com/user-attachments/assets/ac7a5d65-63a2-4dbb-a7bc-8c44c88d1e14)

Is it meant to have these?

2024-08-31 21:16 UTC, PowerfulBacon approved these changes

2024-08-31 21:24 UTC, PowerfulBacon approved these changes

2024-08-31 21:38 UTC, merged