Made electric vehicles no longer ignore EMPs
BeeStation/BeeStation-Hornet pull request #11234
Opened 2024-07-25 15:17 UTC by XeonMations

## About The Pull Request

Made electric vehicles, such as the secway, the janicart, the ATV and the electric wheelchair no longer ignore EMPs

## Why It's Good For The Game

Electrical vehicles should not bypass EMPs, as EMPs are made to disrupt electrical connections. Also gives vehicles atleast one downside now.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Multiple vehicles no longer ignore EMPs:

https://github.com/user-attachments/assets/1c467a2a-27a3-4c9a-8a47-0b74c42e4435

Visual effect added:

https://github.com/user-attachments/assets/02b060c0-77f9-4241-be0f-32a92ee6d6b9

</details>

## Changelog
:cl: XeonMations
balance: Electric vehicles such as the janicart, secway, electric wheelchair and ATV now are affected by EMPs
/:cl:

2024-07-26 21:42 UTC, zeskorion commented
how long does it last

2024-07-30 19:29 UTC, PowerfulBacon requested changes

2024-07-30 19:29 UTC, PowerfulBacon commented on code/datums/components/riding.dm
> +	addtimer(CALLBACK(src, PROC_REF(reboot)), 300, TIMER_UNIQUE|TIMER_OVERRIDE) //if a new EMP happens, remove the old timer so it doesn't reactivate early
Adjust the time according to the severity (Higher severity is less severe, so divide 300 by severity)

2024-07-30 19:29 UTC, PowerfulBacon commented on code/datums/components/riding.dm
It would be nice to have some feedback when they get disabled, perhaps a particle effect, a smoke trail or a noise or something.

2024-07-31 20:05 UTC, PowerfulBacon requested changes

2024-07-31 20:05 UTC, PowerfulBacon commented on code/datums/components/riding.dm
> +	AM.add_emitter(/obj/emitter/fire_smoke, "smoke")
This should only be added if the thing is actually empable

2024-08-01 08:14 UTC, PowerfulBacon approved these changes

2024-08-01 08:23 UTC, merged