Cyborg Plushies!!
BeeStation/BeeStation-Hornet pull request #11269
Opened 2024-07-31 10:01 UTC by MarkusLarsson421

## About The Pull Request
Adds six cyborg plushies for AIs, Roboticists and other Sillycon lovers.

They currently all do one out of four random cyborg noises.

## Why It's Good For The Game
More plushie representation for non-moths players.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/2e871972-7ba0-48dd-a013-5aef76f41ebf

![image](https://github.com/user-attachments/assets/852b56b8-41c3-49c1-82c8-a95aa24375bc)

</details>

## Changelog
:cl:
add: Added Cyborg plushies!!
/:cl:

2024-07-31 10:03 UTC, MarkusLarsson421 commented
15 cyborgs kind of breaks the sound engine, making it a bit weird. Unsure if I should try to fix this or not? Might be out of the scope for this PR.
![image](https://github.com/user-attachments/assets/b54d6943-d7ea-4c07-88c1-f93203081c36)

2024-07-31 10:07 UTC, BriggsIDP commented
Very cute! Please replace the plushie on the ai core of rad with the piecekeeper!

2024-07-31 19:36 UTC, MarkusLarsson421 commented
Just got to make the Mediborg inject the user with a tiny amount of morphine, then this PR will be perfect!

2024-08-03 20:10 UTC, PowerfulBacon commented on code/game/objects/items/plushes.dm
> +/obj/item/toy/plush/sillycons/
```suggestion
/obj/item/toy/plush/sillycons
```

2024-08-05 10:48 UTC, Rukofamicom approved these changes

2024-08-05 13:27 UTC, PestoVerde322 approved these changes

2024-08-05 23:00 UTC, PestoVerde322 requested changes
Missing Inhand Dir icons.

![immagine](https://github.com/user-attachments/assets/a545cdcc-2bf6-417d-970d-8d7f237f262d)

2024-10-04 00:24 UTC, closed without merging