New Trait: Pet Lover
BeeStation/BeeStation-Hornet pull request #11341
Opened 2024-08-18 12:24 UTC by ClownMoff

## About The Pull Request

Title

## Why It's Good For The Game

Everyone needs a best friend

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![imagen](https://github.com/user-attachments/assets/712a2193-ef32-4bde-9f72-f8d23f09269d)

</details>

## Changelog
:cl:
add: New trait: Pet lover. Comes with a pets beacon to summon a new friend.
/:cl:

2024-08-18 12:38 UTC, ClownMoff commented
I wasn't able to make it so you can name the pet before the wheel appears and I don't know if you can make it so you can do it after you select an option you can name it before the package is sent. If someone wants to help, it would be appreciated.

2024-08-18 12:48 UTC, EvilDragonfiend requested changes

2024-08-18 12:48 UTC, EvilDragonfiend commented on code/game/objects/items/miscellaneous.dm
> +		/mob/living/carbon/monkey,
No

2024-08-18 12:48 UTC, EvilDragonfiend commented on code/game/objects/items/miscellaneous.dm
> +		/mob/living/simple_animal/hostile/retaliate/clown/lube,
no

2024-08-18 12:48 UTC, EvilDragonfiend commented on code/game/objects/items/miscellaneous.dm
> +		/mob/living/simple_animal/hostile/retaliate/goat,
no

2024-08-18 12:49 UTC, EvilDragonfiend requested changes

2024-08-18 12:49 UTC, EvilDragonfiend commented on code/game/objects/items/miscellaneous.dm
> +		/mob/living/carbon/monkey,
No

2024-08-18 12:49 UTC, EvilDragonfiend commented on code/game/objects/items/miscellaneous.dm
> +		/mob/living/simple_animal/hostile/retaliate/clown/lube,
No

2024-08-18 12:49 UTC, EvilDragonfiend commented on code/game/objects/items/miscellaneous.dm
> +		/mob/living/simple_animal/hostile/retaliate/goat,
No

2024-08-18 12:49 UTC, EvilDragonfiend commented
aw, github doesn't recognise one line change

2024-08-18 12:55 UTC, ClownMoff commented
Why not?

2024-08-18 13:12 UTC, EvilDragonfiend commented
> Why not? I can see the clown reasoning but you can already get a monkey at hydroponics desk, why cant you get another as a pet?

quirks are not supposed to provide such high impacting gameplay beneficial when it can provide a lot of flexibility.
* Monkey: you can pick monkey when you just specifically need one rather than having other pets.
* Goat: Good for against vines
* Clown: just no. you know why alraedy.

2024-08-18 13:16 UTC, ClownMoff commented
Fine

2024-08-19 08:47 UTC, PowerfulBacon reviewed
Also remove the rare pets, the rare corgis and rare kittens.

2024-08-22 00:29 UTC, ClownMoff commented
I did btw

2024-08-26 07:25 UTC, PowerfulBacon commented on code/datums/traits/positive_quirk.dm
> +	Z.equip_to_slot_or_del(new /obj/item/clothing/neck/petcollar(Z), ITEM_SLOT_BACKPACK)
Improve variable naming, single letter naming is inadequate

2024-08-26 07:25 UTC, PowerfulBacon commented on code/game/objects/items/miscellaneous.dm
> +	return item_list
Ditto

2024-09-04 16:46 UTC, RDS88-beeman commented
lizard please

2024-09-15 02:44 UTC, Nakalon commented
pretty cool now i can shove my own pet into washing machines

2024-10-04 15:25 UTC, Rukofamicom commented
I'm not strictly against this being added so the key can be ignored by other maints, but I don't think this adds meaningful content to the game and is mostly just a little more bloat.

When discussing with head coder I was told it is appropriate to key PRs I feel this way about instead of leaving them stuck in limbo with no reviews.

2024-10-22 08:31 UTC, EvilDragonfiend requested changes
`TRAIT_PETLOVER` is not necessary

2024-12-22 22:52 UTC, Tsar-Salat reviewed
I find PRs like this problematic if they already have a use through interacting with departments.

IC, pets are generally a departmental thing, with the ability to add more through cargo.

I don't really see the purpose of this pr. Maybe if it came with a trauma for protecting the pet and the pet being a detriment to the player, and it dying being a major blow. I think that will be creative way to implement this.

It just being a pet beacon for 1 point is boring.

2025-01-14 18:36 UTC, closed without merging