Pacifies all pets spawned by Xenobiology's Stabilized Gold
BeeStation/BeeStation-Hornet pull request #11350
Opened 2024-08-20 13:24 UTC by aramix273

## About The Pull Request
for all I can tell, the pet spawned by stabilized gold should be a pacifist
the pseudo-immortality is biggest argument in this sense
it's still a good question why there are hostile animals in friendly paths and why they have the FRIENDLY_SPAWN tag despite their attacks (perhaps referring to their default AI rather than capacity to harm, which is kind of an edge case considering sentience)

## Why It's Good For The Game

you can no longer have stabilized gold pets that can bite and poison you then come back each time you kill them
though they can still ventcrawl, pull and strip
took this route rather than removing the snake and lizard from the pool outright because:
- it allows them to be pets still,
- this should cover any other cases if pets were to be added to this

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/d21432e3-595f-4e47-93a8-e3c9f3d5dcf3

</details>

## Changelog
:cl: Aramix
tweak: pacified all pets spawned by Xenobiology's Stabilized Gold
/:cl:

2024-08-20 13:26 UTC, aramix273 commented
should ideally solve #11328 too (testing evidence shows so) while keeping code/mechanic changes local to stabilized gold and without modifying ``simple_animal`` code

2024-08-20 15:43 UTC, EvilDragonfiend commented
why don't you just give them pacifist trait?

2024-08-20 22:42 UTC, aramix273 commented
> why don't you just give them pacifist trait?

did not come to mind to use it
apparently the parrot does not care about the proc that I registered that is supposed to cancel attacks
so, pacifism would help, albeit only for attacking mobs
apparently, even though the parrot has 0 ``obj_damage``, it can still hurt walls and other structures while ``melee_damage`` is non-zero,, so that has to be set to 0 too

2024-08-20 23:15 UTC, aramix273 commented
applied my last observations and had to handle a particular case of parrots being able to just change their ``melee_damage`` via "Toggle Mode"
this is getting a bit convoluted for the purpose of also disabling such a pet's capacity to damage structures, so if the PR's scope or implementation is getting a bit snowflakey, it could be reduced to pacification against just mobs, at expense of potential later abuse to break structures such as consoles or whatnot

2024-08-22 04:56 UTC, EvilDragonfiend requested changes

2024-08-22 04:56 UTC, EvilDragonfiend commented on code/modules/research/xenobiology/crossbreeding/_status_effects.dm
> +		familiar.a_intent = "help"
INTENT_HELP

2024-08-22 16:57 UTC, EvilDragonfiend approved these changes

2024-09-01 11:38 UTC, RDS88-beeman commented
As (I would like to imagine) the primary abuser of this bullshit, please hit burning yellow next.

2024-09-01 11:58 UTC, merged