[Port] Radiation Rework
BeeStation/BeeStation-Hornet pull request #11434
Opened 2024-09-06 00:05 UTC by XeonMations

## About The Pull Request

Ports TG Station's:
- https://github.com/tgstation/tgstation/pull/62265
- https://github.com/tgstation/tgstation/pull/62588
- https://github.com/tgstation/tgstation/pull/62550
- https://github.com/tgstation/tgstation/pull/62695
- https://github.com/tgstation/tgstation/pull/63015
- https://github.com/tgstation/tgstation/pull/63152
- https://github.com/tgstation/tgstation/pull/63230
- https://github.com/tgstation/tgstation/pull/64369
- https://github.com/tgstation/tgstation/pull/66305
- https://github.com/tgstation/tgstation/pull/67337
- https://github.com/tgstation/tgstation/pull/68525

## Why It's Good For The Game

Currently radiation has no proper warnings when you're irradiated, not to mention it takes way too long to get rid of it if you are contaminated. This should fix a few things, while keeping things, hopefully, sane.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: Mothblocks, ShizCalev, KittyNoodle, Krysonism, castawaynont, GuillaumePrata, Tiresoup, blessedmulligan, Pickle-Coding, LemonInTheDark, XeonMations
balance: Radiation is now a status effect, where you are either irradiated or not. When irradiated, you will take constant toxin damage, and irregular burn damage. Radiation is removed once all toxin damage is healed. Standing under a shower will pause the harmful effects of radiation, making it easier to heal. Everything that is irradiated will glow green.
/:cl:

2024-09-06 00:55 UTC, Tsar-Salat commented
Well, at least its now possible to integrate actual radiation shielding into modsuits

2024-09-09 14:17 UTC, MarkusLarsson421 commented
> Currently radiation has no proper warnings when you're irradiated

Isn't that how radiation works? It is known as the silent death.

2024-09-13 12:49 UTC, XeonMations commented
And now to fix the SM...

2024-09-28 23:48 UTC, Rukofamicom commented
I'm not a fan as a whole, but I'm open to being convinced of the benefits. 

I'd be alright with the removal of the contamination system because it's probably needlessly expensive (I haven't actually checked though) and also contributes greatly to the problem of "invisible" radiation poisoning, but I still much prefer a system where radiation builds up with worsening effects over time as it does. 

I'd be okay with the effects of it building being more apparent and/or the removal of radiation being more simplified, but I don't agree with a more or less total removal of radiation as a mechanic at all. 

:key:

2024-10-25 07:46 UTC, PowerfulBacon commented
Radiation is a horrible mechanic and is almost always hated when it actually becomes a threat. I'd be more than happy to see it improved into something that gives the players being abused by it some respect

2024-10-25 11:32 UTC, Rukofamicom commented
> I'd be more than happy to see it improved into something that gives the players being abused by it some respect

I'd be happy with an indicator of being radiated too, but it should be more in line with bleeding that stacks, not a binary on/off with no special treatment.

2024-10-25 18:37 UTC, PowerfulBacon commented
That would be nice, I was thinking it'd be good to have a counter in the same way as bleeding. It could even cheat like bleeding and have an upper limit without telling the player

2024-11-15 17:48 UTC, PowerfulBacon requested changes
## Supermatter Power Output

The power output from the SM is ridiculous, and the radiation it makes is huge.
With a roundstart N2 setup:

![image](https://github.com/user-attachments/assets/4b8db5e9-1e86-4fe0-ba1a-1d444017e535)

And radiation filled the entire room until this point

![image](https://github.com/user-attachments/assets/39084517-7f2d-41e4-87c9-255fbf9267cc)

## Radiation Effects

I dislike how clearing radiation works. Here is my feedback:
- Make radiation like the bleeding status effect, where it has an amount attached to it (give it a limit)
- Tick the counter up as you increase radiation instead of using a prob() that randomly gives the effect
- If the effect is less than a threshold, don't throw the alert and do nothing (at this point it should slowly decrease over time until it goes away)
- One you are at a certain amount, then start doing the toxin damage
- Showering lowers that value, all the rad-meds lower the value of radiation. (Maybe either no toxin damage should increase the rate at which rads go away, or washing/changing clothes should somehow have an effect, but the clothes one is harder and may be out of reasonable scope).
- Remove the halting of the effect entirely
- If you get a lot of rads and start approaching the limit, then start doing some of the other radiation fluff like nosebleeds and hair clumps falling out (these don't have to actually do anything, but are there for flavour)

2024-11-15 17:48 UTC, PowerfulBacon commented on code/datums/components/irradiated.dm
> +		human_parent.dna?.species?.handle_radiation(human_parent, world.time - beginning_of_irradiation, delta_time)
Having a stat greater than dead is impossible

2024-11-15 17:48 UTC, PowerfulBacon commented on code/__DEFINES/traits/declarations.dm
> +#define TRAIT_RADBOOSTER "rad_booster"
The name of this trait doesn't really make much sense. I also think that theres a bit of an issue where if you have a species that heals from rads and forget to put the trait that stops you from getting the irradiated component then your species will get permanent immunity which is a bit of a trap for future coders but I guess its fine

2024-11-15 17:58 UTC, PowerfulBacon commented on code/__DEFINES/traits/declarations.dm
> +#define TRAIT_RADBOOSTER "rad_booster"
I see what the intention is for this now, TRAIT_ALWAYS_PROCESS_RADS, TRAIT_BENEFICIAL_RADS or something might make more sense

2024-11-24 05:20 UTC, XeonMations commented
Making this a draft once more, will need to work on this a lot after LINDA is done.

2024-12-06 15:53 UTC, XeonMations commented
was told to close this until i decide to work on it once more

2024-12-06 15:53 UTC, closed without merging

2024-12-06 16:15 UTC, Rukofamicom commented
Took away the stale label so you should be able to freely re-open it without issues when you do get to it