Randomizes the interval between silicon law stating.
BeeStation/BeeStation-Hornet pull request #11431
Opened 2024-09-05 15:12 UTC by JixS4v

## About The Pull Request

Makes it so the interval between laws stated for borgs varies a bit between 1 and 3 seconds.

## Why It's Good For The Game

Now people manually typing laws is slightly less obvious. 

## Testing Photographs and Procedure

https://github.com/user-attachments/assets/53a05e01-2eb1-443d-96cd-6b4193576512

## Changelog
:cl:
tweak: The delay in between silicon laws stated is slightly randomized
/:cl:

2024-09-05 16:46 UTC, MarkusLarsson421 commented
Can you have it show a speech bubble too? As if you see it flash up it would be obvious they are copy-pasting or typing it.

2024-09-06 13:10 UTC, JixS4v commented
> Can you have it show a speech bubble too? As if you see it flash up it would be obvious they are copy-pasting or typing it.

manually manipulating the typing indicator is a pain in the ass

2024-09-09 05:42 UTC, ColonelOrion commented
Unbelievably based.

2024-09-15 02:39 UTC, Nakalon commented
I believe this could be even more like 5 or 6 seconds, i always thought it was odd they were instant

2024-09-20 03:49 UTC, EvilDragonfiend requested changes

2024-09-20 03:49 UTC, EvilDragonfiend commented on code/modules/mob/living/silicon/silicon.dm
> +	addtimer(CALLBACK(src, PROC_REF(finished_stating_laws), S, total_laws_count), total_time)
```suggestion
	addtimer(CALLBACK(src, PROC_REF(finished_stating_laws), S, total_laws_count), total_time + 1)
```
just in case

2024-10-04 00:23 UTC, closed without merging