despaces prison on fland
BeeStation/BeeStation-Hornet pull request #11472
Opened 2024-09-11 01:35 UTC by HowToLoLu

## About The Pull Request

Fixes a hole in fland introduced by #11364

## Why It's Good For The Game

Space, the final frontier. I don't think anyone can breathe it though. so I think it *might* be safer to seal it off.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/user-attachments/assets/37e8d04b-8009-4619-8ebd-144cd91eb14e)

</details>

## Changelog
:cl:
fix: [FlandStation] The prison is no longer exposed to space roundstart.
/:cl:

2024-09-11 16:24 UTC, PowerfulBacon requested changes
Could you add a test in `tools\maplint\lints`

It needs to read
```
/turf/open/space
  banned_neighbors:
  - /obj/machinery/door
  - /obj/effect/spawner/structure/window
```

and then we can expand on it in the future.
You can put an = before the typepath if you don't want to match subtypes

2024-09-11 16:38 UTC, MarkusLarsson421 commented
Wouldn't banning space next to windows cause a ton of issues?

2024-09-11 16:49 UTC, HowToLoLu commented
> Wouldn't banning space next to windows cause a ton of issues?

It wasn't for banning windows next to space, it was banning window tiles and doors *on* space.

2024-09-12 07:43 UTC, spockye approved these changes
approved map-wise

2024-09-12 16:37 UTC, PowerfulBacon approved these changes
Good catches

2024-09-12 16:48 UTC, merged