Makes Ashwalkers, Lifebringers and Free Golems always spawn
BeeStation/BeeStation-Hornet pull request #11489
Opened 2024-09-14 05:02 UTC by Programs-The-Station

## About The Pull Request

Since we have been on a "get players back into the game via ghost roles", you would think it would be a good idea to have the premiere Lavaland ghost roles readily available, but the available threat for them is often taken up by Megafauna or Biodome/Lavaland Vets.

This PR simply sets the always_place flag to always place the necessary ruins to get the good ghost roles on LL.

To Maintainers: I did this mostly because I ded and tired of having no good ghost roles. If this is not wanted, it can be closed, but it took me literally longer to write this paragraph than it did to actually implement this change and test it.

## Why It's Good For The Game

Getting players back into the game is always good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/user-attachments/assets/16f7732a-9933-404e-9335-e3962595f956)

</details>

## Changelog
:cl:
tweak: Ashwalkers, Free Golems, and Lifebringers always spawn on Lavaland now.
/:cl:

2024-09-14 07:12 UTC, MarkusLarsson421 commented
Problem is that this gets them back onto Lavaland and not the station. Lavaland roles are primarily to allow a space for new people to learn parts of the game. Like Syndicate Scientists, Pod People, Free Golems, and so on. This might just make people go to play those roles on-round start rather than play as a crew member on the station.

2024-09-14 08:40 UTC, PowerfulBacon commented
Really only 1 of these needs to always spawn and they should be in a group to add some variation

2024-09-14 13:50 UTC, Rukofamicom requested changes
This should only be Ashwalkers, with golems and lifebringers remaining random, and as an option for players to learn new mechanics in (mostly) non-disruptive ways. 

I'd previously discussed making Ashwalkers a permanently static spawn on lavaland with Bacon and just never got around to making the PR.

2024-09-14 19:01 UTC, Rukofamicom approved these changes

2024-09-15 00:05 UTC, Crow004 commented
I like this idea i feel like we have few ghost role opportunities sometimes

2024-09-15 03:22 UTC, merged