Smartwires: Cable management & powernet improvements
BeeStation/BeeStation-Hornet pull request #11503
Opened 2024-09-15 19:17 UTC by PowerfulBacon

This PR is still in early development, I am opening it to keep track of work.
- [ ] Fix power consuming machines and how they connect to powernets
- [ ] Find a way for multiple cable colours to join up
- [ ] Try to find a way to allow for multiple different cable colours to run along the same tile
- [ ] Work out how shuttle movement should work
- [ ] Mapping updates
- [ ] Drop cable coil when cutting
- [ ] Fix clicking on a cable not making a new node

## About The Pull Request

Simplifies a large portion of the code for powernets, optimising it a bunch (It was doing some really silly things before).

Simplifies the behaviours for placing cables, to make laying cables significantly easier. You no longer need to be super precise with your clicks, and can just lay cables down by clicking on a turf adjacent to another cable.

Cable laying works in the following way:
- Cables will automatically connect to directly adjacent cables of the same colour.
- Cables will automatically remove their nodes when joined to an adjacent cable.
- If a cable has a machine connected to its node, then the node will not be removed.
- You can use a cable on a turf that already has a cable to manually force that cable tile to have a node in it.

Cable code now works in the following way:
- Powernet reconsolidation is part of machines processing, rather than an asynchronously invoked method
- Powernet reconsolidation runs prior to power machines running, to make sure they are up to date before running power.

https://github.com/user-attachments/assets/e4aa4d68-0e01-428c-a714-0a28e7472293

This is a simple demonstration, there are still a few things todo (notably making them drop cables and remove the debugging maptext)

## Why It's Good For The Game

## Testing Photographs and Procedure

## Changelog
:cl:
tweak: Simplifies cable management by changing how we place cables.
/:cl:

2024-09-15 20:00 UTC, Tsar-Salat commented
> del: Removes the rapid cable layer, since it's no longer useful anymore.

Theres a mech RCL in mech equipment too that I deprecated a few months back. Just commented out.

Mind nuking that too?

2024-09-16 07:06 UTC, PowerfulBacon commented
If you are in help intent, wires should be laid if you click on pipes and other objects

2024-09-22 15:49 UTC, PowerfulBacon commented
screwdriver on the window doesn't block the attack chain

2024-09-22 15:54 UTC, PowerfulBacon commented
Putting cables into storages attempts to lay them on the ground

2024-09-22 15:54 UTC, PowerfulBacon commented
We're probably going to have to bite the bullet and refactor the interaction chain properly

2024-09-22 15:55 UTC, PowerfulBacon commented
ADMIN LOG: Error: /obj/structure/cable([0x2002a73]) took longer than 0.2 seconds to delete (took 0.2 seconds to delete).

2024-09-22 17:27 UTC, XeonMations commented
Issue report: Unable to place security holobarriers over wires. Plating or flooring with wires doesnt allow a barrier to be placed.

2024-09-22 17:58 UTC, PowerfulBacon commented
Maybe I'll abandon click fallthrough until a PR that does a full refactor of interactions, which I've been working on in the background.

2024-09-26 18:04 UTC, PowerfulBacon commented
Perhaps when a machine attempts to access a powernet, it should immediately reconsolidate the powernet. I saw someone wire solars correctly and then re-wire it since the solar controller didn't get the new items on the network quickly enough (although a significant amount of time passed so it should have, perhaps it was a bug with solar controller console).

2024-09-26 18:27 UTC, PowerfulBacon commented
![image](https://github.com/user-attachments/assets/e0493401-745a-49ac-8d87-8f1f84748ac5)

2024-09-26 20:52 UTC, PowerfulBacon commented
Apart from the above issues, the testmerge was very successful. Users seemed to find these a lot easier to use and gave generally positive opinions. Got lucky since a new player wired solars in the TM, so got some bits and pieces that could be improved design wise

2024-09-28 12:27 UTC, PowerfulBacon commented
![image](https://github.com/user-attachments/assets/6f035aea-d473-45a9-9feb-117cfc6c5d81)

Now working as intended

2024-09-28 21:19 UTC, PowerfulBacon commented
This makes cable recipes impossible to access

2024-09-29 10:24 UTC, PowerfulBacon commented
![image](https://github.com/user-attachments/assets/6e0e4504-11fa-48c7-ad60-84ac0a85cd79)

Cable ties are now craftable

2024-09-29 19:05 UTC, PowerfulBacon commented
Deltastation SM APC has 2 wires that cross each other on a supermatter node. It also seemed to cause some bugs when trying to remove that node, but it might be from the assumption that this situation shouldn't happen.
This should really be maplinted against.

2024-10-02 16:26 UTC, PowerfulBacon commented
This cannot be maplinted against. Will perform necessary map updates post-review, or when I feel like self-merging.

2024-12-13 03:20 UTC, mrmanlikesbt commented on code/datums/components/crafting/crafting_lists/structures.dm
> +	name = "Wall Mirror Frame"
wrong recipe name

2024-12-13 03:22 UTC, mrmanlikesbt commented on code/datums/components/crafting/crafting_lists/structures.dm
> +	name = "Wall Mirror Frame"
wrong recipe name

2024-12-13 18:24 UTC, PowerfulBacon commented on code/datums/components/crafting/crafting_lists/structures.dm
> +	name = "Wall Mirror Frame"
This shouldn't even be in here

2025-03-01 12:57 UTC, PowerfulBacon commented
Complexity is not depth. This system relies on changed behaviours of wires with the primary purpose of streamlining wire placement. The fundmantal differences mean that it is both difficult and pointless to add a system for fine wire placement and the new system for layering opens up wiring options that were previously impossible, or required the use of the fine wire placement system in a janky way.

2025-03-01 19:41 UTC, Therealdoooc213 requested changes
Please document the fact you removed nooses.

2025-03-02 16:24 UTC, PowerfulBacon commented
I don't intend to keep them removed, I just haven't bothered to copy the code across for the TM

2025-03-03 18:52 UTC, Rukofamicom requested changes
I see you already acknowledge it, just putting it as a blocking request so it doesn't get lost

Please either document the removal of nooses or fix them.

2025-03-18 00:20 UTC, closed without merging

2025-06-16 07:03 UTC, mrmanlikesbt commented
Seeing as this might be revived soon gonna post this here so you don't forget about this bug

https://github.com/user-attachments/assets/fcafcbae-2871-4806-a6c4-bcfed85b5203