Doubles the max character slots, ups beecoin and Byondmember additions accordingly.
BeeStation/BeeStation-Hornet pull request #11523
Opened 2024-09-18 22:27 UTC by Tsar-Salat

## About The Pull Request

This PR changes the amount of character slots available to players.

Default is now 10. 

Byond members get +6

Beeshop slot purchasers get +2

## Why It's Good For The Game

As a roleplay server, I think it is a terrible state of things that you can only have *three* characters as a normal player.

Some servers like Baystation have had dozens of character slots for years, whilst even some lower rp servers have also made a shift in letting people play more characters. 

My statement is this: An arbitrary limit on characters is an arbitrary limit on creativity. We want people to get immersed and create more characters that have interesting backstories or try new species, and not be worried about having to sacrifice one of their 3 character slots to do so. I've sacrificed numerous characters since I started playing in 2020, so this is something I am passionate about.

Before I made this pr, I went around and got feedback from others who also play multiple characters on the regular, and received pretty positive results. I think this will be a net good for us.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/user-attachments/assets/3c6b03eb-209a-4e08-b8ab-85797df70545)

</details>

## Changelog
:cl: rkz
config: The maximum number of character slots has been doubled from 9 to 18. Regular users will be able to access 10 of these slots, with Byond donors being able to access another 6, and those purchasing the beeshop character slots receiving the remaining two.
/:cl:

2024-09-18 22:29 UTC, EvilDragonfiend commented
DB affecting one. Needs crossed's approval.

2024-09-18 22:56 UTC, Tsar-Salat commented
If Crossed finds the current distribution excessive, I am also open to a base of 8, with +7 for byonders and +3 for beeshop slot purchase.

2024-09-18 23:09 UTC, ClownMoff commented
I have 4 slots and I find pretty anoyying having to change them if I want a one round character or playing someone different, I like having more options

2024-09-19 06:00 UTC, PowerfulBacon commented
Do normal donors not get extra slots?

2024-09-19 06:25 UTC, PowerfulBacon commented
10 seems like a lot, I'd go for 5 or 6 but keep the amount of donor slots high. If normal donors don't get extra slots along with byond members, I'd give them that too.

2024-09-19 08:29 UTC, Geatish commented
Good pr, before this you couldnt even have a separate character for each race

2024-11-23 16:45 UTC, ClownMoff commented
This PR has been open since September please discuss this already 😢 having only 4 characters is so tedious to play around

2025-01-03 23:57 UTC, Crossedfall commented on code/modules/client/loadout/loadout_ooc.dm
> +	C.prefs.max_save_slots += 2
Leave this as one, but make it purchasable up to two times.

2025-01-04 00:02 UTC, Crossedfall commented on code/modules/client/loadout/loadout_ooc.dm
>  	cost = 10000
Half the price

2025-01-04 00:03 UTC, Crossedfall commented on code/modules/client/preferences/preferences.dm
> +	var/max_save_slots = 10
Leave this as three

2025-01-04 00:03 UTC, Crossedfall commented on code/modules/client/preferences/preferences.dm
> +	var/max_save_slots = 10
```suggestion
	var/max_save_slots = 3
```

2025-01-04 00:04 UTC, Crossedfall commented on code/modules/client/preferences/preferences.dm
> +			max_save_slots += 2
```suggestion
			max_save_slots += 1
```

2025-01-04 00:04 UTC, Crossedfall commented on code/modules/client/preferences/preferences.dm
> +				max_save_slots = 16
```suggestion
				max_save_slots = 14
```

2025-01-04 00:06 UTC, Crossedfall commented on code/modules/client/preferences/preferences.dm
> +			max_save_slots += 2
Needs to be reworked a bit. Maybe a modifier on the hash to determine the number of purchases?

2025-01-04 00:07 UTC, Crossedfall commented on code/modules/client/loadout/loadout_ooc.dm
> +	description = "An extra two charslots. Pretty self-explanatory."
```suggestion
	display_name = "An extra character slots"
	description = "An extra charslot. Can be purchased up to four times."
```

2025-01-04 00:08 UTC, Crossedfall requested changes
Drop the immediate bump back down, halve the purchase cost, and add in a mechanism to allow the slot to be purchased more than once.

2025-02-01 21:33 UTC, closed without merging

2025-02-03 01:40 UTC, ClownMoff commented
IT'S SO OVER