Disables Kilo due to frequent crashes
BeeStation/BeeStation-Hornet pull request #1156
Opened 2020-01-26 13:51 UTC by Cenrus

/tg/ has reported the same problem and disabled the map accordingly. Kilo will return to active map rotation once they figure out how to fix the crashing.

:cl:
config: Temporarily disables KiloStation due to frequent crashing.
/:cl:

2020-01-26 18:05 UTC, qwertyquerty commented
Remove the votable tag instead

2020-01-27 19:14 UTC, qwertyquerty commented
@Crossedfall configs

2020-01-28 18:21 UTC, Crossedfall commented
Sad.

2020-01-28 19:14 UTC, Crossedfall requested changes
Once the disabled option is added this can be merged. I've already applied the config changes to Sage.

2020-01-28 19:14 UTC, Crossedfall commented on config/Sage/maps.txt
>  	maxplayers 60
```suggestion
	maxplayers 60
	disabled
```

`votable` is technically fine to remain, but you need to define the map as disabled for it to be removed from rotation.

2020-01-29 16:48 UTC, qwertyquerty commented
@Crossedfall

2020-01-30 02:33 UTC, merged