The slightly-good ninja nerf of 2024
BeeStation/BeeStation-Hornet pull request #11583
Opened 2024-09-26 22:40 UTC by Therealdoooc213

## About The Pull Request

In the title. Nerfs ninjas, katana damage/bleed lowered (4 hits to crit instead of 3), suit protection values lowered, cant use guns anymore.

## Why It's Good For The Game

Ninja has been overpowered for some time, able to delimb in 3 hits, near infinite teleports, insane armor, and was able to use guns. This changes all of that.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.
![image](https://github.com/user-attachments/assets/9d47d3fe-c12b-4fbb-a271-734c0813f2a5)
![image](https://github.com/user-attachments/assets/d1cf658b-6be2-4eda-8b13-77a3d7503bc2)
![image](https://github.com/user-attachments/assets/ce575ed2-b055-4867-ba0f-4605b52c0b95)

</details>

## Changelog
:cl: Therealdoooc
balance: Ninjas can no longer use guns
balance: Ninja suit has lowered protection values
balance: The Energy Katana dashing ability takes longer to recharge now, has a lower damage, and deals lower bleeding
/:cl:

2024-09-27 03:16 UTC, EvilDragonfiend requested changes
Incorrect practice of trait system. NINJA_TRAIT is not how its name means, and trait source shouldn't be given such method.

2024-09-27 03:16 UTC, EvilDragonfiend commented on code/modules/antagonists/ninja/ninja.dm
> +		. = ..()
what's this indent

2024-09-27 03:16 UTC, EvilDragonfiend commented on code/__DEFINES/traits/sources.dm
> +#define NINJA_TRAIT "ninja" //This is what happens to naughty little ninjas
```suggestion
```
This is not trait.

2024-09-27 03:16 UTC, EvilDragonfiend commented on code/modules/antagonists/ninja/ninja.dm
> +	ADD_TRAIT(M, TRAIT_NOGUNS, NINJA_TRAIT)
```suggestion
	ADD_TRAIT(M, TRAIT_NOGUNS, FAST_REF(src))
```
But also do `Remove Trait()` from antag removal proc.

2024-09-28 19:41 UTC, Rukofamicom commented
The ninja, like wizards, are supposed to be an exceedingly powerful enemy to fight.

2024-09-29 07:45 UTC, PowerfulBacon commented
This PR is a nerf for the sake of nerfing and fails to understand what is making the ninja so powerful:
- ridiculous speed
- overpowered katana
- impossible to chase due to overpowered movement options
- invisibility that grants laser immunity usable in combat

If we nerf them in this way, we are making them harder rather than simply less powerful making now player Ninjas worse while not addressing the issues that make skilled players too powerful with ninja.

2024-10-01 17:32 UTC, PowerfulBacon commented
Now that the other ninja nerf is in, I think it's best that we look at the effects of that and reconsider this going forward

2024-10-01 17:32 UTC, closed without merging