[Port] Emote Update
BeeStation/BeeStation-Hornet pull request #11617
Opened 2024-10-02 03:40 UTC by XeonMations

## About The Pull Request

Ports the following TGstation PRs:
- [ ] https://github.com/tgstation/tgstation/pull/79216
- [ ] https://github.com/tgstation/tgstation/pull/79481
- [ ] https://github.com/tgstation/tgstation/pull/80601
- [ ] https://github.com/tgstation/tgstation/pull/81883

## Why It's Good For The Game

Proper functionality of emotes is nice to have, being able to hear custom emotes while deaf is also quite critical, as you are.. deaf. Also having a proper window for all the emotes and what they're like is good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/aaafe9eb-d9b1-48d5-ab5a-bca0eec1a27d

</details>

## Changelog
:cl: XeonMations
fix: Fixed custom emotes not showing up when a person is deaf.
qol: 
/:cl:

2024-10-16 13:44 UTC, XeonMations commented
This should probably be TM'd in order to make sure nothing fucks up with say code. I tested everything i could, but knowing this is my code, I have doubts.

2024-11-15 13:17 UTC, Tsar-Salat requested changes
I couldn't really see any fundamental issues with the code.

I have only these to offer.

2024-11-15 13:17 UTC, Tsar-Salat commented on code/modules/mob/living/emote.dm
> +			var/type = input("Is this a visible or hearable emote?") as null|anything in list("Visible", "Hearable", "Both")
I think the amount of lines here could be cut down by making these inputs TGUI lists or the like.

Ideally we want most used player-facing verbs/objects to send TGUI prompts, not html.

2024-11-15 13:17 UTC, Tsar-Salat commented on code/datums/emotes.dm
>  /datum/emote/proc/run_emote(mob/user, params, type_override, intentional = FALSE)
From what I can see all of the children of this explicitly call parent except for the custom emote.

I would make the parent require calls to parent, and just exclude `/datum/emote/living/custom/run_emote()` with `SHOULD_CALL_PARENT(FALSE)`

This will prevent future screw ups by first time coders I'm sure.

2024-11-15 13:17 UTC, Tsar-Salat commented on code/modules/mob/mob.dm
> +	if((LAZYFIND(visible_message_flags, CHATMESSAGE_EMOTE)) && !target.client.prefs.read_player_preference(/datum/preference/toggle/see_rc_emotes))
What's with the double paren?

It may have a operator use, but I don't really see it. Did TG do that too?

2024-11-16 15:17 UTC, XeonMations commented on code/datums/emotes.dm
>  /datum/emote/proc/run_emote(mob/user, params, type_override, intentional = FALSE)
emote/living/custom/run_emote also calls the parent proc.

2024-11-16 15:18 UTC, XeonMations commented on code/modules/mob/mob.dm
> +	if((LAZYFIND(visible_message_flags, CHATMESSAGE_EMOTE)) && !target.client.prefs.read_player_preference(/datum/preference/toggle/see_rc_emotes))
Just my paranoia.

2024-11-16 15:20 UTC, Tsar-Salat commented on code/datums/emotes.dm
>  /datum/emote/proc/run_emote(mob/user, params, type_override, intentional = FALSE)
Then the parent proc should be SHOULD_CALL_PARENT(TRUE)

2024-11-16 15:29 UTC, XeonMations commented on code/modules/mob/mob.dm
> +	if((LAZYFIND(visible_message_flags, CHATMESSAGE_EMOTE)) && !target.client.prefs.read_player_preference(/datum/preference/toggle/see_rc_emotes))
Nevermind. The parentheses solve a critical logic flaw. Without them, all emotes would not be visible in runechat.

2024-11-16 15:30 UTC, Tsar-Salat commented on code/modules/mob/mob.dm
> +	if((LAZYFIND(visible_message_flags, CHATMESSAGE_EMOTE)) && !target.client.prefs.read_player_preference(/datum/preference/toggle/see_rc_emotes))
Lmao

2024-11-19 06:43 UTC, itsmeow approved these changes
Looks good to me. The asset cache changes are very minimal appear to be OK.

2024-12-03 08:08 UTC, merged