Begins moving felinid species behaviors to organs.
BeeStation/BeeStation-Hornet pull request #11627
Opened 2024-10-03 20:40 UTC by Tsar-Salat

## About The Pull Request
This PR changes some felinid species traits into organ traits in pursuance of eventually moving most if not all felinid-specific behavior to organs.

I started with the two most obvious: Felinid "landing on their feet" & Felinid reaction to chocolate.

The whole "falling from 1 level gives no damage" has been removed from being inherent to all felinids and instead is part of the base human zfall proc, where it just checks for a cat tail. Furthermore, I have gutted the flat fall damage reduction to greater than 1 level fallen. Whether you have a cat tail or not, if you fall more than one level, you will be taking the same damage as all other humanoids.

In regards to the felinid reaction to chocolate, my idea was first to just create a new snowflake subtype of the stomach for felinids, a "cat stomach", but I rather disliked that Idea after thinking about it. Then I thought about just making felinids dislike chocolate through the tongue, but that would be completely ignoring the previous behavior, not simply moving it to an organ.

In lieu of an actual change to the chocolate thing, I have instead opted to just limit the damage to the stomach for now. Eating chocolate causes digestive issues, it should not give you 20 brain damage.

## Why It's Good For The Game

There have been several proposals to make felinids more like humans and remove their inbuilt features, there have also been talks about making felinids their own unique catpeople race and not just humans with ears.

Regardless of whatever path is taken going forward, it is simply not good coding principles to attach all this meme behavior to the species. It makes no sense for a felinid to be able to maintain balance when falling in the vein that it would make no sense for a moth be able to fly with no wings.

In regards to approval, Bacon has made comments about how shit the felinid code is. In regards to species approval prs, this shouldn't be anything egregious and should match up with current development trends

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Single level immunity

![Screenshot 2024-10-03 160251](https://github.com/user-attachments/assets/55657866-2403-4f01-b34a-00cebaf7ff64)

Same as the rest of em

![Screenshot 2024-10-03 160327](https://github.com/user-attachments/assets/7bd5715e-7fbb-4f7d-91ea-c71dfdc2cac2)

</details>

## Changelog
:cl:
tweak: felinid fall immunity is now stored on the cat tail. If you have a cat tail, you have felinid fall immunity.
balance: strips out felinid flat fall damage reduction. Having a cat tail will only give you the single level immunity. Any fall greater than 1 level, you share the same damage as the rest of the humanoids.
tweak: Consuming chocolate as a catperson will now only deal a flat amount of damage to your stomach. It is no longer possible to get brain damage from your tummyache.
/:cl:

2024-10-03 20:43 UTC, PowerfulBacon commented
To be perfectly honest, I think the landing on their feet thing should just be removed.

2024-10-04 01:43 UTC, Nakalon commented
> To be perfectly honest, I think the landing on their feet thing should just be removed.

As a felinid player, I don't care for this. There are almost no situations were Z-levels are seen. If it were to be removed I'd enjoy if it was replaced with something else.

Also, I'm unsure but I think if you pick deviant taste quirk chocolate doesnt affect you anymore, but I could be wrong, worth to check

2024-10-05 07:03 UTC, TsunamiAnt commented
guys we gotta get our vocab straight
Non felinid = Species Behavior(good)
Felinid = Meme Behavior (bad)

I think we would be better off making felinids more unique, not less so.

2024-10-05 22:35 UTC, Tsar-Salat commented
> I think we would be better off making felinids more unique, not less so.

How is this relevant to my pr at all? Im not removing anything

2024-10-06 00:57 UTC, TsunamiAnt commented
> Im not removing anything

i'm a damn idiot. forget i said anything

2024-10-10 18:24 UTC, PowerfulBacon commented
If we continue down this path to moving everything to organs like this, I feel like its going to get incredibly messy incredibly fast since this is not generic or expandable in any way. I see 2 better ways of doing this:
1. Completely remove this behaviour and don't worry about it.
2. Code up some framework for organs to register signals to their mob, and then intercept the z-impact signal thus making a system that can be expanded upon to support all the behaviours that we need.

2024-10-25 18:54 UTC, PowerfulBacon approved these changes
The code isn't the best and really should be signals/trait based, but since its contained in species, it's probably fine for now. Future conversions should be more generic as to not defeat the point of modularising these

2024-12-24 15:03 UTC, PowerfulBacon requested changes

2024-12-24 15:03 UTC, PowerfulBacon commented on code/modules/mob/living/carbon/human/species.dm
> +	if(left_leg || right_leg || !left_leg.bodypart_disabled || !right_leg.bodypart_disabled)
This logic is incorrect, if left leg is null it will throw a runtime

2025-04-12 23:55 UTC, Tsar-Salat commented on code/modules/mob/living/carbon/human/species.dm
> +	if(left_leg || right_leg || !left_leg.bodypart_disabled || !right_leg.bodypart_disabled)
fixed

2025-04-17 20:00 UTC, Tsar-Salat commented
Stole the organ trait code from #12364

2025-04-19 11:59 UTC, PowerfulBacon reviewed
Seems good otherwise

2025-04-19 11:59 UTC, PowerfulBacon commented on code/__DEFINES/traits/declarations.dm
> +#define TRAIT_CATROBATICS "catrobatics"
Should be a generalised and sensible trait name, like TRAIT_NO_FALL_DAMAGE

2025-04-19 17:22 UTC, Tsar-Salat commented on code/__DEFINES/traits/declarations.dm
> +#define TRAIT_CATROBATICS "catrobatics"
Just make a change req

2025-04-19 17:23 UTC, Tsar-Salat commented on code/__DEFINES/traits/declarations.dm
> +#define TRAIT_CATROBATICS "catrobatics"
```suggestion
#define TRAIT_LIGHT_LANDING "lightlanding"
```

2025-04-19 17:23 UTC, Tsar-Salat commented on code/modules/surgery/organs/tails.dm
> +	organ_traits = list(TRAIT_CATROBATICS)
```suggestion
	organ_traits = list(TRAIT_LIGHT_LANDING)
```

2025-04-19 17:24 UTC, Tsar-Salat commented on code/_globalvars/traits/_traits.dm
> +		"TRAIT_CATROBATICS" = TRAIT_CATROBATICS,
```suggestion
		"TRAIT_LIGHT_LANDING" = TRAIT_LIGHT_LANDING,
```

2025-04-19 17:24 UTC, Tsar-Salat commented on code/modules/mob/living/carbon/human/species.dm
> +		if(HAS_TRAIT(H, TRAIT_CATROBATICS) && levels == 1)
```suggestion
		if(HAS_TRAIT(H, TRAIT_LIGHT_LANDING) && levels == 1)
```

2025-04-19 21:17 UTC, Rukofamicom approved these changes

2025-04-20 12:14 UTC, PowerfulBacon approved these changes

2025-04-20 12:28 UTC, merged