Adds a diona-exclusive martial art for traitors
BeeStation/BeeStation-Hornet pull request #11674
Opened 2024-10-11 22:44 UTC by RDS88-beeman

## About The Pull Request
Disclaimer: This is stupid

Adds a martial art for dionae, known as the living-fist technique, loosely inspired by plasma fist. It has three combos, and is bought from the traitor uplink for 10tc by dionae only. It also removes shoves and grabs, replacing them with basic hits. Combos are as follows:
**Vine Lash** (Grab, Grab, Harm): Immediately neck grabs a target. 
**Lacerate** (Disarm, Harm, Disarm): Plays a short animation, and deals 20 chest damage to a target, as well as inflicting 3.6 bleeding. Can only be done on a target in a neck grab, requiring Vine Lash to have been used first. 
**NYMPH BLAST** (case sensitive) (Harm, Disarm, Disarm, Disarm, Harm): Turns someone into a diona, then deals 400 brute damage to their chest, instantly killing them and forcing them to scatter into a pile of nymphs. 

## Why It's Good For The Game
I like plasma fist, and dionae don't have any exclusive traitor items. They're also a good candidate for a powerful martial art because they're slow, meaning that combatants can just walk away to avoid confrontation.  

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Since I can't record, it's hard to capture video footage of combos in use, so please take my word for it that everything works.
![image](https://github.com/user-attachments/assets/396e409a-1fe3-46ea-b201-fcb54219af42)
Here's a picture of the scroll in the traitor inventory.

</details>

## Changelog
:cl:
add: Traitor dionae can now purchase a scroll detailing the Living Fist technique! Punch people so hard they explode into a shower of nymphs. Do other stuff too, if you're not cool.
/:cl:

2024-10-12 00:50 UTC, XeonMations commented
There is a way of restricting the item to be species speciifc, see lizard martial arts. Also I am unsure as to the balance of this, since it'd turn anyone hit by the nymph blast INTO a diona.

2024-10-12 00:54 UTC, RDS88-beeman commented
I consider turning someone into a diona a softer fate than just killing or round-removing them, and also have the potential for good Situation opportunities. I'm not sure it's as much a balance concern as it would be a concern of that being bullshit in the same way transformation sting is. Even still, you keep your name, so it could be infinitely worse.

Also, only diona can buy the item as-is.

2024-10-12 08:13 UTC, Fronsis commented
> Not sure it's as much a balance concern as it would be a concern of that being bullshit in the same way transformation sting is. Even still, you keep your name, so it could be infinitely worse.

People are usually attached to their species and name, thus why when we had the transformation sting cure PR it was heavily celebrated since no one enjoyed the era of transformation sting spam, the thing about these martial arts is... that it doesn't make sense as a martial arts like uh... you do a blast that transform someone and explodes them, removing/dropping all their gear to the floor.

Dunno, except for people that can actually block or fight back it seems that it's one neck grab and you're gonezo, not much counterplay on that, and then being forced to play a race that you might not even like in the first place.

TC also seems cheap for a semi-gib attack.

2024-10-12 15:27 UTC, Therealdoooc213 commented
> TC also seems cheap for a semi-gib attack.

You have to remember how insanely slow diona are, unless they have some form of movement modifiers it'd be near impossible to use that combo unless the person was incapacitated

2024-10-13 00:36 UTC, Rukofamicom commented
> NYMPH BLAST (case sensitive) (Harm, Disarm, Disarm, Disarm, Harm): Turns someone into a diona, then deals 400 brute damage to their chest, instantly killing them and forcing them to scatter into a pile of nymphs.

That's gonna be a hard no from me.

2024-10-23 16:46 UTC, Tsar-Salat requested changes
I will approve this if it is unobtainable by traitors and is instead admin-only.

As ruko said, the whole changing species and doing enough damage to husk someone is uhhh... yeah. Its something I would give to people at EORG for funnies, not something I would really trust unsupervised tots with.

I will key in a few days otherwise

2024-10-23 23:03 UTC, RDS88-beeman commented
I'm done with this. It was a fun concept, but I'm not willing to put too much effort in to make this salvagable. I might make a proper run at it some other time.

2024-10-23 23:03 UTC, closed without merging