added funny cores to cargo bounties
BeeStation/BeeStation-Hornet pull request #11685
Opened 2024-10-12 23:08 UTC by MarkusLarsson421

## About The Pull Request
Adds all the anomalies (except insanity) to be a Cargo bounty.
They only require one (despite the testing evidence) and reward the following (despite the testing evidence):

bleed, 5 000 
bluespace, 12 000 
delimber, 8 000 
flux, 3 000 
gravity, 4 000
hallucination, 1 000 
pyro, 6 000 
vortex, 25 000

It's value has been balanced on my personal opinion of its rarity and danger.

## Why It's Good For The Game
Makes Taylor happy and makes Cargo WANT to get those pesky anomalies. Could encourage Engineers to make a spicy SM to make it create some anomalies if there is a bounty for it.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
The money and amount has been changed, look at About The Pull Request for more detailed information.

![image](https://github.com/user-attachments/assets/caf55576-4665-4da7-884b-38bd40acaeb9)

![image](https://github.com/user-attachments/assets/544efd2e-ad77-46e8-b92d-77b267d44d83)

</details>

## Changelog
:cl:
add: Added anomaly cores to the Cargo bounty.
balance: Added another method for Cargo to get fat stacks of cash.
/:cl:

2024-10-13 00:34 UTC, Rukofamicom approved these changes

2024-10-13 10:06 UTC, MarkusLarsson421 commented
Was told that the rewards were too low, so I'll increase it when I have the time.

2024-10-15 12:24 UTC, Rukofamicom commented
Were you planning to include a normal sale price on them here too?

2024-10-15 12:53 UTC, MarkusLarsson421 commented
> Were you planning to include a normal sale price on them here too?

I could do that, sure.

2024-10-15 13:19 UTC, Rukofamicom approved these changes

2024-10-18 19:44 UTC, PowerfulBacon requested changes
These prices are way too high. They should be 6000 at most.

2024-10-18 21:19 UTC, Rukofamicom commented
Which prices, the bounty prices or the normal prices? Most bounty prices are quite high - simple crafted items from lavaland range up to 36,000 credits.

2024-10-18 23:37 UTC, MarkusLarsson421 commented
Normal sell prices I think he refers to.

Considering their rarity, I don't think the prices are that bad. Especially not the Vortex and Bluespace ones which are REALLY rare and which Science would actually be interested in because of their unique properties.

I won't change anything immediately but give this some thought for a day or two and reach back then.

2024-10-22 20:04 UTC, PowerfulBacon approved these changes
Didn't realise those were bounty prices. I don't think vortex anomalies actually do anything useful for science though

2024-10-22 20:23 UTC, MarkusLarsson421 commented
> I don't think vortex anomalies actually do anything useful for science though

It can be used with Reactive Armour and the Phazon. I've heard it gives infinite power to a Phazon, but haven't tested this out. Either way, it is rare as hell.

2024-10-22 20:26 UTC, merged

2025-09-15 03:40 UTC, Tsar-Salat commented on code/modules/cargo/exports/core.dm
> +	export_types = list(/obj/item/assembly/signaler/anomaly/)
why the hell

2025-09-15 19:02 UTC, MarkusLarsson421 commented on code/modules/cargo/exports/core.dm
> +	export_types = list(/obj/item/assembly/signaler/anomaly/)
Care to elaborate or are you just necroposting?

2025-09-16 16:00 UTC, Tsar-Salat commented on code/modules/cargo/exports/core.dm
> +	export_types = list(/obj/item/assembly/signaler/anomaly/)
why are they all the parent type

2025-09-17 10:11 UTC, MarkusLarsson421 commented on code/modules/cargo/exports/core.dm
> +	export_types = list(/obj/item/assembly/signaler/anomaly/)
No idea, why not?