Makes pickaxe mining less miserable
BeeStation/BeeStation-Hornet pull request #11714
Opened 2024-10-16 14:06 UTC by RDS88-beeman

## About The Pull Request
This makes all pickaxes (not drills, not PKAs, not crushers, not resonators, just pickaxes) mine faster, at the cost of requiring stamina to use.
Standard pickaxes deal six damage per picking action, clamped to 75, while mining as fast as silver pickaxes.
Silver pickaxes are the same, but deal four damage per action.
Diamond pickaxes deal three damage per action, but are "fast as fuck".
Ignore the glitter, that's being atomised.

## Why It's Good For The Game
Ruko told me to and I trust his game design judgement. I also play ashwalker, and pickaxe mining as an ashwalker is miserable. This helps that take less time, while also making it not a unilateral buff.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

I personally have gotten away with not providing testing evidence for a lot of PR's by going "just trust me."
However, I still don't have any way of recording testing video or taking images, so you are just going to have to trust me on this one. I solemnly swear I did in fact take this into a private server and make sure it all worked.

</details>

## Changelog
:cl:
balance: Pickaxes are faster now, you can put your back into it! Granted, putting your back into it tends to tire you out, so watch out for that.
/:cl:

2024-10-16 18:29 UTC, MarkusLarsson421 commented
Get some testing evidence. smh

2024-10-16 21:46 UTC, Rukofamicom commented
This does make normal pickaxes (0.5) technically faster than normal drills (0.6), but drills don't have the stamina cost.

2024-10-16 21:50 UTC, Rukofamicom commented
![dreamseeker_guLi7KO0jE](https://github.com/user-attachments/assets/614579e4-859f-498e-979f-d4b39e2d9bc5)

![dreamseeker_DqPCZs4ecG](https://github.com/user-attachments/assets/f396fbc9-c08b-47d2-8304-278d62580292)

2024-10-16 21:52 UTC, Rukofamicom commented
I do really recommend sharex for testing evidence. It's what I just used to produce those.

2024-10-16 21:54 UTC, Rukofamicom requested changes
That said, having tested it the stamina cost does feel a bit steep for what I was thinking. 

I do see my initial comment about the drill was incorrect now that I'm looking at the code as well.

2024-10-16 21:54 UTC, Rukofamicom commented on code/modules/mining/equipment/mining_tools.dm
> +	var/stamina_use = 6
```suggestion
	var/stamina_use = 5
```

2024-10-16 21:54 UTC, Rukofamicom commented on code/modules/mining/equipment/mining_tools.dm
> +	stamina_use = 4 //costs less stamina because silver is lighter??
```suggestion
	stamina_use = 3 //costs less stamina because silver is lighter??
```

2024-10-21 16:50 UTC, RDS88-beeman commented
![dreamseeker_KUCAQZZ0OA](https://github.com/user-attachments/assets/ba3b7cab-08ad-4bfa-925c-cc5014e8c929)
this is borg proof, they still work

2024-10-25 03:31 UTC, Rukofamicom approved these changes

2024-10-25 03:40 UTC, Tsar-Salat approved these changes
I concur, looks fine. I do not think it will be a problematic alternative

2024-10-25 03:50 UTC, merged