Speeds up preferences menu, mob dummies, & Unit Tests outfits
BeeStation/BeeStation-Hornet pull request #11749
Opened 2024-10-20 19:06 UTC by Tsar-Salat

## About The Pull Request

This PR puts loading preferences menu stuff on a subsytem, SSwardrobe, which allows us to preload stuff like equipment clothing and organs of dummies, and load it when opening the menu, saving us a lot of time.

Additionally, we now unit test outfits

Ports:
- https://github.com/tgstation/tgstation/pull/44109
- https://github.com/tgstation/tgstation/pull/52210
- https://github.com/tgstation/tgstation/pull/59109 (wardrobe changes only)
- https://github.com/tgstation/tgstation/pull/63225

## Why It's Good For The Game

Loading dummies in the preference menu does not make them take an ungodly amount of time just because they have more gear on. (Looking at you, Chief Engineer)

If you want measurement specifics, go look at the TG pr.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Yuh huh

</details>

## Changelog
:cl: rkz, Akrilla, Mothblocks, LemonInTheDark
refactor: refactors pref menu to load faster
code: adds unit test for outfits
refactor: refactors survivalboxes to be less copypaste
code: standardizes storage holdability
/:cl:

2024-11-12 20:05 UTC, Dejaku51 requested changes
Doublecheck if you didn't skip those paths
/obj/item/storage/belt/medical/ert/ComponentInitialize()
/obj/item/storage/belt/bandolier/western/ComponentInitialize()
/obj/item/storage/firstaid/medical/paramedic/ComponentInitialize()

2024-11-13 06:07 UTC, Tsar-Salat commented
> /obj/item/storage/belt/medical/ert/ComponentInitialize()

It just adds to its parent's list. The setter should work fine.

I took the opportunity to run it through the preloader though.



> /obj/item/storage/belt/bandolier/western/ComponentInitialize()

Missed this one. Non-conventional naming. Fixed now.



> /obj/item/storage/firstaid/medical/paramedic/ComponentInitialize()

![Screenshot 2024-11-13 005554](https://github.com/user-attachments/assets/30289388-53dc-4e08-8fc8-7477b10627d1)

Escaped my notice. Fixed

2024-11-13 06:09 UTC, Tsar-Salat commented on code/modules/surgery/bodyparts/bodyparts.dm
> +	if(IS_ORGANIC_LIMB(src))
Runtime due to undefined 'status_traits' when loading dummies through select equipment.

Fixed by nesting the checks by 1.

2024-11-13 07:49 UTC, Dejaku51 approved these changes
looks good

2024-11-16 08:36 UTC, PowerfulBacon approved these changes

2024-11-16 08:54 UTC, itsmeow commented
hold up

2024-11-16 09:02 UTC, itsmeow approved these changes
ok

2024-11-16 09:36 UTC, merged