Merges mob properties
BeeStation/BeeStation-Hornet pull request #11760
Opened 2024-10-23 19:26 UTC by PowerfulBacon

fixes #11759

## About The Pull Request

Merges mob properties and traits, for a convenient method of getting values from a trait.

```
// Set the skin colour trait value to 0, with a priority of 50
ADD_TRAIT(target, TRAIT_SKIN_COLOUR, TRAIT_SOURCE_HUSK, "#000", 50)
// Get the skin colour
var/skin_colour = GET_TRAIT_VALUE(target, TRAIT_SKIN_COLOUR)
```

## Why It's Good For The Game

Mob properties are abandoned since they are a weird duplicate of traits. This merges them together, and allows values to be put into traits in a convenient manner.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
code: Merges mob properties and traits.
/:cl:

2024-10-23 19:27 UTC, Tsar-Salat commented
Is this why theres a runtime in status traits when loading dummies?

2024-10-23 19:28 UTC, PowerfulBacon commented
I don't know

2024-10-24 10:31 UTC, EvilDragonfiend commented
macro is stupid and it sometimes doesn't recognise indent

2024-10-24 15:07 UTC, EvilDragonfiend commented
![image](https://github.com/user-attachments/assets/27c7d4e3-a31c-40f9-8b48-8dcaac03cf66)

wrapping with {} will work, I think

2024-10-24 15:11 UTC, EvilDragonfiend commented
> It is wrapped in brackets, the issue is it picks up relative paths since while they are in brackets they become relatively pathed
> 
> Annoyingly unlint can't work here either

ah, I mean It looks it should have typepath to each proc, but yeah it will be annoying.

2024-10-24 15:47 UTC, EvilDragonfiend commented on code/__DEFINES/_heap_helpers/heap.dm
> +}
```suggestion
#define HEAP_TYPE(typepath, compare_value) \
##typepath{\
	var/list/L;\
}\
##typepath/New(...) {\
	L = list(args);\
}\
##typepath/Destroy(force, ...) {\
	for(var/i in L) {\
		qdel(i);\
	}\
	L = null;\
	return ..();\
}\
##typepath/proc/is_empty() {\
	return !length(L);\
}\
##typepath/proc/insert(atom/A) {\
	L.Add(A);\
	swim(length(L));\
}\
##typepath/proc/pop() {\
	if(!length(L)) {\
		return 0;\
	}\
	. = L[1];\
	L[1] = L[length(L)];\
	L.Cut(length(L));\
	if(length(L)) {\
		sink(1);\
	}\
}\
##typepath/proc/swim(index) {\
	var/parent = round(index * 0.5);\
	while(parent > 0 && (L[index]:##compare_value - L[parent]:##compare_value > 0)) {\
		L.Swap(index,parent);\
		index = parent;\
		parent = round(index * 0.5);\
	}\
}\
##typepath/proc/sink(index) {\
	var/g_child = get_greater_child(index);\
	while(g_child > 0 && (L[index]:##compare_value - L[g_child]:##compare_value < 0)) {\
		L.Swap(index,g_child);\
		index = g_child;\
		g_child = get_greater_child(index);\
	}\
}\
##typepath/proc/get_greater_child(index) {\
	if(index * 2 > length(L)) {\
		return 0;\
	}\
	if(index * 2 + 1 > length(L)) {\
		return index * 2;\
	}\
	if(L[index * 2]:##compare_value - L[index * 2 + 1]:##compare_value < 0) {\
		return index * 2 + 1;\
	} else {\
		return index * 2;\
	}\
}\
##typepath/proc/resort(atom/A) {\
	var/index = L.Find(A);\
	swim(index);\
	sink(index);\
}\
##typepath/proc/List() {\
	. = L.Copy();\
}\
##typepath/proc/operator+=(A) {\
	L.Add(A);\
	swim(length(L));\
}\
##typepath/proc/operator|=(A) {\
	var/original_length = length(L);\
	L |= A;\
	if (original_length != length(L)) {\
		swim(length(L));\
	}\
}\
##typepath/proc/operator-=(A) {\
	var/index = L.Find(A);\
	if(index == 0) {\
		return 0;\
	}\
	. = L[index];\
	L[index] = L[length(L)];\
	L.Cut(length(L));\
	if(length(L)) {\
		sink(index);\
	}\
}
```
This will work

2024-10-24 16:21 UTC, PowerfulBacon commented on code/__DEFINES/_heap_helpers/heap.dm
> +}
This was how it was originally but didn't work due to comments (which I removed anyway). Been meaning to convert it back, but not sure how much byond actually liked this.

2024-10-24 19:40 UTC, PowerfulBacon commented
I would like to be able to implicitly assign trait values based on the trait (for example TRAIT_HUSK adds TRAIT_SKIN_COLOUR) but TRAIT_HULK also adds the same trait value but with a different colour, but I think this will be too much for now

2024-10-27 17:36 UTC, PowerfulBacon commented
I have gotten the performance difference down to something that is barely different for the base case, and I think it is now in an acceptable range that won't have an impact on the code.

2024-10-27 17:37 UTC, PowerfulBacon commented
I should add a lint against mixing value traits with non-value traits though

2024-10-27 21:53 UTC, PowerfulBacon commented
ADD_TRAIT with non-strings doesn't seem to work

2024-11-09 08:02 UTC, PowerfulBacon commented
We need a new comsig signal for when a priority stat gets updated

2024-11-09 18:02 UTC, PowerfulBacon commented
This PR increases compilation times by 2 minutes

2024-11-10 16:10 UTC, PowerfulBacon commented
Compilation problem solved, issue was due to the use of : operator

2024-11-12 17:04 UTC, EvilDragonfiend commented
is it ready for review?

2024-11-12 19:23 UTC, PowerfulBacon commented
Yes, it is in use by 2 of my other PRs, 1 of which is currently in progress. The compilation time issue has been fixed.

2024-11-18 02:02 UTC, EvilDragonfiend requested changes
Would you please put * in parameter explanations? VSCode doesn't recognise newline well when you see the proc hint tooltip.
Also, instead of numbering, specifying parameter name will be easier to read.
I am not sure if you'd like my style, but I'd write in this way:
```
/// Add a trait to a target
/// Parameters:
/// 1: The target to receive the trait
/// 2: The key of the trait
/// 3: The source of the trait
/// 4: The priority of the trait value
/// 5: The value stored in the trait
``` 
to 
```
/// Add a trait to a target
/// * target<datum>: The target to receive the trait
/// * trait_type<DEFINE>: The key of the trait
/// * source<datum|text>: The source of the trait
/// * trait_value<datum>: The value stored in the trait
/// * trait_priority<int>: The priority of the trait value
```
(also, you miswrote 4 and 5. this would be the reason why specifying name is better, I suppose.)

-------------

Also, I feel like there should be a readme that describes the macros.
The PR body seems to be good to be the readme.
(but please update PR body. it's outdated. there is no `MULTIPLY_NUMERIC_TRAIT`)

because I feel overwhelemed massive size of the dm file, and I have no idea which proc is what I would need when especially these are all quite similar.

------------

This is a bit confusing to understand yet, but I see this is ultra-potential.
I think ths confusion comes from the absense of the correct document.
and I will think about how this can be flowing to read apart from the confusion. (I feel trait datum and macros are a-bit-not connected well to read to each others.)

2024-11-18 03:38 UTC, EvilDragonfiend commented
btw, is `The key of the trait` the right definition? I feel like the source is the key, and it should be `trait_type`

2024-11-18 13:57 UTC, PowerfulBacon commented
Multiplicative trait is a number trait, cumulative and multiplicative interact with each other. (Take size for example, adding, multiplying, subtracting then dividing results in permanent changes to size which this system handles appropriately)

2024-11-18 15:28 UTC, EvilDragonfiend commented
> Multiplicative trait is a number trait, cumulative and multiplicative interact with each other. (Take size for example, adding, multiplying, subtracting then dividing results in permanent changes to size which this system handles appropriately)

I mean some macros do not exist but these are stated in the PR body. I guess you were changing it.

2025-01-05 11:07 UTC, PowerfulBacon commented
Updated to reflect the actual name, ADD_MULTIPLICATIVE_TRAIT

2025-01-05 11:08 UTC, PowerfulBacon commented on code/__DEFINES/traits/_traits.dm
> +/// 5: The value stored in the trait
```suggestion
/// 4: The value stored in the trait
/// 5: The priority of the trait value
```

2025-02-09 08:13 UTC, merged