Ezdb port (fixes #11768)
BeeStation/BeeStation-Hornet pull request #11795
Opened 2024-10-29 08:08 UTC by Szyszkrzyneczka

## About The Pull Request

Fixes #11768 when it actually works
ports https://github.com/tgstation/tgstation/pull/75053

/*
    Downloads a portable MariaDB (doesn't pollute your main system)
    Sets up a database with a random password on port 1338 (configurable)
    Installs the initial schema
    Every time after, will run updates

Major versions right now explicitly escape hatch, because those historically come with something like a Python script, and I do not want it to pretend to work.*/ (taken from base pr)

There are some errors that I cannot fix due to my lack of database/python knowledge. I hope this will nudge someone to take a look and finish what I did
apparently this isn't as copy paste as I thought it would be :trollface: 
## Why It's Good For The Game

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

2024-10-31 08:28 UTC, Szyszkrzyneczka commented
I need someone to test if this works on their machine (I get sql errors and dont know how to fix them)

2024-11-08 16:41 UTC, Dejaku51 requested changes

2024-11-08 16:41 UTC, Dejaku51 commented on config/dbconfig.txt
> -FEEDBACK_PASSWORD password1
remove all changes from dbconfig.txt, ezdb has its own config in ezdb.txt

2024-11-08 16:41 UTC, Dejaku51 commented on tools/ezdb/steps/download_mariadb.py
> +FOLDER_NAME = "mariadb-10.11.2-winx64"
should probably use latest version of mariadb but i'll bug crossed to ask

2024-11-08 16:42 UTC, Szyszkrzyneczka commented on config/dbconfig.txt
> -FEEDBACK_PASSWORD password1
Already did bestie

2024-11-08 16:51 UTC, Dejaku51 commented on config/dbconfig.txt
get rid of all changes here, including the empty line and dot removal

2024-11-11 14:41 UTC, Dejaku51 commented on tools/ezdb/steps/download_mariadb.py
> +FOLDER_NAME = "mariadb-10.11.2-winx64"
you know, fuck it, might do something about it later

2024-11-11 14:42 UTC, Dejaku51 approved these changes
looks good, still needs @Crossedfall approval

2025-01-26 05:24 UTC, Crossedfall commented
I'll be totally honest, I kind of hate this lol. I really don't like the idea of game code managing locally running processes in an arbitrary way. One the whole, it's pretty sketchy. I recognize the benefit from an easy-of-setup perspective, but it's... Just super icky. Not to mention, it pollutes and already pretty bloated development environment.

I'll talk with Bacon and some of the others on this internally a bit more, but my initial reaction is to reject the change.

2025-03-06 17:51 UTC, PowerfulBacon commented
No longer being worked on from the looks of it

2025-03-06 17:51 UTC, closed without merging