Moths can now eat cloth directly!
BeeStation/BeeStation-Hornet pull request #11801
Opened 2024-10-30 04:25 UTC by XeonMations

## About The Pull Request

Makes moths be able to eat the raw resources a clothe is made.

## Why It's Good For The Game

Being able to eat clothes but not the material that said clothes are made of seems a bit like an oversight.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/user-attachments/assets/332b9d92-61c1-4bd7-a869-25b1d3ee861d)

https://github.com/user-attachments/assets/725e36e5-0869-4b10-850f-c3095c24ba2d

</details>

## Changelog
:cl: XeonMations
balance: Moths can now eat cloth and cloth subtypes.
/:cl:

2024-10-30 06:40 UTC, Rukofamicom commented
This may have implications with #11640 if normal clothing can be turned back into cloth.

2024-11-10 22:59 UTC, Rukofamicom requested changes
Clothing turned into cloth should contain microplastics when eaten.

This is going to be a fairly complicated issue to solve, but because clothing can be turned into cloth without regard for microplastics, this currently allows players to exploit the system put in place to discourage moths from ignoring dietary needs.

2024-11-10 23:01 UTC, Rukofamicom commented
Looking at the code (on mobile) it doesn't actually look like this provides any nutrition, it's purely a way for them to destroy the cloth?

If that's true disregard the above.

2024-11-11 06:20 UTC, XeonMations commented
Based off the code, it makes cloth the same food item as clothing is. So if you have `obj/item/food/clothing` have microplastics, so will cloth

2024-11-11 08:03 UTC, XeonMations commented
Just checked the code, yes it has microplastics when eating cloth.

2024-11-11 14:16 UTC, Rukofamicom commented
👍 
Looking at more surrounding code it makes sense now.

2024-11-11 14:17 UTC, Rukofamicom approved these changes

2024-11-11 14:18 UTC, Rukofamicom commented
Being able to eat cloth is definitely not a balance change:

Cloth comes from botany, which already grows food for the same or less effort
Cloth comes from clothing, which is already edible for the same nutrition

2024-11-11 14:27 UTC, merged