Moves the CorgStation gateway
BeeStation/BeeStation-Hornet pull request #11818
Opened 2024-11-01 05:25 UTC by Therealdoooc213

## About The Pull Request

Moves the corgstation gateway to service, It was previously located inside of... maintenance where I don't think anyone would ever notice it exists.

## Why It's Good For The Game

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

![image](https://github.com/user-attachments/assets/d3228856-d232-40cc-a706-b399fca247b5)
(vent and scrubber is under the table)
![image](https://github.com/user-attachments/assets/12f141f7-fba1-4f0b-a284-7b049f047a50)

</details>

## Changelog
:cl:
add: The corgstation gateway is now inside of service
add: New maintenance room in corg botany maintenance.
/:cl:

2024-11-11 18:57 UTC, mystery3525 requested changes
![image](https://github.com/user-attachments/assets/f7a07e35-1d06-49a1-ab4c-29fbeb7caf1d)
pipes go to nothing

![image](https://github.com/user-attachments/assets/2df5d00e-1a53-4d2d-a4a9-6556e831eb0a)
- Walls look a little barren, maybe some random poster spawners?
- Needs an intercom
- Needs a firealarm
- Bottom button should probably be on the decal, pixel shifted to the wall, since you have the external button on the top
- Add 1 vent and scrubber
- Light can be shifted one tile up to make it less visually awkward with the decal
- Camera needs to be moved so that it is not ontop of the APC, you can't fix the APC with the camera already on the wall

2024-11-12 04:29 UTC, Therealdoooc213 commented
> * Walls look a little barren, maybe some random poster spawners?
> * Needs an intercom
> * Needs a firealarm
> * Bottom button should probably be on the decal, pixel shifted to the wall, since you have the external button on the top
> * Add 1 vent and scrubber
> * Light can be shifted one tile up to make it less visually awkward with the decal
> * Camera needs to be moved so that it is not ontop of the APC, you can't fix the APC with the camera already on the wall

Sure, the room already has vents and scrubbers though, theyre just hidden under the table and locker. also firelocks under shutters would look weird.

2024-12-13 13:44 UTC, mystery3525 approved these changes

2024-12-27 20:01 UTC, Tsar-Salat commented
> Moves the corgstation gateway to service

can we get literally one gateway thats actually in cargo

2024-12-27 20:01 UTC, Therealdoooc213 commented
> can we get literally one gateway thats actually in cargo

no

2025-01-31 19:44 UTC, Therealdoooc213 commented
![image](https://github.com/user-attachments/assets/02d82add-e87d-45b0-ad08-bff88b8fdfaf)

2025-01-31 21:05 UTC, mystery3525 approved these changes
I'm not a maintainer but its ok

2025-02-15 08:25 UTC, PowerfulBacon approved these changes

2025-02-15 08:32 UTC, merged