Oppenheimer is no longer shot by the syndicate turrets
BeeStation/BeeStation-Hornet pull request #11842
Opened 2024-11-06 04:23 UTC by Therealdoooc213

## About The Pull Request

In the title

## Why It's Good For The Game

Bugs are bad

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/user-attachments/assets/ec9600b9-2654-41e5-ab5b-7f197860df98)

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
fix: Oppenheimer is no longer shot by their own turrets
/:cl:

2024-11-06 07:19 UTC, Dejaku51 requested changes
change faction in the mob define instead of editting it in map.

2024-11-06 09:22 UTC, Dejaku51 commented on code/game/machinery/porta_turret/portable_turret.dm
> +	faction = list(FACTION_SYNDICATE, "syndicate")
remove the added "syndicate" faction

2024-11-06 09:44 UTC, Therealdoooc213 commented on code/game/machinery/porta_turret/portable_turret.dm
> +	faction = list(FACTION_SYNDICATE, "syndicate")
Woops

2024-11-06 15:05 UTC, Tsar-Salat commented
> change faction in the mob define instead of editting it in map. also don't add "syndicate" as a faction. use FACTION_SYNDICATE define

I don't think we should be mandating this unless someone goes through the effort of converting *all* the faction strings to defines.

It doesn't really matter though

2024-11-06 15:06 UTC, Tsar-Salat approved these changes
Simple change, Dejaku already addressed the mapedit issue. 

Looks good to me

2024-11-08 15:58 UTC, Dejaku51 approved these changes

2024-11-08 16:39 UTC, PowerfulBacon approved these changes

2024-11-08 16:51 UTC, merged