New nuclear operative item, The Macho Wrestler Bundle!
BeeStation/BeeStation-Hornet pull request #11843
Opened 2024-11-06 04:59 UTC by Therealdoooc213

## About The Pull Request

Adds a new nuclear operative item, The Macho Wrestler bundle! (18 TC, trademark pending) It contains a Rudos mask (modifies speech), a wrestling belt (grants martial arts), a adrenalin implant, and combat hypospray for healing! Strike fear into your enemys when you throw the captain at a wall and stomp on their head!

## Why It's Good For The Game

Nukies have a severe lack of fun items or flavor, which restricts their gameplay to mainly be Fake centcom, war, or stealth. If there are more nukie items it encourages them to try new gimmicks, plans, and think!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

https://github.com/user-attachments/assets/231d2adc-b328-49d1-a42c-c9fa4dad978a

</details>

## Changelog
:cl:
add: A new nuclear operative bundle, The Macho Wrestler! Contains everything you need to wrastle the captain into giving you the disk.
/:cl:

2024-11-06 13:43 UTC, ClownMoff commented
Good luck convincing mementainers to add the belt and I mean it honestly. I would like seeing this on the game, Also please add icons to the abilities.

2024-11-06 13:47 UTC, ClownMoff requested changes
Some typos and bad grammar

2024-11-06 13:47 UTC, ClownMoff commented on code/modules/uplink/uplink_items.dm
> +	desc = "For the STRONGEST operatives! Master your wrastling abilitys with this bundle. \
Wrastling

2024-11-06 13:47 UTC, ClownMoff commented on code/modules/uplink/uplink_items.dm
> +			Contains: A wrestling belt, for only the strongest, a adrenalin implanter, a mask to strike fear into your enemys, and a combat hypospray!"
Contains: A wrestling belt, only for the strongest machos, an adrenaline implanter, a luchador mask to strike fear into your enemies, and a combat hypospray!"

2024-11-06 15:09 UTC, Rukofamicom requested changes

2024-11-06 15:09 UTC, Rukofamicom commented on code/modules/uplink/uplink_items.dm
> +	desc = "For the STRONGEST operatives! Master your wrastling abilities with this bundle. \
I understand what you're going for but Wrastling just looks wrong. Spell it right or find a different way to spell the funny way to say it. `Wrasslin'` has my vote.

2024-11-06 16:20 UTC, Rukofamicom approved these changes

2024-11-10 13:27 UTC, PowerfulBacon approved these changes

2024-11-10 13:48 UTC, merged