Nerfs disablers max amount of shots from 25 to 12
BeeStation/BeeStation-Hornet pull request #11858
Opened 2024-11-08 14:52 UTC by ClownMoff

## About The Pull Request

Nerfs disablers max amount of shots from 25 to 12, adds a new ammo subtype to e guns so they don't get affected with this nerf

## Why It's Good For The Game

25 shots is an insane amount of bullets for a non armory weapon that anyone can carry, there is no escaping 25 shots.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Soon.

</details>

## Changelog
:cl: ClownMoff
balance: Nerfs disablers max amount of shots from 25 to 12
add: Adds a new disabler ammo subtype for the e gun to prevent the disabler nerf from affecting the other gun
/:cl:

2024-11-08 15:27 UTC, XeonMations commented
Disablers can disable someone without armor in six hits, so making it twelve would require the user to have perfect aim to disable a single target. I don't exactly see any reason other than "i ded" for this, honestly.

2024-11-08 16:09 UTC, Fronsis commented
Agreed with Xeon, most of the times disablers end up missing a lot of shots while chasing someone and it's intentional to have that amount of ammo, so you have the biggest chance to take down someone before resorting to lethals, not to mention there's also ping involved since the player base is from everywhere.

2024-11-08 16:38 UTC, PowerfulBacon commented
I'm fine with them coming down a bit or needing ammo like the service pistols, but this is far too much.

2024-11-09 17:19 UTC, Tsar-Salat commented
Best this gets discussed. 

I think its an important discussion to have, but a consensus should be reached before this moves forward

2024-11-21 15:27 UTC, ClownMoff commented
Let's discuss this again.

They shoot 16 shots instead of 12 now, a reduction of 36% in magazine. Enough to take 3 people if you don't miss a single shot, 2 if you miss 4, one if you miss 10 out of the 16 bullets

2024-11-28 17:38 UTC, PowerfulBacon commented
I played security yesterday and just never bothered reloading the disabled between fights. I agree with this PR

2024-12-29 18:36 UTC, DarnTheMarn commented
Seeing as I mentioned this PR, I'll cross post what I said over there. Nerfing their shot count is better than nothing, but it's a half measure. Lean all the way into it being a sidearm by reducing shot count **and** damage so it's more like a service pistol instead of an energy gun, or make it bigger and leave it as is.

2025-03-06 17:44 UTC, PowerfulBacon requested changes
Rather than make it so that the disabler beam is more expensive except for the subtypes, make it so that the disabler just has a smaller capacity.

2025-04-03 13:50 UTC, Tsar-Salat commented
Requested changes added a month ago and not addressed. Staling.

2025-04-16 13:18 UTC, ClownMoff commented
No longer stale. Ready for review.

2025-05-17 17:13 UTC, PowerfulBacon commented
I will agree with the wisdom of the crowd here, given it has -11, +1

2025-05-19 11:56 UTC, ClownMoff commented
![image](https://github.com/user-attachments/assets/d5d1eb4f-2ad6-4599-b8cb-97b11d06cb66)

You agreed with me bro, did you just make a desition out of the collective secoff opinion?

The majority of negative reactions were to the initial reduction to 12 shots, it is now 16. This at least deserves a testmerge in my opinion, is a warranted nerf. Once again, 25 shots in a row is too many, log into the game and shoot 25 times in a row. In fact, join in with someone else and have them chase you with a disabler and see how far you reach dodging disabler shots. It has been now 7 months with this PR open, make a desition already about it it's really not that deep, disablers are too strong and this tunes them down a little.

2025-05-19 12:02 UTC, ClownMoff commented
And also keep in mind, they recharge twice as fast, it's more of a balance thing than a straight nerf. And the negative emojis all came before the actual changes. Refer to this video.

> New testing evidence for the changes. Now they also recharge twice as fast. You will run out of ammo faster, but can go back in action twice as fast.
> 
>  8mb.video-RXd-jAnfizxw.mp4

2025-05-21 23:38 UTC, DarnTheMarn commented
25 on a pistol is a lot, but with dual wield getting yanked away the disabler is a lot less bad. It's still stupid that it's a primary weapon in a secondary weapon configuration, but what are you gonna do.

2025-06-11 17:01 UTC, Tsar-Salat commented
It clear this isn't going anywhere with Bacon's key.

Frankly, a disabler nerf was never going to work. A full rework like https://github.com/BeeStation/BeeStation-Hornet/pull/12400
is much more engaging from a design perspective.

🔑

2025-06-16 09:26 UTC, ClownMoff commented
It's been a nice 8 months... we did good for a couple of goofballs...

2025-06-16 09:26 UTC, closed without merging