Moves a deltastation wire
BeeStation/BeeStation-Hornet pull request #11874
Opened 2024-11-11 18:56 UTC by PowerfulBacon

## About The Pull Request

Moves a deltastation cable so that only 1 cable is under the APC.
This change is required for smartcables.

## Why It's Good For The Game

This change is needed for smartcables. I thought it would be best to just do it here, so that smartcables can be done entirely via update paths only.

## Testing Photographs and Procedure

![image](https://github.com/user-attachments/assets/3bf5f8a5-2ccc-47cc-9a65-0b605df66a25)

See mapping tests.

## Changelog
:cl:
tweak: Moved a cable on deltastation supermatter's APC so that 2 wires don't overlap at the terminal.
/:cl:

2024-11-11 19:09 UTC, Tsar-Salat approved these changes

2024-11-11 19:17 UTC, mystery3525 approved these changes

2024-11-12 00:14 UTC, Dejaku51 requested changes
You've put gas to filter pump and cyan visible pump on the same tile, right in front of the doors

2024-12-02 12:30 UTC, spockye approved these changes

2024-12-02 16:52 UTC, PowerfulBacon commented
I'll do this today

2024-12-03 09:18 UTC, Dejaku51 approved these changes
looks good

2024-12-03 17:09 UTC, merged