Explosion batching
BeeStation/BeeStation-Hornet pull request #11878
Opened 2024-11-12 19:12 UTC by PowerfulBacon

## About The Pull Request

- Significantly optimises mass-explosions by only flickering the lights a maximum of once per non-sleep execution.
- Implements a limit of 101 explosions in a row for any particular turf, so that >1000 explosions from a single turf will likely get caught before the server freezes for a few seconds.

## Why It's Good For The Game

Fixes an issue with explosive lemons in fridges causing the server to freeze 

## Testing Photographs and Procedure

https://github.com/user-attachments/assets/8b33bf96-e124-4bcd-a97d-5a564e662429

## Changelog
:cl:
fix: Fixes some issues related to mass explosions
/:cl:

2024-11-12 19:49 UTC, Rukofamicom commented
Thank you for the superior fix

2024-11-12 21:39 UTC, Rukofamicom approved these changes

2024-11-12 21:40 UTC, Rukofamicom commented
While this is a vast improvement, this may not catch cases such as the lavaland base or adjacent fridges filled with the fruits due to simultaneous explosions on multiple turfs.

These are a lot rarer than the single botany fridge though.

2024-11-12 21:57 UTC, PowerfulBacon commented
The lavaland based seemed fine the last time I saw it explode

2024-11-12 22:17 UTC, Rukofamicom commented
Explosion act caused a bomb core to appear and immediately explode... Which then triggered explosion act on the wall again, which causes another bomb core to spawn and explode.

The difference is that each explosion would trigger a new core spawn and explosion on each affected turf, not just a single one.

This would repeat until the game processing got far enough to realize the walls were destroyed and should stop spawning further bomb cores.

---

That has since been (mostly*) fixed because I made it so walls can only spawn a single core each. (*Now instead the walls have a ?% chance to spontaneously spawn a syndicate bomb core on top of them at init and I don't know why)

2024-11-13 01:40 UTC, EvilDragonfiend requested changes, later dismissed
This shouldn't make 1500 addtimer to call the proc.
This should be a proc that calls 1500 procs in a certain time (so, we only add one addtimer)
This is very important.

2024-11-13 02:42 UTC, EvilDragonfiend commented
I still don't like the code but addtimer part was what there was already. Maybe it wouldn't be matter at this PR.

2024-11-14 01:03 UTC, merged