Adds In-game Report Template
BeeStation/BeeStation-Hornet pull request #11880
Opened 2024-11-14 08:18 UTC by EvilDragonfiend

## About The Pull Request
Adds In-game Report Template

## Why It's Good For The Game

## Testing Photographs and Procedure

![image](https://github.com/user-attachments/assets/56c1eede-1599-4b55-bcc0-a4ca2e45429c)

https://forums.beestation13.com/t/testing-ingame-report-template-system/26385

Copypasta result

## Changelog
:cl:
add: "Admin" tab now has "Copy In-game Report Template". You can copy ingame information for Beestation player report. This may not be synced in downstream format though.
/:cl:

2024-11-14 09:38 UTC, BriggsIDP commented
Great PR. 
This would be great for bug reports too. Many users vocally don't report bugs because they require a git hub account. if it where possible to have a bug reported in game posted to the codebase under a bot with the users name I think we would have a lot more reports; this would probably need crossed perm though

2024-11-14 10:46 UTC, EvilDragonfiend commented
> Great PR. This would be great for bug reports too. Many users vocally don't report bugs because they require a git hub account. if it where possible to have a bug reported in game posted to the codebase under a bot with the users name I think we would have a lot more reports; this would probably need crossed perm though

yep, but likely once this is found to be working well.

2024-11-14 11:23 UTC, Archanial requested changes
I don't think it is necessarily healthy to have this in the game.
Also if anything either do it in tgui instead of plain html or just open forum (where the template is added by default to posts)

2024-11-14 13:04 UTC, PowerfulBacon commented
1. This needs to be config
2. Is this actually all that useful? It doesn't fill out a lot of information and people should never be making reports without making an ahelp first to get it solved immediately.

Rather than being a verb, if this is to exists then it should be a message in chat when you create an ahelp. When clicking the link it should open the reports website in a new browser and copy the report into the clipboard, including the original ahelp message.

2024-11-14 17:16 UTC, EvilDragonfiend commented
> 1. This needs to be config

sure but I won't make the format configurable. I don't want to put much effort right now.
> 2. Is this actually all that useful? It doesn't fill out a lot of information and people should never be making reports without making an ahelp first to get it solved immediately.

You'll be surprised even writing such basic stuff is how tedious it is. That's why people put the thumb up tags there a lot.

> Rather than being a verb, if this is to exists then it should be a message in chat when you create an ahelp. When clicking the link it should open the reports website in a new browser and copy the report into the clipboard, including the original ahelp message.

I don't think it is possible to do "copy the desired contents to clipboard when you click it on a chat button" in this byond system because of cursed IE11(not real). The thing in my PR is done with a cheating way but it's not feasible in chat system.

2024-11-16 12:06 UTC, EvilDragonfiend commented
Template is now configurable. Check `player_report_template.txt` in config directory.
```
// check 'get_ingame_report.dm' for the detail. Enable 'USE_PLAYER_REPORT_TEMPLATE' config if you want to use this. (Also this first is not copied)
# In-game report: (by In-game template)

&lt!-- [READ ME] Title should be: [Offender's CKEY] Player Report --&gt

CKEY: %CKEY%

Your Character Name: %MOB_NAME%

Your Discord:

Offender's CKEY:

Offender's In-Game Name:

Date (YYYY-MM-DD): (UST) %DATE% (template copied)

Round Number: %ROUND_ID% (%SERVER_NAME%)

Rules Broken:

Incident Description:

Additional Information:
```
This is our template

```
// check 'get_ingame_report.dm' for the detail. Enable 'USE_PLAYER_REPORT_TEMPLATE' config if you want to use this. (Also this first is not copied)
**Your ckey:** %CKEY%

**Your IC Name:** %MOB_NAME%

**Your Discord ID:**

**Date of round: ** %DATE% (template copied)

**Round ID:** %ROUND_ID% (%SERVER_NAME%)

**Defendant’s IC Name:** 

**Complaint:**
```
This is NSV template (as sample)

2024-12-24 15:05 UTC, PowerfulBacon commented
I'm not completely against this but I think it needs much more integration with the ahelp system and work to really be useful

2025-02-10 17:28 UTC, PowerfulBacon commented
I don't want to accept new UIs which use the old HTML format and I don't think this is particularly helpful since the template is already on the forums and this only fills out the easiest to complete properties. Improving the admin process would require a larger amount of work to rework the ahelp process and it would be unreasonable to expect that to be completed for this PR.

2025-02-10 17:28 UTC, closed without merging