[PORT] Security badges
BeeStation/BeeStation-Hornet pull request #11885
Opened 2024-11-15 04:26 UTC by Marshmellow105

## About The Pull Request

Gives the HOS, Warden, Officers and Detectives new security badges which you can wave around when you shout about the NTSD. The sprites come from eris, I just added a red stripe to the security badge.

![image](https://github.com/user-attachments/assets/01dea97a-adef-4ff4-b245-382cc9e049e3)

## Why It's Good For The Game

A little roleplay flavour for the security department.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

Item sprites (Detective, Security)
![image](https://github.com/user-attachments/assets/87a7b1ef-bcfc-4464-b688-0cf8873caad8)

Worn sprites (Same order)
![image](https://github.com/user-attachments/assets/8fdc02e7-6f67-4f0a-a650-ecf551daea0b)

In game (Detectives badge)
![image](https://github.com/user-attachments/assets/3df795a0-2a28-4811-aeed-39854eefe51d)
![image](https://github.com/user-attachments/assets/7baf9331-68a4-419b-812a-f8f61ece4c37)

In game (Security badge)
![image](https://github.com/user-attachments/assets/7067b27f-8cd0-435d-a0d8-a6e5b24597a0)
![image](https://github.com/user-attachments/assets/6b69669a-48b5-4e7d-b7d2-2a9db9d1360f)

In game whilst worn
![image](https://github.com/user-attachments/assets/01dea97a-adef-4ff4-b245-382cc9e049e3)

</details>

## Changelog
:cl: marshmellow10, thevandie
add: Added badges for the Detective and Security
/:cl:

2024-11-15 04:55 UTC, EvilDragonfiend commented
you should specify the port source PR

2024-11-15 05:18 UTC, Marshmellow105 commented
done

2024-11-15 06:29 UTC, Geatish commented
Shouldnt there be a special badge for HoS too you think? Also, since we are starting to rack up suitables, maybe we should port that multiple suit items from tg

2024-11-15 06:33 UTC, Marshmellow105 commented
> Shouldnt there be a special badge for HoS too you think? Also, since we are starting to rack up suitables, maybe we should port that multiple suit items from tg

I could probably throw gold on the officer badge for the HOS

as for the multiple suit items, that apparently requires rightclick/combat mode which is the equivalent of a level 300 raid boss to my level 1 coder class

2024-11-15 07:36 UTC, Geatish commented
> that apparently requires rightclick/combat mode which is the equivalent of a level 300 raid boss to my level 1 coder class

That sounds way out of my range, which i will be stupid enough to try it

2024-11-15 08:02 UTC, Marshmellow105 commented
the HOS badge has been added by request

![image](https://github.com/user-attachments/assets/8f715abb-5fcc-4193-8f55-8bc6fa5c26dd)

2024-11-15 08:20 UTC, Marshmellow105 commented
Think of the fun you can have.

![badge](https://github.com/user-attachments/assets/d61199ee-89a9-4271-89f5-d21b70bf6a83)

2024-11-15 11:53 UTC, ClownMoff commented
Make a clown one

2024-11-15 14:17 UTC, Geatish commented
a final request, make them fit inside of a wallet, if you haven't already

2024-11-15 14:21 UTC, Marshmellow105 commented
> a final request, make them fit inside of a wallet, if you haven't already and add a weight class to them....

Do you have an example of an item that isnt an ID that can go into a wallet so I can look it up when I get off of work?



> Make a clown one

I couldn't do it justice. Imagine a bananium badge with a little afro like the clown PDA.

2024-11-15 14:26 UTC, Geatish commented
> Do you have an example of an item that isnt an ID that can go into a wallet so I can look it up when I get off of work?

Just add `/obj/item/clothing/accessory/badge/officer` to the list of things in wallet.dm
like this
![image](https://github.com/user-attachments/assets/d9ea36cd-607e-429e-9e47-63579129f98d)

2024-11-15 14:28 UTC, Marshmellow105 commented
my man 🤝

2024-11-16 09:36 UTC, PowerfulBacon requested changes

2024-11-16 09:36 UTC, PowerfulBacon commented on code/modules/clothing/under/accessories.dm
> +    add_fingerprint(user)
Call ..() instead of manually adding the fingerprint

2024-11-16 15:12 UTC, PowerfulBacon approved these changes

2024-11-17 09:25 UTC, EvilDragonfiend approved these changes

2024-11-17 09:42 UTC, merged