Refactors ghost-role sentience
BeeStation/BeeStation-Hornet pull request #11897
Opened 2024-11-17 12:09 UTC by PowerfulBacon

I encountered an issue where diona nymphs could bypass the ghost-role cooldown, allowing for you to have infinite lives in combat scenarios. Simple fix right, wrong. This uncovered one hell of a mob spawning rabbit hole that goes deeper than you could have ever imagined.

## About The Pull Request

- Converts ghost role sentience into a component.
- Refactors most ghost role spawns to use this component, and erases the many different implementations of ghost role sentience that we had.

Things are now standardised:
- All sentience spawns will appear in the spawner menu
- Nymphs now respect the ghost role cooldown

There are 2 types of ghost sentience options:
- Unique: Will appear as its own unique entry inside the spawners menu
- Grouped: Will concatenate mobs with the same non-unique name into the same category and will spawn the player in the closest mob to their ghost when they click spawn

Makes the spawn message when you enter a body more clear:

![image](https://github.com/user-attachments/assets/9edbb941-59d9-46d9-9714-dd5c216e2011)

Also ghosting will now give you a ghost role cooldown.

The following sentience spawns are affected:
- Transform disease (replacing banned players)
- Pyro anomaly slimes
- Spiders (Structures can be given the ghost spawner too, though spiders use their own unique spawning behaviour to setup teams)
- Mass sentience secret
- Ghostize smite
- Antagonists replacing banned players (Only if nobody accepts the prompt)
- Blob zombies
- Xeno larvae (They require a ghost to spawn, so this only really affects if a larvae ghosts)
- Nymphs
- Light pink slime potioned slimes
- Replace banned cyborg (Only if nobody accepts the prompt)
- Exploration ghost roles

Other changes:
- Spawners menu will always show flavour text

## Why It's Good For The Game

Things being standard is good, it means that any issues will be shared across all ghost spawners making them much easier to fix.

## Testing Photographs and Procedure

<details>
<summary>
Nymphs
</summary>

![image](https://github.com/user-attachments/assets/8f16c934-2756-4c21-bf5b-9f05584fd64c)

1 alert for all nymphs

![image](https://github.com/user-attachments/assets/8348e7f5-82ef-45ea-b7e0-230308a11c46)

Clicking on a specific message gives you that specific mob

![image](https://github.com/user-attachments/assets/ee127e36-fe01-446a-b104-ed0714c379f2)

Spawner menu:

![image](https://github.com/user-attachments/assets/23377bad-d668-4b29-a7fd-1ef59669560a)

![image](https://github.com/user-attachments/assets/796ad060-4a24-44e1-8db7-535319e60457)

</details>

<details>
<summary>Pyro Slime</summary>

![image](https://github.com/user-attachments/assets/c7c84778-76af-45f7-83c9-484a7ebb9624)

![image](https://github.com/user-attachments/assets/d6f9453b-36e3-48b4-a1fe-020fa44b4b62)

![image](https://github.com/user-attachments/assets/54ac92e7-e40c-4c4c-a0e4-17901fcb0db4)

Ghosting:

![image](https://github.com/user-attachments/assets/ebffb4e3-9c52-47f3-8ce7-e7992402923e)

</details>

## Changelog
:cl:
fix: Nymphs now appear in the ghost menu and respect respawn delay.
add: Adds a message for ghost role spawning
fix: Standardises ghost sentience spawning and ensures that enslaving works for all spawned mobs.
/:cl:

2024-11-17 18:28 UTC, llol111 commented
Does this also affect sentience baloons?

2024-11-17 18:28 UTC, PowerfulBacon commented
No, it affects everything listed in the PR body and those things only

2024-11-26 02:06 UTC, EvilDragonfiend requested changes

2024-11-26 02:06 UTC, EvilDragonfiend commented on code/datums/components/ghost_spawner.dm
> +		if(istype(ghost))
```suggestion
		if(isdead(ghost))
```
istype is not sufficient to prevent href exploit.

2024-11-26 02:06 UTC, EvilDragonfiend commented on code/datums/components/ghost_spawner.dm
> +			return
I don't understand why you check `istype()`.
does it mean there can be null or path?

2024-11-26 02:06 UTC, EvilDragonfiend commented on code/datums/components/ghost_spawner.dm
> +	/// Have we alerted already?
two lines, mistake? also, instead of questioning sentence, please describe normally.
* `/// If set, implies the spawner is alerted already`

2024-11-26 02:06 UTC, EvilDragonfiend commented on code/datums/components/ghost_spawner.dm
> +	/// If we are using a spawned type, should we delete the parent after spawning?
```suggestion
	/// Decides if the parent should be deleted after spawning (When we use a spawned type)
```
Questioning tone is bad to read.

2024-11-26 02:06 UTC, EvilDragonfiend commented on code/datums/components/ghost_spawner.dm
> +	UnregisterSignal(parent_mob, COMSIG_ATOM_ATTACK_GHOST)
I see some missing unregister signals:
* COMSIG_LIVING_DEATH, 
* COMSIG_MOB_GHOSTIZE

I am not certain if it's not necessary.

2024-11-26 02:06 UTC, EvilDragonfiend commented on code/datums/components/ghost_spawner.dm
> +/// component.
two lines?

2024-11-26 02:06 UTC, EvilDragonfiend commented on code/datums/components/ghost_spawner.dm
the component is missing of `on_mob_revival()` proc that reenables a mob's ghost spawner that reverts the effect of `on_mob_death()`

2024-11-26 02:06 UTC, EvilDragonfiend commented on code/datums/components/ghost_spawner.dm
> +	var/datum/mind/master = null
this should be weakref

2024-11-26 02:10 UTC, EvilDragonfiend commented
ah, also `ghostize` shouldn't be counted for all cases. There are 2 cases of ghostize:
* Ghostize to skip last breath
* Ghostize when you're dead already.
I am not particularly sure if doing ghostize when you're dead already is a thing, but I think it was.

2024-12-22 22:13 UTC, Tsar-Salat commented
Can this pr wait on https://github.com/BeeStation/BeeStation-Hornet/pull/12042 ?

I understand this PR is older, but I think it will benefit greatly from the reorganization of spawners from that pr.

2025-01-16 00:24 UTC, closed without merging