Shaft miners start with gauze
BeeStation/BeeStation-Hornet pull request #11906
Opened 2024-11-19 12:46 UTC by Therealdoooc213

## About The Pull Request

Shaft miners will not start with medical gauze in their backpack

## Why It's Good For The Game

Shaft miners bleed often and the medipen doesnt fix that, they shouldnt have to go out of their way to medical for gauze, summon a survival pod, or bleed to death.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

![image](https://github.com/user-attachments/assets/000ec7d0-0e65-435d-8898-fbc0d8a8fb36)

</details>

## Changelog
:cl:
tweak: miners start with gauze in their backpack now
/:cl:

2024-11-20 23:49 UTC, Rukofamicom commented
There are multiple rolls of gauze in every pod and the miner lockers (all six of them) come with a pod if you need it. In addition to this the mining base has first aid kits with more. Most of the time miners don't ever get hit in melee unless they're taking the crusher or just really mess up. 

There's nothing wrong with tossing a pod down for gauze, they work best when scattered around the wastes anyway. 

This is just clutter in the starting inventory 🔑

2024-11-21 00:02 UTC, Fronsis commented
> There are multiple rolls of gauze in every pod and the miner lockers (all six of them) come with a pod if you need it. In addition to this the mining base has first aid kits with more. Most of the time miners don't ever get hit in melee unless they're taking the crusher or just really mess up. There's nothing wrong with tossing a pod down for gauze, they work best when scattered around the wastes anyway.
> 
> This is just clutter in the starting inventory 🔑
> 
> A better solution is to add it to the crusher voucher exchange


Why would a miner need to use a pod just to get some gauzes realistically it doesn't makes sense lol it's literally some gauzes, and wasting one right in front of the base to get gauzes is silly, you could even add it roundstart to their survival box(which still doesn't fit GPS)

You're proposing the miner to walk around with multiple shelter capsules which clutters the inventory even more.

Most *robust*/*veteran* miners don't get hit by Melee, and in fact even since smooth movement got merged i've seen a lot of veteran players get hit either on megafauna fights or a random normal fauna like tentacles, and usually there's always a miner that speedruns grabbing the entire gauze for themselves from the medspot and the newbies have no idea about that.

If anything is the crusher voucher exchange or.. a whole revamp to the inventory of miners with like a special webbing or something considering what they also grab from the locker but  this is literally just gauzes.

2024-11-21 00:08 UTC, Fronsis commented
Another alternative would be to make the miners medipen stop bleeding, what about that Ruko?

2024-11-21 04:46 UTC, Rukofamicom commented
Your response points are baffling

> Why would a miner need to use a pod just to get some gauzes ... You're proposing the miner to walk around with multiple shelter capsules

There are two capsules per miner slot. They are tiny items. **each** capsule contains four rolls of gauze (as well as other med supplies and pre-heated donk pockets) as part of the shelter, and the shelter capsules are explicitly for both storm protection and emergency first-aid. I'm not expecting miners to carry multiple capsules at a time, I'm expecting them to carry at least one for emergencies and then to utilize it in the event they have one - getting mauled by fauna is a medical issue that the pods are designed to help with.

> and usually there's always a miner that speedruns grabbing the entire gauze for themselves

There are no less than **TWENTY FIVE** rolls of gauze that are roundstart available to miners. Miners are not bleeding at roundstart, they are only bleeding after having been mauled and are more than capable of holding the wound for the brief tick up of a capsule. 

> Most robust/veteran miners don't get hit by Melee, and in fact even since smooth movement got merged i've seen a lot of veteran players get hit either on megafauna fights

All of my statements are in regards to normal fauna fights, megafauna are a different type of beast (literally) and no miner is ever reasonably going to use gauze against any of them - you use regenerative cores (which also stop bleeding and instantly set normal blood volume) because bleeding is the least of your concern in the middle of a megafauna fight. If you've been hit enough times that bleeding is a concern, the direct wound damage is already slowing you enough that you're about to die if you don't address the wound itself.  You would only use gauze in circumstances where you have completely disengaged, or the fight has just ended with you winning by the skin of your teeth. 

> random normal fauna like tentacles

This does not cause bleeding. Only melee attacks cause bleeding, and regular mobs rarely ever in range of a miner unless they're using a crusher. The only notable exception are tendrils that are generating legions - the skulls can swarm and bleed someone who isn't careful in their approach. 

> a whole revamp to the inventory of miners with like a special webbing

Miners literally have roundstart access to a webbing via their voucher, or can purchase one for pretty cheap from the point vendor. The roundstart one comes with a free shelter capsule. 

> Another alternative would be to make the miners medipen stop bleeding

The pen is already absurdly powerful and so are the regenerative cores. Regenerative cores already stop bleeding as well as fully restoring blood volume.

2024-11-21 04:50 UTC, Rukofamicom commented
None of this has anything to do with veteran vs new player. 
If a player is experienced enough to want to seek gauze, they should next be learning where to look for it at about the same time.

If they are refusing to utilize their source of gauze after they are in need of gauze, that's a certified skill issue.

2024-12-01 21:57 UTC, PowerfulBacon commented
It should start in the box if its going to exist

2024-12-01 22:16 UTC, Therealdoooc213 commented
![image](https://github.com/user-attachments/assets/348f724b-3f0f-4241-bd35-d604a3731159)

2024-12-03 17:07 UTC, PowerfulBacon commented
And that fits correctly right? You can put it back in the box after taking it out

2024-12-03 22:12 UTC, Therealdoooc213 commented
> And that fits correctly right? You can put it back in the box after taking it out

Yep, fits perfectly fine

2024-12-04 08:41 UTC, PowerfulBacon approved these changes

2024-12-23 17:57 UTC, itsmeow requested changes

2024-12-23 17:57 UTC, itsmeow commented on code/game/objects/items/storage/boxes.dm
> +	new internal_type(src)
```suggestion
	..()
```

2024-12-24 06:29 UTC, itsmeow approved these changes

2025-01-13 00:21 UTC, Tsar-Salat commented
> And that fits correctly right? You can put it back in the box after taking it out

This is what the outfit unit test is for.

2025-01-13 00:22 UTC, Tsar-Salat approved these changes
Looks fine. 

3 approvals > 1 key

2025-01-13 15:38 UTC, merged