Gives BoxStation cargo a fresh coat of paint / Makes the kitchen feel better to play
BeeStation/BeeStation-Hornet pull request #11909
Opened 2024-11-20 00:16 UTC by ClownMoff

## About The Pull Request

- Rearranged some stuff in and around the kitchen
- Gave cargo a fresh coat of paint
- Made the QM room bigger

## Why It's Good For The Game

BoxStation is dated! As for the kitchen, I was trying to cook in there the other day and I was having a rough time managing the space since there wasn't really a lot

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: ClownMoff
tweak: BoxStation: Give new tiles to cargo as a department
tweak: BoxStation: Resized the QM room
tweak: BoxStation: Made some small changes in room layout on the main area and mining
tweak: BoxStation: Rearranged some stuff inside and outside the kitchen to have a better layout to work with ingredients
del: BoxStation: Removed an extra gibber from the kitchen
/:cl:

2024-11-20 05:33 UTC, Fronsis commented
Can you also fix the service maint area access? :3 

Really like the new kitchen, i agree it was a little cramped before and this new look is what i needed

2024-11-25 01:40 UTC, ClownMoff commented
That maintenance area should have been fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/11690

2024-12-04 13:01 UTC, spockye reviewed
sorry about the long wait! this has been sitting for wayy too long without a review

while theres some good use of tiling, im not sure if i agree with the dark colour use... 
when i think about dark floors high security comes to mind, not cargo.
 Imo dark colours dont really fit cargo all that well :p  Mabye try replacing it with their lighter counterparts? some dark is totally alright and would probably help, but i dont think the primary colours for cargo should be black. 
Not gonna force you to change it, but i recommend you do

2024-12-10 11:48 UTC, BarteG44 commented
Dark can work well, given some brown decals

2025-03-18 16:51 UTC, PestoVerde322 requested changes
![image](https://github.com/user-attachments/assets/4d252f70-61dc-49eb-b29b-6a988d63d6db)

Still pipes in walls, also there's a 2x1 area that is disconnected, would suggest to add a maint access there instead

Also, overall cargo feels still drab, add some cargo brown decals around to make it look like it is in fact, cargo. Also also i'd make the waiting room the same as the hallways to have some sense of "continuity".

![image](https://github.com/user-attachments/assets/fa7789ee-57c1-4998-bed9-9488abaaa461)

Not a big fan of the smartfridge being next to a door, maybe shift some element of botany?

2025-04-12 03:23 UTC, Tsar-Salat commented
Requested maptainer changes remain unaddressed.

Address pigeon and I will attempt to get this in in a timely manner, I know you have waited quite a bit, so I would rather this not go stale now.

2025-06-10 00:23 UTC, closed without merging

2025-06-10 08:59 UTC, ClownMoff commented
DON'T CALL IT A COMEBACK