Rat'var sound fix
BeeStation/BeeStation-Hornet pull request #11919
Opened 2024-11-21 04:22 UTC by Therealdoooc213

## About The Pull Request

Fixes #8570

Rat'var played its summoning noise to everyone, including people on the menu.

## Why It's Good For The Game

People on the menu shouldnt be able to hear rat'var summoning and see the summon message.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

https://github.com/user-attachments/assets/7cb71714-9f14-420c-bed9-b54f4e10e57c

</details>

## Changelog
:cl:
fix: rat'var's summoning sound no longer plays on the menu
/:cl:

2024-11-21 07:48 UTC, PowerfulBacon requested changes
Read the chat during testing, note the lack of the appearance message

2024-11-21 13:27 UTC, Therealdoooc213 commented
> Read the chat during testing, note the lack of the appearance message


https://github.com/user-attachments/assets/0220a583-f19e-4207-b8a3-ed2641ecece3

Fixed

2024-11-21 20:39 UTC, PowerfulBacon approved these changes

2024-11-22 02:52 UTC, EvilDragonfiend approved these changes

2024-11-22 03:15 UTC, merged