Ore silos can no longer be eaten by swarmers.
BeeStation/BeeStation-Hornet pull request #11929
Opened 2024-11-22 21:45 UTC by Therealdoooc213

## About The Pull Request

In the title, swarmers are no longer capable of eating ore silos

## Why It's Good For The Game

Let me give you a situation here.
You are a engineer working on a fun project, BSA, custom shuttle, etc. You go your lathe, and it says there's no ores? Weird. You ask the AI to let you into the vault and you're met with the ore silo board destroyed, and all of the iron and glass eaten. Is this fun for the crew? No. Is it fun for the quartermaster/HOP who has to go around relinking everything with a new ore silo? No, not at all.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

https://github.com/user-attachments/assets/08821a64-3b61-40e0-b197-a214a83ae0fe

</details>

## Changelog
:cl:
balance: swarmers can no longer eat ore silos
/:cl:

2024-11-23 00:49 UTC, RDS88-beeman commented
This is the tiniest possible nitpick, but I don't think any other swarmer text explicitly calls machines by their actual names. Maybe "this object should be preserved, the infrastructure will be useful to our masters in the future" would be better, but ultimately this doesn't matter at all.

Maybe stop them breaking lathes while you're at it. They already can't eat chem dispensers or botany trays arbitrarily, or teleport slimes, so doing it for game balance reasons is very precedented.

2024-11-23 01:00 UTC, Rukofamicom commented
I maintain that ore silos were a mistake to begin with - centralizing all of the resources on the station in a single location.

2024-11-23 03:55 UTC, XeonMations commented
make lathes unbreakable by swarmers next <3

2024-11-25 02:01 UTC, EvilDragonfiend requested changes
Make them siphon a small amount of a random material instead of blocking.

2024-11-25 14:33 UTC, Rukofamicom commented
Attacking solo gives them 1 resource at the cost of a random silo material sounds like a good compromise.

2024-11-25 23:52 UTC, Therealdoooc213 commented
lost interest in this idea, because i think its kinda stupid now

2024-11-25 23:52 UTC, closed without merging

2024-11-26 01:57 UTC, XeonMations commented
Fine, I'll do it myself.