Adds 4 cool jackets
BeeStation/BeeStation-Hornet pull request #11930
Opened 2024-11-23 01:45 UTC by ClownMoff

## About The Pull Request

Adds 4 new drip options to the game:

![akira-kaneda-jacket-1-1000x1176](https://github.com/user-attachments/assets/a901357b-1f1b-45c1-bc0c-be23df738c85)
![s-l1200](https://github.com/user-attachments/assets/6fe85493-37f3-4b3a-9faa-80745808dbe2)
![Tunnel_Snake_outfit](https://github.com/user-attachments/assets/b6acd713-8be7-4535-ac77-4c4d60e48061)
![Kim_Kitsuragi](https://github.com/user-attachments/assets/c02e61ff-b743-4b31-8080-92df82a2b74c)

## Why It's Good For The Game

More drip options

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Added 4 new jackets: Underground Serpents jacket, Teen Biker Jacket, Liutenant Jacket and Driver jacket. Find them in the AutoDrobe
/:cl:

2024-11-23 08:32 UTC, PowerfulBacon requested changes, later dismissed
The item names, paths and descriptions need to be less on the nose references. They should either be a description of the item, or have some 'lore' set in the universe completely unrelated to the references. We have rules against content being references and nothing else, and I'm not accepting a typepath being /literallyme. Give us some kind of descriptiveness in the typepath, and it should match the name.

2024-11-23 17:33 UTC, Rukofamicom commented
Are these original or ported? 

I swear I've seen this exact tunnel snakes reference before.

2024-11-23 17:36 UTC, ClownMoff commented
> Are these original or ported? I swear I've seen this exact tunnel snakes reference before.
> 
> > "Underground Serpents Jacket rules, we are the underground serpents. That's us, and we rule! ."

I've tried adding the jacket 3 times now 😭, it's original content

2024-11-23 20:49 UTC, PowerfulBacon commented on code/modules/clothing/suits/jacket.dm
> +	name = "Liutenant Vest"
The correct spelling is lieutenant

2024-12-09 20:03 UTC, Tsar-Salat commented
> I swear I've seen this exact tunnel snakes reference before.

Clearly this guy hasn't seen the 2009 classic.

https://www.youtube.com/watch?v=S0ximxe4XtU

2025-02-01 19:00 UTC, PestoVerde322 approved these changes
All good to go now!

2025-02-07 09:12 UTC, merged