Screentips
BeeStation/BeeStation-Hornet pull request #11938
Opened 2024-11-24 12:31 UTC by PowerfulBacon

## About The Pull Request

Implements the foundation for contextual screentips.

Contains a partial port of: https://github.com/tgstation/tgstation/pull/76889 since I struggled to find documentation on images in maptext.
Contains a partial port of https://github.com/tgstation/tgstation/pull/63567 as I accessed the code to see how TG solved the MouseEntered overhead problem, though I have optimised the code slightly.
The TG code was mainly used to ensure that our system has some resemblance to the TG code, and only makes changes where necessary.
The rest of the code is original code.

It is important to note that simply defining MouseEntered on /atom will incur a pretty significant amount of overhead due to byond enabling networking of mouse entered actions when this is defined, but this is a cost that we are going to have to accept. I did try to implement this clientside, though I faced problems with the label component and it would be impossible to include contextual data. If we are going to have this cost, then we might as well make it as good as it gets.

There are some limitations that I encountered while creating this:
- Icons in maptext don't get properly aligned unless there is text preceeding them on the line.

## Limitations

The context objects will have a lot of proc-calls on objects that have a lot of actions. This may need a testmerge for testing, though since our pops aren't huge and there won't be many things with too many, I don't think the issue will be too great (it's also tied to a subsystem anyway, with low priority).

In the future we may be able to introduce some kind of compilation step that inlines procs for files that have been editted in production.

## Adding screentips to objects

Adding screentips to objects is a matter of defining one of the context procs:
- add_context_self: Defines contextual actions for an object

Context procs pass through a screentip context object, which includes procs that help you define the tips that appear on the object. The context handles styling itself so that we don't end up with inconsistent tips

Context procs:

|Method|Description|
|-|-|
|accept_mob_type(mob_type)|Can be used in if statements to check if a mob matches a certain type, if it does then the screentip will show for that mob. By default screentips only show for humans|
|accept_silicons|Can be used in if statements to check if the user is a silicon, if it does then the screentip will show for that mob. By default screentips only show for humans|
|accept_animals|Can be used in if statements to check if the user is an animal, if it does then the screentip will show for that mob. By default screentips only show for humans|
|add_context(message)|Adds some generic context message to the object. Should be avoided where possible.|
|add_access_context(message, has_access)|Adds an access message to the object, which will show red if the user doesn't have access and green if the user has access.|
|add_left_click_action|Adds an action that can be performed via left click to the object|
|add_left_click_item_action|Adds an action that can be performed via left click to the object, as long as the user is holding the item|
|use_cache|If true, then the item will be cached per the mob type. This should be set if the object's action list doesn't change based on an external state.|

### Example

```dm
/obj/machinery/door/airlock/add_context_self(datum/screentip_context/context, mob/user, obj/item/item)
	..()
	if (machine_stat & BROKEN)	// External state
		return
	if (!hasPower())	// External state
		context.add_left_click_item_action("Pry Open", /obj/item/crowbar)
		return
	// Handle lazy initalisation of access
	if (length(req_access) || length(req_one_access) || req_access_txt != "0" || req_one_access_txt != "0")	// Constant, so not external state
		context.add_access_context("Access Required", allowed(user))
	context.add_left_click_item_action("[panel_open ? "Close" : "Open"] Maintenance Panel", /obj/item/screwdriver)
	if (panel_open)	// External state
		context.add_left_click_item_action("Hack Maintenance Panel", /obj/item/multitool)
		context.add_left_click_item_action("Hack Maintenance Panel", /obj/item/wirecutters)
	if (context.accept_silicons())
		context.add_shift_click_action("Open", (lights && locked) ? "Blocked" : null, (!lights || !locked) && canAIControl(user))
		context.add_ctrl_click_action("[locked ? "Raise" : "Drop"] Bolts", "Blocked", canAIControl(user))
		context.add_alt_click_action("[secondsElectrified ? "Un-electrify" : "Electrify"]", "Blocked", canAIControl(user))
		context.add_ctrl_shift_click_action("[emergency ? "Disbale" : "Enable"] Emergency Access", "Blocked", canAIControl(user))
	else
		context.add_left_click_action("Open", (lights && locked) ? "Bolted" : null, (!lights || !locked))
```

## Caching (WIP)
 
Screentips that don't depend on external state can call `context.use_cache` which, for every input state, will cache the results and re-use it for the rest of the round when that type is encountered in the screentip system again. These must only depend on pre-selected conditions.

Input states are as follows:
- attack_hand: Message shown only when the mob is a human and has nothing in their hand.

If caching is enabled, then the cache will be built as required, requiring no additional effort from the developer:

```dm
context.use_cache()
if (context.accept_silicon())
	if (context.accept_mob_type(/mob/living/silicon/ai))
		context.add_left_mouse_action("Click as AI")
		return
	context.add_left_mouse_action("Click as robot")
else
	context.add_left_mouse_action("Click as human")
```

The above code will work the following way:
- When the screentip is first called as a human, we will cache the human state as 'Click as human' and a condition as added that the cache accepts silicons (since we saw that silicons were accepted)
- When the screentip is first called as a silicon, the context becomes aware that the AI mob type is also accepted, which if we ever encounter it will generate another part to the cache. We add the silicon's message to the silicon cache.
- When an AI is seen, the context is generated for the AI mob and the result is cached.
- When any mob that isn't accepted by the cache at any point is seen, then the cache will let the context know that there are no screentips for this object.

Any external state will break assumptions that the cache makes and will cause incorrect messages to show on the screentip.

While running in debug mode, an extra screentip line is added that tells the developer the cache is active for that object.

## Autotips

To make adding tips easier, I have created a system for auto-tips. These define paths which get automatically added to the global screentip cache upon initialisation.

Since they use the cache, auto-tips cannot depend on external state.

They are defined as follows:

```dm
SCREENTIP_ATTACK_HAND(/obj/machinery/button, "Press")
```

See caching to see the input states.

## Why It's Good For The Game

## Testing Photographs and Procedure

![image](https://github.com/user-attachments/assets/f937f092-b2df-442e-9005-2c1d8fe84d8d)

![image](https://github.com/user-attachments/assets/3b287bf5-0bcb-4ba3-9cdb-cdbffb2ab9d2)

![image](https://github.com/user-attachments/assets/ccf0f4b0-28b6-4aab-b57e-8a0ae29685a5)

## Changelog
:cl:
add: Adds contextual screentips
/:cl:

2024-11-24 12:37 UTC, Geatish commented
Good pr, but there will be an option to turn this off right? I hate having a cluttered screen.
Also something to think about, catching the name of people without examining them isn't ideal, makes it way harder to get away with your identity.

2024-11-24 15:02 UTC, PowerfulBacon commented
It will be a preference, if you can mouse over somebody, you will be able to see their name (which you can do already with the status bar).

2024-11-25 03:57 UTC, EvilDragonfiend requested changes
the term `add` to various proc names sounds very off. It sounds like you're adding an object to a list, and it sounds there's a function 'remove' to be paired with it.
I'd consider using different term. For example:
```dm
/datum/ai_controller/dog/proc/build(datum/source, datum/screentip_context/context, mob/user)
	if (user.a_intent == INTENT_HARM)
		context.assign_action_attack_hand("Punch")
	else
		context.assign_action_attack_hand("Pet")
```
Technically, 'add' describes how exactly the code works, but the current proc name sounds that you can do that multiple times. I mean
```dm
/proc/foo()
	add_attack_hand_action("take item")
	add_attack_hand_action("do thing")
	add_attack_hand_action("punch thing")
```
This isn't a thing, but the name makes it sounds possible.

2024-11-25 03:57 UTC, EvilDragonfiend commented on code/modules/screentips/atom_extensions.dm
> +		client.screentip_context.held_item = null
would you please do `var/datum/screentip_context/screentip_context` instead of taking it from client for every line?

2024-11-25 04:00 UTC, EvilDragonfiend commented
ah, also, I don't like the term `context` is used here. I know it is `screentip_context`, but it may cause confusion with context menu. Not sure if there's a better way to replace it, but please be noted.

2024-11-25 09:07 UTC, PowerfulBacon commented
Context is programming standard.

```
/proc/foo(context)
	context.add_attack_hand_action("take item")
	context.add_attack_hand_action("do thing")
	context.add_attack_hand_action("punch thing")
```
Also this is possible

2024-11-25 12:45 UTC, PowerfulBacon commented
Each individual call also adds a new message, you aren't just setting a single context message but you can add multiple messages to the context for different controls (add a left click, then add a right click, then add a control click, etc.)

2024-11-25 16:06 UTC, llol111 commented
You know, i have conflicted feelings about this.
Since i can turn it off in prefs, theres realy no reason to complain i suppose. And its bound to help newfriends alot alot, which is... good, i guess?
Yet i cant help feel like its bad to add even more screen clutter and "crutches" 🤔

2024-11-26 00:58 UTC, EvilDragonfiend commented
> Each individual call also adds a new message, you aren't just setting a single context message but you can add multiple messages to the context for different controls (add a left click, then add a right click, then add a control click, etc.)

That's what I mean. You don't set multiple contexts to a single action.

2024-11-26 01:03 UTC, Tsar-Salat commented
> Yet i cant help feel like its bad to add even more screen clutter and "crutches" 🤔

You have a vehement dislike of combat mode that you wrote in cope Haiku or whatever on my pr.

This PR will certainly help you.

2024-11-26 07:44 UTC, PowerfulBacon commented
Anything good for new players is generally good for experienced ones too and makes their gameplay experience better

2025-01-08 01:56 UTC, Tsar-Salat requested changes
A few sillies

2025-01-08 01:56 UTC, Tsar-Salat commented on code/modules/screentips/screentip_context.dm
> +		alt_left_mouse_context += "\n[MAPTEXT("<span style='line-height: 0.35; color:[SCREEN_TIP_NORMAL]'>[CENTER("ctrl-[GLOB.lmb_icon] [action_text]")]</span>")]"
```suggestion
		alt_left_mouse_context += "\n[MAPTEXT("<span style='line-height: 0.35; color:[SCREEN_TIP_NORMAL]'>[CENTER("alt-[GLOB.lmb_icon] [action_text]")]</span>")]"
```

2025-01-08 01:56 UTC, Tsar-Salat commented on code/modules/screentips/screentip_context.dm
> +		alt_left_mouse_context += "\n[MAPTEXT("<span style='line-height: 0.35; color:[SCREEN_TIP_INACCESSIBLE]'>[CENTER("ctrl-[GLOB.lmb_icon] [action_text] ([blocked_message])")]</span>")]"
```suggestion
		alt_left_mouse_context += "\n[MAPTEXT("<span style='line-height: 0.35; color:[SCREEN_TIP_INACCESSIBLE]'>[CENTER("alt-[GLOB.lmb_icon] [action_text] ([blocked_message])")]</span>")]"
```

2025-01-08 01:56 UTC, Tsar-Salat commented on code/modules/screentips/screentip_context.dm
> +		alt_left_mouse_context = "\n[MAPTEXT("<span style='line-height: 0.35; color:[SCREEN_TIP_NORMAL]'>[CENTER("ctrl-[GLOB.lmb_icon] [action_text]")]</span>")]"
```suggestion
		alt_left_mouse_context = "\n[MAPTEXT("<span style='line-height: 0.35; color:[SCREEN_TIP_NORMAL]'>[CENTER("alt-[GLOB.lmb_icon] [action_text]")]</span>")]"
```

2025-01-08 01:56 UTC, Tsar-Salat commented on code/modules/screentips/screentip_context.dm
> +		ctrl_left_mouse_context += "\n[MAPTEXT("<span style='line-height: 0.35; color:[SCREEN_TIP_NORMAL]'>[CENTER("alt-[GLOB.lmb_icon] [action_text]")]</span>")]"
```suggestion
		ctrl_left_mouse_context += "\n[MAPTEXT("<span style='line-height: 0.35; color:[SCREEN_TIP_NORMAL]'>[CENTER("ctrl-[GLOB.lmb_icon] [action_text]")]</span>")]"
```

2025-01-08 01:56 UTC, Tsar-Salat commented on code/modules/screentips/screentip_context.dm
> +		ctrl_left_mouse_context = "\n[MAPTEXT("<span style='line-height: 0.35; color:[SCREEN_TIP_NORMAL]'>[CENTER("alt-[GLOB.lmb_icon] [action_text]")]</span>")]"
```suggestion
		ctrl_left_mouse_context = "\n[MAPTEXT("<span style='line-height: 0.35; color:[SCREEN_TIP_NORMAL]'>[CENTER("ctrl-[GLOB.lmb_icon] [action_text]")]</span>")]"
```

2025-01-08 01:56 UTC, Tsar-Salat commented on code/modules/screentips/screentip_context.dm
> +		ctrl_left_mouse_context += "\n[MAPTEXT("<span style='line-height: 0.35; color:[SCREEN_TIP_INACCESSIBLE]'>[CENTER("alt-[GLOB.lmb_icon] [action_text] ([blocked_message])")]</span>")]"
```suggestion
		ctrl_left_mouse_context += "\n[MAPTEXT("<span style='line-height: 0.35; color:[SCREEN_TIP_INACCESSIBLE]'>[CENTER("ctrl-[GLOB.lmb_icon] [action_text] ([blocked_message])")]</span>")]"
```

2025-01-11 13:20 UTC, PowerfulBacon commented
The current goals:
- Implement caching
- Implement pref to disable

I have no plans to rename any of the procs in their current state, and I believe that they have appropriate naming that follow accepted programming conventions.

2025-02-03 09:51 UTC, PowerfulBacon commented
This needs to be completed and merged with high priority so that we can start adding hints for combat mode actions.

2025-02-03 14:16 UTC, PowerfulBacon commented on code/modules/screentips/debug_verbs.dm
> +	to_chat(usr, "<span class='announce'>Building screentip view, please wait...</span>")
This needs to be removed

2025-02-06 22:59 UTC, PowerfulBacon commented on code/modules/atmospherics/machinery/air_alarm/_air_alarm.dm
> +		return
Instead of checking if the player has an item in the context's themselves, we should put the behaviour in the context object to standardise it. I'm thinking having something to track if players have tools to only show the tips if they have a tool on them

2025-02-06 23:01 UTC, Tsar-Salat commented on code/modules/atmospherics/machinery/air_alarm/_air_alarm.dm
> +		return
Yeah. I feel like having all the tools be on screen at once is too much visual noise.

If you can come up with something so I don't have to istype every two lines for a new tool, that'd be useful

2025-02-15 16:17 UTC, PowerfulBacon commented
Will use the more up to date branch on this repo

2025-02-15 16:52 UTC, PowerfulBacon commented
Turns out this branch is up to date and much less conflicting

2025-02-22 14:06 UTC, PowerfulBacon commented
The thing in the bottom left of fullscreen mode can be removed

![image](https://github.com/user-attachments/assets/a7c885ba-3794-4baf-afa4-3fd07ae6238b)

2025-02-22 14:56 UTC, Tsar-Salat commented
> The thing in the bottom left of fullscreen mode can be removed

![image](https://github.com/user-attachments/assets/cdf688fd-c217-4e4a-a3cd-2225f01554ac)

remove the whole thing tbh



> AI should not have screentips by default

ai should not have *item interaction screentips by default.

The modifier keys are still important for regular clicks

2025-03-11 17:58 UTC, PowerfulBacon commented
> hear me out, what if instead of having the tooltips _always_ be on the top, they only showed up next to your cursor when you hovered over something while holding shift. This would place them in an area of the screen you are already looking at, instead of forcing you to look away from what you're aiming at, while still having to continue aiming at it

I like this idea but it would be hard to support controls on it which would defeat the point of them

2025-03-11 22:34 UTC, PowerfulBacon commented
They take up a lot of space, so it would be hard to position multi-line elements.

2025-03-21 22:42 UTC, PowerfulBacon commented
Caching should work the following way:
- If we require knowledge of the held item, caching shouldn't be used anyway.
- If we are looking at something cached, we should load the cache and then load the held item's context on top of the context loaded from cache

2025-05-20 06:49 UTC, PowerfulBacon commented
This is probably just fine to merge

2025-05-26 17:42 UTC, merged