New Colonial Marines ERT, and lavaland ruin.
BeeStation/BeeStation-Hornet pull request #11948
Opened 2024-11-27 18:21 UTC by Therealdoooc213

## About The Pull Request
(THIS PR IS HEAVILY INSPIRED AND USES ICONS FROM CM-SS13)

Adds the United States Colonial Marines (will be said as USCM from now on) lavaland ruin, and a ERT.

The lavaland ruin is a miniature recreation of the Alamo from CM-SS13
The ERT is a group of marines sent by the USCM to investigate a 'distress signal' sent by SS13. Mainly meant for xenomorphs.
I designed the ERT to be a 'glass cannon' of sorts, as their armor is literally worse than security officer armor.

ERT Gear & Armor values

[armor values & ERT gear.txt](https://github.com/user-attachments/files/17938552/armor.values.ERT.gear.txt)

</details>

## Why It's Good For The Game

Beeystation has a severe lack of creativity when it comes to ERT's, its mainly just Blue, Red, Amber, (Honksquad at round end) or death squad once a blue moon. Xenomorphs are a insanely dangerous threat and who else would be better to send to fight them but the USCM?
They're heavily equipped glass cannons that can dish out damage to xenomorphs, but not take them. I believe it'd make a interesting fighting style since they aren't spaceproof.

(The ruin literally has no loot that the miners could take advantage of. The armor is literally worse than security officers roundstart armor. Its only good for looking good)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags

![image](https://github.com/user-attachments/assets/cdbba2cf-8e60-4db0-82e3-48f41d1e8131)
(Yes i know there are issues, i fixed them).

![image](https://github.com/user-attachments/assets/ad0abf4d-2bc9-46ea-a21a-2a454bd446e3)

</details>

## Changelog
:cl:
add: Colonial marines ERT
add: Colonial marines alamo lavaland ruin
/:cl:

2024-11-27 18:27 UTC, Tsar-Salat requested changes
There should be a CM Officer/XO/whateverthefuckColonialMarinescallsthem for the admin spawning the team in to wear, and give them their briefing.

2024-11-27 19:06 UTC, spockye commented
hmm, wouldn't the TGMC icons work a little better with our style?

2024-11-27 19:11 UTC, Therealdoooc213 commented
> hmm, wouldn't the TGMC icons work a little better with our style?

TGMC's style is pretty.. eh. Theyre designed to be fully customized unlike CM-SS13 where its preset and you cant really modify them.

2024-11-27 19:20 UTC, Therealdoooc213 commented
And if we're talking about their xenonauten armor- it looks pretty bad.

2024-11-27 20:34 UTC, Therealdoooc213 commented
Freedom, at last. For the gods have descended upon my PR and graced it with fully completed checks. I thank you.

2024-11-27 23:24 UTC, Therealdoooc213 commented
This also adds a commander loadout for admins to spawn themself in, check testing evidence.

2024-11-29 01:34 UTC, ClownMoff commented
Sprites definitely need adapting to our style

2025-01-24 11:32 UTC, closed without merging