makes badges tiny
BeeStation/BeeStation-Hornet pull request #11941
Opened 2024-11-24 22:20 UTC by Marshmellow105

## About The Pull Request

gives badges the tiny weight class

![Screenshot_7](https://github.com/user-attachments/assets/95338cfa-b8fa-484d-8703-538233ed37b0)

## Why It's Good For The Game

this was sort of intended from the getgo as badges are smaller than your hand

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![Screenshot_7](https://github.com/user-attachments/assets/95338cfa-b8fa-484d-8703-538233ed37b0)

</details>

## Changelog
:cl:
tweak: security badges are now tiny
/:cl:

2024-11-25 15:30 UTC, Dejaku51 approved these changes
i got convinced by the testing evidence

2024-11-27 11:44 UTC, Rukofamicom requested changes
I'm gonna need some better testing evidence, it's not clear enough that this is working as intended.

2024-11-27 12:03 UTC, Marshmellow105 commented
can do

2024-11-27 12:07 UTC, Marshmellow105 commented
> I'm gonna need some better testing evidence, it's not clear enough that this is working as intended.
Improper testing leads to broken code which can ruin the game for others.
![evidence](https://github.com/user-attachments/assets/1dabbd71-d9b5-4a7b-8ee3-9435a5b078d0)

I present to you: testing evidence

please find the tiny badge in this picture

2024-11-27 12:13 UTC, Rukofamicom approved these changes
![image](https://github.com/user-attachments/assets/ebf2b583-dcba-44ee-8af3-065c72c30f64)

Badge confirmed to be tiny, sufficient testing evidence provided.

2024-11-27 12:22 UTC, merged