Fixes Changeling Last resort + digi camo
BeeStation/BeeStation-Hornet pull request #11964
Opened 2024-11-30 19:17 UTC by Geatish

well it the more important part works now

## About The Pull Request

Fixes #11721 
i forgot to pr this 💀 a month ago

- [x] last resort fix
- [ ] triage and fix the digital camo text
the digital camo work as it should from testing, it's just that people wont see the small text that you have it currently active. 

## Why It's Good For The Game

bugs bad

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

I'll get to it, just wait

</details>

## Changelog
:cl:Geatish
fix: Changling last resort and digital camo now works properly 
/:cl:

2024-11-30 20:47 UTC, PowerfulBacon requested changes, later dismissed
I don't believe the examine changes have had enough testing.

2024-11-30 21:02 UTC, Geatish commented
> Place handcuffs on a mob, and examine them.

yep youre right, shits fucked now.

2024-12-05 19:55 UTC, Geatish commented
Alright, im currently moving and i wont be able to work on anything until next year, so im just PRing the working part and making a new issue for the digi camp (it wasnt correctly discribed in the og issue anyways)

2024-12-07 18:23 UTC, PowerfulBacon approved these changes

2024-12-07 19:05 UTC, merged