Adds a flat beecoin source for admins.
BeeStation/BeeStation-Hornet pull request #12001
Opened 2024-12-07 23:55 UTC by Tsar-Salat

## About The Pull Request

A client having the `R_ADMIN` permissions at roundend will give a flat 250 beecoins.

## Why It's Good For The Game

Basically, the only way we have metacoin increases for clients is through the roundend counter or achievements.

The first of which *only* considers playtime as a character in-round. The detriment of this is that choosing to administrate a round over playing ingame is actively a detriment to getting cool stuff as admin. This isn't the perfect solution, but I think the value reaches about around where normal playing is at round conclusion  (~200 beecoins).

I brought this up in an admin meeting and was told that it was a code issue, so here I am.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![Screenshot 2024-12-07 184350](https://github.com/user-attachments/assets/762df7f2-18bc-4e8e-a7a8-2c21515ad66d)

</details>

## Changelog
:cl:
server: admins get a flat beecoin amount at roundend, around what players get for surviving a station and escaping to centcom.
/:cl:

2024-12-08 00:25 UTC, WhereAmO commented
gimme antag tokens instead

2024-12-08 00:34 UTC, Tsar-Salat commented
> gimme antag tokens instead

![damn-door-spiderman](https://github.com/user-attachments/assets/c6d6c034-2cd7-42b5-b973-2abbda9912b5)

2024-12-08 00:58 UTC, llol111 commented
i dont see why this would need to be a thing, i think admins should admin because they want to not for anything else
but i guess i dont have a problem with it either if maints things it a good idea

2024-12-08 08:31 UTC, PowerfulBacon requested changes
This is equal to 9 hours of play in a single round, admins already get donator perms and this will be granted regardless of if they are playing or idling.

The max value should be like 30 and ot should only be rewarded if any amount of tickets were resolved in a round.

2024-12-08 15:38 UTC, Tsar-Salat commented on code/__DEFINES/metacoin.dm
> +#define METACOIN_ROUNDEND_ADMIN 250
```suggestion
#define METACOIN_ROUNDEND_ADMIN 30
```

2024-12-08 15:45 UTC, Tsar-Salat commented
> This is equal to 9 hours of play in a single round, admins already get donator perms and this will be granted regardless of if they are playing or idling.
> 
> The max value should be like 30 and ot should only be rewarded if any amount of tickets were resolved in a round.

Oh I didnt know the modifier was that severe. 

The playtime modifier codedoc says its 4 every 10 minutes. Thats +24 every hour played alive and +20 if escaping onto centcom. About equal to two or 3 rounds of play. 

A bit too high. I lowered it.

2024-12-10 15:50 UTC, Geatish commented
Do mods get anything? 👉👈

2024-12-12 20:49 UTC, PowerfulBacon commented
I don't think that admins should be able to get points this way since it is a method of obtaining beecoins inaccessible to regular players. It would be very unfair if an admin even came close to being top of the beecoin leaderboard (since nobody actually uses them for buying things anyway) and admins already get donator rewards

2024-12-12 21:17 UTC, Tsar-Salat commented
This doesn't reference a thing I said.



> It would be very unfair if an admin even came close to being top of the beecoin leaderboard

You're worried about the optics of obscure leaderboards when those with DB access set their beecoin amounts to funny numbers to get a laugh when you check their playerinfo?

*No one* is getting big dick energy from an arbitrary number on a leaderboard. I feel like 2 people did not read the PR body now.


> (since nobody actually uses them for buying things anyway)

...No one uses the coins that are meant to be used for buying stuff in the bee shop... At all?

I don't know how to engage with that. Why else would I care about the silly DB number at all????



> admins already get donator rewards

I'm going to assume you mean the 10 meme items in the beecoin shop, and not the "rewards" of admins not having to worry about being kicked out when they join the server past popcap when joining to answer a ticket.



So, what I got from this is that my rationale is either not being engaged or it's thought that I'm misleading you because I want to get to the top of a leaderboard?

If either is the case then I would prefer this just be full closed rather than waiting months for more keys to come. If those with DB access don't like this then it's not going anywhere. If there's a better solution or the number is too high or anything I am always willing the change it. This was just the simplest I dea I could think of.

I honest to God just wanted to try out the new colorizers that got added in the last 2 years.

2024-12-12 21:33 UTC, Tsar-Salat commented
Please I really am hoping you are amicable to working this out. This isn't an ideal solution, but I think my reason for this is solid.

If you have an idea on how I can improve this please patch me in. 

Im not looking for reward as an admin, or for contributing my time. 
I want to see this place thrive and I would not put my self interest in front of that, I've talked with other admins and I thought adding the end of round ghost to try and meet around the value that players got was a reasonable idea.

2024-12-13 08:32 UTC, PowerfulBacon commented
I don't necessarily disagree with the stated points in the PR body, but I have my own thoughts that I don't think we're covered.

Players not being able to access it can be kind of resolved by calling the bonus to only applying if you are under 10k coins.

The bigger issue is determining what the player is actually doing. If they don't actually answer tickets, they shouldn't get coins. If they play the game at any point, they shouldn't get bonus coins even if they ghost. If implemented then I could see bugs being reported when an admin didn't get coins after spawning themselves in, but if not implemented it will be abused accidentally by just getting coins without playing the game.

I don't personally think that spending a round adminning should be comparable to actually playing the round in terms of playtime rewards, since it's not playing.

2025-02-25 23:21 UTC, Tsar-Salat commented
This is going to sit for another few months doing nothing, so I'll skip to the end

2025-02-25 23:21 UTC, closed without merging