Adds a multicolor Alphabet decal
BeeStation/BeeStation-Hornet pull request #12007
Opened 2024-12-09 01:18 UTC by BarteG44

## About The Pull Request
Adds a multicolor Alphabet decal for mappers.
I pretty much brute forced this, because i don't have an idea how to edit the decal code to allow for nudging them.
There exists a separate decal that does numbers but it has very inconsistent sprites and uses the dir to select the number, which breaks with any rotation. The new ones actually work somewhat well on shuttles.

## Why It's Good For The Game
more decoration options for the ambitious mappers

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
(decals don't work with pixel shifting so all of these are done with dirs)

![image](https://github.com/user-attachments/assets/f88ddae0-4b97-4e88-8dd2-6489569adac3)
![image](https://github.com/user-attachments/assets/5250e2e4-58aa-4d17-b9ed-99cc7a950ca5)
![image](https://github.com/user-attachments/assets/d04bcc18-3920-4c9e-a404-50a96ad4ee5e)

</details>

## Changelog
:cl:
add: Added new Alphabet decals for mapping
/:cl:

2024-12-09 09:06 UTC, PowerfulBacon commented
These look great

2024-12-09 21:53 UTC, PowerfulBacon approved these changes

2024-12-09 21:54 UTC, PowerfulBacon requested changes
Can you rename the paths to /letter_a instead of /A, to fit inline with naming conventions for types

2024-12-10 00:39 UTC, BarteG44 commented
> Can you rename the paths to /letter_a instead of /A, to fit inline with naming conventions for types

done

2024-12-10 07:44 UTC, PowerfulBacon approved these changes

2024-12-10 07:52 UTC, merged