Fixes reagent grinder juicing. Again.
BeeStation/BeeStation-Hornet pull request #12034
Opened 2024-12-14 12:30 UTC by XeonMations

## About The Pull Request

Turns out juice_typepaths were all lists instead of the proper datums they were supposed to be after https://github.com/BeeStation/BeeStation-Hornet/pull/11994. Oops. This fixes that.

Fixes https://github.com/BeeStation/BeeStation-Hornet/issues/12028

## Why It's Good For The Game

You should be able to juice a banana.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/user-attachments/assets/5ba11276-e586-4a9c-9c2c-405c1020b955

</details>

## Changelog
:cl: XeonMations
fix: You can now juice things once more in a reagent grinder.
/:cl:

2024-12-14 23:48 UTC, Tsar-Salat requested changes
This is the third pr.

This needs to be unit tested, seeing as this has been merged two times already testing evidence kinda isnt enough.

This PR should include a unit test for processing an input into an output for grinders, testing that the grinder:
1. Accepts the item(vegetable or fruit, whichever example grown food you want to use)
2. Activates when used
3. The output reagent, x, is between a minimum and maximum number

2024-12-15 11:44 UTC, XeonMations commented
FUCK I FORGOT TO UNDO THE COMPILE OPTIONS

2024-12-16 02:27 UTC, Fronsis commented
I was about to make a new issue but then i saw #12028 My issue was with putting watermelon slices and juicing it didn't return any watermelon juice just some reagents like water and nutriment, i assume this solves it?

2024-12-27 19:47 UTC, Tsar-Salat approved these changes
Looks fine

2024-12-29 20:16 UTC, Liver-1 commented
@XeonMations I am now unable to juice berries, I put the berries in the grinder and press juice, and get nothing.
![image](https://github.com/user-attachments/assets/f78ff3ee-0cef-4fbe-8f29-dc1eebc848c2)

2024-12-29 20:20 UTC, Liver-1 commented
@XeonMations YOU DID THIS
![image](https://github.com/user-attachments/assets/51d2a3ab-81b8-4e39-8b89-307bd084c6d2)

2025-01-13 00:35 UTC, merged