Bunched Station
BeeStation/BeeStation-Hornet pull request #12030
Opened 2024-12-14 00:55 UTC by BarteG44

## About The Pull Request

Bunched Station (WIP name) is a station based around 4 central corridors running in cardinal directions. Despite being about as large as Fland station in footprint, it's departments are placed and laid out is such a way as to ensure player interaction.

Design principles:
-High traffic areas such as security, bridge, and medbay are all located at the ends of the corridors, forcing traffic to go trough the service-oriented center.
-Most rooms directly connected to the corridors also have plentiful windows facing them with optional shutters or curtains. This is done to allow anyone from the corridor to see and talk directly to people who may be busy in their workplace, who would usually be tucked away somewhere far from sight. The shutters are there to permit some privacy to the people working, while their prevalence will make it less likely for anyone to suspect them of shady business if they do choose to close their department off. It's not suspicious if everyone's doing it.
-Greenery is present in most places. Just like in real life, having some plants around makes the whole space more pleasant to look at.
-More gimmick areas such as an actual Theater, Barbershop (WIP), decently sized office and a maintenance night club
<br>
<br>
<br>
I'll be adding more pictures and reasons for how and why i designed stuff the way i did tomorrow as it's currently 1:40 am 
## Why It's Good For The Game

Box, Meta, and delta are pretty much just different flavors of the same thing, people hate kilo for some reason and people hate corg for good reason. That leaves 3 maps that at least I personally would consider good, 2 of which are exclusive to diametrically different player counts. We could really use something more unique.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![StrongDMM-2024-12-14 01 30 26](https://github.com/user-attachments/assets/c319173b-0905-4e11-9825-ba19af3f1620)

![image](https://github.com/user-attachments/assets/564c4c39-1dd9-4c56-b6bb-b1bcc283b6c6)

![image](https://github.com/user-attachments/assets/3df1fd0a-6ef9-4a97-92e5-192c97beeb5c)

![image](https://github.com/user-attachments/assets/95320c7b-e11a-4fc4-977b-16ce346ed16a)

</details>

## Changelog
:cl:
add: Added bunched station and all of it's shuttles
add: Added big potted plants
add: Added sub divided big engines for shuttles
fix: fixed decals not working on circuit and grass floor tiles
/:cl:

2024-12-14 10:32 UTC, PestoVerde322 commented
![image](https://github.com/user-attachments/assets/76b26ef1-cd39-4396-9683-e5187c4acaf5)
Wrong naming standard, stick to the just naming the station file as just BunchedStation, otherwise you get stuff like this, aside confusion and whatnot
![image](https://github.com/user-attachments/assets/0bb42662-5ae9-4dac-8448-3e63396cd161)

2024-12-14 11:36 UTC, DatFrostys commented
The chapel's carpets are purple. Good map already.

2024-12-14 13:34 UTC, BarteG44 commented
> ![image](https://private-user-images.githubusercontent.com/75247747/395772804-76b26ef1-cd39-4396-9683-e5187c4acaf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNzI2NDMsIm5iZiI6MTczNDE3MjM0MywicGF0aCI6Ii83NTI0Nzc0Ny8zOTU3NzI4MDQtNzZiMjZlZjEtY2QzOS00Mzk2LTk2ODMtZTUxODdjNGFjYWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDEwMzIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YWQ3YThhZGJlMzRkMjFjNTE3YTc4YTRkYzJkN2ZiYjdjNDUwOWM2ODBmNzc4NGY4ZGY2Y2FlZTk5YzBjYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W2JrDAkOe0E_Pq_HL8X3y4IbuVzrfR_g-3Q7W5SjAj4) Wrong naming standard, stick to the just naming the station file as just BunchedStation, otherwise you get stuff like this, aside confusion and whatnot ![image](https://private-user-images.githubusercontent.com/75247747/395772884-0bb42662-5ae9-4dac-8448-3e63396cd161.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNzI2NDMsIm5iZiI6MTczNDE3MjM0MywicGF0aCI6Ii83NTI0Nzc0Ny8zOTU3NzI4ODQtMGJiNDI2NjItNWFlOS00ZGFjLTg0NDgtM2U2MzM5NmNkMTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDEwMzIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3YzZhMDEyMzkyNTU5MDI1YWM3MzkwOWQwYjYyZTA4MjE1MWJmM2RjYzYwYjkwODRkMWNlY2FhMzhlOTQ5ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VQxhRR00PNseSb3J_sAYu1Pq05IfPUWU7bxloZAnliM)

these are placeholder since as i've said, the name is WIP

2024-12-15 01:43 UTC, BarteG44 commented
ough...

2024-12-15 19:17 UTC, ClownMoff commented
I still think this is a gigantic station for our small pop but who knows

2024-12-20 08:58 UTC, AliveArrival commented
You could call it Cardinal Station!
Or just Card Station

Some other options:
Cross Station
Causeway Station
Devil station (It's at the crossroads)
Chatter Station
Walk Station

Bunched station seems very hard to say and even just thinking it it doesn't flow great.

2024-12-20 23:04 UTC, BarteG44 commented
i'm a fan of cardinal station and causeway station ngl

2024-12-21 00:49 UTC, MarkusLarsson421 commented
I can not stress enough how much I love everything about this!

2024-12-25 23:19 UTC, MrFish100 commented
Another station with an irregular toxins layout...  Please reconsider.

2024-12-25 23:43 UTC, BarteG44 commented
Please be specific when talking about things you don't like and want to see changed. This response tells me nothing

2024-12-26 11:56 UTC, MrFish100 commented
Sent the full description in discord. Sorry for not explaining it further here, my bad.

2025-01-02 13:48 UTC, BarteG44 commented
> You could call it Cardinal Station! Or just Card Station
> 
> Some other options: Cross Station Causeway Station Devil station (It's at the crossroads) Chatter Station Walk Station
> 
> Bunched station seems very hard to say and even just thinking it it doesn't flow great.

The deed has been done. Cardinal Station it is

2025-01-02 13:49 UTC, ClownMoff requested changes, later dismissed
My thoughts on some of the code

2025-01-02 13:49 UTC, ClownMoff commented on _maps/bunchedstation.json
> +	"map_name": "Bunched Station",
Is this the final name of the station? Maybe you could take a name from here that hasn't been used.

https://en.wikipedia.org/wiki/NATO_phonetic_alphabet

2025-01-02 13:49 UTC, ClownMoff commented on code/datums/shuttles.dm
> +	description = "Bazinga."
Give it an actual description that makes sense IC

2025-01-02 13:49 UTC, ClownMoff commented on config/maps.txt
> +	minplayers 20
```suggestion
	minplayers 40
```


Bump this to at least the same amount of players required for Fland. This is a huge station and it is unrealistic to think that this map will play well with 20 people. I don't think it will play well with 30 either but 20 is just straight wrong. If the map gets voted with 25 people, 5 leave, 20 come in the round, 2 people go mining and 2 exploring you end up with 16 people in a station that should be for +40 people **on station**

2025-01-02 13:53 UTC, BarteG44 commented on _maps/bunchedstation.json
> +	"map_name": "Bunched Station",
see comment above

2025-01-02 13:53 UTC, BarteG44 commented on code/datums/shuttles.dm
> +	description = "Bazinga."
yep, placeholder. I'll have something here by the evening

2025-01-02 13:55 UTC, BarteG44 commented on config/maps.txt
> +	minplayers 20
again, as bacon said, it's not just the footprint of the map that matters. We'll have to see how it actually plays in game. If it does feel too empty then i'm fine with increasing it

2025-01-02 14:04 UTC, ClownMoff commented
Onto the map itself.

<details>
<summary>Map review</summary>

![image](https://github.com/user-attachments/assets/ec4e2595-5166-44f6-9aaa-f38e24f246b5)

This looks a lot like the one in DeltaStation. That one is not avaiable to everyone. Is this one public? It certainly gives engi-only access but there's an assistant spawn on it

![image](https://github.com/user-attachments/assets/9498ea93-d89c-4de0-9090-2506f69719d0)

Too cramped

![image](https://github.com/user-attachments/assets/05018c7d-9618-4d4f-a5f5-89aadd4a4cee)

Shock those windows if they aren't already.

![image](https://github.com/user-attachments/assets/61ca2d52-f8cb-4be1-9dfe-a5fa7529349d)

The doble airlock needs some resprite, it looks too out of touch with the rest of the artstyle to use it this much on a map

![image](https://github.com/user-attachments/assets/9033e25c-013a-48ca-b422-21256d915a5a)

Put windows here or see-through doors. Cryo pods should never be hidden anywhere and easily accessible for everyone without having to open tons of doors to find them

![image](https://github.com/user-attachments/assets/3aa02390-02a3-4288-a2bb-88931b28c098)

Is this the security medbay outpost?

![image](https://github.com/user-attachments/assets/135a53ef-3e52-45b1-9e17-c133f969b54f)

A second bar/stripclub is a nice touch but having plasma tables unguarded means people can just go there and get free plasma roundstart

![image](https://github.com/user-attachments/assets/738c0b27-1edd-4467-8ce7-f3430b227d49)

Decor-wise doesn't make much sense to have this part open to go through, I'd do a full circle of raillings

![image](https://github.com/user-attachments/assets/64dc5fcd-4c78-4b45-a837-5ceec2e9f096)

Double doors look pretty bad, either put a window or make a new blue double airlock for command.
</details>

I do think this is a pretty station with tons of good ideas and well executed, but what I really fear is how insanely big is for a server that celebrates hits 60 pop a couple times a year

2025-01-02 14:19 UTC, ClownMoff commented on config/maps.txt
> +	minplayers 20
Bacon is straight wrong on that, both matter. This map can feel amazing but if I'm alone wandering in hallways 6 tiles wide by myself and I see some assistant from time to time the map will fail as a lowpop map. Echo can get away with this because everything is cramped together, Delta puts 40 people minimun, same with Fland. Box can get away with being a big map for lowpop since the majority of the action happens on the same hallway (this map has those points of interest/actions either in smaller size or more separated between them so it wont get the same Box effect). 20 pop is a bad pop to put on a map this big and I think the grand majority of mappers would agree and suggest, at minimun, 25-30.

2025-01-02 14:21 UTC, BarteG44 commented on _maps/bunchedstation.json
> +	"map_name": "Bunched Station",
(forgor to push commit)

2025-01-02 14:47 UTC, BarteG44 commented
> Onto the map itself.

1. yeah, it's restricted. good catch on the trapped assistant spawn.
2. it's intentional
3. it being a place to yoink a chem dispenser is also intentional but making it more secure sounds fine
4. I really don't see this. They're as outdated as all the other airlocks
5. I don't think this is that big of an issue. I can sprite a cryopod sign maybe though. Also most of the time when an antag gets caught and ragequits, they don't bother going into cryo anyways.
6. yes.
7. Plasma isn't that secure anyways. You can find it in maintenance and probably get it from cargo if you just asked. I haven't seen anyone do a plasma bombing either in my long time on this server so even if they do start stealing it, i see it as a positive.
8. it's not meant to be traversed, more like to be approachable. Similar idea to like a park. you can walk trough it, but it's not as easy as the road next to it.
9. double doors get used a lot on maps. I honestly think they look fine

2025-01-02 15:51 UTC, ClownMoff commented
> * I really don't see this. They're as outdated as all the other airlocks

![image](https://github.com/user-attachments/assets/1c8abc9b-7bc8-48c6-aad5-6d7e8cb7fe7d)

![image](https://github.com/user-attachments/assets/2c2f9e13-7ebd-4620-a73e-998d5549e2c4)

Different shading, doble one looks definitely older and worse. A resprite should be easy enough


> 8\. it's not meant to be traversed, more like to be approachable. Similar idea to like a park. you can walk trough it, but it's not as easy as the road next to it.

I would relocate the trees then, the opening says "walk through me" and the tree in the way says "don't walk through me"


> 5\. I don't think this is that big of an issue. I can sprite a cryopod sign maybe though. Also most of the time when an antag gets caught and ragequits, they don't bother going into cryo anyways.

You should not do design choices around people breaking the rules, that's what admins are for. You should always have the option to leave the game easily located

> 9\. double doors get used a lot on maps. I honestly think they look fine
Wouldn't  a command doble door look better? ;))

Also, your changelog is wrong. it should be like this

2025-01-02 18:39 UTC, BarteG44 commented
the changelog doesn't need that... it gets credited automatically to the author.

2025-01-06 14:55 UTC, spockye commented
a lot of creative and good mapping here, 
amazing work! 
would like to see this tm'd at a later date to see how it plays out.

2025-01-07 16:41 UTC, BarteG44 commented
i'm working on a feature to make the SM ejection a bit less a "get out of jail free card" but it requires me to learn TGUI so it's gonna be a while

2025-01-13 06:15 UTC, CRISOOOOO commented
Hey, do you have a discord? I would like to talk with you about something

2025-01-13 07:22 UTC, BarteG44 commented
> Hey, do you have a discord? I would like to talk with you about something

@barteg_

2025-01-22 22:50 UTC, Therealdoooc213 commented
Please remove the omnilathe from the bridge. Also, the armory seems to have no button for its shutters.

2025-01-22 22:51 UTC, SergeiKoralev commented
Live Test results from an atmos tech
- Double airlocks in arrivals are nice, but difficult to block when there is a breach or fire. Not an issue, just a note. 
- Arrivals shuttle is pretty neat!
- The below pictured valve is blocked from view by the other scrubber pipe.
![image](https://github.com/user-attachments/assets/e7ce0442-1ffa-40a0-86f8-2a57d66ea91d)
- There is a gas meter next to the plasma tank console that isn't connected to anything
- Turbine gas pumps are backwards.
- Tcomms should have an airlock style door configuration between equipment and the operations desk.
- the air alarm in tcomms causes an alarm
- As an engineer, regarding wires, fuck you. Politely, though.
- I feel like the engi sec and atmos offices could be swapped and it'd feel a bit more natural.
- the tiny fans were doing weird stuff and didn't appear to be where they should have been. I saw at least two in walls, including one at the engi escape pod.
- the little engineering storage pod has an air alarm that causes a round-start alarm.
- the supermatter airlock on the right side of SM is configured incorrectly and does not cycle.
- Mixed air supply tank has no gas sensor in it
- don't run pipes and wires over glass
- Add space heaters in atmos
- escape via pod marooned me
- There are a lot of carp.

2025-01-23 00:01 UTC, SergeiKoralev commented
Paramedic round 
- There are SO MANY bodies in the morgue. 
- the science lobby maint door has science access restriction

2025-01-23 00:05 UTC, Bagietens commented
Toxin's southern chamber cannot be opened. When I click to open it, it says pressurising indefinitely

2025-01-23 00:24 UTC, BarteG44 commented
> Live Test results from an atmos tech
> 
>     * Double airlocks in arrivals are nice, but difficult to block when there is a breach or fire. Not an issue, just a note.
> 
>     * Arrivals shuttle is pretty neat!
> 
>     * The below pictured valve is blocked from view by the other scrubber pipe.
>       ![image](https://private-user-images.githubusercontent.com/43328793/405792670-e7ce0442-1ffa-40a0-86f8-2a57d66ea91d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1ODg3MzIsIm5iZiI6MTczNzU4ODQzMiwicGF0aCI6Ii80MzMyODc5My80MDU3OTI2NzAtZTdjZTA0NDItMWZmYS00MGEwLTg2ZjgtMmE1N2Q2NmVhOTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIyVDIzMjcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYWNhYzc1M2E2MGVlNjhmN2NjOWVhNDMyZWZiODJmNzliMjdhOGUzNDJiNmFjNTFmM2MxMjgwZmNmZWIyOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LxkshEfs68w5rynl8I0_paSXg2chSroCdU1Jb2hniBc)
> 
>     * There is a gas meter next to the plasma tank console that isn't connected to anything
> 
>     * Turbine gas pumps are backwards.
> 
>     * Tcomms should have an airlock style door configuration between equipment and the operations desk.
> 
>     * the air alarm in tcomms causes an alarm
> 
>     * As an engineer, regarding wires, fuck you. Politely, though.
> 
>     * I feel like the engi sec and atmos offices could be swapped and it'd feel a bit more natural.
> 
>     * the tiny fans were doing weird stuff and didn't appear to be where they should have been. I saw at least two in walls, including one at the engi escape pod.
> 
>     * the little engineering storage pod has an air alarm that causes a round-start alarm.
> 
>     * the supermatter airlock on the right side of SM is configured incorrectly and does not cycle.
> 
>     * Mixed air supply tank has no gas sensor in it
> 
>     * don't run pipes and wires over glass
> 
>     * Add space heaters in atmos
> 
>     * escape via pod marooned me
> 
>     * There are a lot of carp.
> 
>     * Adding more exterior airlocks would be nice.

2025-01-23 00:24 UTC, XeonMations commented
my only complaint from the 2nd TM round: There are not enough portable tank injectors in engineering (the blue machines used to fill up canisters to 2553kpa, i forgot what they're called). I had only found one that round

2025-01-23 00:25 UTC, BarteG44 commented
gas pumps

2025-01-23 00:29 UTC, Ragantis commented
Lights in the areas with grass in them were broken round start, unable to be replaced.  Not a big issue and can be fixed using the BSLR later in game or removal of the directional windows if you cared enough about it.

2025-01-23 00:34 UTC, BarteG44 commented
> The below pictured valve is blocked from view by the other scrubber pipe.

The entirety of atmos will need to be redone once linda gets merged but fixed
> There is a gas meter next to the plasma tank console that isn't connected to anything

removed
> Turbine gas pumps are backwards.

embarrassing, fixed
> As an engineer, regarding wires, fuck you. Politely, though.

By an engi main for an engi main
> the tiny fans were doing weird stuff and didn't appear to be where they should have been. I saw at least two in walls, including one at the engi escape pod.

those aren't actually tiny fans, just a fluff object that also appears on the pirate ship

> the little engineering storage pod has an air alarm that causes a round-start alarm.

alarm begone
> the supermatter airlock on the right side of SM is configured incorrectly and does not cycle.

fixed
> Mixed air supply tank has no gas sensor in it

added
> don't run pipes and wires over glass

if you mean the glass tiles next to the medical booth, that was done by a plaer

> Add space heaters in atmos

added 3
> There are a lot of carp.

Adjusted

2025-01-24 18:26 UTC, BarteG44 commented
every single map fails tests. what the fuck did i do

2025-01-29 17:26 UTC, Tsar-Salat commented on config/maps.txt
> +	minplayers 20
> Bump this to at least the same amount of players required for Fland.

This wasn't even tested at this point.

2025-01-29 22:44 UTC, mrmanlikesbt commented
The AI Core needs a total rework. Aside from being just really.. not secure, the turrets can shoot the AI, you can tear down the top 3 reinforced walls and break the APC without any turrets being able to hit you (and you get a clear shot on the AI). Also, just a nitpick, but the satellite should be much larger considering this is a massive station.

https://github.com/user-attachments/assets/74392aa5-7388-4f7b-93ec-8afa79e2dac1

2025-01-30 20:46 UTC, BarteG44 commented
altered the AI core a bit. Gotta see next TM if it's better

2025-02-06 19:56 UTC, XeonMations commented
![image](https://github.com/user-attachments/assets/e1cea9f2-6697-4e5e-89d8-920f7ea7b9e9)

This looks like something is supposed to be here.

![image](https://github.com/user-attachments/assets/aea5d681-0712-4a20-9864-462773d3c816)

Probably a good idea to add in a door in the armory that goes to the evidence, instead of having to loop back around.

2025-02-06 20:01 UTC, BarteG44 commented
> This looks like something is supposed to be here.

![obraz](https://github.com/user-attachments/assets/614b31b0-9271-4bc5-8180-4a31bc2b8122)

these thingamabobs. Idk what they do exactly but they're on all stations. I think they spawn additional sec lockers when you have roundstart officers

2025-02-13 20:38 UTC, BarteG44 commented
WHO

2025-02-19 22:46 UTC, Tsar-Salat requested changes, later dismissed
Add navigation markers and I will put it into TM again

2025-02-20 06:04 UTC, BarteG44 commented
> Add navigation markers and I will put it into TM again

what do you mean by "navigation markers"? 
the bot navigation beacons?
the department direction signs?
Because both of these have been there from the start

![image](https://github.com/user-attachments/assets/95b9310e-037a-4ad1-871c-fafdc309685c)
![image](https://github.com/user-attachments/assets/964748a7-c691-4e84-8c1d-9b57ebd9cf04)
![image](https://github.com/user-attachments/assets/d6a4c6ca-e245-4a03-ab25-52f2974dd9dc)
![image](https://github.com/user-attachments/assets/a0e6ae93-5289-4b5c-a1cb-cabafd169a66)

2025-02-21 00:26 UTC, MarkusLarsson421 commented
I swear to God. (I love it kek)
The custom wonky wires would maaaaybe be a pain to work with in-game if for example a rat ate the wire or such. And smart wires may mess it up but I am not sure.
![image](https://github.com/user-attachments/assets/08a6ddc9-4010-4503-a2b4-338bdf4a74cf)

![image](https://github.com/user-attachments/assets/4c42ecbc-f850-4812-8c97-05f6d0a00272)

What's with the table frames in telecoms?
![image](https://github.com/user-attachments/assets/d9071a9b-4471-4f9a-b781-7244a1ffd12d)

Telecoms should maybe be connected to a plasma tank leading to cooled heat transfer pipes inside, but I am not sure if this is still required. Other maps still does it like Meta.

For some odd reason, these two doors by telecoms are entirely filled with cooled down nitrogen and activates the nearby alarm and moves items around once opened.

![image](https://github.com/user-attachments/assets/d489e211-8eac-4393-b2d1-3fee93ee002c)

![image](https://github.com/user-attachments/assets/8e882366-6f87-4e53-82f0-c9bd0da5ad5f)

![image](https://github.com/user-attachments/assets/9561fbf4-394d-47e6-ba0c-18b2c6e70a13)

Some sort of airlock would be nice for telecoms, it doesn't change much but should be used when the atmosphere of two areas are different, it does not require a cycle program though.

![image](https://github.com/user-attachments/assets/def4747c-1a20-46d1-b2de-8ba7d296066c)

I really like these colour coded buttons! Great idea.
![image](https://github.com/user-attachments/assets/01a2e13c-8e1b-4b86-9511-79d5d4f07394)

Random items on the ground?
![image](https://github.com/user-attachments/assets/69c39403-1bca-4de3-983d-5bb0e1bb2e65)

No disposals chute despite having a disposals pipe right next to it?
![image](https://github.com/user-attachments/assets/861c15a4-b5bc-4bb1-ab91-c1dac1ec1f3e)

![image](https://github.com/user-attachments/assets/a6e2e935-8ea2-44eb-81bf-af667f0d22f8)

Every plasma man on this server will appreciate this!
![image](https://github.com/user-attachments/assets/cb661e11-8390-443a-b67b-4be79a2e51ba)

Don't think we should encourage ideal setups for typical work of some jobs, better leave to blank or move the TEG here.
![image](https://github.com/user-attachments/assets/e99d7306-c1be-41dc-a152-7ff44d2721a6)

The money here can only be picked up by splitting it, but not clicking or using alternative clicking methods.
![image](https://github.com/user-attachments/assets/f6d6d051-fe5c-4bcc-88b5-2e34759a702d)

Buttons ideally shouldn't have access requirements, but it's fine if it is really needed.
![image](https://github.com/user-attachments/assets/0cb7782d-283e-4c31-a2a0-4c242ccbdfb6)

Fences on lattice looks... off.
![image](https://github.com/user-attachments/assets/0312a596-58f2-4e7c-9233-9bf631a39bbe)

Is it supposed to look like this? "Red scrubbers pipe"
![image](https://github.com/user-attachments/assets/a4eca15a-b5ae-4b66-b30e-cb30afc85bb2)

The SM to waste pipe goes outside and around until it connects to the waste pipe, why can't it just go up to the nearby scrubber?
![image](https://github.com/user-attachments/assets/f8765308-7b72-4716-9992-5f1ad03dd2f8)

Robotics gets a free brain unlike any other map. Might be a bit too much?
![image](https://github.com/user-attachments/assets/94b47ab6-8d6c-4251-aa62-4b1ff05c7e13)

Mirror over sink.
![image](https://github.com/user-attachments/assets/3841d7af-6b50-4011-8045-594304dde8c8)

Back door into a head of staff office, especially one so hidden, is kind of icky due to how much of a breeze nicking their traitor objective would be.
![image](https://github.com/user-attachments/assets/e2cf8bf1-fd5e-4908-a43e-f85e40eec85e)

Papers can not be destroyed through normal means, probably make a subtype of them which can be destroyed easily and burn like normal papers.
![image](https://github.com/user-attachments/assets/9261b64b-3b20-4815-a4f1-8a4c2cef30a6)

Lots of food, perfect for autism fort. Other departments also has a lot of free food.
![image](https://github.com/user-attachments/assets/a05b132e-3c86-44ec-b666-68c5614ede15)

No closing detection on the right side.
![image](https://github.com/user-attachments/assets/f6b45021-95be-4a14-bc60-d7183e3faca9)

pAI underneath paper stack.
![image](https://github.com/user-attachments/assets/97f11314-1f5b-4d19-9ca0-98e9c7904641)

Free laz for Xenobio?
![image](https://github.com/user-attachments/assets/a66af2ec-b97b-46b5-80e1-74d556d7f5c1)

lol champagne
![image](https://github.com/user-attachments/assets/2a3a68df-d5cd-4672-aee1-0266d49f851a)

I like how you can find binoculars here and there.
![image](https://github.com/user-attachments/assets/0c051d1b-f2e3-4f6d-86aa-c3a54f972dbe)

No cycling system. Cycling systems were apparently removed by Linda... <.<
![image](https://github.com/user-attachments/assets/eae28f30-0c09-42d7-8dae-b71f515b3a9c)

Exploration doors to their shuttle should be locked to their access code so no assassination target can just waltz in and nick their shuttle.
Same with the back shutters, but there you could maybe just remove the exterior button.
![image](https://github.com/user-attachments/assets/3015a134-7831-415d-8017-344df004d042)

55 plasma is a tad overkill for starting materials for the Explorers. lol
10 or so is plenty.
![image](https://github.com/user-attachments/assets/d5514afa-5798-46cb-b5fe-c80876b37041)

Odd portal placement.
![image](https://github.com/user-attachments/assets/e97e6118-eb3f-4079-8064-dbb55509d743)

A tad tight for three Shaft Miners to gear up on round-start.
![image](https://github.com/user-attachments/assets/19ee8767-e16a-421e-abfd-85351d0951fd)

Shield off VS. on. Don't think there is much of a fix for this, but it might be worth noting. Other shields has similar quirks to them.
![image](https://github.com/user-attachments/assets/2e9a024f-9ad0-423f-bf7a-e7098898306e)

![image](https://github.com/user-attachments/assets/274e2e6a-1ed3-4379-a7ff-051cd0b882b2)

Posters on windows in Medbay maintenance.
![image](https://github.com/user-attachments/assets/2fabf086-29c0-4223-b1d2-5da7dec5184b)

Difficult for Cyborgs to get a brain or body into the machine with the drawer in the way.
![image](https://github.com/user-attachments/assets/2faf99e4-2e11-451f-9726-56cdd17ea8c3)

Remove the one-way free access in the examination room to allow psychologists to trap their victims.
![image](https://github.com/user-attachments/assets/8529a019-e628-4411-95ba-b7fb41aa32e2)

Free guaranteed gondola, could cause folks to be turned into gondolas.
![image](https://github.com/user-attachments/assets/b5f6c375-40b5-4145-ac45-9660bfdcbc7c)

Awful locker area for when you're two or more officers on duty on round-start. Imagine if you're SIX officers.
![image](https://github.com/user-attachments/assets/a9004023-b9d9-443c-9e88-d690dd062ab2)

I'd add some more maintenance loot spawners to give prisoners a very small chance of getting something they can make use of, assuming a capable warden or such don't clean it all out.

No photobooth at the HoP line.

HoP lacking a keycard auth button.

Difficulty turning these on as they hide behind the shutters, requiring alternative clicking methods to turn it on without setting off the alarms.
![image](https://github.com/user-attachments/assets/50c52fc3-e6e4-4793-bfdb-40f906fcfe25)

Absolutely zero protection from ranged laser once the first shutter is destroyed.
![image](https://github.com/user-attachments/assets/ba046d98-ce59-4917-92e8-8f48b41cf919)

Very little privacy for the psychologist to do their terrible RP.
![image](https://github.com/user-attachments/assets/2ff960ab-851b-46c8-b162-094c17b4902d)

Maybe a camera to over view any future project regarding the gravity / tesla location? 
![image](https://github.com/user-attachments/assets/6520aefd-7291-4f9c-9046-db0b6cdb41d1)

Who would win? A black hole or a funny perfect asteroid?
![image](https://github.com/user-attachments/assets/fbcc2ffc-340b-44c2-9b25-c2032a858870)

Shooting trash at the AI sat. lmao
![image](https [...]

2025-02-21 00:33 UTC, MarkusLarsson421 commented on _maps/_basemap.dm
> +#define FORCE_MAP "cardstation"
This should be commented out prior to merge, right? Just a reminder.

2025-02-21 12:42 UTC, BarteG44 commented on _maps/_basemap.dm
> +#define FORCE_MAP "cardstation"
Yes, it's forced for the duration of the TMs

2025-02-21 15:05 UTC, BarteG44 commented
> I swear to God. (I love it kek) The custom wonky wires would maaaaybe be a pain to work with in-game if for example a rat ate the wire or such. And smart wires may mess it up but I am not sure. 

i've had people complain about and praise funky wires in about similar numbers, so they're gonna stay up until smart wires send them off into the sunset

> What's with the table frames in telecoms? 

greebles

> Telecoms should maybe be connected to a plasma tank leading to cooled heat transfer pipes inside, but I am not sure if this is still required. Other maps still does it like Meta.

Both work. All that matters is that the room stays cold

> For some odd reason, these two doors by telecoms are entirely filled with cooled down nitrogen and activates the nearby alarm and moves items around once opened.

fixed

> Some sort of airlock would be nice for telecoms, it doesn't change much but should be used when the atmosphere of two areas are different, it does not require a cycle program though.

i do want one of these in there but space becomes an issue. it will require a complete rework of the room, which i may do honestly

> Random items on the ground? 

apparently i got distracted with something else half way trough reorganizing CE's office. Fixed

> No disposals chute despite having a disposals pipe right next to it? 

there is a chute a few tiles away from both of these

> Don't think we should encourage ideal setups for typical work of some jobs, better leave to blank or move the TEG here. 

as an atmos main i wouldn't consider this one ideal, though if it becomes an issue, i can make it half ruined on round start or replace it with something else entirely

> The money here can only be picked up by splitting it, but not clicking or using alternative clicking methods. 

These are a trick i learned from spocky to simulate multi-z depth. The cash is anchored on purpose since it would be unreachable if it were down a hole. Jank? maybe, but the sovl outweighs it imo

> Buttons ideally shouldn't have access requirements, but it's fine if it is really needed. 

buttons having access requirements is a very common thing on all maps. i really have no idea where this is coming from

> Fences on lattice looks... off. 

fair enough. I'll see if it can be salvaged still

> Is it supposed to look like this? "Red scrubbers pipe" 

Yes because linda is dumb (in the editor)

> The SM to waste pipe goes outside and around until it connects to the waste pipe, why can't it just go up to the nearby scrubber? 

Intentional sovl choice

> Robotics gets a free brain unlike any other map. Might be a bit too much?

It gives robotics something to do at the start of the round and allows for a cyborg latejoin, which are normally impossible for at least a 1/3rd of the round. If maintainers think it's too much then sure, i'll get rid of it

> Mirror over sink. 

that's how it's done on all maps with a north facing sink. not much i can do about it either

> Back door into a head of staff office, especially one so hidden, is kind of icky due to how much of a breeze nicking their traitor objective would be. 

this is also common on other maps. I suppose i can make those doors higher security but i really don't believe it's such a big deal

> Papers can not be destroyed through normal means, probably make a subtype of them which can be destroyed easily and burn like normal papers. 

they can be destroyed, though they do have a lot of integrity. I'll see what i can do

> Lots of food, perfect for autism fort. Other departments also has a lot of free food. 

i'll cut some of it i suppose

> No closing detection on the right side. 

'tis the price of sovl

> pAI underneath paper stack.

fixed

> Free laz for Xenobio?

i'll let maintainers decide

> lol champagne 

can't fix this without editing the layer var (which is forbidden by linters) or without making a whole subtype of bottle/window just for this one specific circumstance 

> No cycling system. Cycling systems were apparently removed by Linda... <.< 

yet another Linda L

> Exploration doors to their shuttle should be locked to their access code so no assassination target can just waltz in and nick their shuttle. Same with the back shutters, but there you could maybe just remove the exterior button.

no access restrictions on shuttle airlocks is a mapping standard it seems. no idea if it's intentional or not but for now i'd rather keep it consistent with all the other shuttles

> 55 plasma is a tad overkill for starting materials for the Explorers. lol 10 or so is plenty. 

55 is the standard on all explo shuttles

> Odd portal placement. 

unfortunate but it's the only logical spot i can fit a gateway and it just looks best that way

> A tad tight for three Shaft Miners to gear up on round-start. 

they gear up there and then never use the room again for the whole shift so i don't think it's worth giving them more space

> Shield off VS. on. Don't think there is much of a fix for this, but it might be worth noting. Other shields has similar quirks to them. 

yeah these are just for flavor

> Posters on windows in Medbay maintenance. 

woe, random room gen be upon ye

> Difficult for Cyborgs to get a brain or body into the machine with the drawer in the way. 

replaced it with a wheeled version so they can just pull it away if need be

> Remove the one-way free access in the examination room to allow psychologists to trap their victims. 

why not

> Free guaranteed gondola, could cause folks to be turned into gondolas. 

they can spawn in maintenance rooms already. if a non antagonist abuses them, i'd say it falls under admin jurisdiction, though again, up to the maintainers

> Awful locker area for when you're two or more officers on duty on round-start. Imagine if you're SIX officers. 

clearly, you are not a lord of the locker room
 
> I'd add some more maintenance loot spawners to give prisoners a very small chance of getting something they can make use of, assuming a capable warden or such don't clean it all out.

> No photobooth at the HoP line.

waiting until it gets a sprite that would not be considered vandalism if placed in the hallway

> HoP lacking a keycard auth button.

they aren't

> Difficulty turning these on as they hide behind the shutters, requiring alternative clicking methods to turn it on without setting off the alarms.

they have a button. 
![image](https://github.com/user-attachments/assets/61f87d6a-19f7-4cfc-9524-5f1c32bb7f9d)
Gonna color it red so it's more noticeable i guess

> Absolutely zero protection from ranged laser once the first shutter is destroyed. 

replaced the shutter with a blast door so it's harder to get a straight line of sight

> Very little privacy for the psychologist to do their terrible RP. 

I actually made sure they have all the privacy possible. They have shutters and curtains, there is no camera in their office and the door has medbay access 

> Maybe a camera to over view any future project regarding the gravity / tesla location? 

there is one
![image](https://github.com/user-attachments/assets/c4644e06-d658-4f6f-8b18-2f9849df109a)

 
> Who would win? A black hole or a funny perfect asteroid? 

i call it an engineer perceptiveness test

> This is the only thing preventing an AI to turn on the incinerator alone for some easy emergency power. 

not sure if you're saying this is good or bad

> Xenobio Maintenance allows the Xenobio camera to go through it, allowing them to see things they shouldn't be able to. !

you blew up the wall and the camera is seeing trough the girder lol
 
> Why a conveyer belt? Feels a bit... needless?

purely for vibes. I am not going for a minimalist station after all

> These fences are gonna get really annoying I think. 

'tis the price of vibes

> Maintenance door should be under the maintenance area and the two other Exploration related doors should be powered by the Exploration room APC. 
> And these entrance doors should not be part of the mai [...]

2025-02-21 17:23 UTC, MarkusLarsson421 commented
> greebles

greebles?

> there is a chute a few tiles away from both of these

So why the double trash solutions?

> buttons having access requirements is a very common thing on all maps. i really have no idea where this is coming from

https://github.com/BeeStation/BeeStation-Hornet/pull/12032#issuecomment-2661323365

It's how I interpreted Bacon's comment. It's also silly, it's a button, not a console nor an ID scanner or anything else other than a button. Then again, no one will attack you for having these.

> It gives robotics something to do at the start of the round

Despite being a Roboticist main, I can never understand why people think Robotics has nothing to do.

> that's how it's done on all maps with a north facing sink. not much i can do about it either

It does happen, but when you can, fix it. Change the layer of the mirror to be below that of the sink. Sometimes it's as easy as placing the sink AFTER the mirror if they have the same layer.

> this is also common on other maps. I suppose i can make those doors higher security but i really don't believe it's such a big deal

Yes and no. Rad and Meta has it into their CMOs offices, but their lockers is easily visible from high traffic areas. Otherwise... Rarely do Heads of Staff have such paths.

> can't fix this without editing the layer var (which is forbidden by linters) or without making a whole subtype of bottle/window just for this one specific circumstance

Could also just place it elsewhere.

> no access restrictions on shuttle airlocks is a mapping standard it seems. no idea if it's intentional or not but for now i'd rather keep it consistent with all the other shuttles

Oh... right... I forgot. Well, it's stupid! :P

> 55 is the standard on all explo shuttles

BS. Corg gets 10, Rad gets 5, Fland gets 100 (for some reason), Kilo gets 40, Meta gets 5, Box gets 10, and Delta gets 55. I am including plasma in the Exploration prep rooms too.

> they can be destroyed, though they do have a lot of integrity. I'll see what i can do

I don't think anyone would cry if you changed their integrity to 1 or such.

> you blew up the wall and the camera is seeing trough the girder lol

Camera shouldn't be able to get in there in the first place.

> not sure if you're saying this is good or bad

I think all maps without exception allow an AI to turn on the turbine without any assistance, so I think it's bad that they can't do it here. In the event of no engineers or such, power will very quickly run out. This won't solve it, but it'll give the station time to fix it.

> they gear up there and then never use the room again for the whole shift so i don't think it's worth giving them more space

Could be worth making them part of a hallway, sort of what Meta has. If they're never used again you don't need to even dedicate a room to them unless you want to open up the possibility of storing items there discretely.

> yeah these are just for flavor

You could make them a subtype which can't be activated or moved to preserve the trick.

> woe, random room gen be upon ye

Look at "BeeStation-Hornet\_maps\Prefab\RandomMapHelper.dmm" to see where openings and walls go.

> waiting until it gets a sprite that would not be considered vandalism if placed in the hallway

kek

> they aren't

Fuck, thought I removed that line.

>replaced the shutter with a blast door so it's harder to get a straight line of sight

Still not a lot of protection, but it's something.

> there is one  

Oh, it was broken.

>i call it an engineer perceptiveness test

Based. kek

2025-02-21 18:25 UTC, BarteG44 commented
> greebles?

![image](https://github.com/user-attachments/assets/e742224a-2756-4f42-a364-64c29bde978c)

> So why the double trash solutions?

because i like how they look. also they don't flush automatically so you can hide junk in them



> It's how I interpreted Bacon's comment. It's also silly, it's a button, not a console nor an ID scanner or anything else other than a button. Then again, no one will attack you for having these.

pretty sure it's specifically about medbay lobby door buttons

> Despite being a Roboticist main, I can never understand why people think Robotics has nothing to do.

speaking from my own experience here. first 20-30 minutes is nothing and only after that you get materials and research for borg upgrades or mechs

> It does happen, but when you can, fix it. Change the layer of the mirror to be below that of the sink. Sometimes it's as easy as placing the sink AFTER the mirror if they have the same layer.

placing things in an order only works when they have the same base layer. Mirrors have a higher layer than most things by default. not to mention that i prefer this look

> BS. Corg gets 10, Rad gets 5, Fland gets 100 (for some reason), Kilo gets 40, Meta gets 5, Box gets 10, and Delta gets 55. I am including plasma in the Exploration prep rooms too.

well i referenced the delta and fland shuttles so i suppose this is a sample size issue. fair enough i guess, i'll cut the starting plasma. not like it's that hard to get anyhow

> I don't think anyone would cry if you changed their integrity to 1 or such.

it's 20 now, down from 300

> Camera shouldn't be able to get in there in the first place.

changed the area

> I think all maps without exception allow an AI to turn on the turbine without any assistance, so I think it's bad that they can't do it here. In the event of no engineers or such, power will very quickly run out. This won't solve it, but it'll give the station time to fix it.

not a fan of the AI being able to do an engineer's/atmos techs job all on it's own, but that doesn't even matter because you can bypass the bypass valve with the black pipe above it lol

> You could make them a subtype which can't be activated or moved to preserve the trick.

i don't really see the point for such a minor issue

> Look at "BeeStation-Hornet_maps\Prefab\RandomMapHelper.dmm" to see where openings and walls go.

yes, no wall is safe other than the center of each side. some bad posters are simply a tradeoff i'm willing to make for the look

2025-02-21 18:32 UTC, MarkusLarsson421 commented
> it's 20 now, down from 300

300!! SWEET JESUS!!

2025-02-21 18:34 UTC, BarteG44 commented
yeah, a reinforced window is 200

2025-02-22 12:48 UTC, BarteG44 commented
why the hell is the \<br> causing issues

2025-02-22 21:06 UTC, PowerfulBacon commented
![image](https://github.com/user-attachments/assets/18547113-7588-4a32-b33b-fb28653143e7)

Wires made like this will completely break when smartwires comes around as the auto-wire updater will only consider directly adjacent tiles.

Do not use any wire directions which are not directly connecting a cardinal (Dont use diagonal wires)

2025-02-22 21:13 UTC, BarteG44 commented
What is the ETA for smart wires?

2025-02-23 00:19 UTC, MarkusLarsson421 commented
> What is the ETA for smart wires?

From what I've heard... Soon:tm:. 
(Very soon.)

2025-02-23 00:36 UTC, BarteG44 commented
>i've had people complain about and praise funky wires in about similar numbers, so they're gonna stay up until smart wires send them off into the sunset

2025-02-23 00:53 UTC, MarkusLarsson421 commented
> If somehow card gets merged before this, ping me on discord when it's ready to merge and i will replace all the wires by hand in 3h tops and contribute it to the PR

Just do it now instead of later silly

2025-02-23 00:55 UTC, BarteG44 commented
I will not compromise on sovl

2025-03-08 13:44 UTC, BarteG44 commented
sound????

2025-03-10 17:22 UTC, BarteG44 commented
yeah sure whatever

2025-03-16 02:11 UTC, BarteG44 commented
This currently includes #12414 and #12358. They should be merged before this

2025-03-16 15:30 UTC, MarkusLarsson421 commented
There is an issue with one light bulb.

2025-03-16 16:04 UTC, BarteG44 commented
> There is an incorrectly placed light bulb.

![image](https://github.com/user-attachments/assets/f15b86ef-1b4d-4f70-894d-c2f7a43d0a37)

2025-03-16 17:35 UTC, MarkusLarsson421 commented
> ![image](https://private-user-images.githubusercontent.com/105491762/423229550-f15b86ef-1b4d-4f70-894d-c2f7a43d0a37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIxNDY4MzgsIm5iZiI6MTc0MjE0NjUzOCwicGF0aCI6Ii8xMDU0OTE3NjIvNDIzMjI5NTUwLWYxNWI4NmVmLTFiNGQtNGY3MC04OTRkLWMyZjdhNDNkMGEzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxNlQxNzM1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGMxY2FjYWIwMjZkOTM0Y2M5ZDRkYTBjMDBmYzk1ZjcwNDE1NzE3ZWYxYWYwNGUwYzIzMGZhMmYwOGQ3YWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pgwnusplr3VqBqL6ehx53d0T0c5-o8vlZ6n0HuSbD4k)

Not that one.

2025-03-17 21:39 UTC, BarteG44 commented
curse you

2025-03-17 22:16 UTC, BarteG44 commented
ough the whole thing exploded

2025-03-18 00:32 UTC, BarteG44 commented
god DAMMIT

2025-03-25 00:44 UTC, BarteG44 commented
100 merge conflict barrage

2025-03-27 06:09 UTC, BarteG44 commented
getting multiple conflicts a day an yet i never had to resolve anything to get rid of them

2025-03-29 11:17 UTC, BarteG44 commented
honey, it's time for your daily merge conflict

2025-03-30 14:12 UTC, BarteG44 commented
it's the damn changelog that conflicts???? how

2025-04-08 23:55 UTC, BarteG44 commented
why the hell do you pass checks

2025-04-15 06:08 UTC, MarkusLarsson421 commented
Approved!

2025-04-15 23:29 UTC, BarteG44 commented
I still hold out hope that the smart wire PR gets closed so that I can return card's wires to their past glory

2025-04-19 15:57 UTC, BarteG44 commented
the sound change label should be removed from this too

2025-04-20 16:34 UTC, BriggsIDP commented
This map has changed a lot since I last reviewed it, nice work! the comments are very helpful to get an insight into your thinking, we might have to make that a standard, though some are a little more fluff then others.
on to the review starting mostly from the top left of the station down:

<details>

![image](https://github.com/user-attachments/assets/c6438447-50ad-4065-8579-6a4f82529f0e)
this window is a little odd, you already have grass next to it, so i would just replace it with a normal tinted window.
![image](https://github.com/user-attachments/assets/83e50e1e-16aa-4d88-85bc-c7cb65559afe)
binos are kind of a exclusive item, unsure how i feel about them just being in the open considering how powerful they can be
![image](https://github.com/user-attachments/assets/dcecd51c-f787-4e66-8b0b-68b1a8df7787)
I would widen this by one tile or remove it entirely.
![image](https://github.com/user-attachments/assets/9e14381e-ccb6-441a-9b92-96f2ccf98587)
left get fake windows but right don't? :( I would replace these with real windows and use the directional curtains. also, you may be over using the wall lockers a little, the personal closet should be more then enough especially here
![image](https://github.com/user-attachments/assets/10c2079f-c3b9-47c6-8e88-0bd6a4ada2b1)
Like, do we really need 9 lockers here?
![image](https://github.com/user-attachments/assets/cbe2b90f-e0d2-4474-b8ab-91c1d4a70470)
plant too big :(
![image](https://github.com/user-attachments/assets/4391fc7a-712a-43c1-b5b4-bf2274eb47d2)
I think another mentor mentioned this being a bit too much and i tend to agree, keep it to two on a tile max!
![image](https://github.com/user-attachments/assets/24a640a3-4f90-4d51-8917-fede99f1df4a)
your choice on this one, but I think this looks cleaner. also no slip markers on tables in bridge.
![image](https://github.com/user-attachments/assets/816d446c-2a1b-40b5-9186-059d0ba6ab31)
![image](https://github.com/user-attachments/assets/f16b0366-2c71-4948-8707-98f927b5025a)
This is insane, it will make changing anything in this area super annoying and slow down map load more, make a new decal color type if you want this green, var edits are preferable to this even. decal to the left of the one in the image is var edited to "#20a85b"
![image](https://github.com/user-attachments/assets/3c496785-9b12-4daa-a701-4a7d952690fd)
I'd add a maint door here
![image](https://github.com/user-attachments/assets/c3079206-f258-4c78-924e-bad32dae415a)
maybe move this room here considering its the main way for players to get to space from this maints
![image](https://github.com/user-attachments/assets/4f7bb053-b6e0-4255-9a9a-23158e09dc6e)
cow jail has no door :(
![image](https://github.com/user-attachments/assets/4f065295-2ee6-4dd7-b6c4-2638b83e5723)
I would say these areas are big enough to warrant airlocks rather then just firedoors
![image](https://github.com/user-attachments/assets/65c10951-4563-4701-8485-92247478b169)
this sever room is kind of small, I would replace the random maint behind it with a smaller one and expand it's size
![image](https://github.com/user-attachments/assets/e75cf2fe-d97b-4886-bf47-cb1a2b7a1f9c)
could use a motion camera considering how exposed and easily assessable it is
![image](https://github.com/user-attachments/assets/cb8a5c17-7a7f-4d65-8ecb-0a08c731cb4a)
seems like a pain to get this out
![image](https://github.com/user-attachments/assets/10e48abf-0817-407e-9311-7ee5d7e0f6c1)
this is an odd room
![image](https://github.com/user-attachments/assets/25e701ea-86fb-4985-bdf3-3746f2ad1e9f)
this is nice, but kind if tight around the door ways
![image](https://github.com/user-attachments/assets/80c78ad2-5bf3-43c1-b9bd-a53a636a55d0)
![image](https://github.com/user-attachments/assets/57115645-531e-492e-b38f-66b5c8c07777)
maybe swap these around?
![image](https://github.com/user-attachments/assets/5a9468a6-ee23-4480-b549-69277ab92ecb)
a real window showing people where to cryo would be good i think.
![image](https://github.com/user-attachments/assets/087ecf82-fc62-42ae-9b23-827bd66a1d8c)
intentional? 
![image](https://github.com/user-attachments/assets/423b28e7-04f0-41ff-aeab-4d43dc33d5cc)
![image](https://github.com/user-attachments/assets/1e2e4bd0-4462-4589-aec9-3b23c2d30777)

bad area

</details>

On to the boring stuff!

Missing air alarms:
<details>

![image](https://github.com/user-attachments/assets/0eb069fd-b796-4b08-998e-af3f681f5646)
![image](https://github.com/user-attachments/assets/4f060a98-61ab-47a5-b078-b2b6fb363f64)
![image](https://github.com/user-attachments/assets/3a906863-2206-4884-9e6e-fca33a1e04be)
![image](https://github.com/user-attachments/assets/afc96285-f5a0-4b7e-8c2d-1d7e4107dc5b)
![image](https://github.com/user-attachments/assets/2148da5c-4b63-45a6-b1d8-5ba274f2e58b)
*

</details>

Missing vents:
<details>

![image](https://github.com/user-attachments/assets/b178c8b2-7cdb-4dcf-a651-8256edd3368f)
![image](https://github.com/user-attachments/assets/6d4aa555-cea3-470c-83b7-43dec6ecaf16)
![image](https://github.com/user-attachments/assets/23d501ae-cc51-4720-8882-a56b4b88683e)

</details>

Missing fire alarms:
<details>

![image](https://github.com/user-attachments/assets/7b484a21-64f9-4365-a21e-3f60169787b0)
![image](https://github.com/user-attachments/assets/40605ed4-b4d1-4cde-874b-57f57a1d248d)

</details>

Actually- there are a lot missing. im just going to ask you to look over the whole map sorry.

this is the gold standard for fire alarms:  
![image](https://github.com/user-attachments/assets/8a056fee-46bf-457a-8bd8-eca0c2f8e247)
it's not always possible but this is the most player friendly way to have them set up, please make sure all rooms that have fire doors in that area have at least one fire alarm, and if its a hallway, two minimum on each side of the hallways area
ie:
![image](https://github.com/user-attachments/assets/36f2bae4-f486-47c3-aa89-ed1159ea9e29)

2025-04-20 23:01 UTC, BarteG44 commented
1. Fair enough, i wanted to keep the greenery view from the dorms side but this was a pretty big hack from the beginning
2. They are exclusive yeah, but considering how big the map is and in how many rooms you can just close the shutters on the windows, i don't think it's too OP. If it proves to be a problem that gets abused then i'd be fine with getting rid of them
3. It's not meant to be a frequented corridor. It's there more as flavor, thus i wouldn't want to remove it
4. It's tinted windows there because i want to control the sightlines in those spaces. if you really don't want left and right to be asymmetrical, i'd rather replace them with walls. Also i use the wall closets as a way to fill up walls
5. You should also do a review of the map while in game. from the editor it looks like there's way too much lockers but in game, it gives the storage room a distinct feel. And if it looks good, there isn't a reason not to have that many
6. the display shall be annihilated
7. these are meant to be cabinet walls like what you would see in an office. I rarely see those standing solitary irl
8. That's a mapping helper. It applies the no-slip overlay to the tile, not everything. Again, something to see in game
9. These are kinda funny. I asked bacon i think like 2 or so years ago if i should be var editing the colors of decals and they said no, so this was my workaround lol. I'll replace them with a single one
10. The entrance to explo is via maintenance basically and they have a second door north too. I'd say a 3rd is too much
11. that room was crafted specifically as the entrance to the airlock
12. that's why it's a prison :)
13. i have tried airlocks there but i really do not like the look. I can add more air alarms as sort of compensation
14. why does it need to be larger? it's not really frequented often and is comparable to other maps already
![image](https://github.com/user-attachments/assets/f360114a-2193-404a-a3a6-4cd6432c21ec)
15. fair enough
16. I will swap the N2O and N2 around but otherwise it's comparable to other maps i would say
17. This room is actually accessible to all engineers because i wanted them to be able to talk with the CE at the desk. I agree that it feels kinda off but i haven't been able to make it look any better. maybe a plant could help...
18. that's better yeah, i'll do that
19. gonna make the door glass
20. enable /obj/ view
21. gonna fix
22. Gonna add more air alarms and vents

Lastly, i cannot agree on the use of fire alarms. I want to place the as they would be placed logically, in an accessible, central spot. They're meant to be triggered to close an area off, not as buttons for doors. Firelocks SHOULD block some areas off and be inconvenient to the average crew

2025-04-22 23:37 UTC, BriggsIDP commented
Thanks for addressing/fixing those issues I would say this is ready to merge now, below are a few small details that need updating but would in no way stop it from being merged:

<details>

![image](https://github.com/user-attachments/assets/ee08e38a-9232-4d30-b440-4a1365082bff)
missing decal in hop's office
![image](https://github.com/user-attachments/assets/5b962eb5-aae9-4ecd-8369-8da562bb01d9)
Not a motion cam! these are just regular cams
![image](https://github.com/user-attachments/assets/56272d9e-bdcf-4f89-8c08-16ba525835a2)
*stares
![image](https://github.com/user-attachments/assets/12de55e3-edd9-4a80-bacd-e3aa53cf0450)
this one is totally fine :)
![image](https://github.com/user-attachments/assets/2618eadb-cbc1-4a4a-bd1e-bb31bdc2cf30)
button on desk looks a little funky when closed. move to a wall?
![image](https://github.com/user-attachments/assets/cae9006d-5576-4bb3-8403-aa78af309442)
these air lock areas are odd since you can get trapped in here, they have no vents, fire or air alarms but have fire locks on each side. You'll probably need to one set of fire locks so this area is part of another with those things, or you'll have to change these areas quite a bit to include walls that you can mount things to.
![image](https://github.com/user-attachments/assets/6815eade-4dfb-4509-8ce6-98596b7c4ef7)
vents invisible under objects, few places like this across the map, please limit this when possible. here are a few I saw:
![image](https://github.com/user-attachments/assets/f192c171-e796-447a-b476-0a3e9100b985)
![image](https://github.com/user-attachments/assets/430767a9-fe29-49c3-b056-7778d0f0c03b)
![image](https://github.com/user-attachments/assets/cf96e423-117c-4081-8bdd-ebc150a51baa)
![image](https://github.com/user-attachments/assets/802843d8-a0c2-433f-9f2a-9e0986d9e18b)
![image](https://github.com/user-attachments/assets/dd087f1f-0232-405f-8ebd-e4329844343a)
![image](https://github.com/user-attachments/assets/7efbd1a1-b446-4d31-821f-242ac7cd50ee)
ect.
![image](https://github.com/user-attachments/assets/e708ad63-c424-400d-ae55-34c72c5f71e0)
glass door?
![image](https://github.com/user-attachments/assets/03fbcff8-2fca-43ef-a2fd-656f71d11930)
This tinted window makes some ugly shadows!
![image](https://github.com/user-attachments/assets/5302154d-b8fa-48a9-abea-5ea59d87bdf3)
no light switches on explo shuttle!
![image](https://github.com/user-attachments/assets/793249cd-3d2a-4f1e-8807-212d2378c080)
while unlikely, having plasma tanks on the arrivals is a little risky as a griefer could sabotage it when it is not needed. you could replace this with an air tank for esthetics. this isn't a problem on other shuttles as they can just be avoided IC.
---
camera blind spots
![image](https://github.com/user-attachments/assets/2023a336-b4bc-4a86-a0b8-81773bab7d44)
![image](https://github.com/user-attachments/assets/3e9b3d16-194b-4ea9-99c6-605c8cb4857f)
![image](https://github.com/user-attachments/assets/ea5cf1c9-a595-4820-bafd-98782ef67c5a)
![image](https://github.com/user-attachments/assets/7afbec0e-b97b-47d8-a85d-21737948fbc6)
![image](https://github.com/user-attachments/assets/671bd79b-d2ce-470d-8aa4-d7b3f83c8486)

inversely, can probably see too much of the maint here
![image](https://github.com/user-attachments/assets/57630043-84fb-40e5-b23e-e86e39159b3e)


---
![image](https://github.com/user-attachments/assets/25078191-1c89-48f3-ab95-0fa191638622)
![image](https://github.com/user-attachments/assets/458c1ea1-1cae-428b-8e0a-b6d1371306a6)
no air, or fire alarms
![image](https://github.com/user-attachments/assets/5b3772bb-79b3-41b9-adb2-c3d3ea9d888a)
no air alarm
![image](https://github.com/user-attachments/assets/3448f88a-4ca2-4062-aff7-6e651a452819)
no vents

</details>

Nice work on this station, it's clear how much time and love you've put into the details. looking forward to playing it!

2025-04-23 01:07 UTC, BarteG44 commented
Fixed all of these other than the psych office not having a camera, which is intentional

>Not a motion cam! these are just regular cams

and no idea how this happened. i swear i selected the motion ones. It's embarrassing really

2025-04-23 06:17 UTC, BriggsIDP commented
Approved!

2025-04-23 18:24 UTC, BriggsIDP approved these changes

2025-04-24 19:19 UTC, Tsar-Salat approved these changes
Code is fine. Floria has covered map review for me.

2025-04-25 13:30 UTC, spockye requested changes
![image](https://github.com/user-attachments/assets/2ed76dd4-6904-4a1e-a04f-cd1e46bb7346)

seems unintentional?

![image](https://github.com/user-attachments/assets/3fe19c9a-d1d4-4844-bed4-31217dd0f8d7)

in Genetics

-----
gotta say man, this is some amazing work. love how it looks, and the attention to detail is on point

would love to see it in action 
keep it up!

2025-04-26 18:42 UTC, spockye approved these changes

2025-05-07 12:32 UTC, PestoVerde322 requested changes, later dismissed
First off, the name of the map file name should be updated to CardinalStation.dmm, to reflect the actual name, now onto various things that are still wrong:

![image](https://github.com/user-attachments/assets/7e330e7d-f779-49cd-8ed0-b568c6e092b8)
Fence in wall, looks off.

![image](https://github.com/user-attachments/assets/0571b99c-1b98-431e-8a5b-3890803473ca)
two indestructible walls?

![image](https://github.com/user-attachments/assets/6390a2e4-37c4-49ca-92a2-0f958aa45e3a)
Three different APCs for otherwise three unassuming areas, now I might be fuzzy on this one, but i recall that there's a way to tie the zone to an APC, ask on discord for further infos.

2025-05-07 20:49 UTC, PestoVerde322 approved these changes

2025-05-07 20:59 UTC, BarteG44 commented
sound change tag can be removed as well

2025-05-10 18:11 UTC, PowerfulBacon approved these changes

2025-05-10 18:11 UTC, PowerfulBacon commented
It passed the mapping checks so good enough for me

2025-05-10 18:18 UTC, merged