[Port] Adds leaning to the game
BeeStation/BeeStation-Hornet pull request #12046
Opened 2024-12-17 12:22 UTC by XeonMations

## About The Pull Request

As the tin shows, adds leaning to the game.

Ports the following TG station PRs:
- [x] https://github.com/tgstation/tgstation/pull/76704
- [x] https://github.com/tgstation/tgstation/pull/77002
- [ ] https://github.com/tgstation/tgstation/pull/78847
- [ ] https://github.com/tgstation/tgstation/pull/87390
- [ ] https://github.com/tgstation/tgstation/pull/88215
- [ ] https://github.com/tgstation/tgstation/pull/88494

## Why It's Good For The Game

![image](https://github.com/user-attachments/assets/9e6faa5e-a740-4f43-bf28-843a1089a5d1)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/user-attachments/assets/23a4eb1f-4d5b-452c-b1df-fd17e9597491)

</details>

## Changelog
:cl: XeonMations
add: Added leaning to the game. You can now lean by dragging your character onto a wall/window.
/:cl:

2024-12-19 17:32 UTC, ClownMoff commented
I'm going to have so much e-sex with this

2024-12-22 17:21 UTC, Tsar-Salat requested changes, later dismissed
https://github.com/user-attachments/assets/b9b82e16-858b-48fe-a4ef-f98cf189bdd8

is there a reason why leaning sometimes fails here?


https://github.com/user-attachments/assets/61ce14e0-45d7-4b57-bf6c-af01225d2c9a

Falling when the airlock should make you fall *into* the airlock. It doesnt make sense to fall forward on something you are leaning on, yea?


https://github.com/user-attachments/assets/379f240b-2f6c-44f1-bb16-199cc5492cbf

The south leaning looks really bad ngl. I get why it should still exist, but is there something you can do to make it look like the spaceman isn't on top of the wall?

![Screenshot 2024-12-22 121546](https://github.com/user-attachments/assets/98ae065d-0719-4215-b906-b53d556ac6ac)

Two people should not be able to lean in the same space.

2024-12-27 08:34 UTC, XeonMations commented
> The south leaning looks really bad ngl. I get why it should still exist, but is there something you can do to make it look like the spaceman isn't on top of the wall?

I genuinly cant do anything about it. If you have suggestions i am open to them.

2024-12-27 17:21 UTC, Rukofamicom commented
Leaning south is immersion breaking enough I'd go as far as to suggest it be impossible.

2024-12-27 19:44 UTC, Tsar-Salat commented
> If you have suggestions i am open to them.

honestly just lower the y distance moved? See how it looks.

2025-01-02 06:46 UTC, TsunamiAnt commented
so much work to avoid just basic pixelshifting smh.

2025-01-14 05:02 UTC, XeonMations commented
climbing should cancel leaning
shouldnt lean on open doors
add leaning on lockers
if someone opens a locker you fall in

2025-01-15 23:31 UTC, XeonMations commented
Done!

2025-01-15 23:32 UTC, XeonMations commented
> honestly just lower the y distance moved? See how it looks.

Lowering the y distance doesnt really help much since the legs of the spessman still clip ontop of the wall, which is what makes it look weird. The only possible way of making it not look bad would cause a bit of the spessmans to become behind the wall, which would then make people able to use this as a hiding mechanic

2025-01-21 00:35 UTC, XeonMations commented
Add the ability to lean on mechs

2025-01-21 08:03 UTC, RDS88-beeman commented
if you're leaning on a door in 0g, and someone opens it, you still fall over even though there's nothing pulling you down

2025-01-21 16:28 UTC, ClownMoff commented
Add the ability to lean on people and if they move you fall down

2025-01-21 16:32 UTC, Tsar-Salat commented
> Add the ability to lean on people and if they move you fall down

Leaning is meant to be an environmental feature, either your character is relaxed or waiting for something, or you want to jump out of the way of a passerby/projectile.

What's the use case here that isn't getting in to "resting and spamming jump on eachother" territory?

2025-01-21 22:13 UTC, BotTierPC commented
I think that leaning + smoking is broken. Smoking seems to cancel lean, after something procs? It not nico metab as taking smoke out of mouth cancelled <3 amazing PR though, so interesting and thankies for adding such an interesting thing to game

2025-01-22 02:19 UTC, XeonMations commented
COMSIG_LIVING_STATUS_PARALYZE,
		COMSIG_LIVING_STATUS_KNOCKDOWN,
		COMSIG_LIVING_STATUS_STUN,
		COMSIG_LIVING_STATUS_SLEEP

2025-01-22 03:31 UTC, XeonMations commented
> I think that leaning + smoking is broken. Smoking seems to cancel lean, after something procs? It not nico metab as taking smoke out of mouth cancelled <3 amazing PR though, so interesting and thankies for adding such an interesting thing to game

Fixed!

2025-02-14 22:32 UTC, PowerfulBacon requested changes
Re-request review on discord/github or send a ping for any clarifications.

2025-02-14 22:32 UTC, PowerfulBacon commented on code/datums/components/leanable.dm
> +	RegisterSignal(lean_target, COMSIG_VEHICLE_MOVE, PROC_REF(mech_moved))
What if the target is a movable that moves, but isn't a vehicle or airlock?

For example:
- Lean on a non-anchored window
- Have another mob move the non-anchored window

2025-02-14 22:32 UTC, PowerfulBacon commented on code/datums/elements/climbable.dm
> +	if(source.flags_1 & ON_BORDER_1 && user.loc != source.loc && (dir_step & source.dir) == source.dir || user.has_status_effect(STATUS_EFFECT_LEANING))
Why are we blocking people from climbing railings that they are leaning on?

2025-02-14 22:32 UTC, PowerfulBacon commented on code/game/objects/items/stunbaton.dm
> +	SEND_SIGNAL(target, COMSIG_LIVING_MINOR_SHOCK) //Only used for nanites AND LEANING NOW!
This comment can just be removed

2025-02-14 22:32 UTC, PowerfulBacon commented on code/modules/mob/living/carbon/carbon.dm
> +	var/verb_text = pick("throw", "toss", "hurl", "chuck", "fling")
Won't this just ignore the custom item throw verbs you added earlier?

2025-02-14 22:32 UTC, PowerfulBacon commented on code/modules/mob/living/silicon/pai/pai_shell.dm
> +	ADD_TRAIT(src, TRAIT_UNDENSE, PAI_FOLDED)
Does this trait need to exist? It seems like a bit of a weird one since it doesn't seem to have any effect anywhere and it's negated

2025-02-14 22:32 UTC, PowerfulBacon commented on code/modules/vehicles/_vehicle.dm
> +	SEND_SIGNAL(src, COMSIG_VEHICLE_MOVE, direction)
Mark this as SHOULD_CALL_PARENT now that it has something that requires calling

2025-02-16 05:16 UTC, XeonMations commented on code/datums/elements/climbable.dm
> +	if(source.flags_1 & ON_BORDER_1 && user.loc != source.loc && (dir_step & source.dir) == source.dir || user.has_status_effect(STATUS_EFFECT_LEANING))
Climbing onto a railing and leaning uses the same method.

2025-02-16 06:16 UTC, XeonMations commented on code/modules/mob/living/carbon/carbon.dm
> +	var/verb_text = pick("throw", "toss", "hurl", "chuck", "fling")
Fixed

2025-02-16 06:31 UTC, XeonMations commented on code/modules/mob/living/silicon/pai/pai_shell.dm
> +	ADD_TRAIT(src, TRAIT_UNDENSE, PAI_FOLDED)
Yeah, used for a lot of leaning stuff, for example non-airlock doors.

2025-03-06 17:55 UTC, Dejaku51 commented
damn you, you lazy AI

2025-03-06 17:55 UTC, PowerfulBacon commented on code/datums/elements/climbable.dm
> +	if(source.flags_1 & ON_BORDER_1 && user.loc != source.loc && (dir_step & source.dir) == source.dir || user.has_status_effect(STATUS_EFFECT_LEANING))
I don't see why you shouldn't be able to climb onto things that you are learning on

2025-03-06 17:57 UTC, PowerfulBacon commented on code/datums/elements/climbable.dm
> +	if(source.flags_1 & ON_BORDER_1 && user.loc != source.loc && (dir_step & source.dir) == source.dir || user.has_status_effect(STATUS_EFFECT_LEANING))
2 questions:
- Can we still climb tables? (And by extension, can things be climbable and leanable at the same time, and wouldn't that just make something unable to be climbed)
- Why do we need to not climb onto things that we are leaning on?

2025-03-06 23:05 UTC, XeonMations commented on code/datums/elements/climbable.dm
> +	if(source.flags_1 & ON_BORDER_1 && user.loc != source.loc && (dir_step & source.dir) == source.dir || user.has_status_effect(STATUS_EFFECT_LEANING))
There is currently nothing leanable that is climbable. This check makes it so you cant climb onto a table while leaning on a wall, for example.

Leaning and climbing use the same control. Thus overriding eachother.

2025-03-10 17:06 UTC, PowerfulBacon approved these changes

2025-03-11 03:23 UTC, XeonMations commented
Leaning on southern objects is now disabled as per request

2025-03-11 23:53 UTC, Rukofamicom approved these changes

2025-03-12 00:01 UTC, merged