Adds in radio fuzzing in maintenance
BeeStation/BeeStation-Hornet pull request #12076
Opened 2024-12-24 13:19 UTC by PowerfulBacon

## About The Pull Request

Blocks outgoing signals while in maintenance.

Any outgoing radio messages will be fuzzy, although you will still see incoming messages as normal (similarly to how signal jamming usually works, partly because radio code doesn't make it easy to fuzz messages for specific users).

The following things are jammed while in maintenance:
- Comms messages go out, but will be fuzzy and unreadable (AI comms are not affected, nor are centcom or syndicate comms)
- Recieving comms messages is unaffected
- Suit sensors will have scrambled data
- AIs will be unable to track you through suit sensors
- Pinpointers will not function if you or your target are in maintenance

## Why It's Good For The Game

The maintenance tunnels are a scary place, they should be able to serve as a home turf for antagonists and give advantages to those antagonists who act independantly and alone. The maintenance tunnels can't come to you, you have to decide to go to them.

## Testing Photographs and Procedure

![image](https://github.com/user-attachments/assets/40e1e558-ca6d-404c-881c-594a93a09437)

![image](https://github.com/user-attachments/assets/e4949bfe-eca7-43af-b1d5-0297e0131958)

Messages come in normally:
![image](https://github.com/user-attachments/assets/15bafbd5-c5a8-403e-93b8-8d21a12deca1)

![image](https://github.com/user-attachments/assets/c34384b9-67e7-46c8-8cbe-f9c13afc6f5f)

Crew pinpointers break when taken into maintenance:

![image](https://github.com/user-attachments/assets/40b6f54a-3128-4f01-aeae-836a6b5da8e3)

![image](https://github.com/user-attachments/assets/fd53f64b-aa55-4425-a622-9d26edea1ac6)

## Changelog
:cl:
add: Outgoing radio messages will become fuzzy if they originate from the maintenance tunnels.
add: Disruptions to the suit sensor and tracking network while the user is in maintenance.
/:cl:

2024-12-24 15:39 UTC, mrmanlikesbt commented
Are syndicate contract pinpointers affected? If so, I don't think they should be considering how inaccurate they already are.

Maybe instead of whenever any level of jamming is applied to suit sensors and the returning health is just randomized, you could have it so if _JAM_MINOR_ is active then the returning value is within a randomized 50-100 range? I do think having _JAM_FULL_ should completely obfuscate your suit sensors

2024-12-24 15:47 UTC, PowerfulBacon commented
Only crew pinpointers get jammed

2024-12-24 20:09 UTC, Fronsis commented
The more i think about this PR, the worse it gets, in paper i see your points if i only think solely on Antag vs Victims vs Sec but this also raises a **lot** of issues and i don't think this is the way to approach what you intend to do

1- Signal Jammer will become less relevant to buy even if you have the camera and hallway advantage.

2- Let's be honest NO ONE enjoys the Ion Anomaly and the only reason people bear with it it's because **it goes away** denying basic communication it's just annoying, it's not fun.

3- This will make finding bodies 150% more difficult, we already had a good balance since the refresh rate of sensors was changed, you no longer see insta-security or paramedics arriving in 0.1 seconds, unecessary change.

4- Antagonists have plenty of tools to ''shut'' their target one was made by you on #11911 (Even if people have given negative feedback but that's for another time) Cultists stuns, Heretics mute (and even more with your proposed rebalance on discord think-tank), Sleepy pen, mute toxin, drinks that make you mute, EMP, taking advantage of ION anomalies, etcetera we don't need to hugbox antagonists to this extent

5- One that i think it's extremely important and it's above Antag vs target vs sec: You fuck up basic communication on a normal scenario.
Are you not thinking how much of a pain in the ass is to roundstart trying to talk with your friends/co-workers because one is in mainteance trying to call you over because they found something cool but they can't because ''muh dangerous maint with tinfoil covered walls''

You fuck up people that get trapped by accident (Lots of newbies run across this, it's a classic for janitors with the cart for example)

You obliterate anyone trying to do gimmicks using the maint rooms, barber shop? private psychiatrist office? private bars? shops? questionable surgery bay or engineering project? a cozy home to invite friends over? Delayed, becomes a pain in the ass for the sake of a random rebalance of antagonist when it ends up affecting people that has nothing to do with it.

6- Coordinating sec becomes more of a pain in the ass, even if we had #11280 merged (which is ready to go but blocked for some reason) it becomes useless, you'll force Security to move together or in pairs, which is fine that i don't mind but you end up making things worse for your ''antag buff'' because now you'll be facing the entire sec force that's moving on a conga-line instead of a random officer that you have a higher chance to kill and advance your antagonist agenda from there

Those
  >  antagonists who act independantly and alone
Need to be smart and use the **plenty** of tools at their disposal to antagonize and accomplish silent kills, in fact a lot of people do stealth kills nowadays, they don't need an entire maintenance shut down just for their commodity when it affects the entire crew just to hugbox, it's also a #skill issue on their part.

2024-12-24 20:22 UTC, BarteG44 commented
i'd still want to at least see it test merged. Even if it screws up balance, it sounds like an interesting change.

2024-12-24 20:36 UTC, itsmeow commented
I like this idea but I think we need more tools and mechanics that reduce its overall impact.

Reducing accuracy of pinpointers and sensors rather than making them useless overall (e.g., you can determine the general area / side of the station). So recovering bodies doesn't become nigh impossible. Also, adding intercoms in some deep maintenance areas making communication possible in more select, intentional spots, for those without other comms methods and a little bit of cunning.

It might also be worth making the emergency station-bounced radios able to resist this effect (maybe with limited uses?).

Do note for the people stating it makes comms in maints impossible: That's not true, you can use NTNet/ PDA Messenger just fine.

Essentially, comms from maints need to be more intentional now, rather than 

"Y -> HELP MED MAINTS!!"

2024-12-24 22:21 UTC, DarnTheMarn commented
I don't see the complaints stated above as all that valid. The problem with ion anomaly, jammers, and stuff like EMP's is that they are done arbitrarily **to you**. Going into maint is **your decision**. If you don't want the risk, stay out of maint and take the long way around somewhere. If you know a killer is in maint, don't go in without a battle buddy. A rambo wannabe charging into maint at the first sound of someone getting 5 brute is exactly the type of person that should be ganked in maint.

2024-12-24 22:44 UTC, Fronsis commented
From a IC perspective on a **normal** shift where **nothing out of the ordinary** happens, at best people should worry about the questionable maintenance rooms, the dirtyness, darkness and suspicous blood but besides that it offers interesting rooms for people to do gimmicks with or loot and that's when the antagonist enter at play with their surprise appearance that disrupt that ''normal shift''

Historically in Bee and other servers maintenance has been a mix of ''danger'' and ''opportunities'', there is a reason why Assistants used to line up to get maint access before it was removed, to loot and use the rooms to set up gimmicks, not everyone has the ''Send to All'' PDA messaging, not everyone want to bother the AI to advertise whatever they're doing, i don't know why something that used to be A to B needs to become A to F just because we're hugboxing the antagonists when they already have many tools to achieve that same goal.

> If you know a killer is in maint, don't go in without a battle buddy

Sure, that i agree, in my case it's very easy for me to adapt and order my officers to pair up, but that will just go to one of Bacon's original complaints from months ago where the antag can't 1v1 because they get surrounded by 30 officers in less than one minute *shrug, i'm just thinking about the players that are neither antag nor security that will get the short stick of this when this is unecessary, if everything what Kat suggested is more balanced because at the very least you have an option to stay communicated if you put an effort for it instead of randomly denying the comms of the entirty of maint that ruins the flow of communication and information in non-dangerous times (not necessarily relevant to reporting a crime or antag related)

Also about the PDA's i can already predict messages being sent by quick copy-pasting, walking with the pda tab open or people rushing HoP office vendor and Lawyer office to get the Send All cartdrige.

Lastly, Bacon i've witnessed a lot of your antags rounds these recents times and i've noticed most of the time as a regular traitor you choose the Comms Jammer as part of your loadout and i've even seen you say it makes everything easy to go stealth and accomplish your objectives, this change basically amplifies it and i'm not sure what you're trying to achieve other than making stealth things easier when you should be well aware that **everyone** that has a decent amount of hours on Bee would rather see an interesting gimmick or something loud than a random greentext of someone who stole a hand tele and did a random bomb on cargo that makes you go ''Oh X was an antag? i had no clue!!!'' the more experienced and robust players will just have an even easier time to do stuff they're already good at as an antagonist and the new players will still be stuck in maint trying to ask for help while no one can even use a pinpointer to get to them.

The issue of communications, body recoveries and so much more are still present and all the downsides do not, in my opinion, justify this absurd change to maintenance.

2024-12-24 23:25 UTC, Fronsis commented
Anyways in short this boils down to: Is this fun/enjoyable for the general players on a shift? What do we earn? What do we lose? Why did people like/dislike the current system? And when i find myself answering these type of questions i feel like this commodity for antags doesn't weight properly against the current system in terms of enjoyment or fun, i wouldn't mind a few testmerges of this of course just to get more feedback but these were my starting thoughts when reading the Why is it good for the game.

2024-12-25 00:21 UTC, DarnTheMarn commented
>antag can't 1v1 because they get surrounded by 30 officers in less than one minute 

I think the idea here is that if you have to meet up before heading in, that'll take more than one minute to organize.

2024-12-25 09:23 UTC, PowerfulBacon commented
The difference between what this adds and what we have now is that maintenance doesn't come to you. The fuzzing effect is not absolute and some data can pass through it. If someone is talking in maintenance, you still know they are talking and you still know they are there but some data will be lost.

What we gain is the area that exists to serve as the domain for antagonist and crime being more scary and something that you would be just slightly more adverse to just thoughtlessly running into.

2024-12-25 09:29 UTC, PowerfulBacon commented
The issue of PDAs bypassing signal jamming is unintended and a fix will be issued.

2024-12-25 10:04 UTC, PowerfulBacon commented
Crew pinpointers will now only show you up to 25 tiles of the body location with minor jamming.

2024-12-25 17:46 UTC, aramix273 commented
some circuits components work off based on NTNet packets, I believe
what immediately comes to mind are radio components (signalers) or NTNet transmitter/receiver
are those affected? should they be? how?

2024-12-26 01:24 UTC, Marshmellow105 commented
if this is the cost of sec dispatch I am ready to pay it

2024-12-26 02:26 UTC, SunShine214 commented
Is this needed? It really seems like it’s unnecessary bloat trying to solve a problem that is better solved in a method that isn’t so arbitrary. It makes no sense in universe by (tcomms use subspace, some walls aren’t going to make a difference)

SS13 is a game all about emergent gameplay, and arbitrary code requirements like this devolve these core principles of the entire game. As an example, this removes any interesting interactions inside of maints, and would require antags or just normal crew to use the station blueprints in order to do any gimmicks with radio or similar.

2024-12-26 02:33 UTC, DarnTheMarn commented
> if this is the cost of sec dispatch I am ready to pay it

I don't have any say in this either way but this is apples and oranges. You can still receive messages in maint just fine so you only need the one guy outside of maint. That's only a like 15-20% reduction in the certified problematic-o-meter

2024-12-26 02:52 UTC, Marshmellow105 commented
> I don't have any say in this either way but this is apples and oranges. You can still receive messages in maint just fine so you only need the one guy outside of maint. That's only a like 15-20% reduction in the certified problematic-o-meter

Still better than as is. You need a partner going into maintenance to be safe, you cant just blurt out ‘HELP X’ and have people rush to your sensors.

I honestly think this is a fun antag buff that makes maintenance scary as it should be.

2024-12-26 02:57 UTC, Fronsis commented
> > I don't have any say in this either way but this is apples and oranges. You can still receive messages in maint just fine so you only need the one guy outside of maint. That's only a like 15-20% reduction in the certified problematic-o-meter
> 
> Still better than as is. You need a partner going into maintenance to be safe, you cant just blurt out ‘HELP X’ and have people rush to your sensors.
> 
> I honestly think this is a fun antag buff that makes maintenance scary as it should be.

The pr is all too focused on the antagonist side of things while leaving crew and their gimmicks/fun left over, people will just use metas to circunvent this(as usual) anyways and it kills a lot of gimmicks

Also dispatch mask will need to bypass this comms interference(which would make the only part affected the random victims)

2024-12-26 02:59 UTC, Fronsis commented
> > if this is the cost of sec dispatch I am ready to pay it
> 
> I don't have any say in this either way but this is apples and oranges. You can still receive messages in maint just fine so you only need the one guy outside of maint. That's only a like 15-20% reduction in the certified problematic-o-meter

Hell this is already  a meta, just play around doors to quickly relay information like..

-> go in deep, find blood cult runes
-> go out for one second inform, go back in/retreat

It's stupid and annoying lol and that's what people will end up doing for the most part, hell even being  on space and checking from there works too

2024-12-26 09:11 UTC, Fronsis commented
> if this is the cost of sec dispatch I am ready to pay it

It would be scrambled unless tweaked so.. no point

2024-12-26 11:34 UTC, Rukofamicom approved these changes

2024-12-26 15:44 UTC, Vasily2013 commented
Not having a way to bypass the interference is seriously annoying, especially if you're an engineer. It makes communications impossible. I think if this is meant as a buff to antags it is drastically too much. I'd suggest starting smaller, just cut the radios and crew pinpointer, let PDA and suit sensors work.

2024-12-26 16:09 UTC, PerishedFraud commented
> Bad. Bad. Bad. Bad. Bad.

Elaboration time:

Our antags are expected to make the round more interesting. It's often said that objectives are best left ignored and an antag should focus on making things tense, fun and so on. Murder and stealth are the most boring and least fun things you can do as an antag, yet PRs like this are made to encourage murder and stealth. It directly conflicts with our goals for gameplay.

The change is predominantly geared towards antags despite them having fairly good capabilities against crew. One should not balance around new players in antag roles, but around the actual strength of an antagonist. Just as how a new heretic may praise this change because they normally struggle to capture people, this same heretic will easily capture a new player in a crew role. Thus changes like this shift the balance uncomfortably towards special snowflake antags and shift the crew ever so closer to cattle for slaughter. Again, crew slaughter not being our goal, at least not anymore, directly contradicts things like this.

The change directly removes interactivity in maints. People who spend a lot of time in maints like janitors, assistants, engineers and what have you, can no longer communicate properly with the crew. There is no upside to this unless your goals are to annoy players (ignoring antag stuff above).

The change optimizes crew death, even antags aside. Please stop optimizing crew death. Dying is the worst form of gameplay, actively drives new players away and does not contribute to round end unless done en masse.

Overall, misguided change that feels at home in an LRP server where every antag has a bone pass, not here. And yes, bad bad bad bad bad.

2024-12-26 16:21 UTC, Rukofamicom commented
The PR is geared toward making a relatively safe space for antags to operate - universal for all antags to utilize without gear requirements, sabotage of comms or being ready to immediately gank someone so quickly they don't have the chance to use comms.

This PR can enable engaging antags as much or more than bad ones who already go around ganking people silently. It enables players to be more engaging in their approaches without putting their round at risk because they accidentally gave the player who meta-hates all antags to engage.

2024-12-26 16:23 UTC, PerishedFraud commented
To me that just sounds like solving a community issue (old sec players vs new antags, and sec being too strong) with code that affects everyone, for the worse.

2024-12-26 16:35 UTC, Geatish commented
Honestly i would change so storefronts doesn't have the maint zone, would mostly fix the problem regarding gimmicks.
Either way, cool pr. Makes maints actually feel more dangerous.

2024-12-26 16:43 UTC, Vasily2013 commented
I'll put some additional food for thought here. Like I said already, this is a lot of really major changes in really short order. I think maybe this PR should be broken up and released in phases if needed. 

* Start off with radios and pinpointers in this PR
* Wait a couple months to see if that has the desired effect
* If desired effect has not been had, add PDAs in.
* Wait again and observe effect
* If desired effect still has not been had, add in suit sensor scrambling.


Alternatively you could do the same thing by making maintenance processors for tcomms, and have those be in maintenance rather than tcomms proper, it would add something interesting for engineers to do with tcomms. Not sure how that would be implemented, but it would provide an easier way to have it be dynamic and engaging, rather than just a constant way of life.

2024-12-27 02:48 UTC, Fronsis commented
> To me that just sounds like solving a community issue (old sec players vs new antags, and sec being too strong) with code that affects everyone, for the worse.

Correct, after speaking with Bacon and other people the issue more or less boils own to Security or the Antagonist being too efficient at their job.. There's not really an easy solution tofix that since people can't suddenly become unrobust, you can have sportmanship but it kinda ends there otherwise you're kinda doing fail rp

I don't see why we need to have an entire maintenance area the random antag kingdom where everything becomes a pain in the ass because antags needs to have their hand held, most antags already have tools to disable another spessman then if Security has 2 braincells they should announce: DO NOT WANDER INTO MAINTENANCE, DANGEROUS INDIVIDUAL LURK NEAR and if they decide to ignore all IC warnings, that's on them and that's okay.

Vasiliy, Kat and others had a few ideas that propose better alternatives.

2024-12-27 05:59 UTC, Rukofamicom commented
> Alternatively you could do the same thing by making maintenance processors for tcomms, and have those be in maintenance rather than tcomms proper, it would add something interesting for engineers to do with tcomms. Not sure how that would be implemented, but it would provide an easier way to have it be dynamic and engaging, rather than just a constant way of life.

We hashed this one out in DMs a bit earlier and I wanted to state what I did in the original conversation here as well regarding these:
* Maints would still be a deadzone for comms at roundstart, with the ability to easily build machines that boost it if someone wanted to go out of their way to do so, such as for a gimmick shop/bar/club or whatever someone is running inside of maints.
* The machine should be readily accessible and easily built, but require an anchored frame so they can't just be dragged along.
* The only locations that should start with one are the existing gimmick jobs that spawn in a maints room. 

---

Only one other thing I want to say right now: This PR does not significantly impact any aspect of game balance except the spread of information, and it only affects the sender if they are currently within maints. It does not completely remove their message, instead partially obscuring it.

* This does not allow anybody to kill anyone faster 
* This does not make anyone die faster
* This does nothing to players that aren't roaming maints regularly (sorry engineers)
* The biggest impact this has is removing the ability for someone to willingly sacrifice themselves in exchange for outing an antagonist by standing still to scream "HELP MAINTS LOCATION" while they're being attacked instead of doing literally anything else like trying to run away. 
* This does have a secondary impact of diminishing maint gimmicks where someone build something custom within maints, some form of machine that acts as a comms booster as described above will alleviate this one.

Maints are supposed to be an inherently spooky/dangerous place with scraps of loot. Just like a single cultist shouldn't chase security into the brig alone, a single officer shouldn't be pursuing a cultist into maints alone. The best way to think about this PR is making maints its own department, and antagonists the ones in charge of it. Others can enter and do things, but at their own risk. 

Murderbone and most non-objective round removals are both against the rules and this PR isn't going to magically make more people break the rules. All I ask is you give the PR a fair and honest chance to see what antagonists actually do with it. Having the freedom to make threats knowing your target has to respond by either running, fighting or playing along instead of simply screaming for help is a great tool for being more engaging as an antagonist.

---

> After speaking with Bacon and other people the issue more or less boils own to Security or the Antagonist being too efficient at their job

Right now the antag/sec balance is in a terrible state with it very heavily tilted in security's favor yes. If security is staffed, playing to win and coordinated at all, they simply win. It either takes understaffed, uncoordinated, inexperienced, or just good faith playing along in spite of knowing what's up for antagonists to succeed currently. It's not really a skill issue when antagonists are by nature of the role nearly always less experienced than the security players. 

A security main will always have more hours and experience in security than the most experienced antagonist will. Antagonists should be scary by default, not only the ones that have been playing for five years and have nearly four thousand hours.

2024-12-27 11:57 UTC, PerishedFraud commented
Having a machine to counteract the fuzzing seems like a good solution. It can easily be sabotaged to get the desired effect since it's in maints but it lets the players actually do something about the issue instead of just dealing with 'magical antag land' as another post mentioned. This simple addition would make this a lot more balanced.

2024-12-27 12:01 UTC, ClownMoff commented
This (like a lot of PRs) attempts to balance only the gaming side of the game and forgets about the RP part. People do stuff in maintenance as a gimmick and having to exit maintenance to respond to people or every time you need to speak with someone will be incredibly annoying. Oh, and if somehow you got trapped in maintenance without the access for whatever reason they have no way of communicating to get out unless they keep spamming comms until RNG lands and the message is readable enough. Terrible idea.

2024-12-27 12:09 UTC, ClownMoff commented
> I don't see the complaints stated above as all that valid. The problem with ion anomaly, jammers, and stuff like EMP's is that they are done arbitrarily **to you**. Going into maint is **your decision**. If you don't want the risk, stay out of maint and take the long way around somewhere. If you know a killer is in maint, don't go in without a battle buddy. A rambo wannabe charging into maint at the first sound of someone getting 5 brute is exactly the type of person that should be ganked in maint.

If they point of this game said to us by administration team is that every shift should be a normal one and antagonists and stuff like that aren't supposed to be the norm in Nanotrasen why would entering maintenance be a risk? Validhunters aside.

2024-12-27 12:10 UTC, ClownMoff commented
> This PR does not significantly impact any aspect of game balance except the spread of information

This comment seems so out of touch with reality. You mean spread of information? On the text-based roleplay game? Only one of the most important parts of the whole game? Being able to communicate???!

2024-12-27 15:54 UTC, Vasily2013 commented
> Also the pinpointer breaking is such a dumb idea, what's the point on this, I swear every PR from the maintainers I see is just sucking off either security or antagonists, why would you invalidate the whole point of paramedics.

I'm of the opinion that pinpointers only giving a regional idea is fine for maint. It's the crew monitor that's the real nerf to medical.

2024-12-27 17:30 UTC, Rukofamicom commented
An important point raised in discord: it's possible for players to become semi-trapped inside of maints if they duck in while not having the access requirements to get back out.

Possibly worth making maints public access by default with this change, or at least most of it anyway.

2024-12-27 17:49 UTC, Fronsis commented
> An important point raised in discord: it's possible for players to become semi-trapped inside of maints if they duck in while not having the access requirements to get back out. _I know they can still send messages and crew will probably be able to put together what's going on._

That reminded me that.. I'm not sure which PR changed it but a while back i realized that if you're in crit or, as you said, duck/laying down you're unable to open a door even if you have the access for it, it was very common to be able to crawl into a hallway to escape death/to be found but since that change got introduced.. Lots of folks have died with their body next to the door because they were unable to open it.

One of the most common issues i've encountered during this TM is that feeling of ''ugh'' or ''*sigh/really?'' when i'm having a conversation with someone and because i walk into maint (by muscle memory) the conversation stops because my message is scrambled so i have to do **one** step out, repeat my message and then walk in, it kinda ruins the flow.

While this might be more complicated to do, i figured a good way to do solve that is the fuzzing become worse the deeper you go in, if you're three-tiles inside maint (with the door open facilitating radio transmission) you should be able to talk normally and the deeper you go the worse it gets into it becomes a fully scrambled message, something like this:

![Screenshot_126](https://github.com/user-attachments/assets/723fbc1a-e713-442b-94d9-fd8862262730)

But considering our maps variations.. I do believe the maint machinery approach **across different maintenance areas** of all maps would be better, you just need to sabotage them, they could randomly get a short circuit or be roundstart broken with a % chance, requiring an engineer to repair them and scientist possibly to upgrade them? I was thinking they could perhaps be a machine for each direction of the station.

Talking about our maps variations, some of them have very small maintenance segments and that brings back the issue i brought up, it feels.. meh to be unable to send proper messages just because you're in a small 3x1 hallway when you have doors that could ''facilitate'' the radio waves coming through compared to a whole 16x16 maintenance room which would make sense.

2024-12-27 19:25 UTC, PerishedFraud commented
I'd like to restate that the people who downvoted this including myself are unhappy with the change, and no amount of manipulative discussion (such as suggesting downplaying or modifying the change, implying that it cannot be undone) will change that.

2024-12-28 01:02 UTC, DarnTheMarn commented
Just played a round so here's some anecdotal evidence. 

I was a detective on corg when swarmers got called out and we all ran around trying to find them. I rounded a corner only to find myself face to face with a couple swarmers and had to beat a hasty retreat and call for backup. Later in the round, I also stumbled on a spider in bar maint and ran for my fucking life so I could call for backup.

Pretty good experience, it made maint feel more dangerous and gave those swarmers and spiders a bit more of a chance than they would have otherwise.

2024-12-28 23:05 UTC, Liver-1 commented
The entire security team got killed by one nightmare in the shift that just went by.
We couldn't even start trying to retrieve them or formulate a response because the people I was trying to help were in maints.
Feels bad man.
AI needs a buff if this goes through. comms defuzzer or something. Please don't make the role just be sitting and watching people die not being able to give any assistance. AI is ONLY information control and distribution. If you fuck with comms you basically evaporate any positives an ai can bring to a round.

Please don't reduce AI to an actual loudspeak doorknob.

2024-12-28 23:10 UTC, Liver-1 commented
> The PR is geared toward making a relatively safe space for antags to operate - universal for all antags to utilize without gear requirements, sabotage of comms or being ready to immediately gank someone so quickly they don't have the chance to use comms.
> 
> This PR can enable engaging antags as much or more than bad ones who already go around ganking people silently. It enables players to be more engaging in their approaches without putting their round at risk because they accidentally gave the player who meta-hates all antags to engage.

When I antag I like to mock and call out sec with funny gimmicks, usually from a hidden base in maints. This directly removes this ability for antags,

2024-12-29 01:30 UTC, Rukofamicom commented
> AI needs a buff if this goes through. comms defuzzer or something. Please don't make the role just be sitting and watching people die not being able to give any assistance. AI is ONLY information control and distribution. If you fuck with comms you basically evaporate any positives an ai can bring to a round.

The AI is not supposed to be affected by this PR. If they are affected, it is a bug.

2024-12-29 12:16 UTC, Rukofamicom requested changes
Alright, so the biggest complaint/solution by far is regarding how this affects both roles that start in maints (barber/psychiatrist) and how it restricts players from building their own thing in maints, including antagonists who like to taunt sec. 

A signal boosting machine should be added as part of the PR that enables unfuzzed comms within a limited range (I would use sight range so they can never go through walls or around corners and typically affect an entire room). The machine should require anchoring the frame before being built and not be possible to drag around.

2024-12-29 12:37 UTC, Rukofamicom commented
The other biggest complaint I see I disagree with outright and want to break down my thought process on why this will encourage better, not worse antaggery:
* There will always be "bad" antags that play too efficiently and go for perfect stealth
* Yes this PR does give people with that playstyle a bit of an easier time if they encounter people in maints - every change that adds more tools has good and bad ways to use them. 
* This PR does not **enable** the bad antag playstyle - This is proven by the existing bad antags that are already able to be bad antags with a relatively low skill level. Sleepy pen (or reagent combat in general), triggered explosives, energy crossbow, etc. all exist for quick takedowns when they're appropriate and good antagonists need these tools available too. There is not much we can do about this on a coding level without also ruining the good players' experience and capabilities.
* This PR does not **encourage** the bad antag playstyle either - "Play to win" mentality is what does this, and this PR does not enhance or encourage that mentality. Those players will always exist. 
* What this PR does encourage is the players who want to play antagonist but have turned the role off because they feel forced to minmax after getting repeatedly beat down for daring to be engaging or having a gimmick, because it took one overly suspicious shitter to stumble on them and ruin it for the rest of the round with a single comms message. 
* The other thing this PR encourages is forcing a choice between engagement alone and calling for backup, slowing down the immediate removal of antagonists from the round and giving them a breathing window where they can go "Okay I was spotted, what do I do now" instead of immediately having to fight while also being under the pressure that backup is on the way.

This is the appropriate time to say "maints are ignoring feedback" because I do strongly disagree with the assertions that this will encourage or severely enable players that have a mindset problem when it doesn't. This PR gives breathing room to all of the good faith antagonists while not doing much to the others who can and do already gank you whether you're in maints or not because that's just what they do and it's unfortunately up to admins to stop that side of things. 

I had more say on the sensor scrambling side of the feedback but I'm out of time.

2024-12-29 15:42 UTC, DarnTheMarn commented
> A signal boosting machine should be added as part of the PR that enables unfuzzed comms within a limited range

Should the machine be limited in number, or printable at techfabs/circuit imprinters and if so, which ones? And should the machine be solid or traversable? If you don't want people to build them everywhere either/or could be do that job. If there's a limited number, you can't build them everywhere. If they're solid, you can't put them in the 1 tile wide hallways.

2024-12-29 16:49 UTC, Rukofamicom commented
The machine should be readily accessible to the folks trying to renovate part of maints. If an engineer is willing I have no problem with someone trying to build a network across all of maints to undo all fuzzing; it will be such a colossal task it isn't likely to happen often and can be just as easily undone since they can't work through walls and thus will always be visible if active.

2024-12-30 23:59 UTC, Vasily2013 commented
> The machine should be readily accessible to the folks trying to renovate part of maints.

You could make them wall-mounted items, like cameras. I also wouldn't make them LOS. Maybe somewhere between 5x5 and 10x10? That would let you require multiple per maint section to be effective, but also not need four or five repeaters just to cover a curvy hallway like near the Meta grav generator. 

Also, should doors stop the effect as well? Or would you just base it on open/closed turfs?

2024-12-31 04:22 UTC, Fronsis commented
> The machine should be readily accessible to the folks trying to renovate part of maints. If an engineer is willing I have no problem with someone trying to build a network across all of maints to undo all fuzzing; it will be such a colossal task it isn't likely to happen often and can be just as easily undone since they can't work through walls and thus will always be visible if active.
> 
> Nobody is regularly going to set up 50 boosters every round realistically even if they can, and trying to do so will make them a prime target.

Something that came to my mind was a 4(or i guess depending on map) main radio-wave controllers with a RNG spawn on the walls of maintenance divided like in bow, port, starboard directions that could be easily sabotaged or destroyed(Engis would need to print a board and build a new one in case of something like C4 or big qdel) and they also have a roundstart chance to start broken/not wired so engis can have some stuff to do after setting SM and other roundstart activities, the ION anomaly could straight up destroy all four at once too

2024-12-31 13:57 UTC, DarnTheMarn commented
This is getting death by committee'd, keep it simple stupid. A machine that unfuzzes radios within a small sight radius is plenty good enough to deal with the main complaint. Not a whole lot of rooms in maint where it needs to be AOE instead of sight radius.

2025-01-23 17:16 UTC, closed without merging