Adds a mapper comment mapping helper
BeeStation/BeeStation-Hornet pull request #12077
Opened 2024-12-24 23:49 UTC by BarteG44

## About The Pull Request

Adds a mapper comment mapping helper. Code has comments so maps should be able to have them too.

## Why It's Good For The Game

Allows mappers to comment on their design choices and decisions within the mapping editor. This mainly aims to make the map review process easier as mappers can explain why they did things a certain way ahead of a maintainer having to manually ask, eliminating at least some of the unnecessary back and forth. 

The second, more soulful, purpose of these is documenting the mapping process. Imagine if something like this had been added when the game was still new. We could be reading the years of comments left on box station, allowing us not only to understand how the map came to be what it is today but also to learn from the successes and mistakes of past mappers. Think Dev commentary nodes in Valve games like TF2 and Half Life 2.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/user-attachments/assets/0ea41769-2f41-46fb-9119-5281d0045c66)

![image](https://github.com/user-attachments/assets/e3166654-2799-4351-b383-3c59d71d2e83)

https://github.com/user-attachments/assets/16408f96-93fe-4f5f-bf4e-636331c1ed3d

</details>

## Changelog
:cl:
add: Added a Mapper Comment helper object visible only in a mapping editor
/:cl:

2024-12-27 12:04 UTC, ClownMoff commented
Good PR

2024-12-30 23:00 UTC, Dejaku51 requested changes

2024-12-30 23:00 UTC, Dejaku51 commented on code/modules/mapping/mapping_helpers.dm
> +	qdel(src) //Gets deleted on mapload since it has no actual function.
```suggestion
	return INITIALIZE_HINT_QDEL
```

2024-12-30 23:04 UTC, BarteG44 commented on code/modules/mapping/mapping_helpers.dm
> +	qdel(src) //Gets deleted on mapload since it has no actual function.
fair enough

2024-12-30 23:38 UTC, Dejaku51 approved these changes

2025-01-01 18:28 UTC, merged