Fixes warnings in compiler
BeeStation/BeeStation-Hornet pull request #12087
Opened 2024-12-27 07:40 UTC by XeonMations

## About The Pull Request

I hate seeing warnings on main....

## Why It's Good For The Game

warnings bad

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/user-attachments/assets/bf348daa-380f-416a-a992-0ab01a9203c4)

</details>

## Changelog
:cl: XeonMations
code: Fixed some warnings in the compiler
/:cl:

2024-12-27 07:43 UTC, EvilDragonfiend requested changes
use `pass()` instead of return. it is not consistent when other conditions don't do return.

2024-12-27 09:10 UTC, EvilDragonfiend approved these changes

2024-12-27 19:43 UTC, Tsar-Salat approved these changes

2024-12-28 21:28 UTC, Tsar-Salat commented
this is annoying me so merging

2024-12-28 21:38 UTC, merged