[PORT] Bloodsuckers from monkestation
BeeStation/BeeStation-Hornet pull request #12092
Opened 2024-12-27 23:38 UTC by mrmanlikesbt

## About The Pull Request

Bloodsuckers are originally from [fulpstation](https://github.com/fulpstation/fulpstation/pull/97), however, this is specifically a port of [monkestation's version.](https://github.com/Monkestation/Monkestation2.0/pull/151)

This pr does **NOT** include monster hunters. All monster hunter interactions are replaced by the curator- sort of giving them the same importance that a chaplain has.

## Why It's Good For The Game

[insert persuasive argument here]

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:  TheSwain, JohnFulpWillard, mrmanlikesbt
add: new antagonist, bloodsucker
imageadd: new radial menu yes and no icons
/:cl:

2024-12-28 21:32 UTC, Absolucy commented
please do not port the code 1:1

bloodsucker code is infamously HORRIBLE and would be much better off with extensive refactors/rewrites

2024-12-28 23:06 UTC, mrmanlikesbt commented
fair enough

2024-12-31 09:38 UTC, mrmanlikesbt commented
@itsmeow how are antagonist preference icons decided? I've been trying to figure this out for a few days, but haven't been able to figure it out. The code below always has the traitor icon.

```dm
/datum/role_preference/antagonist/bloodsucker
	name = "Bloodsucker"
	description = "..."
	antag_datum = /datum/antagonist/bloodsucker
	preview_outfit = /datum/outfit/bloodsucker

/datum/outfit/bloodsucker
	name = "Bloodsucker outfit (Preview only)"
	suit = /obj/item/clothing/suit/costume/dracula
```
![Screenshot 2024-12-31 033355](https://github.com/user-attachments/assets/5c52b235-c994-4525-b55a-e3b6ef8b7b24)

I've also tried to change other antagonist preferences' preview outfits, but I couldn't even get that to work. This led me to believe that maybe they're compiled with tgui, so re-compiled it to no avail. After that I wasted my time by going down some other rabbit holes that lead no where.

2024-12-31 09:40 UTC, itsmeow commented
@mrmanlikesbt 
Debug -> Regenerate Asset Cache

2025-01-01 00:27 UTC, TsunamiAnt commented
why is it bloodsucker and not vampire anyhow. Honestly ruins the vibe a bit.

2025-01-01 00:50 UTC, mrmanlikesbt commented
There is a vampire race and bloodsucker antagonist, I don't want to cause confusion between the two. ~~Or we can just delete the vampire race and rename bloodsuckers to vampires.~~

2025-01-01 12:10 UTC, TsunamiAnt commented
Just delete vampires and rename 'em. Our vamps were always just a Halloween gimmick anyhow

2025-01-02 02:34 UTC, mrmanlikesbt commented
> Just delete vampires and rename 'em. Our vamps were always just a Halloween gimmick anyhow

@PowerfulBacon ?

2025-01-08 17:27 UTC, PowerfulBacon commented
I don't really care what happens to the halloween races

2025-01-11 02:17 UTC, Absolucy commented on code/modules/antagonists/bloodsucker/life_bloodsucker.dm
> +	var/static/handled_final_death = FALSE
this static var will be shared across _all bloodsuckers_, not just the current datum

2025-01-11 04:41 UTC, mrmanlikesbt commented on code/modules/antagonists/bloodsucker/life_bloodsucker.dm
> +	var/static/handled_final_death = FALSE
should be fixed

2025-01-11 05:21 UTC, Absolucy commented on tgui/packages/tgui/interfaces/AntagInfoBloodsucker.tsx
> +          src={resolveAsset(`bloodsucker.${selectedPower.power_icon}.png`)}
these are just the icons used by the actions, right?
you could totally just implement a spritesheet using subtypesof with the actions.

2025-01-11 05:22 UTC, mrmanlikesbt commented on tgui/packages/tgui/interfaces/AntagInfoBloodsucker.tsx
> +          src={resolveAsset(`bloodsucker.${selectedPower.power_icon}.png`)}
yes. I would've done that but I've got no idea how tgui works so idk how I would go about implementing that

2025-02-02 17:57 UTC, PowerfulBacon commented
This is cool

2025-02-08 10:57 UTC, PowerfulBacon commented
Fails lints, can't be put to testmerge

2025-02-09 10:09 UTC, PowerfulBacon commented
I am happy to throw this on at higher pops once combat mode is merged.

2025-02-09 10:10 UTC, PowerfulBacon commented
Also needs testing evidence to be provided

2025-02-15 08:17 UTC, PowerfulBacon commented
I want to start TMing this on live since it looks really cool, get some testing evidence in

2025-02-15 08:17 UTC, mrmanlikesbt commented
i'll try and get testing evidence tomorrow. no promises tho

2025-02-16 00:16 UTC, Absolucy commented
should prolly make sure to port some of my fixes/qol if you haven't done so already:
- https://github.com/Monkestation/Monkestation2.0/pull/4886
- https://github.com/Monkestation/Monkestation2.0/pull/4893
- https://github.com/Monkestation/Monkestation2.0/pull/5455

i try to keep a list of prs and issues related to bloodsuckers in the ["Bloodsucker Jank" milestone](https://github.com/Monkestation/Monkestation2.0/milestone/2), fwiw

2025-02-16 01:50 UTC, mrmanlikesbt commented
@PowerfulBacon enjoy your testing evidence

2025-02-16 07:53 UTC, PowerfulBacon commented
Good stuff

2025-02-17 20:28 UTC, PowerfulBacon commented
- [ ] Vampires do not have an icon when using the combo HUD. To replicate, press admin > Toggle Combo HUD. You should see an antag icon appear to the top right of all antagonists but it does not show for vampires.

2025-02-17 20:35 UTC, Absolucy commented
![image](https://github.com/user-attachments/assets/ba67cd1e-6d11-41a9-8135-f466940c1964)

no icon in antag prefs (i cleared cache just to make sure)

2025-02-17 21:57 UTC, mrmanlikesbt commented
> no icon in antag prefs (i cleared cache just to make sure)

![image](https://github.com/user-attachments/assets/9cdc2741-72f6-4ee2-995a-77a288fd618c)

could not reproduce on local. but yeah, I see the same on sage. I think someone with the appropriate permission needs to use the Regenerate Asset Cache verb.
cough cough @PowerfulBacon

2025-02-17 22:13 UTC, PowerfulBacon commented
yea, sorry I need to run this on the server

2025-02-18 01:01 UTC, Therealdoooc213 commented
They have no round-end HUD icon from what I can see.

2025-02-18 06:34 UTC, mrmanlikesbt commented
Clans are now chosen by resting in a claimed coffin and powers are chosen via radial menu instead of the previous tgui popup.
Feedback is always appreciated if anybody thinks this should be different

https://github.com/user-attachments/assets/7d029777-e2c0-4c58-a7f8-5b7f9a837e91

2025-02-20 20:24 UTC, mrmanlikesbt commented
instead of using the crafting menu for vampire structures you now use the 'Vampiric Conversion' power on iron to convert it into fleshy mass which is used to make the new vampire structures. I should note however, the new coffins are still made via the crafting menu (except the meat coffin)

https://github.com/user-attachments/assets/9fbb6cd7-3bd0-4ed5-b612-1c82d0cbcc79

2025-02-23 17:55 UTC, PowerfulBacon commented
Conflicting.

2025-03-02 05:12 UTC, mrmanlikesbt commented
I revamped the Vampire UI. Suggestions and criticism are accepted as always.

https://github.com/user-attachments/assets/ae70f968-5db7-4d55-bd2b-add125a5a657

2025-03-08 20:57 UTC, PowerfulBacon commented
- Feeding on monkeys is broken.
- Apparently you forgot to port the cooldown for malkavian ramblings.

2025-03-08 21:47 UTC, Absolucy commented
bloodsucker hud does not show vassals either

2025-03-08 22:00 UTC, Absolucy commented
also would be nice if there was the examine for vampires/vassals that let them tell who's some other vampire's vassal

2025-03-08 22:45 UTC, DatFrostys commented
Nosferatus aren't shown as disfigured, not sure about having a bad back though. Same for the favorite vassal

2025-03-09 04:57 UTC, mrmanlikesbt commented
> Reportedly drinking blood does not work

Can I get some elaboration on this? If you could tell me the reporting person's Discord that would be good

2025-03-10 18:57 UTC, mrmanlikesbt commented
I've fixed all of the above things. I should note, however that I can't really implement the hud system the way it's meant to be without having first ported
- https://github.com/BeeStation/BeeStation-Hornet/pull/10897
In the meantime, examine vassals to see if they are yours/another vampire's. The same goes for vassals examining vampires.

2025-03-13 19:19 UTC, JackieOTheWisp commented
I don't want our halloween gimmick species dropped, isn't there any other way?

2025-03-13 19:20 UTC, JackieOTheWisp commented
I like the idea of this antag, it would be fun to see, but I like the idea of non-antag vampires around halloween to play as.

2025-03-14 20:22 UTC, Absolucy commented on code/modules/antagonists/vampire/powers/targeted/feed.dm
> +		if(!human_target.dna?.species || !(human_target.mob_biotypes & MOB_ORGANIC))
check for `TRAIT_NOBLOOD` maybe?

2025-03-14 20:22 UTC, Absolucy commented on code/modules/antagonists/vampire/powers/targeted/feed.dm
> +		if(!human_target.dna?.species || !(human_target.mob_biotypes & MOB_ORGANIC))
check for `NOBLOOD in human_target.dna.species.species_traits` too, maybe?

2025-03-14 21:28 UTC, Absolucy commented on code/modules/antagonists/vampire/daylight_vampire.dm
> +	if(!owner || !owner.current)
```suggestion
	if(!owner?.current)
```

2025-03-15 00:42 UTC, Absolucy commented on code/modules/antagonists/vampire/datum_vampire.dm
> +		clan_data["icon"] = icon2base64(icon(my_clan.join_icon, my_clan.join_icon_state, frame=1))
PLEASE NO, JUST MAKE A PROPER SPRITESHEET OR WAIT UNTIL DMICON IS MERGED

2025-03-15 00:46 UTC, mrmanlikesbt commented on code/modules/antagonists/vampire/datum_vampire.dm
> +		clan_data["icon"] = icon2base64(icon(my_clan.join_icon, my_clan.join_icon_state, frame=1))
:trollface:

2025-03-15 00:51 UTC, mrmanlikesbt commented on code/modules/antagonists/vampire/datum_vampire.dm
> +		clan_data["icon"] = icon2base64(icon(my_clan.join_icon, my_clan.join_icon_state, frame=1))
i am gonna need some elaboration as to why this is a bad practice if you want it changed though

2025-03-15 00:53 UTC, Absolucy commented on code/modules/antagonists/vampire/datum_vampire.dm
> +		clan_data["icon"] = icon2base64(icon(my_clan.join_icon, my_clan.join_icon_state, frame=1))
because `icon2base64` technically _writes to the filesystem_, and then the client has to send a big chunk of base64 - so it is NOT a very fast proc. even with `ui_static_data`, not a good practice.

2025-03-15 16:24 UTC, Bieyes commented
Please do not re-add none-antag vampires, they're too unbalanced..

2025-03-15 16:53 UTC, JackieOTheWisp commented
please don't remove the vampire species! I love playing vampire around halloween!

2025-03-15 17:55 UTC, Therealdoooc213 commented
> please don't remove the vampire species! I love playing vampire around halloween!

This would make it INCREDIBLY confusing. Also, powergaming race.

2025-03-16 01:09 UTC, Rukofamicom requested changes
Alright, I've voiced some of these in discord before but not properly on the PR. I think this is a great general concept, but it needs some polish particularly in the form of simplification. I have a few requests regarding this:

1. Clans are an unnecessary complication and should be removed, this antag does not need to be four nearly distinct antagonists in a trench coat. Let players have their choice of these as defining powers while limiting the total number of powers and/or progression in a different way. I'll leave exactly how you manage this up to you except for what I've outlined below

2. Frenzy should make all vampires stun immune as an innate feature of the antagonist

3. Vent crawling is part of what makes the Halloween race you're removing such a massive nuisance and should not be part of the basic skillset any vampire has. Bat transformation should be one of the optional skills and should still allow this, but should also drop all items on use to narrow the number of cases where it is useful (such as for getting away, or a quick infiltration for sabotage/feeding, but not for theft). Bat transformation being unlocked should also unlock it for use by the favorite thrall as part of the ability. 

4. The sol cycle is somewhat flavorful, but I feel the mechanics surrounding it are more disruptive than fun. Vampires should heal in their coffin and gain a heal over time for a period of time after leaving it but not heal passively at all times. Vanishing act should either become one of the optional abilities, or be tied to the presence of this healing effect and only becoming usable when the vampire is in need of another rest to renew it. If you wish to retain the various effects that sole currently triggers, have them trigger upon entering the chapel

I am not 100% forcing these as I haven't taken the time to thoroughly discuss these with others, but I do feel like this antagonist suffers from being excessively complicated to learn both as a player of one and a player against them.

2025-03-16 22:46 UTC, DatFrostys commented
Making and upgrading a fav vassal as a ventrue made me mute during two separate rounds. Unsure what causes this, my guess is that I may enter some bugged frenzy from being hungry which prevents me from speaking at all

2025-03-17 17:02 UTC, JackieOTheWisp commented
> Also, powergaming race.

I like to make a gay vampire character around halloween because it's silly, sue me lol /j

I'm going to accept that my silly halloween guy will be gone, honestly. I do like this antag, anyways lol

2025-03-31 11:23 UTC, Rukofamicom requested changes, later dismissed
Alright, I told you I was open to discussion and had nearly the entirety of my last change request rejected as a whole. These are my bare minimum blocking requests before I continue testing and observe how players interact with vampires again. 

* No vampire should have the ability to ventcrawl without dropping all of their items. This is an incredibly frustrating mechanic that should not be brought over from the old race. This effectively means Nosferatu needs major changes or it will probably be too weak for your design.

* I also don't really like that one of the clans entire flavorful purpose is to hunt down other vampire players when they already messed up. I don't have a solution for this so this is not a request since you want to insist on keeping the clans I'm just raising a concern about it. They could punish the other vampire in some way such as hunting their favored thrall down, but I don't like the encouraging of the antags to off each other entirely.

* Bat transformation is something that should be preserved from the original race, but it should drop your items to the ground upon use per the above point. All vampires should have the ability to do this transformation and being hit out of bat form (which is harder to do than it seems like it would be if you preserve their speed) should send the vampire into torpor. 

* At minimum remove the obvious orange glow around vampires during Sol. We should not have mechanics that encourage the flipping of a valid-switch and flag someone as "HEY SHOOT/STAB/TOOLBOX ME NOW". I still feel sol should be removed as a mechanic in general, but I'm not going to force it.

2025-05-04 18:12 UTC, PowerfulBacon commented
Ready for TM?

2025-05-07 02:24 UTC, mrmanlikesbt commented
Major changes since last TM

Slight QoL improvements for vampire powers.


Any vampire indicators for Sol have been removed.


Slight rebalancing of the Brawn ability, it has a level of RNG to it now and does slightly less damage


The Nosferatu clan has been replaced with the Brujah clan. Upon joining, the vampire will:

- Break the masquerade
- Gain an improved version of the brawn power
- Gain an objective to convert a head of staff into a discordant vassal (a vassal that is not loyal to the vampire but instead aims to cause anarchy)

2025-05-09 03:05 UTC, Rukofamicom commented
Pulling the TM

Targetted abilities (including the ability to bite) are currently broken. 
Trying to use any ability which requires a target results in an error. 

Multiple players claiming this same bug: 

```
Whenever I activate it, it said "select a target" but whenever I clicked somebody, it said "already using a targeted power" 
```

2025-05-09 03:06 UTC, mrmanlikesbt commented
> Trying to use any ability which requires a target results in an error.

is there a runtime?

2025-05-09 03:21 UTC, RDS88-beeman commented
The vampire and thrall antag symbols show up on inspect, at the bottom of the inspect thing. I don't know what causes it, but it might be because I had a secHUD on.
![image](https://github.com/user-attachments/assets/cb1ce89b-e371-4850-9a47-d08aa1c3c72c)
![image](https://github.com/user-attachments/assets/295a6ada-5e5d-42d9-93b6-7b1c8be0211e)

2025-05-09 03:33 UTC, mrmanlikesbt commented
OOPS, my bad. Both of these are fixed now, @Rukofamicom 

https://github.com/user-attachments/assets/9b68064d-3782-4461-a8ee-eeab073df440

2025-06-01 11:56 UTC, TsunamiAnt commented
im gonna be honest, it's really weird that it's the malkavians that enforce masquerade not the ventrue

2025-06-01 12:03 UTC, TsunamiAnt commented
oh also i noticed my bleed wasn't healing as vamp, im not sure if that's intentional, but i had to use bandages.

2025-07-08 19:44 UTC, TsunamiAnt commented
Bugs noticed during recent testmerge:
Power selection menu in coffin disappears. I quote from the ticket:
> "So It told me "You have the opportunity to grow more ancient. Select a power to advance your Rank." and gave me the list, but while I was still in the coffin it said "You have the opportunity to grow more ancient. Select a power to advance your Rank." again and then the radial menu disappeared without me selecting anything."
Leaving and returning to the coffin fixed it.

When dynamic tried to spawn the latejoin vampire breakout, it was correctly applied to the player but this warning came in chat:
XXX was selected by the Vampire Breakout ruleset, but couldn't be made into a Vampire.

When a ventrue vampire made another vampire they apparently got muted and were unable to talk the rest of the round.

Notes on stakes:
When attempting to stake a vampire, the staking process begins but the stake does not embed. When the vampire subsequently returned to their coffin with the teleport, leaving behind their gear, they were stuck with 0 blood in a constant frenzy loop until we rescued them by opening the coffin from outside and adding blood to them.*

After some experimenting, stakes only embedded when i was sleeping due to morphine. I think as long as you can get them on the ground for long enough, you should be able to stake them. I also think you shouldn't even be able to START the staking process if you are not in a position where the staking is actually possible.

Also, the stakes quickly fall out of their chests anyways.

Also also, you can spam stakes and it makes the squelch every time. Is it possible to only allow one do_after at a time?

Notes:
It is likely rare-y to get more than one vampire in a round, and **even rarer** that one of them chooses malkavian. This makes vampire-related violence against masquerade breakers very unlikely. Thus:
### Killing masquerade breakers should be an objective of every vampire, always.

2025-07-22 17:01 UTC, TsunamiAnt commented
Bugs spotted during recent TM:

With the new cuff timer changes, vassalizing people can be a crapshoot.

When someone used max level dominate on me, i was only stunned and blinded for a time. I later got critted, at which time i became a vassal for a split second and was then cured immediately.

2025-07-23 13:31 UTC, TsunamiAnt commented
entirely unrelated, but would it be possible to tell the curator when sol starts and ends too?

Also give them the chaplains witchhunter kit!

2025-07-23 17:58 UTC, TsunamiAnt commented
More notes:

Blood bolt is described as being able to open "Doors/lockers" but does not open doors.

Stakes:

Staking now appears to work under the following conditions:
The vampire was aggro grabbed.
The vampire is not just on the ground, but also KO like stamina or sleepiness.

By WORK i mean that staking:
Does do the do_after and sound.
Still appears to only have a small chance to actually insert the stake at the end of it, like, 9 times out of 10 the stake just won't embed.
WHEN the stake does embed, it neither hinders any powers, nor does it stay inside. It will fall out by itself after a small amount of time later.

2025-08-01 20:10 UTC, TsunamiAnt commented
I have not noticed any bugs with the current testmerge.

A persistent """complaint""" seems to be the limitlessness of vassals. Would it be possible to restrict max vassals to 1 every 10 levels?

2025-08-01 21:32 UTC, mrmanlikesbt commented on code/modules/antagonists/vampire/conversion_vampire.dm
> +		return FALSE
Temporary fix

```suggestion
```

2025-08-08 11:59 UTC, PowerfulBacon commented
Ready for TM/merge?

2025-08-08 18:54 UTC, mrmanlikesbt commented
> Ready for TM/merge?

soon

2025-08-08 23:20 UTC, Rukofamicom approved these changes

2025-08-09 13:15 UTC, PowerfulBacon approved these changes

2025-08-10 21:08 UTC, Dejaku51 requested changes
Runtimes in those places (mr.man has full runtimes)
runtime error: Cannot read null.vampire_blood_volume
runtime error: cannot read from list
runtime error: Invalid/unsupported color format argument in color_to_full_rgba_matrix()
runtime error: illegal: sqrt(-10.000000)
runtime error: Cannot read "Ladies\' Strapless".name
runtime error: Cannot execute null.playsound local().

2025-08-13 18:31 UTC, Dejaku51 commented
```
[18:19:08] Runtime in code/modules/antagonists/vampire/life_vampire.dm, line 160: undefined variable /mob/living/simple_animal/hostile/retaliate/bat/vampire/var/internal_organs
proc name: heal vampire organs (/datum/antagonist/vampire/proc/heal_vampire_organs)
src: Vampire (/datum/antagonist/vampire)
call stack:
Vampire (/datum/antagonist/vampire): heal vampire organs()
Vampire (/datum/antagonist/vampire): torpor end()
Vampire (/datum/antagonist/vampire): check end torpor()
Vampire (/datum/antagonist/vampire): on sol end(Sol (/datum/controller/subsystem/sunlight))
Sol (/datum/controller/subsystem/sunlight): SendSignal("comsig_sol_end", /list (/list))
Sol (/datum/controller/subsystem/sunlight): fire(0)
Sol (/datum/controller/subsystem/sunlight): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop(2)
Master (/datum/controller/master): StartProcessing(0)
```
Also you can get stuck as a transformed bat, when you die as a bat your body drops then second later it turns into alive bat

2025-08-16 19:17 UTC, ro5490 commented
Could sync up the day/night cycle with in-game dayshift nightshift lighting cycles, for immersion

2025-08-16 20:03 UTC, BotTierPC commented
There might be a bug where a vampire inside a coffin, Can be sold on the cargo shuttle and then sent to the centcom z level (even if walled in) ?

2025-08-17 17:53 UTC, Dejaku51 approved these changes

2025-08-17 17:58 UTC, merged