[PORT] Refactors most spans into macros
BeeStation/BeeStation-Hornet pull request #12093
Opened 2024-12-28 01:13 UTC by mrmanlikesbt

## About The Pull Request

Converts most spans to macros. I used regex to convert existing spans and generate the macros defined in spans.dm

- https://github.com/tgstation/tgstation/pull/59645
- https://github.com/tgstation/tgstation/pull/59685

## Why It's Good For The Game

It's annoying any time you want flavortext to type out <span class='... etc.
this adopts the practice that basically every tg based server has had for years making code a ton easier to read and saving contributors' time.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: mrmanlikesbt, Watermelon914, Timberpoes
refactor: Refactors how spans are done in code.
/:cl:

2024-12-28 02:03 UTC, XeonMations commented
The last time this was suggested, this happened: https://github.com/BeeStation/BeeStation-Hornet/pull/4971

IMO this should be a thing, godspeed man.

2024-12-28 02:54 UTC, Tsar-Salat requested changes, later dismissed
> I used regex to convert existing spans

If you use regex or another tool in PRs, the string you searched with should be included in the body

2024-12-28 03:26 UTC, mrmanlikesbt commented
I updated the PR to include the code used for conversion

2024-12-28 06:06 UTC, EvilDragonfiend commented
I don't like this but reasoning makes sense.

2024-12-28 17:26 UTC, llol111 commented
Im not coderbrained enough to know (or care, tbh) about the backend coder side changes here.
But im curious how this will affect adminbuss.

Right now, we admins can use the "<span class='... etc." like an HTML command in game  to make text appear in one of the span classes, giving it the large size and rainbowy blink of ratvars text for instance, or even just making it slightly larger and red with spann class userdanger.
How, if at all, will this be possible if span classes are not used anymore

2024-12-28 19:56 UTC, Tsar-Salat commented
> How, if at all, will this be possible if span classes are not used anymore

Span classes are basic html. It is not that they will not work anymore, it's just writing them in the code is simplified.

Writing the full wrapper out will still work both in-game and code

2024-12-29 02:18 UTC, Tsar-Salat requested changes
I plan to approve this, but there's still quite a few remaining unwrapped text remaining.

![image](https://github.com/user-attachments/assets/d36b2641-ddf9-4381-8ff5-f3fd7237e017)

Obviously there are going to be cases where you cannot easily convert to the macro, but stuff like to_chat procs are trivial.

![image](https://github.com/user-attachments/assets/87d25259-3847-488b-af70-80bcb6404215)

When you knock a few more out, req my review again

2024-12-29 06:18 UTC, itsmeow commented
i like these because they enforce html syntax for a very heavily used tag. people make mistakes on these often enough that having a macro to enforce the syntax is useful

2024-12-30 09:10 UTC, mrmanlikesbt commented
I went ahead and converted almost all of the remaining spans. The spans I didn't convert were either incredibly obscure or would require quite a bit of refactoring to use span macros (take **scanners.dm** for instance). 

**role_preferences.dm** wasn't converted because it's loaded before the span macros.

All in all, the only spans I feel should be converted, but aren't, are in **_drone.dm**. I'm not going to get into it- but I tried and failed. The people at tg clearly didn't think it was worth the effort because they also didn't bother to use macros.

2024-12-30 10:56 UTC, EvilDragonfiend commented
Your regex is missing underbar

2024-12-30 17:52 UTC, PowerfulBacon commented
I hate these but I guess we don't really have the choice with TG stuffing these down our throats

2025-01-06 18:38 UTC, Tsar-Salat approved these changes
remaining html is about 300 lines, which is much better than the last review.

I saw you duped two definitions which conflicted open dream lints. I took the opportunity to fix it.

This looks good.

2025-01-06 19:01 UTC, Tsar-Salat commented on code/__DEFINES/span.dm
> +#define span_tooltip(str) ("<span class='tooltip'>" + str + "</span>")
This is incorrect, tooltips spans hook into tgui on TG. Recheck this.

Also, tooltiphover doesnt seem to be used anywhere. Unused spans should be deleted.

2025-01-23 14:35 UTC, Tsar-Salat commented
From local testing, all the spans I tested worked correctly.

I still put it on overnight for a testmerge, and it passed. 

I asked also for maintainer comment and the discussions brought up were resolved. The only concern I have is with making sure contributors are using only the macros, but I dont think that is going to be a long term problem. New spans being added is an exceedingly rare event, I think we just need to make sure current open PRs use the new macros, and everything will come together in future prs.

The only improvement I can think of is testing for enforcing the macros, but I do know there are places in the code where enforcing the macro would be unfeasible or would not work. A test is pointless with false positives, so I think its fine.



> I hate these but I guess we don't really have the choice with TG stuffing these down our throats

I am taking this as headdev approval.

2025-01-23 16:37 UTC, merged

2025-01-24 21:42 UTC, PowerfulBacon commented
![image](https://github.com/user-attachments/assets/51669885-627d-438d-aebe-65a84c0553fc)

Was this change manual or has the script been invalidly converting things and removing spans?

2025-01-24 21:44 UTC, mrmanlikesbt commented
script fuckup