Fixes Winter Echo problems
BeeStation/BeeStation-Hornet pull request #12112
Opened 2024-12-31 12:56 UTC by ClownMoff

## About The Pull Request
Adds a row of tiny fans in the entrance of Echo so the station doesn't slowly turn blue, nerfs the insanely amount of health hostile trees have

## Why It's Good For The Game

Not having the station covered in blue due to cold air is good, trees not having just 100 health less than a space dragon is also good, specially when they can randomly spawn and hit people that just walked out of the station.

https://github.com/BeeStation/BeeStation-Hornet/issues/12039

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Added a row of tiny fans on Winter Echo to prevent cold from coming in.
balance: Hostile trees now have 100 health instead of 250
/:cl:

2024-12-31 13:21 UTC, Dejaku51 commented
i suggest using the holofield thingy added by rkz instead

2024-12-31 13:39 UTC, Dejaku51 commented
also this changes atmos related things so

2024-12-31 17:38 UTC, Rukofamicom requested changes
https://github.com/BeeStation/BeeStation-Hornet/pull/11550

I second the request for these to be used instead of tiny fans. There should be no new instances of tiny fans.

2025-01-01 13:34 UTC, ClownMoff commented
I don't understand how the holofields work and the game is breaking atmoswise at the sight of me messing anything, literally  the best curse of action would be removing Winter Echo as is a map until it's fixed, it has some very important flaws like random megafauna that kills you and an atmos that doesn't work properly

![image](https://github.com/user-attachments/assets/17282148-8d34-4ae4-822c-405ef0d9c475)

2025-01-01 14:48 UTC, Dejaku51 commented
that runtime is unrelated, on how to use holofields you can look at fland which uses them

2025-01-01 18:13 UTC, Dejaku51 commented
![image](https://github.com/user-attachments/assets/ebae7b52-7e6d-474d-8a50-d403da9e161c)

2025-01-01 23:57 UTC, ClownMoff commented
It's a temporary fix for a teporary map, whats the harm? It saves people time as it does it automatically with no one having to activate it, maybe people don't even notice it or know its there, let's just use tiny fans for this one thing, normal Echo will eventually come back

2025-01-21 23:53 UTC, MCterra10 commented
I would argue that honestly, the fans make more logical sense in this instance; it's not really maintaining pressure of an area vs space (where holofields make sense), it is protecting an area from temperature changes.

This is far more analogous to shopping malls in real life that use a big air conditioner at the doorway to create a "wall of air" to shield against the hot or cold air from outside blowing in.

Hell, you could even revamp the fans into that as a concept, although that would be far more problematic than this PR for the LINDA work.

2025-02-14 01:52 UTC, closed without merging