Gives nukies more telecrystals
BeeStation/BeeStation-Hornet pull request #12110
Opened 2024-12-31 02:14 UTC by mrmanlikesbt

## About The Pull Request

Nukies now get 0.5 TC per living player (rounded to the closest multiple of 5)
If you declare war over 30 population, nuclear operatives are given an additional 0.5 TC per living player.
Syndicate reinforcements no longer get TC on war being declared

## Why It's Good For The Game

Nukies currently get a base 30 TC + 0.2 TC per living player (rounded to the closest multiple of 5). If they declare war <ins>and the pop is over 50</ins> they also get an additional 280tc that is split among the team. (56 TC per person with a team of 5)

Nuclear operatives are meant to be an elite strike force with the sole purpose of destroying the station. They should have tons of resources given the relatively small size of their team compared to the crew.

If you do end up declaring war and the population isn't **over 50** you are absolutely going to lose unless you have John /tg/ McRobust on your team. Given the 15-minute delay the infiltrator has, this gives the crew ample time to: order a buttload of guns, set up barricades in the hall, give everyone AA, and finally arm everyone.

Considering how often nukies fail and how **INCREDIBLY RARE* 50 pop is. I believe nukies really need a buff to make them a threat again and not 

## Testing Photographs and Procedure

<details>
<summary>Graphs</summary>

## Current Telecrystal distribution (with a team size of 5)

![chart_old_nowar](https://github.com/user-attachments/assets/330831da-fae5-47b0-b6d7-d139559181a8)

![chart_old_war](https://github.com/user-attachments/assets/783f7c0e-3389-4891-b791-0dd51870709c)

## Proposed Telecrystal distribution

![chart_new_nowar](https://github.com/user-attachments/assets/3daba79f-c495-4c47-8277-f9db4ff46f5c)

![chart_new_war](https://github.com/user-attachments/assets/a439cde1-1e9f-434a-9958-623784fe4458)

</details>

## Changelog
:cl:
balance: rebalanced something
tweak: tweaked a few things
/:cl:

2024-12-31 17:41 UTC, Rukofamicom approved these changes

2024-12-31 22:33 UTC, mrmanlikesbt commented
@Rukofamicom do you think the war min pop should be changed to 25? A trend I notice on rounds is usually 25ish people ready up then ~10 join the round like 2 minutes later

2024-12-31 22:36 UTC, mrmanlikesbt commented
Nevermind. I forgot war tc is given based on the pop at the time of declaration- not roundstart.

2025-01-03 20:29 UTC, Tsar-Salat requested changes
@mrmanlikesbt 

Include the alert to tgui_alert conversions of https://github.com/BeeStation/BeeStation-Hornet/pull/12122 and I will merge this PR, and close the other.

Its preferable to reduce as many html inputs as we can.

2025-01-03 20:45 UTC, Tsar-Salat approved these changes

2025-01-03 20:58 UTC, merged