[PORTS]: /tg/station Faction defines.
BeeStation/BeeStation-Hornet pull request #12113
Opened 2024-12-31 17:43 UTC by Therealdoooc213

## About The Pull Request

Go read the main PR's about the pull request, linked below.

PORTS

- https://github.com/tgstation/tgstation/pull/66318
- https://github.com/tgstation/tgstation/pull/73681 MAIN PR!
- https://github.com/tgstation/tgstation/pull/71963 (mainly just FACTION_NEUTRAL)

## Why It's Good For The Game

Go read the main pr's why its good for the game, linked above.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

Pine trees interacting with mobs on echostation surface
https://github.com/user-attachments/assets/16ae9fcf-2cfa-452b-94eb-b56fa8c2289c
Cyborg walking past AI's turrets
https://github.com/user-attachments/assets/811360c2-8bb7-4cef-a3df-4658456dd9c6

</details>

## Changelog
:cl: therealdoooc, Profakos, BongoDongo2000, Jacquerel
code: converts faction strings to defines
/:cl:

2024-12-31 18:31 UTC, Tsar-Salat commented
> Go read the main pr's why its good for the game, linked above.

This section should still be included in the PR if it's easily explained.

If the benefits require technical details and reasoning, sure you can say "TG included technical details in their pr", but it's preferable to at least give 2 sentences why it's good here.

2025-01-02 22:21 UTC, Tsar-Salat commented
@Therealdoooc213 I think your centcom map broke file changes. 

This can be fixed by resetting the .dmm file to master, committing without hooks, making your changes again, then committing again.

It can be annoying, but it should prevent weird mapconflicts

2025-01-18 18:32 UTC, Tsar-Salat approved these changes

2025-01-22 16:12 UTC, Dejaku51 commented
Add defines to those:
code/game/machinery/porta_turret/portable_turret.dm:866
code/game/objects/items/holy_weapons.dm:710
code/modules/spells/spell_types/construct_spells.dm:341
code/modules/research/xenobiology/xenobiology.dm:131
code/modules/research/xenobiology/xenobiology.dm:129
code/modules/research/xenobiology/xenobiology.dm:119
code/modules/religion/sects/plant_sect.dm:154
code/modules/religion/sects/carp_sect.dm:20
code/modules/mob/living/simple_animal/hostile/statue.dm:231
code/modules/mob/living/simple_animal/hostile/illusion.dm:39
code/modules/mob/living/simple_animal/bot/bot.dm:1195
code/modules/mob/living/silicon/robot/robot_modules.dm:659
code/modules/mob/living/silicon/robot/robot_modules.dm:664
code/modules/mining/lavaland/necropolis_chests.dm:771
code/modules/mining/equipment/lazarus_injector.dm:43
code/modules/clothing/outfits/standard.dm:136
code/modules/clothing/head/costume.dm:168
code/modules/clothing/head/costume.dm:163
code/modules/antagonists/space_dragon/space_dragon.dm:99
code/modules/antagonists/space_dragon/space_dragon.dm:88
code/modules/antagonists/cult/cult.dm:144
code/modules/antagonists/cult/cult.dm:116
code/modules/antagonists/clock_cult/servant_of_ratvar.dm:67
code/modules/antagonists/clock_cult/servant_of_ratvar.dm:80
code/modules/antagonists/abductor/equipment/gland.dm:275
code/modules/antagonists/abductor/equipment/gland.dm:142
code/modules/antagonists/abductor/equipment/gland.dm:137
code/modules/antagonists/abductor/equipment/gland.dm:68
code/modules/antagonists/abductor/equipment/gland.dm:25
code/game/objects/items/holy_weapons.dm:710

2025-01-22 16:17 UTC, Dejaku51 requested changes
Include those:
code/game/machinery/porta_turret/portable_turret.dm:866
code/game/objects/items/holy_weapons.dm:710
code/modules/spells/spell_types/construct_spells.dm:341
code/modules/research/xenobiology/xenobiology.dm:131
code/modules/research/xenobiology/xenobiology.dm:129
code/modules/research/xenobiology/xenobiology.dm:119
code/modules/religion/sects/plant_sect.dm:154
code/modules/religion/sects/carp_sect.dm:20
code/modules/mob/living/simple_animal/hostile/statue.dm:231
code/modules/mob/living/simple_animal/hostile/illusion.dm:39
code/modules/mob/living/simple_animal/bot/bot.dm:1195
code/modules/mob/living/silicon/robot/robot_modules.dm:659
code/modules/mob/living/silicon/robot/robot_modules.dm:664
code/modules/mining/lavaland/necropolis_chests.dm:771
code/modules/mining/equipment/lazarus_injector.dm:43
code/modules/clothing/outfits/standard.dm:136
code/modules/clothing/head/costume.dm:168
code/modules/clothing/head/costume.dm:163
code/modules/antagonists/space_dragon/space_dragon.dm:99
code/modules/antagonists/space_dragon/space_dragon.dm:88
code/modules/antagonists/cult/cult.dm:144
code/modules/antagonists/cult/cult.dm:116
code/modules/antagonists/clock_cult/servant_of_ratvar.dm:67
code/modules/antagonists/clock_cult/servant_of_ratvar.dm:80
code/modules/antagonists/abductor/equipment/gland.dm:275
code/modules/antagonists/abductor/equipment/gland.dm:142
code/modules/antagonists/abductor/equipment/gland.dm:137
code/modules/antagonists/abductor/equipment/gland.dm:68
code/modules/antagonists/abductor/equipment/gland.dm:25
code/game/objects/items/holy_weapons.dm:710

2025-01-24 10:31 UTC, Dejaku51 approved these changes

2025-01-24 10:39 UTC, merged