Ports Superglue and Bluespace Compression device
BeeStation/BeeStation-Hornet pull request #1227
Opened 2020-02-22 15:46 UTC by zeskorion

## About The Pull Request
Ports superglue and bluespace compression device, both available as traitor items

superglue can be used to make any item Nodrop, once. It costs 2 tc

bluespace compression device costs 5 tc, and can reduce an item by one size five times, which can be replenished with bluespace crystals. It cant compress storage items (which, due to our code, means most exosuits cant be compressed either)
## Why It's Good For The Game
cool fun items yay

## Changelog
:cl:
add: Super Glue
add: Bluespace Compression device
imagedel: icons for both
/:cl:

2020-02-22 15:48 UTC, MarkSuckerberg commented
Let me just shrink 5 maxcaps and hide them in my bag.

2020-02-22 15:59 UTC, MarkSuckerberg requested changes

2020-02-22 15:59 UTC, MarkSuckerberg commented on code/game/objects/items/devices/compressionkit.dm
> +	var/mode = 0
delete this too since ya don't need it

2020-02-22 15:59 UTC, MarkSuckerberg commented on code/game/objects/items/devices/compressionkit.dm
> +	to_chat(user, "<span class='notice'>Use in-hand to swap toggle compress/expand mode (expand mode not yet implemented).</span>")
this too, since it's useless info

2020-02-22 16:10 UTC, zeskorion commented
> Let me just shrink 5 maxcaps and hide them in my bag.

or, you know, make a bag of holding or bluespace body bag...

2020-02-24 17:46 UTC, merged

2024-10-31 23:20 UTC, Tsar-Salat commented
> Ports

????