Most leather products can now be cut back up into leather
BeeStation/BeeStation-Hornet pull request #1340
Opened 2020-03-12 05:15 UTC by Victor239

## About The Pull Request
Use a sharp object or wirecutters to cut most leather products back into leather. Leather satchels and toolbelts are the only ones you cannot cut up.

## Why It's Good For The Game
Similar interaction as cutting up cloth products back into cloth, makes sense that it would be possible for leather also. 

## Changelog
:cl:
add: You can now cut most leather products back into leather.
/:cl:

2020-03-23 17:06 UTC, qwertyquerty commented
I do not like how this is implemented. Your verdict @ike709 ?

2020-03-23 17:15 UTC, ike709 commented
@qwertyquerty I agree.

2020-03-23 19:39 UTC, Victor239 commented
It's basically the same as how it's implemented for cutting cloth products back into cloth.

2020-03-24 05:42 UTC, qwertyquerty commented
In my opinion, we need a scrapable component, that lets anything with it be scrapped for materials with specific tools, or something of the likes.

2020-03-29 19:02 UTC, qwertyquerty requested changes
Do that

2020-04-08 16:56 UTC, qwertyquerty commented
Doesn't seem like he's going to be doing that

2020-04-08 16:56 UTC, closed without merging