Minor TGUI Fixes
BeeStation/BeeStation-Hornet pull request #1372
Opened 2020-03-18 10:24 UTC by Cenrus

## About The Pull Request

adds tooltips to cargo crates
buffer can make 0.1u pills
crew monitor vitals square fix

## Why It's Good For The Game

fixes. qwerty pls update tgui it's been 4 months

## Changelog
:cl:
fix: Fixes crew monitor vitals square
fix: Chem buffers can make 0.1u pills
fix: Cargo crates now show tooltips
/:cl:

2020-03-18 10:28 UTC, Cenrus commented
![Capture](https://user-images.githubusercontent.com/31044876/76951204-30a29080-6903-11ea-82a9-ca1f8f328cdd.PNG)

If anyone knows how to fix this, please tell me.

2020-03-18 10:59 UTC, Cenrus commented
fixeeeed

2020-03-19 16:13 UTC, Crossedfall requested changes
Please link to the original PR(s). Properly cherry-picking the commits would also be preferred. Ping me over discord if you need help.

2020-03-20 15:22 UTC, Crossedfall approved these changes

2020-03-20 15:22 UTC, merged