Name/Occupation over announcement
BeeStation/BeeStation-Hornet pull request #1373
Opened 2020-03-18 14:22 UTC by Cenrus

Displays the name and job of whoever is announcing over station comms.

Allows you to identify who is spamming the radio with WGW.

:cl:
add: The name and job of the announcer now appear below priority messages.
/:cl:

2020-03-18 16:49 UTC, MarkSuckerberg commented
finally

2020-03-19 16:11 UTC, Crossedfall requested changes
Since this seems like a relatively small tweak, can you please properly cherry-pick the commit that you're porting? Also, can you provide a link to the original PR?

2020-03-20 17:51 UTC, Cenrus commented
not sure if I can cherry pick oracle any more, but I provided a link and included the original author in the cl

2020-03-20 19:21 UTC, Crossedfall commented
Aye, cherry-picking works even if the source is archived. But, I think this will suffice for now. In the future, please try to cherry-pick commits in a way that preserves authorship. :)

2020-03-23 17:18 UTC, qwertyquerty commented
Would it not be a better idea to use the name and job of their ID?

2020-03-23 20:30 UTC, Cenrus commented
![image](https://user-images.githubusercontent.com/31044876/77360356-1d4d5600-6d45-11ea-99e3-ec24d97db0d4.png)

2020-03-26 16:34 UTC, ModDownloading commented
I think it should use the name and job of whoever the console is signed in as, make some shenanigans for people who don't log out.

2020-03-29 19:07 UTC, qwertyquerty requested changes
Make it use the name of whoever is signed in

2020-04-06 00:25 UTC, ike709 commented
Also conflicts.

2020-04-09 00:51 UTC, qwertyquerty commented
Seemingly abandoned by author

2020-04-09 00:51 UTC, closed without merging