added another religon
BeeStation/BeeStation-Hornet pull request #1523
Opened 2020-04-12 21:08 UTC by nikk735

## About The Pull Request

adds Taoism, adds a slice of gondola meat into your bag if you choose Taoism 
also removed anti gondola propaganda

## Why It's Good For The Game

we just needed to have a gondola religion its completely necessary for game play 

## Changelog
:cl:
add gondola religon
/:cl:

2020-04-12 21:17 UTC, St0rmC4st3r commented on code/modules/jobs/job_types/chaplain.dm
> +			B.deity_name = pick("Gondola")
You disgust me.

2020-04-12 21:18 UTC, St0rmC4st3r requested changes

2020-04-12 21:18 UTC, St0rmC4st3r commented on code/modules/jobs/job_types/chaplain.dm
> +			B.deity_name = pick("Gondola")
```suggestion
			B.deity_name = "Gondola"
```

2020-04-12 21:19 UTC, zeskorion commented
Looks like you just want a way to get roundstart Tranquility

2020-04-12 21:22 UTC, St0rmC4st3r commented
> Looks like you just want a way to get roundstart Tranquility

What if it also gave a ton of krokodil and pax roundstart?

2020-04-12 22:10 UTC, nikk735 commented
zesk you are exactly right

2020-04-12 22:12 UTC, nikk735 commented
i copy paste didnt mean to leave that in

2020-04-12 22:12 UTC, nikk735 commented
there  needs to be a non admin way to start the gondola revolution

2020-04-12 23:32 UTC, zeskorion commented
> there needs to be a non admin way to start the gondola revolution

just go to space

2020-04-13 03:54 UTC, nikk735 commented
> > there needs to be a non admin way to start the gondola revolution
> 
> just go to space

how can a chaplain trying to spread peace and tao go to space?

2020-04-13 04:48 UTC, nikk735 commented
the game is unplayable if you cant eat gondola meat within the first 3 seconds of the round start

2020-04-13 07:58 UTC, zeskorion commented
> the game is unplayable if you cant eat gondola meat within the first 3 seconds of the round start

then make the religion add the reagent to you, not give you gondola steak

2020-04-13 16:37 UTC, nikk735 commented
Well you can’t convert others to the gondola religion then

Sent from my iPhone

> On Apr 13, 2020, at 3:58 AM, zeskorion <notifications@github.com> wrote:
> 
> ﻿
> the game is unplayable if you cant eat gondola meat within the first 3 seconds of the round start
> 
> then make the religion add the reagent to you, not give you gondola steak
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-04-21 02:50 UTC, nikk735 commented
this is kinda a superior idea tho

2020-04-23 00:57 UTC, ike709 commented
Lame PR, plus you can sometimes find a gondola in random maint.

2020-04-23 00:57 UTC, closed without merging