Fixes the express supply console so ghosts can't order shit anymore
BeeStation/BeeStation-Hornet pull request #1524
Opened 2020-04-12 21:21 UTC by ivanmixo

## About The Pull Request

Title

## Why It's Good For The Game
Fixes a bug

## Changelog
:cl:
fix: Fixes the express supply console so ghosts can no longer order stuff/make beacons.
/:cl:

2020-04-20 05:03 UTC, bloons3 commented
Should close https://github.com/BeeStation/BeeStation-Hornet/issues/1337

2020-04-21 19:57 UTC, ike709 commented on code/modules/cargo/expressconsole.dm
> +			if(ishuman(usr) && isliving(usr))
Unnecessary, remove.

2020-04-21 19:57 UTC, ike709 commented on code/modules/cargo/expressconsole.dm
> +			else if(issilicon(usr) && isliving(usr))
Unnecessary, remove.

2020-04-21 20:00 UTC, ike709 requested changes
This really isn't the correct way to go about fixing this.

2020-04-26 07:30 UTC, PowerfulBacon commented
Can there not be 1 is living check at the start?

2020-04-26 08:55 UTC, bloons3 commented
Wouldn't that mess with admin/silicon interaction?

2020-05-02 00:13 UTC, closed without merging