Mob Faction refactor + Lizard wings
BeeStation/BeeStation-Hornet pull request #1616
Opened 2020-04-23 15:59 UTC by Cenrus

https://github.com/tgstation/tgstation/pull/45828
https://github.com/tgstation/tgstation/pull/46037

Liz can now use flight potions for wings. Mob faction application has been improved slightly

![image](https://user-images.githubusercontent.com/31044876/80121111-cd4ff200-8583-11ea-9090-57eeac057858.png)

## Why it's good for the game

Liz with wings

:cl: Nemvar, Wjohnston sprites and Mey Ha Zah for some help getting those sprites into a sane form
add: the flight potion now works with lizards
code: Improved the way factions are applied to species.
fix: Shadowpeople no longer get attacked by faithless.
/:cl:

2020-04-26 00:45 UTC, Cenrus commented
Tested.

2020-05-06 00:28 UTC, ike709 commented
Conflicts.

2020-05-07 17:22 UTC, PowerfulBacon requested changes
Changing species while having wings keeps the effects of the wings, but removes the wing sprite, leading to the person just hovering.

2020-05-12 11:59 UTC, Cenrus commented
Fixed issue with keeping wings.

2020-05-13 12:36 UTC, PowerfulBacon requested changes
Decapitalise proc names

2020-05-13 12:36 UTC, PowerfulBacon commented on code/modules/mob/living/carbon/human/species.dm
> +/datum/species/proc/GiveSpeciesFlight(mob/living/carbon/human/H)
/datum/species/proc/give_species_flight(mob/living/carbon/human/H)

2020-05-13 12:36 UTC, PowerfulBacon commented on code/modules/mob/living/carbon/human/species.dm
> +/datum/species/proc/HandleFlight(mob/living/carbon/human/H)
/datum/species/proc/handle_flight(mob/living/carbon/human/H)

2020-05-13 12:36 UTC, PowerfulBacon commented on code/modules/mob/living/carbon/human/species.dm
> +/datum/species/proc/CanFly(mob/living/carbon/human/H)
/datum/species/proc/can_fly(mob/living/carbon/human/H)

2020-05-13 12:36 UTC, PowerfulBacon commented on code/modules/mob/living/carbon/human/species.dm
> +/datum/species/proc/ToggleFlight(mob/living/carbon/human/H)
/datum/species/proc/toggle_flight(mob/living/carbon/human/H)

2020-05-15 11:53 UTC, PowerfulBacon approved these changes

2020-05-15 13:14 UTC, merged