Medical Kiosk III: The Finale
BeeStation/BeeStation-Hornet pull request #1730
Opened 2020-05-03 13:35 UTC by Cenrus

No more dirty branches, it just works.

:cl: ArcaneMusic, MrDoomBringer for the sprite
add: Medical Kiosks researchable under the Biological technology research node.
/:cl:

2020-05-03 18:40 UTC, ike709 commented
You should add one to pubby if you're adding it to all the other maps.

2020-05-04 13:22 UTC, Cenrus commented
Pubby has one now.

2020-05-06 00:59 UTC, Kmc2000 requested changes
Some things to look at

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +	var/scan_active_1 = FALSE       //Shows if the machine is being used for a general scan.
You should refactor this into something like:
var/scan_state = SCAN_STATE_GENERAL
This is not fun to look at

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +	if (pandemonium == TRUE)
```suggestion
	if (pandemonium)
```

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +	var/pandemonium = FALSE			//AKA: Emag mode.
Could replace this with obj_flags & EMAGGED on emag_act()?

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +	var/default_price = 15          //I'm defaulting to a low price on this, but in the future I wouldn't have an issue making it more or less expensive.
Unecessary, you can do:
initial(price) to get the value of "price" when the object was declared.

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +	var/active_price = 15           //Change by using a multitool on the board.
```suggestion
```

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +/obj/machinery/medical_kiosk/proc/clearScans() //Called it enough times to be it's own proc
ew

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +	if(is_operational())
```suggestion
	icon_state = "[(is_operational()) ? "kiosk" : "kiosk_off"]"
```

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +		user.visible_message("<span class='notice'>[user] snaps [O] onto [src]!</span>", \
What happens if someone walks off with the wand and steals it entirely?

Perhaps you could have the scanner have a sort of "scanner plate" /pressure plate that you walk onto, and then it scans you.

"Please step onto the scanning pad"

This then removes the need to store two patients or whatever.

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +		. += "<span class='notice'>\The [src] has its scanner clipped to the side. Alt-Click to remove.</span>"
```suggestion
		. += "<span class='notice'>\The [src] has its scanner clipped to the side. Alt-Click [src] to remove it.</span>"
```

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +	else
Why alt click to remove the scanner when this has a UI?
Perhaps make it a button on the UI, or give the machine a radial menu?

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +	patient_distance = get_dist(src.loc,altPatient)
```suggestion
	patient_distance = get_dist(get_turf(src),altPatient)
```

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +	else if(patient_distance>5)
```suggestion
	else if(patient_distance > 5)
```

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +	var/max_health = altPatient.maxHealth
I would personally prefer you put all of this in a dict. This is a lot of stats. While not strictly necessary, it'd allow you to a: have multiple patients and dodge concurrency issues (IE, what happens if two people want to scan at the same time, and they both have wands?) and b: make the code a little bit less long.

Something like:
var/list/patients_info = list()
for(patient in patients)
var/list/patient_info() = list()
patient_info["name"] = patient.name
patient_info["bleeding"] = (patient.bleeding) ? "Patient is bleeding" : "Patient is not bleeding"
patients_info[++patients_info.len] = patient_info
data["patients"] = patients_info

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +			if(paying_customer == TRUE)
```suggestion
			if(paying_customer)
```

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/machinery/medical_kiosk.dm
> +		if("beginScan_2")
Weird casing, but OK.
We tend to go with snake_case in SS13, rather than this camelCase you're using

2020-05-06 00:59 UTC, Kmc2000 commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> +	var/new_cost = input("Set a new cost for using this medical kiosk.","New cost", custom_cost) as num|null
I would honestly make this a UI button on the kiosk itself rather than this. Have a "medical authorization" mode which lets you access this.

2020-05-06 07:37 UTC, PowerfulBacon commented
Why are there so many changes to Metastation?

2020-05-06 09:04 UTC, PowerfulBacon requested changes
Make it so you can't buy something that has already been bought, otherwise switching tabs costs money, unless you drop your ID in which case it is now free.

2020-05-11 09:22 UTC, Angustmeta commented
Relevant TG wiki entry to copy from (partly or fully):
https://tgstation13.org/wiki/Machines#Medical_Kiosk

As with most TG ports, I like it if you copy my edits from the TG wiki to Bee wiki.

2020-05-13 14:11 UTC, qwertyquerty commented
@Cenrus oi moment

2020-05-14 10:35 UTC, Cenrus commented
I am away from home for some time and can't fix the conflicts right now.

2020-05-15 13:13 UTC, ike709 commented
@Cenrus Did you fix the thing @PowerfulBacon mentioned?

2020-05-16 13:24 UTC, Cenrus commented
Sounds like an issue with the new UI, I can revert it.

2020-05-16 13:34 UTC, ike709 commented
Nah, all UIs going forward have to be TGUI3.

2020-05-23 00:34 UTC, Cenrus commented
Closing. I'll try fixing the UI and code issues another time.

2020-05-23 00:34 UTC, closed without merging