Adds multi-z support for pinpointers [NSV13 port]
BeeStation/BeeStation-Hornet pull request #1874
Opened 2020-05-25 21:00 UTC by covertcorvid

## About The Pull Request
Adds "above" and "below" icons to pinpointers and code for using them

## Why It's Good For The Game
Helps make multi-z more viable

## Changelog
:cl:
add: Added multi-z support for pinpointers
imageadd: Added above and below overlays for pinpointers
/:cl:

2020-05-25 21:22 UTC, PowerfulBacon requested changes
Remove double z level check

2020-05-25 21:22 UTC, PowerfulBacon commented on code/game/objects/items/pinpointer.dm
> +		if(here.z != there.z)
```
if(here.z != there.z)
	if(here.z != there.z)
         if(here.z > there.z)
				add_overlay("pinon_below[icon_suffix]")
			else
				add_overlay("pinon_above[icon_suffix]")
			return
```

2020-05-25 21:30 UTC, PowerfulBacon approved these changes

2020-05-25 23:06 UTC, ike709 commented
Looks like there's a stray pixel in the top left corner in part of the animation.

2020-05-27 15:15 UTC, covertcorvid commented
> 
> 
> Looks like there's a stray pixel in the top left corner in part of the animation.

It looks okay on my screen. Any chance you can get a screenshot?

2020-05-27 16:31 UTC, ike709 commented
https://github.com/BeeStation/BeeStation-Hornet/pull/1874/checks?check_run_id=707453872

Watch the icondiffbot's preview of the sprites.

2020-05-27 17:44 UTC, covertcorvid commented
I don't see it still
https://streamable.com/lfxdid

2020-05-27 18:09 UTC, ike709 commented
https://streamable.com/zvsnv8

Because you're using lightmode.

2020-05-27 21:52 UTC, covertcorvid commented
Just deleting the area got me no changes, so I painted the transparent part electric green and then deleted it all again, but the icondiffbot preview still shows it. I'm not sure what to do about that, I'm open to suggestions.
I can also record what it looks like in game in an hour or so as evidence.

2020-05-27 23:33 UTC, Jalleo commented
I have also had a look and I cannot find the pixel via the DMI itself. I believe there might be corruption in the icon bot itself when it tried to animate it.

2020-05-27 23:33 UTC, ike709 commented
Eh, maybe it's just icondiffbot weirdness.

2020-05-27 23:33 UTC, merged