Full auto firemode issues
BeeStation/BeeStation-Hornet pull request #1993
Opened 2020-06-17 21:06 UTC by Kmc2000

## About The Pull Request

Fixes some wackiness with full auto firemode breaking guns. Oh god. Why. The bugs keep on coming and they keep on coming...

fix https://github.com/BeeStation/BeeStation-Hornet/issues/1944

## Why It's Good For The Game

I was unable to replicate, so I cannot attest to whether that is fixed or not:
https://github.com/BeeStation/BeeStation-Hornet/issues/1986

## Changelog
:cl:
fix: Fixed inconsistencies with full auto weapons.
/:cl:

2020-06-18 02:38 UTC, francinum commented on code/modules/projectiles/autofire.dm
> +	next_autofire = world.time + 1 SECONDS
Should be calculated from a variable on the gun.

2020-06-18 09:53 UTC, PowerfulBacon commented
Tested this, if you spam click you can sometimes fire 2 shots at the same time.
If you click, then hold right away the gun does not full auto and only fires when you release the hold.

2020-06-18 10:11 UTC, zeskorion commented
the shift click examine firing / user direction bug is still there


additionally, i found a new issue while testing: there is no Clumsiness check on fullauto guns

2020-06-18 12:00 UTC, Kmc2000 commented
> the shift click examine firing / user direction bug is still there
> 
> additionally, i found a new issue while testing: there is no Clumsiness check on fullauto guns

I don't understand how, there's literally a line of code to check for that

2020-06-20 06:02 UTC, zeskorion commented
> > the shift click examine firing / user direction bug is still there
> > additionally, i found a new issue while testing: there is no Clumsiness check on fullauto guns
> 
> I don't understand how, there's literally a line of code to check for that

try it. my testing shows it still happening, unless i did it wrong

2020-06-22 04:25 UTC, zeskorion commented
honestly, i dont even understand why the new autofire shit was necessary? automatic to 1 worked just fine, and my firerate pr fixed the issue with firerate

2020-06-23 14:25 UTC, Kmc2000 commented
> honestly, i dont even understand why the new autofire shit was necessary? automatic to 1 worked just fine, and my firerate pr fixed the issue with firerate

Because we use it for our full auto ARs and one of your guys asked for it upstream.

2020-06-26 17:21 UTC, PowerfulBacon approved these changes
Fixes most of the issues, if more pop up in the future we can do another PR.
The only issue I found was because temp gun has a speed of 0.
I'll wait to see what Zesk, or Ike thinks first though

2020-07-07 09:03 UTC, PowerfulBacon commented
Another issue that I recently discovered is being on help intent and spamming allows you to fire a lot faster than being on harm intent, not sure if this fixes that or not.
Use the CTF rifles (which have a fire rate of 2), go on harm intent and they fire at a normal speed, but spam clicking on help intent allows you to unload the entire mag in a few seconds.

2020-07-10 12:14 UTC, ike709 commented
@Kmc2000 ^

2020-07-10 20:47 UTC, zeskorion requested changes
above bugs still need fixing, as do the ones that make you unable to throw or examine with automatic guns

2020-07-14 12:06 UTC, Kmc2000 commented
The throw + examine bugs are addressed in this PR

2020-07-20 01:00 UTC, ivanmixo commented on code/modules/projectiles/autofire.dm
> +			user.setDir(get_dir(user, object))
This doesn't work, try
```suggestion
			user.face_atom(autofire_target)
```

2020-07-20 01:01 UTC, ivanmixo commented on code/modules/projectiles/autofire.dm
I also suggest you add this so people can't shoot out of lockers or sleepers

```suggestion
if(!isturf(user.loc))
			return FALSE
```

2020-07-20 15:59 UTC, PowerfulBacon commented
@Kmc2000 you keep saying these problems aren't on NSV which is weird but they totally are, I tried putting guns on racks there and ended up blasting the fuck out of them

2020-07-20 17:10 UTC, Kmc2000 commented
>bacon
You're the first person that I've heard who has a bug with them on nsv..

2020-07-21 07:13 UTC, PowerfulBacon commented
> > bacon
> > You're the first person that I've heard who has a bug with them on nsv..

Wait really? Try putting a pulse rifle onto a rack and you just shoot, and you cant throw them either

2020-07-24 04:16 UTC, ike709 commented
Will this PR ever be done?

2020-08-02 21:05 UTC, PowerfulBacon commented
Please can we just merge the changes, some critical bugs have been fixed that are still in game until we merge this

2020-08-02 23:16 UTC, ike709 commented
@PowerfulBacon Those two code suggestions are good suggestions though. KMC literally just needs to hit commit and fix it if github mangles the formatting.

2020-08-06 02:22 UTC, ivanmixo commented
wew how has this still not been touched since I made those suggestions.

Almost tazed cap with hos gun I found while trying to throw it to him a couple rounds ago

2020-08-09 06:39 UTC, PowerfulBacon commented
@Kmc2000 problems with full auto weapons shooting when you shift click, click on chargers or click on tables are on NSV too, valve plz fix

2020-08-10 19:36 UTC, Kmc2000 commented
Gimmie a hot sec.

2020-08-10 19:36 UTC, closed without merging