changes to lexorin and sulfonal recipes
BeeStation/BeeStation-Hornet pull request #2022
Opened 2020-06-21 13:57 UTC by That0nePerson

## About The Pull Request
Lexorin has been talked about as one of the best toxins for a while, and it has a piss-easy recipe, only requiring 3 basic chems. Sulfonal is objectively much worse than lexorin, yet has a much, much harder recipe. After some discussion on the discord, stormcaster has recommended these changes to the recipes. Sulfonal now takes perfluoro instead of acetone, and lexorin takes sulfonal as a 4th ingredient while still only giving 3u.

## Why It's Good For The Game
See above, lexorin has been super easy to make and OP, while sulfonal has been pretty bad, with lexorin being basically an upgrade. This balances things a bit, making the recipie for lexorin take sulfonal and making it sort of a step-up from sulfonal.

## Changelog
:cl:
balance: sulfonal now takes perfluorodecalin instead of acetone
balance: lexorin now takes sulfonal, still gives 3u
/:cl:

2020-06-21 18:27 UTC, eLeCtrOssSnake commented
If you try to get the idea of how these chems work, it's pretty obvious that sulfonal is just a toxin, that is just charcoal defeated and lexorin being a really fast toxin that suffocates, but the thing is that it requires plasma, so that kinda makes sense why the other recipes are so easy. In conclusion, this pull request won't balance anything nor change it, so I would rate it as useless and unneeded.

2020-06-21 22:48 UTC, That0nePerson commented
plasma is easily available from all department lathes at maximum 30 minutes into the round, earlier is mining is good

2020-06-21 23:28 UTC, zeskorion requested changes

2020-06-21 23:28 UTC, zeskorion commented on code/modules/reagents/chemistry/recipes/toxins.dm
>  	results = list(/datum/reagent/toxin/lexorin = 3)
change to 4

2020-06-22 00:19 UTC, That0nePerson commented on code/modules/reagents/chemistry/recipes/toxins.dm
>  	results = list(/datum/reagent/toxin/lexorin = 3)
done

2020-06-22 04:43 UTC, Chessus commented
You start with plasma in chemistry on meta station also. You've got a access to a potent  toxin from roundstart.

2020-06-22 07:22 UTC, Isy232 commented
This is good. 15u of lexorin does 187.5 oxyloss damage while also stopping breathing. If not given any help it will kill you quickly. You will also be knocked out partway through because of oxygen deprevation, meaning you have little time to react.

Lexorin is the deadliest poison mixable in the game and yet it does not require anything but plasma and 2 other base chems to make.

I've personally never seen one, but a lexorin massacre wouldn't be horribly difficult to pull off.

This is a good nerf.

2020-06-22 20:00 UTC, zeskorion commented
> This is good. 15u of lexorin does 187.5 oxyloss damage while also stopping breathing. If not given any help it will kill you quickly. You will also be knocked out partway through because of oxygen deprevation, meaning you have little time to react.
> 
> Lexorin is the deadliest poison mixable in the game and yet it does not require anything but plasma and 2 other base chems to make.
> 
> I've personally never seen one, but a lexorin massacre wouldn't be horribly difficult to pull off.
> 
> This is a good nerf.

initropidril and plasmaman mutation toxin can both be deadlier, as can curare

2020-06-22 20:47 UTC, zeskorion approved these changes

2020-06-22 20:47 UTC, merged

2020-06-23 03:50 UTC, Isy232 commented
> plasmaman mutation toxin can be deadlier

Except that requires black slimes from xenobio and is a lot more difficult to mass produce.