Edited borg modules
BeeStation/BeeStation-Hornet pull request #2028
Opened 2020-06-22 20:59 UTC by BettonnCZ

asfasdasd

## About The Pull Request
All credit goes to Schneckenhof. Edited the borg modules of the following silicons: Peacekeeper, Serviceborg.
Peacekeeper has been equipped with pepper spray to keep the peace if necessary, servieborg was given cookie synth instead of the lollipop launcher and beaker apparatus

## Why It's Good For The Game
It makes service borg more than just a walking keg and a lolipop launcher.
Peacekeeper can now select targets to calm down instead of confusing mass of people.

## Changelog
:cl:
Removed modules from service borg: guitar, razor, lollipop launcher.
Added modules for peacekeeper borg: pepperspray.
Added modules for service borg: cookie synth, beaker apparatus.
/:cl:

2020-06-22 21:13 UTC, Schneckenhof commented
Thanks for helping out, testing, and for redoing the modifications to the code that I had done. For some reason VS was being weird and wouldn't let me test. Thanks again. I'm apparently going to have to go back and setup everything properly so I can get PR's out myself in the future.

2020-06-23 13:13 UTC, PowerfulBacon commented
Why are you removing the lollipop, razor and guitar?

2020-06-23 13:16 UTC, BettonnCZ commented
lollipops because medborg has it, razor because noone ever uses it, guitar because the synth already has it

2020-06-23 14:20 UTC, Schneckenhof commented
Razor:
Currently Broken. See my bug report here:
https://github.com/BeeStation/BeeStation-Hornet/issues/2027

Also it is rarely used.

Guitar:
Redundant. The Synthesizer can already play the guitar sound, as well as every other instrument.
It is just taking up a slot unnecessarily.

....Unless someone wants to modify the code to allow an emagged serviceborg to strangle people with guitar strings? That might be fun. But a normal human would have to be able to do that as well. 

Lolipop dispenser:
Lolipops are healing items. The medborg already has it.
It makes sense for the medborg to have the lolipop. 
But why the Service borg?

I feel it makes more sense for the service borg to have the cookie dispenser. 
It is food after all, and the service borg already makes drinks.

Beaker:
The Beaker allows the service borg to make the full range of drinks in addition to other tasks.
This has been requested multiple times in the forums.

Pepper Spray on Peaceborg:

Firstly, Compensate the Peaceborg for the loss of their cookie exclusivity.

Secondly, Peaceborg needs a mid-range ability. Basically they either sonic blast an entire room, or they have to get in close to stab someone with the hypo.

The current situation is bad in a typical toolbox murderspree situation:

1) You get in close to use hypospray. But you misclick, now you are in toolbox range. Ouch. Oh he has armor. Your Hypo doesn't even penetrate. Ouch, you're now dead.

2) You use Sonic blast. You have now knocked down the murderer, but you've also knocked down ALL 6 Sec officers who were helping. OOPS, The target has armor, is caffinated, and is on drugs. He recovers faster than everyone else, and proceeds to beat the downed officers to death. 

OR:
3) You pull out your trusty pepper pray, you catch 2 officers and the target in the blast, but the other 3 officers swoop in ~~to decapitate and throw the target into deep space~~ to arrest the perpetrator and hold a trial -- at least according to officer friendly standing there with bloodstained hands. 

Pepper Spray seemed to fit this bill nicely.

2020-06-23 19:04 UTC, PowerfulBacon commented
Fix the changelog

2020-06-30 04:03 UTC, zeskorion requested changes
the razor only works when aiming at the head. dont remove it.

2020-07-01 14:43 UTC, closed without merging