Nanite research points and programs
BeeStation/BeeStation-Hornet pull request #2047
Opened 2020-06-25 02:51 UTC by Tamuren

##  About The Pull Request
This PR takes from the following:
[Makes nanites more accessible, giving them a separate research point type #47421](https://github.com/tgstation/tgstation/pull/47421/files)
[Adds research-boosting programs for nanites #47098](https://github.com/tgstation/tgstation/pull/47098)
[[READY] New nanite program in the Utility category, Nanite Sting. #46907](https://github.com/tgstation/tgstation/pull/46907)
[Nanite program rebalancing, added two new mood programs #47227](https://github.com/tgstation/tgstation/pull/47227)
[Adds the Reduced Diagnostics nanite program](https://github.com/tgstation/tgstation/commit/21e54e3271c357baf74acc5f9b293d8d24460b04#diff-8ad082c49b52bfff3c4c47feab51721b)
[Moves research nanite programs to Basic Nanite Programming](https://github.com/tgstation/tgstation/commit/8c77042c8afe1881cf4df2f0e55d3dc56e4f2f2d)

It adds a new research point type, nanite, and makes nanites more appealing to research early. It also makes nanite programs brought over from the TGUI 3.0 update finally available. These include:  

Distributed Computing: slowly adds generic research points over time
Neural Network: adds research points over time as well, but scales in efficiency for each mob that is currently running the program, breaking even with Distributed Computing at 12 hosts.
Reduced Diagnostics: hides nanite program details on scan, increases nanite regen rate slightly
Nanite Sting: a trigger-based close-range nanite-spreading program. It requires the Military Nanite Programming research node. Targets of this program will notice that they got stung. If no valid targets are found, the used volume is refunded.
Happiness Enhancement: improves mood while active
Happiness Suppression: decreases mood while active

## Why It's Good For The Game

Allows nanites to be researched faster and less obtrusively. More programs more fun

## Changelog
:cl:
add: New research point type: nanite
add: Added code to all_nodes.dm to make nanite programs available
/:cl:

2020-06-25 05:36 UTC, zeskorion requested changes
I think you screwed up, because this changes only two files

2020-06-25 11:11 UTC, Tamuren commented
Yep, most of the code was brought over during the TGUI 3.0 bounty. I just had to add a little to finish the job.

2020-06-25 13:32 UTC, Tamuren commented
This is ready for review

2020-06-27 21:46 UTC, zeskorion approved these changes

2020-07-10 20:55 UTC, merged