Refactors languages, adds missing languages and some species updates.
BeeStation/BeeStation-Hornet pull request #2058
Opened 2020-06-27 00:15 UTC by yorii

## About The Pull Request

Updates mainly stuff from the follow PRs:
https://github.com/tgstation/tgstation/pull/48106
https://github.com/tgstation/tgstation/pull/48309
https://github.com/tgstation/tgstation/pull/48573

But also a few other minor related additions and edits directly copied from tgstation, full changelog will be edited later.

Still to do: Update sprites.

## Why It's Good For The Game

Just brings some files that haven't been touched in a long while more up to date and includes the full language, and language menu refactoring from tgstation.

## Changelog
:cl:
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
imageadd: added some icons and images
imagedel: deleted some icons and images
code: changed some code
refactor: refactored some code
admin: messed with admin stuff
/:cl:

2020-06-27 02:53 UTC, yorii commented
Plz review now

2020-06-27 03:06 UTC, yorii commented
I mean now

2020-06-27 03:14 UTC, YakiAttaki commented
If it helps, I already ported most of the racial language stuff to AuStation downstream, here:
https://github.com/austation/austation/pull/1712

2020-06-27 03:26 UTC, yorii commented
> If it helps, I already ported most of the racial language stuff to AuStation downstream, here:
> [austation/austation#1712](https://github.com/austation/austation/pull/1712)

Thanks, I think I got all of it :) (and more!)

2020-06-27 04:17 UTC, yorii commented
Ooops forgot to make the robots able to charge :)

2020-06-27 04:21 UTC, yorii commented
TODO: make organics take a minor amount of burn damage if they're ever so stupid to try and connect themselves in a recharge station.

2020-06-27 06:17 UTC, yorii commented
Okay now I'm done :D

2020-06-27 07:32 UTC, yorii commented
I am now 100% done and I leave the rest up to whoever finds it.
Only thing really is if you want something to happen to non-electric races when they step into a charging station?
For now I leave it be as it is :D (that is nothing happens)

2020-06-30 07:48 UTC, yorii commented
Hi I couldn't log in to github all day yesterday, but there are a few old proc calls that need to be adjusted with new source vars. (They'll still work fine with the source var of TRUE/FALSE though so this is actually mergeable as is).

I'll get to fixing the last few edits later this week.

2020-07-04 05:38 UTC, yorii commented
it's finished and ready to merge now

2020-07-04 06:26 UTC, yorii commented
oopsiewoopsie I made a wittle fuckywucky

2020-07-04 06:30 UTC, yorii commented
there all good now :D

2020-07-04 06:46 UTC, yorii commented
@zeskorion merge plz

2020-07-09 08:03 UTC, qwertyquerty submitted a review, later dismissed

2020-07-11 06:55 UTC, yorii commented
@ike709 you can testmerge this now, or whenever :) I'm looking forward to speaking secret languages with my racial brethren!

2020-07-15 16:26 UTC, yorii commented
@zeskorion @ike709 come on please testmerge this before it becomes completely stale and too troublesome to unconflict...

2020-07-20 01:21 UTC, TheFakeElon commented
Hurry up and merge/close so we can fix shit downstream smh, it’s been almost a month

2020-07-20 09:25 UTC, Crossedfall commented
I'll bug them about it and try for a test merge tomorrow. Not sure what the hold up has been on this one.

2020-07-21 06:23 UTC, Crossedfall commented
Test merged onto Sage

2020-07-21 06:25 UTC, zeskorion requested changes
other than requested changes, this looks pretty solid to me

2020-07-21 06:25 UTC, zeskorion commented on code/modules/mob/living/carbon/human/species_types/mothmen.dm
> +		if(flying_species) //This is all exclusive to if the person has the effects of a potion of flight
can you remove all of these moth changes except the language one? i've handled them in gh#2143

2020-07-21 06:43 UTC, yorii commented
Changes done :) Thanks for your review zesko!

2020-07-21 06:50 UTC, Crossedfall commented
Updated TM

2020-07-21 07:39 UTC, zeskorion submitted a review, later dismissed

2020-07-21 09:23 UTC, yorii commented
What do with the dna.dm conflict?

2020-07-21 11:13 UTC, 4rchibald commented
@yorii Plasmamen are no longer protected by their envirosuits and burst in flames the moment they spawn on arrival shuttle. Its clearly related to this PR since issue appeared during 2 rounds it was test merged and after quick searching I see some changes were made around the section of code related to suits and igniting when in oxygen atmosphere (Sadly I'm not a coder so I have no clue what exactly is the problem)

2020-07-21 11:37 UTC, yorii commented
@4rchibald This PR doesn't really touch any of that.. is this happening on both Golden and Sage?

2020-07-21 11:38 UTC, yorii commented
Actually nevermind, it does have some code cleanup regarding envirosuits, let me try to debug it!

2020-07-21 11:41 UTC, yorii commented
I see what it is now when I tried to reproduce, plasmamen spawn in with their internals turned off for whatever reason..?
Turning on your internals as soon as the round starts prevents this from happening.

2020-07-21 11:56 UTC, yorii commented
So yeah... I somehow made plasmemes spawn with their internals turned off instead of on. Let me see if I can rectify this.

2020-07-21 13:07 UTC, yorii commented
Okay I fixed it now.

2020-07-21 13:14 UTC, yorii commented
although somehow I managed to really spook the dna.dm file when resolving a merge conflict 👀

2020-07-21 13:21 UTC, yorii commented
Can't unfuck dna.dm diff shenanigans, OCD triggered...

2020-07-21 19:49 UTC, 4rchibald commented
@yorii What's currently test merged on Sage already includes your fix? 
Cause its still happening. Exactly same issue. Its not about internals (normally when they are off you are not burning, just suffocating) but enviro jumpsuits and/or helmets and how they protect plasmamen from bursting in flames when are in atmosphere with oxygen. The moment they join the game they are greeted with text 'Your body reacts with the atmosphere and bursts into flame!' and 'You're set on fire!' few moments later they are dead

2020-07-21 20:05 UTC, Crossedfall commented
@4rchibald The TM does not include the latest changes. You can see the commit number in the MOTD. It was updated recently but the round hasn't ended yet. 

![image](https://user-images.githubusercontent.com/26130695/88101469-a5146700-cb63-11ea-8fbe-80f40eafd16c.png)

I have to temporarily pull this out to test another PR though, so the changes will be reflected when we test merge this again.

2020-07-21 22:43 UTC, yorii commented
> @yorii What's currently test merged on Sage already includes your fix?
> Cause its still happening. Exactly same issue. Its not about internals (normally when they are off you are not burning, just suffocating) but enviro jumpsuits and/or helmets and how they protect plasmamen from bursting in flames when are in atmosphere with oxygen. The moment they join the game they are greeted with text 'Your body reacts with the atmosphere and bursts into flame!' and 'You're set on fire!' few moments later they are dead

Did you actually double check your internals? The only change which was missed was that internals at roundstart were off, and turning them on prevented fires from happening in my testing, it was confirmed by another person as well to be the roundstart internals setting.

2020-07-22 08:04 UTC, zeskorion approved these changes

2020-07-22 08:29 UTC, merged

2020-08-03 09:31 UTC, Vivalas commented
Yeah so this PR right here is why we test our code. This PR breaks ethereals. By changing the variable name in handle_charge from ethereal_charge to get_charge you broke ethereals, because there's no way to actually increment crystal_charge anywhere in the code now.

So, yay. :clap:

2020-08-03 14:26 UTC, yorii commented
@Vivalas that wasn't the reason why it broke, the reason is that it's no longer the ethereal itself having the charge, it's their stomach organ. They can still charge with borg chargers and a fix for the rest is already on the way.

2020-08-03 20:47 UTC, Vivalas commented
Yeah I was aware of that, crystal_charge is the variable stored in the ethereal stomach organ. I wasn't aware there was actually a way to charge them, however. I couldn't find anywhere in the code where crystal_charge was increased. interesting

2020-08-04 22:25 UTC, Crossedfall commented
> 
> 
> Yeah I was aware of that, crystal_charge is the variable stored in the ethereal stomach organ. I wasn't aware there was actually a way to charge them, however. I couldn't find anywhere in the code where crystal_charge was increased. interesting

This is why we fully go through the code before making sarcastic rude comments.

So, yay. 👏