Increases likeliness of extended on MRP
BeeStation/BeeStation-Hornet pull request #2088
Opened 2020-07-01 12:38 UTC by zeskorion

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2020-07-01 13:40 UTC, PowerfulBacon commented
Can you maybe increase secret extended as well and have them both at 5 or 6?

2020-07-01 14:37 UTC, Flakkyboo commented
> 
> 
> Can you maybe increase secret extended as well and have them both at 5 or 6? (Also there is no way this will pass the vote lmao)
> 
> Also 9 is wayyyy to high

exactly what i said 6 is a good number 9 is just salt.

2020-07-01 15:36 UTC, St0rmC4st3r commented
> Can you maybe increase secret extended as well and have them both at 5 or 6?

I second that. Secret extended should be as common as regular extended. This will ultimately be better than just explicit greenshifts happening very often.

2020-07-01 21:17 UTC, zeskorion commented
> Can you maybe increase secret extended as well and have them both at 5 or 6? (Also there is no way this will pass the vote lmao)
> 
> Also 9 is wayyyy to high

Fuck the vote.

2020-07-02 02:04 UTC, Isy232 commented
I honestly agree with this, its nice to be guaranteed a long round so you know you wont have to leave part way through it. Its annoying to try to build a shuttle or some other cool stuff and then just have medbay go boom and red alert shuttle get called.

2020-07-09 15:44 UTC, yorii commented
I think it's a nice change but 9 is a bit too high isn't it?

2020-07-09 18:06 UTC, TeomanTheGreat commented
Yeah 9 is waaaaay to high make it like 6 or 7

2020-07-15 14:02 UTC, Crossedfall requested changes

2020-07-15 14:02 UTC, Crossedfall commented on config/Sage/game_options.txt
> +PROBABILITY EXTENDED 9
Two things. One, keep it the list ordered. Two. I agree with the others, 9 is way too high. I think 7 would likely be a bit better.

2020-07-24 04:19 UTC, ike709 commented
@Crossedfall Config.

2020-08-04 16:13 UTC, Crossedfall approved these changes
Config changes applied

2020-08-04 16:13 UTC, merged