updates the price of the vape
BeeStation/BeeStation-Hornet pull request #2220
Opened 2020-07-28 15:53 UTC by BettonnCZ

haha

## About The Pull Request

The hacked vending machine shows that E-cigarette costs 10 credits, which is false, it costs 50. I moved the E-cigarette to the premium list, so it shows the proper price

## Why It's Good For The Game

It won't confuse players wanting to buy the E-cigarette.

## Changelog
:cl:
fix: Fixed the price showed next to the E-cigarette to show the proper price.
/:cl:

2020-07-28 19:37 UTC, St0rmC4st3r commented
I think we should rather fix the broken prices for contraband.

2020-07-28 19:39 UTC, BettonnCZ commented
well, this just works ¯\_(ツ)_/¯, i dont know where is the price referenced.

2020-07-28 23:35 UTC, Crossedfall commented
This is the code you actually want to change. This checks to see if the item is hidden (contraband) and then applies the premium price to it. Just remove the `|| hidden_records.Find(R)` portion of the check.

https://github.com/BeeStation/BeeStation-Hornet/blob/a54b6c5682d2719b8ae6111785935d98e5be5cd9/code/modules/vending/_vending.dm#L766-L767

2020-07-28 23:42 UTC, Crossedfall requested changes
see above

2020-07-29 08:44 UTC, BettonnCZ commented
![obrazek](https://user-images.githubusercontent.com/63119702/88778139-6e080c00-d188-11ea-94c0-e4bc93d97304.png)
removed the  || hidden_records.Find(R)
![obrazek](https://user-images.githubusercontent.com/63119702/88778167-78c2a100-d188-11ea-9b86-2f3673aa559c.png)
still shows the wrong price

2020-08-02 06:51 UTC, Crossedfall commented
> 
> 
> ![obrazek](https://user-images.githubusercontent.com/63119702/88778139-6e080c00-d188-11ea-94c0-e4bc93d97304.png)
> removed the || hidden_records.Find(R)
> ![obrazek](https://user-images.githubusercontent.com/63119702/88778167-78c2a100-d188-11ea-9b86-2f3673aa559c.png)
> still shows the wrong price

Did you try to buy it though? It should only take the 10 credits from you.

2020-08-02 09:14 UTC, BettonnCZ commented
i think it should be now good, i tought the vape is supposed to charge you 50, now it charges you 10 credits, which it displays.

2020-08-02 15:57 UTC, Crossedfall commented on code/modules/vending/cigarette.dm
> +	contraband = list(/obj/item/clothing/mask/vape = 5)
```suggestion
	contraband = list(/obj/item/clothing/mask/vape = 5)
```

Buncha whitespace

2020-08-02 15:58 UTC, Crossedfall commented
Fix the whitespace issue and then update your PR body to address the fact that you're fixing non-premium contraband pricing as a whole, not just vapes and I think we'll be good.

2020-08-02 17:42 UTC, Crossedfall approved these changes

2020-08-02 17:43 UTC, merged