Wraps isnum()
BeeStation/BeeStation-Hornet pull request #2230
Opened 2020-07-30 08:35 UTC by ike709

Untested, but it compiles.

Fixes at least 1 href exploit.

2020-07-30 08:39 UTC, Crossedfall submitted a review, later dismissed
Looks fine for my owned files. (That's all I checked on this)

2020-07-30 08:41 UTC, PowerfulBacon commented
?compile
```
#define isnan(x) ( (x) != (x) )
#define isinf(x) ( isnum((x)) && !((x) == text2num("inf")) && !((x) == text2num("-inf")) )
#define isnum_safe(x) ( isnum((x)) && !isnan((x)) && !isinf((x)) )

/proc/main()
  world.log << isnan(7) //0
  world.log << isnan(text2num("nan")) //1
  world.log << isnan(text2num("inf")) //0
  world.log << isinf(7) //1
  world.log << isinf(text2num("nan")) //1
  world.log << isinf(text2num("inf")) //0
  world.log << isnum_safe(7) //0
  world.log << isnum_safe(text2num("nan")) //0
  world.log << isnum_safe(text2num("inf")) //1
```

2020-07-30 08:43 UTC, PowerfulBacon requested changes
Looks like isinf() return true if the number is not infinity

2020-07-30 08:47 UTC, PowerfulBacon requested changes
#define isinf(x) (isnum((x)) && (((x) == text2num("inf")) || ((x) == text2num("-inf")))

Has 10 opening brackets but 9 closing

2020-07-30 08:49 UTC, PowerfulBacon submitted a review, later dismissed
Tests are outputting the correct results now

2020-07-30 17:07 UTC, PowerfulBacon commented on code/game/objects/items/stacks/stack.dm
> +		if (!multiplier || !isnum_safe(multiplier) || (multiplier <= 0)) //href protection
I believe the !multiplier is unnecessary now, since the !isnum_safe would handle if the value is null when it checks if it is a number

2020-07-30 17:07 UTC, PowerfulBacon commented on code/game/objects/items/stacks/stack.dm
> +		if (!multiplier || !isnum_safe(multiplier) || (multiplier <= 0)) //href protection
And the multiplier <= 0 handles if the value is actually 0

2020-07-31 09:39 UTC, PowerfulBacon approved these changes

2020-08-01 12:04 UTC, Crossedfall approved these changes

2020-08-01 12:04 UTC, merged