Ruko's Player Quality Points Thing (TM)
BeeStation/BeeStation-Hornet pull request #2270
Opened 2020-08-08 03:22 UTC by ike709

This entire concept is entirely devised by Headmin Ruko, I'm just the hired help.

TODO:

- [ ] Nuke note severity from the code
- [ ] Nuke note severity from the DB
- [ ] Mirror the config changes to Sage config once it's finalized
- [ ] So, so much testing
- [ ] Inevitable tweaks

## Changelog
:cl: Designed by Ruko, coded by ike709
add: Notes/bans are now quantified via a negative point value, rather than severity. Playtime as a living character gives a positive point value, effectively allowing you to improve your track record simply by playing.
/:cl:

2020-08-08 04:31 UTC, zeskorion commented
We communist china now boys

2020-08-08 05:15 UTC, Bastian0930 commented
but W H Y change this?

ruko has no ping but what's the reasoning?

2020-08-08 05:46 UTC, Rukofamicom commented
To standardize bans on a point based system by replacing the severity of notes with a point value instead. Players lose points when noted and gain them back by playing rounds without being noted. Players with more than x points after gaining new ones will be recommended (but not forced) a ban length based on that total. Points and bans will be given following a guide so that there won't be nearly as much discrepancy between different admins for the same offenses. Offenses will be worth different amounts of points within a range, so there will still be _some_, but not nearly as much. 

This will also help to highlight particularly active players for not being as problematic as they may seem - A player that breaks a rule one in ten rounds but only plays one round a week will appear to have a pretty sparse record. A player doing the same offense one in ten rounds that plays ten rounds a day will be labeled as a much worse player despite having the same overall impact on the game as the first. 

TL;DR
It's a more sophisticated way to track players who cause issues so we can gauge how much of a problem they really are. Ban lengths will be much more consistent and vary based on a player's record of good **and** bad conduct, and permanent bans will be handed out in a more uniform fashion instead of seemingly on a whim.

2020-08-08 08:52 UTC, PowerfulBacon commented
Why base the regaining points on how long you are playing, having is based on how many offences you have would punish players that consistently get negative points (like 13 hour player with 3 bans) would then be punished harsher than a 1000 hour player with 1 ban.

2020-08-08 09:39 UTC, TotallyNotChief commented
muh good boy points

the question is, if i don't break any rules and if i get a lot of GBPs, can i then exchange them for chicken tendies?

2020-08-08 17:14 UTC, Archanial commented
We cs go now

2020-08-09 05:41 UTC, triplezeta commented
wouldn't Paradise's karma system work better as a means to regain your social credit than just playing

2020-08-09 05:53 UTC, AsciiSquid commented
Is reading the dates and times of things really so hard as to justify an overhaul of the note system? If you really don't trust your staff to discern note volume with respect to playtime just set expiry dates for notes so they don't burden a players record months after the fact.

This change seems to be more out of a laziness in enforcing standards than anything sophisticated.

2020-08-09 06:23 UTC, Epsilos commented
wouldn't this just encourage one admin with a grudge to collect a bunch of small 1 point infractions to throw the book at someone they hate when anyone without that grudge would only take notice when something actually worthy of a medium-high note happened

2020-08-09 14:19 UTC, BeloneX commented
my social credit score...

2020-08-09 14:25 UTC, ethan10000llahd commented
I already had a bad social credit score... ohgod no I don't want to go to brazil over low social cred-

2020-08-09 22:44 UTC, Rukofamicom commented
> Is reading the dates and times of things really so hard
No, it isn't, but determining how much a player has played in between offenses is currently not possible at all. We can only gauge offenses against total playtime and against real-time that has passed.

> This change seems to be more out of a laziness
Is... that bad? Removing some degree of human error from the equation and making things easier on the admins in a given system is kind of the goal of programming any administrative tool isn't it?

2020-08-09 23:21 UTC, Crossedfall commented on SQL/database_changelog.txt
> +`playerqualitypoints` double(4,2) ZEROFILL NOT NULL DEFAULT 0;
```suggestion
ALTER TABLE SS13_player
ADD COLUMN `playerqualitypoints` double(4,2) ZEROFILL NOT NULL DEFAULT 0;
```

2020-08-09 23:28 UTC, Crossedfall commented on config/config.txt
> +#### Player Quality Points Settings
I wonder if this should be in its own config. 🤔

2020-08-10 02:54 UTC, Crossedfall reviewed
Gave some bad advice here, assumed we were only dealing with positive numbers.

2020-08-10 02:54 UTC, Crossedfall commented on SQL/database_changelog.txt
> +ADD COLUMN `playerqualitypoints` double(4,2) ZEROFILL NOT NULL DEFAULT 0;
```suggestion
ALTER TABLE SS13_player
ADD COLUMN `playerqualitypoints` double(4,2) NOT NULL DEFAULT 0;
```

2020-08-10 02:54 UTC, Crossedfall commented on SQL/beestation_schema.sql
> +  `playerqualitypoints` double(4,2) ZEROFILL NOT NULL DEFAULT 0,
```suggestion
  `playerqualitypoints` double(4,2) NOT NULL DEFAULT 0,
```

2020-08-10 04:41 UTC, ike709 commented
This survives basic testing on staging.

2020-08-12 07:27 UTC, TheFakeElon commented
**what if more social credits increased your antag rep**

2020-08-13 20:25 UTC, MrLostman commented
This is why you shouldn't let Americans manage your code base. If you need help I'm sure AUStation could offer you some help for a price.

2020-08-13 22:58 UTC, MCterra10 commented
Yes lostman, let your anger out
This is based

2020-08-13 23:00 UTC, TheFakeElon commented
> This is why you shouldn't let Americans manage your code base. If you need help I'm sure AUStation could offer you some help for a price.

Don't mind him, he's New Zealand

2020-08-13 23:00 UTC, TheFakeElon commented
> This is why you shouldn't let Americans manage your code base. If you need help I'm sure AUStation could offer you some help for a price.

Don't mind him, he's New Zealand

2020-08-13 23:00 UTC, TheFakeElon commented
> This is why you shouldn't let Americans manage your code base. If you need help I'm sure AUStation could offer you some help for a price.

Don't mind him, he's New Zealand

2020-08-13 23:00 UTC, TheFakeElon commented
> This is why you shouldn't let Americans manage your code base. If you need help I'm sure AUStation could offer you some help for a price.

Don't mind him, he's New Zealand

2020-08-13 23:00 UTC, TheFakeElon commented
> This is why you shouldn't let Americans manage your code base. If you need help I'm sure AUStation could offer you some help for a price.

Don't mind him, he's New Zealand

2020-08-13 23:00 UTC, TheFakeElon commented
> This is why you shouldn't let Americans manage your code base. If you need help I'm sure AUStation could offer you some help for a price.

Don't mind him, he's New Zealand

2020-08-13 23:05 UTC, MCterra10 commented
SS13 is rapidly becoming a communist dystopia. Soon servers will share the social credit scores of their players, and players will be discriminated based on their arbitrary number oh god I can see it already

2020-08-13 23:06 UTC, MCterra10 commented
You say n word, you lose credit
You defib Captain, you get credit
Social credits as a system for in-game actions when

2020-08-13 23:36 UTC, Archanial commented
> 
> 
> You say n word, you lose credit
> You defib Captain, you get credit
> Social credits as a system for in-game actions when

society smh

2020-08-15 21:53 UTC, Crossedfall requested changes
Failed linting

2020-08-15 21:53 UTC, Crossedfall commented on code/modules/jobs/job_exp.dm
> +		return
Travis failure

> code/modules/jobs/job_exp.dm, line 334, column 4:
> warning: ambiguous `&&` on left side of an `in`
> - add parentheses to fix: `a && (b in c)`
> - add parentheses to disambiguate: `(a && b) in c`

2020-08-15 22:47 UTC, ike709 commented on code/modules/jobs/job_exp.dm
> +	if(GLOB.naughty_keys.len && key in GLOB.naughty_keys)
```suggestion
	if(GLOB.naughty_keys.len && (key in GLOB.naughty_keys))
```

2020-08-15 22:52 UTC, ike709 commented
Passes now.

2020-08-15 22:59 UTC, Archanial commented
This PR scares me.

2020-08-18 01:30 UTC, ZombiesVsPlants commented
> leaves armory as warden
> -5000 social credit

2020-09-26 17:01 UTC, ike709 commented
Just going to let this go stale. It can be reopened when the necessary policy changes happen.

2020-10-02 00:48 UTC, closed without merging