Fixes autofire, for real this time.
BeeStation/BeeStation-Hornet pull request #2279
Opened 2020-08-10 19:45 UTC by Kmc2000

## About The Pull Request

Mirror of https://github.com/BeeStation/NSV13/pull/814. Please direct review there to avoid headache.

## Why It's Good For The Game

-Autofire code has been taken out the back and shot.  It now uses a component and is far more consistent in its behaviour, allowing you to do epic things like place guns on a table without them breaking EVERYTHING.

-Full-auto has been moved to a small focus group of guns for the time being. Admins can edit this in game by changing the full_auto var

-Autofire now uses fire_rate to determine how quickly you can shoot.

-Autofire no longer lets you magdump people (As far as I can tell through our testing)

-Autofire no longer bugs the hell out when trying to physically click on people, throw the gun etc.

## Changelog
:cl: Kmc2000 with Gun Jesus
add: Fully automatic firing for guns, except this time it isn't horribly coded and broken.
/:cl:

2020-08-10 19:46 UTC, Kmc2000 commented
This is currently test merged on NSV. I'll get back to you on how that goes

2020-08-18 11:42 UTC, Kmc2000 commented
We've had this running on NSV for the weekend and I've not had the usual complaints about autofire being broken. We'll be merging it on our end, recommending you testmerge this yourselves!

2020-08-18 11:45 UTC, PowerfulBacon commented on code/modules/projectiles/autofire.dm
> +			return ..()
..() called twice. remove the top . = ..() since its made redundant by line 36 anyway

2020-08-31 08:23 UTC, PowerfulBacon requested changes
Remove the double ..()

2020-09-26 09:09 UTC, PowerfulBacon commented on code/modules/projectiles/autofire.dm
> +			return ..()
```suggestion
					return
			else //They're trying to disable the full auto of a gun. Remove the relevent component
				if(autofire_component)
					autofire_component.RemoveComponent()
					qdel(autofire_component)
					return ..()
		if(NAMEOF(src, fire_rate))
			autofire_component?.default_fire_delay = (10 / var_value)
			return
```

2020-09-26 11:13 UTC, PowerfulBacon approved these changes

2020-09-27 19:21 UTC, merged

2020-09-29 23:42 UTC, AnjelicaChaykovsky commented
hos gun is not full auto anymore because of this i guess ?