Mentor System Rework (WIP)
BeeStation/BeeStation-Hornet pull request #2337
Opened 2020-08-25 23:44 UTC by francinum

## About The Pull Request
Just because someone else jumps off a cliff doesn't mean you should too. This extends to quarter-assing a port of a system.

## Why It's Good For The Game
Mentor code is awful. Maybe it should be less awful.

## Changelog
:cl:
server: Mentor stuff has changed massively. Don't merge this without making me write a full changelog.
/:cl:

2020-08-26 01:18 UTC, francinum commented on code/_globalvars/lists/mobs.dm
> +GLOBAL_LIST_EMPTY_TYPED(admins, /datum/admins)							//all clients whom are admins
There's probably a better solution than making these typed but it gets dreamchecker to shut up.

2020-08-26 03:37 UTC, ike709 commented on code/modules/admin/holder2.dm
>  		owner.add_admin_verbs()	//TODO <--- todo what? the proc clearly exists and works since its the backbone to our entire admin system
wew

2020-08-26 19:28 UTC, francinum commented on code/modules/admin/verbs/adminhelp.dm
> +	if(reclassed)
This stuff also doesn't seem to be working.

2020-09-03 21:36 UTC, francinum commented on code/modules/admin/verbs/adminhelp.dm
> +	to_chat(world, "TBUIACT: [action]")
TODO: Clear out debug prints.

2020-09-03 21:36 UTC, francinum commented on code/modules/admin/verbs/adminhelp.dm
> +	to_chat(world, "AHUIACT: [action]")
TODO: Clear out debug prints.

2020-09-03 21:36 UTC, francinum commented on code/modules/admin/verbs/adminhelp.dm
> +		to_chat(world, "RC_YEET USR: [usr.name]")
TODO: Clear out debug prints.

2020-09-09 20:49 UTC, Crossedfall requested changes
We are our own codebase, we don't need "Bee edit" lines scattered around the place.

2020-09-09 20:49 UTC, Crossedfall commented on code/__DEFINES/admin.dm
> +#define R_EVERYTHING (1<<17)-1 //the sum of all other rank permissions, used for +EVERYTHING //BEESTATION EDIT - Bumped for bitflags.
You don't need to do edit comments like this.

2020-09-09 20:49 UTC, Crossedfall commented on code/modules/admin/admin_verbs.dm
> +//BEE START - MENTOR2 AND TELEPORT FLAG
Same as above

2020-09-09 20:49 UTC, Crossedfall commented on code/modules/admin/topic.dm
> +	if(href_list["ahelp"]) //BEE CHANGE, Tickets should check their own permissions on ui_state.
^

2020-09-09 20:49 UTC, Crossedfall commented on code/modules/client/client_procs.dm
> +	//BEESTATION Only R_ADMIN holders are in GLOB.admins, ditto for R_MENTOR and GLOB.mentors, All staff are in GLOB.staff
You get the gist

2020-09-18 19:39 UTC, FortSumter commented
I'm a mentor. All I ask is you add aghost to mentors. Other than that as far as usability the current system was fine more or less. I'm sure whatever this does will be good but if it doesn't give mentors the ability to aghost to answer a question it's not going to be any kind of improvement us mentors really care about.

2020-09-19 23:51 UTC, francinum commented
@FortSumter Never gonna happen. That's outside your privy access. The follow button WILL work if you're already dead though.

2020-09-22 23:15 UTC, theboy6545 commented
speed merge this shit please i beg

2020-09-23 00:58 UTC, francinum commented
I'd like this to get in before anymore changes to TGUI.

2020-09-24 14:19 UTC, FortSumter commented
Meeeeh.... I was an trialmin for bee for a while. Having a ticket system is nice, but doesn't change much besides maybe have what we mentors do be acknowledged by Crossed and the headmins. mghost (aghost but for mentors) would of been a real game changer, for it would allow us to get the situational context we need to appropriately answer questions that need it. You can't even argue against doing that due to metagaming because aghosting is logged in admin, and people tend to ask questions about their antag roles anyway. The only trouble I see is that some of the valid hunters on LRP are mentors, and while most all of them are professional enough not to use meta game knowledge to kill someone, it would be difficult to prove their innocence if they were the mentor who answered the antags question.

2020-09-24 19:59 UTC, Crossedfall requested changes
Mentor panel should be removed, since all it does now is create SQL errors.

https://github.com/BeeStation/BeeStation-Hornet/blob/master/code/modules/admin/verbs/mentors_edit.dm

2020-09-24 20:04 UTC, Crossedfall commented on beestation.dme
> +#include "code\modules\mentor\mentor2.dm"
Is this listed as `mentor2` for iterative purposes? Or..?

2020-09-24 20:04 UTC, Crossedfall commented on code/modules/admin/admin_verbs.dm
> +//BEE END
```suggestion
```

2020-09-24 20:13 UTC, Crossedfall commented
`Mentor` flag grants access to the Player Panel and subsequently the Banning Panel. While a mentor cannot ban players, they can, however, view their IP & CID using this method.

2020-09-24 20:35 UTC, Crossedfall commented
Lots of administrator references still show up for mentor specific things. For example, when a mentor claims a ticket, the end-user sees:
![image](https://user-images.githubusercontent.com/26130695/94196596-395bbc80-fe7a-11ea-8f4e-373a43052072.png)

If a ticket is rejected they see: 
![image](https://user-images.githubusercontent.com/26130695/94196634-48db0580-fe7a-11ea-9493-1043f3ee6855.png)

Mentors marking a ticket as IC (Is that a needed aspect of mentor tickets?):
![image](https://user-images.githubusercontent.com/26130695/94196733-6c05b500-fe7a-11ea-8b5a-7b1536198c57.png)

Mentors have a Deadmin/Readmin option which incorrectly logs them as dropping/gaining admin perms (minor gripe)

---

Ahelps and Mhelps are linked. Which means if a user has an active mhelp, they wont be able to submit an ahelp and vice versa.

--- 

Clicking the `Transfer` button within the ticket does not sent the redirected notice to the player (redirecting via the ticket browser does, however)
![image](https://user-images.githubusercontent.com/26130695/94197074-e0d8ef00-fe7a-11ea-9cfd-88c76ab6d6fe.png)

---

Mentorhelp should arguably be in the Mentor tab. If not, then the mentor tab should just be removed since there is only one option there now and it's an alias for Staffwho

2020-09-25 00:38 UTC, francinum commented
...I'm not gonna lie I'm *super* tired of touching this branch.

2020-10-15 11:19 UTC, TeomanTheGreat commented
When will this be done

2020-11-03 17:55 UTC, ike709 commented
Fran's busy and doesn't wanna work on this anyways. Someone else can finish it.

2020-11-03 17:55 UTC, closed without merging