Adds sterilizer spray to robodrobe
BeeStation/BeeStation-Hornet pull request #2342
Opened 2020-08-27 20:07 UTC by super12pl

## About The Pull Request
Adds sterilizer spray to robodrobe for surgery.

## Why It's Good For The Game
Quality of robo life improvement

## Changelog
:cl:
add: Adds sterilizer spray to robodrobe
/:cl:

2020-08-27 21:56 UTC, zeskorion submitted a review, later dismissed

2020-08-30 08:59 UTC, PowerfulBacon requested changes
AdvancedAirlockControllers fucked up and need reverting

2020-08-31 19:07 UTC, PowerfulBacon commented
You reverted all the mapping changes except the airlocks (They are really fucked up in the mapping I think because the values of pixel_y and pixel_x are set so you might have to manually do that)

2020-09-01 10:40 UTC, Mick1299 commented
The mapping issue isn't with pixel x and y, its with airlock controllers occasionally not saving their set direction for some weird ass reason. You need to manually set all the directions for them

2020-09-02 08:01 UTC, zeskorion submitted a review, later dismissed

2020-09-02 08:16 UTC, PowerfulBacon commented
Check the map renders details and diffs. There is still 1 airlock that was messed up by the mapmerger

2020-09-02 08:16 UTC, PowerfulBacon reviewed
a

2020-09-02 08:18 UTC, PowerfulBacon approved these changes, later dismissed
Approving to remove the change request for Zesko, since he says the airlock controller should be fine, but really I wouldn't want that changed in diffs since I don't think it will be fine.

2020-09-02 08:19 UTC, zeskorion commented
nah, looked over again, diffbot isnt very clear. gonna wait for it to be fixed

2020-09-02 08:22 UTC, PowerfulBacon reviewed
Bug with advanced airlock controllers cause them to break in fastdmm2, you will have to revert these

2020-09-02 08:22 UTC, PowerfulBacon commented on _maps/map_files/Deltastation/DeltaStation2.dmm
>  	},
This

2020-09-02 08:22 UTC, PowerfulBacon commented on _maps/map_files/PubbyStation/PubbyStation.dmm
>  	},
Not related to PR, should be removed

2020-09-02 08:22 UTC, PowerfulBacon commented on _maps/map_files/PubbyStation/PubbyStation.dmm
>  	},
And here

2020-09-02 08:22 UTC, PowerfulBacon commented on _maps/map_files/PubbyStation/PubbyStation.dmm
>  	},
And this

2020-09-02 08:22 UTC, PowerfulBacon commented on _maps/map_files/PubbyStation/PubbyStation.dmm
>  	},
And this

2020-09-02 08:22 UTC, PowerfulBacon commented on _maps/map_files/PubbyStation/PubbyStation.dmm
>  	},
And this

2020-09-02 08:22 UTC, PowerfulBacon commented on _maps/map_files/PubbyStation/PubbyStation.dmm
>  	},
And this

2020-09-02 08:22 UTC, PowerfulBacon commented on _maps/map_files/PubbyStation/PubbyStation.dmm
>  	},
And here

2020-09-05 20:09 UTC, PowerfulBacon approved these changes

2020-09-05 20:09 UTC, merged