MedSec/Hybrid HUD - Assemby and Dissasembly
BeeStation/BeeStation-Hornet pull request #2356
Opened 2020-08-29 20:06 UTC by eeSPee

##  About The Pull Request

Adds the ability to craft MedSec Hud to your little spessman, and the ability to screwdriver it to disassemble into two separate med+sec hud.

## Why It's Good For The Game

Medsec is quite versatile little piece of equipment, suitable for command members and Brrig Physicians. Trade off flash resistance for ability to see both Med and Sec displays at the same time.

## Changelog
:cl:
First push.
/:cl:

2020-08-30 07:49 UTC, PowerfulBacon approved these changes

2020-08-30 07:49 UTC, PowerfulBacon commented
Fix your changelog

2020-09-01 02:20 UTC, Mick1299 commented
I was under the impression that getting all three huds was meant to be a challenge

2020-09-14 17:09 UTC, zeskorion requested changes
Fails travis

2020-10-17 22:48 UTC, closed without merging