Billy Club Changes
BeeStation/BeeStation-Hornet pull request #2417
Opened 2020-09-08 13:35 UTC by eeSPee

#2222  About The Pull Request

Sec officers, Wardens and HoS no longer start with billy clubs. They can get them in Sec Vending Machine if needed. Also billy clubs may spawn in maints.

## Why It's Good For The Game

Billy clubs are generally useless for sec. 

## Changelog
:cl:
del: billy clubs from starting items on sec
add: billy clubs in sec vending
add: billy clubs may spawnw in maints
/:cl:

2020-09-08 16:49 UTC, zeskorion requested changes

2020-09-08 16:49 UTC, zeskorion commented on code/game/objects/items/weaponry.dm
> +	desc = "Excelent at breaking down shields."
Spelling error

2020-09-08 16:49 UTC, zeskorion commented on code/_globalvars/lists/maintenance_loot.dm
> +	/obj/item/club = 1,
Nah, remove this from the random loot pool

2020-09-08 16:50 UTC, zeskorion commented
Also: need to reduce secbelt slots back to 5

2020-09-08 17:39 UTC, eeSPee commented
> Also: need to reduce secbelt slots back to 5

No, because it already comes in secbelts. That remains unchanged.

2020-09-09 21:43 UTC, zeskorion commented
> > Also: need to reduce secbelt slots back to 5
> 
> No, because it already comes in secbelts. That remains unchanged.

 Honestly, it's a specialized tool, just remove it from those as well

2020-09-09 22:05 UTC, eeSPee commented
Fair enough.

2020-09-10 16:21 UTC, Victor239 commented
No, the fact that crew and antags now have access to Bee's buffed version of blocking means that one is necessary for dealing with them. Remove the backpack one but keep the sec belt one. 

Zesko's salt suggestion is simply because I've got a PR that's being voted on _right now_ that fixes sec belts slots. Ignore him.

2020-09-10 16:27 UTC, Victor239 commented
@PowerfulBacon check Zesk making grudge code reviews to get my existing (winning) vote immediately reversed. 

@zeskorion honestly it's really embarassing hating on sec to this level that you're still chasing after this change.

2020-09-10 16:55 UTC, PowerfulBacon commented
> @PowerfulBacon check Zesk making grudge code reviews to get my existing (winning) vote immediately reversed.
> 
> @zeskorion honestly it's really embarassing hating on sec to this level that you're still chasing after this change.

Your PR adds slots to the webbing and doesn't change the secbelts

2020-09-10 16:55 UTC, PowerfulBacon approved these changes, later dismissed

2020-09-10 17:14 UTC, Victor239 commented
It does change sec belts. Currently their storage space can't be fully utilised, thus leaving an empty slot. The PR fixes that unusable slot. Zesk's suggestion reverses the fix by removing that slot again.

2020-09-11 09:39 UTC, eeSPee commented
@PowerfulBacon what was your review about? I pushed the changes and it deleted the changes.

2020-09-12 12:02 UTC, PowerfulBacon commented
Conflicts

2020-09-14 10:57 UTC, eeSPee commented
> Conflicts

should I remove the changes to toolbelts?

2020-10-04 20:00 UTC, zeskorion commented
espee does not seem to know how to resolve conflicts, closing

2020-10-04 20:00 UTC, closed without merging