You can now recolo(u)r lightbulbs (#44122)
BeeStation/BeeStation-Hornet pull request #2456
Opened 2020-09-14 14:27 UTC by Cenrus

https://github.com/tgstation/tgstation/pull/44122

Use a spraycan on lights to recolour them. Nice if you want to create an atmospheric bar

:cl: nemvar
add: Colored lights now shine in different colours.
/:cl:

2020-09-14 15:30 UTC, ike709 commented on code/modules/power/lighting.dm
>  /obj/machinery/light/update_atom_colour()
hmmm

2020-09-14 15:31 UTC, ike709 commented
How does this interact with bacon's area-based lighting?

2020-09-14 16:19 UTC, Cenrus commented
![image](https://user-images.githubusercontent.com/31044876/93111408-796ab480-f6ae-11ea-8e5b-b760fd4be508.png)

Works fine

2020-09-14 16:22 UTC, eeSPee commented
But can it change the light of coulours? I think not.

2020-09-14 17:51 UTC, Sinmero commented
Works fine.

![123](https://user-images.githubusercontent.com/38570414/93120088-83e77700-f6cb-11ea-9035-f51b856594df.png)

2020-09-16 06:30 UTC, PowerfulBacon commented on code/modules/power/lighting.dm
>  /obj/machinery/light/update_atom_colour()
There are 2 update atom colour procs btw

2020-09-16 11:55 UTC, PowerfulBacon requested changes

2020-09-16 11:55 UTC, PowerfulBacon commented on code/modules/power/lighting.dm
> +	update()
```suggestion
```

2020-09-16 12:05 UTC, Cenrus commented
I could have sworn I already got rid of that extra proc, sorry

2020-09-16 12:06 UTC, PowerfulBacon approved these changes

2020-09-17 15:13 UTC, merged