Bridge and other high security areas now start with reinforced airlocks
BeeStation/BeeStation-Hornet pull request #2458
Opened 2020-09-15 21:08 UTC by ivanmixo

## About The Pull Request

This PR changes all the bridge, head of staffs' office airlocks, EVA, teleporter and gateway to fully plasteel reinforced doors.
These doors take longer to hack and are not breakable with a fire axe. 

Note: this changes Box and Meta station. I will the rest of the maps if this gets merged.

## Why It's Good For The Game

Tiding is fun, but being the one getting tided isn't. This would theoretically give captain a bit more time to get his shit and leave or more time to call security over (if it exists) and prepare a defense against the AA rush, while also requiring a little bit more effort from the ones tiding (insuls are mandatory when trying to hack plasteel reinforced doors). 

## Changelog
:cl:
tweak: Airlocks to bridge and other high security areas such as the heads' offices, EVA, teleporter and gateway now start reinforced with plasteel.
/:cl:

2020-09-15 21:26 UTC, TotallyNotChief commented
that's actually pretty good

2020-09-15 21:35 UTC, ivanmixo commented
> on second thought the meta would just shift to using thermite or unwelding cap's office maint walls on box and then it'll be just as bad

Still more effort than just hacking in (as a greyshirt at least).

2020-09-16 07:51 UTC, Victor239 commented
No. This is just a PR to fix Golden's absurd spare rush culture, which should be a policy change. This would make it far harder for legitimate antags to break into these areas.

2020-09-16 08:36 UTC, TotallyNotChief commented
> This would make it far harder for legitimate antags to break into these areas.

as if that's a bad thing

2020-09-16 12:29 UTC, Blueturbo47 commented
It also gives more power to ai, longer hacking doors means longer ai can lock people in places. Also now ai's robotics console is harder to get to. But ill leave my vote neutral.

2020-09-17 00:17 UTC, francinum commented
I'd recommend demoting it to metal.

2020-09-20 17:01 UTC, qwertyquerty approved these changes

2020-09-20 17:02 UTC, qwertyquerty requested changes
@ivanmixo get the rest of the maps

2020-09-20 17:52 UTC, ivanmixo commented
@qwertyquerty okay, done

2020-09-21 14:25 UTC, qwertyquerty commented
On second thought this should be a code change not a mapping change. Just change the security level of the command airlocks in code.

2020-09-21 19:49 UTC, ivanmixo commented
> On second thought this should be a code change not a mapping change. Just change the security level of the command airlocks in code.

christ dude

2020-09-29 04:04 UTC, qwertyquerty commented
@ike709 broken checks

2020-09-29 04:04 UTC, qwertyquerty approved these changes

2020-09-29 04:06 UTC, qwertyquerty requested changes
Wait a minute why did you keep the mapping changes they do nothing

2020-09-30 18:47 UTC, ivanmixo commented
Because this PR reinforces the armoury/warden's office as well.

2020-10-04 20:14 UTC, zeskorion approved these changes

2020-10-12 11:39 UTC, Doosteroni commented
This is so lame you beepeople are tasteless

2020-10-18 15:36 UTC, ivanmixo commented
How long is this merge gonna get delayed? This is more then a month old at this point.

2020-10-24 20:38 UTC, PowerfulBacon reviewed
There are a lot of random doors being given security_level = 6 in the .dmi file when the doors already have it from the airlock type

2020-10-25 14:50 UTC, ivanmixo commented
> There are a lot of random doors being given security_level = 6 in the .dmi file when the doors already have it from the airlock type

.dmi? 

Again, this is completely irrelevant. Doing it all through files would make all of security reinforced, which is not what I wanted. The map changes are necessary so only armoury/warden office is reinforced. It isn't random doors.

2020-11-03 18:00 UTC, merged