Adds job titles to radio messages
BeeStation/BeeStation-Hornet pull request #2514
Opened 2020-09-21 22:32 UTC by Victor239

## About The Pull Request
Radio messages now show the speaker's job after their name, based on the crew manifest job (and updated if it's changed of course). 

Example:
> [Common] John Doe (Assistant) says, "Test."

## Why It's Good For The Game
Allows you to see the jobs of who you're talking to over radio, which is helpful when seeing people asking for help or telling you about stuff they're working on etc. 

## Changelog
:cl:
add: Radio messages now show the speaker's job after their name
/:cl:

Ports:
https://github.com/WaspStation/WaspStation-1.0/pull/30

2020-09-22 01:27 UTC, TeomanTheGreat commented
Victor considering all these recent pr's you've been making are you trying to turn us into para?

2020-09-22 05:30 UTC, BeloneX commented
> Victor considering all these recent pr's you've been making are you trying to turn us into para?

all of these are from wasp

2020-09-22 06:00 UTC, ike709 commented
Actually this is from Oracle via Wasp.

2020-09-22 06:35 UTC, PowerfulBacon commented
Personally, I dont like this and prefer the cleaner format we had before, having only the AI able to see what jobs people are

2020-09-22 12:27 UTC, Blueturbo47 commented
Is this what job your id says or what job your variables say? And I don't see why anyone knows anyone's job on comms and it would be helpful to stay hidden by people not knowing your job. Would make sense for just the ai to know jobs though.

2020-09-22 12:58 UTC, Gregolry commented
From a logical perspective this makes little sense to me. Why would you know someone’s job just from hearing them on comms?

2020-09-22 13:52 UTC, Bestparty commented
yo victor next time just rebase bee to para

2020-09-22 14:44 UTC, Victor239 commented
It shows your current job on crew manifest. So if you update your ID to have a new job it'll similarly update. 

IC-wise it follows the same logic as why you can identify anyone's full name just from hearing them talk on radio, whether it be golems, agent ID'd syndicate agents, etc. 

I've never played Para and I doubt you have save those snide responses.

2020-09-23 16:34 UTC, Isy232 commented
I think this is good, as the only other way to identify the head of your department is to have them talk on big text or to check a manifest.

2020-09-24 04:45 UTC, francinum commented
Mildly helpful at the cost of excess clutter.

2020-09-24 06:21 UTC, ike709 commented
Eh I think heads of staff should have their job title shown because:
1. We tell people their department head at roundstart anyways.
2. Listen to your boss for the love of Christ.

I'm iffy on job titles for non-heads.

2020-09-24 06:31 UTC, PowerfulBacon commented
Heads of staff have big text anyway, and if they are talking to their department / people they are command of, then they will be the only person with command text on their comms so do not need a job title

2020-09-24 06:31 UTC, ike709 commented
Also a good point.

2020-09-24 07:18 UTC, Victor239 commented
It has the most utility on common comms so it's intended to be visible there. 

My hope is additionally that more considerate heads of staff will be able to stop using high volume always too, since crew will have this smaller signal that the person speaking is command. High volume can then be relegated to true announcements and emergency messages rather than just telling jokes or whatnot.

2020-10-03 15:41 UTC, PowerfulBacon commented
Personally I don't think this fits the more modern look, and have only really seen it on super old servers. I think it would add too much clutter and would just look a bit weird.

2020-10-04 09:51 UTC, PowerfulBacon requested changes

2020-10-04 09:51 UTC, PowerfulBacon commented on code/game/say.dm
> +	return "[ speakerJob ? " (" +  speakerJob + ")" : ""]"
Use "([variable])" rather than "(" + variable + "}"

2020-10-04 19:58 UTC, PowerfulBacon commented
Going to close this, for a few reasons
 1. A lot of clutter in chat (especially for long job names and loud mode messages).
 2. Doesn't make a lot of sense just hearing someone over comms and knowing their job.
 3. It's a power reserved for AI
 4. It kind of looks a bit shit.

2020-10-04 19:58 UTC, closed without merging

2020-10-04 21:56 UTC, Victor239 commented
This passed the vote bruh. 

And it makes sense the same way that you know anyone's voice on radio even if they're a lavaland agent. My headcanon is the radio announcement system appends their name and job before their message.

2020-10-04 21:59 UTC, ike709 commented
I'm kind of indifferent on this PR but I would like to point out that bee isn't a democracy and that the votes are purely for collecting feedback.