fix(build): some fixes for better hosting experience
BeeStation/BeeStation-Hornet pull request #2528
Opened 2020-09-23 13:42 UTC by Epicus7

Hello there! We are running the Russian server with fork of Beestation and encountered some problems, which are pretty annoying for hosting. Here our fixes for them.

* Add configs to .gitignore, similary to Bay builds. This fix doesn't touch subfolder of `config/`, only actual config files.
* Fix byond-extools library loading for Linux
* Use config instead of hardcoded urls in the server description for byond hub

2020-09-23 14:27 UTC, BeloneX commented
thank you tovarish

2020-09-23 14:32 UTC, PowerfulBacon commented
The configs are included in the repo, so that anyone that downloads a fork of Bee can have the exact config we use for a quicker setup and is manually updated

2020-09-23 17:28 UTC, Epicus7 commented
> The configs are included in the repo, so that anyone that downloads a fork of Bee can have the exact config we use for a quicker setup and is manually updated

But I can't change configs as I need, without copying entire build somewhere else from the local repository. It affects git's status and cause problems with updating the repository on host.

Baystation-like builds uses different folder `config/example` to store examples. There I can copy the examples to `config/`, change it as i need and everything works alright. With BeeStation i need somehow circumvent git in order to change configs and do not broke repository.

The only thing, I don't sure if `config/Sage` folder can be used as example. If it doesn't and it is just a config of second server, i can move deleted configs to new `example` folder.

2020-09-24 01:23 UTC, francinum commented
@Epicus7 You should be running your server through https://github.com/tgstation/tgstation-server, which includes support for static files, as well as various other support systems, and is tightly integrated with the codebase.

2020-09-25 15:35 UTC, Crossedfall requested changes
Outside of the changes to `.gitignore` I consider the rest to be a welcome cleanup.

2020-09-25 15:35 UTC, Crossedfall commented on .gitignore
> +!config/title_screens/
```suggestion
```

2020-09-25 19:27 UTC, Crossedfall commented
I actually misread the PR during my last review. I thought you were removing some trash files we used to have, but that's not actually the case. Just going to close this since it's not something we're going to be merging.

2020-09-25 19:27 UTC, closed without merging