some syringe injecting fixes
BeeStation/BeeStation-Hornet pull request #2664
Opened 2020-10-09 06:21 UTC by zeskorion

## About The Pull Request
-lengthens time to embed
-failing embed no longer attempts to inject
-borgs can no longer embed
## Why It's Good For The Game

fix
## Changelog
:cl:

fix: syringe stuff
/:cl:

2020-10-09 14:34 UTC, PowerfulBacon requested changes
There should be a message saying [user] is trying to inject L like there is normally, so you aren't just randomly stabbed

2020-10-09 14:35 UTC, axpov approved these changes, later dismissed

2020-10-09 15:54 UTC, zeskorion commented
> There should be a message saying [user] is trying to inject L like there is normally, so you aren't just randomly stabbed

Ah, yeah. When i get home

2020-10-10 03:05 UTC, zeskorion commented
> There should be a message saying [user] is trying to inject L like there is normally, so you aren't just randomly stabbed

done

2020-10-10 06:13 UTC, PowerfulBacon approved these changes

2020-10-10 06:13 UTC, merged