Sound fading subsystem, ambience fading.
BeeStation/BeeStation-Hornet pull request #2680
Opened 2020-10-11 09:30 UTC by PowerfulBacon

## About The Pull Request

Adds in the ability to have sounds fades.
Makes sounds fade in and out for the ambient buzz.

## Why It's Good For The Game

It sounds so good and so smooth.

## Changelog
:cl:
add: Ambient fading
add: Sound effect subsystem
/:cl:

2020-10-11 16:30 UTC, qwertyquerty requested changes

2020-10-11 16:30 UTC, qwertyquerty commented on code/controllers/subsystem/ambience.dm
> +			M.client.ambient_buzz_sound = sound_in
Should be A.ambient_buzz

2020-10-11 16:33 UTC, qwertyquerty commented
Fade should be a subtype of sound effect, so we can have more than one sound effect. The sound effect datum should handle all changes to the sound within itself

2020-10-11 17:28 UTC, PowerfulBacon commented
> Fade should be a subtype of sound effect, so we can have more than one sound effect. The sound effect datum should handle all changes to the sound within itself

Alright, could make it useful for something like sounds that have their position updated as you move too

2020-10-14 15:20 UTC, PowerfulBacon commented
@qwertyquerty updated to your specifications, pushing in a bit

2020-10-17 18:32 UTC, qwertyquerty commented on code/controllers/subsystem/sound.dm
> +		id = "[id][A]"
Should probably be REF(A)

2020-10-17 18:32 UTC, qwertyquerty commented on code/controllers/subsystem/sound.dm
> +/proc/sound_fade(sound/S, start_volume = 100, end_volume = 0, time = 10, var/listeners)
I don't like this. This should all be done in the New() of /sound_effect and the New() of /sound_effect/fade

Possibly add a proc to sound effects to begin them

2020-11-06 03:34 UTC, ike709 commented
Address qwerty's comments.

2020-11-11 20:56 UTC, ike709 commented
@qwertyquerty Re-review

2020-11-25 03:51 UTC, ike709 commented
@qwertyquerty reeeeeee

2020-11-28 12:19 UTC, PowerfulBacon commented
@qwertyquerty

2020-11-28 12:19 UTC, PowerfulBacon commented
@qwertyquerty

2020-11-28 12:19 UTC, PowerfulBacon commented
@qwertyquerty

2020-11-28 12:19 UTC, PowerfulBacon commented
@qwertyquerty

2020-11-28 19:17 UTC, qwertyquerty approved these changes

2020-11-28 19:18 UTC, merged