Fix assmly GUI not working in TGUI TTV
BeeStation/BeeStation-Hornet pull request #2707
Opened 2020-10-13 17:41 UTC by Autisem

## About The Pull Request
closes issue #2700 which prevented you from opening the assembly GUI when its inside the TTV.

This happened because `ui_status` only checked if the object is can be interacted with and not the object containing itself. Its not fully tested with all assembly's but it works on the timer at least.

## Why It's Good For The Game
fix bug good yes

## Changelog
:cl:
fix: assembly's now can be interacted with while inside other objects like TTV
/:cl:

2020-10-13 18:07 UTC, TotallyNotChief commented
does using a ttv in hand open the new tgui3 interface now? because its implemented and it works if you click on a ttv as a ghost

2020-10-13 18:14 UTC, ItsTisme commented
> does using a ttv in hand open the new tgui3 interface now? because its implemented and it works if you click on a ttv as a ghost

When you open the TTV, you have a option that says the assmbly name and "remove", this makes it so when you actuely press the assmebly name item you open its GUI and are free to edit is aslong as you have acces to the TTV itself

2020-10-14 14:54 UTC, PowerfulBacon requested changes
Change the actual ui_interacts that are called to have a different default_state, so instead of 
/obj/item/assembly/timer/ui_interact(mob/user, ui_key = "main", datum/tgui/ui = null, force_open = FALSE, \
									datum/tgui/master_ui = null, datum/ui_state/state = GLOB.hands_state)
you would have GLOB.hands_state as whatever state is required for it

2020-10-14 16:52 UTC, Autisem commented
> Change the actual ui_interacts that are called to have a different default_state, so instead of
> /obj/item/assembly/timer/ui_interact(mob/user, ui_key = "main", datum/tgui/ui = null, force_open = FALSE,
> datum/tgui/master_ui = null, datum/ui_state/state = GLOB.hands_state)
> you would have GLOB.hands_state as whatever state is required for it

I may miss understand what your trying to say here. But assuming you say I make my own `GLOB.hands_state`..

`hands_state` is logic that checks once a UI is opend wether it should remain open. I could make my own version of this but it seems redudent since the `hands_state` checks for alot of logic wether carbons are holding something and making another global value to snowflake assembly hand state seems unneeded

Or iam getting wrong what yout trying to say

2020-10-17 18:05 UTC, PowerfulBacon submitted a review, later dismissed
This if fine actually

2020-10-24 18:42 UTC, PowerfulBacon commented on code/modules/assembly/assembly.dm
> +		. = max(., UI_INTERACTIVE)
Might as well just return UI_INTERACTIVE

2020-11-06 03:38 UTC, ike709 commented on code/modules/assembly/assembly.dm
> +		. = max(., UI_INTERACTIVE)
```suggestion
		return UI_INTERACTIVE
```

2020-11-06 03:38 UTC, ike709 commented on code/modules/assembly/assembly.dm
> +	.= ..()
```suggestion
	. = ..()
```

2020-11-06 03:48 UTC, merged