standardizes spray stuns
BeeStation/BeeStation-Hornet pull request #2738
Opened 2020-10-17 22:32 UTC by zeskorion

## About The Pull Request
spraycan now checks eye covering instead of flash protection
pepper spray now checks mouth and eye covering instead of a snowflake flag

## Why It's Good For The Game
one snowflak flag for one reagent is terribles
spray paint shouldnt be as useful as a flash

## Changelog
:cl:
code: pepper proofing now checks eye and mouth covering instead of a snowflake flag
fix: spraypaint now uses eye covering instead of flash protection
/:cl:

2020-10-18 07:52 UTC, PowerfulBacon commented
This makes it so all glasses protect from pepperspray, as well as all breathe masks?

2020-10-19 06:56 UTC, bloons3 commented
Would it make sense for only eye coverings that shroud the eyes (like goggles, eye obscuring masks) to protect from pepper spray instead of all eye coverings?

2020-10-24 14:33 UTC, PowerfulBacon requested changes
Instead of standardizing it by making literally anything on the eyes protect from stuns making the items useless, why not standardize it by using the PEPPERPROOF flag check on spraycans

2020-10-25 09:02 UTC, PowerfulBacon commented
In its current form this isn't well balanced. The standardization should use PEPPERPROOF to check for all rather than check if they are wearing anything for all, since it just doesn't make sense for somethings to be pepperproof like an eyepatch.
Feel free to reopen if you change it in some way.

2020-10-25 15:30 UTC, zeskorion commented
> In its current form this isn't well balanced. The standardization should use PEPPERPROOF to check for all rather than check if they are wearing anything for all, since it just doesn't make sense for somethings to be pepperproof like an eyepatch.
> Feel free to reopen if you change it in some way.

You read this wrong. You need both a gas mask and eye shit to protect from spraycan. Spraycans were intended to check eye covering, but used flash protection instead for some reason

2020-10-25 15:32 UTC, Moccha-Bee commented
gas mask already covers your eyes and mouth, make it pimenta proof

2020-11-06 03:51 UTC, merged

2020-11-06 03:53 UTC, ike709 commented
What could go wrong?

2020-11-06 09:05 UTC, PowerfulBacon commented
pepperspray now blocked by default breath mask and cosmetic goggles