Teratomas are actual antags now
BeeStation/BeeStation-Hornet pull request #2782
Opened 2020-10-23 00:41 UTC by Archanial

## About The Pull Request

This PR will require SQL changes, since it adds ROLE_TERATOMA to banning panel.

This PR changes how (ling) teratomas are spawned and adds antag datum to them (basically makes admin work much easier and you can greentext as teratoma).
The teratoma will now burst after 5 seconds from the user, which will create some gibs.
You can now "teratomize" user in TP.
The maint teratomas (from mobspawners) get different antag datum, which tells you basically not to kill.
Teratomas cannot be DNA stung or made into human by mutadone.
I also touched a little of monki code, and refactored one thing since it was shitcode.

Please do not merge for now, since I need to figure how to restrict them from DNA machines.

## Why It's Good For The Game

Improvement and teratoma nerf (no more creating army with dna sting).

## Changelog
:cl:
add: Teratomas are actual antagonists now!
add: You can now make someone teratoma in traitor panel.
tweak: Teratomas cannot be made into a human with DNA sting or by mutadone!
refactor: fixed some shitcode in monkey (who cares).
/:cl:

2020-10-23 00:55 UTC, leestriter commented
What about virus spawned teratomas? Treated like maint teratomas?

2020-10-23 00:56 UTC, Archanial commented
> 
> 
> What about virus spawned teratomas? Treated like maint teratomas?

Yes

2020-10-23 10:38 UTC, BeloneX commented
Why not give the maint teratomas the pacifist trait?

2020-10-23 12:08 UTC, Archanial commented
> 
> 
> Why not give the maint teratomas the pacifist trait?

because iirc they follow lavaland escalation, that means they can kill in self defence but cannot mass grief/murderbone.
That wouldn't stop maint teratomas from for example flooding with plasma, but would make their life hell, since they could not respond to any attacks.

2020-10-23 12:26 UTC, BeloneX commented
> > Why not give the maint teratomas the pacifist trait?
> 
> because iirc they follow lavaland escalation, that means they can kill in self defence but cannot mass grief/murderbone.
> That wouldn't stop maint teratomas from for example flooding with plasma, but would make their life hell, since they could not respond to any attacks.

Maint teratomas are shitty by concept honestly.

2020-10-24 20:26 UTC, PowerfulBacon commented on code/modules/antagonists/changeling/powers/teratoma.dm
> +	c.chem_charges -= chemical_cost				//I'm taking your chemicals hostage!
Isn't this going to use double chemicals, since chemical subtraction is already handled when sting_action is called

2020-10-24 20:43 UTC, Archanial commented on code/modules/antagonists/changeling/powers/teratoma.dm
> +	c.chem_charges -= chemical_cost				//I'm taking your chemicals hostage!
I thought of it.
My initial idea was to take chems hostage and return them.
But if sting action returns false it doesn't take them anyway, so I just simply take them here.

2020-10-28 04:53 UTC, zeskorion approved these changes, later dismissed
surprised teratomas became this much of a thing people love. approving for codeowner shit i guess

2020-10-29 17:32 UTC, PowerfulBacon requested changes
Specifically specify to the maint ones not to kill people

2020-10-29 17:34 UTC, BeloneX commented
> Specifically specify to the maint ones not to kill people

You and I both know that won't stop them from doing it, maintenance Teratomas should be just scrapped entirely.

2020-10-29 17:34 UTC, PowerfulBacon commented
They should, but you still need to specify and differentiate for bannings sake

2020-10-29 18:26 UTC, Archanial commented
> 
> 
> Specifically specify to the maint ones not to kill people

`to_chat(owner, "<span class='userdanger'>Avoid killing unprovoked, kill only in self defense!</span>")`

2020-11-14 10:04 UTC, PowerfulBacon approved these changes

2020-11-14 10:04 UTC, merged