Fixes heretics getting IC mutted for spamming grasp.
BeeStation/BeeStation-Hornet pull request #2825
Opened 2020-10-27 11:24 UTC by eeSPee

## About The Pull Request

Adds multiple catch phrases to grasp touch melee spells, to prevent them from IC muting the caster. This is especially notable for heretics' mansus grasp.

## Why It's Good For The Game

Oversight.

## Changelog
:cl:
tweak: touch spells cycle through multiple 'catchphrases' to prevent casters (especially heretics) from getting muted by casting them repeatedly.
/:cl:

2020-10-27 12:52 UTC, PowerfulBacon commented
This shouldn't happen if they are forced, there is a bigger issue if forced says are muting people IC

2020-10-27 13:23 UTC, eeSPee commented
Last round I played heretics I got IC muted for using mansus grasp and nothing else. There could be a bigger issue.

2020-11-01 17:20 UTC, MNarath1 commented
> This shouldn't happen if they are forced, there is a bigger issue if forced says are muting people IC

Funny thing i made like half a yeah ago a Issue about that during an old clockcult round where i got muted after speed cogging apc's had to ahelp to unmute
https://github.com/BeeStation/BeeStation-Hornet/issues/476 thats the one so yes its very much possible to get muted thanks to forced speech

2020-11-08 14:49 UTC, PowerfulBacon requested changes
The issue isn't with heretics, but with the forced say code not being checked for IC spam. This happens on all spells and other things too and having random phrases is more of a band aid than an actual fix

2020-11-16 23:00 UTC, eeSPee commented
The issue is more complex...

2020-11-16 23:00 UTC, closed without merging