Revert "Disables the roundstart report on sage."
BeeStation/BeeStation-Hornet pull request #2830
Opened 2020-10-27 23:53 UTC by Cenrus

Reverts BeeStation/BeeStation-Hornet#2741

Broke station goals, preventing them from showing in the supply catalog. It's also likely to contain false information, so not such a good source of metaknowledge after all.

2020-10-28 00:25 UTC, BeloneX commented
> Reverts #2741
> 
> Broke station goals, preventing them from showing in the supply catalog. It's also likely to contain false information, so not such a good source of metaknowledge after all.

They do show up in the supply catalog.

2020-10-28 12:25 UTC, Cenrus commented
![picture](https://user-images.githubusercontent.com/31044876/97435590-8965ed00-1918-11eb-872f-126a4639e4e2.PNG)

Are you sure? I they're supposed to be under the Engineering category.

2020-10-28 12:31 UTC, BeloneX commented
> ![picture](https://user-images.githubusercontent.com/31044876/97435590-8965ed00-1918-11eb-872f-126a4639e4e2.PNG)
> 
> Are you sure? I they're supposed to be under the Engineering category.

You're right, it's not there.

2020-10-28 16:16 UTC, ike709 commented
Just separate station goal code from gamemode report code.

2020-11-08 14:35 UTC, PowerfulBacon requested changes
I think removing it was a good change, separate it from gamemode code like ike suggested

2020-11-17 18:40 UTC, closed without merging