Emag shuttles
BeeStation/BeeStation-Hornet pull request #2841
Opened 2020-10-28 23:01 UTC by Archanial

## About The Pull Request

This here adds new config file (and renames the old one) in which you specify which shuttles can be bought if the comms console has been emagged.
I've locked a few shuttles behind emag in this PR but this is still subject to change.
closes #2828

## Why It's Good For The Game

Bad shuttles are literal banbait right now. This limits them while not completely removing from the game.
Also this adds actual use to emagging the comms console.

## Changelog
:cl:
add: New option to have a shuttle be only buy-able after comms console is emagged.
/:cl:

2020-10-28 23:03 UTC, BeloneX commented
good PR.

2020-10-28 23:12 UTC, BeloneX commented on code/datums/shuttles.dm
> +	var/syndicate_exclusive = FALSE	//makes you able to buy the shuttle in emaged comms console even if can_be_bought is FALSE
grammar correction, should be.
//makes you able to buy the shuttle at a emagged comms console even if can_be_bought is FALSE

2020-10-28 23:17 UTC, BeloneX requested changes
Correct the grammar with what i provided.

2020-10-28 23:17 UTC, BeloneX commented on config/Sage/shuttles_unbuyable.txt
> +##Listing maps here will make the shuttle be avaialable to be bought if comms console is emagged
```suggestion
##Listing maps here will make the shuttle be available to be bought if the comms console is emagged
```

2020-10-28 23:17 UTC, BeloneX commented on code/game/machinery/computer/communications.dm
> +						dat += "<b> Shuttle supplied by Syndicate, order on your own risk: </b>"
```suggestion
						dat += "<b> Shuttle supplied by the Syndicate, order at your own risk: </b>"
```

2020-10-28 23:17 UTC, BeloneX commented on code/datums/shuttles.dm
> +	var/syndicate_exclusive = FALSE	//makes you able to buy the shuttle in emaged comms console even if can_be_bought is FALSE
```suggestion
	var/syndicate_exclusive = FALSE	//makes you able to buy the shuttle at a emagged comms console even if can_be_bought is FALSE
```

2020-10-28 23:56 UTC, Archanial reviewed
how do I close this window

2020-10-28 23:56 UTC, Archanial commented on code/datums/shuttles.dm
> +	var/syndicate_exclusive = FALSE	//makes you able to buy the shuttle in emaged comms console even if can_be_bought is FALSE
actually "at an emagged"

2020-10-29 22:06 UTC, BeloneX commented
proof that oracle was years ahead of us https://github.com/OracleStation/OracleStation/pull/707/

2020-10-29 23:25 UTC, TheFakeElon commented
Emagged consoles probably shouldn’t read out the name of who bought the shuttle. Unless bloodbaths are something your aiming for

2020-10-30 15:54 UTC, Gregolry commented
That's kinda on the antag, if they don't wanna get lynched for buying a shitty shuttle then they should get an ID with another name or get gud

2020-11-02 00:40 UTC, eeSPee commented
> Emagged consoles probably shouldn’t read out the name of who bought the shuttle. Unless bloodbaths are something you’re aiming for

Agent ID, pal.

2020-11-02 00:51 UTC, TheFakeElon commented
@Gregolry @eeSPee lol, the announcer name uses usr.real_name not the ID card

2020-11-07 09:36 UTC, PowerfulBacon commented
I think it should be unlocked through screwdrivering the board, so antagonists without emag can buy them, self antaggers who are going to get banned can buy them and you can't accidently buy them thinking the 100k shuttle named hyperfractal gigashuttle is actually really deadly

2020-11-24 19:29 UTC, PowerfulBacon commented
Closed in favour of https://github.com/BeeStation/BeeStation-Hornet/pull/2920/files

2020-11-24 19:29 UTC, closed without merging