[PORT] Replaces travis with github-actions
BeeStation/BeeStation-Hornet pull request #2902
Opened 2020-11-10 23:15 UTC by jupyterkat

## About The Pull Request

ports
tgstation/tgstation#54668
tgstation/tgstation#54833
tgstation/tgstation#54780
tgstation/tgstation#54805

## Why It's Good For The Game

Github-actions is faster and more consistent

2020-11-10 23:27 UTC, TheFakeElon commented
Godspeed, travman o7

2020-11-11 01:19 UTC, TeomanTheGreat commented
Rip Travis may he rest in peace

2020-11-11 01:42 UTC, Crossedfall commented
Add the `workflow_dispatch` trigger so we can run tests on-demand.

2020-11-11 02:04 UTC, Crossedfall commented
> Github-actions is faster and more consistent

![image](https://user-images.githubusercontent.com/26130695/98756281-d8d40080-238f-11eb-88ac-60cc3364a61b.png)

2020-11-11 02:42 UTC, jupyterkat commented
run_all_tests is not working correctly for some reason

2020-11-11 08:01 UTC, MCterra10 commented
github actions is not ready for this.

2020-11-11 23:49 UTC, Crossedfall requested changes

2020-11-11 23:49 UTC, Crossedfall commented on .github/workflows/test.yml
> +          path: deploy
```suggestion
```

Creating deploy artifacts from external forks is a terrible idea. It means that users could introduce malicious code into their PR and then GitHub would compile that into an executable deploy package that is tied to our repository.

2020-11-11 23:49 UTC, Crossedfall commented on .github/workflows/test.yml
> +    - master
```suggestion
  push:
    paths-ignore:
  	- 'html/changelogs/**'
    branches:
    - master
```

We don't want it to run for CL pushes

2020-11-17 18:52 UTC, Crossedfall commented
Alright, lets give this a go.

2020-11-17 18:52 UTC, Crossedfall approved these changes

2020-11-17 18:53 UTC, merged