Mastermode is stored as a configuration entry
BeeStation/BeeStation-Hornet pull request #2982
Opened 2020-11-21 05:26 UTC by francinum

## Changelog
:cl:
config: Default gamemode is now a config entry.
/:cl:

2020-11-21 08:12 UTC, PowerfulBacon approved these changes, later dismissed

2020-11-22 20:57 UTC, jlsnow301 commented
very fixable conflict with my PR

2020-11-25 12:53 UTC, francinum commented
I still have no idea why the test are failing.

2020-12-27 07:44 UTC, Crossedfall commented
Re-running tests, mostly because I don't remember what the error was and all the old ones were listed as canceled.

2020-12-27 11:20 UTC, Crossedfall requested changes
This wont pass the CI due to lacking configs. The CI runs with an absolutely minimum config file, whereas this requires secret config options to function. Defaulting to `extended` resolves this

2020-12-27 11:20 UTC, Crossedfall commented on code/_globalvars/game_modes.dm
> +GLOBAL_VAR_INIT(master_mode, "secret") //! Stores the current gamemode. Fuck you CIscript.
```suggestion
GLOBAL_VAR_INIT(master_mode, "extended") //! Stores the current gamemode. Fuck you CIscript.
```

2020-12-27 11:20 UTC, Crossedfall commented on code/controllers/configuration/entries/game_options.dm
> +	config_entry_value = "secret"
```suggestion
	config_entry_value = "extended"
```

2020-12-29 02:27 UTC, francinum commented on code/_globalvars/game_modes.dm
> +GLOBAL_VAR_INIT(master_mode, "extended") //! Stores the current gamemode. Fuck you CIscript.
```suggestion
GLOBAL_VAR_INIT(master_mode, "Loading...") //! Stores the current gamemode. Intentionally invalid placeholder is replaced in Ticker.
```

2021-01-14 20:24 UTC, ike709 commented
@Crossedfall config

2021-01-25 06:00 UTC, Crossedfall approved these changes
Config applied

2021-01-25 06:01 UTC, merged