Fastmos mapping improvements
BeeStation/BeeStation-Hornet pull request #3006
Opened 2020-11-24 11:22 UTC by Archanial

## About The Pull Request

This PR adds new variable to firelocks, that can be set manually to bypass the check in AACs (that sometimes fails roundstart at random I wasn't able to pinpoint the issue).
I've gone thru every map (excluding kilo which is still wip I think) and fixed every instance of AAC failing.
AI sat on delta now has fastmos cycling airlocks, window firedoors and firelocks.
I've removed some stacked (or floating) space posters on pubby.
Some external airlocks that didn't have AAC are now fixed.
Removed some double stacked glass on the pubby-chapel.
Minor improvements to box's AI sat (some walls are now reinforced and added 2 windoors).

## Why It's Good For The Game

Better maps, departures no longer get depressurized

## Changelog
:cl:
add: Delta's AI sat now fastmos compatible.
add: Fixed some AACs not working.
add: Minor improvements to box's AI sat.
del: Removed double stacked windows on pubby's chapel.
/:cl:

2020-11-25 13:37 UTC, OceanFish1 commented
finally someone adds tiny fans on ferries so ERT members don't do the "depressurize the shuttle" any % speedrun

2020-11-25 19:14 UTC, ike709 approved these changes, later dismissed

2020-11-28 02:35 UTC, francinum requested changes
The maps fail to pass check() properly due to having two doors on the edge of an area.

One door must always have the same area in every cardinal direction, and that door will be considered the internal door. This isn't a complex system and this addition is unnecessary.

2020-11-28 05:09 UTC, Archanial commented
thank you Fran.
Everything is fixed (I think).

2020-12-09 01:17 UTC, merged