Station bounced radio QOL
BeeStation/BeeStation-Hornet pull request #3010
Opened 2020-11-24 14:46 UTC by Sinmero

## About The Pull Request

Ctrl-clicking station bounced radio will toggle the speakers.
Alt-clicking station bounced radio will toggle broadcasting.

## Why It's Good For The Game

Using station bounced radios is more convenient now.

## Changelog
:cl:
tweak: Ctrl-clicking station bounced radio will toggle the speakers.
tweak: Alt-clicking station bounced radio will toggle broadcasting.
/:cl:

2020-11-24 16:42 UTC, PowerfulBacon requested changes
Shouldn't this be in /obj/item/radio rather than just the radio that defaults to off?

2020-11-24 16:44 UTC, ike709 commented
Bacon is correct.

2020-11-24 20:26 UTC, Sinmero commented
done

2020-11-25 04:05 UTC, ike709 commented on code/game/objects/items/devices/radio/radio.dm
> +	desc = "A basic handheld radio that communicates with local telecommunication networks.<br/>Alt-click on the station bounced radio to toggle broadcasting.<br/>Ctrl-click on the station bounced radio
This doesn't go here. Add it to examine().

2020-11-27 14:32 UTC, TheFakeElon commented on code/game/objects/items/devices/radio/radio.dm
> +		broadcasting = !broadcasting
use false

2020-11-27 14:32 UTC, TheFakeElon commented on code/game/objects/items/devices/radio/radio.dm
> +		listening = !listening
Use false

2020-11-29 08:41 UTC, PowerfulBacon requested changes, later dismissed
Call . = ..() if they are headsets

2020-11-30 10:12 UTC, Sinmero commented
I dont quite understand what . = ..() does. Hope its good now. Also bool = !bool is how it is written in the headset volume toggle.

2020-12-11 14:41 UTC, qwertyquerty approved these changes

2020-12-11 14:44 UTC, merged