Grey slime crystal fix
BeeStation/BeeStation-Hornet pull request #3041
Opened 2020-11-29 19:57 UTC by Ravellon

## About The Pull Request

Right now, instead of using add_nutrition() function the grey crystal directly adjusts slime's nutrition. This prevents slimes from having their life effects triggered on nutrition change, such as splitting or raising their charge, while making them unwilling to feed once nutrition rises above 1000. That makes them unwilling to split once they cross that threshold.

With this change, grey crystal will feed slimes to 996/1200 nutrition and 9/10 growth instead of overfeeding them.

## Why It's Good For The Game

This way, leaving slimes in range of crystal for some time will put them into perfect range for either breeding or crossbreeding while not risking infinite slime spawning.

## Changelog
:cl:
fix: Grey slime crystals will now slowly feed the slimes in rage to 996/1200 nutrition and 9/10 growth range, instead of overfeeding them and making them unable to split.
/:cl:

2020-11-30 14:53 UTC, TheFakeElon requested changes

2020-11-30 14:53 UTC, TheFakeElon commented on code/modules/research/xenobiology/crossbreeding/_structures.dm
> +	if((slime_mob.nutrition < 996)||(slime_mob.amount_grown < (SLIME_EVOLUTION_THRESHOLD - 1)))
Brackets aren't needed
```suggestion
	if(slime_mob.nutrition < 996) || slime_mob.amount_grown < SLIME_EVOLUTION_THRESHOLD - 1)
```

2020-11-30 22:19 UTC, TheFakeElon commented on code/modules/research/xenobiology/crossbreeding/_structures.dm
> +	if(slime_mob.nutrition < 996) || slime_mob.amount_grown < SLIME_EVOLUTION_THRESHOLD - 1)
Messed up the initial code suggestion lmao, my bad

```suggestion
	if(slime_mob.nutrition < 996 || slime_mob.amount_grown < SLIME_EVOLUTION_THRESHOLD - 1)
```

2020-11-30 22:29 UTC, Ravellon commented
I missed it too, so it's my fault for not being attentive enough.

2020-12-03 12:44 UTC, Ravellon commented
On a related note. The purple crystal is very very weak. It has 1/10 chance to heal 2 damage of any basic type or 1/8 chance to heal 2 damage to heart, lungs, liver or brain.
And it does not matter if there is no damage of the chosen type, it tries to heal it anyway and wastes the healing tick.

This is just garbage, tbh.

2020-12-07 00:12 UTC, Rukofamicom commented
> This prevents slimes from having their life effects triggered on nutrition change, such as splitting

This is not true at all. Slimes fed by the crystal grow and reproduce just the same as normal. I tested this crystal by putting it in an enclosure with one slime while doing all the rest of the bugtesting. By the time I was done with the rest of the bugtesting, the pen had 8-12 slimes per tile.

No electric charge is probably correct though. Not being able to feed is negligible since they divide anyway. Are you certain you hadn't reached the entity limit when you had your experience? This will prevent slimes from feeding and reproducing

2020-12-07 05:42 UTC, Ravellon commented
This is very weird. I managed to reproduce my issue once. The other three times it was as you described.
As in, one time they stuck at under 10 growth and got overfed, making them unable to split, even after I culled their numbers.
The other three times they continued to split after I culled the numbers.

Closing for now.

2020-12-07 05:42 UTC, closed without merging