Non-Observing Mentors now don't see the Follow button
BeeStation/BeeStation-Hornet pull request #3117
Opened 2020-12-08 23:56 UTC by Kerbin-Fiber

## About The Pull Request
Does as the title says.

## Why It's Good For The Game
It's annoying to see a Follow button and have it not work because you're a lowly mentor. While mentors *would like* to be able to follow people and **aghost,** that isn't realistic and mentors shouldn't be able to do that. This is a simple and easy fix by just removing the follow button when you can't use it, and shows it to you when you can.

Closes #127
Also fixes a small grammatical error in a comment. Just cuz.

## Changelog
:cl:
tweak: Mentors no longer see the Follow button when you can't follow the Mhelper.
/:cl:

2020-12-09 00:09 UTC, ike709 commented on code/modules/mentor/mentorhelp.dm
> +		if(isobserver(M))
Just put this in the above check.

2020-12-09 00:32 UTC, francinum requested changes
Just cull the entire follow link.

It doesn't even *work* and it never has.

`/datum/mentor/Topic()` doesn't actually exist.

2020-12-09 01:44 UTC, Sinestia commented
it doesnt work for admemes either cull it

2020-12-09 09:43 UTC, Rukofamicom commented
This is actually a potentially necessary part of one of my bounties, but I'm sure it can just be re-added in an actually functional way.

I've been trying to find a coder willing to make that link put a mentor in as that player's imaginary friend temporarily, with a return to body function when teaching is done.

2020-12-11 14:06 UTC, qwertyquerty approved these changes, later dismissed

2020-12-11 18:42 UTC, ike709 commented on code/modules/mentor/mentorpm.dm
> -			to_chat(C, "<span class='mentorfrom'>Reply PM from-<b>[key_name_mentor(src, C, 1, 0, show_char)]</b>: [msg]</span>")
Looks like you removed the wrong arg here.

2020-12-11 20:21 UTC, merged