Adds furday
BeeStation/BeeStation-Hornet pull request #3167
Opened 2020-12-15 19:56 UTC by PowerfulBacon

## About The Pull Request

https://cdn.discordapp.com/attachments/354087825936875521/788453905796825109/final_5fd8234f45b5c7009372f89e_20613.mp4

## Why It's Good For The Game

Its not

## Changelog
:cl:
add: Furday
/:cl:

2020-12-15 19:57 UTC, Archanial requested changes

2020-12-15 19:57 UTC, Archanial commented on code/modules/holiday/holidays.dm
> +	return pick("Boop", "Snoot", "Furry", "Artist")
```suggestion

```

2020-12-15 19:57 UTC, Archanial commented on code/modules/holiday/holidays.dm
> +	return pick("Boop", "Snoot", "Furry", "Artist")
thank me later

2020-12-15 19:58 UTC, bluezorua commented
### **OwO**

2020-12-15 20:00 UTC, Archanial commented
It doesn't even pass linters
smh smh my head

2020-12-15 20:00 UTC, BeloneX commented
> It doesn't even pass linters
> smh smh my head

Linters is actually broken.

2020-12-15 20:00 UTC, R3pID-4207 commented
I am not a fan of this one

2020-12-15 20:01 UTC, Archanial commented
> 
> 
> > It doesn't even pass linters
> > smh smh my head
> 
> Linters is actually broken.

THATS THE JOKE

2020-12-15 20:02 UTC, Archanial commented on code/modules/holiday/holidays.dm
> +		log_game("Furday randomly mass-purbatted everyone.")
```suggestion

```

2020-12-15 20:02 UTC, BeloneX commented
> > > It doesn't even pass linters
> > > smh smh my head
> > 
> > 
> > Linters is actually broken.
> 
> THATS THE JOKE

![image0-17](https://user-images.githubusercontent.com/47011211/102266504-d594dd00-3f18-11eb-9bf2-fc66f12bbf91.gif)

2020-12-15 20:05 UTC, PowerfulBacon commented
very important bcus 5 days til furday

2020-12-15 20:08 UTC, DatBoiTim commented
Well we know where the priorities lie.

2020-12-15 20:08 UTC, Archanial commented
bacon ohw (on his way) to get qwerty to merge another dumbass meme pr
![tenor](https://user-images.githubusercontent.com/37456678/102267053-a59a0980-3f19-11eb-839b-d8a171a4fa54.gif)

2020-12-15 20:09 UTC, Blueturbo47 commented
All felinids get felinid disease?

2020-12-15 20:09 UTC, TeomanTheGreat commented
Question am I allowed to slaughter felinids on this day?

2020-12-15 20:10 UTC, DatBoiTim commented
> bacon ohw (on his way) to get qwerty to merge another dumbass meme pr
> ![tenor](https://user-images.githubusercontent.com/37456678/102267053-a59a0980-3f19-11eb-839b-d8a171a4fa54.gif)

Felinid Paywall 2: Electric Boogaloo

2020-12-15 20:10 UTC, PowerfulBacon commented
> 
> 
> Question am I allowed to slaughter felinids on this day?

no you have to become a furry and do whatever they say

2020-12-15 20:11 UTC, TeomanTheGreat commented
> > 
> > 
> > Question am I allowed to slaughter felinids on this day?
> 
> no you have to become a furry and do whatever they say

No

2020-12-15 20:23 UTC, Penwin0 commented
Im going to cut off your grubby little hands so you cant code no more

2020-12-15 23:07 UTC, qwertyquerty commented
Get checks to pass and I merge

2020-12-16 00:57 UTC, BeloneX commented
> Get checks to pass and I merge

Merge it.

2020-12-16 02:06 UTC, OceanFish1 commented
FURRY CODING

FURRY CODING

2020-12-16 08:41 UTC, ike709 commented
no fun allowed

2020-12-16 08:41 UTC, closed without merging