Abductors get Agent IDs
BeeStation/BeeStation-Hornet pull request #3234
Opened 2020-12-25 21:13 UTC by Sinestia

## About The Pull Request

Abductors spawn with syndicate agent IDs
They can also buy replacements from their console

This has been implemented on multiple other servers, such as yogs, paradise (iirc)
## Why It's Good For The Game

Abductors now have no reason to dump you without your ID. 
## Changelog
:cl:Froststahr
add: Abductors now start with agent IDs! Just swipe a victim's ID card onto it to copy their access. 
/:cl:

2020-12-26 07:43 UTC, heepox commented
solid change 10/10

2020-12-26 14:11 UTC, Autisem commented
When iam abductor I usualy get the cap to make 2 new ID's. This is nice quality of life and makes us both waste les time. I likey

2020-12-26 14:13 UTC, Autisem requested changes
Add agent ID to the abductor outfit, this will automaticly apply them to both then

2020-12-27 00:26 UTC, Sinestia commented
> Add agent ID to the abductor outfit instead of to scientist and agent individuely, this will automaticly apply them to both then

Good suggestion, done.

2020-12-27 14:05 UTC, merged