MASSSK
BeeStation/BeeStation-Hornet pull request #3300
Opened 2021-01-03 15:27 UTC by Sinestia

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2021-01-03 15:27 UTC, Sinestia commented
Uh submitting it through vscode didn't give the opportunity to fix desc ONE SEC

2021-01-04 07:46 UTC, TheFakeElon commented
godspeed, beebot

2021-01-07 12:01 UTC, PowerfulBacon commented
whats the point though? Are there any situations in which the usage of bitflags is better for slots (since I can't really see something needing to have multiple slot flags at once)

2021-01-31 17:44 UTC, park66665 requested changes
We can reap the benefits of having a bitflag only defines for slots, but that is a PR for another time.

2021-01-31 17:44 UTC, park66665 commented on code/modules/mob/living/carbon/update_icons.dm
> +	if(client && hud_used && hud_used.inv_slots[ITEM_SLOT_MASK])
```suggestion
	if(client && hud_used && hud_used.inv_slots[TOBITSHIFT(ITEM_SLOT_MASK) + 1])
```

2021-01-31 17:44 UTC, park66665 commented on code/modules/mob/living/carbon/update_icons.dm
> +	if(client && hud_used && hud_used.inv_slots[ITEM_SLOT_NECK])
```suggestion
	if(client && hud_used && hud_used.inv_slots[TOBITSHIFT(ITEM_SLOT_NECK) + 1])
```

2021-01-31 17:44 UTC, park66665 commented on code/modules/mob/living/carbon/update_icons.dm
> +	if(client && hud_used && hud_used.inv_slots[ITEM_SLOT_BACK])
```suggestion
	if(client && hud_used && hud_used.inv_slots[TOBITSHIFT(ITEM_SLOT_BACK) + 1])
```

2021-01-31 17:44 UTC, park66665 commented on code/modules/mob/living/carbon/update_icons.dm
> +	if(client && hud_used && hud_used.inv_slots[ITEM_SLOT_BACK])
```suggestion
	if(client && hud_used && hud_used.inv_slots[TOBITSHIFT(ITEM_SLOT_HEAD) + 1])
```

2021-01-31 17:44 UTC, park66665 commented on code/modules/events/wizard/curseditems.dm
> +			loadout[ITEM_SLOT_HEAD] = /obj/item/clothing/head/kitty
You should apply `TOBITSHIFT` here.

2021-02-04 00:04 UTC, Sinestia commented
a pity i had to webedit again -- im basically clueless on resolving merge conflicts in an external tool

couldn't test these new changes yet

2021-02-04 20:26 UTC, park66665 commented
#3558 will be merged soon(tm) so I am going to wait before another review (or pestering folks with perms to TM this)

2021-02-10 23:16 UTC, TheFakeElon commented
#3558 has been merged

2021-02-24 22:00 UTC, Sinestia commented
I will have my revenge when I break a bunch of people's PRs in return

2021-02-28 09:09 UTC, Sinestia commented
alright there we go im not a klutz i promis

2021-03-23 03:28 UTC, TheFakeElon approved these changes
yolo

2021-03-23 22:45 UTC, merged