Temporarily Disables Circuit Clone Printing
BeeStation/BeeStation-Hornet pull request #3317
Opened 2021-01-06 01:00 UTC by ro5490

## About The Pull Request
Lots of admins have been complaining about circuit issues
This is a temporary fix until other things have been put in place

Removes the clone printing functionality of all circuit printers except the debug one.

(Also I havent tested to see if this works or not but it should)

## Why It's Good For The Game
You actually have to take some time to manually create circuits
This should help prevent people from just pasting grief circuit codes at roundstart.
And should slow down circuit creation in general.

## Changelog
:cl:
del: Removed the ability to print circuits from copy-pasted codes
del: Removed the Instant Cloning Circuit upgrade from the techweb
/:cl:

2021-01-06 01:01 UTC, ro5490 commented
This is a temp fix til either logging is fixed, bugs are patched, or someone else removes circuits entirely.

2021-01-06 01:34 UTC, MNarath1 commented
Most actually interresting circuits take multiple rounds preparing i could not imagine remaking my most complicated circuit in even a single round nor every round this will just make circuits impossible also many so called grief circuits are very basic and just abuse a single mechanic and can easily get made withint short time instead of actual work i

2021-01-06 01:35 UTC, MNarath1 commented
this litterally beats making any circuits that have even the slightliest use to the round except making like a small com circuit or a calculator(no even a calculater might take too long this will not help at all but just remove circuits)

2021-01-06 02:01 UTC, ro5490 commented
I'm making a list of the big issues currently, so feel free to post some here

2021-01-06 03:10 UTC, jlsnow301 commented
Basically no one will do circuits anymore. People seem to bat around removing circuits because of "bugs and exploits" but no one ever discusses them and certainly no one even attempts to fix them. Improve don't remove etc

2021-01-06 03:11 UTC, MNarath1 commented
thats why i am asking for a list of bugs cause the are no issues on github anywhere

2021-01-06 03:12 UTC, ro5490 commented
> Basically no one will do circuits anymore. People seem to bat around removing circuits because of "bugs and exploits" but no one ever discusses them and certainly no one even attempts to fix them. Improve don't remove etc

This is the main issue, exploits are found by players and abused rather than reported to the team. So fixes arent put in place and the team just pushes towards full circuit removal.

2021-01-06 03:12 UTC, ro5490 commented
Circuit Rework List
> Logging - Source/Destination Attribution
> Blood Sucking Nerf
> Reagent Mixing Nerf/Removal
> Injection Nerf?
> Chem Spraying Nerf?
> Icon Rework - Circuits dont look like what they contain I.e - You cant see a blaster in a circuit arm.
> Energy Cost Nerf
> See https://github.com/tgstation/tgstation/pull/54025 For their conditions and work from those too?


> thats why i am asking for a list of bugs cause the are no issues on github anywhere that discuss current circuit exploits and are open

@MNarath1

2021-01-06 03:12 UTC, ro5490 commented
list so far, I'll expand it when I can

2021-01-06 03:16 UTC, MNarath1 commented
ok things in tg pr list most i know already like ui beeing crap i can think about a fix for copy pasta stuff and the likes for ui i will definitly need outside help because i got no idea of javascript

2021-01-06 03:39 UTC, jlsnow301 commented
> ok things in tg pr list most i know already like ui beeing crap

#3252 . which was also batted down on the pretense that they're bugged and or going to be removed

2021-01-06 03:48 UTC, MNarath1 commented
> > ok things in tg pr list most i know already like ui beeing crap
> 
> #3252 . which was also batted down on the pretense that they're bugged and or going to be removed

ye like i said i am fine on working on that too but first gotta tackle logging and like i said i have no idea about javascript so thats something i cannot do alone likewise with fixing copy pasta alone cause i would need an API for the database and stuff thats something i would probably need to contact crossed about

2021-01-06 04:10 UTC, jlsnow301 commented
Overall I disagree with this. I think many of the issues listed here are hardly exploitable or don't apply to bee. For instance: Blood sucking gives a massive warning and requires a casting delay, you are also limited to one hypo injector. Things like throwers don't even exist, as listed in the tg so you cannot just spam glass shard throwers. 

I think admins are biased against circuits despite the exploitable functionality being largely removed. We should address the individual bugs rather than "temporary" removal, especially on some phantom like "bugs that are withheld"

2021-01-06 04:19 UTC, BeloneX commented
> Basically no one will do circuits anymore. People seem to bat around removing circuits because of "bugs and exploits" but no one ever discusses them and certainly no one even attempts to fix them. Improve don't remove etc

Ah yes, the "improve dont remove" statement without any suggestion on how to tackle the issue.

2021-01-06 04:20 UTC, BeloneX commented
> Overall I disagree with this. I think many of the issues listed here are hardly exploitable or don't apply to bee. For instance: Blood sucking gives a massive warning and requires a casting delay, you are also limited to one hypo injector. Things like throwers don't even exist, as listed in the tg so you cannot just spam glass shard throwers.
> 
> I think admins are biased against circuits despite the exploitable functionality being largely removed. We should address the individual bugs rather than "temporary" removal, especially on some phantom like "bugs that are withheld"

Can't fix bugs when people don't report them on purpose to abuse them.

2021-01-06 05:31 UTC, MNarath1 commented
> > Overall I disagree with this. I think many of the issues listed here are hardly exploitable or don't apply to bee. For instance: Blood sucking gives a massive warning and requires a casting delay, you are also limited to one hypo injector. Things like throwers don't even exist, as listed in the tg so you cannot just spam glass shard throwers.
> 
> > 
> 
> > I think admins are biased against circuits despite the exploitable functionality being largely removed. We should address the individual bugs rather than "temporary" removal, especially on some phantom like "bugs that are withheld"
> 
> 
> 
> Can't fix bugs when people don't report them on purpose to abuse them.

That goes for any kind of exploit that is there not only for circuits i am fine with tackling currently known issues starting with logging and then work down on those.

2021-01-06 14:50 UTC, jlsnow301 commented
> Can't fix bugs when people don't report them on purpose to abuse them.

Or when they don't exist

2021-01-06 23:52 UTC, MNarath1 commented
https://github.com/BeeStation/BeeStation-Hornet/pull/3321 first one i took a look upone cause lets be honest admins not beeing able to actually figure out trough logs who shot is kinda dumb

2021-01-07 04:14 UTC, Dmp1987 commented
Removing blueprint copying is a really bad fix, it limits people to only building dumb quick grief'y stuff like spamming repeated radio signals etc plus eliminating all the more interresting and constructive builds that take multiple shifts to build and design

The print someone made that automatically pod-people you on death would be a no go without blueprints, we would never have the time to build something like that in one shift, designing circuits is the most fun job at the moment, designing systems and finding effeccient solutions to different department needs.

Gimping circuits this way to fix exploits is a weird way to go, instead of symptom treating or treating the root of the problem you go with shooting the patient in the gut to let him slowly bleed out

you could atleast disclose said exploits to a trusted codingbus party so it could get fixed or damn let me have a go at it, DM cant be that bad to dev in despite the horror stories i heard, got a pba in IT sci so maybe i got a fighting chance

please don't remove circuits, its the only thing that's not mind boggling boring and repetitive on the station so much potential and takes a bit more than "click these 10 buttons to make drugs and bombs" or chugging monkey's into slime pens until you you're the speedy leader of a mob army

Hell, make it a separate job in sci and whitelist it so people only get to build grief stuff once

2021-01-07 12:07 UTC, PowerfulBacon requested changes
There is a config flag for this
## Determines if players are allowed to print integrated circuits, uncomment to allow.
IC_PRINTING

2021-01-07 13:06 UTC, MNarath1 commented
> ## Why It's Good For The Game
> You actually have to take some time to manually create circuits
> This should help prevent people from just pasting grief circuit codes at roundstart.
> And should slow down circuit creation in general.

Again this will not contribute at all to fix any of the problems mentionend and instead of slowing the circuit creation process down it will just outright make it impossible to create them due to the fact that most good circuits need multiple rounds to make them while most grief circuits only exploit a single or few mechanics to archive whatever they are designed to do so those will still be most likely possible but anything actually good nope that will be gone

2021-01-07 18:41 UTC, bloons3 commented
Copy Paste is bad because you shouldn't be able to carry things into a new round.

For example, you can design a very interesting Supermatter design. However, you cannot copy-paste your amazing design into a new round without having to build it in that round. You can have a plan that you follow to build it, but you can't copy paste it and have it instantly.

Nanites also follow this. You can write out what you want your nanites to do, and plan how to make them work, but you can't copy/paste a nanite script and end up with amazing nanites in an instant. You still need to get the programs, and connect their signals together.

2021-01-07 21:05 UTC, jlsnow301 commented
> The print someone made that automatically pod-people you on death would be a no go without blueprints, we would never have the time to build something like that in one shift

*blushing*

2021-01-07 22:53 UTC, MNarath1 commented
> Copy Paste is bad because you shouldn't be able to carry things into a new round.
> 
> 
> 
> For example, you can design a very interesting Supermatter design. However, you cannot copy-paste your amazing design into a new round without having to build it in that round. You can have a plan that you follow to build it, but you can't copy paste it and have it instantly.
> 
> 
> 
> Nanites also follow this. You can write out what you want your nanites to do, and plan how to make them work, but you can't copy/paste a nanite script and end up with amazing nanites in an instant. You still need to get the programs, and connect their signals together.

I am working on something to fix copy pasta while still giving a way to carry over circuits but eliminating discord copy pasta circuits.
Circuits are just scaling a lot more in complexity then most stuff, Nanites comes closer to this but it is still not nearly the same level but it is in the end very rewarding to work out a good circuit

2021-01-07 23:13 UTC, ro5490 commented
> you could atleast disclose said exploits to a trusted codingbus party so it could get fixed or damn let me have a go at it, DM cant be that bad to dev in despite the horror stories i heard, got a pba in IT sci so maybe i got a fighting chance

This is the main issue however
People find exploits and keep them private so they dont get patched.
I've only ever had other admins tell me about exploits.

Personally I dont want to remove cloning or circuits, but a decent portion of the admin team wanted a PR to do so, so I made this instead.

2021-01-07 23:22 UTC, MNarath1 commented
> > you could atleast disclose said exploits to a trusted codingbus party so it could get fixed or damn let me have a go at it, DM cant be that bad to dev in despite the horror stories i heard, got a pba in IT sci so maybe i got a fighting chance
> 
> This is the main issue however
> People find exploits and keep them private so they dont get patched.
> I've only ever had other admins tell me about exploits.
> 
> Personally I dont want to remove cloning or circuits, but a decent portion of the admin team wanted a PR to do so, so I made this instead.

you are basically describing the mindset of a normal griefer that tries to grief trough exploits this is by no means limited to circuits at all.

2021-01-08 01:16 UTC, bloons3 commented
> > > you could atleast disclose said exploits to a trusted codingbus party so it could get fixed or damn let me have a go at it, DM cant be that bad to dev in despite the horror stories i heard, got a pba in IT sci so maybe i got a fighting chance
> > 
> > 
> > This is the main issue however
> > People find exploits and keep them private so they dont get patched.
> > I've only ever had other admins tell me about exploits.
> > Personally I dont want to remove cloning or circuits, but a decent portion of the admin team wanted a PR to do so, so I made this instead.
> 
> you are basically describing the mindset of a normal griefer that tries to grief trough exploits this is by no means limited to circuits at all.

If a game mechanic allows for trivial grief, it should be removed.

2021-01-08 03:28 UTC, MNarath1 commented
> > > > you could atleast disclose said exploits to a trusted codingbus party so it could get fixed or damn let me have a go at it, DM cant be that bad to dev in despite the horror stories i heard, got a pba in IT sci so maybe i got a fighting chance
> 
> > > 
> 
> > > 
> 
> > > This is the main issue however
> 
> > > People find exploits and keep them private so they dont get patched.
> 
> > > I've only ever had other admins tell me about exploits.
> 
> > > Personally I dont want to remove cloning or circuits, but a decent portion of the admin team wanted a PR to do so, so I made this instead.
> 
> > 
> 
> > you are basically describing the mindset of a normal griefer that tries to grief trough exploits this is by no means limited to circuits at all.
> 
> 
> 
> If a game mechanic allows for trivial grief, it should be removed.

I am not sure what exactly you mean with trivial grief but I give in there need to be changes to take low effort circuit griefs aka copy pasta grief out of the picture and i am indeed working on that.

2021-01-08 03:29 UTC, bloons3 commented
I think this would work well.

You should not be able to carry things round to round without putting in actual work to build them.

2021-01-08 03:48 UTC, MNarath1 commented
> I think this would work well.
> 
> 
> 
> You should not be able to carry things round to round without putting in actual work to build them.

It will not circuit creation takes to long for that especially if you want to flesh it out properly but you are right that export and importing a string into the game that can come from anywhere without putting any kind of work into the circuit concept nor realization is a problem and not a good approach so i am changing that approach into another direction making sure you cannot import just any string anymore so you actually have to make your circuits yourself instead of grabbing it from reddit or discord

2021-01-08 03:52 UTC, MNarath1 commented
And i am actually almost done with it too just need to flesh some stuff out but the framework is there

2021-01-08 07:55 UTC, bloons3 commented
> making sure you cannot import just any string anymore so you actually have to make your circuits yourself instead of grabbing it from reddit or discord

Let me restate this.

I am against any functionality to export or import circuits in any way. The start of every round in SS13 is a fresh start, and while you may have written strategies, you cannot directly take mechanisms from one round to another.

If you want to experiment with circuits, and develop a strategy for building them from scratch in round, that's fine. I myself have a preferred supermatter engine setup I build that uses a plasma loop with radiators inside of the supermatter chamber.

Circuits, like every other game mechanic, should be built and wired from scratch in every round. Nanites are a similar mechanic to circuits, and they have no import/export functionality, only guides that _tell_ you how to wire and connect them.

2021-01-08 09:36 UTC, Autisem commented
Problem is circuits are infinitely more complex then both the SM or nanites. Sadly most grief circuits are basic in function so you only make sure that people will grief with it. Especialy if your circuit does some special networking(very possible with NTNet circuits or either signaler ones). Its kinda like construction projects, rounds on bee rounds simply arent along to do these large scale things and if you cant increment progress even a little you will literly kill off circuits for anything other then griefing

2021-01-08 09:36 UTC, Autisem commented
Not to mention certain circuits to help crew would be a pain to rebuild from scratch every single time

2021-01-08 12:15 UTC, MNarath1 commented
> > making sure you cannot import just any string anymore so you actually have to make your circuits yourself instead of grabbing it from reddit or discord
> 
> Let me restate this.
> 
> I am against any functionality to export or import circuits in any way. The start of every round in SS13 is a fresh start, and while you may have written strategies, you cannot directly take mechanisms from one round to another.
> 
> If you want to experiment with circuits, and develop a strategy for building them from scratch in round, that's fine. I myself have a preferred supermatter engine setup I build that uses a plasma loop with radiators inside of the supermatter chamber.
> 
> Circuits, like every other game mechanic, should be built and wired from scratch in every round. Nanites are a similar mechanic to circuits, and they have no import/export functionality, only guides that _tell_ you how to wire and connect them.

look i am very much aware of your opinion here but i also know how this will effect circuits in general as in completly kill them my solution is a compromise that still allows people to preserve their hard work between rounds but removes easy access to premade circuits those people had no hand in developing

2021-01-09 00:32 UTC, Dmp1987 commented
> > you are basically describing the mindset of a normal griefer that tries to grief trough exploits this is by no means limited to circuits at all.
> 
> If a game mechanic allows for trivial grief, it should be removed.

bag of holding?

2021-01-11 11:56 UTC, PowerfulBacon commented
my big question I always ask: why?

> This is a temporary fix until other things have been put in place

A temporary fix... for what?

2021-01-11 16:08 UTC, MNarath1 commented
> my big question I always ask: why?
> 
> 
> 
> > This is a temporary fix until other things have been put in place
> 
> 
> 
> A temporary fix... for what?
> 
> And what else is going to be put in place or is it going to be a permanent temporary fix

I am working on something that could replace the old circuit cloning but its currently only working with savefiles and thats not ideal i would love making it work with sql but i have no idea about the how i mean savefiles work but i am concerned about the size increase of the data folder it would probably not get too bad but still

2021-01-11 17:48 UTC, PowerfulBacon commented
> I am working on something that could replace the old circuit cloning but its currently only working with savefiles and thats not ideal i would love making it work with sql but i have no idea about the how i mean savefiles work but i am concerned about the size increase of the data folder it would probably not get too bad but still

What would it even solve though?

2021-01-11 18:01 UTC, MNarath1 commented
> > I am working on something that could replace the old circuit cloning but its currently only working with savefiles and thats not ideal i would love making it work with sql but i have no idea about the how i mean savefiles work but i am concerned about the size increase of the data folder it would probably not get too bad but still
> 
> 
> 
> What would it even solve though?

You mean what i am working at or this PR what i am doing would solve the problem with copy pasta circuits this PR i am not to sure myself the author complains about bugs and stuff and problems the admins encouter why none of said admins have made a actual issue about said problems on github i do not understand they always say fix it but give no real laundry list i mean i got a list now more or less even trough i think its kinda out of data like blood suck injection already got nerfed if i remember right by the circuit part limit

2021-01-22 08:59 UTC, TheFakeElon commented
tl;dr
This PR removes the ability to _directly_ convert meta/OOC text strings into powerful weapons/gadgets

2021-02-01 03:58 UTC, TheFakeElon commented
Circuits are in a bad spot right now, they're pretty sub-par without copy-paste and become very repetitive to make. But, you can make incredibly powerful gadgets with little to no effort because you made (or someone else posted) a text file.

A less outright solution would be preferred, but circuits have a pretty weird place in the game because of the very small amount of persistency in ss13 while also requiring pretty large time investments to do make anything useful, importing and exporting was a bandaid solution to a bigger problem with circuits. This PR would almost completely nullify their use.

The best fix I can think of would be removing the import/export functionality but retaining some degree of persistency, it could be tied to player save files to solve the issue of sharing, but that won't do a whole lot in the long run. This PR has been stale for a while now so I'm going to close it.

(And as bacon pointed out, it's already a config option lol)

2021-02-01 03:58 UTC, closed without merging

2021-02-01 16:49 UTC, MNarath1 commented
> Circuits are in a bad spot right now, they're pretty sub-par without copy-paste and become very repetitive to make. But, you can make incredibly powerful gadgets with little to no effort because you made (or someone else posted) a text file.
> 
> 
> 
> A less outright solution would be preferred, but circuits have a pretty weird place in the game because of the very small amount of persistency in ss13 while also requiring pretty large time investments to do make anything useful, importing and exporting was a bandaid solution to a bigger problem with circuits. This PR would almost completely nullify their use.
> 
> 
> 
> The best fix I can think of would be removing the import/export functionality but retaining some degree of persistency, it could be tied to player save files to solve the issue of sharing, but that won't do a whole lot in the long run. This PR has been stale for a while now so I'm going to close it.
> 
> 
> 
> (And as bacon pointed out, it's already a config option lol)

If you are fine with something thats based on player sav files i can already provide that (i have said code ready in my repro )but i am working on instead bringing it over to sql as it would be more clean and easier to administrate