Dutch Hot Coco now actually has chocolate in it
BeeStation/BeeStation-Hornet pull request #3369
Opened 2021-01-12 13:56 UTC by super12pl

## About The Pull Request
Dutch hot coco from vendors now has 5 units of cocoa in it.

## Why It's Good For The Game
Hot **Chocolate**

## Changelog
:cl:
add: Dutch hot coco now has actual chocolate in it.
/:cl:

2021-01-12 14:51 UTC, Victor239 commented
Better question is why the hell is `hot_cocoa` a separate reagent.

2021-01-12 14:53 UTC, eeSPee commented
> Better question is why the hell is `hot_cocoa` a separate reagent.

It's a drink.

2021-01-12 20:49 UTC, Crossedfall commented
Hot_cocoa already has cocoa in it though. 🤔 Is this just extra chocolaty?

https://github.com/BeeStation/BeeStation-Hornet/blob/2467386bb666982dd41cb5e6acb4b1ebc4e392f3/code/modules/food_and_drinks/recipes/food_mixtures.dm#L52

2021-01-12 22:18 UTC, super12pl commented
> Hot_cocoa already has cocoa in it though.  Is this just extra chocolaty?
> 
> https://github.com/BeeStation/BeeStation-Hornet/blob/2467386bb666982dd41cb5e6acb4b1ebc4e392f3/code/modules/food_and_drinks/recipes/food_mixtures.dm#L48-L52
You need cocoa and water to create hot cocoa but actual hot cocoa doesn't work like cocoa (felinids can safely drink hot chocolate for example)

2021-01-13 07:06 UTC, Crossedfall commented
> 
> You need cocoa and water to create hot cocoa but actual hot cocoa doesn't work like cocoa (felinids can safely drink hot chocolate for example)

So fix hot_cocoa instead 🤔

2021-01-13 20:25 UTC, super12pl commented
> > You need cocoa and water to create hot cocoa but actual hot cocoa doesn't work like cocoa (felinids can safely drink hot chocolate for example)
> 
> So fix hot_cocoa instead

Actually yeah I can do that

2021-01-14 00:25 UTC, nikk735 commented
add candy too its a chocolate bar

2021-01-14 08:47 UTC, park66665 commented on code/modules/mob/living/carbon/human/species_types/felinid.dm
> +	if(chem.type == /datum/reagent/consumable/cocoa OR /datum/reagent/consumable/hot_cocoa)
```suggestion
	if(istype(chem, /datum/reagent/consumable/cocoa) || istype(chem, /datum/reagent/consumable/hot_cocoa))
```

2021-01-14 22:46 UTC, Fronsis commented
As long as it also helps curing the felinid disease... rip the Candy chocolate bar that didn't work as cure

2021-01-16 09:55 UTC, PowerfulBacon requested changes
yikes repetetive code. Just make hot_cocoa a subtype of cocoa

2021-01-25 09:48 UTC, PowerfulBacon commented on code/modules/mob/living/carbon/human/species_types/felinid.dm
> +	if(istype(chem, /datum/reagent/consumable/cocoa) || istype(chem, /datum/reagent/consumable/cocoa/hot_cocoa))
If you have
A/B/C
and 
A/B/C/D
istype(item, A/B/C) will return true for types A/B/C and A/B/C/D
istype(item, A/B/C/D) will return true for type A/B/C/D

2021-01-25 09:48 UTC, PowerfulBacon commented on code/datums/diseases/transformation.dm
> +	cures = list(/datum/reagent/consumable/cocoa, /datum/reagent/consumable/cocoa/hot_cocoa) //kills all the tiny cats that infected your organism
Pretty sure subtypes are assumed to work

2021-01-25 09:48 UTC, PowerfulBacon reviewed
Also you need to change all instances of /datum/reagent/consumable/hot_cocoa with /datum/reagent/consumable/cocoa/hot_cocoa

2021-01-28 14:11 UTC, park66665 commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
>  	nutriment_factor = 3 * REAGENTS_METABOLISM
```suggestion
	description = "Made with love! And cocoa beans."
	reagent_state = LIQUID
	nutriment_factor = 3 * REAGENTS_METABOLISM
```

Without this, hot cocoa will be `SOLID`.

2021-01-31 10:10 UTC, PowerfulBacon submitted a review, later dismissed

2021-02-02 15:32 UTC, park66665 requested changes
1. typecheck at `/datum/species/human/felinid/handle_chemicals` should be `istype(chem, /datum/reagent/consumable/cocoa)`
2. `/datum/disease` `cures` list is checked by `==` check, not `istype` check. You should change `/datum/disease/transformation/felinid`'s `cures` list to `list(/datum/reagent/consumable/cocoa, /datum/reagent/consumable/cocoa/hot_cocoa)` if you intended `/datum/reagent/consumable/cocoa/hot_cocoa` to work as a cure to `/datum/disease/transformation/felinid`

2021-02-04 12:33 UTC, park66665 approved these changes
All clear. This PR is good to go.

2021-02-04 12:33 UTC, merged