Enables the science shuttle
BeeStation/BeeStation-Hornet pull request #3388
Opened 2021-01-14 13:19 UTC by St0rmC4st3r

## About The Pull Request

The science shuttle is now powered and consoles are present in all current stations. The outpost itself is still unpowered however and the access is still an intentional mess.

## Why It's Good For The Game

Apparently many people want it for some reason.

## Changelog
:cl:
tweak: Upon multiple requests, the science outpost shuttle is now accessible from roundstart.
/:cl:

2021-01-14 15:04 UTC, PowerfulBacon commented
fix the double window on metastation while you are there

2021-01-14 16:24 UTC, St0rmC4st3r commented
> fix the double window on metastation while you are there

Oh crap, now I remember.

2021-01-15 02:34 UTC, francinum requested changes
This is not the correct way to do this. Replace it with a charged APC, the area requires power, and thus it should not be left without a roundstart APC.

2021-01-15 12:19 UTC, St0rmC4st3r commented
> This is not the correct way to do this. Replace it with a charged APC, the area requires power, and thus it should not be left without a roundstart APC.

I am not sure what you are talking about. No APC has been deleted. I only removed a helper in the shuttle. This helper removes charge from whatever APC is on the same tile.

2021-01-17 00:41 UTC, francinum approved these changes

2021-01-17 10:58 UTC, merged