Sharp Mop 2.0
BeeStation/BeeStation-Hornet pull request #340
Opened 2019-08-20 08:06 UTC by UwUPlusUwU

Adds sharp mop and recipe- now rebalanced!

## About The Pull Request

Adds a rebalanced sharp mop and a recipe.

## Why It's Good For The Game

Mostly a proof-of-concept, but janitors can now convert their trusty brooms to a slightly better version, allowing for the dream of combat janitors.

## Changelog
:cl:
add: Added sharpened mop.
/:cl:

2019-08-20 10:44 UTC, UwUPlusUwU commented
Haha yes, how do I stop it upstreaming help aaaaaaaaa.

2019-08-20 13:42 UTC, UwUPlusUwU commented
Ignore the third check, it just says it was from a previous build which passed.

2019-08-20 14:21 UTC, vyzk commented
sounds epic

2019-08-20 18:21 UTC, ondrej008 commented
Rename this PR to "Adds Sharp Mop and Dio emote"

2019-08-20 18:23 UTC, ondrej008 requested changes

2019-08-20 18:23 UTC, ondrej008 commented on code/modules/crafting/recipes.dm
> +	reqs = list(/obj/item/tank/internals/oxygen/red = 2)
What the fuck?

2019-08-20 18:23 UTC, ondrej008 commented on code/modules/opo/jojo.dm
> +
At least say you added this shit.

2019-08-20 18:23 UTC, ondrej008 commented on beestation.dme
> -#include "code\modules\mob\living\carbon\human\update_icons.dm"
?

2019-08-21 01:46 UTC, qwertyquerty commented
Try again

2019-08-21 01:46 UTC, closed without merging