Adds the Advanced Chameleon Kit
BeeStation/BeeStation-Hornet pull request #3435
Opened 2021-01-19 11:11 UTC by Victor239

## About The Pull Request

Adds the Advanced Chameleon Kit to traitor uplink for 12 TC (worth over 22 TC). 

Includes the existing items:
- No-Slip Chameleon Shoes (3 TC)
- Chameleon Combat Gloves (1 TC)
- Chameleon Flashproof Glasses (2 TC)
- Chameleon Bangproof Headset (2 TC)
- [Chameleon Lightweight Duffel Bag](https://github.com/BeeStation/BeeStation-Hornet/pull/3405) (2 TC)
- Wig, razor, PDA, etc from basic chameleon kit. 

Includes several new items which are also sold separately:
- **Chameleon Space Suit** - lightly armored compared to the Syndicate Space Suit but has no slowdown, two extra-large pockets (holds normal-sized items) and is of course stealthier. Allows lizardpeople and felinids to hide their tails. Includes a spaceproof lightly armored helmet and both items fit in backpacks. Costs 4 TC.
- **Chameleon Deep-Pocketed Coat** - lightly armored like the normal chameleon suit but additionally has extra-large pockets. Costs 2 TC.
- **Chameleon Rebreather Mask** - removes the wearer's need to breathe and includes a voice changer like the basic chameleon mask. Costs 2 TC. 
- **Chameleon Combat Uniform & Accessory Kit** - a lightly armored uniform that comes with two detachable hidden accessories that can't be detected by examining you - a holster and a generic 3 item pocket. Costs 4 TC. 

Additional tweaks:
- Tactical turtleneck and chameleon jumpsuit given matching armor values and changed all 0 armor values to 10 for consistency. 
- Chameleon hat changed all 0 armor values to 5 for consistency. 

Note: won't compile without:
- https://github.com/BeeStation/BeeStation-Hornet/pull/3326 for hidden accessories
- https://github.com/BeeStation/BeeStation-Hornet/pull/3405 for chameleon duffel bag

## Why It's Good For The Game

More useful options for traitors.

## Changelog
:cl:
add: Adds the Advanced Chameleon Kit to traitor uplinks and all new items also sold separately. 
/:cl:

2021-01-19 11:20 UTC, eeSPee commented
> Advanced Chameleon Kit

IMO include agent ID and make it 20? Or make it part of the syndicate tactical kit. Just suggestions.

> Includes several new items which are also sold separately

Not mentioned in the changelog and should be atomized, IMO.

2021-01-19 12:58 UTC, Victor239 commented
> IMO include agent ID and make it 20? Or make it part of the syndicate tactical kit. Just suggestions.

Don't think it's quite worth pricing it at 20 TC even with an agent ID. I could maybe make it additionally a syndi tactical kit with an agent ID and emag perhaps depending on interest and suggestions.

> Not mentioned in the changelog,

Updated now.

> Also should be atomized imo.

This is all adding items for one kit so I don't see any irrelevant changes here.

2021-01-19 13:14 UTC, PowerfulBacon commented
Kinda overpriced in my opinion, sounds like normal marketing where they say the value is '22TC!' when in reality the items inside are pretty marked up, most of the stuff could probably be said to cost 1 TC, like the headset, the glasses and the shoes are pretty good, but there is no way the coat with pockets is worth 2 TC, the rebreather mask is worth 2 TC or the accessory kit is worth 3 (Admittedly the space suit is an insane deal, pretty sure that's cheaper than the regular space suit)

2021-01-19 13:39 UTC, OceanFish1 commented
> Chameleon Rebreather Mask - removes the wearer's need to breathe and includes a voice changer like the basic chameleon mask. Costs 2 TC.

Wait isn't that OP just to spend 2 TC on a mask that removes need to breathe and makes you forget about oxygen at all? Like there is only one mask that does things like that and you can only get that from xenobio.

2021-01-19 14:13 UTC, eeSPee commented
> > Chameleon Rebreather Mask - removes the wearer's need to breathe and includes a voice changer like the basic chameleon mask. Costs 2 TC.
> 
> Wait isn't that OP just to spend 2 TC on a mask that removes need to breathe and makes you forget about oxygen at all? Like there is only one mask that does things like that and you can only get that from xenobio.

Would it be a good idea to make it Atmos Tech restricted item?

2021-01-19 15:04 UTC, Isy232 commented
I think this should cost like 8, 12 is too much, bangproof headset is worth 1 TC, same as flashproof and duffelbag.

2021-01-19 15:05 UTC, Isy232 commented
> > > Chameleon Rebreather Mask - removes the wearer's need to breathe and includes a voice changer like the basic chameleon mask. Costs 2 TC.
> > 
> > 
> > Wait isn't that OP just to spend 2 TC on a mask that removes need to breathe and makes you forget about oxygen at all? Like there is only one mask that does things like that and you can only get that from xenobio.
> 
> Would it be a good idea to make it Atmos Tech restricted item?

Atmos techs would have no use for this item because they have the tools to overfill their roundstart engi internals tank and basically never need it.

2021-01-19 17:35 UTC, bloons3 commented
> > Chameleon Rebreather Mask - removes the wearer's need to breathe and includes a voice changer like the basic chameleon mask. Costs 2 TC.
> 
> Wait isn't that OP just to spend 2 TC on a mask that removes need to breathe and makes you forget about oxygen at all? Like there is only one mask that does things like that and you can only get that from xenobio.

That doesn't sound balanced at all. I'd understand if it had a separate backpack (since IRL rebreathers have large and complex supporting machinery), but this isn't Jame's Bond we're talking about here.

![image](https://user-images.githubusercontent.com/3241376/105071644-7ca1f280-5a4a-11eb-83ed-3d4dbed05d77.png)

( Thunderball )

2021-01-19 18:43 UTC, Victor239 commented
> coat with pockets is worth 2 TC

My thought process was that a smugger's satchel can hold about twice as many items but isn't armoured and can't disguise almost your entire body. 1 TC items are all trash tier, if this was 1 TC it'd be a no brainer to buy since it's useful to anyone. 

> the rebreather mask is worth 2 TC 

I couldn't really think of another useful ability to give a chameleon mask to be honest, but the trend with these advanced chameleon items is they each remove one particular weakness from the user (e.g. slips, flashes, bangs, shocks, etc) so gases seem like a good fit for this. Not sure about the price however.

> the accessory kit is worth 3 

Costs 4 and the reasoning is that your uniform is never going to get searched unless you're being perma'd (and realistically Sec is going to forget most of the time even then), yet you can store an emag+esword+sleepy pen in there, or a .357 revolver and two speedloaders. Which is pretty damn robust and makes the uniform close to the more expensive Storage Implant in terms of useful hidden storage. Don't want to make it any cheaper really as it's a cheap perfect hidden storage for any traitor which Sec are not going to find unless you're charged with a capital crime based off other evidence.

> Admittedly the space suit is an insane deal, pretty sure that's cheaper than the regular space suit

My armour accessories PR also decreases normal Syndicate space suit from 3 to 2 TC. Could bump up the chameleon version to 5 TC separately.

2021-01-22 04:13 UTC, TheFakeElon commented
The rebreather isn't really overpowered when you take into account how long an emergency oxygen tank lasts, the main upside is that it saves you a pocket/suit slot. With that being said; imo, it's a pretty cheesy effect, it'd be a bit better if it did something like filtering harmful gasses instead of bypassing the entire breathing mechanic

2021-01-22 18:00 UTC, bloons3 commented
> The rebreather isn't really overpowered when you take into account how long an emergency oxygen tank lasts, the main upside is that it saves you a pocket/suit slot.
> With that being said; imo, it's a pretty cheesy effect, it'd be a bit better if it did something like filtering harmful gasses instead of bypassing the entire breathing mechanic

It'd be better if you could attack small oxygen tanks to it and use those as the source of atmos, instead of completely _bypassing_ breathing. Something like the power-fist.

2021-01-24 05:35 UTC, francinum requested changes
I'm registering a general blocker on this until tomorrow when I can properly put down all the reasons why parts of this need changes.

2021-01-24 18:32 UTC, FortSumter commented
Chameleon hardsuit would be based for nuke ops, which is where my problem is. Even if this had the agent ID and cost 20TC, stealth nuke ops with take it, grab a CQC manual, and maybe one other item of their choice and they can be in and out with the captain and the disk before anyone can yell "It's nukies!" this is the reason why a chameleon hardsuit was never added, and while I like the idea personally, should never be added for balance reasons.

2021-01-25 03:56 UTC, Victor239 commented
It's a space suit not a hardsuit, but yeah actually that's a good point that it shouldn't be available to nukies.

2021-01-25 04:07 UTC, bloons3 commented
So someone could dress up as an assistant smoking a cigarette, wearing a hazard vest, spacewalk for an infinite amount of time, then casually stroll back onto the station, while being flashproof and flash bang proof.

2021-01-25 04:34 UTC, Victor239 commented
The chameleon space suit wouldn't really work as a hazard vest since it hides your jumpsuit so it looks weird, you basically have to wear it as a space suit or other full body garment. So you get to look like a guy wearing an EVA suit OR in your underwear, plus a cigarette.

2021-01-25 05:00 UTC, francinum commented
The idea with chameleon gear has always been that it's fake, it's plastic crap that doesn't provide much of any utility besides a disguise.

The ability for them to act as a functional space suit and other actually useful equipment is counter to the tradeoff.

2021-01-25 05:34 UTC, Victor239 commented
Sure, and that's the basic chameleon gear - very cheap, mainly useful as a disguise with also a little added armour. 

With the advanced versions I've already added and am adding here they're ~~money~~ TC sinks if you have spare crystals, or handy if you're unable to get access to a specific useful item you really need (eg insuls, bangproof headset), or as nice filler items in surplus crates. 

I think it's more a matter of what price they should be rather than whether traitors should get access to them at all, none of this stuff is balance or lore breaking. Except for potentially the rebreather and space suit which others here have already raised questions about of course.

2021-01-25 05:51 UTC, francinum commented
> Sure, and that's the basic chameleon gear - very cheap, mainly useful as a disguise with also a little added armour.

You realize that being able to tell what someone is wearing is an extremely important thing, and is *exactly why* the cham stuff is weak and useless.

> With the advanced versions I've already added and am adding here they're ~money~ TC sinks if you have spare crystals

If you have spare crystals you either have a problem or you have an ace in the hole if you need a backup plan.


> or handy if you're unable to get access to a specific useful item you really need (eg insuls, bangproof headset)

That's very much *the traitor's problem.* and does NOT need an uplink solution.
That gear is rare or difficult to access by design.
That's literally the fucking *point* of them not getting it.
Hell, you can already BUY insulated gloves with tools in the suspicious briefcase.

They're just stupid obvious unless you *put the effort in to make them not.*

> or as nice filler items in surplus crates.

What the fuck?


> I think it's more a matter of what price they should be rather than whether traitors should get access to them at all, none of this stuff is balance or lore breaking. Except for potentially the rebreather and space suit which others here have already raised questions about of course.

Uh huh...

2021-01-25 05:54 UTC, qwertyquerty commented
3 maintainers dislike this pr greatly

2021-01-25 05:54 UTC, closed without merging