Fixes gun circuit runtime and some slightly logging changes
BeeStation/BeeStation-Hornet pull request #3447
Opened 2021-01-19 19:37 UTC by MNarath1

## About The Pull Request

This PR fixes a runtime that occured for logging when it tried to call usr if the action was actually not called by a player like with a timer also fixes yet another runtime that occured when it tried to write into the non existing combat log of the assembly. This also includes a sligthly change to the gun circuit logging as the log message now includes the circuit creator too.
## Why It's Good For The Game

Runtimes bad. 
Runtimes that freezer the projectile in the air cause someone(me) forgot to consider timers as the action source of a weapon circuit firing is even worse.
## Changelog
:cl:
fix: weapon circuit runtime
tweaks: adds creator to weapon circuit logging
/:cl:

2021-01-19 20:15 UTC, qwertyquerty approved these changes

2021-01-19 20:15 UTC, qwertyquerty commented on code/modules/integrated_electronics/subtypes/manipulation.dm
> +	A.firer = !usr ? "[assembly]/[REF(assembly)] circuit made by [assembly.creator]" : "[usr.ckey]/[usr] trough [assembly]/[REF(assembly)] circuit made by [assembly.creator]"
"trough"

2021-01-19 20:15 UTC, qwertyquerty commented on code/modules/integrated_electronics/subtypes/manipulation.dm
> +	A.firer = !usr ? "[assembly]/[REF(assembly)] circuit made by [assembly.creator]" : "[usr.ckey]/[usr] trough [assembly]/[REF(assembly)] circuit made by [assembly.creator]"
fix spelling

2021-01-19 20:17 UTC, qwertyquerty commented on code/modules/integrated_electronics/subtypes/manipulation.dm
> +	A.firer = !usr ? "[assembly]/[REF(assembly)] circuit made by [assembly.creator]" : "[usr.ckey]/[usr] trough [assembly]/[REF(assembly)] circuit made by [assembly.creator]"
"trough"

2021-01-19 20:18 UTC, qwertyquerty requested changes, later dismissed
"trough"

2021-01-19 20:23 UTC, MNarath1 commented on code/modules/integrated_electronics/subtypes/manipulation.dm
> +	A.firer = !usr ? "[assembly]/[REF(assembly)] circuit made by [assembly.creator]" : "[usr.ckey]/[usr] trough [assembly]/[REF(assembly)] circuit made by [assembly.creator]"
Ok is that formulation better ?

2021-01-19 21:07 UTC, MNarath1 commented
@qwertyquerty is that better now?

2021-01-25 11:15 UTC, PowerfulBacon approved these changes

2021-01-25 15:57 UTC, merged