Slime Cargo Pack
BeeStation/BeeStation-Hornet pull request #3452
Opened 2021-01-20 13:14 UTC by eeSPee

## About The Pull Request

Adds grey slime cargo crate to science.

## Why It's Good For The Game

Sometimes it happens that all slimes die (accident, sabotage) and makes xenobiology useless.

There's no reason for this not to exist.

## Changelog
:cl:
add: Added Slime Cargo Pack in Science
/:cl:

2021-01-20 13:40 UTC, Rukofamicom commented
You can already revive dead grey slimes by injecting their cores with plasma if your starter slimes happen to die. You can revive *any* dead slime with a lazarus injector for that matter.

2021-01-20 13:41 UTC, eeSPee commented
I'd argue there is no reason for this not to exist.

2021-01-20 14:31 UTC, leestriter commented
> 
> 
> You can already revive dead grey slimes by injecting their cores with plasma if your starter slimes happen to die. You can revive _any_ dead slime with a lazarus injector for that matter.

Yeah but sometimes xenobio gets sabotaged, and someone kills the greys and flushes the extracts, or a noob turns all the greys into cubes. While I don't think the crate will see a ton of use it offers a way to recover if you get truly screwed. A bit of grief protection.

2021-01-20 15:36 UTC, TheFakeElon commented
> Yeah but sometimes xenobio gets sabotaged, and someone kills the greys and flushes the extracts, or a noob turns all the greys into cubes. While I don't think the crate will see a ton of use it offers a way to recover if you get truly screwed. A bit of grief protection.

I suppose, but does this ever happen? I can't imagine this crate is going to be used for anything beyond cheesing the steal slime extract objective

2021-01-20 15:48 UTC, eeSPee commented
> I suppose, but does this ever happen? I can't imagine this crate is going to be used for anything beyond cheesing the steal slime extract objective

Which is laughably easy to do anyway.

2021-01-20 15:57 UTC, TheFakeElon commented
> Which is laughably easy to do anyway.

I know, which is why I didn't mention it as a root problem. The main problem is that there is no problem, this PR addresses an issue that doesn't exist. (as far as I'm aware of)

2021-01-20 15:59 UTC, TheFakeElon commented on code/modules/cargo/packs.dm
> +
This should probably require an ID to unlock, it'd be very easy to open a bunch of these quickly and cause some chaos.

2021-01-20 16:03 UTC, PowerfulBacon commented
You can bypass the max slime limit

2021-01-20 16:04 UTC, eeSPee commented
Max slime limit?

2021-01-20 16:22 UTC, PowerfulBacon commented
> 
> 
> Max slime limit?

there is a max slime breeding limit

2021-01-24 18:11 UTC, FortSumter commented
I like this. I agree with the author that this should exist to solve the problem of what if xenobio gets nuked, and while he's at it include a xenobio console board and a bio bag too and have it purchasable at an extortion-ally high price. If you manage to fuck up xenobio that hard, you should have to pay for it. This would also allow cargo to be turned into another xenobio, which would be a great project after cargo does engineering's job and builds an engine.

2021-01-24 18:22 UTC, eeSPee commented
I'm thinking to remake this into a xenobio starter pack. Including grey cores and machines...

But I think slime consoles are hard coded.

2021-01-25 07:22 UTC, francinum commented
> I'm thinking to remake this into a xenobio starter pack. Including grey cores and machines...
> 
> But I think slime consoles are hard coded.

They are not. They have a board.

2021-01-25 07:48 UTC, eeSPee commented
> > I'm thinking to remake this into a xenobio starter pack. Including grey cores and machines...
> > But I think slime consoles are hard coded.
> 
> They are not. They have a board.

Hmm. I was always under the impression that slime consoles are hard coded and unique.

2021-01-25 07:57 UTC, TheFakeElon requested changes
The crate should be access locked

2021-01-25 09:53 UTC, PowerfulBacon requested changes, later dismissed
They should also have something to stop you buying a shit ton of slimes, going over the slime limit and lagging the server.

2021-01-25 11:03 UTC, eeSPee commented
Reworked into Xenobiology Pack, containing slime extracts and plasma, so that the slime limit cannot be overridden. It's ridiculously expensive but also contains the boards required to set up xenobio.

2021-01-25 12:54 UTC, TheFakeElon approved these changes, later dismissed

2021-01-25 12:57 UTC, RDS88-beeman commented
this costs as much as a null crate. Bruh

2021-01-25 14:18 UTC, St0rmC4st3r commented
>or a noob turns all the greys into cubes. While I don't think the crate will see a ton of use it offers a way to recover if you get truly screwed. A bit of grief protection.

I would not believe this, but two days ago exactly this happened, so yes.
However, what about "Steal extract" objective?

2021-01-25 14:21 UTC, eeSPee commented
> I would not believe this, but two days ago exactly this happened, so yes.
> However, what about "Steal extract" objective?

What about Reflective Armor crate?

The "Steal extract" objective is not meant to be particularly hard or challenging to complete. Usually you can sneak into xenobio and tiding into xenobio and stealing random extracts does not raise an eyebrow.

The crate is quite pricey so stealing the extract would not be as easy as it seems.

2021-01-25 14:21 UTC, RDS88-beeman commented
you can already order reflector vests from cargo for probably cheaper, and hand tele's can be in abandoned crates. Getting antag objectives for money and/or RNG bullshit is nothing new

2021-01-25 15:55 UTC, TheFakeElon approved these changes
Adding more traitor objective shortcuts is not exactly preferable but that's something that should probably be addressed in a different PR, as it's nothing new

2021-01-27 03:49 UTC, francinum commented
I'm not trilled with the objective bypass

However the objective is also really fucking stupid.

2021-01-27 03:49 UTC, merged