Felinids are now forced to use cat tails and ears.
BeeStation/BeeStation-Hornet pull request #3475
Opened 2021-01-24 12:44 UTC by PowerfulBacon

## About The Pull Request

Adds in a new variable for species, forced_features.
Anything in the list of forced_features will be forced upon a mob when they select their species in preferences, or when the save file is loaded forced_features are checked for validation.

Felinid on_species_gain automatically adds the tail parts, however in preferences you could disable the tail, or set it to 'clockwork tail'

## Why It's Good For The Game

Prevents players from playing felinid with no tail or the clockwork tail.

## Changelog
:cl:
fix: Felinids can no longer play without cat ears or tail.
/:cl:

2021-01-24 12:52 UTC, Penwin0 commented
Rip

2021-01-24 13:32 UTC, OceanFish1 commented
There was one imposter among us

2021-01-24 17:31 UTC, FortSumter commented
As an AI player, I approve of this change. No more awkward situations where I followed a felinids orders on asimov! While you're at it, can you make the medical records work like the security ones? It takes too long and is too much of a pain to check what race the person giving me orders is.

2021-01-25 07:10 UTC, TheFakeElon approved these changes

2021-01-25 07:10 UTC, francinum commented
Are they a species or not.

If not: Why the fuck do they have these choices

2021-01-25 07:10 UTC, francinum requested changes
No. Clarify this shit first.

2021-01-25 08:40 UTC, PowerfulBacon commented
Yes they are a species

2021-01-25 10:37 UTC, Autisem commented
I guese bee wont really have other tail types any time soon so this might be fine, but its a little bit of a soft lock should that ever change

2021-01-25 11:08 UTC, PowerfulBacon commented
> 
> 
> I guese bee wont really have other tail types any time soon so this might be fine, but its a little bit of a soft lock should that ever change

It would be very easy to make forced_type a list and have it only selectable from that list instead, if we ever get any furry downstreams

2021-01-25 20:47 UTC, Autisem commented
> > I guese bee wont really have other tail types any time soon so this might be fine, but its a little bit of a soft lock should that ever change
> 
> It would be very easy to make forced_type a list and have it only selectable from that list instead, if we ever get any furry downstreams

Propably a good thing, should another race come along that like that

2021-01-27 03:30 UTC, francinum commented
Sure whatever.

This is honestly a hack fix over a terrible system but let's just keep stacking up the technical debt until it buries us.

2021-01-27 03:30 UTC, francinum approved these changes

2021-01-27 03:30 UTC, merged