gas elasticity
BeeStation/BeeStation-Hornet pull request #3504
Opened 2021-01-27 12:33 UTC by Sinestia

## About The Pull Request
https://github.com/tgstation/tgstation/pull/55192
is this

when you sell a canister with gas it goes through the list and if the moles are greater than 0 it puts it through an elasticity formula.

![image](https://user-images.githubusercontent.com/40812746/105989840-4c201100-6067-11eb-9459-6013e47a46bb.png)
This is an example of what the payment curve looks like, using miasma as an example. 

In practice, this is mostly a nerf to BZ and miasma farms. The most you'll get from a single BZ can is about 15000 credits for 10000 moles, double that for miasma of course. **Before you complain that I'm destroying cargo's fun, you can still get filthy rich off of these. It just takes more effort and time, and it's encouraged you diversify too.**

This doesn't really affect expensive gasses like hypernob, as your "peak" is at 3 million in one canister from 20k moles, which is fine I think.
## Why It's Good For The Game
BZ farms, especially using portable scrubbers, are an oft-complained about topic. 

This reels them in a lot, and implements something that really should have always been there.

 The gas prices don't need to be changed (aside from fixing stimulum on the wiki,) and I don't think lavaland gas composition or corpse flowers need nerfed either. 

## Changelog
:cl:Froststahr
add: Gas selling now uses elasticity
balance: Effectively, mass quantities of gases are significantly less profitable. 
/:cl:

2021-01-27 12:41 UTC, githubuser343 commented
Elasticity makes sense for gases that are easily available in vast quantities, such as BZ and miasma.
It does not make sense for the rare and hard to get gases such as hyper noblium and stimulum.

Compare it to ore sales, all ores except plasma are elastic in price. Elasticity should be selected per gas, not as a property of canisters.

Why should value of hyper noblium be lower because someone exported BZ?

2021-01-27 12:42 UTC, Sinestia commented
> 
> 
> Elasticity makes sense for gases that are easily available in vast quantities, such as BZ and miasma.
> It does not make sense for the rare and hard to get gases such as hyper noblium and stimulum.
> 
> Compare it to ore sales, all ores except plasma are elastic in price. Elasticity should be selected per gas, not as a property of canisters.
> 
> Why should value of hyper noblium be lower because someone exported BZ?

it doesn't, the math is ran per gas

2021-01-27 12:47 UTC, githubuser343 commented
> it doesn't, the math is ran per gas

Maybe I'm misunderstanding what elasticity does.

If you sell a canister full of BZ, will this affect the price of another identical canister being sold on another shuttle?

2021-01-27 12:58 UTC, ivanmixo commented
Is this per canister or the total amount of moles on the shuttle?

2021-01-27 12:59 UTC, githubuser343 commented
After reading through the code handling exports, I've come to the conclusion that elasticity does absolutely nothing to address the problem of cargo cheesing lavaland BZ for millions. Instead of selling 1 large canister they can just separate the gas into multiple canisters to bypass elasticity, balance by tedium.

2021-01-27 13:02 UTC, Sinestia commented
> 
> 
> > it doesn't, the math is ran per gas
> 
> Maybe I'm misunderstanding what elasticity does.
> 
> If you sell a canister full of BZ, will this affect the price of another identical canister being sold on another shuttle?

Per canister, it runs through the list and runs the formula on each valid gas. 

It does still lose value due to what happens in another function, but yeah. 



> 
> 
> After reading through the code handling exports, I've come to the conclusion that elasticity does absolutely nothing to address the problem of cargo cheesing lavaland BZ for millions. Instead of selling 1 large canister they can just separate the gas into multiple canisters to bypass elasticity, balance by tedium.

To make millions you would have to make hundreds of canisters. 

Tedium is actually a valid way to improve things, and if it's truly necessary, it can be made brutal by touching the bz value (e.g. set it to 3.)

2021-01-27 13:04 UTC, githubuser343 commented
> Per canister, it runs through the list and runs the formula on each valid gas.

Do you have any idea how much it takes to produce 20000 mols of hyper noblium?

2021-01-27 13:06 UTC, Sinestia commented
> 
> 
> > Per canister, it runs through the list and runs the formula on each valid gas.
> 
> Do you have any idea how much it takes to produce 20000 mols of hyper noblium?

From old fusion, quite a lot. I haven't felt a surge of inspiration to do much of new fusion

Not sure what point this is leading to -- if it's that this doesn't affect hypernob, then yeah I said that it barely does in the PR description and that I'm fine with it.

2021-01-27 13:25 UTC, Sinestia commented
If it is that much of an issue

it would be possible to use two different elasticity values, one within the canister used in the gas worth calculation, and another for the canister itself cumulatively when fed to centcom. This would result in harsh penalties for stacking canisters, however it would have its own downsides (such as mixing different gases in a shipment, granted, that's gonna be a pretty rare scenario.)

But for now i'll leave it til there's feedback from higher ups

2021-01-27 15:08 UTC, TheFakeElon commented
@Sinestia People can just split the canister's contents quickly with 2/3 connector ports to completely circumvent this system. The limit should be per shuttle, this lets transit time act as a buffer rather than the canisters themselves

2021-01-27 16:43 UTC, Sinestia commented
> 
> 
> @Sinestia People can just split the canister's contents quickly with 2/3 connector ports to completely circumvent this system. The limit should be per shuttle, this lets transit time act as a buffer rather than the canisters themselves

It's not a complete circumvention, you are still having to sell 15k canisters instead of what is currently done

I can give it a go though, because this is honestly very bandaid-y.

2021-01-29 09:42 UTC, PowerfulBacon commented
Does the price drop to 0 or just a really small number?

2021-01-29 09:57 UTC, francinum commented
Better question, actually. From a reading of the code you never adjust the permanent price, elasticity is only calculated per canister, could this conceivably result in a higher rate of return via splitting up the contents into multiple canisters of lower molar content?

2021-01-29 12:40 UTC, Autisem commented
Maby add stocks, Valua of items increases over time and selling such item/product reduces the price based on how much you sold, you then have to wait again for prices to increase or sell at super low prices

2021-01-29 13:04 UTC, Sinestia commented
> Does the price drop to 0 or just a really small number?

Marginal revenue (price per extra unit) drops to an infinitesimally small number

> Better question, actually. From a reading of the code you never adjust the permanent price, elasticity is only calculated per canister, could this conceivably result in a higher rate of return via splitting up the contents into multiple canisters of lower molar content? Time is no object, and due to other systems at play, the iron for manufacturing canisters is no item either.

I'm having it combine all of the gas and treating the gas aside from the canisters, but yes, with the straight port that is how it works (is pointed out in the comments there, even, albeit in very broken english.)

It'll be as elon described pretty much
> Maby add stocks, Valua of items increases over time and selling such item/product reduces the price based on how much you sold, you then have to wait again for prices to increase or sell at super low prices

That'd be nice but that's more of an export overhaul that would likely re-use whatever I do

2021-01-29 14:33 UTC, PowerfulBacon commented
Wait I don't see how this fixes it. Just separate the gas into more cans.

2021-01-29 14:35 UTC, PowerfulBacon requested changes
Lists should be static / typecaches of if they never change rather than a local list.
All this will do is make people split them into 5000 moles per canister to get a good amount of money, since its only elastic per can

2021-01-29 14:39 UTC, Sinestia commented
I'd hold off on review til it behaves as suggested, albeit former is appreciated

~~whats reviewable will be worse,  I promise /s~~

2021-01-29 14:39 UTC, Sinestia commented
wait fuck oops i meant to find the draft button lol

2021-01-29 18:18 UTC, ike709 commented
If you really wanted this to work you'd need to modify cargo exports to add up all of the gasses being exported and then apply elasticity to the totals.

2021-02-23 00:45 UTC, closed without merging

2021-03-11 05:46 UTC, bloons3 commented
@ike709 could this be merged while the total gas exported is used in a later PR?

2021-05-20 01:11 UTC, TheFakeElon commented
rip

2021-05-20 06:06 UTC, Sinestia commented
😳