Fixes a runtime when crawling in dual-port air vents
BeeStation/BeeStation-Hornet pull request #3516
Opened 2021-01-29 14:21 UTC by r1ks-iwnl

## About The Pull Request
![image](https://user-images.githubusercontent.com/69760936/106285914-b7c3d300-624d-11eb-82b2-275a4c943bb9.png)
Turns out a runtime happens every time you tried to vent crawl in a dual-port vent if not sitting on the same tile as the vent.

## Why It's Good For The Game
Fix

## Changelog
:cl:
fix: Ventcrawling in dual-port air vents actually works now.
/:cl:

2021-01-29 14:29 UTC, PowerfulBacon reviewed
This doesn't fix your runtime. Runtime will occur on line 41 because vent_found is null if the check on line 38 fails Intent lines 41 and 42 or change line 38 to be is_type_inchace bla bla bla && machine.can_crawl_through

2021-01-29 14:29 UTC, PowerfulBacon requested changes
see above

2021-01-29 14:30 UTC, r1ks-iwnl commented
Welp this magically fixed it for me i guess

2021-01-29 14:31 UTC, PowerfulBacon commented
```
if(is_type_in_typecache(machine, GLOB.ventcrawl_machinery) && vent_found.can_crawl_through())
	vent_found = machine
```
This doesn't fix it, you likely weren't testing it on the same pipe that was happening on the server. This will likely cause a runtime if you have a thermomachine next to a vent.

2021-01-29 14:58 UTC, r1ks-iwnl commented
Tested it again and it works perfectly fine for me, doesn't cause any runtimes with a thermomachine either

2021-01-29 17:01 UTC, Archanial commented
> This doesn't fix your runtime. Runtime will occur on line 41 because vent_found is null if the check on line 38 fails Intent lines 41 and 42 or change line 38 to be is_type_inchace bla bla bla && machine.can_crawl_through

It should because dual vent is not unary, thus can_crawl can be accessed

2021-01-30 19:06 UTC, PowerfulBacon commented
whatever caused the first runtime will still runtime here.

2021-01-30 21:36 UTC, r1ks-iwnl commented
> whatever caused the first runtime will still runtime here.

As i said this does fix the runtime, it happened if i tried ventcrawling while not sitting directly on top of the vent, if i tried to ventcrawl while being on a tile next to the vent it would runtime, after this changes it doesn't cause any runtimes.

2021-01-31 10:44 UTC, PowerfulBacon commented
You fixed 1 specific instance of it happening, although the code afterwards is complete shitcode and will still runtime if it ever gets that far

2021-01-31 10:59 UTC, PowerfulBacon commented
hm in game it looks like it is impossible to achieve, still shitcode but its not your shitcode

2021-01-31 10:59 UTC, PowerfulBacon approved these changes

2021-01-31 10:59 UTC, merged