Adds the Snake Operative Kit
BeeStation/BeeStation-Hornet pull request #3543
Opened 2021-02-01 05:57 UTC by Victor239

## About The Pull Request

Wasn't sure whether to put this under Badassery or Bundles categories.

The 20 TC Snake Operative Kit is intended to make you feel like a badass Solid Snake at taking down opponents - with a cost. 

The first and most notable weakness is if you get this kit you will be pacified. The second is that several of the outfit pieces are no-drop, and highly obvious Syndicate gear. These ldownsides are to limit how robust this kit is, and make it more of a hardmode which requires a certain style of play. 

**Included in this kit is:**
- CQC Manual (you'll basically only be able to use the Chokehold)
- Chameleon Projector
- Syndicate Space Suit box
- Agent ID
- *No-drop clothing pieces:* combat uniform, syndicate mask, combat gloves, combat boots and syndicate duffel bag.
- *Removable clothing:* night vision goggles and assault belt.

All in all you'll be forced to look like a validman at all times, but with the NVGs, chameleon projector and CQC you'll be a superb ambusher and able to quickly knock out any Assistant validhunting you. Good for those who are very patient, or alternatively for those who want to show off how robust they are. 

![](https://i.imgur.com/ZDY79Wb.png)

## Why It's Good For The Game

New kit forces an interesting style of stealth antag which is fairly lacking at the moment, and also gives a way for the most robust to show off just how they good they are by being pacified and looking like a valid always. 

## Changelog
:cl:
add: Adds the Snake Operative Kit for 20 TC. Includes CQC, a cham projector and a number of other items, however you are also pacified and several clothing items are no-drop. 
/:cl:

2021-02-01 06:24 UTC, sircope commented
looks ugly, what about a bandana instead of the mask??

2021-02-01 07:12 UTC, TheFakeElon commented
I know literally nothing about metal gear besides the box memes, and yet there's no stealth implant or at the very least a normal box 😔

2021-02-01 07:32 UTC, Victor239 commented
The sprites can be updated later by spriters if need be but it's fine for now. 

I was really considering the stealth implant instead of chameleon projector but it's too OP in my opinion, it completely negates the downside of looking like an obvious valid and makes it easy to run up to someone full speed in a hallway and attack them even.

2021-02-01 09:29 UTC, REALALFREDCOLLINS commented
Hello Victor 'White' Pride

2021-02-01 11:58 UTC, Autisem commented
swap the projector for the stealth implant and then its good, I dont care that the projecter is a better item I want my fucking box

2021-02-01 12:01 UTC, Autisem commented
On another note, maby give them syndie tools aswel so they can atleast break into area's more easily.

Chameleon mask maby to combo with the agent card?

2021-02-01 14:42 UTC, heepox commented
Funny, but contractor is superior in allmost every way that matters to this.

2021-02-01 14:46 UTC, heepox commented
maybe make the kit more unique than haha pacifist cqc stealthy boi
and wasent there a bug that made you able to use martial arts even when pacifist? or was that just psychotic brawling martial art that did that.

2021-02-01 15:17 UTC, PowerfulBacon commented
solid snake without the solid snake stealth box?

2021-02-01 15:20 UTC, PowerfulBacon reviewed
comes with all this stuff but gets 1-tapped by a flash

2021-02-01 15:20 UTC, PowerfulBacon commented on code/modules/clothing/snakeop.dm
> +	else
hm

2021-02-01 16:15 UTC, Victor239 commented
Sure I can add syndie tools to the belt. Not giving them a cham mask, they're supposed to look obvious.

It's not supposed to be better than contractor. This forces a more tactical style of stealth than just run around in your chameleon outfit. 

Alright I'll give them a stealth implant, but a nerfed version which forces them to move slowly. Surely some of you have played blitz ops and just run up to the cap with a stealth implant and been able to instantly defeat em with CQC, as well as easily escape after with it. 

The space suit helmet is flashproof.

2021-02-01 20:46 UTC, sircope commented
also, why pacifism? it's quite obvious snake killed people in the games

2021-02-01 22:18 UTC, TheFakeElon commented on code/modules/clothing/snakeop.dm
> +	else
*cry

2021-02-01 23:57 UTC, Victor239 commented
Because it's too robust to have all these particular Syndicate items and _not_ have a significant downside.

2021-02-02 05:46 UTC, ike709 commented
Gotta give them the box, man.

2021-02-02 08:34 UTC, PowerfulBacon commented
Also you should make your own CQC for this considering the majority of moves are unusable. How are you actually meant to win any fights if someone is coming after you without bypassing pacifism entirely

2021-02-02 14:34 UTC, Victor239 commented
Chokehold is a 3 hit 40 sec sleep. If you're up against 2 people then you've messed up the stealth approach, but you can still instantly aggro grab and throw one into another to stun. I could add something like the Karate combos to it but I don't think it'd be that helpful on top of the existing moves. 

To reiterate it's supposed to be a challenging kit to use. It can be tweaked later down the line but I'd rather it be too difficult than too easy with it, since CQC is extremely robust even whilst pacified and it's niche is to be a challenge.

2021-02-02 18:41 UTC, Autisem commented
Considering though that the projector is much more poewrfull since it lets you dodge bullets and other suck attacks way more easily. Also this antag type still cant murder bone, rush ops are powerfull because they only need the disk. They need to do it only once while youd have to do it consistnatly with this kit

Finaly like bacon said maby modified CQC to give them either diffrent moves or same moves but only stam damage

2021-02-02 18:47 UTC, Autisem commented
Also being essentialy valid is a MAJOR downside because literly everyone will hunt you for gamer gear

2021-02-02 19:28 UTC, heepox commented
list of things a true Solid snake reference should have
-Cigarettes
-Lighter
-Bandana (the one you tie across your forehead)
-Facepaint
-Sneaking suit
-Silenced pistol (the tranq pistol)
-A combat knife
-jackboots
-The legendary carboard bawks
-Fulton kit
-Combat gloves
-Agent ID
-Some type of CQC with chokeholds, bodyslams and disarms.
-Flashbangs
-Flash and bang protection. (not everyone can be arsed to just get earmuffs and flashproof eyewear (there are plenty you can get))

(reason no mask is because you gotta eat and drink bro unless you give them a special mask like the clown/mime one)


If you just want a Haha pacifist robustinator spaces people with 1 click stuns then dont waste a reference on it.

2021-02-02 20:25 UTC, Autisem commented
> list of things a true Solid snake reference should have

> -Lighter

e-cig with maby healing chem?

2021-02-03 14:56 UTC, Victor239 commented
> silenced pistol, knife, enhanced CQC, etc

I haven't played MGS so fair enough that I may be using the reference wrong and I'd rather not detract from it. I may just remove the Snake references then because I can't imagine how I'd make a kit that would be suitable for traitors with all this stuff. 

Maybe just make a nuke op bundle with the full package and a traitor kit with current loadout minus the references.

2021-02-03 19:23 UTC, PowerfulBacon commented
Could just be a midround then you can give it more powerful and snake like gear

2021-02-03 22:16 UTC, sircope commented
> > silenced pistol, knife, enhanced CQC, etc
> 
> I haven't played MGS so fair enough that I may be using the reference wrong and I'd rather not detract from it. I may just remove the Snake references then because I can't imagine how I'd make a kit that would be suitable for traitors with all this stuff.
> 
> Maybe just make a nuke op bundle with the full package and a traitor kit with current loadout minus the references.

a reference item referencing something you never played? a bold choice

2021-02-04 00:28 UTC, Victor239 commented
Eh it's popular enough that it's easy to recognise his gear

2021-02-08 19:17 UTC, Tennessee116 commented
Use the r4407 Solid Snake sprites.

2021-02-10 23:55 UTC, TheFakeElon requested changes
Give snake man a box

2021-02-10 23:55 UTC, TheFakeElon commented on code/modules/clothing/snakeop.dm
> +	else
```suggestion
	if(!used_up)
```

2021-02-10 23:55 UTC, TheFakeElon commented on code/modules/clothing/snakeop.dm
> +			user.dropItemToGround(H.back)
```suggestion
			for(var/item/I in H.get_equipped_items())
					H.dropItemToGround(I)
```

2021-02-10 23:55 UTC, TheFakeElon commented on code/modules/clothing/snakeop.dm
> +			user.equip_to_slot_or_del(new /obj/item/storage/box/syndie_kit/space(user), SLOT_IN_BACKPACK)
I'd make this a list and do something like suggested above with `equip_to_appropriate_slot()` instead of drop items

2021-02-10 23:55 UTC, TheFakeElon commented on code/modules/clothing/snakeop.dm
> +	var/used_up = FALSE
nit-pick but `used` would be better

2021-02-11 07:33 UTC, TheFakeElon commented on code/modules/clothing/snakeop.dm
> +			user.dropItemToGround(H.back)
```suggestion
			H.unequip_everything()
```

2021-02-15 20:28 UTC, Rukofamicom commented
Needs stealth implant instead of chameleon projector. I disagree that the stealth implant is flat better - both have their strengths and weaknesses.

2021-02-19 00:33 UTC, Victor239 commented
Will probably rework this later into a midround instead so they can have all the gear + more and be unpacified.

2021-02-19 00:33 UTC, closed without merging