Remove the extended gamemode from Sage
BeeStation/BeeStation-Hornet pull request #3668
Opened 2021-02-18 16:56 UTC by Sinestia

## About The Pull Request
( i hope you like my title ) 

I set extended's odds to 0, and moved it in the config with an explanation as to why. 

**I considered redistributing the points to normal secret_extended, but opted not to. If that's desirable just ask or submit it as a review and I'll be happy to do it.** 

## Why It's Good For The Game

Currently, extended running on Sage causes an issue where all 3 station objectives are blared out. This is caused by a goof I made when I fixed station objectives being disabled altogether on sage with the creation of NO_INTERCEPT_REPORT.

Aside from the bug, Sage still shouldn't be running normal extended.

It's not good when the gamemode can be meta'd by checking the cargo computer and 1/5th of the server immediately cryos. You can patch that up with admin intervention but frankly that seems very silly to me when secret_extended works perfectly fine. 

**That's why I opted to do this instead of submitting a fix first -- Because the gamemode is designed to give you 3 objectives and a fix won't change that.**
## Changelog
:cl:Froststahr
config: EXTENDED set to 0, moved down the config file with a description explaining why. This is distinct from secret_extended, which remains in rotation at high odds. This applies to Sage.
/:cl:

2021-02-18 17:07 UTC, PowerfulBacon submitted a review, later dismissed

2021-02-18 17:07 UTC, PowerfulBacon commented
Some people do like the knowing extended mode to know when its safe to build

2021-02-18 17:09 UTC, githubuser343 commented
Some of the best rounds I've played were extended, the game is not just about antag rolling and combat. Extended allows for longer rounds where you can enjoy doing projects that just take too long for normal rounds.

2021-02-18 17:11 UTC, PowerfulBacon commented
This doesnt remove extended, just the extended version that gives 3 station objectives.

2021-02-18 17:44 UTC, Sinestia commented
i got someone with the clickbait oml

2021-02-18 22:42 UTC, Crossedfall commented on config/Sage/game_options.txt
> +PROBABILITY EXTENDED 0
```suggestion
## Creates issues when NO_INTERCEPT_REPORT is enabled
PROBABILITY EXTENDED 0 
```

2021-02-18 22:42 UTC, Crossedfall commented on config/Sage/game_options.txt
> +PROBABILITY EXTENDED 0
This note should be mirrored to Golden's config as well.

2021-02-18 22:43 UTC, Crossedfall requested changes
Mirror the note to Golden's config since that's the default one-shots use

2021-02-19 00:50 UTC, BeloneX approved these changes, later dismissed

2021-02-19 02:06 UTC, Sinestia commented
Mirrored

2021-02-23 00:46 UTC, Crossedfall approved these changes
Config applied

2021-02-23 00:47 UTC, merged