Brig physician reversion thing which means that now they are a member of sec, but dont get sec gear but do get proper access to their shiz
BeeStation/BeeStation-Hornet pull request #3692
Opened 2021-02-20 21:45 UTC by PowerfulBacon

## About The Pull Request

Makes brig physician a member of security.
Brig physician now spawns with a mindshield.
Brig physician access is now an actual access titled 'brig infirmary'
(From pre-change) brig physician no longer has security or brig access, meaning they cannot get access to security gear.

Additionally, while I am here, this PR removes keycard auth from security personnel, because there is absolutely no reason non-command should have keycard auth (Security is just as good as regular crew and shouldn't be given command tools for being sec).

## Why It's Good For The Game

Unlike the lawyer, a brig physician actually works for sec rather than independently from security so it doesn't work as a civilian position.
A lot of people don't like the changes that happened with the brig phys update, which was made to give less security gear to them however was way too extreme.
This PR brings back the brig physician everyone knows and loves while removing their access to security tools at the same time.
Since the brig physician isn't expected to be in medical, they answer to the HOS not the CMO.

## Changelog
:cl:
add: Brig physician is now mindshielded.
add: Brig physician access now works properly.
add: Uses brig phys access on some maps to allow the brig phys to reach the surgery rooms.
del: Removes security officer's keycard auth access.
tweak: Brig physician now answers to the HOS instead of the CMO.
/:cl:

2021-02-20 21:49 UTC, PowerfulBacon commented
obviously being a coder I didnt even check if it launches

2021-02-20 21:49 UTC, PowerfulBacon commented on code/modules/clothing/suits/jobs.dm
> +r
```suggestion
/obj/item/clothing/suit/hazardvest/brig_phys
```

2021-02-20 21:49 UTC, Naevii commented
speedmerge

2021-02-20 21:50 UTC, PowerfulBacon commented
actually im testing it now

2021-02-20 21:52 UTC, PowerfulBacon commented on code/modules/jobs/job_types/brigphys.dm
> +	minimal_access = list(ACCESS_BRIGPHYS, ACCESS_SEC_DOORS, ACCESS_COURT, ACCESS_MAINT_TUNNELS, ACCESS_MORGUE, ACCESS_WEAPONS, ACCESS_MEDICAL, ACCESS_KEYCARD_AUTH)
WHY DID THEY HAVE ACCESS_KEYCARD_AUTH!

2021-02-20 21:56 UTC, PowerfulBacon commented
Ok the brig phys access actually works and is assignable on the HOP's console.

2021-02-20 22:03 UTC, Victor239 commented
Originally Sec was given keycard auth just for changing alert level, since it doesn't make sense that it's dependent on say getting the CMO to agree that nuke ops are a red alert threat and getting to their office to auth. Instead the Warden and HoS can jointly red alert. 

Wasn't the best implementation though since keycard auth has access to other things like BSA, which isn't required here. It should probably be split into two different access levels.

2021-02-20 22:04 UTC, PowerfulBacon commented
Normal seccies shouldnt be able to change the alert at all. Its not their job, it shouldn't be. Just because they have somewhat of a metashield doesn't mean they should be given more than it makes sense for them to have.

2021-02-20 22:06 UTC, Victor239 commented
In the event of HoS being killed, then Warden and another seccie should be able to imo. It's almost always a dire situation if the HoS is murdered or missing.

2021-02-20 22:07 UTC, PowerfulBacon commented
they cant even get into the places with keycard auth anyway. Since its in the name of security they should only have as much access as they need and nothing more, otherwise that's a security flaw.

2021-02-20 22:09 UTC, yyzsong commented
Should probably keep CMO as a head. They *are* still a doctor after all.

2021-02-20 22:10 UTC, Naevii commented
> Should probably keep CMO as a head. They _are_ still a doctor after all.

they are more dependant on security  rather than on medical, they spend most of their shift in security and hardly ever interact with medbay.

2021-02-20 22:12 UTC, Victor239 commented
> Since its in the name of security they should only have as much access as they need and nothing more, otherwise that's a security flaw.

Agreed, and what I'm suggesting here is that setting alert level makes more sense as a Security function primarily and Command secondary. After all it's focused on "what threats is the station facing", how useful is the RD's input here even? HoS' responsibility should be keeping the crew updated on how alert to threats they should be.

2021-02-20 22:25 UTC, PowerfulBacon commented
eh sec should have no access to keycards or anything related to command duties

2021-02-20 22:30 UTC, Rukofamicom commented
This PR is one of the two ideal solutions to the brig physician problems. Brig physician is now primarily a doctor for Sec and inmates. Innate access to security equipment should never have been something they had because people shouldn't be playing brig physician with the intent to act/arm up as an officer - but the option remains available with HoS approval in times of need. 

> sec should have no access to keycards or anything related to command duties

I second this and it's a nice bonus to see this as a part of the PR. Security should not have unilateral control over alert levels when alert levels are the primary limiting factor on what security is and isn't allowed to do. Security deserves to be held in check just like every other department and it should be up to command staff whether or not they get to kick into powergamer mode or not.

2021-02-20 22:43 UTC, PowerfulBacon commented on code/modules/jobs/job_types/brigphys.dm
> +	department_head = list("Head of Security")
```suggestion
	department_head = list("Head of Security", "Chief Medical Officer")
```

2021-02-20 22:43 UTC, PowerfulBacon commented on code/modules/jobs/job_types/brigphys.dm
> +	supervisors = "the head of security"
```suggestion
	supervisors = "the head of security and the chief medical officer"
```

2021-02-20 22:49 UTC, Victor239 commented
> Security deserves to be held in check just like every other department and it should be up to command staff whether or not they get to kick into powergamer mode or not.

This is already a powergaming rule violation so it seems redundant to me. If people really are abusing that by frivolously raising threat levels then just ban them for it.

2021-02-20 22:56 UTC, Firespider01 approved these changes

2021-02-20 23:05 UTC, Crossedfall requested changes
Alright. I've sat down and talked to Bacon about this for a bit and I've shifted from being entirely neutral to being for the original change.

The main thing for me is the inconsistencies presented in how the brig physician role is handled. It is not part of security. It was slowly changed to be that against its original design and forced into being part of security, but, looking at it objectively from a design point of view that really doesn't make any sense.

A brig physician is almost identical in function to a department security officer. In-universe, department officers are expected to have a basic understanding of the department they are stationed in so that they can lend a hand if absolutely necessary; their primary focus is to keep that area safe. They have an office in that department, have access to their radio channel, and even has some basic access to the area itself. **BUT**, they are not part of that department. They are part of security.

Similarly... Brig physicians have an office in security, help out with medical related issues, and have access to their radio channel, but they are not part of security. They are a medical officer tasked with servicing that area. *Just like how a department security officer is tasked with serving their assigned area*.

In terms of design, I see no reason why they would be treated as an exception to this long established rule of interdepartmental co-existence.

Going to have to gather more opinions on this, but for now I'm going to slap the DNM on this as it's currently written.

2021-02-20 23:14 UTC, Naevii commented
> Alright. I've sat down and talked to Bacon about this for a bit and I've shifted from being entirely neutral to being for the original change.
> 
> The main thing for me is the inconsistencies presented in how the brig physician role is handled. It is not part of security. It was slowly changed to be that against its original design and forced into being part of security, but, looking at it objectively from a design point of view that really doesn't make any sense.
> 
> A brig physician is almost identical in function to a department security officer. In-universe, department officers are expected to have a basic understanding of the department they are stationed in so that they can lend a hand if absolutely necessary; their primary focus though is to keep that area safe. They have an office in that department, have access to their radio channel, and even has some basic access to the area itself. **BUT**, they are not part of that department. They are part of security.
> 
> Similarly... Brig physicians have an office in security, help out with medical related issues, and have access to their radio channel, but they are not part of security. They are a medical officer tasked with servicing that area. _Just like how a department security officer is tasked with serving their assigned area_.
> 
> In terms of design, I see no reason why they would be treated as an exception to this long established rule of interdepartmental co-existence.
> 
> Going to have to gather more opinions on this, but for now I'm going to slap the DNM on this as it's currently written.

because players who played this role, and security liked this role the way it was BEFORE the "good change"?

if brig physician can't be mindshielded it just allows shitters for easier antag role with more access.

Similarly, there would be no reason to have a person, stationing in brig if you can't even trust them and they exist to make your work harder. 
And as a brig physician one trick pony i can say i would rather see this job entirely removed rather than make it into second lawyer.

2021-02-20 23:48 UTC, Crossedfall commented
Discussions moved to discord, since having prolonged debate is difficult on github.

2021-02-20 23:55 UTC, PowerfulBacon commented
So is on discord cause the messages get lost after 5 minutes (and I have no idea where the discussion even is)

2021-02-20 23:56 UTC, Crossedfall commented
> 
> 
> So is on discord cause the messages get lost after 5 minutes (and I have no idea where the discussion even is)

It's on discord because github isn't a good place for prolonged discussion and never has been. I don't like Discord as a main alternative, and would prefer the forums, but this is how it went down.

2021-02-21 06:07 UTC, TheFakeElon commented
better emotes on discord

2021-02-21 10:47 UTC, PowerfulBacon commented
I am almost perfectly split at this point between making them a member of sec and not since the arguments for both sides are pretty strong.

To me it would be like departmental sec, as like you said, departmental sec are expected to have basic understanding of the department, answer to both heads and are a member of both security and their respective department at the same time. Brig physician should be both am member of security and medical at the same time if we follow that, original version of this PRw as flawed and did not have them answering to the CMO however that has been changed.

2021-02-22 19:48 UTC, Sapfearon commented
Brig phys worked like IRL police medic - he is medic, he is member of police AND has relevant police training. Yes, he is not carrying guns nor arrest, but he is trusted member of police and not some random medic assigned to area.
Which is why reverting him back to being mindshielded is good idea.
By the way, why detective is job rank lower then sec officer? He is mindshield, he is not private detective and irl detective is big step up from normal grunt. Should be same way here imo. Opens up slot for non-mindshielded private investigator too.

2021-02-24 19:43 UTC, Socialistion commented
Add this please brig phys is one of my favorite jobs and I quite enjoyed being a sec doctor. I don't have much to actually contribute to any discussion but please, removing brig phys mindshield was probably the most idiotic thing that could've been done in my opinion.

2021-03-02 21:03 UTC, PowerfulBacon commented
@Crossedfall yay or nay

2021-03-20 14:29 UTC, closed without merging