implements tgstation commit 2187c90093767b356e27177b2dadb6b5072e4d6e and 1eeca7c8548215e6df203cdbb2c1587252258d43
BeeStation/BeeStation-Hornet pull request #3696
Opened 2021-02-21 12:18 UTC by bloons3

## About The Pull Request

These SHA1's look cool so we should commit them

## Why It's Good For The Game

Trust me.
## Changelog

2021-02-21 12:20 UTC, MNarath1 commented
Very funny

2021-02-21 12:28 UTC, MNarath1 commented
Also liking your own PR really bloons?

2021-02-21 13:38 UTC, BeloneX approved these changes, later dismissed

2021-02-21 14:38 UTC, Sinmero commented
> Trust me.

bruh

2021-02-21 15:28 UTC, TeomanTheGreat commented
No changelog. Smh

2021-02-21 16:30 UTC, OceanFish1 commented
another null crate nerf moment

2021-02-21 17:19 UTC, francinum approved these changes

2021-02-22 03:13 UTC, bloons3 commented
![image](https://user-images.githubusercontent.com/3241376/108652389-a1461b80-7489-11eb-9502-da5148fe6ad2.png)

2021-02-22 07:06 UTC, francinum requested changes
Give it a changelog, you know the rules.

2021-02-22 08:19 UTC, park66665 commented
`/datum/supply_pack/emergency/specialops` has a reference to `NULL_ENTRY`. You probably want to change that too.

2021-02-22 08:42 UTC, park66665 commented on code/modules/cargo/packs.dm
> +	"(*!&@#SAD ABOUT THAT NULL_ENTRY, HUH OPERATIVE? WELL, THIS LITTLE ORDER CAN STILL HELP YOU OUT IN A PINCH. CONTAINS A BOX OF FIVE EMP GRENADES, THREE SMOKEBOMBS, AN INCENDIARY GRENADE, AND A \"SLEE
```suggestion
	desc = "(*!&@#SAD ABOUT THAT NULL_ENTRY, HUH OPERATIVE? WELL, THIS LITTLE ORDER CAN STILL HELP YOU OUT IN A PINCH. CONTAINS A BOX OF FIVE EMP GRENADES, THREE SMOKEBOMBS, AN INCENDIARY GRENADE, AND A \"SLEEPY PEN\" FULL OF NICE TOXINS!#@*$"
```

2021-02-22 08:58 UTC, bloons3 commented on code/modules/cargo/packs.dm
> +	"(*!&@#SAD ABOUT THAT NULL_ENTRY, HUH OPERATIVE? WELL, THIS LITTLE ORDER CAN STILL HELP YOU OUT IN A PINCH. CONTAINS A BOX OF FIVE EMP GRENADES, THREE SMOKEBOMBS, AN INCENDIARY GRENADE, AND A \"SLEE
😰

2021-02-22 15:23 UTC, PowerfulBacon commented
🔑

2021-02-23 08:32 UTC, BowStache commented
only reason to play cargo smh

2021-02-23 08:35 UTC, bloons3 commented
> only reason to play cargo smh

If the only reason you play Cargo is for the chance of antag gamer gear, play on a different server.

2021-02-23 08:36 UTC, mudzbe commented
> only reason to play cargo smh

THIS and guns. This PR is massive cringe

> > only reason to play cargo smh
> 
> If the only reason you play Cargo is for the chance of antag gamer gear, play on a different server.

He does

2021-02-23 08:46 UTC, Edgar-Allan-ShitPoest commented
I gotta say this is one of the dumbest PR ideas. Maybe instead of removing nullcrates you should work on something else cargo can do?

2021-02-23 08:54 UTC, BowStache commented
bloons3? more like cringe3

2021-02-23 12:54 UTC, Sinestia commented
> 
> 
> I gotta say this is one of the dumbest PR ideas. Maybe instead of removing nullcrates you should work on something else cargo can do?

You're welcome to do so, pretty much everyone agrees cargos in a pretty poor state 

That's not an argument against the removal of nulls tho lol

If I had to guess the only alternative that might be accepted would be like capping the purchases to 1 (but i doubt that tbh)

2021-02-23 12:59 UTC, Edgar-Allan-ShitPoest commented
> 
> 
> > I gotta say this is one of the dumbest PR ideas. Maybe instead of removing nullcrates you should work on something else cargo can do?
> 
> You're welcome to do so, pretty much everyone agrees cargos in a pretty poor state
> 
> That's not an argument against the removal of nulls tho lol
> 
> If I had to guess the only alternative that might be accepted would be like capping the purchases to 1 (but i doubt that tbh)

Agree with sucking my nuts lole :^).
Stop nerfing fun shit because you wanna be a giant baby.

2021-02-23 13:07 UTC, Sinestia commented
> 
> 
> > > I gotta say this is one of the dumbest PR ideas. Maybe instead of removing nullcrates you should work on something else cargo can do?
> > 
> > 
> > You're welcome to do so, pretty much everyone agrees cargos in a pretty poor state
> > That's not an argument against the removal of nulls tho lol
> > If I had to guess the only alternative that might be accepted would be like capping the purchases to 1 (but i doubt that tbh)
> 
> Agree with sucking my nuts lole :^).
> Stop nerfing fun shit because you wanna be a giant baby.

https://www.youtube.com/watch?v=NBLyl2UIoVs

2021-02-23 13:25 UTC, AtlasRules commented
griefsky is already EMP proof, unless you have 2/3 people or a borg you're not going to live long unless you're not unrobust

terrible PR/10 too much /tg/

2021-02-23 13:32 UTC, BeloneX commented
> > > I gotta say this is one of the dumbest PR ideas. Maybe instead of removing nullcrates you should work on something else cargo can do?
> > 
> > 
> > You're welcome to do so, pretty much everyone agrees cargos in a pretty poor state
> > That's not an argument against the removal of nulls tho lol
> > If I had to guess the only alternative that might be accepted would be like capping the purchases to 1 (but i doubt that tbh)
> 
> Agree with sucking my nuts lole :^).
> Stop nerfing fun shit because you wanna be a giant baby.

Hello moccha.

2021-02-23 13:32 UTC, mudzbe commented
Bloons, take notes https://github.com/BeeStation/BeeStation-Hornet/pull/3723 this is how a real man does a PR

2021-02-23 13:34 UTC, Edgar-Allan-ShitPoest commented
> 
> 
> > Agree with sucking my nuts lole :^).
> > Stop nerfing fun shit because you wanna be a giant baby.
> 
> Hello moccha.

i dont know who moccha is

2021-02-23 13:44 UTC, mudzbe commented
YOU CANNOT CENSOR THE TRUTH

2021-02-23 13:55 UTC, park66665 commented
Headcoder will be informed of this situation as soon as possible. Until @ike709 makes decision, discussion for this PR will be locked.

2021-02-24 01:34 UTC, jupyterkat commented
everything's fine
![image](https://user-images.githubusercontent.com/56778689/108931903-94e5dc80-769c-11eb-9369-78860fd7ab6d.png)

2021-02-24 01:41 UTC, Singularity69 commented
This is fine

2021-02-25 06:54 UTC, bloons3 reviewed
added changelog

2021-02-25 07:05 UTC, bloons3 reviewed
resolve fran's requested changed

2021-02-26 04:10 UTC, francinum approved these changes
Approved without question. I have almost never seen these used by antags without the direct and active aid of cargo.

2021-02-26 04:22 UTC, ike709 commented
At first I wasn't a major fan of this. Then I was shown the logs of how often these get ordered in a round. It's literally multiple dozens per round whenever Cargo gets the credits.

I'm invoking "we can't have nice things".

2021-02-26 04:22 UTC, merged