Ports Delta_time
BeeStation/BeeStation-Hornet pull request #3731
Opened 2021-02-24 02:35 UTC by jupyterkat

## About The Pull Request

ports
tgstation/tgstation#52981
and fixes

## Why It's Good For The Game

you should probably read the tg pr instead

🆑Donkie
code: Process procs now properly utilize deltatime when implementing rates, timers and probabilities, which paves way for easier subsystem tickrate adjustments.
/🆑

2021-02-24 03:06 UTC, TheFakeElon commented
Our contributor guidelines will need to be updated for standardization if this is merged too

2021-02-24 03:14 UTC, jupyterkat commented
will do that

2021-02-24 03:25 UTC, TheFakeElon commented
> will do that

Nah, was mentioning it for maintainers.

2021-02-24 03:35 UTC, jupyterkat commented
okay then

2021-02-24 05:34 UTC, MCterra10 commented
bookmarking for pre-emptive downstream updates
📑

2021-02-24 09:43 UTC, PowerfulBacon commented
Cool

2021-02-24 10:02 UTC, bloons3 commented
@jupyterkat 
The recent lava burns stuff inside of it PR will need to be updated for delta time as well.
It was ported without it

2021-02-24 10:06 UTC, jupyterkat commented
Already updated for delta time

2021-02-24 11:15 UTC, bloons3 commented
Blind copypaste isn't gonna work well.

DRUNK_HEALING is good having it's own process, but you need to remove the calls in Life() about it.
https://github.com/tgstation/tgstation/pull/46507

Double check that we have the Processing system for Quirks/Traits: https://github.com/tgstation/tgstation/pull/35440/files

2021-02-24 11:19 UTC, jupyterkat commented
Not completely blind, but things go through and I can’t fix it all by myself.

2021-02-24 11:20 UTC, bloons3 commented
> Not completely blind, but things go through and I can’t fix it all by myself.

Add a checklist item to it in the main PR post

- [ ] task lists look like this
- [ ] and are good for keeping things on track
- [ ] this one is completed

2021-02-24 11:27 UTC, bloons3 commented
No, don't remove the quirk Process() code.

Remove the DRUNK_HEALING quirk stuff from the Life() process

2021-02-24 11:28 UTC, jupyterkat commented
No need, got most of it working, just tiny things needed to be fixed. I’ll deal with porting life()’s delta time later.

2021-02-24 11:29 UTC, jupyterkat commented
I think the quirk process change should go with that pr

2021-03-07 17:30 UTC, Ghilker commented
point of advice, don't add delta time to atmos stuff, we are removing it because it caused issues with the subsystem and pipelines

2021-03-07 22:03 UTC, jupyterkat commented
@Ghilker pr not merged yet, I’ll port that later

2021-03-22 23:15 UTC, TheFakeElon commented
...Draw straws for review assignment

2021-03-23 23:26 UTC, ike709 commented
@TheFakeElon you win

2021-04-07 17:17 UTC, TheFakeElon commented
> @TheFakeElon you win

😫

2021-04-12 15:11 UTC, utilbird commented on code/game/machinery/spaceheater.dm
> +		if(requiredPower< 1)
```suggestion
		if(requiredPower < 1)
```

2021-04-12 15:11 UTC, TheFakeElon commented on code/modules/mob/living/silicon/pai/pai.dm
> +	var/emitterregen = 1.25
This is a bit more than double 🤔

2021-04-12 15:24 UTC, TheFakeElon commented
Didn't see anything too out of place in the diffs, can't confirm if this accounts for all bee additions yet. I'll check tomorrow (probably)

2021-04-23 05:06 UTC, TheFakeElon requested changes
-----  Important note: Most clockwork stuff doesn't have deltatime accounted for because TG removed it, I would recommend checking clockwork related objects and datums. I listed some below but not all -----

`alert.dm line` 434
`action.dm line` 655
`forced_movement.dm` line 37
`position_point_vector.dm` line 217
`rot.dm` line 38/48 (maybe, not sure about this one)
`wet_floor.dm` line 111. Might need to touch on SSwet_floors if nothing in this proc
`status_effect.dm` line 47
`areas.dm` line 379.
`dynamic.dm` line 583. midround injections use probability on process()
`meteor.dm` line 16. probs on process()

`revolution.dm` line 116/212.
`cloning.dm` line 276. (maybe)
`dance_machine.dm` line 459. prob checks
`race_converter.dm` line 84. prob checks
`airlock_types.dm` line 203. prob checks
`powersink.dm` line 122.
`weldingtool.dm` line 376.

`clockwork_massive.dm` line 61. prob checks
`clockwork_turfs.dm` line 270. prob checks
`brass_clothing.dm` line 131. prob checks
`interdiction_lens.dm` line 59. prob checks
`ocular_warden.dm` line 38.
`prosperity_prism.dm` line 56.
`clockwork_camera.dm` line 71.
`cult_structures.dm` line 169.
`nuclearbomb.dm` all processes.

2021-04-23 05:08 UTC, TheFakeElon commented
I've been through about half of the total process() calls now. 

There might be some false flags in there so I apologize for that in advance

2021-05-13 01:07 UTC, jupyterkat commented
cockcult stuff converted

2021-05-13 02:36 UTC, jupyterkat commented
all the delta_time'able stuff is done now

2021-05-20 01:13 UTC, TheFakeElon submitted a review, later dismissed
Contributor guidelines will need to be updated @ike709

2021-05-27 00:21 UTC, TheFakeElon approved these changes
yolo

2021-05-27 00:21 UTC, TheFakeElon commented
shit

2021-05-30 17:20 UTC, PowerfulBacon approved these changes

2021-05-30 18:53 UTC, ike709 commented
Was this ever actually testmerged?

2021-05-30 22:30 UTC, jupyterkat commented
none of you guys bothered to do it

2021-05-31 22:55 UTC, ike709 commented
Seems okay in TM. YOLO.

2021-05-31 22:55 UTC, merged