[minor] damage overlays fix
BeeStation/BeeStation-Hornet pull request #3774
Opened 2021-02-27 19:38 UTC by kit-katz

## About The Pull Request

fixes an issue where damage overlays overflow and disappear once the damage exceeds the bodypart's health

## Why It's Good For The Game

you cant go wrong with fixing a feature.

## Changelog
:cl:

fix: damage overlays no longer disappear once you deal to much damage

/:cl:

2021-02-28 19:14 UTC, park66665 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +	if((brute_dam < max_damage) && (tbrute != brutestate) || (burn_dam < max_damage) && (tburn != burnstate))
```suggestion
	if((tbrute != brutestate) || (tburn != burnstate))
```

2021-02-28 19:14 UTC, park66665 commented on code/modules/surgery/bodyparts/bodyparts.dm
>  	var/tburn	= round( (burn_dam/max_damage)*3, 1 )
```suggestion
	var/tbrute = round((min(brute_dam, max_damage) / max_damage) * 3, 1)
	var/tburn = round((min(burn_dam, max_damage) / max_damage) * 3, 1)
```

2021-02-28 19:21 UTC, park66665 commented
Also, what's up with the changes in human_parts_greyscale.dmi?

2021-02-28 20:56 UTC, kit-katz commented
huh odd. that one was already merged in a prior PR. why is it here again

2021-02-28 21:59 UTC, park66665 commented
If you see no reason why it was included, then remove it from the PR changes.

2021-03-01 16:53 UTC, PowerfulBacon commented
why is bodypart damage exceeding the maximum?

2021-03-01 23:50 UTC, kit-katz commented
idunno always has been

2021-03-02 15:33 UTC, park66665 requested changes
I won't merge this PR if my remaining review isn't properly addressed.

Let me explain since it seems that you don't get it. The way you fixed the bug actually isn't right.

Suppose there is a limb damaged up to approx. 2/3 of `max_damage`. Due to how `round` works with two arguments, the limb's damage state will be 2. If that limb is damaged beyond the `max_damage`, at once, then `update_bodypart_damage_state` tries to update state higher than 2, preferably 3, as it should.

However, since you made the code block the update when damage is higher than `max_damage`, it will fail to update, and the state will be stuck at 2 when it should be 3.

I hope you understood my review better.

2021-03-03 02:15 UTC, park66665 approved these changes
All clear. This PR is good to go.

2021-03-03 02:20 UTC, merged