attempts to bring supply pod's code up to date + updates adminbuse pod launcher tgui
BeeStation/BeeStation-Hornet pull request #3837
Opened 2021-03-09 07:20 UTC by jupyterkat

## About The Pull Request

ports
tgstation/tgstation#53833
tgstation/tgstation#52611
and a few more pr-less commits

## Why It's Good For The Game

https://user-images.githubusercontent.com/56778689/110433118-2d03ad00-8104-11eb-845d-f82f13c910d8.mp4

## Changelog
:cl:jupyterkat, mrdoombringer
admin: admins can now edit the delays for reversing supplypods
admin: The supplypod menu no longer sucks
imageadd: new supplypod icons
imagedel: old supplypod icons
refactor: refactored supplypods code
/:cl:

2021-03-09 16:46 UTC, PowerfulBacon commented
Who is helen weinstein?

2021-03-09 16:48 UTC, PowerfulBacon commented on code/modules/cargo/supplypod.dm
> +	message_admins(holder)
a

2021-03-09 16:48 UTC, PowerfulBacon commented on code/modules/cargo/supplypod.dm
> +	message_admins("HUU!")
b

2021-03-09 16:48 UTC, PowerfulBacon commented on code/modules/cargo/supplypod.dm
> +	message_admins("HYUU!")
c

2021-03-09 21:39 UTC, jupyterkat commented
do note that the shrapnel cloud button doesn’t actually work because we haven’t got the component yet

2021-03-12 17:19 UTC, francinum commented
Please add a notice or simply disable the shrapnel cloud button if you do not plan to add the component in this PR.

2021-03-13 08:11 UTC, jupyterkat commented
Oh I am planning to add the component in the future

2021-03-14 23:39 UTC, francinum requested changes
@jupyterkat Until you do, please grey out the button in the UI, hide it, or otherwise mark it inoperative.

2021-03-15 11:05 UTC, jupyterkat commented
button is commented out

2021-03-19 04:32 UTC, francinum approved these changes
Sure that works.

2021-03-19 06:21 UTC, francinum commented
No problems after vague abuse. Anything else can get fixed in post.

Approved.

2021-03-19 06:21 UTC, merged