Gary Centcoms new hit game: Space station: battle royale. The all new free, online third person robust-them up complete with the famous robusting rocket, the place where dreams are made. Preorder now on the epic flames store for a free 1 month battle pass.
BeeStation/BeeStation-Hornet pull request #3880
Opened 2021-03-13 20:36 UTC by PowerfulBacon

## About The Pull Request

Improves battle royale a bunch.
 - Battle royale is now on a new map loaded when BR is started.
 - Battle royale now has a shuttle you can jump off at any time.
Its pretty cool

![image](https://user-images.githubusercontent.com/26465327/111043368-175ef200-843a-11eb-99b8-7ce59fe4b15e.png)

Video was too big so here is a single screenshot of my gameplay.

![image](https://user-images.githubusercontent.com/26465327/111043456-93593a00-843a-11eb-9efa-411b2845f412.png)

![image](https://user-images.githubusercontent.com/26465327/111043466-a1a75600-843a-11eb-804d-d394918a1c42.png)

## Why It's Good For The Game

Its really good game, 10/10.

## Changelog
:cl: Gary Centcom CEO of Epic Flames
add: Battle royale map
add: Battle royale robusting rocket.
/:cl:

2021-03-13 21:33 UTC, PowerfulBacon commented
early access btw

2021-03-14 00:58 UTC, wraith-54321 commented
yeah, battle royale is really cool but its very rarely used

2021-03-14 12:36 UTC, eeSPee commented
Probably will never see the light of day because it doesn't comment out a feature everyone likes.

2021-03-14 13:16 UTC, PowerfulBacon commented
ok seems good to me

2021-03-16 08:57 UTC, WhyIsCaeciliusTaken requested changes

2021-03-16 08:57 UTC, WhyIsCaeciliusTaken commented on code/modules/battle_royale/battle_royale_species.dm
> +	inherent_traits = list(TRAIT_NOHUNGER,TRAIT_PIERCEIMMUNE,TRAIT_NODISMEMBER,TRAIT_VIRUSIMMUNE,TRAIT_NODISMEMBER,TRAIT_ALWAYS_CLEAN,TRAIT_FEARLESS)
TRAIT_PIERCEIMMUNE is listed twice

2021-03-16 08:57 UTC, WhyIsCaeciliusTaken commented on code/modules/battle_royale/battle_royale_drops.dm
> +	/obj/item/gun/ballistic/automatic/proto = 1,
This SMG spawns with no firing pin. You need the unrestricted subtype.

2021-03-16 08:57 UTC, WhyIsCaeciliusTaken commented on code/modules/battle_royale/battle_royale_drops.dm
> +	/obj/item/gun/energy/lasercannon = 1,
No firing pin.

2021-03-16 08:57 UTC, WhyIsCaeciliusTaken commented on code/modules/battle_royale/battle_royale_drops.dm
> +	/obj/item/storage/box/syndie_kit/imp_radio = 1,
What's the point of a radio implant in a battle royale?

2021-03-16 16:43 UTC, PowerfulBacon commented on code/modules/battle_royale/battle_royale_species.dm
> +	inherent_traits = list(TRAIT_NOHUNGER,TRAIT_PIERCEIMMUNE,TRAIT_NODISMEMBER,TRAIT_VIRUSIMMUNE,TRAIT_NODISMEMBER,TRAIT_ALWAYS_CLEAN,TRAIT_FEARLESS)
its so nice I had to put it twice

2021-03-16 16:47 UTC, PowerfulBacon commented on code/modules/battle_royale/battle_royale_drops.dm
> +	/obj/item/gun/energy/lasercannon = 1,
fixed

2021-03-16 16:48 UTC, PowerfulBacon commented on code/modules/battle_royale/battle_royale_species.dm
> +	inherent_traits = list(TRAIT_NOHUNGER,TRAIT_PIERCEIMMUNE,TRAIT_NODISMEMBER,TRAIT_VIRUSIMMUNE,TRAIT_NODISMEMBER,TRAIT_ALWAYS_CLEAN,TRAIT_FEARLESS)
wait I only see it once

2021-03-16 16:49 UTC, PowerfulBacon commented on code/modules/battle_royale/battle_royale_species.dm
> +	inherent_traits = list(TRAIT_NOHUNGER,TRAIT_PIERCEIMMUNE,TRAIT_NODISMEMBER,TRAIT_VIRUSIMMUNE,TRAIT_NODISMEMBER,TRAIT_ALWAYS_CLEAN,TRAIT_FEARLESS)
oh TRAIT_NODISMEMBER is twice

2021-03-16 20:00 UTC, PowerfulBacon commented
Needs more guns, harvesting tool seems to not work

2021-03-16 20:01 UTC, PowerfulBacon commented
[19:51:04] Runtime in projectile.dm, line 148: undefined variable /datum/species/human/battleroyale/var/pixel_x

2021-03-16 20:16 UTC, PowerfulBacon commented
this was actually a lot of fun and a big improvement

2021-03-20 14:37 UTC, closed without merging