Remove TRAIT_RADIMMUNE from IPCs
BeeStation/BeeStation-Hornet pull request #3889
Opened 2021-03-15 11:52 UTC by YakiAttaki

## About The Pull Request
for whatever reason, IPCs are the only "silicon" type mob that are immune to rads. Not even borgs, drones, or AIs are immune. Why the hell are IPCs rad immune? Kinda dumb.

## Why It's Good For The Game
Means IPCs can't just tank massive radiation and shrug it off. Makes more sense mechanically as they're just borgs with hands and more freedom.

## Changelog
:cl:
balance: removed IPC's rad-immune trait
/:cl:

2021-03-15 11:53 UTC, bluezorua commented
borgs and drones are rad immune??

2021-03-15 11:56 UTC, heepox commented
Borgs and drones and AI do not take damage from radiation even if they do not have TRAIT_RADIMMUNE as they literally cannot take toxin damage.

2021-03-15 11:59 UTC, YakiAttaki commented
radiation still kills borgs and drones.

2021-03-15 12:02 UTC, bluezorua commented
> radiation still kills borgs and drones.

it litterly doesn't?

2021-03-15 12:02 UTC, YakiAttaki commented
> > radiation still kills borgs and drones.
> 
> it litterly doesn't?

i literally watched a borg die due to radiation

2021-03-15 12:03 UTC, bluezorua commented
> > > radiation still kills borgs and drones.
> > 
> > 
> > it litterly doesn't?
> 
> i literally watched a borg die due to radiation

well then you watched wrong

2021-03-15 12:04 UTC, amidoingitright commented
to clarify borgs and ai aswell as drones suffer burn damage
this occurs at fusion tier rads
which IPC's are immune to

2021-03-15 12:05 UTC, TheFakeElon commented
> well then you watched wrong

They didn't, rads in large amounts causes burn, usually once it's at that stage it one shots them once they're contaminated

2021-03-15 12:06 UTC, bluezorua commented
did you ever do any testing? or do you just want to nerf ipcs for no reason, because 
1. silicons are immune to toxin damage so radiation is harmless
2. ipcs are stupidly hard to deal toxin damage with

2021-03-15 12:07 UTC, amidoingitright commented
there have been fusion rads powerful enough to kill the AI in its sat with the burn damage
are you even listening?

2021-03-15 12:08 UTC, bluezorua commented
> there have been fusion rads powerful enough to kill the AI in its sat with the burn damage
> are you even listening?

rads rarely are that high, and at that point just let ipcs have the radiation immunity because ipcs need some form off buff since they are litteral tissue paper

2021-03-15 12:09 UTC, bluezorua commented
> there have been fusion rads powerful enough to kill the AI in its sat with the burn damage
> are you even listening?

that was pre-nerf fusion, for that to happen you need to make fusion right next to the ai

2021-03-15 12:13 UTC, amidoingitright commented
IPC's are also immune to organ decay
have the easiest revival steps
have their brain in their chest {wildcard but it can trick people}

2021-03-15 12:13 UTC, TheFakeElon commented
> that was pre-nerf fusion, for that to happen you need to make fusion right next to the ai

It happened 40 minutes ago. You're starting to hurt my brain, please stop throwing random false facts around to prove your point.

2021-03-15 12:17 UTC, bluezorua commented
> IPC's are also immune to organ decay
> have the easiest revival steps
> have their brain in their chest {wildcard but it can trick people}

they get 3 shot by welders and can be made completely unrevivable by removing their brain , also emps cause them to just get destroyed, something a tider can easily acquire

they have many ups and man downsides and rad immunity is one of them

2021-03-15 12:18 UTC, bluezorua commented
> > that was pre-nerf fusion, for that to happen you need to make fusion right next to the ai
> 
> It happened 40 minutes ago. You're starting to hurt my brain, please stop throwing random false facts around to prove your point.

I don't know how you manage to get radiation so strong you kill the ai at sat so beats me

2021-03-15 12:20 UTC, bluezorua commented
also spiecies changes require maintainer approval

2021-03-15 12:28 UTC, amidoingitright commented
> also spiecies changes require maintainer approval

> thefakeelon is a bee maintainer
why are you defending a moot point?

2021-03-15 12:41 UTC, TheFakeElon commented
@amidoingitright 
No, he's right. @YakiAttaki should have asked before PRing

2021-03-15 12:41 UTC, TheFakeElon submitted a review, later dismissed
nonetheless

2021-03-15 12:48 UTC, YakiAttaki commented
My apologies

2021-03-15 14:33 UTC, PowerfulBacon requested changes
Look at porting the stuff on NSV that makes IPCs take brain damage instead of mutating when exposed to rads.

2021-03-15 20:24 UTC, PowerfulBacon commented
Also would need maintainer approval for species changes, but since you have an approval anyway it wont be too hard probably

2021-03-16 19:52 UTC, Archanial commented
> 
> 
> > radiation still kills borgs and drones.
> 
> it litterly doesn't?

Extreme rads kill borgs. You are wrong.

2021-03-17 00:58 UTC, TheFakeElon commented
If you're porting then you need to credit the original authors

2021-03-17 01:34 UTC, TheFakeElon requested changes

2021-03-17 01:34 UTC, TheFakeElon commented on code/datums/weather/weather_types/radiation_storm.dm
> +								5;TRAUMA_RESILIENCE_MAGIC
what in the goddamn. what is this semicolom voodoo

2021-03-17 01:34 UTC, TheFakeElon commented on code/datums/weather/weather_types/radiation_storm.dm
> +				if(HAS_TRAIT(H, TRAIT_IPCRADBRAINDAMAGE)) // instead, give IPCs brain damage
I don't see why you'd want to use traits for this, you should just be able to use `isipc(L)`

2021-03-17 01:34 UTC, TheFakeElon commented on code/modules/mob/living/carbon/human/species.dm
> +		if(!(H.getorgan(/obj/item/organ/stomach) && stomach.organ_flags == ORGAN_SYNTHETIC)) // synthetics can't vomit
```suggestion
		var/obj/item/organ/stomach/S = H.getorganslot(ORGAN_SLOT_STOMACH)
		if(S && istype(S) !(S.organ_flags & ORGAN_SYNTHETIC)) // synthetics can't vomit // synthetics can't vomit
```
organs flags are bit flags so you'll have to use bit operators.

2021-03-17 01:34 UTC, TheFakeElon commented on code/modules/mob/living/carbon/life.dm
>  		adjustToxLoss(log(radiation-RAD_MOB_SAFE)*RAD_TOX_COEFFICIENT)
This is already checked in `adjustToxLoss`

2021-03-17 01:34 UTC, TheFakeElon commented on code/modules/reagents/chemistry/recipes/medicine.dm
> +	name = "Radioactive Disinfectant"
The name is a bit misleading 😆

2021-03-17 01:34 UTC, TheFakeElon commented on code/modules/mob/living/carbon/human/species.dm
> +			H.emote(emote_type)
emote calls should (almost) always be done async for.. reasons
```suggestion
			INVOKE_ASYNC(H, /mob.proc/emote, emote_type)
```

2021-03-17 01:34 UTC, TheFakeElon commented on code/datums/weather/weather_types/radiation_storm.dm
> +							H.emote(emote_type)
```suggestion
							INVOKE_ASYNC(H, /mob.proc/emote, emote_type)
```

2021-03-17 01:34 UTC, TheFakeElon commented on code/__DEFINES/traits.dm
> +#define TRAIT_IPCRADBRAINDAMAGE	"rad_brain_damage" // causes IPCs to take brain damage when irradiated
Just check for IPC brains

2021-03-17 06:09 UTC, Lagomorphica commented
Seems fine enough, however, ,make sure the brain traumas it gives you are only Basic, as was highlighted in the PR on NSV - making it only be ones curable with chemistry makes far more sense, since thats about equal to how annoying must mutations are to a human. Randomly getting a Deep Rooted or lobotomy-required brain trauma is a lot worse than almost any mutation I can think of, since even Acid Skin just requires you to be revived and given a mutadone pill.

People do seem to think IPCs are a bit overpowered at the moment, and removing some of their utility that plasmamen have might help - even if I am a bit biased towards playing IPC. It will also give Solder more use, albeit I do hope that the amount of brain damage it causes isn't overboard. I would, however, advise spawning some in Engineering roundstart, akin to how normal Engineers get it - which'd require a mapping change. I'm not sure if this'll be the best on Beestation myself (especially if the surgical traumas are needed, since chemists on golden and sage can be quite uncooperative to an IPC of all people asking for medication), but its still worth trying.

As for the E+015 rads thing, I believe that was changed so that 1000 rads does burn damage? However, for both sides, I feel that,

- If it wasn't changed and you still need E+015 rads, it'd be a bit stupid to have a debilitating thing on IPC's - albeit when I looked in radiation code it was at 1000. 
- If it was changed then brain damage would work, albeit I'd say anything above a basic (chem curable) brain trauma is extremely overkill.

Yes, I am biased towards IPCs, but even people on NSV brought this up - having severe or debilitating brain traumas that kill you and are nigh-incurable short of giving yourself -another- brain trauma, in comparison to being able to just pop mutadone, is pretty debilitating.

2021-03-17 07:04 UTC, YakiAttaki commented
aight i'll fix this pr up another day

2021-03-18 02:35 UTC, closed without merging