fixes ex_act being called multiple times on the same items, thus destroying it in any explosion strengths
BeeStation/BeeStation-Hornet pull request #3906
Opened 2021-03-16 23:47 UTC by jupyterkat

## About The Pull Request

see title

## Why It's Good For The Game

frag12 instant clothing evaporate is not good

## Changelog
:cl:
fix: fixed ex_act being called until the item is destroyed
/:cl:

2021-03-17 00:30 UTC, jupyterkat commented
probably resolves #3732

2021-03-17 15:34 UTC, PowerfulBacon requested changes, later dismissed
but aint lowturf an empty list?

2021-03-17 15:34 UTC, PowerfulBacon commented on code/controllers/subsystem/explosion.dm
>  		cost_lowturf = MC_AVERAGE(cost_lowturf, TICK_DELTA_TO_MS(TICK_USAGE_REAL - timer))
Lowturf is an empty list though

2021-03-17 15:34 UTC, PowerfulBacon commented on code/controllers/subsystem/explosion.dm
> +			high_mov_atom -= movable_thing
again high_mov_atom is an empty list

2021-03-17 19:04 UTC, jupyterkat commented
None of the lists you mentioned are empty when I debugged the subsystem

2021-03-17 19:26 UTC, PowerfulBacon commented
Because it gets filled between firings.
![image](https://user-images.githubusercontent.com/26465327/111526494-b9424f80-8756-11eb-82ad-4b43ffcaa7b6.png)

2021-03-17 19:27 UTC, PowerfulBacon commented
hm although ex_act might fill it pottentially

2021-03-17 19:28 UTC, jupyterkat commented
so the bug is on the modified ex_act procs you requested

2021-03-17 19:29 UTC, jupyterkat commented
Because it still removes the items from the list correctly without runtiming for some reason

2021-03-17 23:51 UTC, jupyterkat commented
Ex_act calls contents_explosion, which adds the item to the SSexplosions list again

2021-03-19 06:24 UTC, francinum commented
Needs investigation. While you're in there can you please just entirely snap zesko's terrible idea to make explosions deal infinite damage to objects immediately in an explosion center?

2021-03-19 06:41 UTC, jupyterkat commented
It’s not zesko’s idea, or change honestly. More like a bug that’s brought in through bacon’s or some other maintainer’s review. This addresses that already.

2021-03-21 12:14 UTC, PowerfulBacon approved these changes

2021-03-21 12:15 UTC, PowerfulBacon commented
do things get damaged at all if they are in the contents of a mob now?

2021-03-21 23:49 UTC, jupyterkat commented
yes, explosion() calls still add them

2021-03-31 15:10 UTC, merged