Donator items 2 electric boogaloo
BeeStation/BeeStation-Hornet pull request #3923
Opened 2021-03-19 15:03 UTC by TheFakeElon

## About The Pull Request

#3368 but not broken. Original PR had a few icon bugs and a missed item inclusion. 

## Why It's Good For The Game

#3368

## Changelog
:cl:
add: Adds donator items in the beecoin shop, for real this time.
/:cl:

2021-03-19 15:50 UTC, park66665 requested changes
You currently are reverting the icon changes of #3420, #3555, #3678, and #3725 unless IconDiffBot is blatantly lying. Please resolve icon conflicts properly.

2021-03-19 16:29 UTC, TheFakeElon commented
ughhhhhhaHHHHHHHHHHA.

Someone should make a better system for handling icon diffs, the fact that this doesn't appear as a conflict is stupid, but I digress.

2021-03-19 17:06 UTC, park66665 approved these changes
LGTM

2021-03-21 21:08 UTC, ike709 approved these changes

2021-03-21 21:08 UTC, merged