Implements a blacklist for problematic contractor dropoff points
BeeStation/BeeStation-Hornet pull request #3933
Opened 2021-03-20 19:17 UTC by Cenrus

## About The Pull Request

Blacklists the following areas from being valid contract dropoff locations:

External solars. Kills the target from lack of pressure and has no plating for the pod to land at.
Toxins test site, for being in space.
AI Upload, core and satellite for being excruciatingly hard and protected by turrets
Shuttles.

## Why It's Good For The Game

People dying from external dropoff locations isn't good, the point of contracting is that the victim is supposed to be sent up and return alive.

## Changelog
:cl:
add: Blacklisted solars, toxins test site, shuttles, and AI Upload/Sat from being contract dropoff locations.
/:cl:

2021-03-20 19:53 UTC, PowerfulBacon commented on code/game/gamemodes/objective.dm
> +														/area/shuttle/))
```suggestion
														/area/solar,
														/area/science/test_area,
														/area/shuttle))
```

2021-03-20 20:42 UTC, eeSPee commented
I'd also like to add, head's offices and anything sec.

2021-03-20 20:43 UTC, PowerfulBacon commented
hold on this can literally be custom player areas made in space can't it?

2021-03-20 21:35 UTC, Archanial commented
Why not use `GLOB.the_station_areas` instead of `sortedAreas`?
Or you can change it completely to use `get_safe_random_station_turf()`

2021-03-21 13:22 UTC, TheFakeElon commented on code/game/gamemodes/objective.dm
> +		if(dropoff_area && is_station_level(dropoff_area.z) && !dropoff_area.outdoors && !is_type_in_typecache(dropoff_area, area_blacklist))
```suggestion
		if(dropoff_area && is_station_level(dropoff_area.z) && !dropoff_area.outdoors && !area_blacklist[dropoff_area.type]
```

2021-03-21 15:18 UTC, Cenrus commented
Not blacklisting sec/head offices from being contract targets. You can earn well over 20 TC (+ the equipment you get in the starter kit) by doing contracts, and secure dropoff locations are part of the challenge of contracting.

2021-03-21 17:56 UTC, PowerfulBacon commented
Revert elons review, that doesnt account for subtypes of areas

2021-03-22 19:38 UTC, heepox commented
No more solars or AI crap? Thank god. Now i dont have to maxcap AI inorder to contract.

2021-03-22 22:04 UTC, TheFakeElon commented
> Revert elons review, that doesnt account for subtypes of areas. Also it doesn't compile

It does account for subtypes. This is the cleaner way to do it.

I might have typo'd and broke it though 😅

2021-03-22 22:11 UTC, TheFakeElon commented
> Revert elons review, that doesnt account for subtypes of areas. Also it doesn't compile

It does account for subtypes. This is the more efficient and cleaner way to do it. Don't know why it didn't compile though, I probably typo'd somewhere 😅

2021-03-22 22:24 UTC, TheFakeElon commented on code/game/gamemodes/objective.dm
> +		if(dropoff_area && is_station_level(dropoff_area.z) && !dropoff_area.outdoors && !is_type_in_typecache(dropoff_area, area_blacklist))
OH, it was the missing closing bracket
```suggestion
		if(dropoff_area && is_station_level(dropoff_area.z) && !dropoff_area.outdoors && !area_blacklist[dropoff_area.type])
```

2021-03-24 00:20 UTC, ike709 commented
There is in fact that helper proc for getting a safe station turf.

2021-03-24 00:36 UTC, Archanial commented
> There is in fact that helper proc for getting a safe station turf.

Yes, `get_safe_random_station_turf()'

2021-03-24 01:02 UTC, francinum requested changes
We have a proper check for this already, `area.valid_territory`

If you want to blacklist anything more specific, please generalize it as an option in map jsons than a hardcoded list.

2021-03-24 04:43 UTC, Sinestia commented
> 
> 
> I'd also like to add, head's offices and anything sec.

Heads and sec aren't that bad, and are Interesting

Main thing is that people shouldn't be being thrown to their deaths

2021-04-04 11:36 UTC, PowerfulBacon commented
stale, reopen when changes applied

2021-04-04 11:36 UTC, closed without merging