Makes a generic recursive movement tracker (#47241)
BeeStation/BeeStation-Hornet pull request #3973
Opened 2021-03-25 23:59 UTC by bloons3

## About The Pull Request
Give the Detective some nice gimmick items to use instead of SecHUDs

- [ ] https://github.com/tgstation/tgstation/pull/47241 - Adds generic popup component
- [ ]  tgstation/tgstation#46891 - Add SpyGlasses
- [ ]  tgstation/tgstation#56883 - Turn the camera into an accessory
- [ ]  tgstation/tgstation#53355 - Merge the Det's Sunglasses into their Spy Glasses

## Why It's Good For The Game

## Changelog
:cl: FatCat1978, ninjanomnom
add: Added new things
code: Moves out the recursive movement tracker found in the orbiting components to a datum usable by other things
/:cl:

2021-03-26 01:30 UTC, bloons3 commented
BRUH
![image](https://user-images.githubusercontent.com/3241376/112564256-ed49f000-8da8-11eb-9381-a1c15b531bf8.png)

2021-03-26 21:28 UTC, Archanial commented on code/game/objects/items/devices/spyglasses.dm
> +		return
```suggestion
	if(!user?.client)
		return
```

2021-03-27 06:02 UTC, utilbird commented on code/game/objects/items/devices/spyglasses.dm
> +		return TRUE
```suggestion
	return slot == ITEM_SLOT_EYES
```

2021-03-27 06:02 UTC, utilbird commented on code/game/objects/items/devices/spyglasses.dm
> +	. = ..()
`.` is the return value of a proc so the direct return method is preferred at the end of a proc
```suggestion
	return ..()
```

2021-03-27 06:02 UTC, utilbird commented on code/game/objects/items/devices/spyglasses.dm
> +	. = ..()
```suggestion
	return ..()
```

2021-03-27 06:02 UTC, utilbird commented on code/game/objects/items/devices/spyglasses.dm
> +	desc = "An eye gougingly yellow pamphlet with a badly designed image of a detective on it. the subtext says \" The Latest way to violate privacy guidelines!\" "
weewoo
```suggestion
	desc = "An eye gougingly yellow pamphlet with a badly designed image of a detective on it. the subtext says \" The Latest Way To Violate Privacy Guidelines!\" "
```

2021-03-27 08:08 UTC, bloons3 commented on code/game/objects/items/devices/spyglasses.dm
> +		return TRUE
Personal preference?

2021-03-27 16:08 UTC, francinum commented on code/game/objects/items/devices/spyglasses.dm
> +		return TRUE
branch bad

2021-03-27 20:51 UTC, DatBoiTim commented
Based?

2021-03-29 15:05 UTC, PowerfulBacon commented
The balance of these seem pretty off, a remote camera that you can view anywhere (not even at a security camera console) and in a second window 24/7.
It would be better as something like the remote camera but you need a console in detectives office to view it, or it takes pictures at the camera with a short cooldown.

2021-03-29 15:07 UTC, PowerfulBacon requested changes, later dismissed
Unintentional changes to skin

2021-03-31 16:35 UTC, bloons3 commented
> Unintentional changes to skin

Which skin? Not seeing it in the git history

2021-04-23 04:32 UTC, TheFakeElon reviewed
`ITEM_SLOT_EYES` is a bitflag and it'll need to use operators as such. `&` instead of `==`, etc.

2021-04-23 04:32 UTC, TheFakeElon commented
Now that I look at it, a lot of our code still uses equality checks. I'll bring it up to date sometime soon:tm:

2021-05-12 02:46 UTC, TheFakeElon commented on code/game/objects/items/devices/spyglasses.dm
> +	if(slot != ITEM_SLOT_EYES)
```suggestion
	if(!(slot & ITEM_SLOT_EYES))
```

2021-05-12 02:46 UTC, TheFakeElon commented on code/game/objects/items/devices/spyglasses.dm
> +	return slot == ITEM_SLOT_EYES
```suggestion
	return slot & ITEM_SLOT_EYES
```

2021-05-20 01:07 UTC, TheFakeElon approved these changes

2021-05-20 01:07 UTC, merged