Adds Random Crits
BeeStation/BeeStation-Hornet pull request #3999
Opened 2021-03-29 21:02 UTC by DatBoiTim

## About The Pull Request
Adds a basic implementation of random crits to the game.

## Why It's Good For The Game
![RandomCrits](https://user-images.githubusercontent.com/68963748/112899640-68b0e780-90b0-11eb-9ba6-0d31c3fb17bb.png)
![More Random Crits](https://user-images.githubusercontent.com/68963748/112899662-70708c00-90b0-11eb-8b64-b105ad5adca4.jpg)
![EvenEvenMoreRandomCrits](https://user-images.githubusercontent.com/68963748/113075865-ce2dd280-919b-11eb-9c2b-46f3952e4b5a.png)

## Changelog
:cl: DatBoiTim
add: Random Crits
add: Gibs for critical explosions
add: Critical Damage for Projectiles
add: Critical damage for melee stuff
add: Funny meme about random crits when you do a random crit
/:cl:

2021-03-29 21:03 UTC, Effemu commented
😐 
by the way do you know joe?

2021-03-29 21:03 UTC, DatBoiTim commented
> 😐
> by the way do you know joe?

Yeah I know Joe Mama

2021-03-29 21:03 UTC, Autisem commented
IF YOU KNOW WHATS GOOD YA YA YOU WILL RUN

2021-03-29 21:04 UTC, DatBoiTim commented
Individual Item Based Crit Chance and Multipliers come later

2021-03-29 21:52 UTC, ilikesaying commented
Random Crits are fair and balanced

2021-03-29 23:48 UTC, St0rmC4st3r commented
Yes. Merge this.

2021-03-29 23:51 UTC, cheesePizza2 commented
this should also add kritzkreig as a modified medigun

2021-03-30 01:50 UTC, OceanFish1 commented
Monkey got random crit on biting someone killing em.....

2021-03-30 01:51 UTC, DatBoiTim commented
> Monkey got random crit on biting someone killing em.....

Cope and Seethe

2021-03-30 06:34 UTC, TheFakeElon commented
Mfw there's no crit sound or runechat CRITICAL HIT!

2021-03-30 11:53 UTC, Singularity69 commented
This is a REALLY GOOD IDEA. SPEED MERGE!

2021-03-30 11:59 UTC, DatBoiTim commented
> Mfw there's no crit sound or runechat CRITICAL HIT!

I cannot do sound design effectively. Hearing damage.

2021-03-30 13:42 UTC, Tennessee116 commented
@zeskorion they're bringing back RNG combat

2021-03-30 13:43 UTC, DatBoiTim commented
> @zeskorion they're bringing back RNG combat you might wanna take a look at this

They're fair and balanced what's wrong with that?

2021-03-30 13:56 UTC, francinum submitted a review, later dismissed
https://www.youtube.com/watch?v=Pij5aoehWUw

2021-03-30 15:27 UTC, DatBoiTim commented
![image](https://user-images.githubusercontent.com/68963748/113014733-d7428380-914a-11eb-860d-e9d022f85676.jpeg)

2021-03-30 16:13 UTC, eeSPee commented
Chances should be 5%, 2x damage.

2021-03-30 16:40 UTC, DatBoiTim commented
> Chances should be 5%, 2x damage.

Hey now don't want to get too crazy handing these critical hits with huge multipliers to random folks

2021-03-30 17:08 UTC, eeSPee commented
> > Chances should be 5%, 2x damage.
> 
> Hey now don't want to get too crazy handing these critical hits with huge multipliers to random folks

You get that on levelup after killing 3 people.

2021-03-30 17:10 UTC, DatBoiTim commented
> You get that on levelup after killing 3 people.

That's encouraging murderbone and I am actually being serious about it

2021-03-30 17:17 UTC, eeSPee commented
We have different notions of PvP.

2021-03-30 17:18 UTC, DatBoiTim commented
> We have different notions of PvP.

Listen the crust need to be random 5% is too consistent for a default value

2021-03-30 20:03 UTC, wraith-54321 commented
there is now a 10% chance that any hit from any weapon including fists will dust you

2021-03-30 20:06 UTC, zeskorion commented
> @zeskorion they're bringing back RNG combat

Ugh now im getting alerts from this i dont care much


> Chances should be 5%, 2x damage.

Have you tried not playing D&D? Also that crit mechanism isnt even 2x damage its 2x dice 



> > @zeskorion they're bringing back RNG combat you might wanna take a look at this
> 
> They're fair and balanced what's wrong with that?

Random crits add nothing to combat other than making it swingy and less reliable but i dont really care much

2021-03-30 20:08 UTC, wraith-54321 commented
but if we are being honest this is just making melee vs melee combat RNG based which is not good

2021-03-30 20:21 UTC, DatBoiTim commented
> but if we are being honest this is just making melee vs melee combat RNG based which is not good

I just haven't figured out projectiles yet

2021-03-30 20:26 UTC, ike709 commented
The mob performing the crit should automatically say some variation of "sorry for the crit bro"

2021-03-30 20:29 UTC, DatBoiTim commented
> The mob performing the crit should automatically say some variation of "sorry for the crit bro"

Genius

2021-03-31 01:13 UTC, DatBoiTim commented
Anyways I made some changes that you asked for Ike. At least in places where it was applicable.

2021-03-31 15:03 UTC, eeSPee commented
Can you add a combat rating like in Warlords Battlecry?

2021-03-31 15:05 UTC, DatBoiTim commented
> Can you add a combat rating like in Warlords Battlecry?

Elaborate. Also WYCI

2021-03-31 23:27 UTC, TheFakeElon requested changes
Just put the multiplier in `take_damage()` and the STAM, BRUTE and BURN parts of the `apply_damage()` proc.

2021-04-01 00:44 UTC, DatBoiTim commented
> e multiplier in `take_damage()` and the STAM, BRUTE and BURN parts of the `apply_damage()` proc.

Can you elaborate further so I don't fuck it up?

2021-04-01 04:20 UTC, DatBoiTim commented
Reverting to meet @TheFakeElon 's changes
Unfortunately Ike no crit announcement

2021-04-01 12:06 UTC, eeSPee commented
> > Can you add a combat rating like in Warlords Battlecry?
> 
> Elaborate. Also WYCI

The combat stat works like this:
* Each target has a combat rating, anywhere from 0 to 50.
* Maths magic determine the outcome of each attack
* There are 5 possible outcomes: Miss, Marginal Blow, Stagnant Blow, Critical Hit and Deathblow.
** Miss deals 1 damage, regardless of attacker's weapon
** Marginal Blow deals half damage
** Stagnant Blow deals regular damage
** Critical Hit deals double damage
** Deathblow deals quadruple damage, and makes you shout out a deathblow
* On top of that, Critical Hits and Deathblows cause additional effects
** Blunt weapons (toolboxes, bats) deal knockback
** Sharp weapons (knives, spears) pierce armors
** Slashing weapons (hatchets, axes) cause your character to cleave multiple targets
** Fire weapons (flares, lighters) set your targets on fire
** Electric weapons (stun batons, inducers) cause a tesla arc that stuns multiple weapons

2021-04-01 12:08 UTC, DatBoiTim commented
> > > Can you add a combat rating like in Warlords Battlecry?
> 
> > 
> 
> > Elaborate. Also WYCI
> 
> 
> 
> The combat stat works like this:
> 
> * Each target has a combat rating, anywhere from 0 to 50.
> 
> * Maths magic determine the outcome of each attack
> 
> * There are 5 possible outcomes: Miss, Marginal Blow, Stagnant Blow, Critical Hit and Deathblow.
> 
> ** Miss deals 1 damage, regardless of attacker's weapon
> 
> ** Marginal Blow deals half damage
> 
> ** Stagnant Blow deals regular damage
> 
> ** Critical Hit deals double damage
> 
> ** Deathblow deals quadruple damage, and makes you shout out a victorious scream
> 
> * On top of that, Critical Hits and Deathblows cause additional effects
> 
> ** Blunt weapons (toolboxes, bats) deal confusion
> 
> ** Sharp weapons (knives, spears) pierce armors
> 
> ** Slashing weapons (hatchets, axes) cause your character to cleave multiple targets
> 
> ** Fire weapons (flares, lighters) set your targets on fire
> 
> ** Electric weapons (stun batons, inducers) cause a tesla arc that stuns multiple weapons

Extremely WYCI

2021-04-01 12:10 UTC, eeSPee commented
> Extremely WYCI

WYCI?

2021-04-01 12:11 UTC, DatBoiTim commented
> > Extremely WYCI
> 
> 
> 
> WYCI?

When you code it

2021-04-01 12:59 UTC, eeSPee commented
Ehh.

When there's demand.

2021-04-07 17:08 UTC, TheFakeElon approved these changes
*\_|>w<|_/*

2021-04-07 17:10 UTC, DatBoiTim commented
🤠

2021-04-07 23:26 UTC, yorii commented
I like the idea, but this code is lazy, you even made crits fully ignore armor? That sounds exploitable.

2021-04-07 23:27 UTC, DatBoiTim commented
> I like the idea, but this code is lazy, you even made crits fully ignore armor? That sounds exploitable.

Unfortunately this was how maintainers asked me to make it

2021-04-07 23:29 UTC, DatBoiTim commented
There were a lot of changed I had to revert 😔

2021-04-08 12:34 UTC, yorii commented
> There were a lot of changed I had to revert 😔 to make maintainers like it

Feels bloody weird man, so this is the version they accepted?
Maintainers trying to ruin game by adding obvious exploits confirmed.

2021-04-08 12:36 UTC, DatBoiTim commented
> > There were a lot of changed I had to revert 😔 to make maintainers like it
> 
> 
> 
> Feels bloody weird man, so this is the version they accepted?
> 
> Maintainers trying to ruin game by adding obvious exploits confirmed.

Bear in mind however the damage passed through here in most cases is already reduced by armor. So it goes armor reduction -> Proc Call -> Crit check -> Crit multiplier

2021-04-08 12:42 UTC, yorii commented
> > > There were a lot of changed I had to revert 😔 to make maintainers like it
> > 
> > 
> > Feels bloody weird man, so this is the version they accepted?
> > Maintainers trying to ruin game by adding obvious exploits confirmed.
> 
> Bear in mind however the damage passed through here in most cases is already reduced by armor. So it goes armor reduction -> Proc Call -> Crit check -> Crit multiplier

Yes but from my understanding of the code, the armor reduction is just calculated and sent to the damage proc call as a variable, which the crit then doesn't use.

2021-04-08 12:51 UTC, zeskorion commented
> > > > There were a lot of changed I had to revert 😔 to make maintainers like it
> > > 
> > > 
> > > Feels bloody weird man, so this is the version they accepted?
> > > Maintainers trying to ruin game by adding obvious exploits confirmed.
> > 
> > 
> > Bear in mind however the damage passed through here in most cases is already reduced by armor. So it goes armor reduction -> Proc Call -> Crit check -> Crit multiplier
> 
> Yes but from my understanding of the code, the armor reduction is just calculated and sent to the damage proc call as a variable, which the crit then doesn't use.

Nah this is part of apply_damage() armor reduction is handled a bit later in the proc

Anyways, random crits dumb, thought you should know


And my idea for implementing it was way bettee

2021-04-08 12:57 UTC, yorii commented
So what does `damage * hit_percent` even do then?

2021-04-08 13:38 UTC, DatBoiTim commented
> So what does `damage * hit_percent` even do then?

Poorly named var.

I coded this in more or less a fever dream.

2021-04-08 17:25 UTC, yorii commented
> I coded this in more or less a fever dream.

lol :D

2021-04-09 11:54 UTC, DatBoiTim commented
> Anyways, random crits dumb, thought you should know

This is a meme PR I am completely aware

2021-04-19 05:28 UTC, TheFakeElon commented
Your <strike>meme</strike> PR is being sacrificed for the greater good of the backlog o7.

2021-04-19 05:28 UTC, closed without merging