Makes the chav trait more immersive
BeeStation/BeeStation-Hornet pull request #4010
Opened 2021-03-31 13:38 UTC by PowerfulBacon

## About The Pull Request

Chav trait increases damage of sharp objects by 30% but makes the user unable to use guns.

## Why It's Good For The Game

Improves the mechanical quality of roleplay significantly.

## Changelog
:cl:
tweak: Chav trait users can no longer use guns.
tweak: Chav trait users deal 30% more damage with sharp melee items.
/:cl:

2021-03-31 13:49 UTC, DatBoiTim commented
This PRs a bit funny innit?

2021-03-31 13:50 UTC, RDS88-beeman commented
london

2021-03-31 14:01 UTC, DatBoiTim requested changes
Needs more immersion

2021-03-31 14:01 UTC, DatBoiTim commented on code/datums/mutations/speech.dm
> +	ADD_TRAIT(owner, TRAIT_WELL_GOOD_SHANKER, BRITISH_TRAIT)
Maybe add a nicotine addiction? Gotta ave them ciggies mate.

2021-03-31 15:10 UTC, WhyIsCaeciliusTaken commented
hmm yes 45 damage DEsword

2021-03-31 15:25 UTC, PowerfulBacon commented
> 
> 
> hmm yes 45 damage DEsword

Keep in mind its a genetic trait rather than something you can get roundstart, so a traitor would have to work for it first.

2021-03-31 16:23 UTC, Lagomorphica commented
Bit quirky innit?

2021-03-31 21:33 UTC, bloons3 commented
+30% seems _really_ powerful...

2021-03-31 23:39 UTC, ivanmixo commented
> +30% seems _really_ powerful...

At the cost of no guns? I think its fine since I'd argue hulk is still a better option.

2021-04-01 00:25 UTC, Singularity69 commented
Based

2021-04-03 13:54 UTC, closed without merging