Syndicate Tome Unlocks Extra Rites At The Altar
BeeStation/BeeStation-Hornet pull request #4063
Opened 2021-04-09 15:47 UTC by eeSPee

## About The Pull Request

Allows the syndicate tome to unlock certain, malicious rites when used on Altars Of God. These rites are not free, and still cost mana (ie, altar points) to use. They are quite powerful, however. The rites are as follow:
* Candle: Allows you to summon a lesser staff of fireball for 2000 points. This staff has 4 fireball charges.
* Technophile: Allows you to launch a station wide blackout event for 2000 points.

## Why It's Good For The Game

Syndicate tome is already an underwhelming item. Maybe this will grant it additional usability and more way to see it used in game. It's powerful, but not overpowered, and requires a bit of work to obtain.

## Changelog
:cl:
add: Syndie Tome unlocks extra rites at the Altar of God
/:cl:

2021-04-09 15:49 UTC, someguyjust commented
This seems like a cool idea and give the sydicate tome a use, I like it.

2021-04-09 16:28 UTC, Archanial commented
okay but last time I've checked points were capped at 1000

2021-04-09 16:29 UTC, zeskorion commented
Fireball is an extremely powerful spell and a wand of fireball is able to kill most people in a few hits, and is far easier to aim as well. Whilst this is a good application for the syndicate tome, remember it has a low TC cost and make the rewards work accordingly

2021-04-09 16:47 UTC, eeSPee commented
> Fireball is an extremely powerful spell and a wand of fireball is able to kill most people in a few hits, and is far easier to aim as well. Whilst this is a good application for the syndicate tome, remember it has a low TC cost and make the rewards work accordingly

I will take your feedback into account, but also keep in mind the syndie tome has no other purpose other then acting like a proper bible.

Additionaly, it requires quite a bit of grind/effort to get to the rewards. It's not always guaranteed and is likely to raise suspicion (the item itself can be seen when interacting with the altar), so the tome is a quite risky, not always guarantee item.

2021-04-09 20:25 UTC, bloons3 commented
I would disagree on adding more (extremely OP) features to the chaplain's altar.

2021-04-09 20:54 UTC, Archanial requested changes
https://github.com/BeeStation/BeeStation-Hornet/blob/9270ba0faec7e636cdef4188c19a3ac4ffc6ef7d/code/modules/religion/religion_sects.dm#L24
max favor is set to 1000 and it's only overwritten in candle sect (to 10k).

2021-04-09 20:54 UTC, Archanial commented on code/modules/religion/rites.dm
> +	var/obj/item/gun/magic/wand/fireball/inert/mwand = new /obj/item/gun/magic/wand/fireball/inert(altar_turf)
```suggestion
	var/obj/item/gun/magic/wand/fireball/inert/mwand = new(altar_turf)
```

2021-04-10 00:36 UTC, JustANormalHooman commented
This is absurd honestly. I like the idea, but as others have said, the tome is cheap and the wand is insane. A chaplain sacrificing humonkeys should not suddenly get to kill 4 security members with a fireball stun.

2021-04-10 12:04 UTC, PowerfulBacon commented
Fuck the fireball staff, fireballs are a 1 hit kill

2021-04-10 13:52 UTC, Autisem commented
Id like to note examing a syndie bibles shows the name of who ever its bounded too, it bassicly marks you as valid and really has no other purpose other then maby clutch heal. So this seem fair

2021-04-10 19:13 UTC, Rukofamicom commented
> Candle: Allows you to summon a lesser staff of fireball for 2000 points. This staff has 4 fireball charges.

No. Even if this only had one charge, no. Fireball is too god damn powerful.

2021-04-13 14:24 UTC, eeSPee commented
> > Candle: Allows you to summon a lesser staff of fireball for 2000 points. This staff has 4 fireball charges.
> 
> No. Even if this only had one charge, no. Fireball is too god damn powerful.

I'm thinking, now that staff of lava was removed from the Miner Item Pool...

2021-04-13 17:13 UTC, zeskorion commented
> > > Candle: Allows you to summon a lesser staff of fireball for 2000 points. This staff has 4 fireball charges.
> > 
> > 
> > No. Even if this only had one charge, no. Fireball is too god damn powerful.
> 
> I'm thinking, now that staff of lava was removed from the Miner Item Pool...

NO. that is even WORSE than fireball

2021-04-16 14:04 UTC, eeSPee commented
> > > > Candle: Allows you to summon a lesser staff of fireball for 2000 points. This staff has 4 fireball charges.
> > > 
> > > 
> > > No. Even if this only had one charge, no. Fireball is too god damn powerful.
> > 
> > 
> > I'm thinking, now that staff of lava was removed from the Miner Item Pool...
> 
> NO. that is even WORSE than fireball

I'll settle for hellwater then.

2021-04-20 15:56 UTC, eeSPee commented
Alright; ironed out some quirks and now code should allow for 'corrupted rites', only accessible with the syndie tome.

2021-04-20 18:00 UTC, bloons3 commented
I don't really see how giving someone hellwater for hitting their sect altar with a syndicate bible encourages roleplay and gives the Chaplain a useful **gimmick**.

2021-04-20 20:41 UTC, eeSPee commented
> I don't really see how giving someone hellwater for hitting their sect altar with a syndicate bible encourages roleplay and gives the Chaplain a useful **gimmick**.

You can drink the hellwater and stay on fire for a really long time.

2021-04-26 02:18 UTC, TheFakeElon commented on code/datums/components/religious_tool.dm
> +	if((operation_flags & RELIGION_TOOL_INVOKE))
```suggestion
	if(operation_flags & RELIGION_TOOL_INVOKE)
```

2021-04-26 02:18 UTC, TheFakeElon commented on code/datums/components/religious_tool.dm
> +				if (trite[1] != "!" || synditome_check)
Blehh

2021-04-26 02:18 UTC, TheFakeElon commented on code/datums/components/religious_tool.dm
> +				if (trite[1] != "!" || synditome_check)
```suggestion
		var/synditome_check = istype(the_item, /obj/item/storage/book/bible/syndicate)
		if(synditome_check || (istype(the_item, catalyst_type)))
			var/list/rite_list = list()
			for(var/trite in easy_access_sect.rites_list)
				if (trite[1] != "!" || synditome_check)
```

2021-04-26 02:18 UTC, TheFakeElon commented on code/datums/components/religious_tool.dm
> +				if (trite[1] != "!" || synditome_check)
This could probably be improved by removing the double synditome check but _eh_

2021-04-26 20:18 UTC, eeSPee commented on code/datums/components/religious_tool.dm
> +	if((operation_flags & RELIGION_TOOL_INVOKE))
oops

2021-05-20 03:45 UTC, TheFakeElon reviewed
should be good after this

2021-05-20 03:45 UTC, TheFakeElon commented on code/datums/components/religious_tool.dm
> +			if(LAZYLEN(rite_list)==0)
```suggestion
			if(!LAZYLEN(rite_list))
```

2021-05-20 03:45 UTC, TheFakeElon commented on code/datums/components/religious_tool.dm
> +			return .
```suggestion
			return
```
`.` is the return value by default

2021-05-20 03:45 UTC, TheFakeElon commented on code/datums/components/religious_tool.dm
> +				return .
```suggestion
				return
```

2021-05-20 03:45 UTC, TheFakeElon commented on code/datums/components/religious_tool.dm
> +				return .
```suggestion
				return
```

2021-06-01 02:49 UTC, closed without merging