Corgium 'polymorphs' people into corgis
BeeStation/BeeStation-Hornet pull request #4128
Opened 2021-04-22 15:40 UTC by eeSPee

## About The Pull Request

Corgium now uses the shapeshift data to store creatures, similarly on how the shapeshifting spells works.

Also the damage transferred to the mob is now stamina damage, so corgium is no longer lethal.

## Why It's Good For The Game

Corgium was never meant to be more than a meme reagent. It shouldn't be a death weapon.

## Changelog
:cl:
tweak: Corgium shapeshifts people into corgis now. The damage taken in corgi form is now carried over as stamina.
/:cl:

2021-04-23 17:32 UTC, PowerfulBacon commented
> Also the damage transferred to the mob is now stamina damage

![image](https://user-images.githubusercontent.com/26465327/115908602-48cbd400-a462-11eb-98db-2093b9b8680c.png)

2021-04-23 18:11 UTC, eeSPee commented
> > Also the damage transferred to the mob is now stamina damage
> 
> ![image](https://user-images.githubusercontent.com/26465327/115908602-48cbd400-a462-11eb-98db-2093b9b8680c.png)

I was thinking of removing the damage entirely, so people can't abuse it as a one-hit chem.

2021-04-28 16:20 UTC, PowerfulBacon requested changes
Have it transfer to brute so you cant drink corgium and gain temporary immortality to environmental hazards. (Become corgi, die, become corgi again, die, become corgi again and repeat)

2021-04-28 22:48 UTC, eeSPee commented
The whole reason this PR exist is so that people can't corgi someone, and then kill them in one laser shot.

> Have it transfer to brute so you cant drink corgium and gain temporary immortality to environmental hazards. (Become corgi, die, become corgi again, die, become corgi again and repeat)

You'd still take damage when you're not a corgi though.

2021-05-01 08:31 UTC, PowerfulBacon commented
> 
> 
> The whole reason this PR exist is so that people can't corgi someone, and then kill them in one laser shot.
> 
> > Have it transfer to brute so you cant drink corgium and gain temporary immortality to environmental hazards. (Become corgi, die, become corgi again, die, become corgi again and repeat)
> 
> You'd still take damage when you're not a corgi though.

But you would instantly turn back into a corgi again

2021-05-02 14:42 UTC, DatBoiTim commented
Maybe a solution would be to have the chem completely delete once the corgi transformation happens.

2021-05-02 22:34 UTC, eeSPee commented
Polymorphs on overdose and you can overdose only once.

2021-05-02 22:41 UTC, DatBoiTim commented
> Polymorphs on overdose and you can overdose only once.

What's the OD threshold?

2021-05-02 22:45 UTC, eeSPee commented
> What's the OD threshold?

25

2021-05-21 14:10 UTC, eeSPee commented
Should I fix those? Or close the PR?

2021-05-27 01:35 UTC, closed without merging