Prevents Midrounds From Spawning After Shuttlecall
BeeStation/BeeStation-Hornet pull request #4134
Opened 2021-04-23 18:10 UTC by eeSPee

## About The Pull Request

Prevents certain events from spawning after shuttle has been called.

## Why It's Good For The Game

It's not fun when you're midround alien/abductor/pirate and you have less than 10 minutes to do your thing.

## Changelog
:cl:
tweak: Prevents midround antags from spawning after shuttle has been called.
/:cl:

2021-04-24 10:26 UTC, PowerfulBacon requested changes, later dismissed

2021-04-24 10:26 UTC, PowerfulBacon commented on code/modules/events/_event.dm
> +	var/can_spawn_after_shuttlecall = FALSE	// Prevents the event from spawning after the shuttle was called
Why is the name of the variable the literal opposite of what it does. This doesn't allow them to spawn after shuttlecall, this prevents them from spawning after shuttle call if true.

2021-04-24 10:26 UTC, PowerfulBacon commented on code/modules/events/blob.dm
> +	can_spawn_after_shuttlecall = TRUE
Blob delays shuttle anyway

2021-04-24 23:08 UTC, Sinestia commented
I'm gonna powergame this by keeping the shuttle called as much as possible /s


Aliens delay the shuttle too if they get an empress/queen up in time, it might be worth allowing them to spawn too. 

Up to you though, probably isn't as warranted as it is with blob

2021-04-26 03:35 UTC, OceanFish1 commented
Go on green alert, call shuttle, recall in 9 minutes, repeat,????, no more midround antags

2021-04-26 03:59 UTC, wraith-54321 commented
there is a thing if you keep calling and recalling it forces an un-recallable shuttle call, so I dont think that would end up happening unless people knew about this but not that

2021-04-26 04:04 UTC, Sinestia commented
It doesn't really matter

 If you do that it's the easiest thing to ban for + apparently there actually are safeguards to ping pong as mentioned if you go hard enough.   

 Usually I'm more along the lines of "jannies suck and its best thing things are addressed by code" but this is sooooo blatant if you actually are dumb enough to do it.

2021-04-26 06:02 UTC, ike709 commented
inb4 people spam the shuttle to reduce antags

2021-04-26 11:35 UTC, PowerfulBacon commented
> 
> 
> inb4 people spam the shuttle to reduce antags

I mean that's likely not going to be a huge issue and is pretty obvious for admins to deal with, you could literally go to their spawn points and wall them off if you wanted to meta that hard.

2021-04-26 15:23 UTC, ike709 approved these changes

2021-04-26 15:46 UTC, eeSPee commented
> > inb4 people spam the shuttle to reduce antags
> 
> I mean that's likely not going to be a huge issue and is pretty obvious for admins to deal with, you could literally go to their spawn points and wall them off if you wanted to meta that hard.

Assistant McAssistantson walling off gateway and welding off all vents outside main hallways :S

2021-04-28 16:21 UTC, merged