Fax Machine
BeeStation/BeeStation-Hornet pull request #4211
Opened 2021-05-03 16:53 UTC by cerebrallolzy

## About The Pull Request
Adds a fax machine for the bridge and Lawyer's Office.

## Why It's Good For The Game
Imagine that you're the lawyer, and you notice HoS jails someone and follows out an execution that the Captain didn't give permission for. This will give the lawyer the ability to get the HoS punished/fired. 

Essentially, this gives the Lawyer an opportunity to actually do their job.

## Changelog
:cl:
add: fax machine
soundadd: fax sound
imageadd: fax machine icons
spellcheck: fixed a few typos
admin: admin tools for faxes
/:cl:

2021-05-03 17:06 UTC, PowerfulBacon commented
kind of just an IC ahelp machine.

2021-05-03 17:13 UTC, cerebrallolzy commented
> 
> 
> kind of just an IC ahelp machine.

It's mostly for Sage... it's kinda weird praying for an admeme to fire the HoS.

2021-05-03 17:24 UTC, OceanFish1 commented
*nervously typing in fax* I saw captain erping in dorms pls demote he i was muted from aehlp

2021-05-03 19:46 UTC, Archanial commented on code/modules/admin/topic.dm
> +		if(!check_rights(R_ADMIN))
Since smiting is fun, I think this should be fun too.

2021-05-03 19:46 UTC, Archanial commented on code/modules/admin/topic.dm
> +		var/mob/living/carbon/human/H = locate(href_list["FaxReplyTemplate"]) in GLOB.mob_list
I'm pretty sure there is global list of players

2021-05-03 19:46 UTC, Archanial commented on .gitignore
> +config/dbconfig.txt
It's not intentional, is it?

2021-05-03 19:46 UTC, Archanial commented on code/__DEFINES/say.dm
> +#define MAX_PAPER_FIELDS 50
Use the defines located in paper.dm or move them all here

2021-05-03 19:46 UTC, Archanial commented on code/modules/admin/topic.dm
> +		var/obj/item/paper/P = new /obj/item/paper(null)
```suggestion
		var/obj/item/paper/P = new /obj/item/paper()
```

2021-05-03 19:46 UTC, Archanial commented on code/modules/admin/topic.dm
> +			tmsg += "Greetings, esteemed crewmember. Your fax has been received successfully by NAS Trurl Fax Registration.<BR><BR>We at the NAS Trurl appreciate the good work that you have done here, and sin
use switch instead

2021-05-03 19:46 UTC, Archanial commented on code/modules/admin/topic.dm
> +			P.stamped = list()
I'm not entirely sure what you mean by this code. You initilize stamped but then check if it's still null?

2021-05-03 19:46 UTC, Archanial commented on code/modules/admin/topic.dm
> +		if(istype(H) && H.stat == CONSCIOUS && (istype(H.ears, /obj/item/radio/headset)))
You also need to check if owner is not deaf and if headset is functioning

2021-05-03 19:46 UTC, Archanial commented on code/modules/admin/topic.dm
> +		var/obj/item/paper/P = new /obj/item/paper(null)
```suggestion
		var/obj/item/paper/P = new /obj/item/paper()
```

2021-05-03 19:46 UTC, Archanial commented on code/modules/paperwork/fax.dm
> +	var/sent_at = null
```suggestion
	var/from_department
	var/to_department
	var/origin
	var/message
	var/sent_by
	var/sent_at
```

2021-05-03 19:46 UTC, Archanial commented on code/modules/paperwork/faxmachine.dm
> +	var/obj/item/card/id/scan = null
```suggestion
	var/obj/item/card/id/scan
```

2021-05-03 19:46 UTC, Archanial commented on code/modules/paperwork/faxmachine.dm
> +	var/emagged = FALSE
Use emaged flag instead

2021-05-03 19:46 UTC, Archanial commented on code/modules/paperwork/faxmachine.dm
> +		return TRUE
```suggestion
	if(authenticated || user.has_unlimited_silicon_privilege)
		return TRUE
```

2021-05-03 20:03 UTC, ike709 commented
I haven't looked at this but if this is a straight port with no code improvements then I'll tell you now that it won't be merged.

2021-05-03 21:19 UTC, francinum requested changes
This code is overall really, really just, *weird*

The fax reply system looks incredibly painful to use, being just a series of `alert()s`, This probably justifies it's own specialized panel.

2021-05-03 21:19 UTC, francinum commented on code/__HELPERS/text.dm
> +/proc/pencode_to_html(text, mob/user, obj/item/pen/P = null, format = 1, sign = 1, fields = 1, deffont = PEN_FONT, signfont = SIGNFONT, crayonfont = CRAYON_FONT, no_font = FALSE)
We use markdown for paper handling.

2021-05-03 21:19 UTC, francinum commented on .gitignore
> +config/dbconfig.txt
This is bad, Don't do this.

2021-05-05 08:53 UTC, eLeCtrOssSnake commented
Cool addition, though please do not limit it only for sage.

2021-05-21 03:28 UTC, ike709 requested changes
This code is just... Not good. It needs a pretty hefty rewrite.

2021-05-23 01:03 UTC, cerebrallolzy commented
Will rewrite and open another PR

2021-05-23 01:03 UTC, closed without merging

2021-08-13 12:11 UTC, AnCopper commented
> Will rewrite and open another PR

Famous last words.