CBT from /tg/
BeeStation/BeeStation-Hornet pull request #4219
Opened 2021-05-04 03:34 UTC by Sinestia

## About The Pull Request

ports https://github.com/tgstation/tgstation/pull/55373
ports https://github.com/tgstation/tgstation/pull/54567 too

**This is in draft because while it runs locally, I haven't touched any tasks, and don't know much about TGS, I'd have to experiment with that locally/get help. I'm also going to throw in the other CBT PRs (not tgui 4.3 though.)** 

 Tl;dr, tgui will no longer be bundled and will be compiled locally. 
 Pointing DreamMaker at a .dme will no longer work. 

 You will compile using either:
**Ctrl+Shift+B** in vscode (or F5 to run with a debugger as usual.)
 `./tools/build/build` from Repo root on Linux.
`Build.bat` on root on Windows. Click it monkey. 

## Why It's Good For The Game

No unnecessary merge conflicts with tgui PRs. 

## Changelog
:cl: Stylemistake, Cyberboss, SpaceManiac
code: TGUI now uses Common Build Tooling, CBT. 
server: TGS will require adaptation. 
/:cl:

2021-05-04 04:03 UTC, ike709 commented
There's definitely more follow-up PRs.

2021-05-04 04:03 UTC, Sinestia commented
oh. Fixing git tasks was that easy

2021-05-04 04:04 UTC, Sinestia commented
> There's definitely more follow-up PRs.

Yep, will get on it.

2021-05-04 04:18 UTC, ike709 commented
If there's CBT changes in the 4.3 PR then get those but otherwise yes you can ignore 4.3.

2021-05-04 04:25 UTC, Sinestia commented
> If there's CBT changes in the 4.3 PR then get those but otherwise yes you can ignore 4.3.

Seems like there's some important stuff in there, will have to get them then

2021-05-06 04:25 UTC, ike709 commented
https://github.com/BeeStation/BeeStation-Hornet/pull/4220

2021-05-11 08:54 UTC, Sinestia commented
Was just gonna do the whole thing because that other PR had no documentation of what it actually ported but it's being reviewed so I guess I'll just not. 


 I think it's still bizarre since tg does these changes together (hence the CI screaming despite having the same change that "triggered it" lol) but w.e

2021-05-11 20:48 UTC, Sinestia commented
![image](https://user-images.githubusercontent.com/40812746/117882805-4fcf5080-b270-11eb-970e-8feed870abb9.png)
Even modfab works as it used to 👌🏻

2021-05-11 20:48 UTC, Archanial commented
epic :+1:

2021-05-11 20:54 UTC, ike709 commented
Does paper work? If this includes fully functional tgui 4.3 I'll go with this PR over the other one.

2021-05-11 20:58 UTC, Sinestia commented
> Does paper work? If this includes fully functional tgui 4.3 I'll go with this PR over the other one.

Can't see anything obviously wrong about paper. 
![image](https://user-images.githubusercontent.com/40812746/117883970-b3a64900-b271-11eb-8f6c-0bfb0ead66fc.png)

2021-05-11 21:18 UTC, Sinestia commented on .github/workflows/extra_pr_labels.yml
> +        uses: eps1lon/actions-label-merge-conflict@513a24fc7dca40990863be2935e059e650728400
I couldn't figure out why, but bumping the version was necessary and there were no newer releases to use. TG was using a wholly different script.

2021-05-12 00:52 UTC, ike709 commented
Have you tested this locally? TGS refuses to testmerge this saying that it causes an error in DreamMaker.

2021-05-12 11:08 UTC, Sinestia commented
> Have you tested this locally? TGS refuses to testmerge this saying that it causes an error in DreamMaker.

Yep, tested it locally quite a bit on both windows and linux to make sure everything works fine and tguis work right.


It might not just work with TGS without other changes, to be frank I've never used TGS so I might have neglected a necessary change to make it work. 

 I'll probably have to DL it to see what I've gotta do.

2021-05-12 17:20 UTC, Sinestia commented
![image](https://user-images.githubusercontent.com/40812746/118014189-8a8cc380-b318-11eb-9cee-60689c4729c5.png)

Alright, to get it to work you must add PreCompile.bat to your EventScripts in TGS
(or PreCompile.sh for Linux.)

 The .yml should do it automatically for newly created instances.

2021-05-13 02:55 UTC, Crossedfall requested changes
Can't dig into it further right now, but the dockerfile will not build. Issue seems to be related to nodejs.

```
 => ERROR [build 4/4] RUN env TG_BOOTSTRAP_NODE_LINUX=1 tools/build/build     && tools/deploy.sh /deploy  && rm /  0.6s
------
 > [build 4/4] RUN env TG_BOOTSTRAP_NODE_LINUX=1 tools/build/build     && tools/deploy.sh /deploy       && rm /deploy/*.dll:
#15 0.500 realpath: ../bootstrap/.cache/node-v12.20.0.tar.gz: No such file or directory
------
executor failed running [/bin/sh -c env TG_BOOTSTRAP_NODE_LINUX=1 tools/build/build     && tools/deploy.sh /deploy     && rm /deploy/*.dll]: exit code: 1
```

2021-05-14 14:59 UTC, Sinestia commented
Curious, node seems fine, the exit code I got is for it not being able to locate the file meaning the paths are probably screwed up.

2021-05-19 07:43 UTC, ike709 commented on .vscode/tasks.json
> +			"dme": "tgstation.dme",
🤔

2021-05-19 07:44 UTC, ike709 commented
After checking this out locally and attempting to compile, it errors with `command 'dreammaker.reparse' not found`.

2021-05-20 06:36 UTC, Sinestia commented
> 
> 
> After checking this out locally and attempting to compile, it errors with `command 'dreammaker.reparse' not found`.

I can't replicate this, I'm on a fresh install too.

2021-05-21 09:46 UTC, Sinestia commented
Right, back to my setup, gonna try to resolve the docker situation

2021-05-23 08:51 UTC, AffectedArc07 commented
You dont want to do this

The amount of comments I have seen in coderbus about this shit being broken and people whining that they cant easily build, not to mention CBT builds end up taking longer for people (I have no idea why, maybe from running a subprocesses out of node), but this is a step in the wrong direction. 

You have to remember that not everyone who downloads the code is a coder, and some people just want it for local test servers. These people just press the dme thats called `beestation` and manually do the build inside the DM "IDE". They dont want to have to be installing extra shit, or worse, having extra shit installed on their PC without them even realising.

2021-05-23 13:59 UTC, Sinestia commented
Docker functions. Safe to say I admittedly am clueless with docker and it was much easier to just change the old one mostly ignoring tg changes due to extools.... not playing well even when I made it compile itself.

2021-05-24 01:49 UTC, ike709 commented
Maintainers are currently considering if we want to use CBT or not, given the mixed opinions in coderbus.

2021-05-24 03:26 UTC, MCterra10 commented
The tgui upgrade is great, but I heavily disagree with forcing every coder who doesn't give a shit about tgui and doesn't work with it to install the tumour that is node on their system to be able to compile the game

2021-05-24 05:05 UTC, Sinestia commented
NodeJS is soy software, though you don't really install it. 

It just keeps a local dir of it, it's a cyst, not a tumor.

2021-05-31 22:41 UTC, ike709 commented
The maintainers and downstream have decided that we don't want the overhead introduced by CBT. I'm willing to leave this PR open for the general TGUI improvements/updates if you remove the CBT part.

2021-05-31 22:42 UTC, ike709 commented
The topic will be revisited once Juke Build has matured.

2021-06-03 23:04 UTC, Sinestia commented
CBT will be removed, other modernizations will remain

2021-06-04 00:04 UTC, ike709 commented
The arguments have been had, CBT isn't happening.

2021-06-11 02:15 UTC, Sinestia commented
git will hate this not done yet but finally started getting around to it

2021-06-15 00:29 UTC, jupyterkat commented
Code and Build Torture

2021-06-17 09:22 UTC, Sinestia commented
Threw in one more to make reviewing easier

https://github.com/tgstation/tgstation/pull/56727/

should be ready 2 be looked at again, and might definitely wanna TM lol.

2021-06-26 00:40 UTC, lordScrubling commented
tell me this includes the tall ass atmos chamber monitoring consoles

2021-06-28 02:10 UTC, Sinestia commented
> 
> 
> tell me this includes the tall ass atmos chamber monitoring consoles

 You can think of this as being solely about the tgui backend

not any specific interfaces were changed beyond updating them

2021-06-28 02:12 UTC, merged

2021-06-28 02:17 UTC, MCterra10 commented
Yolomerged

2021-06-28 02:18 UTC, MCterra10 commented
Yolo

2021-06-28 03:08 UTC, ike709 commented
It was testmerged on sage.

2021-06-28 12:24 UTC, jupyterkat commented
ci checks fails on tgui regardless if the build is correct or not

2021-06-28 12:37 UTC, lordScrubling commented
> 
> 
> ci checks fails on tgui regardless if the build is correct or not

https://github.com/BeeStation/BeeStation-Hornet/pull/4606
no it's somehow possible, not sure how i got it

2021-06-28 12:47 UTC, Sinestia commented
> 
> 
> ci checks fails on tgui regardless if the build is correct or not

Your cache is bad

run git clean -xdf on your tgui folder

happened to me too