Adds Old insuls and Old gas mask among assistant heirlooms
BeeStation/BeeStation-Hornet pull request #4258
Opened 2021-05-07 12:24 UTC by eeSPee

## About The Pull Request

Adds worn down insuls and old gas mask among assistant heirlooms.

## Why It's Good For The Game

Gotta nail that classic assistant look!

## Changelog
:cl:
add: Worn down insuls and old gas mask among assistant heirlooms
/:cl:

2021-05-07 12:24 UTC, ToasterBan commented
aren't those roundstart insuls?

2021-05-07 12:36 UTC, Sinestia commented
> aren't those roundstart insuls?

They're basically budget insulated gloves but a lot better

3/7 chance of just being insuls
3/7 chance to be half protection
and 1/7 chance to be 25% protection.

2021-05-07 12:39 UTC, ivanmixo commented
Potentially having roundstart insuls is bad. Family heirloom is already problematic as a trait, this just makes it worse.

2021-05-07 12:44 UTC, Sinestia commented
Also https://github.com/BeeStation/BeeStation-Hornet/pull/4255


Old gas mask isn't bad

2021-05-07 12:53 UTC, Archanial commented on code/datums/traits/negative.dm
> +				heirloom_type = pick(/obj/item/storage/toolbox/mechanical/old/heirloom,/obj/item/clothing/mask/gas/old,/obj/item/clothing/gloves/color/fyellow/old)
```suggestion
				heirloom_type = pick(/obj/item/storage/toolbox/mechanical/old/heirloom, /obj/item/clothing/mask/gas/old, /obj/item/clothing/gloves/color/fyellow/old)
```

2021-05-07 16:30 UTC, bloons3 commented
So you see, _fingerless_ insulated gloves are legitimately useless and only cosmetic.

The gloves you want to add, are not. Please do not give assistants roundstart insulated gloves.

2021-05-07 20:59 UTC, ike709 commented
No roundstart insuls.

2021-05-07 21:47 UTC, eeSPee commented
> So you see, _fingerless_ insulated gloves are legitimately useless and only cosmetic.
> 
> The gloves you want to add, are not. Please do not give assistants roundstart insulated gloves.

Ok got that.

2021-05-10 16:48 UTC, qwertyquerty requested changes
No roundstart insuls

2021-05-11 11:10 UTC, eeSPee commented
Aite done.

2021-05-11 18:40 UTC, bloons3 commented
Bit concerned that giving assistants gas masks roundstart will encourage them to look like greytiders all round long.

Heirloom items shouldn't be _useful_, since carrying them around is meant to be annoying to balance the point they give you.

2021-05-11 18:51 UTC, ike709 commented
No roundstart gasmask.

2021-05-11 22:07 UTC, Sinestia commented
> Bit concerned that giving assistants gas masks roundstart will encourage them to look like greytiders all round long.
> 
> Heirloom items shouldn't be _useful_, since carrying them around is meant to be annoying to balance the point they give you.

You aren't necessarily wrong but there is quite a disparity

2021-05-19 13:32 UTC, eeSPee commented
Not a good idea.

2021-05-19 13:32 UTC, closed without merging