[WIP] paramedic hardsuit, office and access (sprites needed)
BeeStation/BeeStation-Hornet pull request #4266
Opened 2021-05-09 11:48 UTC by bluezorua

## About The Pull Request

todo:
[]paramed hardsuit
[]paramed office that contains said hardsuit
[]and paramed access number so only paramed/cmo has access to it
[]gives paramed and cmo paramed access

## Why It's Good For The Game

paramed RN is just a slightly inferior doctor so adding this will spice them up a bit+ makes recovering dead bodies from space easier, also hardsuits are cool

## Changelog
:cl:
add: paramedic office! parameds own spiecal place over all currently avaliable maps!
add: paramedic hardsuit! a hardsuit for paramedic duties!
add: paramedic access code! this is so only parameds and the cmo can access the paramed office
/:cl:

2021-05-09 12:10 UTC, bluezorua commented
GOD DAMNIT STOP BREAKING

2021-05-09 15:38 UTC, bluezorua commented
now I just need to get a spriter to do the sprites and map this stuff up

2021-05-09 16:50 UTC, Archanial commented
Giving parameds hardsuits is a bad idea. Just ask someone to open EVA and I'm pretty sure CMO has access to it.

2021-05-09 17:03 UTC, bluezorua commented
> Giving parameds hardsuits is a bad idea. Just ask someone to open EVA and I'm pretty sure CMO has access to it.

parameds have Eva access, this is meant to be a superior alternative to EVAs

2021-05-09 19:45 UTC, Sinestia requested changes

2021-05-09 19:45 UTC, Sinestia commented on code/modules/clothing/spacesuits/hardsuit.dm
> +obj/item/clothing/suit/space/hardsuit/medical/emt
he do be gooncoding tho

2021-05-09 22:30 UTC, Archanial commented on code/modules/clothing/spacesuits/hardsuit.dm
> +obj/item/clothing/suit/space/hardsuit/medical/emt
```suggestion
/obj/item/clothing/suit/space/hardsuit/medical/emt
```
:weary:

2021-06-14 19:53 UTC, ike709 commented
Stale

2021-06-14 19:53 UTC, closed without merging