Ports rebindable movement keys from /tg/
BeeStation/BeeStation-Hornet pull request #4296
Opened 2021-05-13 10:49 UTC by super12pl

## About The Pull Request
Ports https://github.com/tgstation/tgstation/pull/47626
Adds ability to rebind default movement keys (WSAD) in game preferences.

I am not sure about quality of the port but hey it works.

## Why It's Good For The Game
Makes the game *actually playable* for people with non-qwerty keyboards, fixes #3633, also more editable hotkeys good.

## Changelog
:cl:
add: Rebindable movement keys
/:cl:

2021-05-14 16:37 UTC, TheFakeElon commented on code/modules/client/client_procs.dm
> +	if(prefs && prefs.key_bindings)
```suggestion
	if(prefs?.key_bindings)
```

2021-05-21 06:17 UTC, francinum commented
Testmerged for RID 29867, resulted in nonfunctional movement keys.

2021-05-21 06:17 UTC, francinum requested changes
Nonfunctional upon testmerge.

No relevant runtimes.

2021-05-21 06:28 UTC, francinum commented
Additional aside to the review:

* Set sane default hotkeys **and force them with a savefile version burn**
* Arrowkeys *MUST* always be valid movement keys.

2021-06-02 14:33 UTC, super12pl commented
¯\_(ツ)_/¯

2021-06-02 14:33 UTC, closed without merging