Circuit logging slight expansion
BeeStation/BeeStation-Hornet pull request #4307
Opened 2021-05-15 15:51 UTC by cheesePizza2

## About The Pull Request

When plopping a battery into an assembly, it logs the player, the battery, and the assembly into the GAME log file.

## Why It's Good For The Game

better logging. since batteries are what "activate" assemblies, the person who put the battery in is the person who actually activated a circuit, not the guy who printed the assembly.

## Changelog
:cl:
admin: circuit's log when a battery is put in
/:cl:

2021-05-19 01:41 UTC, cheesePizza2 commented
you're such a sussy baka

2021-05-21 03:41 UTC, ike709 requested changes
Don't bloat the game log, use `investigate_log()` with `INVESTIGATE_CIRCUIT`.

2021-05-21 10:45 UTC, cheesePizza2 commented
ah alright i'll do that soon

2021-05-21 12:14 UTC, cheesePizza2 commented
fixed

2021-05-21 13:32 UTC, ike709 commented on code/modules/integrated_electronics/core/assemblies.dm
> +		investigate_log("[user] has slotted [I] into [src].", INVESTIGATE_CIRCUIT)
```suggestion
		investigate_log("[key_name(user)] has slotted [I] into [src].", INVESTIGATE_CIRCUIT)
```

2021-05-21 21:31 UTC, ike709 approved these changes

2021-05-23 01:08 UTC, cheesePizza2 commented
so uh, now that it's approved, is it gonna get merged?

2021-05-23 01:41 UTC, merged