fixes the jumpsuit code made by some idiot
BeeStation/BeeStation-Hornet pull request #4348
Opened 2021-05-20 00:56 UTC by someguyjust

## About The Pull Request
fixes code not actually uncovering the chest area when it should of, and this was fucking done by moving code related to jumpsuits to Under.dm, instead of Clothing.dm, i dont know why this fixes it but it does, why it wasn't put there to be with i am more confused about.

## Why It's Good For The Game
this is intended, but the dumbass didn't put it under the jumpsuit code

## Changelog
:cl:Shotgun.boom#2723
fix: jumpsuits actually uncovers the chest
code: moved jumpsuit code from clothing.dm to under.dm
/:cl:

2021-05-20 01:27 UTC, someguyjust commented
what the fuck what is conflicting

2021-05-20 02:55 UTC, Crossedfall commented
> what the fuck what is conflicting

![image](https://user-images.githubusercontent.com/26130695/118912179-fceb3e00-b8ec-11eb-96db-050aeabfc0b4.png)

2021-05-20 06:56 UTC, Archanial commented on code/modules/clothing/under/_under.dm
> +	if(src.has_sensor == LOCKED_SENSORS)
```suggestion
	if(has_sensor == LOCKED_SENSORS)
```

2021-05-20 06:56 UTC, Archanial commented on code/modules/clothing/under/_under.dm
> +		return 0
```suggestion
		return FALSE
```

2021-05-20 06:56 UTC, Archanial commented on code/modules/clothing/under/_under.dm
> +	if(src.has_sensor == BROKEN_SENSORS)
```suggestion
	if(has_sensor == BROKEN_SENSORS)
```

2021-05-20 06:56 UTC, Archanial commented on code/modules/clothing/under/_under.dm
> +		return 0
```suggestion
		return FALSE
```

2021-05-20 06:56 UTC, Archanial commented on code/modules/clothing/under/_under.dm
> +	if(src.has_sensor <= NO_SENSORS)
```suggestion
	if(has_sensor <= NO_SENSORS)
```

2021-05-20 06:56 UTC, Archanial commented on code/modules/clothing/under/_under.dm
> +		return 0
```suggestion
		return FALSE
```

2021-05-20 06:56 UTC, Archanial commented on code/modules/clothing/under/_under.dm
> +	var/list/modes = list("Off", "Binary vitals", "Exact vitals", "Tracking beacon")
```suggestion
	var/list/modes = list("Off", "Binary vitals", "Exact vitals", "Tracking beacon")
```
this probably could be static

2021-05-20 09:34 UTC, Cenrus commented
It is conflicting because the branch hasn't been updated to include the suit sensor changes on master

2021-05-20 14:48 UTC, PowerfulBacon requested changes
There is a bigger underlying issue here if moving the proc from 1 file to another 'fixes' the issue.
Since no code is changed and you literally just moved the proc from 1 file to another then either 1 of 2 things is happening:
 - Clothing.dm isn't being loaded from the beestation.dme
 - There is an override for verb/toggle() that breaks clothing.dm

If the second is the case, then rather than moving the verb, the second verb/toggle needs to be removed.

2021-05-20 16:39 UTC, someguyjust commented
> There is a bigger underlying issue here if moving the proc from 1 file to another 'fixes' the issue.
> Since no code is changed and you literally just moved the proc from 1 file to another then either 1 of 2 things is happening:
>  - Clothing.dm isn't being loaded from the beestation.dme
>  - There is an override for verb/toggle() that breaks clothing.dm
> 
> If the second is the case, then rather than moving the verb, the second verb/toggle needs to be removed.
> 
> > this is intended, but the dumbass didn't put it under the jumpsuit code
> 
> Byond handles procs by looking at their typepath not their item.
> That means that the proc
> /a/b/proc/c()
> will apply to the datum /a/b, no matter what file it is placed in.
> Code lines can be placed in completely random files and will still work fine, and multiple different datums can be inside 1 file.
> The only thing the file that code is in should affect is the order in which it is loaded.
> For example:
> 
> "code/a.dm"
> /obj/item/apple/proc/eat()
>    world.log << "consumed"
> 
> "code/b.dm"
> /obj/item/apple/proc/eat()
>    world.log << "dead" 

> 
> (Not sure on the order)
> B will be loaded after A. Despite being in different files the typepath for the proc is the same, meaning it is both being added to /obj/item/apple. Since B.dm is loaded after A.dm, the proc in A.dm is overridden by the proc in B.dm meaning that when eat() is called on the apple, "dead" will be printed to the world log rather than consumed.
> 

I don't know What happening with the code or why it worked, I am just a clueless as when I started to fix this, I simply looked at tgs code and found clothing.dm did not have jumpsuit shit in the same file, and found it in under.dm I tried to figure out why it worked there, I finally tried moving the code to the same spot as tgs and it works .

2021-05-20 17:16 UTC, PowerfulBacon commented
It probably worked because you are working on an outdated branch.

2021-05-21 03:45 UTC, ike709 commented
At this point you need to update your master branch, make a new branch, and try this PR again.

2021-05-21 03:45 UTC, closed without merging