Moves all resarched weapons to a seperate armory protolathe.
BeeStation/BeeStation-Hornet pull request #4424
Opened 2021-05-31 17:10 UTC by Fresh341

## About The Pull Request
Moves all weapons unlocked via weapon technologies to a seperate protolathe in the armory.

## Why It's Good For The Game
This allows the warden to control who gets advanced weapons and who doesn't. 
I never liked how you could deny a bloodthirsty security officer a weapon and they would just wait a bit and then print an even better one from the security protolathe, to which even the detective has access to. Having security officers walking around with marksman beam rifles on a greenshift is not fun for anyone. This doesn't remove that possibility, just allows you to blame it on the warden in that case.

This does NOT affect any other equipment besides the weapons. Telescopic Shields etc. are still avaible from the normal security protolathe. Firing pins are avaible from both lathes as a QOL.
Ammunition will still be avaible from the normal security protolathe. Its just that the guns itself can now only be printed in the armory.
This does also NOT affect mech weapons. They are still avaible from the normal security lathe.

I added a lathe to all five maps. (Box,Meta,Delta,Pubby and Corg) I tried to keep the changes as minimal as possible but if someone has a problem with it please let me know.

This is my first pr ever, so bear with me if i fucked things up. I tested all the changes though and it seemed to work fine.

## Changelog
:cl:
add: Added a new departement called "armory"
add: Added a new departemental protolathe to the armory departement
add: Added the armory protolathe board to the HOS locker.
add: Added all firing pins to the armory protolathe
balance: Moved tesla revolver, advanced energy gun, marksman beamrifle, decloner, temp gun, x-ray gun, ion carbine and energy crossbow to said new protolathe
/:cl:

2021-05-31 17:57 UTC, OceanFish1 commented
Validhunting rate drops to 0% congratulations

2021-06-02 09:45 UTC, PowerfulBacon commented
I don't really like the corg placement

2021-06-02 09:47 UTC, PowerfulBacon approved these changes, later dismissed

2021-06-02 09:47 UTC, PowerfulBacon commented on code/__DEFINES/research.dm
> +#define DEPARTMENTAL_FLAG_ARMORY		(1<<7)
Armory should be before ALL

2021-06-02 09:52 UTC, Fresh341 commented on code/__DEFINES/research.dm
> +#define DEPARTMENTAL_FLAG_ARMORY		(1<<7)
Aight, let me see if i can change this.

2021-06-02 10:00 UTC, Autisem commented
besure to give either HoS or warden a spare weapons lathe board. Its standard for there to be a spare in the lockers

2021-06-02 10:20 UTC, Fresh341 commented
> 
> 
> besure to give either HoS or warden a spare weapons lathe board. Its standard for there to be a spare in the lockers

It is in the changelog

2021-06-02 10:23 UTC, Fresh341 commented
> 
> 
> I don't really like the corg placement

Hmm i can place it somewhere else if you want me to. Any idea where it would fit better?

2021-06-02 11:33 UTC, Isy232 commented
> add: Added all firing pins to the armory protolathe

Do you mean you also allowed it to print standard firing pins instead of just mindshield and test range?

If so, thats good, but please tell me.

2021-06-02 12:03 UTC, Fresh341 commented
> 
> 
> > add: Added all firing pins to the armory protolathe
> 
> Do you mean you also allowed it to print standard firing pins instead of just mindshield and test range?
> 
> If so, thats good, but please tell me.

No, i only added the mindshield and test-range firing pins to them. I couldn't find the standart ones in the weapon_designs.dm.

2021-06-03 02:09 UTC, francinum commented
Adding standard firing pins to the armory lathe will not be approved.

They are intentionally not printable.

2021-06-03 09:31 UTC, Fresh341 commented
> 
> 
> Adding standard firing pins to the armory lathe will not be approved.
> They are intentionally not printable.
> 
> Do not include edit tags in the changelog segment.

Alright, well i would have no idea on how to add them anyways. Sorry for the edit tag then, i didn't know that. Anything else that you don't agree with/needs fixing?

2021-06-04 08:49 UTC, PowerfulBacon submitted a review, later dismissed
Corgstation is fine, but rip the sec scooter

2021-06-06 14:19 UTC, Fresh341 commented
> 
> 
> Corgstation is fine, but rip the sec scooter

Oh i did not remove the scooter, i just moved it ontop of the other one. I did the same with the flashers on another map. Thats what i mean't with minimal changes. I hope thats still okay.

2021-06-07 19:17 UTC, Fresh341 commented
Hope that last commit removed the merge conflicts. (I hope i did not break everything here)

2021-06-08 11:40 UTC, PowerfulBacon approved these changes, later dismissed

2021-06-16 03:41 UTC, bloons3 commented on _maps/map_files/CorgStation/CorgStation.dmm
> +>>>>>>> master
merge conflict, fails map CI

2021-06-17 18:16 UTC, Fresh341 commented
I won't have access to my computer in the next 10 or so days, i will see if i can fix everything once i come back!

2021-06-23 16:03 UTC, lordScrubling commented
Porting [tgstation#56133](https://github.com/tgstation/tgstation/pull/56133) is a much better solution than this band-aid

2021-06-30 07:27 UTC, Fresh341 commented
> 
> 
> Porting [tgstation#56133](https://github.com/tgstation/tgstation/pull/56133) is a much better solution than this band-aid

I don't really understand what you mean with this. The PR you mentioned completely revamps how security aquires advanced guns. It completely changes the balance and would never pass the public vote in my opinion.

And your PR still does not fix the issue that any officer can aquire those advanced guns. Which questions me if you even read what my PR is supposed to "fix"/change. My PR tries to make the warden be responsible for the advanced weaponry of security. And not like how it is right now, everyone with just basic security access can print particle acceleration rifles or any other really strong gun for example.

2021-07-03 22:08 UTC, lordScrubling commented
> 
> 
> > Porting [tgstation#56133](https://github.com/tgstation/tgstation/pull/56133) is a much better solution than this band-aid
> 
> I don't really understand what you mean with this. The PR you mentioned completely revamps how security aquires advanced guns. It completely changes the balance and would never pass the public vote in my opinion.
> 
> And your PR still does not fix the issue that any officer can aquire those advanced guns. Which questions me if you even read what my PR is supposed to "fix"/change. My PR tries to make the warden be responsible for the advanced weaponry of security. And not like how it is right now, everyone with just basic security access can print particle acceleration rifles or any other really strong gun for example. The TG PR still allows any security officer to craft those advanced guns. Read my PR description please before commenting.

They need a base gun from the armory or cargo to first create the guns

2021-07-09 17:56 UTC, Fresh341 commented
Quick question to anyone that reads this. Ike made an annoucement that all mapping changes are stopped for now. Does that mean i should just commit the updated code without the changes i made to each map?

2021-07-09 18:20 UTC, Fresh341 commented
Working on resolving the merge conflicts now.

2021-07-09 18:57 UTC, Kapu1178 commented
this is comedy

2021-07-09 20:03 UTC, Kapu1178 commented
putting this here as a celebration https://cdn.discordapp.com/attachments/565330972707651584/863146873472417812/unknown.png

2021-07-09 20:07 UTC, Archanial approved these changes, later dismissed
I wonder if I can trigger actions

2021-07-09 20:41 UTC, Archanial approved these changes
Code is good, waiting for map unfreeze

2021-07-25 21:32 UTC, PowerfulBacon submitted a review, later dismissed

2021-07-25 21:41 UTC, Archanial requested changes
Delta is broken

2021-08-03 21:44 UTC, Fresh341 commented
I won't be able to work on this in the next week or so. Not that we are in a hurry anyways. I hope my last commit fixed deltastation though.

2021-08-05 16:01 UTC, PowerfulBacon approved these changes
This isn't a solution, its just an inconvenience to a problem that will be worked around. But code is fine and it passed vote so :shrug:

2021-08-14 12:43 UTC, Fresh341 commented
Yes it might not be a solution. But it atleast allows for an IC way of punishing security being equipped with advanced weaponry. After this PR you can blame it on the warden as captain/hos/AI if security is equipped with advanced weapons on a greenshift. I never quite understood why all the guns are supposed to be in the armory but after a couple resarch nodes anyone with basic security access can print better guns than the ones in the armory. Whatever. Its the decision of you guys to merge it in the end. I believe it would be a good change but that is not on me to decide ultimately.

2021-09-05 00:38 UTC, qwertyquerty commented
🔑

2021-09-05 00:39 UTC, ike709 commented
🔑

2021-09-05 00:39 UTC, closed without merging

2021-09-05 00:39 UTC, francinum commented
🔑