ports tg's filter debug menu & minor filter refactor
BeeStation/BeeStation-Hornet pull request #4434
Opened 2021-06-01 06:56 UTC by jupyterkat

## About The Pull Request

ports tgstation/tgstation#55246

![image](https://user-images.githubusercontent.com/56778689/120279824-40d14080-c2fa-11eb-8532-fccb8d8eb960.png)

## Why It's Good For The Game

## Changelog
:cl:
add: New filter editor for admins + development purposes
/:cl:

2021-06-02 09:43 UTC, PowerfulBacon commented
horray now admins can fuck up even more things

2021-06-04 05:25 UTC, bloons3 requested changes

2021-06-04 05:25 UTC, bloons3 commented on code/game/atoms.dm
> +	VV_DROPDOWN_OPTION(VV_HK_RADIATE, "Radiate")
does this have a side effect?

can't find code for this in this PR

2021-06-11 02:46 UTC, bloons3 commented
no don't remove it I wanna adminbus with it reeeee

https://github.com/tgstation/tgstation/blob/46acdbd52d98ee79fb4b823b5c09676756c0d8e4/code/game/atoms.dm#L1248

2021-06-11 11:42 UTC, jupyterkat commented
like you said, it does literally nothing because I literally didn’t bring any code from it to here. wait for a separate pr

2021-06-11 14:01 UTC, bloons3 commented
😿

2021-07-09 10:57 UTC, TheFakeElon approved these changes

2021-07-09 10:57 UTC, merged