ports removal of crossed() and uncrossed(), also checkexit()
BeeStation/BeeStation-Hornet pull request #4454
Opened 2021-06-04 08:01 UTC by jupyterkat

## About The Pull Request

ports
tgstation/tgstation#58188
tgstation/tgstation#58340
and other supporting prs

## Why It's Good For The Game

lots of overhead calling snapped out of existence

## Changelog
:cl:
refactor: make things faster in general
/:cl:

2021-06-04 09:43 UTC, AffectedArc07 commented
You bastard
![image](https://user-images.githubusercontent.com/25063394/120782239-b8cd7f80-c521-11eb-8a1f-69e7cf682297.png)

2021-06-04 09:57 UTC, jupyterkat commented
:crabrave: crossed is gone

2021-06-04 13:58 UTC, OceanFish1 commented
Server is overtaken since crossed getting removed :trollface:

2021-06-04 14:52 UTC, Archanial commented
[*] crossed

2021-06-08 01:12 UTC, mathis650 commented
wow i can't believe they're removing crossed

2021-06-12 09:20 UTC, optimumtact commented
Port this too https://github.com/tgstation/tgstation/pull/59608

2021-06-12 09:58 UTC, jupyterkat commented
> Port this too [tgstation/tgstation#59608](https://github.com/tgstation/tgstation/pull/59608)

merge it first, oranges

2021-06-14 20:02 UTC, ike709 commented
> and other supporting prs

There's a _lot_ of supporting PRs. Are you sure you got all of them? I think I have most of them listed in https://github.com/BeeStation/BeeStation-Hornet/projects/2#column-7174998

2021-06-14 21:28 UTC, jupyterkat commented
do I have to list out all of them now

2021-06-19 16:48 UTC, ike709 commented
This PR lets ghosts "walk around" and trigger things like proximity sensors and pool sound effects.

2021-06-19 20:04 UTC, lordScrubling commented
> 
> 
> This PR lets ghosts "walk around" and trigger things like proximity sensors and pool sound effects.

oh, so thats why that pool sounded like a waterfall yesterday and an admin was calling the chaplain for it saying it was possessed

2021-06-20 08:57 UTC, jupyterkat commented
Fixed, no more waterfalls

2021-06-20 09:58 UTC, RDS88-beeman commented
As far as i can tell this is the PR that breaks bio bags interacting with reproductive extracts, fix please

2021-06-20 10:37 UTC, jupyterkat commented
shush I'll fix later

2021-06-20 11:35 UTC, RDS88-beeman commented
fix now please i wanna slime time sooner rather than later

2021-06-20 11:54 UTC, jupyterkat commented
the more you whine the longer it’ll take

2021-06-20 14:30 UTC, MNarath1 requested changes

2021-06-20 14:30 UTC, MNarath1 commented on code/game/atoms_movable.dm
> +//Called after a successful Move(). By this point, we've alrefady moved
```suggestion
//Called after a successful Move(). By this point, we've already moved
```

2021-06-20 21:52 UTC, AnCopper commented
Something in this PR causes ghosts to trigger walk-over sounds of items such as plushies.

2021-06-21 01:42 UTC, Archanial commented
Pretty sure it breaks prox checkers for xenos and AI turrets. Probably other prox checkers too but those are confirmed.

2021-06-21 01:43 UTC, Archanial commented
![obraz](https://user-images.githubusercontent.com/37456678/122696207-dd746780-d242-11eb-9216-3b86a4878d89.png)

2021-06-21 02:30 UTC, jupyterkat commented
do you know how little that picture narrows it down?

2021-06-21 03:17 UTC, Archanial commented
Yes, have fun.

2021-06-21 03:50 UTC, optimumtact commented
connect loc is buggy, you should really wait for us to shake out the turf change

2021-06-21 23:47 UTC, jupyterkat commented
I'll put this on hold until it gets fixed

2021-06-22 10:43 UTC, jupyterkat commented
@Archanial facehuggers work, turrets works but only when target is not lying down, prox sensor works

2021-06-22 11:32 UTC, Archanial commented
> 
> 
> @Archanial facehuggers work, turrets works but only when target is not lying down, prox sensor works

The issue was with xenos standing on resin not healing, but that's prox sensor issue. I guess we will see on testmerges.

2021-06-22 18:39 UTC, ivanmixo commented
Wet tiles don't slip people, ghosts make the pool make the pool sound.

2021-06-22 21:10 UTC, PowerfulBacon requested changes
Investigate this breaking clockcult runes, Ghosts now trigger crossed() including pools and motion sensors

2021-06-22 21:28 UTC, PowerfulBacon commented
![image](https://user-images.githubusercontent.com/26465327/123001850-1c243200-d3a9-11eb-91dc-b920b2c24a78.png)

2021-06-23 00:50 UTC, jupyterkat commented
@PowerfulBacon update the testmerge?

2021-06-23 03:36 UTC, jupyterkat commented
xeno heals work, slips work, clockwork shit runtimes resolved

2021-06-23 04:33 UTC, jupyterkat commented
clocknerd sigils made works correctly

2021-06-23 04:52 UTC, jupyterkat commented
ghosts are made less spooky and no longer affects the physical world

2021-07-02 12:36 UTC, jupyterkat commented
will be resolved soon. not dead yet

2021-07-15 08:16 UTC, Kylerace commented
changelog is misleading, this only touches movement code and mostly has a visible effect when many things are moving through a tile at once since thats where Crossed() and Uncrossed() get called on the order of n^2 times

2021-07-15 08:53 UTC, jupyterkat commented
still makes things faster

2021-07-15 09:00 UTC, Kylerace commented on code/__DEFINES/dcs/helpers.dm
> +#define LoadComponent(arguments...) _LoadComponent(list(##arguments))
https://github.com/tgstation/tgstation/pull/59185

2021-07-15 09:00 UTC, Kylerace commented on code/datums/components/_component.dm
> +		return NONE | call(listening_datum, listening_datum.signal_procs[src][sigtype])(arglist(arguments))
https://github.com/tgstation/tgstation/pull/59154

2021-07-15 09:00 UTC, Kylerace commented on code/datums/components/_component.dm
> +	for(var/datum/listening_datum as anything in target)
https://github.com/tgstation/tgstation/pull/59432

2021-07-15 09:00 UTC, Kylerace commented on code/datums/components/_component.dm
> +	if(QDELING(src))
https://github.com/tgstation/tgstation/pull/57773

2021-07-15 09:00 UTC, Kylerace commented on code/datums/elements/_element.dm
> +/datum/element/proc/OnTargetDelete(datum/source, force)
https://github.com/tgstation/tgstation/pull/59303

2021-07-15 09:16 UTC, Kylerace commented
also @LemonInTheDark is missing from the changelog. also might want to look at https://github.com/tgstation/tgstation/pull/60026

tbh theres probably like 5 other relevant fix prs you could use its hard to keep track of them all

2021-07-15 09:33 UTC, Kylerace commented
since you have rohs movement refactor you'll want this https://github.com/tgstation/tgstation/pull/59894, also Rohesie and Wayland-Smithy arent in the changelog

2021-07-15 09:52 UTC, jupyterkat commented
thanks for the help but maints will still certainly keep delaying this pr

2021-07-15 12:13 UTC, Archanial commented
This is delayed mostly because it was really buggy on testmerge. I'll ask around for another round.

2021-07-16 12:59 UTC, jupyterkat commented
> changelog is misleading, this only touches movement code and mostly has a visible effect when many things are moving through a tile at once since thats where Crossed() and Uncrossed() get called on the order of n^2 times
> 
> edit: oh you did signal internals ports too

the thing here is we wanna have alot of projectiles and projectiles calls crossed()

2021-09-05 00:41 UTC, ike709 commented
This is objectively a good change. _However,_ TG is still working on this and it still has bugs and should be done later.

2021-09-05 00:41 UTC, closed without merging

2021-09-05 01:04 UTC, jupyterkat commented
> This is objectively a good change. _However,_ TG is still working on this and it still has bugs and should be done later.

less buggy than your other merged buggy as shit datumized ai or datum lightings