Allows admins to edits expired and removed bans
BeeStation/BeeStation-Hornet pull request #4461
Opened 2021-06-04 21:58 UTC by Archanial

## About The Pull Request
Untested and webeditpilled :sunglasses: 

ported: https://github.com/tgstation/tgstation/pull/59431

## Why It's Good For The Game

## Changelog
:cl:
admin: Admins can edits expired and removed bans
/:cl:

2021-06-04 22:09 UTC, Archanial commented
oh my god why is copypasting so hard I swear I didn't drink that much

2021-06-04 22:27 UTC, Archanial commented
please pass

2021-06-05 08:13 UTC, AffectedArc07 commented
But why? This seems like a bad idea

2021-06-05 11:42 UTC, Archanial commented
Because sometimes bans get appealed and we want to change their message.

2021-06-07 18:01 UTC, Crossedfall approved these changes, later dismissed
👏

2021-06-07 18:02 UTC, Crossedfall requested changes

2021-06-07 18:02 UTC, Crossedfall commented on code/modules/admin/sql_ban_system.dm
> +			output += "<a href='?_src_=holder;[HrefToken()];editbanid=[ban_id];editbankey=[player_key];editbanip=[player_ip];editbancid=[player_cid];editbanrole=[role];editbanduration=[duration];editbanadmins
You still didn't copy paste this correctly. You're not using our output

2021-06-07 18:52 UTC, Archanial commented on code/modules/admin/sql_ban_system.dm
> +			output += "<a href='?_src_=holder;[HrefToken()];editbanid=[ban_id];editbankey=[player_key];editbanip=[player_ip];editbancid=[player_cid];editbanrole=[role];editbanduration=[duration];editbanadmins
```suggestion
			output += "<a href='?_src_=holder;[HrefToken()];editbanid=[ban_id];editbankey=[player_key];editbanip=[player_ip];editbancid=[player_cid];editbanrole=[role];editbanduration=[duration];editbanadmins=[applies_to_admins];editbanreason=[rustg_url_encode(reason)];editbanpage=[page];editbanadminkey=[admin_key]'>Edit</a><br>[unban_href]"
```

2021-06-07 19:05 UTC, Crossedfall approved these changes

2021-06-07 19:05 UTC, merged