Removes teratomas from the game completly
BeeStation/BeeStation-Hornet pull request #4547
Opened 2021-06-16 14:03 UTC by Goblinu

## About The Pull Request
Teratomas has had an negative effect both on players and admins alike, the concept of teratomas are detrimental to the game overall. An antagonist role like teratomas should not be in this game at all, maybe in the future they can be reintroduced as a rare side-antag but as of currently the methods of procuring a teratoma is both too easy and just causes too many issues overall.

## Why It's Good For The Game

Teratomas caused nothing but issues, which is the purpose of an antagonist but in a tomas case it is more detrimental than intended. They can be infinitly manifactured by changelings and virologists alike and overall are bad antagonists with no purpose whatsoever other than to sabotage. 

## Changelog
:cl:
Del: Teratomas
Del: Pituitary Disruption
/:cl:

2021-06-16 14:07 UTC, Goblinu commented
Gonna have to work on this more later to fix the checks

2021-06-16 17:16 UTC, leestriter commented
You could just make it so pituitary disruption doesn't make teratomas, deleting the whole thing is overkill.

2021-06-16 19:07 UTC, eeSPee commented
Is this grudgecode?

2021-06-16 19:10 UTC, snek-with-tophat commented
I guarantee you this is a grugecode

2021-06-16 20:01 UTC, Goblinu commented
> 
> 
> I guarantee you this is a grugecode

Critisism to the pr, peanut posts like theese however are not. If you got a issue with the PR go ahead and formulate it rather than making uneccesary comments that leads to nothing but conflicts

2021-06-16 20:04 UTC, Goblinu commented
> 
> 
> You could just make it so pituitary disruption doesn't make teratomas, deleting the whole thing is overkill.

The gimmick about pituitary disruption is that it makes you heal aloot brute and celluar, with the cons being you create tomas, i would gladly put up a bounty to make a new virus, specially if @DatBoiTim is up to the task

2021-06-16 20:04 UTC, eLeCtrOssSnake commented
I honestly don’t get it.

2021-06-16 20:05 UTC, Goblinu commented
> 
> I honestly don’t get it.

What part exactly is it that you dont get?

2021-06-16 20:59 UTC, eLeCtrOssSnake commented
Everything. From purpose to the way you've made this extreme grudge code.

2021-06-16 21:24 UTC, Goblinu commented
> 
> Everything. From purpose to the way you've made this extreme grudge code.

Again, im up for discussion and useless comments like theese are uneccesary, if you have arguments as to why tomas are a positive thing to the game please lay them on me

2021-06-16 21:38 UTC, williamcll commented
Why not just nerf teratomas instead of outright removing them? They barely cause widespread damages anyway.

2021-06-16 21:51 UTC, Goblinu commented
> 
> 
> Why not just nerf teratomas instead of outright removing them? They barely cause widespread damages anyway.

Cause i have troubble seeing how you improve or nerf reskinned monkeys with antag status, they were creatad without second thought

2021-06-16 23:03 UTC, leestriter commented
> > You could just make it so pituitary disruption doesn't make teratomas, deleting the whole thing is overkill.
> 
> The gimmick about pituitary disruption is that it makes you heal aloot brute and celluar, with the cons being you create tomas, i would gladly put up a bounty to make a new virus, specially if @DatBoiTim is up to the task

Actually, the gimmick is heal brute, take cellular, and either get new organs or spit them out. The toma part is minor, and their spawn rate was recently reduced. You could just eliminate their spawn and not fundamentally change pituitary disruption.

2021-06-16 23:04 UTC, DatBoiTim commented
> > > You could just make it so pituitary disruption doesn't make teratomas, deleting the whole thing is overkill.
> 
> > 
> 
> > The gimmick about pituitary disruption is that it makes you heal aloot brute and celluar, with the cons being you create tomas, i would gladly put up a bounty to make a new virus, specially if @DatBoiTim is up to the task
> 
> 
> 
> Actually, the gimmick is heal brute, take cellular, and either get new organs or spit them out. The toma part is minor, and their spawn rate was recently reduced. You could just eliminate their spawn and not fundamentally change pituitary disruption. 

This.

2021-06-16 23:39 UTC, TheFakeElon commented
I ded

2021-06-17 00:40 UTC, Vasily2013 commented
As an admin: Please god yes. 90% of ling/traitorling/dynameme gamemodes where someone calls foul play have a toma involved in some way shape or form. 

My personal fix would be a better objective than "unleash mayhem." 

But removing tomas wouldn't be a significant loss except for murderbone objective lings.

2021-06-17 01:04 UTC, Archanial requested changes
If you want to at least attempt to do it right remove ROLE_TERATOMA.

2021-06-17 02:20 UTC, Raven-Industries commented
This is a terrible idea. Teratomas may need a bit of a rework, but as a concept, they are amazing. Teratomas are space [Gremlins](https://en.wikipedia.org/wiki/Gremlin"), and there's a lot of potential there. You're claiming that there is no place for a sabotaging antag in the game, but I fail to see why that is the case. Why shouldn't they be there for nothing but sabotage? It gives engineering more to do, and it provides an antag type in-between "stealth mode, everyone will think it's greenshift" and "station go boom". Instead of a complete removal, why not, as said, tweak their objective to something like "Sabotage the station systems and create misery and chaos. Do not kill anyone or destroy the SM/main power source". Provide some limits to the sabotage, so it's not a shuttle worthy antag, but otherwise it's fine.

2021-06-17 02:26 UTC, TheFakeElon commented
The main problem with teratomas is the vague administration/rules surrounding them. A more clear objective would help but it's up to admemes to clearly clarify what you can or can't do as a teratoma

2021-06-17 03:13 UTC, Sinestia commented
I think you could resolve this relatively simply by binding their objectives to their creator

non-antag viro, you're just a weak plastic golem that scares people.
non-hijack ling, you can't do things he can't
maints tomas would remain as-is. 

(Viro tomas and ling tomas probably need more constrains on how many can be shat out but that's a side thing.)

2021-06-17 12:30 UTC, TerryTehCoder commented
> Do not kill anyone or destroy the SM/main power source". Provide some limits to the sabotage, so it's not a shuttle worthy antag, but otherwise it's fine.

Ooh, that made me think. There's probably some use looking at the swarmer code if it's really that prevalent of a issue, although I disagree with leaving in physical coding limits unless it's necessary, this is probably more of a administrative issue with Teratomas as said before.

2021-06-17 16:50 UTC, Goblinu commented
> 
> 
> > > > You could just make it so pituitary disruption doesn't make teratomas, deleting the whole thing is overkill.
> > 
> > 
> > > 
> > 
> > 
> > > The gimmick about pituitary disruption is that it makes you heal aloot brute and celluar, with the cons being you create tomas, i would gladly put up a bounty to make a new virus, specially if @DatBoiTim is up to the task
> > 
> > 
> > Actually, the gimmick is heal brute, take cellular, and either get new organs or spit them out. The toma part is minor, and their spawn rate was recently reduced. You could just eliminate their spawn and not fundamentally change pituitary disruption.
> 
> This. Just remove the teratoma loot spawner under PD

I will do that, on a 2nd thought removing PD is a bad move, i'll edit the PR to only remove the toma spawning part

2021-06-17 16:52 UTC, DatBoiTim commented
> > 
> 
> > 
> 
> > > > > You could just make it so pituitary disruption doesn't make teratomas, deleting the whole thing is overkill.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > The gimmick about pituitary disruption is that it makes you heal aloot brute and celluar, with the cons being you create tomas, i would gladly put up a bounty to make a new virus, specially if @DatBoiTim is up to the task
> 
> > > 
> 
> > > 
> 
> > > Actually, the gimmick is heal brute, take cellular, and either get new organs or spit them out. The toma part is minor, and their spawn rate was recently reduced. You could just eliminate their spawn and not fundamentally change pituitary disruption.
> 
> > 
> 
> > This. Just remove the teratoma loot spawner under PD
> 
> 
> 
> I will do that, on a 2nd thought removing PD is a bad move, i'll edit the PR to only remove the toma spawning part

Yeah this is a good way to go about it. Not only does it fix spawning little pieces of shit who's sole job is being a pain in the ass with this disease.

There were also some exploits that could be achieved with the teratoma spawns(chiefly necropolis virus stuff).

2021-06-17 16:52 UTC, Goblinu commented
> 
> 
> This is a terrible idea. Teratomas may need a bit of a rework, but as a concept, they are amazing. Teratomas are space [Gremlins](https://en.wikipedia.org/wiki/Gremlin%22), and there's a lot of potential there. You're claiming that there is no place for a sabotaging antag in the game, but I fail to see why that is the case. Why shouldn't they be there for nothing but sabotage? It gives engineering more to do, and it provides an antag type in-between "stealth mode, everyone will think it's greenshift" and "station go boom". Instead of a complete removal, why not, as said, tweak their objective to something like "Sabotage the station systems and create misery and chaos. Do not kill anyone or destroy the SM/main power source". Provide some limits to the sabotage, so it's not a shuttle worthy antag, but otherwise it's fine.

Never claimed theres no place for sabotage antags, swarmers are a great example of a sabotage antag which doenst create agonizing situations for admins and players alike. I do however claim that the teratoma is a terrible side antag with no purpose or goal whatsover, its a glorified reskined monkey with antag status, it has caused enough issues since its implementation and i think any attempts at fixing it would be futile

2021-06-17 19:37 UTC, eeSPee commented
Idea:
Non antag teratomas: lavaland escalation
Antag lings (changeling): custom objectives (think, broodmother)

2021-06-24 04:47 UTC, lordScrubling commented
> 
> 
> Idea:
> Non antag teratomas: lavaland escalation
> Antag lings (changeling): custom objectives (think, broodmother)

when you code it

2021-07-08 22:59 UTC, wraith-54321 commented
if your gonna remove tomas then add the blood spiders that replaced them

2021-07-23 13:22 UTC, lordScrubling commented
i keep seeing this damned pr on my kraken i assume cause you used your master for this
inescapable
![image](https://user-images.githubusercontent.com/85033680/126787603-34e94d9f-bcf0-4ba1-9fe4-3b838fd14b59.png)
🤮🤮🤮
thankfully this will be going stale soon

2021-07-25 21:16 UTC, Archanial commented
stale

2021-07-25 21:16 UTC, closed without merging