Ports "Arcononomy: Personal Departmental Cargo Ordering" from tg
BeeStation/BeeStation-Hornet pull request #4572
Opened 2021-06-19 02:46 UTC by lordScrubling

## About The Pull Request
Ports [tgstation#53881](https://github.com/tgstation/tgstation/pull/53881) and [tgstation#59691](https://github.com/tgstation/tgstation/pull/59691)
Introduces a new app for modular tablets and laptops that allows people to request orders using their department budget
Heads and quartermasters can approve requests and call the cargo shuttle with the app but not send it back
All heads now start with a tablet that comes with the app preinstalled
`access_view` is a new var that determines what access someone needs to see certain shipments, so that people can't order whatever with their department's budget
The cargo console file has been renamed from console to orderconsole.dm to make it easier to identify
BZ and CO2 canister shipments are now atmos access because theres no reason for toxins to use bz and co2 is pretty lethal to release

## Why It's Good For The Game
Budgets are no longer cards heads keep hidden until the hos or something decides to load up the armory or the cmo decides to load up on meds only at the start of the round

## Changelog
:cl:
add: cargo ordering app
add: heads start with a tablet with the app installed
tweak: bz and co2 canister shipments require atmos access
/:cl:

2021-06-19 03:10 UTC, lordScrubling commented
Ah, i still need to make this scan ids that are on you since pcs dont come with an id module like tg

2021-06-19 20:17 UTC, lordScrubling commented
I still have to figure out why it replaces the approve/reject button with a 0 when you dont have permission

2021-06-21 22:08 UTC, RDS88-beeman commented
there is a reason for scientists to order BZ, and ironically it's for xeno, but all currently in rotation maps start with a can anyway so /shrug/

2021-06-21 22:28 UTC, lordScrubling commented
> 
> 
> there is a reason for scientists to order BZ, and ironically it's for xeno, but all currently in rotation maps start with a can anyway so /shrug/

for xeno but requires toxins access 😳 useless even with xeno access yeah

2021-07-10 16:17 UTC, lordScrubling commented
/recompile tgui

2021-07-10 16:18 UTC, lordScrubling commented
/rebuild tgui

2021-07-10 17:49 UTC, lordScrubling commented
/rebuild tgui

2021-07-11 22:38 UTC, lordScrubling commented
/rebuild tgui

2021-07-27 15:22 UTC, lordScrubling commented
?rebuild tgui

2021-08-05 15:55 UTC, Archanial requested changes

2021-08-05 15:55 UTC, Archanial commented on code/modules/modular_computers/file_system/programs/budgetordering.dm
> +	var/blockade_warning = "Bluespace instability detected. Shuttle movement impossible."
Can't those two be static?

2021-08-05 15:55 UTC, Archanial commented on code/modules/modular_computers/file_system/programs/budgetordering.dm
> +	. = EXPORT_CARGO
```suggestion
	return EXPORT_CARGO
```

2021-08-05 15:55 UTC, Archanial commented on code/modules/modular_computers/file_system/programs/budgetordering.dm
> +	return id
```suggestion
	return id ? id : FALSE
```

2021-08-05 15:55 UTC, Archanial commented on code/modules/modular_computers/file_system/programs/budgetordering.dm
> +		D = get_buyer_id(user)
```suggestion
		var/obj/item/card/id/D = get_buyer_id(user)
```

2021-08-05 15:55 UTC, Archanial commented on code/modules/modular_computers/file_system/programs/budgetordering.dm
> +	data["loan"] = !!SSshuttle.shuttle_loan
```suggestion
	data["loan"] = SSshuttle.shuttle_loan
```
?

2021-08-05 15:55 UTC, Archanial commented on code/modules/modular_computers/file_system/programs/budgetordering.dm
> +	for(var/pack in SSshuttle.supply_packs)
You could build it once in ui static data

2021-08-17 01:33 UTC, lordScrubling commented on code/modules/modular_computers/file_system/programs/budgetordering.dm
> +	data["loan"] = !!SSshuttle.shuttle_loan
![image](https://user-images.githubusercontent.com/85033680/129649318-30a337f4-8089-4131-ba02-47d46343fde7.png)

2021-08-17 01:37 UTC, lordScrubling commented on code/modules/modular_computers/file_system/programs/budgetordering.dm
> +	for(var/pack in SSshuttle.supply_packs)
the order console does the same thing, don't want to make them different

2021-08-17 01:39 UTC, lordScrubling commented on code/modules/modular_computers/file_system/programs/budgetordering.dm
> +	var/blockade_warning = "Bluespace instability detected. Shuttle movement impossible."
the order console does the same thing, don't want to make them different

2021-09-05 00:45 UTC, ike709 commented
Okay so the maintainers approve of this and finally reviewed this in voicechat. However, rather than hiding packs you don't have access to it should instead just block ordering them.

2021-09-05 16:18 UTC, lordScrubling commented
above addressed

2021-10-18 00:20 UTC, Crossedfall requested changes
Seems to work as expected. The numbers are a bit off though. I believe the normal supply console ignores normal separation and doesn't include a space or comma. Can we mirror that here to keep it consistent? Otherwise good to go  

![image](https://user-images.githubusercontent.com/26130695/137650359-c3457fb2-7349-4ce9-afea-2c1d0e338168.png)

2021-11-14 17:32 UTC, lordScrubling commented
normal console has separators as well in `formatMoney`

2021-11-14 21:27 UTC, lordScrubling commented
![image](https://user-images.githubusercontent.com/85033680/141699197-64b8d9b7-6a3a-46bb-9bbf-25548eb05096.png)
all money in verdana now

2021-12-12 01:54 UTC, lordScrubling commented on code/modules/modular_computers/file_system/programs/budgetordering.dm
> +
```suggestion
```

2022-01-03 20:43 UTC, merged