Removes positive stage speed threshold from DNA saboteur
BeeStation/BeeStation-Hornet pull request #4769
Opened 2021-07-08 22:59 UTC by ivanmixo

## About The Pull Request

Removes the threshold which allowed the DNA saboteur symptom to give positive mutations. 

## Why It's Good For The Game

Being able to sidestep a part of medbay (genetics) with a single disease is bad.

## Changelog
:cl:
tweak: DNA saboteur can no longer give positive mutations
/:cl:

2021-07-08 23:04 UTC, zeskorion commented
As the person who added this threshold i approve this pr. It was buffed a little while ago, which made it render genetics obsolete. Before that, no one used this threshold anyways.

2021-07-08 23:13 UTC, zeskorion requested changes
The severityset proc and the desc need to be updated as well

2021-07-09 00:23 UTC, leestriter commented
I was the one who wanted it buffed but I see your point. It came out stronger then I expected, and replacing genetics is bad.

2021-07-09 04:46 UTC, Archanial approved these changes, later dismissed
cool

2021-07-09 10:04 UTC, PowerfulBacon commented on code/datums/diseases/advance/symptoms/genetics.dm
>  	else
Bad else

2021-07-14 05:14 UTC, TheFakeElon approved these changes

2021-07-14 05:14 UTC, merged