Fixes soulstoning people with no soul.
BeeStation/BeeStation-Hornet pull request #4835
Opened 2021-07-16 13:44 UTC by Ivniinvi

## About The Pull Request
You can no longer be soul-stoned if you lack a soul. (Bind Soul, etc.) Closes #4834 

## Why It's Good For The Game
If you don't have a soul, your soul shouldn't be able to be captured.

## Changelog
:cl:
fix: You can no longer use a soulstone on soulless targets.
/:cl:

2021-07-16 13:59 UTC, Cenrus commented
The shard picks a shade from ghosts if no soul is available, is this nessecary?

2021-07-17 05:23 UTC, TheFakeElon submitted a review, later dismissed

2021-07-18 19:14 UTC, Archanial commented on code/modules/antagonists/wizard/equipment/soulstone.dm
> +	if(!M.mind.hasSoul)
what if body has no mind, also this should go after human check

2021-07-19 16:58 UTC, ike709 commented on code/modules/antagonists/wizard/equipment/soulstone.dm
> +	if(!M.mind.hasSoul)
```suggestion
	if(!M.mind?.hasSoul)
```
and yeah move it below human check

2021-07-25 21:31 UTC, Archanial requested changes

2021-07-25 21:31 UTC, Archanial commented on code/modules/antagonists/wizard/equipment/soulstone.dm
> +	if(!M.mind?.hasSoul)
```suggestion
	if(M.mind && !M.mind.hasSoul)
```

2021-07-27 23:46 UTC, TheFakeElon commented on code/modules/antagonists/wizard/equipment/soulstone.dm
> +	if(!M.mind?.hasSoul)
why 🤔

2021-08-05 16:07 UTC, PowerfulBacon approved these changes

2021-08-05 16:07 UTC, merged