Syndicate Incursion private radio
BeeStation/BeeStation-Hornet pull request #4863
Opened 2021-07-19 11:52 UTC by Cenrus

## About The Pull Request

Adds a new independent radio channel for the syndicate incursion to use. The syndicate channel cannot hear the incursion one and vice versa, but the incursionists can snoop into syndicate comms by buying an encryption key.

## Why It's Good For The Game

I want to add Incursion to dynamic at some point and I don't like how they hog up the syndicate channel, taking it away from traitors. Now incursionists and traitors can buy syndicate keys to chat on the same channel. There are also ways for the station to get a hold of syndicate comms during incursion mode, such as the asteroid/lavaland comms agent base.

Opens up some interesting gameplay opportunities, will you be talking with a fellow excommunciate on the syndicate channel, or are you about to be lured into a trap by the team set out to assassinate you?

## Changelog

:cl:
add: Added incursionist private radio channel.
tweak: Excommunicates can buy the syndicate encryption key in the uplink.
/:cl:

2021-07-19 13:03 UTC, PowerfulBacon commented on code/__DEFINES/radio.dm
> +#define FREQ_INCURSION 1361  //!  Private channel for the incursion team
This should be lower on the non accessible radio channels rather than in the middle of all the station channels

2021-07-19 17:23 UTC, francinum commented
...How many radio tokens do we have left exactly, jeez.

2021-07-20 11:01 UTC, PowerfulBacon requested changes
They need a span for the channel, and their freq needs to be lower and nearer to syndie rather than in the middle of all the station stuff.
(Also they could just use blood brother implants)

2021-07-25 21:34 UTC, PowerfulBacon commented
Closing since somewhat stale, feel free to ping and have this branch reopened. This would be better off using the blood brother radio implant, or should use a non-accessible radio channel frequency.

2021-07-25 21:34 UTC, closed without merging