Ability to fireman carry or have monkeys piggyback you
BeeStation/BeeStation-Hornet pull request #4865
Opened 2021-07-19 18:35 UTC by lordScrubling

## About The Pull Request
![image](https://user-images.githubusercontent.com/85033680/126209458-314ef2b3-ebac-49ac-9674-e7bf9d43685f.png)

## Why It's Good For The Game
No more dragging around monkey/toma bodies leaving blood trails when it's time to clean up

## Changelog
:cl:
add: fireman carry works on monkeys and they can piggyback you
/:cl:

2021-07-20 23:22 UTC, Raven-Industries commented
Out of the scope for this, but it would be amusing if monkeys could strangle you when being fireman carried.

2021-07-21 20:06 UTC, Archanial requested changes
Teratomas don't have sprites. Either ask someone to sprite them or blacklist them.

2021-07-22 00:00 UTC, lordScrubling commented
> 
> 
> Teratomas don't have sprites. Either ask someone to sprite them or blacklist them.

why do i need sprites for buckling

2021-08-05 16:09 UTC, Archanial approved these changes

2021-08-07 21:30 UTC, merged