Increase Borg Light Replacer Restock Rate
BeeStation/BeeStation-Hornet pull request #4880
Opened 2021-07-21 03:29 UTC by Mick1299

## About The Pull Request
Increases the restock rate for bulbs in the janitor borg light replacers from 1 bulb per 3 seconds to 1 bulb per 1 second

## Why It's Good For The Game
With the old rate, it would take over a minutes worth of sitting in the recharger just to restock 20 bulbs in the light replacer. This increases the rate three fold, to one bulb a second. 

## Changelog
:cl:
tweak: Increase Janitor borg light replacer restock rate
/:cl:

2021-07-21 07:56 UTC, Sinestia commented
The borg that's 5x better than the job it emulates needs a buff lol

2021-07-21 09:49 UTC, DatBoiTim commented
Wouldn't upgraded chargers take care of this?

2021-07-21 10:19 UTC, PowerfulBacon requested changes
If the charge variable is no longer being used, remove it.

2021-07-21 12:05 UTC, eeSPee commented
I recommend making it recharge like the RCD, when the cyborg goes to recharge.

2021-07-21 12:40 UTC, Mick1299 commented
Charge has been snapped

2021-07-22 13:11 UTC, PowerfulBacon approved these changes

2021-07-25 21:20 UTC, Archanial approved these changes

2021-07-25 21:21 UTC, merged