Changes all OneHuman boards to OneCrew boards
BeeStation/BeeStation-Hornet pull request #4947
Opened 2021-07-27 02:05 UTC by Ivniinvi

## About The Pull Request
Changes all OneHuman boards to OneCrew boards

## Why It's Good For The Game
With Sage becoming the only server, and Sage's AI being Crewsimov at roundstart as opposed to Asimov, it makes far more sense for the board to be OneCrew instead of OneHuman

## Changelog
:cl:
del: Removed the OneHuman AI module
add: Replaced all instances of the OneHuman AI module with the OneCrew AI module
/:cl:

2021-07-27 02:13 UTC, Sinestia requested changes
I wouldn't assume that Sage will forever be crewsimov, there's certainly disagreement among staff from what I've seen.

That said, I think it's more likely to remain crewsimov for a variety of reasons. Biggest is just that changing would be stomping on players who enjoy playing non-human heads/sec for.... shallow RP (because you know SS13 players can't be tasked with RPing racism in a more subtle and engaging way.)

 So overall this is pretty good, makes it easier for people using the circuit, and it's an easy enough thing to revert if the server config changes.

2021-07-27 02:13 UTC, Sinestia commented on code/game/objects/items/AI_modules.dm
>  	laws = list("Only SUBJECT is human.")
Missed this

2021-07-27 02:24 UTC, Sinestia commented
Also while you're here

There's other laws making reference to humans like safeguard, may as well match all of the laws.

2021-07-27 02:32 UTC, Raven-Industries commented
I _will_ miss seeing captains upload human laws on crewsimov and then throwing a tantrum when the AI doesn't listen to the new law.

2021-07-27 02:58 UTC, Ivniinvi commented
Default law modules no longer reference humans, also fixed a mistake in the Oxygen module description

2021-07-27 03:20 UTC, Sinestia requested changes
Asimov + asimovpp still need changed but otherwise good.

2021-07-27 03:20 UTC, Sinestia commented on code/game/objects/items/AI_modules.dm
> +/******************** OxygenIsToxicToCrewmembers ********************/
Should probably say crew, for any plural.

2021-07-27 05:48 UTC, ZombiesVsPlants commented
It would be helpful if you could keep the original boards for Austation (we still use asimov)

2021-07-27 06:13 UTC, Ivniinvi commented
gonna rewrite this with onecrew being a new board, enough changes for me to just close and reopen

2021-07-27 06:25 UTC, Ivniinvi commented
Actually never mind, on second thought that would be way too many boards, I'd just suggest reverting or not merging this if we/a downstream uses or goes back to asimov in the future. Going to leave Asimov and Asimovpp in place, but add crewsimov and crewsimovpp.

2021-07-27 06:34 UTC, Archanial commented
Sus pr

2021-07-27 08:12 UTC, Sinestia commented
Still one inappropriate use of crewmembers


Also asimov was untouched, the actual circuit isn't overriden by the config.

2021-07-27 23:36 UTC, MNarath1 commented
if you edit all human boards change the PR title too to reflect that.

2021-07-28 04:31 UTC, williamcll commented
Has conflicts with PR #4953

2021-07-28 08:53 UTC, Singularity69 commented
make it so you could change between one crew and one human?

2021-08-06 12:55 UTC, PowerfulBacon requested changes
I think the prefered option would be toi make the boards be able to have attack_self to change the human to whatever you want. (Asimovpp should be humans too with the ability to edit it on attack_self)

2021-08-26 13:20 UTC, closed without merging