Mediborg's Amputation Adventure - Emag Edition
BeeStation/BeeStation-Hornet pull request #4975
Opened 2021-07-29 05:55 UTC by Ivniinvi

## About The Pull Request
You can now emag Mediborg's Amputation Adventure, instead of taking one limb it will take all of them, and dispense 20-30 tokens if you choose to do so.

## Why It's Good For The Game
The other two arcade machines have emag functions, why not this one?

## Changelog
:cl:
add: Mediborg's Amputation Adventure can now be emagged.
/:cl:

2021-07-29 10:02 UTC, tiramisuapimancer commented
Can you slam a [Cabinet Man](https://www.youtube.com/watch?v=iZ_P3F3nA1U) reference into this? I'll be your best friend!

2021-08-05 16:20 UTC, Archanial requested changes

2021-08-05 16:20 UTC, Archanial commented on code/game/machinery/computer/arcade.dm
> +			for(var/i=1; i<=rand(20,30); i++)
```suggestion
			for(var/i=1 to rand(20, 30))
```

2021-08-05 16:20 UTC, Archanial commented on code/game/machinery/computer/arcade.dm
> +			to_chat(c_user, "<span class='notice'>You (wisely) decide against putting your hand in the machine.</span>")
put that message after everything and return after completing action, instead.

2021-08-05 16:20 UTC, Archanial commented on code/game/machinery/computer/arcade.dm
> +			for(var/i=1; i<=rand(3,5); i++)
```suggestion
			for(var/i=1 to rand(3, 5))
```

2021-08-06 12:48 UTC, PowerfulBacon approved these changes

2021-08-06 12:48 UTC, merged