Adds the ability to clear a pAI's zeroth law.
BeeStation/BeeStation-Hornet pull request #4990
Opened 2021-07-31 03:55 UTC by Ivniinvi

## About The Pull Request
A pAI's master can clear said pAI's zeroth law.

## Why It's Good For The Game
It's actually quite often that I see pAI masters just want to vibe, or the pAIs just want to go vibe and RP by themself, and this lets the master of the pAI clear the zeroth law stating that the pAI must serve them.

## Changelog
:cl:
add: A pAI's master can now clear the pAI's zeroth law.
/:cl:

2021-08-01 04:42 UTC, francinum commented
You should probably make this be reset by emag as with your other PR

2021-08-02 02:36 UTC, Ivniinvi commented
> You should probably make this be reset by emag as with your other PR

Prime Directive is now restored to "Serve your master." whenever a new master uploads their DNA.

2021-08-05 16:28 UTC, Archanial requested changes

2021-08-05 16:28 UTC, Archanial commented on code/game/objects/items/devices/paicard.dm
> +			if(confirm == "Yes")
```suggestion
			if((input("Are you CERTAIN you wish to remove this pAI's Prime directive? This action cannot be undone.", "Clear Directive") in list("Yes", "No")) == "Yes")
```

2021-08-05 16:38 UTC, Archanial approved these changes

2021-08-05 21:56 UTC, francinum approved these changes

2021-08-05 21:56 UTC, merged