second return of fastmos: electric boogaloo
BeeStation/BeeStation-Hornet pull request #5013
Opened 2021-08-02 03:14 UTC by jupyterkat

## About The Pull Request

re-enables the ''''''''fixed''''''' auxmos monstermos

## Why It's Good For The Game

the people demand it, i love democracy

## Changelog
:cl:
add: atmos made fast once again
/:cl:

2021-08-02 03:41 UTC, ZombiesVsPlants commented
![image](https://user-images.githubusercontent.com/60122079/127801501-5c94cea0-ea1f-4ddd-a7eb-c824a8fa223a.png)

2021-08-02 06:53 UTC, williamcll commented
What did you fix exactly?

2021-08-02 07:29 UTC, Sinestia commented
> 
> 
> What did you fix exactly?

Most of the magic is elsewhere, they've been working with putnam on this.

2021-08-02 08:12 UTC, bluezorua commented
does this have the monstermos flaw of only 14 gas "slots"?

2021-08-02 09:19 UTC, MNarath1 commented
Could you maybe PR the auxmos changes to the auxmos fork ? Pretty sure those two sides should get PR on those two side respectivly instead of just the compiled dll here.

2021-08-02 09:21 UTC, MNarath1 commented
ah wait you did on putnam's repro upstream

2021-08-02 12:05 UTC, Sinestia commented
> 
> 
> does this have the monstermos flaw of only 14 gas "slots"?

that wasn't a flaw, it's a single preprocessor line that needed to be changed.

It just has to know how many gasses to expect, you can set the number to whatever you want. I think ike just left it at 14 and threw in a dummy gas so that he could avoid making any direct modifications of extools.

2021-08-02 12:14 UTC, jupyterkat commented
> does this have the monstermos flaw of only 14 gas "slots"?

no

2021-08-02 12:15 UTC, PowerfulBacon commented
time to remap all station firelocks again :tf:

2021-08-02 12:16 UTC, PowerfulBacon commented
imo LINDA is too slow and makes breaches and space threats nothing, Monstermos is too fast and makes minor breaches absolutely devestating and makes the game need the hugbox firelocks.

2021-08-02 17:40 UTC, AnCopper commented
> imo LINDA is too slow and makes breaches and space threats nothing, Monstermos is too fast and makes minor breaches absolutely devestating and makes the game need the hugbox firelocks.

Paradise Station has fastmos that doesn't instantly depressurize the entire Station.

2021-08-03 00:20 UTC, ike709 commented
> Paradise Station has fastmos that doesn't instantly depressurize the entire Station.

Get someone to implement ZAS in auxtools and I'll consider it.

2021-08-03 02:16 UTC, Sinestia commented
> 
> 
> > Paradise Station has fastmos that doesn't instantly depressurize the entire Station.
> 
> Get someone to implement ZAS in auxtools and I'll consider it.

paradise has LINDA

2021-08-04 10:12 UTC, jupyterkat commented
up for testmerge

2021-08-04 11:36 UTC, PowerfulBacon commented
Can we put this to vote again now thar people have had time to play without monstermos? I was originally pro monstermos, however going back to old atmos I much prefer the non instant decompression.

2021-08-04 20:33 UTC, jupyterkat commented
> Can we put this to vote again now thar people have had time to play without monstermos? I was originally pro monstermos, however going back to old atmos I much prefer the non instant decompression.

no more votes, the fate is sealed

2021-08-10 09:22 UTC, Emiliapains commented
In any case I vote for this to merge, uh wish we could add a poll in here

2021-08-10 16:42 UTC, mcmeiler commented
> add a poll in here

We have a PR vote channel in the discord for a reason

2021-10-21 00:54 UTC, francinum commented
I'm not a fan of bringing back the quick escape firelocks.

2021-10-28 03:11 UTC, francinum requested changes

2021-10-28 03:11 UTC, francinum commented on code/game/machinery/doors/firedoor.dm
> -	if(panel_open || operating)
Please revert your changes to this file.

2021-10-28 04:06 UTC, jupyterkat commented
all works on this will be halted until francis learnt his lesson

2021-11-02 16:52 UTC, closed without merging

2021-11-09 14:01 UTC, Emiliapains commented
Bring it back :(