Converts the component printer to modular fabricator.
BeeStation/BeeStation-Hornet pull request #5020
Opened 2021-08-02 13:15 UTC by PowerfulBacon

## About The Pull Request

Changes the component printer into a modular fabricator. Improves the category names of the circuit components.

![image](https://user-images.githubusercontent.com/26465327/127867658-fbf8e369-7727-4ca1-8963-8902081a0004.png)

![image](https://user-images.githubusercontent.com/26465327/127867675-50223243-d182-439a-a5bd-35637ee612b9.png)

![image](https://user-images.githubusercontent.com/26465327/127867686-fc18858d-64a1-486c-9c44-5861deae27da.png)

![image](https://user-images.githubusercontent.com/26465327/127867701-9142b937-c9de-4227-8993-d94452eea1d2.png)

![image](https://user-images.githubusercontent.com/26465327/127867712-31b7f6c7-344b-4b11-9b71-a0a3908f9294.png)

![image](https://user-images.githubusercontent.com/26465327/127867726-6332779d-1fd4-4021-89f1-5cd1ef48aab4.png)

![image](https://user-images.githubusercontent.com/26465327/127867739-c86f1d00-6901-4761-b732-1c31aa82ea21.png)

![image](https://user-images.githubusercontent.com/26465327/127867823-49f48754-b020-40b8-8a0f-4849ce8dd384.png)

## Why It's Good For The Game

The old UI was horrible to use and navigate, modular fabricator is much better when you are trying to print stuff and browse stuff.

## Changelog
:cl:
refactor: Circuit component printer is now a modular fabricator and uses the modular fabricator UI.
/:cl:

2021-08-03 04:07 UTC, Archanial requested changes

2021-08-03 04:07 UTC, Archanial commented on code/modules/research/designs/wiremod_designs.dm
> +#define WIREMOD_CIRCUITRY "Circuitry"
Move this to defines

2021-08-16 16:54 UTC, Archanial approved these changes
:+1:

2021-08-16 16:54 UTC, Archanial commented on code/game/machinery/fabricators/modular_fabricator.dm
> +	var/minimum_construction_time = 35
Why isn't this define?

2021-08-16 17:01 UTC, ike709 commented on code/game/machinery/fabricators/modular_fabricator.dm
> +	var/minimum_construction_time = 35
Not everything needs to be a define

2021-08-16 17:01 UTC, merged

2021-08-25 20:13 UTC, PowerfulBacon commented on code/game/machinery/fabricators/modular_fabricator.dm
> +	var/minimum_construction_time = 35
Defines are good for variables that aren't obvious or repeated in multiple places. Like returning 1, 2 or 3 as status indicators of how a proc went