Dockerfile updates + BYOND version bump
BeeStation/BeeStation-Hornet pull request #5063
Opened 2021-08-08 05:13 UTC by Crossedfall

## About The Pull Request

Rewrites most of the Dockerfile so that it adheres to modern standards and properly utilizes our several dependency changes. These changes will unfortunately result in a final image size that's about 66 MB larger than our previous images. 278 MB up from 212 MB (at the time of writing).

Our byond hub image has also been updated to use a Debian base over the previous 32-bit Ubuntu image. https://github.com/BeeStation/byond-docker/commit/116121a8ad37e792e9046b90baf34d63e0841d04

## Changelog
N/A

2021-08-08 16:27 UTC, Sinestia requested changes
Auxtools errors currently

2021-08-08 16:35 UTC, Crossedfall commented
> Auxtools errors currently

Mistakenly removed some required dependencies in the final version of the base image. Should be resolved with https://github.com/BeeStation/byond-docker/commit/a0fd0cb8a0ba48c6e774acc43bdaf3afda0e1b05

2021-08-08 17:12 UTC, Sinestia approved these changes

2021-08-11 07:04 UTC, Crossedfall commented
Self merging off the back of @Sinestia's approval

2021-08-11 07:04 UTC, merged