AIs can no longer strip people
BeeStation/BeeStation-Hornet pull request #5084
Opened 2021-08-10 12:19 UTC by ImSynthex

## About The Pull Request

This might be an awful way of doing it, but that's the way it's done with larvae, and it works

I think this was meant to be fixed before in https://github.com/BeeStation/BeeStation-Hornet/pull/4590 but that just didn't work

## Why It's Good For The Game

Closes https://github.com/BeeStation/BeeStation-Hornet/issues/4950

## Changelog
:cl:
fix: AIs can no longer strip people
/:cl:

2021-08-10 15:58 UTC, St0rmC4st3r commented
*snap
*snap

2021-08-10 17:39 UTC, Archanial requested changes

2021-08-10 17:39 UTC, Archanial commented on code/modules/mob/living/silicon/ai/ai.dm
> +	to_chat(src, "<span class='warning'>You don't have any arms!</span>")
```suggestion
```
It doesn't need any message

2021-08-12 18:34 UTC, Archanial commented
The actual solution to the issue lays in mob.dm.
The best way would be to just not show up the panel to something like AI which should never be able to strip people.
https://github.com/BeeStation/BeeStation-Hornet/blob/2d4937b60ca8546bb87fbb2edae5aa96e1bcfd87/code/modules/mob/mob.dm#L805
this is the check for this.
All you need to add is ` && !isAI(U)`.

2021-08-12 20:01 UTC, ImSynthex commented
yeah, i was looking for that, thanks, i'll update this in a few hours to use mob.dm

also maybe change larvae over to that 😳

2021-08-12 23:56 UTC, ike709 approved these changes, later dismissed

2021-08-13 04:07 UTC, Archanial requested changes

2021-08-13 04:07 UTC, Archanial commented on code/modules/mob/mob.dm
> +			if(!iscyborg(U) && !isAI(U) || U.a_intent == INTENT_HARM)
```suggestion
			if((!iscyborg(U) || U.a_intent == INTENT_HARM) && !isAI(U))
```
AIs shouldn't have strip panel even on harm and besides both AI and borg are the same subtype.

2021-08-13 15:16 UTC, ike709 approved these changes

2021-08-13 16:15 UTC, Archanial approved these changes
:+1:

2021-08-13 16:28 UTC, PowerfulBacon approved these changes

2021-08-13 16:29 UTC, merged