The Incredible Fusion of Medical HUD and Prescription Glasses
BeeStation/BeeStation-Hornet pull request #5094
Opened 2021-08-11 18:17 UTC by Vexylius

## About The Pull Request

Medical Doctors with poor eyesight - rejoice! Today our R&D team came up with an idea to integrate a medical HUD in a pair of  prescription glasses... and they failed! So the next thing they tried was putting prescription lenses in an abomination made out of two medical HUDs, and that attempt was more successful.
The result looks more-or-less like this:
![image](https://user-images.githubusercontent.com/22380218/129081590-6e3da338-41f7-4523-85dd-f2ed4a83f1ab.png)
(Credits to @Naevii for the sprite (that I've slightly changed))

Available after researching HUDs in a medical lathe and as a loadout item for  a price of 3500 beecoins.

## Why It's Good For The Game

If you can put medhud on sunglasses, why not on prescription glasses?

## Changelog
:cl:
add: Prescription Medical HUD
/:cl:

2021-08-11 18:25 UTC, Archanial requested changes

2021-08-11 18:25 UTC, Archanial commented on code/modules/client/loadout/loadout_accessories.dm
> +	cost = 3500
```suggestion
```
no free huds from beeshop

2021-08-11 18:51 UTC, RDS88-beeman commented
hey fun idea what if instead of giving nearsighted brig physes a medHUD implant give them this

2021-08-11 21:55 UTC, Vexylius commented on code/modules/client/loadout/loadout_accessories.dm
> +	cost = 3500
aight

2021-08-12 15:51 UTC, lordScrubling commented
> 
> 
> hey fun idea what if instead of giving nearsighted brig physes a medHUD implant give them this

i don't remember brig physes getting that or even a medhud

2021-08-12 19:09 UTC, super12pl commented
> hey fun idea what if instead of giving nearsighted brig physes a medHUD implant give them this

CMO was the one with medHUD implant dummy

2021-08-13 10:21 UTC, ImSynthex commented
> CMO was the one with medHUD implant dummy
nearsighted brig phys gets a bugged medhud implant that can't be removed and doesn't show up on scanners :)

2021-08-13 21:14 UTC, super12pl commented
> > CMO was the one with medHUD implant dummy
> 
> nearsighted brig phys gets a bugged medhud implant that can't be removed and doesn't show up on scanners :)

what the fuck

2021-08-14 02:45 UTC, lordScrubling commented
probably not an implant then, just puts the hudglasses on then deletes them without removing their hud element

2021-08-14 11:07 UTC, Archanial approved these changes

2021-08-14 19:31 UTC, merged