Adds phobia quirk.
BeeStation/BeeStation-Hornet pull request #5095
Opened 2021-08-11 19:13 UTC by super12pl

## About The Pull Request
Adds negative phobia quirk which at cost of -2 points gives the holder random permanent phobia.

## Why It's Good For The Game
Phobias are fun, let's have more of them

## Changelog
:cl:
add: Phobia quirk
/:cl:

2021-08-11 19:50 UTC, Vasily2013 commented
If there is a way to list the specific phobia in the medical records that would be based as hell.

2021-08-11 21:45 UTC, St0rmC4st3r requested changes

2021-08-11 21:45 UTC, St0rmC4st3r commented on code/datums/traits/negative.dm
> +/datum/quirk/paraplegic/add()
Why are you so cruel towards paraplegic people? What did they do to you?

2021-08-11 21:45 UTC, St0rmC4st3r commented on code/datums/traits/negative.dm
> +/datum/quirk/paraplegic/add()
Remover also needed.

2021-08-12 08:37 UTC, super12pl commented on code/datums/traits/negative.dm
> +/datum/quirk/paraplegic/add()
Added

2021-08-16 16:46 UTC, Archanial approved these changes

2021-08-22 05:42 UTC, qwertyquerty commented
Is this really worth 2 points?

2021-08-23 01:29 UTC, St0rmC4st3r commented
> Is this really worth 2 points?

Considering how crippling some phobias can be (security, doctors), yes

2021-08-26 21:46 UTC, PowerfulBacon approved these changes

2021-08-26 21:46 UTC, merged