Spiders: Adds a large user warning when a nurse or midwife clears their directive
BeeStation/BeeStation-Hornet pull request #5134
Opened 2021-08-16 01:54 UTC by Rukofamicom

## About The Pull Request

![image](https://user-images.githubusercontent.com/9547572/129501152-422248cc-ac84-450f-94ce-bd299a0a6644.png)

![image](https://user-images.githubusercontent.com/9547572/129501169-c9baeee8-53ad-4fe3-a4a5-a3612d6caa80.png)

It isn't clear that when canceling a dialogue box it returns a null value. I've made this substantially more visible to the end user so that perhaps spiders without directives will be generated a little less frequently. 

## Why It's Good For The Game

Spiders without directives cause mass mayhem and chaos, often times without a clear path of blame. This very large message will make it very apparent to a player what they have done, and warns them of what will happen if they do not correct it in case it was unintentional

## Changelog
:cl:
add: Added a very large notice to spiders who are clearing their directive when they do.
/:cl:

2021-08-16 02:52 UTC, Rukofamicom commented
Working on preventing reproduction entirely by player controlled spiders without a directive.

2021-08-16 03:17 UTC, Rukofamicom commented
Now I'd just like to fix error messages when failing to lay eggs, but by all rights this is good to go. 

The error messages for why you failed to lay eggs *already didn't work*

2021-08-16 03:54 UTC, Rukofamicom commented
No error message fix, but I did update the ability icon so that players are at least told they need to set a directive in order to reproduce on the reproduction ability itself.

2021-08-16 04:18 UTC, Archanial commented
Ided pr

2021-08-16 13:33 UTC, Archanial requested changes

2021-08-16 13:33 UTC, Archanial commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +			return 1
```suggestion
			return TRUE
```
If you can change rest returns to true/false

2021-08-16 13:34 UTC, Archanial requested changes

2021-08-16 13:34 UTC, Archanial commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +		if(S.fed && S.directive)
You are checking for fed twice, what you should do is check fed then return true whenever player has no ckey or has directive.

2021-08-18 04:38 UTC, Archanial approved these changes
Code good

2021-08-19 23:07 UTC, PowerfulBacon approved these changes

2021-08-19 23:07 UTC, merged