Mobs no longer create blood trails while being thrown
BeeStation/BeeStation-Hornet pull request #5164
Opened 2021-08-20 23:24 UTC by lordScrubling

## About The Pull Request
they get a little flag while being thrown that prevents the creation of trails

## Why It's Good For The Game
trying to move bodies but it keeps making streaks

## Changelog
:cl:
add: throwing creatures doesn't make blood trails anymore
/:cl:

2021-08-20 23:46 UTC, yyzsong commented
Mfw walk into medbay and see medical doctors chucking people across the fucking medbay to save time

2021-08-22 05:52 UTC, qwertyquerty approved these changes

2021-08-22 05:53 UTC, qwertyquerty requested changes
Actually, I take it back. If you're going to have a state flag for an object currently being thrown, it should be applied to all throwable objects, not just mobs

2021-08-22 16:00 UTC, ivanmixo commented
So you can just throw someone over and over down the hall and they won't lose any blood?

2021-08-25 22:57 UTC, BrumalLake commented
> 
> 
> This makes 0 sense.

feel like this is gonna be your recurring joke after i did it to you

2021-09-02 14:20 UTC, PowerfulBacon commented on code/modules/mob/living/living.dm
> +	if(!has_gravity() || movement_type & THROWN)
```suggestion
	if(!has_gravity() || (movement_type & THROWN))
```
Just to be safe I would do something like this, bit checks not in brackets can get funky

2021-09-06 17:12 UTC, lordScrubling commented
should the flag be applied to all moveables when you throw them right now? i don't think anyone will be used the flag any time soon on non mobs

2021-09-10 13:17 UTC, qwertyquerty commented
Yes, it should be applied to anything that can possibly be thrown.

2021-09-10 16:48 UTC, Isy232 commented
People still bleed when thrown...

2021-09-10 18:06 UTC, lordScrubling commented
> People still bleed when thrown in anything even remotely realistic...

holy shit stop talking about realism and even then you lose the realism argument because you don't drag against the ground while flying through the air 🤯

2021-09-14 23:44 UTC, lordScrubling commented
> 
> 
> Yes, it should be applied to anything that can possibly be thrown.

addressed

2021-09-15 14:38 UTC, qwertyquerty approved these changes

2021-09-15 15:25 UTC, KubeRoot commented
I don't like this very much so, not when the argument for it is that it shouldn't be making blood streaks when *moving bodies*. There are multiple ways to move bleeding bodies without leaving blood trails, including fireman carry, rollerbeds and bodybags, literally yeeting people across rooms shouldn't be better than those options.

2021-09-15 16:04 UTC, Sinestia commented
Caveman PR

2021-09-15 22:21 UTC, lordScrubling commented
meant for moving bodies a couple of tiles not long distances
they still streak while landing

2021-09-17 06:59 UTC, chizzy376 commented
> meant for moving bodies a couple of tiles not long distances
> they still streak while landing

This PR coupled with the one that allows you to catch thrown bodies will have medical staff play basketball with the dying person's body since that would be the most efficient way to move people around. Besides, hurling someone that is bleeding at mach 5 is going to leave a blood trail, since they're still bleeding and the blood in the air that leaks out will eventually fall to the ground.. thus forming a blood trail on the ground when thrown. I really do not like this PR since you'll turn rescuing from a fireman carry to a game of professional basketball

2021-09-18 13:00 UTC, lordScrubling commented
i did not ask for that to get merged and it'll be faster to carry or use other methods in long distances
they will still leave some blood trails

>they're still bleeding and the blood in the air that leaks out will eventually fall to the ground

you just described dripping

2021-09-18 14:02 UTC, ivanmixo commented
make mobs do a big blood splatter on the tile they land on

2021-10-01 21:18 UTC, merged