Significantly reduces the ability to conclusively metagame the karate/tribal claw/sleeping carp granters
BeeStation/BeeStation-Hornet pull request #5195
Opened 2021-08-24 21:42 UTC by Ivniinvi

## About The Pull Request
You can now craft a Blank Scroll identical to a used martial granter with 2 paper.

## Why It's Good For The Game
Cool decoration
Also less metagaming of blank scrolls as currently they exclusively come from uplink items.

## Changelog
:cl:
add: Blank Scrolls are now craftable with two pieces of paper.
/:cl:

2021-08-24 22:01 UTC, Crossedfall commented
![image](https://user-images.githubusercontent.com/26130695/130695936-90656f4e-f70e-4d21-8854-3bbbd9b7eba6.png)

I mean. I gotta do what it says on the tin. I don't make these rules.

2021-08-24 22:03 UTC, RDS88-beeman commented
Can you let us write on and rename them please, if that's not a feature already?
We already have a sprite for the written scroll

2021-08-24 22:03 UTC, RDS88-beeman commented
FUCK

2021-08-25 01:52 UTC, lordScrubling commented on code/datums/components/crafting/recipes.dm
> +	category = CAT_MISC
🤮 no new line under
conjoined

2021-08-25 16:23 UTC, Autisem commented
This still seems pointless if they dont spawn naturaly in maint except for clowns

2021-08-25 18:58 UTC, PowerfulBacon approved these changes

2021-08-25 19:16 UTC, ivanmixo commented
> This still seems pointless if they dont spawn naturaly in maint except for clowns

IIRC there is a maint room with an empty scroll anyways

2021-08-27 04:05 UTC, francinum requested changes
Consideration: Make them an actual flavor of paper instead of a worthless waste of space only crafted for the meme.

2021-09-02 17:57 UTC, DatBoiTim commented
> Consideration: Make them an actual flavor of paper instead of a worthless waste of space only crafted for the meme.

Even give it a writen icon state identical to the unused.

Good for chaplain stuff.

2021-10-07 17:13 UTC, closed without merging