brings wiremods up to date
BeeStation/BeeStation-Hornet pull request #5197
Opened 2021-08-25 05:26 UTC by jupyterkat

## About The Pull Request

brings wiremods up to date
pr list goes here

## Why It's Good For The Game

wiremod is currently outdated and has rare uses

## Changelog
:cl: mothblocks
add: updated wiremods
/:cl:

2021-08-27 17:56 UTC, francinum requested changes

2021-08-27 17:56 UTC, francinum commented on code/modules/wiremod/components/admin/proccall.dm
> +	circuit_flags = CIRCUIT_FLAG_INPUT_SIGNAL|CIRCUIT_FLAG_OUTPUT_SIGNAL|CIRCUIT_FLAG_ADMIN
No. What the *FUCK ARE YOU THINKING*

2021-08-27 18:21 UTC, ike709 commented on code/modules/wiremod/components/admin/proccall.dm
> +	circuit_flags = CIRCUIT_FLAG_INPUT_SIGNAL|CIRCUIT_FLAG_OUTPUT_SIGNAL|CIRCUIT_FLAG_ADMIN
...did TG actually merge this or did you make it?

2021-08-27 18:25 UTC, francinum commented on code/modules/wiremod/components/admin/proccall.dm
> +	circuit_flags = CIRCUIT_FLAG_INPUT_SIGNAL|CIRCUIT_FLAG_OUTPUT_SIGNAL|CIRCUIT_FLAG_ADMIN
Apparently they did?

Still incredibly goddamn dangerous even if the circuits *are* protected.
This is *COMPLETELY UNMENTIONED IN THE PR BODY*

2021-08-27 18:26 UTC, ike709 commented
Remove every admin circuit.

2021-08-27 18:57 UTC, Archanial commented on code/modules/wiremod/components/admin/proccall.dm
> +	circuit_flags = CIRCUIT_FLAG_INPUT_SIGNAL|CIRCUIT_FLAG_OUTPUT_SIGNAL|CIRCUIT_FLAG_ADMIN
its admin only calm down

2021-08-27 19:49 UTC, ike709 commented on code/modules/wiremod/components/admin/proccall.dm
> +	circuit_flags = CIRCUIT_FLAG_INPUT_SIGNAL|CIRCUIT_FLAG_OUTPUT_SIGNAL|CIRCUIT_FLAG_ADMIN
It's still a terrible idea.

2021-08-27 21:50 UTC, jupyterkat commented
no fabs can build the goddamn admin circuits except for the debug fab dammit. 

Incredibly dangerous? Just fucking revoke all admins from proc calling then. Go fuck off franc

If tgmins can use it for events, then I don’t see why we can’t

2021-08-27 21:52 UTC, jupyterkat commented on code/modules/wiremod/components/admin/proccall.dm
> +	circuit_flags = CIRCUIT_FLAG_INPUT_SIGNAL|CIRCUIT_FLAG_OUTPUT_SIGNAL|CIRCUIT_FLAG_ADMIN
no it’s not, admins are allowed to proc call anytime

2021-08-28 00:08 UTC, ike709 commented
Remove every admin circuit.

2021-08-28 00:17 UTC, jupyterkat commented
no

2021-08-28 00:20 UTC, closed without merging

2021-08-28 02:16 UTC, Sinestia commented
You should remove things when the headcoder asks but I don't see the issue with this

Is it dangerous? Of course, but so are a lot of other things admins have. 

 I think beemins should be trustable enough to see a component that literally does arbitrary proccalls as being dangerous. Oh well.

2021-08-28 07:55 UTC, Archanial commented on code/modules/wiremod/components/admin/proccall.dm
> +	circuit_flags = CIRCUIT_FLAG_INPUT_SIGNAL|CIRCUIT_FLAG_OUTPUT_SIGNAL|CIRCUIT_FLAG_ADMIN
It's not terrible idea, how is it different from admin calling sdql or proccall?

2021-08-28 08:01 UTC, mcmeiler commented
It's still admin only. If it ever were to fall into the hands of a normal user, who then proceeds to crash the server, it's on the admin who spawned the circuit *and* the user who crashed the server. 
Though this requires an admin to spawn it first, which shouldn't be happening in the first place.

2021-09-11 20:11 UTC, Watermelon914 commented
don't think you guys realise but players cannot even use these in normal circuits because the integrated circuit needs to be set to admin_only for any of the admin related circuit components to work. Not only that, when an integrated circuit is set to admin_only, they become inaccessible to regular players and regular players are no longer able to interact with it at all.

Sounds like you don't trust admins to use event tooling at all.

2021-09-11 20:31 UTC, ike709 commented
@Watermelon914  I don't trust admins with a privilege elevation exploit. Any admin with VV can use these circuits to do arbitrary SDQL calls without actually checking if they have `R_DEBUG`.

2021-09-11 20:43 UTC, jupyterkat commented
it checks for varedit, if you have varedit you can mass edit shit already

2021-09-11 20:44 UTC, ike709 commented
The existing permissions system being a mess is not an excuse to make it more irrelevant.

2021-09-11 20:44 UTC, ike709 commented
There's not an argument anyone can make that will get me to merge this PR in its current state, so don't waste the effort trying.

2021-09-11 20:45 UTC, jupyterkat commented
then you can just add r_debug to the required perms

2021-09-11 20:48 UTC, jupyterkat commented
> The existing permissions system being a mess is not an excuse to make it more irrelevant.

go fix it then

2021-09-11 22:55 UTC, Watermelon914 commented
> @Watermelon914 I don't trust admins with a privilege elevation exploit. Any admin with VV can use these circuits to do arbitrary SDQL calls without actually checking if they have `R_DEBUG`, to give an example of why this is a bad idea.

I was assuming beestation trusted their admins to not abuse the permissions given to them. If that's not the case, then fair enough.

On tgstation, this isn't an issue because most ranks have access to R_DEBUG. If your issue is that you don't give admins any debug permissions, then adding admin circuits to beestation is a bad idea because they are only designed for event tooling and nothing else and in order to be effective in any event you run, it practically requires you to use proccalls.

There is no reason to add an event tool if it is going to be locked behind debug.

2021-09-11 22:58 UTC, Watermelon914 commented
However, I recommend you port the system but not the components that come with it. You can easily leave them out.
This'll give the foundation for your admins to create components that may not be as free as the proccall component but still able to run semi-decent events with it, unless you don't trust your admins to run events either.
This is very easy to accomplish, simply just remove most/all of the files from the admin component folder.

2021-09-12 00:45 UTC, ike709 commented
> This is very easy to accomplish, simply just remove most/all of the files from the admin component folder.

![image](https://user-images.githubusercontent.com/5714543/132967058-ffb80665-4a08-4881-a75e-507059de0986.png)

2021-09-12 01:12 UTC, Archanial commented
How sure are you that this allows for elevation?
Admins have debug rights already