Fix missing equipment for mecha
BeeStation/BeeStation-Hornet pull request #5223
Opened 2021-08-29 15:03 UTC by kreeperHLC

## About The Pull Request
Fixing the disappearance of equipment when trying to install it in the wrong type of mecha.

## Changelog
:cl:
fix: Equipment no longer disappears when you try to install it in the wrong type of mecha.
/:cl:

2021-08-30 05:55 UTC, francinum commented
Check if the item can even be attached first before taking it in the first place?

2021-08-31 07:05 UTC, kreeperHLC commented
> Check if the item can even be attached first before taking it in the first place?

I understand that you want me to check the attachment of the equipment when it is not in your hand, but how do you imagine that? Neither I nor my head could think of a way to do it.
/obj/item/mecha_parts/mecha_equipment/try_attach_part exists only in /obj/mecha/attackby

2021-08-31 07:44 UTC, kreeperHLC commented
I decided to fix it in a simpler way. I switched the checks around. Now you don't even have to wait for an equipment to be attached to see if it doesn't match.

2021-08-31 09:00 UTC, PowerfulBacon requested changes
Jeez to be after do_mob

2021-08-31 09:06 UTC, francinum commented
> 
> 
> Jeez to be after do_mob

Clarify?

2021-08-31 10:14 UTC, PowerfulBacon commented
The check needs to be after the do_after check due to that having a delay.

2021-08-31 14:44 UTC, ike709 commented on code/game/mecha/equipment/mecha_equipment.dm
>  	if(!user.temporarilyRemoveItemFromInventory(src))
The check should be between do_mob() and this

2021-09-02 11:29 UTC, kreeperHLC commented
I don't know why you make people wait, but like you said, that's what I did. /shrug

2021-09-02 13:27 UTC, PowerfulBacon approved these changes

2021-09-02 13:27 UTC, merged