1984: Suppressed Bans
BeeStation/BeeStation-Hornet pull request #5251
Opened 2021-09-01 08:05 UTC by francinum

## About The Pull Request
Administrators with a new permission flag can issue irrevocable, centcom-excluded bans.
This system is given a very high degree of protection befitting it's status as an incredibly dangerous tool.

## Why It's Good For The Game
Requested by Crossedfall.

## Changelog
:cl:
admin: +SUPPRESS can now be granted to allow access to issue hidden bans.
server: You should NOT be granting this lightly.
/:cl:

2021-09-01 08:11 UTC, PowerfulBacon commented
Why would you ever want a ban that is impossible to remove. I get supressed from centcom since the 18+ thing, but if someone appeals or there was a mistake its gg

2021-09-01 08:28 UTC, francinum commented
> 
> 
> Why would you ever want a ban that is impossible to remove. I get supressed from centcom since the 18+ thing, but if someone appeals or there was a mistake its gg

Because this is exactly what crossed asked for.

2021-09-01 08:50 UTC, Rukofamicom commented
> Why would you ever want a ban that is impossible to remove. 

Because age related bans are 100% unappealable. They are not, however permanent.

Since they are totally unappealable anyway, and they involve sensitive player data, we don't need them publicly listed, and nobody except for the admin placing the ban needs to be aware of it.

2021-09-01 09:10 UTC, PowerfulBacon commented
Age bans are absolutely appealable, time exists.

2021-09-01 14:26 UTC, ike709 commented
@PowerfulBacon The actual reason is GDPR Right to be Forgotten requests. We maintain the ban to operate our service but remove all references to the data outside of the ban DB itself.

2021-09-01 14:28 UTC, ike709 commented on code/modules/admin/sql_ban_system.dm
> +			error_state += "Admin bans can not not be suppressed."
not not

2021-09-01 14:30 UTC, ike709 commented
Wtf is that DMI file change?

2021-09-01 17:38 UTC, PowerfulBacon commented
> 
> 
> @PowerfulBacon The actual reason is GDPR Right to be Forgotten requests. We maintain the ban to operate our service but remove all references to the data outside of the ban DB itself. This feature already exists and is in use. This PR just expands the permissions.
> 
> Whether or not seniormins should have this ability is another story, but since permissions are configurable it is a non-issue w/ regards to merging this.

Yea but they still should be revokable.

2021-09-01 18:25 UTC, Crossedfall commented
> > @PowerfulBacon The actual reason is GDPR Right to be Forgotten requests. We maintain the ban to operate our service but remove all references to the data outside of the ban DB itself. This feature already exists and is in use. This PR just expands the permissions.
> > Whether or not seniormins should have this ability is another story, but since permissions are configurable it is a non-issue w/ regards to merging this.
> 
> Yea but they still should be revokable. (by senior or headmins at least, rather than forcing database edits)

If the bans were still made visible in a way that allowed them to be revoked, then it wouldn't abide by the strict standards set out by privacy guidelines and laws.

2021-09-04 04:02 UTC, Crossedfall requested changes
Drop the badge

2021-09-11 20:45 UTC, Crossedfall approved these changes
I was looking for another reason to read this

![20210216_104803](https://user-images.githubusercontent.com/26130695/132961167-b1574ad7-8d13-4497-b69e-8ab63f37ac0d.jpg)

2021-09-11 20:45 UTC, merged

2021-09-12 01:58 UTC, MCterra10 commented
Australia gang, no GDPR for us :trollface: