The Cargo area on the latejoin menu is no longer incorrectly labeled Command
BeeStation/BeeStation-Hornet pull request #5274
Opened 2021-09-02 15:13 UTC by Ivniinvi

## About The Pull Request
Closes #5214.
The cause of this error was that the latejoin menu was checking the playtime counter of the first job in the global position list. This PR removes the HoP from the supply_positions list, they now exist exclusively on the command_positions list. This was caused by #5004 changing the experience department of the HoP.

## Why It's Good For The Game
Mislabeled field bad.

## Changelog
:cl:
fix: The latejoin menu no longer mislabels Cargo as Command
/:cl:

2021-09-02 15:33 UTC, PowerfulBacon requested changes, later dismissed
HOP is the head of supply though. The problem comes through terrible code on that menu

2021-09-02 20:02 UTC, KubeRoot commented
Maybe this PR should be testmerged/merged until a proper solution is figured out? I'd say it's more confusing for the whole category to be mislabeled than for the HoP to be missing from the category.

2021-11-14 00:04 UTC, francinum commented
That complaint is honestly so minor that this is a good enough fix.

2021-11-14 00:05 UTC, francinum approved these changes

2021-11-14 00:07 UTC, KubeRoot commented
I think the latejoin menu needs a rewrite with how bad the code is. I particularly hate how it uses different things from the occupation menu, and completely breaks if you disable a job, like disabling AI in config.

2021-11-14 00:10 UTC, merged