Admins can now force people to stub their toes.
BeeStation/BeeStation-Hornet pull request #5347
Opened 2021-09-08 15:13 UTC by Ivniinvi

## About The Pull Request
title

## Why It's Good For The Game
Isn't this just about the worst insult from god imaginable?

## Changelog
:cl:
admin: Admins can now force people to stub their toes.
/:cl:

2021-09-08 15:27 UTC, PowerfulBacon commented
Should make the punishment a thing that whenever they touch a table with shoes on they have a 100% chance to stub their toe

2021-09-08 15:52 UTC, Ivniinvi commented
> Should make the punishment a thing that whenever they touch a table with shoes on they have a 100% chance to stub their toe

There is now an option to either force them to stub their toe immediately, once, or to apply a trait that causes them to always stub their toe when they bump a table.

2021-09-08 15:55 UTC, ike709 commented on code/modules/admin/verbs/randomverbs.dm
> +				to_chat(usr, "<span class='warning'>Only humans can stub their toes!</span>")
```suggestion
				to_chat(usr, "<span class='warning'>Only humanoids can stub their toes!</span>")
```

2021-09-08 15:56 UTC, ike709 commented on code/modules/admin/verbs/randomverbs.dm
> +				to_chat(usr, "<span class='warning'>Only humans can stub their toes!</span>")
```suggestion
				to_chat(usr, "<span class='warning'>Only humanoids can stub their toes!</span>")
```

2021-09-08 15:57 UTC, ike709 commented on code/modules/admin/verbs/randomverbs.dm
> +			to_chat(H, "<span class='warning'>You stub your toe on an invisible table!</span>")
You should move toe stubbing into its own proc rather than copypasting the code here.

2021-09-09 15:37 UTC, qwertyquerty commented on code/modules/admin/verbs/randomverbs.dm
> +	var/list/punishment_list = list(ADMIN_PUNISHMENT_LIGHTNING, ADMIN_PUNISHMENT_BRAINDAMAGE, ADMIN_PUNISHMENT_GIB, ADMIN_PUNISHMENT_BSA, ADMIN_PUNISHMENT_FIREBALL, ADMIN_PUNISHMENT_ROD, ADMIN_PUNISHMEN
Need to add the "always" punishment here

2021-09-09 15:39 UTC, qwertyquerty requested changes
^

2021-09-09 16:49 UTC, ike709 commented on code/modules/mob/living/carbon/human/human.dm
> +		power = power / 2
```suggestion
		power *= 0.5
```

2021-09-10 13:06 UTC, qwertyquerty approved these changes

2021-09-10 13:06 UTC, merged