Kicks up a bunch of dynamic threat levels.
BeeStation/BeeStation-Hornet pull request #5377
Opened 2021-09-11 20:33 UTC by Ivniinvi

## About The Pull Request
Raises the following dynamic threat levels per the admin discussion earlier today:
Wizard 20->40
Nukies 20->30
Blob 10->20
Xenos 10->20
Cult 20->25

## Why It's Good For The Game
Admins decided that round ending and team antags should be higher cost.

## Changelog
:cl:
config: The cost of the following rulesets for Dynamic have been increased: Wizard, Nuclear Operatives, Blob, Xenomorphs, Blood Cult.
/:cl:

2021-09-11 20:47 UTC, PowerfulBacon commented
feels like threat level creep considering the highest it was originally created to have is 20 (the only one being higher is clockcult at 35 which is newer). Dynamic rarely roles high values so at 40 it would be the only thing available to spawn and would have no midround antags.
Also dynamic sucks balls with the weighting.

2021-09-11 20:49 UTC, Crossedfall requested changes
Use the config

2021-09-12 10:57 UTC, mcmeiler commented
> Admins decided that round ending and team antags should be higher cost.

Wizard isn't round ending nor a team antag though.

2021-09-12 11:31 UTC, PowerfulBacon commented
> Admins decided that round ending and team antags should be higher cost.

And whats the reasoning for this? I suspect the admins wanted them to have lower weights rather than higher costs. Increasing the cost will not make them appear less commonly if that was the intention for this.

2021-09-12 16:34 UTC, lordScrubling commented
boooring 🥱 
dynamic with only traitors and changelings 99% of the time

2021-09-13 08:19 UTC, llol111 commented
> > Admins decided that round ending and team antags should be higher cost.
> 
> And whats the reasoning for this? I suspect the admins wanted them to have lower weights rather than higher costs. Increasing the cost will not make them appear less commonly if that was the intention for this.

I do not remember discussion on the others, and cant weigh in or oppinionate on those.
But i do remember the discussion for wizard.

Trust me, unlike some people, i love wizard. I realy do.
But at the end of the day it just a big murderfucker, atleast in its current state.
Being a roleplay server, thats not ideal.
That being as it is, it should be rarer in my opinion. Dynamic likes spawning them a bit to much.

All that said at the end of the day we have no influence over yall coders so make of that what you want

2021-09-13 15:35 UTC, Autisem commented
It was a point of discusion internaly, that dynamic is too chaotic sometimes. wizard is fun but not every other round, and from personal experiance becoming a wizard 5 times on dynameme even with low threath its simply too much

2021-09-13 15:43 UTC, PowerfulBacon commented
Wizard just shouldn't be in dynamic. It should be its own gamemode.
It should have been removed from dynamic and kept in the config rather than the other way around.

2021-09-14 00:27 UTC, Ivniinvi commented
Gonna make the changes as a new pr.

2021-09-14 00:27 UTC, closed without merging