Syndicate uniform supplies
BeeStation/BeeStation-Hornet pull request #5429
Opened 2021-09-19 06:35 UTC by heepox

For when you want to look stylishly evil.

## About The Pull Request

Adds a Syndicate Uniform Supplies Crate Containing some Stylish Syndicate Gear
Tactical Turtlenecks
Combat Boots
Syndicate Berets
Armored Vests (no syndicate Equivalent sadly)
Combat Gloves
Balaclavas (Still cool might change to Syndie masks but i dont want them to look totally like nukies)

## Why It's Good For The Game

Adds the ability for someone to order Syndicate Clothes and some armor from an Emagged Cargo console for 1800 credits to equip themselves and 2 others in Fashionably evil clothing.

## Changelog
:cl:
add: Syndicate Uniform Supplies crate to EMAG:ed cargo console containing three sets of syndicate clothing and equipment to wear. Costs 1800.
/:cl:

2021-09-19 17:39 UTC, Autisem commented
Id make them more expensive purely because of combat gloves being insulated. Other then that looks fun

2021-09-19 19:51 UTC, lordScrubling commented
the contraband pack and smugglers already have syndicate masks
save the people a few bucks will you

2021-09-20 08:01 UTC, williamcll commented
Can you put this on the nukie outpost as well?

2021-09-20 14:55 UTC, Boxlta commented
add syndicate admirial equipment to a second crate for like, 5000

2021-09-21 09:37 UTC, williamcll commented
> add syndicate admirial equipment to a second crate for like, 5000

Pretty sure it's called strategist.

2021-09-21 19:04 UTC, Howluinb commented
Do I misunderstand what you mean by Armored Vests, or do you mean stuff like Armored greatcoat/overcoat ect ?
Those are literally way too strong to be buyable

2021-09-22 01:17 UTC, lordScrubling commented
armored vest as in mk IV swat hardsuit
yes, armored vest exactly as written in the code
aand you don't even need an electromagnetic sequencer to buy that stuff anyways

2021-09-22 09:45 UTC, heepox commented
> armored vest as in mk IV swat hardsuit
> yes, armored vest exactly as written in the code
> aand you don't even need an electromagnetic sequencer to buy that stuff anyways

yes its the ones sec and barman have. Literally called that in code. Its there for convenience. and you dont need an emag to buy it but you need sec access to open if you dont have emag.

2021-10-27 07:45 UTC, Archanial requested changes

2021-10-27 07:45 UTC, Archanial commented on code/modules/cargo/packs.dm
> +	desc = "(*!&@#SAD ABOUT THAT NULL_ENTRY, HUH OPERATIVE? WELL, THIS LITTLE ORDER WILL MAKE YOU STYLISH SYNDICATE STYLE. CONTAINS A COLLECTION OF THREE TACTICAL TURTLENECKS, THREE COMBAT BOOTS, THREE
don't mention OOC stuff IC

2021-10-27 07:45 UTC, Archanial commented on code/modules/cargo/packs.dm
> +	cost = 1800
1800 is too low

2021-10-27 07:45 UTC, Archanial commented on code/modules/cargo/packs.dm
> +	cost = 1800
this is still a contraband and is significantly harder to ship to the station. If anything it should cost more to sponsor syndicate.

2021-11-12 17:52 UTC, heepox commented on code/modules/cargo/packs.dm
> +	desc = "(*!&@#SAD ABOUT THAT NULL_ENTRY, HUH OPERATIVE? WELL, THIS LITTLE ORDER WILL MAKE YOU STYLISH SYNDICATE STYLE. CONTAINS A COLLECTION OF THREE TACTICAL TURTLENECKS, THREE COMBAT BOOTS, THREE
literally copied from the other emag crate.

2021-11-12 17:53 UTC, heepox commented on code/modules/cargo/packs.dm
> +	cost = 1800
other crate has actyally useful stuff... if anything this should be cheaper.

2021-11-16 12:04 UTC, Archanial commented on code/modules/cargo/packs.dm
> +	desc = "(*!&@#SAD ABOUT THAT NULL_ENTRY, HUH OPERATIVE? WELL, THIS LITTLE ORDER WILL MAKE YOU STYLISH SYNDICATE STYLE. CONTAINS A COLLECTION OF THREE TACTICAL TURTLENECKS, THREE COMBAT BOOTS, THREE
This doesn't justify anything. Just delete SAD NULL_ENTRY

2021-11-16 12:04 UTC, Archanial commented on code/modules/cargo/packs.dm
> +	cost = 1800
Those are illegally shipped syndicate goods, it doesn't matter if they're useful, they're hard to ship.

2021-11-16 12:05 UTC, Archanial commented on code/modules/cargo/packs.dm
> +	cost = 1800
```suggestion
	cost = 3000
```

2021-11-26 09:27 UTC, Archanial approved these changes

2021-11-30 18:17 UTC, merged