More list related components for WireMod
BeeStation/BeeStation-Hornet pull request #5439
Opened 2021-09-20 19:08 UTC by The-Moon-Itself

## About The Pull Request
Adds a variety of components related to lists to WireMod. These include:
- Two list constructors, so you can actually have a list to work with. The default List Constructor makes a list of length 4 with initial values provided by input ports. The List Length Constructor creates an empty list of specified length from a port.
- Write component and modified index component. Write overrides a value in the list, index returns a value at the specified index. Both of these use a new abstract component class called "indexer" which uses selectable options to change how they function, players can choose to offset their indexes so the list starts at index 0 instead of 1, as well as the option to allow indexes to overflow or underflow back to the start or end of the list respectively.
- Append component, which places a new value on the end of the list, increasing its size by 1.
- Pop component, which can pop the last value off the list like it were a stack, or take the first entry off, as if it were a queue.

Other changes include:
- A maximum list size constant has been added, which these new components respect. No list can be created from components that exceed COMPONENT_MAXIMUM_LIST_SIZE in length, the current value of this constant is 256 because exponents of 2 are cool and clean.
- The component printer now shows the list components category to players.

## Why It's Good For The Game
Lists allow for cleaner calculations and processes in WireMod. The components added in this PR allow for the uses lists for stacks, queues, for loops, and general storage in potential devices created by players.

## Changelog
:cl:
add: More list related WireMod components.
tweak: The index component now has more features.
tweak: The component printer now has a list component category
/:cl:

2021-10-25 21:55 UTC, Archanial requested changes

2021-10-25 21:55 UTC, Archanial commented on code/modules/wiremod/components/abstract/indexer.dm
> +	)
can be static

2021-10-25 21:55 UTC, Archanial commented on code/modules/wiremod/components/list/list_length_constructor.dm
> +	var/new_list = new/list(length)
```suggestion
	var/new_list = new list(length)
```

2021-10-25 23:08 UTC, The-Moon-Itself commented on code/modules/wiremod/components/list/list_length_constructor.dm
> +	var/new_list = new/list(length)
Turns out this causes issues. Without the slash, BYOND thinks 'list' is a var of list_length_constructor instead of the list class.

2021-10-25 23:11 UTC, Archanial commented on code/modules/wiremod/components/list/list_length_constructor.dm
> +	var/new_list = new/list(length)
Byond moment
At least put space between new and /

2021-10-26 01:28 UTC, The-Moon-Itself commented on code/modules/wiremod/components/list/list_length_constructor.dm
> +	var/new_list = new/list(length)
I've made that line a bit more clear, and cleaned up that proc a bit more while I was at it.

2021-10-27 07:47 UTC, Archanial approved these changes

2021-10-27 07:47 UTC, merged