Admins no longer auto-deadmin when logging in to a pAI
BeeStation/BeeStation-Hornet pull request #5462
Opened 2021-09-28 02:29 UTC by Ivniinvi

## About The Pull Request
see title

## Why It's Good For The Game
pAIs are exempt from deadmin regulations, and it's really annoying to press readmin every single time you aghost (and potentially miss logs in that interval)

## Changelog
:cl:
admin: You no longer auto-deadmin as pAI
/:cl:

2021-09-30 17:52 UTC, Crossedfall requested changes
Bad coding practice. Add a flag for PAIs or something broader that contains them. Don't add a hyper specific override.

2021-10-01 17:03 UTC, Crossedfall requested changes
Still doesn't address the problem. The point of it being a flag is so that it can be disabled in config if we want. The `does_not_deadmin` var still acts as a needless override for that.

2021-10-17 23:00 UTC, Crossedfall requested changes
Still have some left over bits of code.

2021-10-17 23:00 UTC, Crossedfall commented on code/modules/mob/living/silicon/pai/pai.dm
> +	does_not_deadmin = TRUE
```suggestion
```

2021-10-17 23:00 UTC, Crossedfall commented on code/modules/mob/living/silicon/silicon.dm
> +	var/does_not_deadmin = FALSE //does this silicon trigger the deadmin condition
```suggestion
```

2021-10-21 19:46 UTC, Ivniinvi commented
arrrrrrrrgh i thought i removed those

2021-11-21 06:23 UTC, Crossedfall requested changes

2021-11-21 06:23 UTC, Crossedfall commented on code/modules/mob/living/silicon/login.dm
> +	if(istype(src, /mob/living/silicon/pai) && (CONFIG_GET(flag/auto_deadmin_pai) || (client.prefs?.toggles & DEADMIN_POSITION_PAI)))
```suggestion
	if(istype(src, /mob/living/silicon/pai) && (CONFIG_GET(flag/auto_deadmin_pai) || (client.prefs?.toggles & DEADMIN_POSITION_PAI)))
		return client.holder.auto_deadmin()
	if(CONFIG_GET(flag/auto_deadmin_silicons) || (client.prefs?.toggles & DEADMIN_POSITION_PAI)))
```

2021-11-21 06:31 UTC, Crossedfall commented on code/modules/mob/living/silicon/login.dm
> +	if(istype(src, /mob/living/silicon/pai) && (CONFIG_GET(flag/auto_deadmin_pai) || (client.prefs?.toggles & DEADMIN_POSITION_PAI)))
tbh, this logic is still pretty yucky.  Two checks for the same return is kinda nasty.

2021-11-27 02:06 UTC, ike709 commented
@Crossedfall

2021-11-27 09:49 UTC, Ivniinvi commented
Crossed has said that he wants the following conditions to be met for the logic:
- One level of indenting 
- One typecheck
- No identical returns
I may be dumb but the only way I can think to accomplish this is one giant if statement, which he has also said he doesn't want.

2022-01-03 20:50 UTC, ike709 commented
@Crossedfall

2022-01-03 20:51 UTC, ike709 commented
I don't really like having a config flag just for pAI autodeadmin tbh.

2022-01-09 01:10 UTC, closed without merging