[PORT] DB Achievements
BeeStation/BeeStation-Hornet pull request #5482
Opened 2021-10-02 02:54 UTC by Ivniinvi

## About The Pull Request
Ports DB achievements from TG.
Ports the following:
tgstation/tgstation#47058
tgstation/tgstation#47617
tgstation/tgstation#48007
And the relevant parts of:
tgstation/tgstation#51255

**This will require migration using the enclosed tool**

## Why It's Good For The Game
We no longer rely on the BYOND hub for achievements, instead using the DB.
Unfortunately, this means ripping out the G-G-Ghosts achievement, as I couldn't figure out a good way to handle it without sleeping in a signal handler.

## Changelog
:cl: Ivniinvi, AMonkeyThatCodes, Qustinnus, Willox, AnturK, SpaceManiac
server: Achievements are now handled by the DB instead of the BYOND hub
add: The verb check-achievements in the OOC tab can be used to see your achievements
del: The G-G-Ghosts achievement is no longer available.
/:cl:

2021-10-02 16:50 UTC, ike709 commented
based

2021-10-02 19:45 UTC, qwertyquerty commented
Bring in all the existing medals into this system

2021-10-02 19:56 UTC, Ivniinvi commented
> Bring in all the existing medals into this system

It has everything except G-G-Ghosts

2021-10-03 07:55 UTC, Ivniinvi commented
I've now re-added the Ghosts medal (thanks Archanial) and edited the descriptions Crossed didn't like.

2021-10-05 01:27 UTC, qwertyquerty commented
Alright, so I think we need a way to award the users who currently have medals their respective achievements.

2021-10-05 01:28 UTC, Ivniinvi commented
> Alright, so I think we need a way to award the users who currently have medals their respective achievements.

Yes, that's what HubMigrator does.

2021-10-05 01:42 UTC, KubeRoot commented
> I've now re-added the Ghosts medal (thanks Archanial) and edited the descriptions Crossed didn't like.

Maybe edit the PR description to remove the mention of not having that one

2021-10-05 01:43 UTC, Ivniinvi commented
> > I've now re-added the Ghosts medal (thanks Archanial) and edited the descriptions Crossed didn't like.
> 
> Maybe edit the PR description to remove the mention of not having that one

Oop, thanks, updated.

2021-10-05 16:14 UTC, qwertyquerty requested changes, later dismissed
Remove your config changes

2021-10-21 19:49 UTC, Ivniinvi commented
![image](https://user-images.githubusercontent.com/22421329/138346857-8070e077-8890-49d2-9d48-78430d06788f.png)

Crossed has approved the portions that he is code owner of (but he didn't mark it as approved on github)

2021-10-25 22:30 UTC, Crossedfall requested changes

2021-10-25 22:30 UTC, Crossedfall commented on tools/HubMigrator/HubMigrator.dm
> +#define MEDAL_METEOR 			"Your Life Before Your Eyes"
I only did a brief check, but I found 10 that didn't correctly match up. Should go back through this list and make sure it's all correct.

2021-10-25 22:30 UTC, Crossedfall commented on code/datums/achievements/boss_achievements.dm
> +	database_id = "Boss Killer"
```suggestion
	database_id = BOSS_MEDAL_ANY
```

2021-10-25 22:31 UTC, Crossedfall commented
> ![image](https://user-images.githubusercontent.com/22421329/138346857-8070e077-8890-49d2-9d48-78430d06788f.png)
> 
> Crossed has approved the portions that he is code owner of (but he didn't mark it as approved on github)

I haven't approved anything yet, I just told you that I would only approve the stuff I had ownership of.

2021-10-25 22:51 UTC, Ivniinvi commented
> > Crossed has approved the portions that he is code owner of (but he didn't mark it as approved on github)
> 
> I haven't approved anything yet, I just told you that I would only approve the stuff I had ownership of.

Oops, sorry, misinterpreted that

2021-10-25 22:53 UTC, Ivniinvi commented
Right, I've addressed the concerns presented.

Various inconsistencies:
The "Exterminator" medal exists in the code and on the hub, but no one has it.
The "Crusher" medal exists in the code but not on the hub.
The "Forgotten Star" medal exists in the code but not on the hub.
The "Avada Kedavra!" medal exists on the hub but not in the code, and no one has it.

As such, none of these four have been included in HubMigrator.dm

2021-10-27 09:20 UTC, Crossedfall requested changes

2021-10-27 09:20 UTC, Crossedfall commented on tools/HubMigrator/HubMigrator.dm
> +			var/list/keyline = list("INSERT INTO [ach](ckey,achievement_key,value,last_updated) VALUES")
last_updated should be when the achievement was unlocked (which is already part of the scraped data).  Currently, this just sets all of the dates to the current date.

2021-12-06 22:50 UTC, Crossedfall requested changes

2021-12-06 22:50 UTC, Crossedfall commented on SQL/database_changelog.txt
> +ALTER TABLE `achievement_metadata` ADD COLUMN (`achievement_name` VARCHAR(64) NULL DEFAULT NULL, `achievement_description` VARCHAR(512) NULL DEFAULT NULL);
```suggestion
DROP TABLE IF EXISTS `achievement_metadata`;
CREATE TABLE `achievement_metadata` (
	`achievement_key` VARCHAR(32) NOT NULL,
	`achievement_version` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`achievement_type` enum('achievement','score','award') NULL DEFAULT NULL,
	`achievement_name` VARCHAR(64) NULL DEFAULT NULL,
	`achievement_description` VARCHAR(512) NULL DEFAULT NULL,
	PRIMARY KEY (`achievement_key`)
) ENGINE=InnoDB;
```

There's no reason to have two queries when those tables don't exist yet.

2021-12-06 22:52 UTC, Crossedfall commented on SQL/database_changelog.txt
> +CREATE TABLE `achievements` (
```suggestion
DROP TABLE IF EXISTS `achievements`;
CREATE TABLE `achievements` (
```

2021-12-06 22:52 UTC, Crossedfall commented on SQL/database_changelog.txt
> +CREATE TABLE `achievements` (
Consistency with the other query

2021-12-06 22:55 UTC, Crossedfall approved these changes
Everything works now.

2021-12-06 23:01 UTC, Crossedfall commented
DB updated and cheevos ported.

2021-12-06 23:04 UTC, merged