Changeling shriek no inflicts confusion.
BeeStation/BeeStation-Hornet pull request #549
Opened 2019-10-14 15:26 UTC by Cenrus

About the Pull Request

Changeling shriek no longer confuses anyone that hears it, causing them to run into tables and walls. Could be a controversial change, so I recommend that a vote is held.

Why It's good for the game

Even after the recent nerf, Resonant Shriek still stands as one of the best changeling abilities, for only one evolution point, and 20 chemicals. When a changeling shrieks, you are forced to either stand still and be an easy target, or move and run into walls, stunning you.

Changeling

🆑 Cenrus
balance: Resonant shriek no longer causes confusion.
/🆑

2019-10-14 15:46 UTC, zeskorion commented
Ok but what does it do if it doesnt confuse you

2019-10-14 15:54 UTC, Cenrus commented
That's my main problem with this, it goes from an extremely powerful ability to almost useless.

2019-10-14 20:44 UTC, ike709 approved these changes

2019-10-14 20:44 UTC, ike709 commented
Code is fine, unsure about balance.

2019-10-15 01:43 UTC, MarkSuckerberg commented
Err, if it doesn't confuse and everything else it does is negligent, this seems like a de facto removal, not a rebalance...

2019-10-15 01:57 UTC, ike709 requested changes
Do the thing.

2019-10-15 01:57 UTC, ike709 commented on code/modules/antagonists/changeling/powers/shriek.dm
> -				C.confused += 15
On second thought, you will need to update the desc and helptext.

2019-10-15 01:57 UTC, ike709 commented
@MarkSuckerberg Semantics. Though I dislike changeling and I'm fine with nerfing them.

2019-10-15 02:13 UTC, qwertyquerty commented
You could probably just reduce the duration of confusion

2019-10-15 02:26 UTC, MarkSuckerberg commented
Yeah, I dontlike changelings in the slightest either, it's just I'm not a fan of leaving a useless ability in. Either find a way to nerf it, or remove it completely.

2019-10-17 19:39 UTC, TothBrush commented
Please god merge this. Changeling abilities should be unique tools for unique situations. Shriek is broken you can just run around spamming it willy nilly and then slaughter anyone who dares come near you.

2019-10-22 22:49 UTC, Toxici11i commented
the fuck, i literally nerfed this last month to cost more chems and inflict less confusion

ided pls nerf

### tg intensifies

2019-10-28 21:20 UTC, ike709 commented
Still haven't updated the desc & helptext.

2019-10-31 16:18 UTC, qwertyquerty commented
Make a new PR that instead of making this useless, balances it a bit. Then update the help text.

2019-10-31 16:18 UTC, closed without merging