Adds some useful stuff to the debug box
BeeStation/BeeStation-Hornet pull request #5519
Opened 2021-10-05 00:01 UTC by TheChaser212

## About The Pull Request
Adds a captain id, blueprints and alien tools to the debug box as well as a bunch of missing materials.

## Why It's Good For The Game
Makes testing stuff a bit easier.

## Changelog
:cl:
admin: Added some useful items to the debug box
/:cl:

2021-10-05 00:04 UTC, lordScrubling commented
don't you get some sort of centcom id

2021-10-05 00:13 UTC, TheChaser212 commented
> don't you get some sort of centcom id

The debug outfit has a commander id which doesn't have id console access so having the spare as well could be useful

2021-10-05 00:13 UTC, lordScrubling commented
you can't mold the brass and runed metal so

2021-10-05 00:15 UTC, KubeRoot commented
The full debug outfit includes additional stuff, including a chief engineer toolbelt, an omnitool, ~~a true AA centcom ID~~, energy axe, T4 BRPED, a human spawner, a hardsuit-mask-oxygen tank setup.

Adding the missing materials is a good idea (at least copper), but not sure about the rest.

Though, as clarified while I was writing the comment, maybe it'd be a better idea to just replace the ID with a full AA one.

2021-10-05 03:45 UTC, TheChaser212 commented
Alright I decided to change some of the items on the debug outfit rather than adding them to the box

2021-10-05 09:35 UTC, Archanial commented
I'd rather have CE tools just because alien ones look weird

2021-10-05 17:34 UTC, chizzyyyy commented
How about adding more RPED mats too, adding a disk with all genetics traits inside too? Also more than 50 of each mat would be nicer

2021-10-05 19:14 UTC, KubeRoot commented
Having silo link on the admin RCD doesn't make much sense, since it already has INFINITE matter.

> I'd rather have CE tools just because alien ones look weird

I agree, maybe a compromise would be having an alien toolbelt in the backpack or box of debug tools? There's advantages to them for sure, especially with alien multitool revealing wires, but I think experimental tools are generally more convenient, especially since you can also fit RPD and RCD on the toolbelt with them.

> Also adding a disk with all genetics traits inside too would be wonderful, could you please do that?

Not sure how well that would work though, I don't think the console has a search functionality?

2021-10-05 23:57 UTC, Mick1299 commented on code/game/objects/items/RCD.dm
> +	upgrade = RCD_UPGRADE_FRAMES | RCD_UPGRADE_SIMPLE_CIRCUITS | RCD_UPGRADE_SILO_LINK
Why does it need the silo link upgrade when it has infinite matter by default

2021-10-06 00:20 UTC, KubeRoot commented
I just remembered, I would also suggest porting the debug glasses from https://github.com/tgstation/tgstation/pull/47923, might want to look at the other changes as well to see how they did it. I think it's sometimes nice to have xray easily accessible when debugging.

2021-10-06 01:55 UTC, TheChaser212 commented
Okay, added all those suggestions

2021-10-07 02:59 UTC, KubeRoot commented
I got a new suggestion: how about a holofan in the box of tools?

2021-10-07 03:06 UTC, lordScrubling commented
all these niche things
don't want something cause it looks weird
who even uses this outfit
you can't even fit the things back into the box

2021-10-07 03:51 UTC, KubeRoot commented
> all these niche things

Most of the things in the outfit aren't *that* niche, they're things you might want while debugging stuff.

> don't want something cause it looks weird

Don't want something to *replace the current toolbelt worn by the outfit*, the "looks weird" part is probably also about it just being hard to recognize, and in my case because experimental tools are more compact.

> who even uses this outfit

I do, and if you're not using it while coding stuff you should start, a few clicks and you go from any mob, aghost included, to a human equipped with a hardsuit, oxygen with internals on, a full suite of materials and tools, full access... Often when testing my code I just go straight to switching myself to the debug outfit first thing after spawning in.

> you can't even fit the things back into the box

That is true, but I think that also applies to stuff *actually accessible in-game*, like boxes from an uplink. That said, you do also have a bag of holding to put stuff in, and you can always drop them where you are when just debugging.

*But also, any reason to not make this box also have ridiculously high storage?*

2021-10-08 02:41 UTC, BrumalLake commented
i just teleport to where i need to go cause i don't want to walk so i don't need access 99% of the time, god state if i need spaceproofing, and spawn things in cause most of the time it's niche things that you're not gonna find inside the debug outfit
nothing wrong with adding these toys though
you can stay on your mortal plane

2021-10-25 17:24 UTC, Archanial requested changes

2021-10-25 17:24 UTC, Archanial commented on code/game/machinery/cloning.dm
> +		var/datum/mutation/human/HM = i
do a typed loop instead

2021-10-25 19:42 UTC, KubeRoot commented on code/game/machinery/cloning.dm
> +		var/datum/mutation/human/HM = i
I believe the code for this is:

```suggestion
	for(var/datum/mutation/human/HM as() in GLOB.all_mutations)
```

2021-10-25 20:29 UTC, chloecat0 commented on code/game/machinery/cloning.dm
> +		var/datum/mutation/human/HM = i
Yeah that works

2021-10-25 21:49 UTC, Archanial approved these changes

2021-10-25 21:49 UTC, merged