The Community Hairstyle Pack
BeeStation/BeeStation-Hornet pull request #5538
Opened 2021-10-07 13:59 UTC by DrMacCool

## About The Pull Request

This PR is the product of a fun little project over on the [Beestation Forums](https://forums.beestation13.com/t/new-hairstyles/15009). It contains 18 new hairstyles and beards made up of personal additions and community requests.

**Additions w/ Credits**

**Hairstyles**
<details>
<summary> 'Bald 2', requested by Archanial </summary>

![image](https://user-images.githubusercontent.com/91456657/136906997-fd52e142-50bd-48fc-9229-b1b959d3f999.png)

</details>
<details>
<summary> 'Curtains' </summary>

![image](https://user-images.githubusercontent.com/91456657/136907449-7ce679cf-c68a-431f-9498-e57fe31a2363.png)

</details>
<details>
<summary>'Gelled Spikes'</summary>

![image](https://user-images.githubusercontent.com/91456657/136907649-75710b1d-2001-4d2e-bcfc-113139c22816.png)

</details>
<details>
<summary>'Moustache', requested by Engelwood</summary>

![image](https://user-images.githubusercontent.com/91456657/136907850-0ecdf3d1-f35b-4d81-adf0-ea5daeb470c3.png)

</details>
<details>
<summary>'Mohawk (Reverse)', requested by Engelwood</summary>

![image](https://user-images.githubusercontent.com/91456657/136908050-478e4575-20bd-4c10-aeb4-0c32a378b4ed.png)

</details>
<details>
<summary>'Mullet', requested by Spockye</summary>

![image](https://user-images.githubusercontent.com/91456657/136908424-d1c6d9ff-1f01-4a86-b020-0f109e9d0abc.png)

</details>
<details>
<summary>'Parted 2'</summary>

![image](https://user-images.githubusercontent.com/91456657/136908647-1c8e6ec9-1846-4659-8550-bd3880c8183c.png)

</details>
<details>
<summary>'Pompadour (Huge)', requested by Engelwood</summary>

![image](https://user-images.githubusercontent.com/91456657/136908752-23576f97-d46d-45d7-bfed-98b9520553d3.png)

</details>
<details>
<summary>'Ponytail (Alchemist)'</summary>

![image](https://user-images.githubusercontent.com/91456657/136909213-becc5d73-c1ec-4e74-a767-d319831efc4f.png)

</details>
<details>
<summary>'Ponytail (Tight)'</summary>

![image](https://user-images.githubusercontent.com/91456657/136909535-76cb11b8-da1d-435b-9b29-554146f428fb.png)

</details>
<details>
<summary>'Short Afro'</summary>

![image](https://user-images.githubusercontent.com/91456657/136909430-eab0e404-3238-4c2d-aa39-154bd2876b06.png)

</details>
<details>
<summary>'Spamton', requested by Crow004</summary>

![image](https://user-images.githubusercontent.com/91456657/136909639-2456a16f-2a85-4d1a-9810-a289c1594ec0.png)

</details>
<details>
<summary>'Pride', requested by Kapu1178</summary>

![image](https://user-images.githubusercontent.com/91456657/136909717-e1faf6cf-fb45-4a27-bba4-6fba9e362fac.png)

</details>

**Facial Hair**
<details>
<summary>'Eyebrows'</summary>

![image](https://user-images.githubusercontent.com/91456657/136910081-dec8e6be-e308-44b3-9c6d-cd85c0e204a9.png)

</details>
<details> <summary>'Beard ( Powerful)', requested by Dog132 </summary>

![image](https://user-images.githubusercontent.com/91456657/136909923-1d5c3f63-e3da-416e-947a-e0bf15e97b52.png)
 
</details>
<details>
<summary>'Beard (The Colonel)', requested by Colonel</summary>

![image](https://user-images.githubusercontent.com/91456657/136910282-ba42061c-6843-4e0e-8c0c-46a81e58c0b7.png)

</details>
<details>
<summary>'Moustache (Robotnik)', requested by Engelwood</summary>

![image](https://user-images.githubusercontent.com/91456657/136910372-c5cfac47-06e2-4af4-b0b1-4cdb0ebc85c3.png)

</details>
<details>
<summary>'Moustache ('Stache 'n Chops)', requested by Taylor</summary>

![image](https://user-images.githubusercontent.com/91456657/136910519-5ea16ea9-3c05-4dd0-93a4-45957d82c6be.png)

</details>

## Why It's Good For The Game

More customisation options for humans/ethereals/oozelings.

## Changelog
:cl:
add: Adds 18 new hairstyles/beards requested by the community.
/:cl:

2021-10-07 15:46 UTC, Archanial commented
Make bald 2 😏

2021-10-08 02:11 UTC, DrMacCool commented
> 
> 
> Make bald 2 😏

Will you immediately merge the PR if I do?

2021-10-09 20:03 UTC, Archanial commented
> 
> 
> > Make bald 2 smirk
> 
> Will you immediately merge the PR if I do?

yes

2021-10-09 20:04 UTC, Archanial requested changes

2021-10-09 20:04 UTC, Archanial commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +	icon_state = "hair_vegeta"
I am unsure if we can have reference to Vegeta in code

2021-10-09 20:04 UTC, Archanial commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +	icon_state = "facial_gigachad"
same here, not sure if we want to have reference to a meme, when those are banned in rules

2021-10-09 23:36 UTC, Kapu1178 commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +	icon_state = "hair_vegeta"
Suggested rename: Pride

2021-10-10 08:28 UTC, DrMacCool commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +	icon_state = "facial_gigachad"
Yeah, I thought 'Gigachad' would be pushing the boundaries. Any suggestions for what would be better?

2021-10-10 08:28 UTC, DrMacCool commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +	icon_state = "hair_vegeta"
Gotcha.

2021-10-11 07:09 UTC, DrMacCool commented
Jesus Christ GitHub is confusing. Ignore the four commits I just made.

Point is: Names changed, 'Bald 2' added (It's real).

I am going to blow my brains out if there's something else I've screwed up.

2021-10-11 08:14 UTC, Archanial commented
It's fine github will squash it.

2021-10-12 06:30 UTC, Crossedfall commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +
```suggestion
```

All of this whitespace can go

2021-10-12 06:33 UTC, Crossedfall commented
Can we get a single image with all the new hairstyles? It'd be much easier to see than looking at the sprite diffs

2021-10-12 06:45 UTC, DrMacCool commented
> 
> 
> Can we get a single image with all the new hairstyles? It'd be much easier to see than looking at the sprite diffs. Or you can do sets of each and spoiler tag them under the correlating bullet.

Sure thing. There's pictures of each of the styles that were requested over on the OG [forum thread](https://forums.beestation13.com/t/new-hairstyles/15009), but I can put them all here, too.

2021-10-15 22:28 UTC, Crossedfall approved these changes

2021-10-15 22:28 UTC, merged