rat cubes
BeeStation/BeeStation-Hornet pull request #5542
Opened 2021-10-08 03:59 UTC by fighterslam

## About The Pull Request
Adds Rat Cubes to the game, orderable from cargo.
These rats cannot have diseases and thus are useless for virology

## Why It's Good For The Game
You can now acquire rats. Rats for the kitchen, rats for your favorite coworker, rats for your least favorite coworker.. Rats!

## Changelog
:cl: fighterslam
add: Added rat cubes, orderable from Cargo.
/:cl:

2021-10-08 04:00 UTC, zeskorion commented
Lizards may now eat ratt

2021-10-08 09:08 UTC, Archanial requested changes

2021-10-08 09:08 UTC, Archanial commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	var/clean = FALSE
```suggestion
	var/sterile = FALSE 
```

2021-10-08 11:39 UTC, St0rmC4st3r commented
I think you should do something so that bounties could not be cheesed with this. Make it require wild rats from their natural habitat?

2021-10-15 04:12 UTC, Dingo-Dongler commented
Why would you have the flavour text about the virologist running out of samples if they don't have any diseases

2021-10-23 12:22 UTC, BrumalLake reviewed
changed a variable name without changing its instances?

2021-10-23 12:22 UTC, BrumalLake commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	if(prob(75) && !clean)
```suggestion
	if(prob(75) && !sterile)
```

2021-10-23 12:22 UTC, BrumalLake commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	clean = TRUE
```suggestion
	sterile = TRUE
```

2021-10-28 21:48 UTC, Boxlta commented
RAT CUBE RAT CUBE RAT CUBE

2021-10-28 21:59 UTC, RyunaTW commented
RATS RATS RATS RATS HAVE IT SPAWN A RAT NAME LOUIE RANDOMLY LIKE LISA CORGI RATS RATS RATS RATS

2021-11-09 22:06 UTC, fighterslam commented
not ready for review quite yet, I need to re-make the rat-cube-box sprite before this is ready

2021-11-20 01:13 UTC, lordScrubling commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	if(prob(75)) && !sterile)
```suggestion
	if(!sterile && prob(75))
```
unpaired and it'd be better to check if it's sterile before computing rand

2022-01-03 20:52 UTC, ike709 commented
Stale

2022-01-03 22:23 UTC, Archanial commented
Stale

2022-01-03 22:23 UTC, closed without merging