Ports Decal Painter
BeeStation/BeeStation-Hornet pull request #5557
Opened 2021-10-13 15:47 UTC by Ivniinvi

## About The Pull Request
Ports the Decal Painter from tgstation
Ports:
tgstation/tgstation#54556
tgstation/tgstation#51762
And parts of
tgstation/tgstation#48040

## Why It's Good For The Game
People can now paint decals to their heart's content, whether it be a caution sign near the SM or warning labels near an airlock.

## Changelog
:cl: Ivniinvi, Denton, ArcaneMusic, XRandomXManX
add: The Decal Painter is now available at protolathes and autolathes for you to paint decals.
/:cl:

2021-10-13 22:16 UTC, Archanial requested changes

2021-10-13 22:16 UTC, Archanial commented on code/game/objects/items/airlock_painter.dm
> +	var/dir_list = list(1,2,4,8)
I'm pretty sure those are defined somewhere

2021-10-13 22:16 UTC, Archanial commented on code/game/objects/items/airlock_painter.dm
> +	var/turf/open/floor/F = target
This cast should be in second if

2021-10-14 20:11 UTC, Ivniinvi commented on code/game/objects/items/airlock_painter.dm
> +	var/dir_list = list(1,2,4,8)
If I set it to use GLOB.cardinals it just shows as "West West West West" for some reason

2021-10-14 20:20 UTC, Archanial commented on code/game/objects/items/airlock_painter.dm
> +	var/dir_list = list(1,2,4,8)
Yeah stuff such as NORTH, SOUTH etc. are defined, use defines.

2021-10-25 18:02 UTC, Archanial approved these changes

2021-10-25 18:02 UTC, merged