virology gameplay tweaks and rebalances (again)
BeeStation/BeeStation-Hornet pull request #5567
Opened 2021-10-15 07:41 UTC by zeskorion

## About The Pull Request
changes several core aspects of virology.
-nerfs maint diseases
-some crew now occasionally spawn with dormant diseases the virologist can extract via extrapolator or blood sample. this encourages the virologist to collect blood samples and data from the crew, instead of crawling through maint and then spending the rest of the shift in virology
-diseases now have a chance to mutate when they're transmitted. this scales inversely with stealth and resistance, and the level of the symptom mutated depends on severity- the more severe, the higher the symptom level. the end result of this change is that viro is encouraged to test deadly, contagious, but easy to cure viruses on monkeys. this means there is now a reason to follow biohazard SOP as virologist, or when entering the virology lab. this also adds engagement with science, cargo, genetics, and chemistry, whether to cure your old monkeys or get new ones- mutated viruses count as the same disease, so curing them immunizes them to that virus
Edit: people are freaking out cuz i forgot to add that adding cryostylane to a disease means it wont mutate.   Relax.
-removes the tedium balancing involved in adding the last few symptoms to a disease. all it is is a 2-5 minute time-tax
-adds randomized virus cures
-some misc fixes (see changelog. if dirty syringe disease transfer was removed intentionally, i'll modularize it out into a different pr)

## Why It's Good For The Game
my rationalization was in the above description. this change is primarily geared towards crew engagement.
also has a few fixes, see changelog

## Changelog
:cl:
add: diseases can now mutate new symptoms when transmitted between hosts
add: crew can now spawn with dormant viruses, which a virologist can extract with an extrapolator or blood sample
add: adds randomized virus cures
tweak: nerfs maintenance diseases to compensate for the above disease extraction methods
tweak: removes RNG involved in the fourth, fifth, and sixth symptoms added to a virus
fix: fixes a bug when determining severity of a severity 5 symptom
fix: syringes now properly interact with extrapolators
fix: dirty syringes now transfer diseases again. yay?
fix: fixes disease severity calculations that got stealth removed.
/:cl:

2021-10-15 07:42 UTC, zeskorion commented
please add needs wiki update and needs testmerge labels. due to the scope of this pr, there may be some bugs i didnt catch or some balance minutia with the numbers that needs changing with a testmerge. and the wiki thing is obvious

2021-10-15 10:34 UTC, Archanial commented
Are you sure disease mutating on transfer is za good idea? Won't it make releasing positive viruses dangerous?

2021-10-15 10:46 UTC, Archanial requested changes

2021-10-15 10:46 UTC, Archanial commented on code/datums/diseases/_disease.dm
> +		var/datum/disease/advance/A = D
This should be done in child instead of parent

2021-10-15 10:46 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +	var/static/list/advance_cures = list(list(/datum/reagent/water, /datum/reagent/consumable/nutriment, /datum/reagent/ash, /datum/reagent/iron),list(/datum/reagent/consumable/ethanol, /datum/reagent/u
Needs newlines and judging by how github formatted it, there's something wrong with syntax

2021-10-15 10:46 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +			advance_diseases += P
This means you will add it twice

2021-10-15 10:46 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +	for(var/datum/symptom/S in symptoms)
As()

2021-10-15 10:46 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +		spread_text = "None"
```suggestion
		spread_text = NONE
```

2021-10-15 10:46 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +		var/datum/reagent/D = GLOB.chemical_reagents_list[cures[1]]
Why's cure list if you pick one?

2021-10-15 10:46 UTC, Archanial commented on code/datums/diseases/advance/symptoms/viral.dm
> +	A.mutability = 0.5
Add or subtract here instead of flat values

2021-10-15 10:46 UTC, Archanial commented on code/datums/diseases/advance/symptoms/viral.dm
> +	A.mutability = 0.5
Same for 3 other examples

2021-10-15 10:46 UTC, Archanial commented on code/game/objects/items/devices/scanners.dm
> +				for(var/datum/symptom/S in A.symptoms)
As()

2021-10-15 10:46 UTC, Archanial commented on code/game/objects/items/devices/scanners.dm
> +				for(var/datum/symptom/S in A.symptoms)
As()

2021-10-15 10:46 UTC, Archanial commented on code/modules/jobs/job_types/_job.dm
> +	dormantdiseasecheck(H)
Name looks awful, add some _

2021-10-15 10:46 UTC, Archanial commented on code/modules/jobs/job_types/_job.dm
> +	if(islizard(H) || iscatperson(H))
This is stupid

2021-10-15 10:46 UTC, Archanial commented on code/modules/jobs/job_types/_job.dm
> +	var/datum/symptom/guaranteed = null
```suggestion
	var/datum/symptom/guaranteed
```

2021-10-15 10:46 UTC, Archanial commented on code/modules/jobs/job_types/_job.dm
> +		scandisease.spread_text = "None"
```suggestion
		scandisease.spread_text = NONE
```
Or null

2021-10-15 17:10 UTC, KubeRoot commented
> Are you sure disease mutating on transfer is za good idea? Won't it make releasing positive viruses dangerous?

You can add cryostylane to diseases to prevent modification, from what I can tell this also prevents mutation while spreading.

2021-10-15 17:42 UTC, zeskorion commented on code/datums/diseases/_disease.dm
> +		var/datum/disease/advance/A = D
If i did, i'd have to copy and past the entire proc due to the order i need it to function in

2021-10-15 17:44 UTC, zeskorion commented on code/datums/diseases/advance/advance.dm
> +			advance_diseases += P
No, this is checking if the host is already infected with a mutant strain. It adds it to a list that contains all diseases to override

2021-10-15 17:45 UTC, zeskorion commented on code/datums/diseases/advance/advance.dm
> +		spread_text = "None"
Spread text is a string that appears when a disease is checked in the pandemic, not a flag

2021-10-15 17:46 UTC, zeskorion commented on code/modules/jobs/job_types/_job.dm
> +		scandisease.spread_text = "None"
See above

2021-10-15 17:47 UTC, zeskorion commented
> Are you sure disease mutating on transfer is za good idea? Won't it make releasing positive viruses dangerous?

You can add cryostylane to a virus to make it not mutate. This only affects positive viruses in that-
They cant be taken and modified
A traitor could intentionally make one mutable to subtly screw over the crew

2021-10-15 17:48 UTC, zeskorion commented on code/modules/jobs/job_types/_job.dm
> +	if(islizard(H) || iscatperson(H))
I want to get level 0 symptoms from clowns. Simple as.

2021-10-15 17:50 UTC, zeskorion commented on code/datums/diseases/advance/advance.dm
> +		var/datum/reagent/D = GLOB.chemical_reagents_list[cures[1]]
Because some diseases use multiple cures. Not advance diseases other than sentient disease, but id break stuff if i removed that

2021-10-15 17:51 UTC, zeskorion commented on code/datums/diseases/advance/advance.dm
> +	var/static/list/advance_cures = list(list(/datum/reagent/water, /datum/reagent/consumable/nutriment, /datum/reagent/ash, /datum/reagent/iron),list(/datum/reagent/consumable/ethanol, /datum/reagent/u
Yeah its too long ill do that

2021-10-15 17:59 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +			advance_diseases += P
Include this in the check above

2021-10-15 18:01 UTC, Archanial commented on code/modules/jobs/job_types/_job.dm
> +	if(islizard(H) || iscatperson(H))
no, the comment's about lizards and felinids

2021-10-15 19:59 UTC, zeskorion commented on code/datums/diseases/advance/advance.dm
> +	for(var/datum/symptom/S in symptoms)
not sure what you mean here

2021-10-15 20:04 UTC, zeskorion commented on code/modules/jobs/job_types/_job.dm
> +	if(islizard(H) || iscatperson(H))
they are mechanically likelier to get a virus. this makes sense. the only kind of IC racism this may encourage is virologists being more likely to talk to lizards and felinids for a blood sample

2021-10-15 20:13 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +	for(var/datum/symptom/S in symptoms)
```suggestion
	for(var/datum/symptom/S as() in symptoms)
```

2021-10-16 12:13 UTC, Syrox25 commented
I await the numerous Viro bans from people making airborne Self-resp (as it should be)

As for Malicious virus'. Pairing mutation with random cure, would that not make Viro even worse for round derailment? granted, it *should* only be martyr/hijack if a death plague happens... but needing several cures and vaccines (which in theory could never end if mutation is high enough)

Could it also end up with someone eating a rat and the crew being unable to counteract it due to naturally high mutation chance and transmission

Or am I overthinking this and all "mutations" still share virus name, cure and vaccine?

2021-10-16 15:36 UTC, zeskorion commented
> I await the numerous Viro bans from people making airborne Self-resp (as it should be)
> 
> As for Malicious virus'. Pairing mutation with random cure, would that not make Viro even worse for round derailment? granted, it _should_ only be martyr/hijack if a death plague happens... but needing several cures and vaccines (which in theory could never end if mutation is high enough)
> 
> Could it also end up with someone eating a rat and the crew being unable to counteract it due to naturally high mutation chance and transmission
> 
> Or am I overthinking this and all "mutations" still share virus name, cure and vaccine?

Mutations should all share the same vaccine, but not cure.
Mutating death plagues will be slightly harder to cure, but less deadly overall due to becoming imperfect 
Mutating positive viruses will not grow too dangerous cuz severity stuff, but also can be stopped from mutating altogetherr

2021-10-16 16:23 UTC, Archanial requested changes

2021-10-16 16:23 UTC, Archanial commented on code/datums/diseases/_disease.dm
> +		var/datum/disease/advance/A = D
No, this is not true, just run parent proc after your function and everything should stay the same

2021-10-16 16:23 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
>  	for(var/datum/symptom/S in symptoms)
```suggestion
	for(var/datum/symptom/S as() in symptoms)
```
not your code but might as well put it

2021-10-16 16:23 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +	if(!keepid)
does the rest have to run if we're keeping the ID? If not early return here

2021-10-16 16:23 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +	for(var/datum/symptom/S in symptoms)
this is still valid and not resolved

2021-10-16 16:23 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +		var/datum/reagent/D = GLOB.chemical_reagents_list[cures[1]]
this still looks somewhat stupid to me, can't you just use initial to get the name?

2021-10-16 16:23 UTC, Archanial commented on code/game/objects/items/devices/scanners.dm
> +				for(var/datum/symptom/S in A.symptoms)
still not resolved

2021-10-16 16:23 UTC, Archanial commented on code/game/objects/items/devices/scanners.dm
> +				for(var/datum/symptom/S in A.symptoms)
same

2021-10-16 16:23 UTC, Archanial commented on code/modules/jobs/job_types/_job.dm
> +		unfunny= FALSE
what's the point of extra var here if you are just going to use it once?

2021-10-16 16:23 UTC, Archanial commented on code/modules/jobs/job_types/_job.dm
> +	var/biohazard = 10
Medical doctors deal with diseases so they should have less of a chance to have dormant viruses since they are the ones who detect and heal them.

2021-10-16 19:46 UTC, zeskorion commented on code/modules/jobs/job_types/_job.dm
> +		unfunny= FALSE
because i need it to equal 0 when  on a clown or mime, because i need a 0-level symptom

2021-10-16 19:48 UTC, zeskorion commented on code/modules/jobs/job_types/_job.dm
> +	var/biohazard = 10
"dormant" viruses are meant to represent antibodies or old dna from a previously cured virus someone is now immune to, so them having a greater chance is still in-line

2021-10-16 20:25 UTC, zeskorion commented on code/datums/diseases/advance/advance.dm
> +	if(!keepid)
we need the new name bit for disease evolution

2021-10-16 20:29 UTC, zeskorion commented on code/datums/diseases/advance/advance.dm
> +		var/datum/reagent/D = GLOB.chemical_reagents_list[cures[1]]
not my code, this is basically how the original coder got the name from the cure in a list to the cure text. i don't want to touch it cuz im not that well versed in lists

2021-10-16 20:32 UTC, zeskorion commented on code/datums/diseases/_disease.dm
> +		var/datum/disease/advance/A = D
no, because the copy of the disease is made in this proc before my function

2021-10-16 22:37 UTC, Archanial commented on code/datums/diseases/_disease.dm
> +		var/datum/disease/advance/A = D
then copypaste rest of the function, it's only like 4-5 lines anyway

2021-10-18 11:04 UTC, ZombiesVsPlants commented
> diseases now have a chance to mutate when they're transmitted
> encouraged to test deadly, contagious, but easy to cure viruses on monkeys

Oh shit, I might actually play virologist after this, this sounds fun AF
(Also sounds fun to experiment on dozens of monkeys as a medical borg for malf in order to release a unoptimised virus)

2021-10-28 21:30 UTC, zeskorion commented on code/datums/diseases/_disease.dm
> +		var/datum/disease/advance/A = D
bleh, done, whatever

2021-11-08 17:14 UTC, Archanial approved these changes

2021-11-08 17:15 UTC, merged