deep frying nonfoods is no longer a qdel v2
BeeStation/BeeStation-Hornet pull request #5568
Opened 2021-10-15 07:51 UTC by zeskorion

## About The Pull Request
this pr was denied through a qwerty moment about a year ago, even though most devs were in agreeance on it
https://github.com/BeeStation/BeeStation-Hornet/pull/2624
lets try it again

## Why It's Good For The Game
deepfrying is a wayyyy to easily done way to qdel an item, and doesn't even check resistance flags

## Changelog
:cl:
del: removes deepfrying items to destroy them. you can now eat them out of the crust, or just clean them off
/:cl:

2021-10-15 10:28 UTC, Archanial commented
This makes deep fryer not do anything.

Unless you make stuff get damaged or associate frying level level with damage/complete consumption of said item this is not going to fly.

2021-10-15 10:29 UTC, Archanial commented on code/modules/food_and_drinks/food/snacks_bread.dm
> +/obj/item/reagent_containers/food/snacks/deepfryholder/proc/clean_batter()
Missing signal handler

2021-10-15 15:04 UTC, KubeRoot commented
> this pr was denied through a qwerty moment

![image](https://user-images.githubusercontent.com/6917698/137509448-3e4f9707-a0a5-4aac-9784-c05a4065b72e.png)

More like maintainers decided to hold a vote and the playerbase voted against it.

2021-10-15 15:06 UTC, ike709 commented
\> pretending votes matter

2021-10-15 15:40 UTC, AnCopper commented
> > this pr was denied through a qwerty moment
> 
> ![image](https://user-images.githubusercontent.com/6917698/137509448-3e4f9707-a0a5-4aac-9784-c05a4065b72e.png)
> 
> More like maintainers decided to hold a vote and the playerbase voted against it.

Golden existed back then.

2021-10-15 16:46 UTC, williamcll commented
> > > this pr was denied through a qwerty moment
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/6917698/137509448-3e4f9707-a0a5-4aac-9784-c05a4065b72e.png)
> > More like maintainers decided to hold a vote and the playerbase voted against it.
> 
> Golden existed back then.

pretty sure more people voted than the amount of people that played golden.

2021-10-15 17:29 UTC, ike709 commented
\> arguing about the irrelevant votes

2021-10-15 17:41 UTC, zeskorion commented
> This makes deep fryer not do anything.
> 
> Unless you make stuff get damaged or associate frying level level with damage/complete consumption of said item this is not going to fly.

This makes the deep fryer not do anything other than make deep fried food, yes.

2021-10-15 18:36 UTC, francinum requested changes
Add the signal handler mark and ping me for a merge.

Ideally this'd tie into the damage system, but the ability to make any item ireecoverable regardless of resistance flags with one click is kinda a major issue.

2021-10-15 19:15 UTC, Archanial commented
🔑

2021-10-15 20:25 UTC, Archanial commented
Okay I don't entirely oppose the idea but this pr is flawed.

Items should get damaged, damage to the item scaling on the time thing is fried or on fry level and possibly completely destroyed if it's hp is low enough and is fried enough.

And then, based on amount of hp gone, you should add nutrients to deepfry holder so we don't end up with deepfry, take bite, deepfry take bite...

2021-10-15 21:11 UTC, zeskorion commented
> Okay I don't entirely oppose the idea but this pr is flawed.
> 
> Items should get damaged, damage to the item scaling on the time thing is fried or on fry level and possibly completely destroyed if it's hp is low enough and is fried enough.
> 
> And then, based on amount of hp gone, you should add nutrients to deepfry holder so we don't end up with deepfry, take bite, deepfry take bite...

i don't believe the deepfryer should be able to destroy items in any capacity. they're way too easy to access
and, there's no reason to have it deal damage to an item it doesnt destroy. damaging items is a very, very rare mechanic. its easier to just haul it to the recycler at that point, yknow?

2021-10-15 21:13 UTC, francinum approved these changes
Review requirements fulfilled.

2021-10-16 09:19 UTC, PowerfulBacon commented
The resistance flags are checked when something is deep fried.

2021-10-16 21:27 UTC, zeskorion commented
> The resistance flags are checked when something is deep fried. Also can't you infinitely eat stuff?

it checks the indestructable tag when you try to put it in the deep fryer. the deep fryer doesnt check any other flags, like heatproof
and spraying cooking oil doesnt check any flags

2021-11-16 12:29 UTC, AnCopper commented
@PowerfulBacon

2021-11-22 01:13 UTC, merged

2021-11-22 01:30 UTC, MCterra10 commented
Based?

2021-11-22 06:58 UTC, AnCopper commented
Should've been done a year ago, finally.

2021-11-22 07:33 UTC, zeskorion commented
> Should've been done a year ago, finally.

First made on october the fourth, last year