Random disease name overhaul
BeeStation/BeeStation-Hornet pull request #5578
Opened 2021-10-18 00:14 UTC by zeskorion

## About The Pull Request
random disease names are picked from a large pool of name elements that take several factors of a disease into account, instead of just being "Experimental disease" or "sample #1234"

## Why It's Good For The Game
adds a bit of personality to random diseases you wouldnt find elsewhere, will definitely get a few laughs

## Changelog
:cl:
add: random diseases now have better random names
/:cl:

2021-10-18 00:15 UTC, zeskorion commented
if you want me to post a few disease name examples, ask and you shall recieve

2021-10-18 00:49 UTC, zeskorion commented
a list of all maint diseases found in one round of deltastation under current maint disease balance 

Germs
Spacer's Asteroid Bug
The Space Complex
Colds
Healing Cold Infection
Malignant Station
Andrea-62
Bloodborne Heart
Clockwork Asteroid Disease
Sicks
Diseaseism
Spacer's Diseaseitis
Idiot's Asteroid-alpha
Sickitosis
Disease-51
Station Rot
Sandford's Magnet
Benign Nouns
Nounosis
Simmons's Station
Immortal #1972
Sick Bug
Noun Complex
Bloody Asteroid
Clockwork Robot
Lazy Cold Virus
Bloodborne Immortal Bug
Diseasey
Crypto Space
Sleeping Mutant
Elixirism
Crystalline Space
The Germosis
Feet Virus
Space Syndrome

2021-10-18 02:19 UTC, mcmeiler commented
> Feet Virus

😳

2021-10-19 14:22 UTC, Archanial requested changes

2021-10-19 14:22 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +/datum/disease/advance/proc/randomdiseasename(var/atom/diseasesource)//generates a name for a disease depending on its symptoms and where it comes from
Can you follow naming scheme?

2021-10-19 14:22 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +		if(-INFINITY to 1)
-infinity will never be reached, what's the point of having it?

2021-10-19 14:22 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +				prefixes += list("Vermin ", "Zoo", "Maintenance ")
This seems to be frequent but some of those have random spaces and the end or beginning.

2021-10-19 14:22 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +			if(istype(diseasesource, /mob/living/simple_animal/pet/hamster/vector))
Use switch

2021-10-19 14:22 UTC, Archanial commented on code/datums/diseases/advance/symptoms/fever.dm
> +		prefixes += list("Desert")
This code can run multiple times

2021-10-19 14:22 UTC, Archanial commented on code/datums/diseases/advance/symptoms/flesh_eating.dm
> +		bodies = list("Zombie")
Same here

2021-10-19 14:22 UTC, Archanial commented on code/datums/diseases/advance/symptoms/pierrot.dm
> +	prefixes += "[pick(GLOB.clown_names)]'s "
Same

2021-10-19 14:22 UTC, Archanial commented on code/datums/diseases/advance/symptoms/fever.dm
> +		prefixes += list("Desert")
I suggest clearing prefixes etc. in parent, because resistance, severity etc may change

2021-10-19 14:32 UTC, zeskorion commented on code/datums/diseases/advance/advance.dm
> +			if(istype(diseasesource, /mob/living/simple_animal/pet/hamster/vector))
Does switch even work with istype like that?

2021-10-19 14:32 UTC, zeskorion commented on code/datums/diseases/advance/advance.dm
> +				prefixes += list("Vermin ", "Zoo", "Maintenance ")
That is intentional. Zoo is meant to stick directly onto the body

2021-10-19 14:33 UTC, zeskorion commented on code/datums/diseases/advance/advance.dm
> +		if(-INFINITY to 1)
Its the lowest number and how all disease mins are written

2021-10-19 14:34 UTC, zeskorion commented on code/datums/diseases/advance/symptoms/fever.dm
> +		prefixes += list("Desert")
Good point

2021-10-19 15:21 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +		if(-INFINITY to 1)
Max will return 1 at least

2021-10-19 15:21 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +			if(istype(diseasesource, /mob/living/simple_animal/pet/hamster/vector))
Check .type and compare strings

2021-10-19 20:31 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +				prefixes += list("Vermin ", "Zoo", "Maintenance ")
I'd suggest documenting it somewhere

2021-10-19 20:36 UTC, Archanial requested changes

2021-10-19 20:36 UTC, Archanial commented on code/datums/diseases/advance/advance.dm
> +			return "[body][suffix]"
```suggestion
	switch(rand(1, 3))
		if(1)
			return "[pick(prefixes)][pick(bodies)]"
		if(2)
			return "[pick(prefixes)][pick(bodies)][pick(suffixes)]"
		if(3)
			return "[pick(bodies)][pick(suffixes)]"
```

2021-10-20 01:33 UTC, zeskorion commented on code/datums/diseases/advance/advance.dm
> +		if(-INFINITY to 1)
Ah, i had a dumb brain

2021-10-20 09:55 UTC, Archanial requested changes

2021-10-20 09:55 UTC, Archanial commented on code/datums/diseases/advance/symptoms/fever.dm
> +		prefixes = list("Desert")
Instead of this make parent proc run prefixes = initial(prefixes)

2021-10-20 19:10 UTC, zeskorion commented on code/datums/diseases/advance/symptoms/fever.dm
> +		prefixes = list("Desert")
This instance has no prefix list

2021-10-20 20:30 UTC, Archanial commented on code/datums/diseases/advance/symptoms/fever.dm
> +		prefixes = list("Desert")
It applied to every disease.
If resistance drops names will not clear.
It's just easier and more convenient to set that stuff to initial in parent proc.

2021-10-20 23:05 UTC, zeskorion commented on code/datums/diseases/advance/symptoms/fever.dm
> +		prefixes = list("Desert")
Thats fair. When i get home, then

2021-10-21 05:29 UTC, Archanial approved these changes

2021-10-21 14:16 UTC, zeskorion commented
~~now to go pester other maints with this cuz its my favorite pr of this batch so far~~

2021-10-21 18:45 UTC, francinum approved these changes
Go on then.

2021-10-21 18:45 UTC, merged