Nitrile and latex gloves reduce firefighter carry delay
BeeStation/BeeStation-Hornet pull request #559
Opened 2019-10-15 10:07 UTC by Cenrus

## About The Pull Request

Wearing nitrile or latex gloves reduces the time it takes to fireman carry a player.

it takes ages to lift people up, and in an emergency that can really heck your day. now it's faster with latex or nitrile gloves. The latex gloves sprite is bugged and won't show on your hands, I would appreciate someone looking into this.

## Changelog

:cl:
add: Halved firefight carry delay with latex or nitrile gloves
/:cl:

2019-10-15 17:21 UTC, jlsnow301 commented
Might convince people to actually carry them rather than bleed them across the entire hallway

2019-10-15 20:18 UTC, ike709 commented on code/modules/clothing/gloves/color.dm
> +	REMOVE_TRAIT(user, carrytrait, CLOTHING_TRAIT)
You need to make a `Destroy()` subtype as well with similar functionality.

2019-10-15 20:20 UTC, ike709 commented on code/modules/clothing/gloves/color.dm
> +	desc = "Pricy sterile gloves that are thicker than latex. Transfers intimate paramedic knowledge into the user via nanochips."
As someone who regularly works with both types of gloves, `stronger` would technically be more correct. Nitrile gloves are still paper thin, they're just a sturdier material.

2019-10-15 20:21 UTC, ike709 commented on code/modules/mob/living/carbon/human/human.dm
> +	var/skills_space = "" //cobby told me to do this
> cobby

Is this an uncredited TG port?

2019-10-15 20:30 UTC, ike709 commented on code/modules/mob/living/carbon/human/human.dm
> +		"<span class='notice'>[carrydelay < 35 ? "Using your gloves' nanochips, you" : "You"] [skills_space] start to lift [target] onto your back[carrydelay == 40 ? ", while assisted by the nanochips in y
```suggestion
		"<span class='notice'>[HAS_TRAIT(src, TRAIT_QUICKER_CARRY) ? "Using your gloves' nanochips, you" : "You"] [skills_space] start to lift [target] onto your back[HAS_TRAIT(src, TRAIT_QUICK_CARRY) ? ", while assisted by the nanochips in your gloves.." : "..."]</span>")
```

2019-10-15 20:31 UTC, ike709 commented on code/modules/clothing/gloves/color.dm
> -	item_state = "lgloves"
What's with the random icon change?

2019-10-15 20:31 UTC, ike709 requested changes
Address the things.

2019-11-02 23:51 UTC, ike709 commented
Stale.

2019-11-02 23:51 UTC, closed without merging