death nettle nerf
BeeStation/BeeStation-Hornet pull request #5591
Opened 2021-10-21 03:18 UTC by zeskorion

## About The Pull Request
death nettle has been nerfed to be at a more station-centric power level- at max potency, it is a fireaxe sidegrade with 25 damage and 12 throwforce, one handed, that cannot penetrate thick clothing, and no random stun
both nettles have had their acid levels nerfed by half as well, due to how easy to produce they are

## Why It's Good For The Game
death nettles have up to 45 damage, 20% chance to stun, and 100% chance to drop all items on hit at the moment, as well as being thrown to apply massive amounts (up to around 50) of fluorosulfiric acid, all while being able to be produced in massive numbers by botanists. this brings them down to non-antag station levels. 

if this is too much of a nerf, ill take feedback from maintainers

## Changelog
:cl:
balance: nerfs death nettles. they are now no more powerful than a fire axe
/:cl:

2021-10-21 03:22 UTC, BrumalLake commented on code/modules/hydroponics/grown/nettle.dm
> +	if(M.can_inject(user)
unpaired 😢

2021-10-21 15:01 UTC, Archanial requested changes

2021-10-21 15:01 UTC, Archanial commented on code/modules/hydroponics/grown/nettle.dm
> +		return ..()
doesn't parrent actually run hitting code and check for things like range?
```suggestion
/obj/item/reagent_containers/food/snacks/grown/nettle/death/attack(mob/living/M, mob/user)
	if(!..())
		return
	if(M.can_inject(user))
		return FALSE
```

2021-10-21 16:29 UTC, zeskorion commented on code/modules/hydroponics/grown/nettle.dm
> +		return ..()
Will check when home

2021-10-22 03:04 UTC, zeskorion commented on code/modules/hydroponics/grown/nettle.dm
> +		return ..()
no, this is not how the attack proc works. i did make a mistake though, and  i rectified it

2021-10-26 07:34 UTC, Wilchenx commented
>both nettles have had their acid levels nerfed by half as well

doesn't that basically do nothing as all plants are also reagent containers, so you can essentially fill them up with syringes?

2021-10-27 07:24 UTC, Archanial approved these changes

2021-10-30 05:34 UTC, zeskorion commented
> > both nettles have had their acid levels nerfed by half as well
> 
> doesn't that basically do nothing as all plants are also reagent containers, so you can essentially fill them up with syringes?

it makes them harder to function as mass produced armor deleting throwing weapons

2021-11-02 16:22 UTC, PerishedFraud commented
Remove the nettle completely. There's no reason for a botanist to have it to begin with. Remove lemon bombs too.  If people want to weaponize botany at least force them to be creative.

2021-11-04 07:05 UTC, MrLostman commented
![333](https://user-images.githubusercontent.com/50007631/140271474-db4a156d-379e-40e0-ad20-b37fd5bb365b.jpg)

2021-11-11 21:13 UTC, Archanial approved these changes

2021-11-11 21:19 UTC, francinum approved these changes

2021-11-11 21:19 UTC, merged