Makes ash heretic immune to fire
BeeStation/BeeStation-Hornet pull request #5594
Opened 2021-10-21 13:59 UTC by FriendlyContractor

## About The Pull Request
Makes ash path heretic immune to being set on fire

## Why It's Good For The Game
People always bump into you in combat and end up seting you on fire as well which makes ash abilities allowing you to set others on fire a hinderance rather than uselfull ability. This tiny PR fixes it
## Changelog
:cl:
tweak: Ash heretics immune to being set on fire
/:cl:

2021-10-21 15:02 UTC, Archanial requested changes

2021-10-21 15:02 UTC, Archanial commented on code/modules/antagonists/eldritch_cult/knowledge/ash_lore.dm
> +	ADD_TRAIT( user, TRAIT_NOFIRE,MAGIC_TRAIT)
clear this on loss

2021-10-21 16:45 UTC, FriendlyContractor commented on code/modules/antagonists/eldritch_cult/knowledge/ash_lore.dm
> +	ADD_TRAIT( user, TRAIT_NOFIRE,MAGIC_TRAIT)
Fixed. Tested in game and works as intended

2021-10-22 02:17 UTC, zeskorion commented
they shouldnt get fire immunity as a basic trait

2021-10-22 13:21 UTC, FriendlyContractor commented
> 
> 
> they shouldnt get fire immunity as a basic trait

It fits with their fire themed lore nicely and most importantly as i mentioned when they get fiery blade upgrade which makes blade ignite people on hit those people inavoidably end up bumping into you and transfering portion of their flames to you which ultimately feels like this ability is a downgrade rather than something uselfull. We already have roundstart race which is immune to being set on fire and it has not been impacting the game negatively

2021-10-23 12:04 UTC, ItsTisme commented
wont there clothing burn still? randomly dropping everything on you still sounds like a huge draw back

2021-10-23 13:19 UTC, FriendlyContractor commented
> 
> 
> wont there clothing burn still? randomly dropping everything on you still sounds like a huge draw back

No - worn clothes cannot burn. I also tested this in game to make double sure and it checks out

2021-10-24 05:18 UTC, Howluinb commented
Did you make it so that they would still need to ascend in order to be immune to high pressure? It would prevent grief, to some degree, as they would not be able to plasmaflood - only fight with fire.

2021-10-24 12:44 UTC, BrumalLake commented
is this the trait that makes them instantly get extinguished cause that's a little conspicuous
and this should be on mark of ash since that's when they can actually start igniting people

2021-10-24 13:56 UTC, FriendlyContractor commented
> 
> 
> Did you make it so that they would still need to ascend in order to be immune to high pressure? It would prevent grief, to some degree, as they would not be able to plasmaflood - only fight with fire.

The only thing it protects from is being set on fire. It doest not protect from pressure or heat

2021-10-27 07:23 UTC, Archanial approved these changes

2021-10-27 07:23 UTC, merged