Adds Apple Fritters
BeeStation/BeeStation-Hornet pull request #5629
Opened 2021-10-27 00:39 UTC by TeomanTheGreat

## About The Pull Request
Adds apple fritters. **Apple Fritter sprite by Kate Bishop** 

## Why It's Good For The Game
Apple fritters taste good and add more variety to what you see on the kitchen counter

## Changelog
:cl: Phil Smith
add: Apple fritters. 
/:cl:

2021-10-27 01:18 UTC, BrumalLake commented
bath salts but for botanists with minimal recoil

2021-10-27 01:25 UTC, Kapu1178 requested changes

2021-10-27 01:25 UTC, Kapu1178 commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +	M.health += 100
No.

2021-10-27 01:30 UTC, TeomanTheGreat commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +	M.health += 100
it lasts for like 4 seconds (or how much time it takes to metabolize the units in the fritters) and takes it away

2021-10-27 01:37 UTC, TeomanTheGreat commented
> 
> 
> bath salts but for botanists with minimal recoil

its very easy to get fat eating these things so don't expect to be able to chow down a bunch of the stuff and have a bunch of frittonium in your body

2021-10-27 01:45 UTC, zeskorion commented
Ugh this is dumb for a meme. This literally doubles your crit threshold

Meme code is bloody stupid

2021-10-27 02:12 UTC, BrumalLake commented
i'm pretty sure it takes 20 seconds to metabolize 5 units even more when you're hungry as it's a consumable reagent and even longer with our average 60% td
just to get knocked down for 6 seconds regardless of how much you ate and there are a few species that can't get fat

2021-10-27 02:21 UTC, TeomanTheGreat commented
> 
> 
> i'm pretty sure it takes 20 seconds to metabolize 5 units even more when you're hungry as it's a consumable reagent and even longer with our average 60% td just to get knocked down for 6 seconds regardless of how much you ate and there are a few species that can't get fat

ah that's right kinda forgot about those guys. oops. Have any ideas on how I can make this less busted while still being entertaining as a meme item?

2021-10-27 03:05 UTC, TeomanTheGreat commented
> you're not gonna mediate this by saying that certain species not being able to get fat is the only problem with having double health

Double health for a very small time. I did test it and it didnt last all too long without it stopping. If this were to be going on during a fight then your opponent who ate this stuff wont be getting very far as soon as it wears off and all the damage they endured comes back to kick them in the ass. And plus you know the stam damage.

2021-10-27 03:11 UTC, BrumalLake commented
aw man 6 seconds of down time when botanists can pack hundreds of units lasting minutes
you're right

2021-10-27 03:15 UTC, TeomanTheGreat commented
> aw man 6 seconds of down time when botanists can pack hundreds of units lasting minutes
> you're right

Im sure you can cram quite a few of the plates in your bag or a tray but I'm not sure about eating it during battle especially when your being shot and or attacked back by whoever you were trying to rush after eating these. Also the ingredients require pastry base and the oil from the chefs oil tank so atleast they need to get the chef with them.

2021-10-27 03:27 UTC, BrumalLake commented
wait this is about fritonium and you're talking about eating making you fat
i was taking about injecting pure fritonium this whole time
you won't even get fat like you said and you don't have to stand still to do it either
the recipe isn't that difficult
i don't believe that interaction with a sentient being in the room next to you gives a green light to have double health
i believe you can get the oil and eggs without them anyways

2021-10-27 03:34 UTC, TeomanTheGreat commented
> i was taking about injecting pure fritonium this whole time



Oh. Now that i think about it i forgot to blacklist this on the random shit that botanists can add to plants. My mistake ill fix that right now.

2021-10-27 03:36 UTC, TeomanTheGreat commented
> 
> 
> wait this is about fritonium and you're talking about eating making you fat i was taking about injecting pure fritonium this whole time you won't even get fat like you said and you don't have to stand still to do it either the recipe isn't that difficult i don't believe that interaction with a sentient being in the room next to you gives a green light to have double health i believe you can get the oil and eggs without them anyways

oh also I know this isn't my place to ask you this since this is my pr but do you have any suggestions of what I can add to the recipe to make this harder to obtain without it being stupidly difficult. Its like 11 pm where I am and I didn't get much sleep last night so my thinking isn't exactly on normal levels.

2021-10-27 03:38 UTC, BrumalLake commented
if you put food in a multi mixer and press the button labeled grind a magical substance comes out nevertheless
and i don't believe in making it harder to get just cause it's broken
it should be the other way around

2021-10-27 03:39 UTC, TeomanTheGreat commented
> if you put food in a multi mixer and press the button labeled grind a magical substance comes out nevertheless

Aww man you didn't read everything in the pr didn't you. Its set to ungrindable exactly to prevent people from cheesing it.

2021-10-27 03:41 UTC, BrumalLake commented
yeah sorry for not scouring every line of code to see if you were trying to stealth remove pulse slugs again

2021-10-27 03:45 UTC, TeomanTheGreat commented
> yeah sorry for not scouring every line of code to see if you were trying to stealth remove pulse slugs again

Do i have to explain it to you again. That was a fuckup in my commit history because i was a dumbass. Also this pr isnt even that long lol.

2021-10-27 03:49 UTC, BrumalLake commented
that was a joke lads
i didn't even make a review you can't tell if i read it or not but i did skim
it should at least be in the description of a pr adding something far past the edge

2021-10-27 03:54 UTC, TeomanTheGreat commented
> that was a joke lads

Hard to tell whats not a joke and what is when its on a github pr comment section

> it should at least be in the description of a pr adding something far past the edge

Done

2021-10-27 06:29 UTC, Archanial requested changes

2021-10-27 06:29 UTC, Archanial commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +/datum/reagent/consumable/frittonium // literally stronger brave bull (with a side effect) and with zero tactical use unless you manage to eat it during a fight in which you will collapse seconds lat
Remove this

2021-10-27 07:26 UTC, ItsTisme commented
Add a OD threshold, or do the thing most chems do where after X amount of ticks the bad sides creep up. Bassicly a hardcap on how long this effect lasts. Double health + any good armor is going to be pain to deal with

2021-10-27 11:25 UTC, Vexylius commented
Adding content just for the meme is not a good idea

2021-10-27 15:56 UTC, TeomanTheGreat commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +/datum/reagent/consumable/frittonium // literally stronger brave bull (with a side effect) and with zero tactical use unless you manage to eat it during a fight in which you will collapse seconds lat
The comment or the chem itself

2021-10-27 16:28 UTC, TeomanTheGreat commented
All right max health is lowered to 40 and there is an overdose effect now.

2021-10-27 16:37 UTC, Tsar-Salat commented
> All right max health is lowered to 40 and there is an overdose effect now.

Imagine going to the bakery and you see a guy overdose on _**Apple Fucking Fritters**_

2021-10-27 17:33 UTC, Archanial commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +/datum/reagent/consumable/frittonium // literally stronger brave bull (with a side effect) and with zero tactical use unless you manage to eat it during a fight in which you will collapse seconds lat
Chem itself

2021-10-27 17:36 UTC, TeomanTheGreat commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +/datum/reagent/consumable/frittonium // literally stronger brave bull (with a side effect) and with zero tactical use unless you manage to eat it during a fight in which you will collapse seconds lat
i mean considering i just nerfed it even further I would say its not necessary at the moment. Feel free to state your new opinion if you have one. If you still hate it ill get rid of it.

2021-10-27 17:42 UTC, Isy232 commented
> All right max health is lowered to 40 and there is an overdose effect now.

@TeomanTheGreat Adding features like +40 health for eating a food is an LRP mechanic. How the fuck are you supposed to say "Eating this gives me more health" IC, it just makes no sense.

I would say make Apple Fritters give a large amount of positive mood, which IIRC DOES impact crit threshold, so it would give you part of the meme mechanic without any problems.

2021-10-27 17:54 UTC, Kapu1178 requested changes

2021-10-27 17:54 UTC, Kapu1178 commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +	M.health = min(M.health - 40, M.maxHealth) // this can indeed kill someone if they took a lot of damage during the fritter metabolization
This is fucking stupid. It bypasses a ton of damage systems in the game, use take_overall_damage() or adjustToxLoss()

2021-10-27 18:02 UTC, TeomanTheGreat commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +	M.health = min(M.health - 40, M.maxHealth) // this can indeed kill someone if they took a lot of damage during the fritter metabolization
No longer relevant

2021-10-27 18:02 UTC, TeomanTheGreat commented
Fritters now add mood instead of health

2021-10-27 18:03 UTC, TeomanTheGreat commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +/datum/reagent/consumable/frittonium // literally stronger brave bull (with a side effect) and with zero tactical use unless you manage to eat it during a fight in which you will collapse seconds lat
no longer relevant. fritters now add mood.

2021-10-27 18:03 UTC, TeomanTheGreat commented
> 
> 
> > All right max health is lowered to 40 and there is an overdose effect now.
> 
> @TeomanTheGreat Adding features like +40 health for eating a food is an LRP mechanic. How the fuck are you supposed to say "Eating this gives me more health" IC, it just makes no sense.
> 
> I would say make Apple Fritters give a large amount of positive mood, which IIRC DOES impact crit threshold, so it would give you part of the meme mechanic without any problems.

done

2021-10-28 00:41 UTC, BrumalLake commented
please stop using the "makes no sense" argument 🤮 it doesn't even make no sense in this case either

2021-10-28 07:01 UTC, Crossedfall commented
I like how your CL entry explicitly names you, but you didn't add in the credits for Kate. 😔

As for the change itself, it's a "funny" meme but the actual content is pretty weak. 🔑

2021-10-28 07:10 UTC, francinum commented
This code's a mess, overrides species tastes without doing so properly, you can end up being disgusted but also 'loving it' at the same time.
🗝️

2021-10-28 07:10 UTC, closed without merging

2022-03-16 09:59 UTC, Zanara04 commented
:)