Det's starting revolver and ammo are now MOSTLY non-lethal (and adds new .38 rubber bullets)
BeeStation/BeeStation-Hornet pull request #5646
Opened 2021-10-28 20:10 UTC by TeomanTheGreat

## About The Pull Request
Det now starts with rubber bullets instead of their lethal ones.

## Why It's Good For The Game
Detectives (as per the sop) shouldn't be performing arrests and them having lethal rounds just encourages them to blast people (which they already do). Mostly non-lethal rounds should fix this problem to an extent and it takes above 2 full clips plus what's already starting in the revolver to kill someone with these new rounds.

## Changelog
:cl: Phil Smith
balance: Detective's now start with rubber/bouncy rubber revolver bullets in their gun and shoulder holster
/:cl:

2021-10-28 20:50 UTC, Archanial commented
I love how we ported AI datums but then didn't port any features associated with it nor fixes

2021-10-28 21:03 UTC, FriendlyContractor commented
Making detectives weapon non-lethal will not discourage detective from performing arrests at all. Also dying doesnt matter in this game you can always be quickly fixed up with no consequences

2021-10-28 21:50 UTC, mcmeiler commented
Seems like a duplicate. We can already make rubber shots at autolathes. Just that detective players ~~have no idea how to use an autolathe~~ forget to print them and instead use lethals.
- #4504

2021-10-28 22:49 UTC, TeomanTheGreat commented
> Seems like a duplicate. We can already make rubber shots at autolathes. Just that detective players ~~have no idea how to use an autolathe~~ forget to print them and instead use lethals.
> - #4504 

Those are called rubber shot yet they are also bouncy according to the code. This is just rubber shot with no bounce and given to the det roundstart.

2021-10-28 22:58 UTC, TeomanTheGreat commented
> Making detectives weapon non-lethal will not discourage detective from performing arrests at all. Also dying doesnt matter in this game you can always be quickly fixed up with no consequences

Are you saying that dets should have lethal in the first place? Because the gun is only for self defense and frankly when det is doing det shit there is no need for him to blast his opponent to smithereens when he can just knock them down with this and cuff em (I would imagine they can arrest a person who just tried to murder them)

2021-10-28 23:32 UTC, FriendlyContractor commented
Im saying that your intentions seems to be having detective arrest people less( frankly this whole thing with detective not  supposed to arrest people and being "lesser security" is nonsense but thats for another discussion)  but what you propose is gonna have opposite effect

2021-10-28 23:52 UTC, BrumalLake requested changes
identical to bouncy without the ricochet
you should make either a child

2021-10-28 23:58 UTC, TeomanTheGreat commented
> identical to bouncy without the ricochet
> you should make either a child

Aight (i dont have much freetime atm but ill get to it when i do)

2021-10-28 23:59 UTC, Raven-Industries commented
The opinion of someone who plays det reasonably often: I'm going to be more tempted to make arrests or otherwise 'intervene' if my roundstart ammunition is nonlethals. As it is now, I generally stay hands off because I know that the only real recourse I have is lethals, and since you need solid justification to use them, it means my options are limited. Can't make average arrests, because your only real stopping power also kills them, and that would be overescalation. Can't do searches, because the only way you have to enforce that is your trusty revolver, which you can't use unless they start hacking limbs off. As it stands now, with lethals, I find myself roleplaying more to handle situations because of that restriction (oftentimes I find that I hold to that restriction a little _too_ much and end up dead because of my reluctance to use said revolver).

2021-10-29 03:44 UTC, zeskorion commented
> > Seems like a duplicate. We can already make rubber shots at autolathes. Just that detective players ~have no idea how to use an autolathe~ forget to print them and instead use lethals.
> > 
> > * [Adds .38 Rubbers To Autolathes #4504](https://github.com/BeeStation/BeeStation-Hornet/pull/4504)
> 
> Those are called rubber shot yet they are also bouncy according to the code. This is just rubber shot with no bounce and given to the det roundstart.

just give det these and dont add a new one

2021-10-29 15:16 UTC, mcmeiler commented
> I'm going to be more tempted to make arrests
> Can't do searches

I won't get into a rules discussion here but as dictated per SOP, detectives aren't allowed to perform arrests and searches *at all* under normal conditions, i.e. green and blue alert and a present security force

2021-10-29 20:17 UTC, TeomanTheGreat commented
> 
> 
> identical to bouncy without the ricochet you should make either a child

Done

2021-10-29 20:49 UTC, Crossedfall requested changes
Remove the new ammo type and just give them the pre-existing ammo. The path "bouncy" doesn't actually mean they're bouncy. In the original PR they were going to have a ricochet of 6, but it was reset back to 1 before being merged. (They do have a high chance to ricochet though, to be fair.. It's still just once though)

2021-10-30 15:34 UTC, Raven-Industries commented
> > I'm going to be more tempted to make arrests
> > Can't do searches
> 
> I won't get into a rules discussion here but as dictated per SOP, detectives aren't allowed to perform arrests and searches _at all_ under normal conditions, i.e. green and blue alert and a present security force
You're right, but my point is that the temptation to just step in _just that once_ and do something is there. I think that temptation would be much greater when you have easy access to a non-lethal option, where it's easier to justify using it because "it won't injure them or anything". Having a purely lethal weapon, in my opinion, forces you to avoid that sort of thing, and RP your way around things rather than disabler-blast a path to your goal.

2021-10-30 16:20 UTC, 4rchibald commented
Detective is not a better looking security officer, they should not be doing arrests unless it is absolutely necessary. Their job is to investigate, because of that they are often in dangerous places and dealing with dangerous people hence they were issued gun permit for self defence, to be used only in immediate physical threat to them.
This is according to lore and SOP, we just need admins putting more pressure on detectives and heads to enforce it instead of making detective into officer. If there is will to merge this PR then we should simply remove detective and add one more slot in security

2021-10-30 18:12 UTC, TeomanTheGreat commented
> Detective is not a better looking security officer, they should not be doing arrests unless it is absolutely necessary. Their job is to investigate, because of that they are often in dangerous places and dealing with dangerous people hence they were issued gun permit for self defence, to be used only in immediate physical threat to them.
> This is according to lore and SOP, we just need admins putting more pressure on detectives and heads to enforce it instead of making detective into officer. If there is will to merge this PR then we should simply remove detective and add one more slot in security 

You can still stop threats to yourself by doing stam damage you know.

2021-11-02 06:42 UTC, Dawson1917 commented
Detective becomes less of a unique role from security officer every time this kind of change makes it through. If their equipment just becomes reskinned or subpar sec gear then there's no reason to play as a detective when you can just go sec officer and ask for or print a forensic scanner to be a better-geared detective. Giving them nonlethals doesn't add to their job, it's just balancing it around shitters who use lethals when they explicitly aren't supposed to, both IC and as per server rules.

As others have said, not having a nonlethal ranged option (and a subpar melee nonlethal in the form of the wooden baton) makes you play situations differently than you would as a sec officer; you often need people to voluntary let you search or detain them if you try to make an arrest or collect evidence, because the alternative is gunning them down without due cause and getting yourself in trouble with Security or the administration. Having a nonlethal weapon means you can play exactly like a shit sec officer by stunning suspects and rifling through their inventory instead of needing to RP or play smart to do your job.

In addition I don't think it should be possible to print more ammo for the detective's revolver, lethal or nonlethal. Especially speedloaders. Their gun and ammunition should be treated as a valuable (dangerous) and limited resource, not something you can use on a whim and just print more of from the seclathe.

2021-11-10 22:20 UTC, TeomanTheGreat commented
Well, that was painful. Now I wonder why this is conflicting.

2021-11-10 22:35 UTC, TeomanTheGreat commented
based!

2021-11-10 22:46 UTC, Archanial commented on code/modules/research/techweb/all_nodes.dm
> +	"space_heater", "beaker", "large_beaker", "bucket", "xlarge_beaker", "sec_rshot", "sec_beanbag_slug", "sec_bshot", "sec_slug", "sec_Islug", "sec_Brslug", "sec_dart", "sec_38" "sec_38b",
```suggestion
	"space_heater", "beaker", "large_beaker", "bucket", "xlarge_beaker", "sec_rshot", "sec_beanbag_slug", "sec_bshot", "sec_slug", "sec_Islug", "sec_Brslug", "sec_dart", "sec_38", "sec_38b",
```

2022-01-02 21:10 UTC, PowerfulBacon submitted a review, later dismissed
Use a regular rubber type rather than the bouncy bullets

2022-01-03 21:06 UTC, PowerfulBacon requested changes
Apparently the bouncy bullets are bouncy, I'd rather you used non-bouncy bullets.

2022-01-03 21:10 UTC, merged