Circuit imprinters work without consoles
BeeStation/BeeStation-Hornet pull request #5676
Opened 2021-11-01 22:08 UTC by Archanial

## About The Pull Request

Title + adds special engineering circuit imprinter
## Why It's Good For The Game

## Changelog
:cl:
add: Cirucit imprinters work without consoles
add: Special circuit imprinter subtype for engineering
/:cl:

2021-11-01 22:53 UTC, KubeRoot requested changes

2021-11-01 22:53 UTC, KubeRoot commented on code/modules/research/machinery/departmental_circuit_imprinter.dm
> +	circuit = /obj/item/circuitboard/machine/circuit_imprinter/department/science
This should have a different circuit

2021-11-01 22:56 UTC, KubeRoot commented on code/modules/research/machinery/departmental_circuit_imprinter.dm
> +	circuit = /obj/item/circuitboard/machine/circuit_imprinter/department/science
In fact, the name is also wrong? Not sure if it's actually used in-game, but it should be changed at least for the editor.

And are you sure about the department flags?

2021-11-01 23:27 UTC, KubeRoot commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> +	icon_state = "science"
```suggestion
	icon_state = "engineering"
```

2021-11-01 23:30 UTC, lordScrubling commented
this pr just expired with https://github.com/BeeStation/BeeStation-Hornet/pull/5675

2021-11-02 00:03 UTC, KubeRoot commented
I would recommend renaming the PR and updating the description to match the current state, since it no longer affects the ability to access circuit imprinters and only adds the engineering circuit imprinter.

2021-11-27 23:32 UTC, francinum requested changes
Engineering is not getting a free autolathe.

2021-11-27 23:38 UTC, francinum commented
PR body has insufficient information and insufficient justification for alteration.

2021-11-27 23:39 UTC, Archanial commented
PR body has been updated

2021-11-27 23:40 UTC, francinum approved these changes

2021-11-27 23:44 UTC, merged