Bunny ears now adapt to the hair color of the wearer
BeeStation/BeeStation-Hornet pull request #5736
Opened 2021-11-07 20:16 UTC by ivanmixo

## About The Pull Request

Title. Same behavior as kitty ears. They're a subtype to avoid copypaste code.

## Why It's Good For The Game

Why not have them adapt to the wearer's hair color?

## Changelog
:cl:
add: Rabbit ears now adapt to the wearer's hairstyle like kitty ears do
/:cl:

2021-11-07 20:49 UTC, francinum commented
~~It'd probably be best for you to make them both a subtype of an abstract 'hairmatch' clothing object, or move the behavior to a component.~~

2021-11-07 20:57 UTC, ivanmixo commented
I could do a component I guess, might as well.

2021-11-07 21:55 UTC, Effemu commented
![obraz](https://user-images.githubusercontent.com/71228581/140663268-9ba6d194-84c0-4901-beec-7006139a2dc5.png)

You will be punished for your sins.

2021-11-07 22:14 UTC, ivanmixo commented
> ~It'd probably be best for you to make them both a subtype of an abstract 'hairmatch' clothing object, or move the behavior to a component.~

Done

2021-11-07 23:48 UTC, Wilchenx commented
gateway to adding viera

2021-11-08 08:46 UTC, ivanmixo commented
> <!-- Write **BELOW** The Headers and **ABOVE** The comments else it may not be viewable. -->
> <!-- You can view Contributing.MD for a detailed description of the pull request process. -->
> 
> ## About The Pull Request
> 
> Title. Moved the kitty and bunny ear functionality to a component.
> 
> <!-- Describe The Pull Request. Please be sure every change is documented or this can delay review and even discourage maintainers from merging your PR! -->
> 
> ## Why It's Good For The Game
> 
> Why not have them adapt to the wearer's hair color?
> 
> <!-- Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding. -->
> 
> ## Changelog
> :cl:
> add: Rabbit ears now adapt to the wearer's hairstyle like kitty ears do
> /:cl:
> 
> <!-- Both :cl:'s are required for the changelog to work! You can put your name to the right of the first :cl: if you want to overwrite your GitHub username as author ingame. -->
> <!-- You can use multiple of the same prefix (they're only used for the icon ingame) and delete the unneeded ones. Despite some of the tags, changelogs should generally represent how a player might be affected by the changes rather than a summary of the PR's contents. -->
>

2021-11-08 23:21 UTC, francinum submitted a review, later dismissed

2021-11-10 07:39 UTC, bluezorua commented
> gateway to adding viera

stop using weeb words and say bunnygirls like a normal person

2021-11-10 09:36 UTC, Archanial requested changes, later dismissed

2021-11-10 09:36 UTC, Archanial commented on code/datums/components/haircolor_clothes.dm
> +    RegisterSignal(parent, COMSIG_ATOM_UPDATE_ICON, .proc/update_color)
unregister on remove

2021-11-21 02:32 UTC, ivanmixo commented on code/datums/components/haircolor_clothes.dm
> +    RegisterSignal(parent, COMSIG_ATOM_UPDATE_ICON, .proc/update_color)
Look at `datum/Destroy()` please

2021-11-23 02:51 UTC, francinum commented
I'm not sure if the destruction thing needs to be touched.

2021-11-23 10:01 UTC, ivanmixo commented
99% sure `datum/Destroy()` clears all the signals and components' signals anyways. Don't think I need to manually unregister them.

2021-11-23 23:35 UTC, francinum commented
Signal refs and all attached components are automatically garbage collected as part of datum level destroy. Handling it yourself is nice for cleanliness.

2021-11-23 23:35 UTC, francinum approved these changes

2021-11-23 23:46 UTC, merged