Removes teratomas
BeeStation/BeeStation-Hornet pull request #5739
Opened 2021-11-07 23:03 UTC by ivanmixo

## About The Pull Request

Title. Someone should probably fill in the void this leaves in ling abilites. 😉 

## Why It's Good For The Game

Teratomas are a thing lings can infinitely spawn and the rules allow them to do basically whatever they like in the name of "causing chaos". Being able to just infinitely create antags with no real resources required isn't great, either. I don't think anyone enjoys fighting them or being one.

![image](https://user-images.githubusercontent.com/22431091/140665158-e0269ee7-a716-44e0-aa05-8fcc0b3b7b71.png)

## Changelog
:cl:
del: Removed teratomas
/:cl:

2021-11-07 23:05 UTC, zeskorion commented
could you kindly hold off on this pr until gh#5624 is resolved? I plan to totally rework tomas into a simplemob instead of a monkey, im just waiting on that pr for icon conflict reasons

2021-11-07 23:28 UTC, Wilchenx commented
ided

2021-11-08 00:01 UTC, zeskorion requested changes

2021-11-08 00:01 UTC, zeskorion commented on code/datums/diseases/advance/symptoms/heal.dm
> -						if(A.affected_mob.job == "Clown")
can you not remove the organ spawns from the symptom? read the code you're removing, please?

2021-11-08 16:04 UTC, Effemu commented
cope ivan

2021-11-08 17:19 UTC, Archanial commented
Issues with teratomas:
- they need absorbs which encourages random murders, and that colides with rules somewhat
- they are spammable

How to solve it:
They don't need to be simplemobs. It's much funnier to be a monkey than a simplemob. Just make it an ability which you can purchase multiple times and each time you do that, you could produce one of the teratomas, which have some sort of mind link to you (or you just understand them) and can possibly be DNA stung to make you somesort of makeshift BB. Of course cost should be adjusted to match their power.

2021-11-08 18:36 UTC, zeskorion commented
As the person who added the things in the first place, making them a special simplemob that exists primarily as a nuisance is a better solution. It lets them exist without ghosts, and restricts their capabilities

2021-11-09 01:04 UTC, francinum commented
@Archanial The simplemob idea is actually the result of an old discussion on the topic.
No matter what restrictions you think are 'reasonable' on them, the ability for changelings to in any way have the possibility of mass-manufacturing fully fledged carbon antagonists is a poor one.

The simplemob solution solves it and is considered acceptable by the original author.

2021-11-11 19:12 UTC, Glcbitj commented
Can't you just make it so there's a big cooldown like 20-30 minutes on spawning them, or make it so they required consumed genomes, like 1/toma. Will make them appear less frequently and probably not do suicidal things anymore.

2021-11-12 02:55 UTC, francinum commented
No.

2022-01-04 02:30 UTC, ivanmixo commented
uhhhhhhhhhh

2022-01-27 01:03 UTC, closed without merging