Cryopods use signals to handle objectives
BeeStation/BeeStation-Hornet pull request #5774
Opened 2021-11-13 05:16 UTC by TheChaser212

## About The Pull Request
Instead of looping through every objective whenever someone cryoes, a signal will be sent to any objectives that have that person as a target. Also makes team and crew objectives show up when announcing objectives and fixes crew objectives not being added to people at roundstart.

Probably needs to be testmerged.

## Why It's Good For The Game
Less shitcode, better performance.

## Changelog
:cl:
fix: Fixed crew objectives not being assigned at roundstart
refactor: Cryopods use signals to handle objectives instead of looping through every objective
/:cl:

2021-11-13 06:28 UTC, Kapu1178 commented
Why wasnt this done when DCS was added S M H

2022-01-21 10:03 UTC, Archanial commented on code/__HELPERS/roundend.dm
> +					for(var/datum/objective/CO in M.mind.crew_objectives)
What's the reason of this change? It's supposed to only handle crew objectives, which are different.

2022-01-21 10:03 UTC, Archanial commented on code/controllers/subsystem/job.dm
> +	var/list/crewobjjobs = list()
```suggestion
	var/list/crew_obj_list = list()
	var/list/crew_obj_jobs = list()
```

2022-01-21 10:03 UTC, Archanial commented on code/controllers/subsystem/job.dm
> +			crewobjjobs["[job]"] += list(obj)
```suggestion
			crewobjjobs["[job]"] += obj
```

2022-01-21 10:03 UTC, Archanial commented on code/datums/brain_damage/creepy_trauma.dm
> +	UnregisterSignal(obsession.mind, COMSIG_MIND_CRYOED)
unregister signal on removal of datum

2022-01-21 10:03 UTC, Archanial commented on code/datums/mind.dm
> +		for(var/datum/objective/objective in crew_objectives)
```suggestion
		for(var/datum/objective/objective as() in crew_objectives)
```

2022-01-21 10:03 UTC, Archanial commented on code/datums/mind.dm
> +		for(var/datum/objective/O in all_objectives)
```suggestion
		for(var/datum/objective/O as() in all_objectives)
```

2022-01-21 10:03 UTC, Archanial commented on code/datums/mind.dm
> +		for(var/datum/objective/C in crew_objectives)
```suggestion
		for(var/datum/objective/C as() in crew_objectives)
```

2022-01-21 10:03 UTC, Archanial commented on code/datums/mind.dm
> +	if(all_objectives.len)
crew objectives aren't included here?

2022-01-24 02:59 UTC, TheChaser212 commented on code/__HELPERS/roundend.dm
> +					for(var/datum/objective/CO in M.mind.crew_objectives)
There's no reason an admin couldn't add a normal objective to someone's crew objective list, this way it'd show up as completed.

2022-01-24 03:06 UTC, TheChaser212 commented on code/datums/mind.dm
> +	if(all_objectives.len)
I decided to keep them separate so they show up as optional and aren't numbered. I'll change the names so they make more sense.

2022-01-25 11:09 UTC, Archanial commented on code/__HELPERS/roundend.dm
> +					for(var/datum/objective/CO in M.mind.crew_objectives)
If there is no reason, revert this change. Also add as() since you don't have to check types here.

2022-01-25 11:59 UTC, TheChaser212 commented on code/__HELPERS/roundend.dm
> +					for(var/datum/objective/CO in M.mind.crew_objectives)
Okay done

2022-02-08 22:23 UTC, KubeRoot requested changes
Got a couple code nitpicks, looks good in general.

2022-02-08 22:23 UTC, KubeRoot commented on code/game/gamemodes/objective.dm
> +		M.announce_objectives()
If you're using conditional `R?.objectives -= src` here, why not do a proper `if` to also only print things when the antag datum is found?

2022-02-08 22:23 UTC, KubeRoot commented on code/game/gamemodes/objective.dm
> +	return ..() || !target || considered_alive(target, enforce_human = human_check) || (human_check == TRUE && brain_target)? brain_target?.suicided : FALSE
```suggestion
	return ..() || !target || considered_alive(target, enforce_human = human_check) || (human_check == TRUE && brain_target)? brain_target.suicided : FALSE
```

The null check shouldn't be necessary here, as you check `brain_target` just before in the `&&`.

2022-02-10 22:58 UTC, KubeRoot approved these changes

2022-02-10 22:59 UTC, merged