Notes and messages will not automatically expire
BeeStation/BeeStation-Hornet pull request #5871
Opened 2021-11-29 21:33 UTC by francinum

## Why It's Good For The Game
Note expiration is weird because it both is and isn't deletion, and has a very limited usecase.

## Changelog
:cl:
config: A new config has been added to make setting notes to expire a more intentional action.
/:cl:

2021-11-29 21:53 UTC, Archanial requested changes, later dismissed

2021-11-29 21:53 UTC, Archanial commented on code/modules/admin/sql_message_system.dm
>  	if(isnull(expiry))
else here

2021-11-29 21:55 UTC, Archanial approved these changes, later dismissed

2021-11-29 23:13 UTC, Crossedfall commented on code/controllers/configuration/entries/general.dm
> +
```suggestion
```

2021-11-30 00:49 UTC, Crossedfall approved these changes

2021-11-30 00:49 UTC, merged