BeeRT
BeeStation/BeeStation-Hornet pull request #589
Opened 2019-10-19 11:49 UTC by UwUPlusUwU

Adds Bee ERT.

## About The Pull Request

Adds two outfits, one hardsuit, and a new response team.

## Why It's Good For The Game

We're Beestation yet we don't have Bee-related content. This changes now.

## Changelog
:cl:
add: The Bee Response Team have arrived.
/:cl:

2019-10-19 11:49 UTC, UwUPlusUwU commented
I hope I fucking die, Qwert please smite me irl.

2019-10-19 14:52 UTC, SomeAngryMiner commented
mind if i ask why is there an alien mosin in here?

2019-10-19 14:54 UTC, UwUPlusUwU commented
Oh yeah, I forgot to take that out of the pack.
REEEEEEEEEEEEE

2019-10-19 18:53 UTC, qwertyquerty commented
You may not have a personal icon file. Please sort the icons out into where they should belong, and clean up your PR from the other junk

2019-10-19 23:05 UTC, MarkSuckerberg commented
I don't understand why all of this is in a separate directory... (and this is my personal opinion, I know it was a completely separate PR) the sharpened mop should be under spear.dm, the clothing should be under their respective .dm s (hardsuit.dm, ert.dm, etc.) I just don't like this form of semi-spaghettification, and don't see any need for it. Take this with a grain of salt though

2019-10-19 23:08 UTC, MarkSuckerberg requested changes

2019-10-19 23:08 UTC, MarkSuckerberg commented on code/modules/opo/bee.dm
> +/datum/ert/janitor
/datum/ert/janitor ?

2019-10-19 23:08 UTC, MarkSuckerberg commented on code/modules/opo/bee.dm
> +	icon = 'code/modules/opo/opo.dmi'
Make sure to update this when you move the icons.

2019-10-19 23:08 UTC, MarkSuckerberg commented on code/modules/opo/bee.dm
> +/datum/antagonist/ert/commander/bee
This should be in code/datums/ert.dm at the very least.

2019-10-20 03:17 UTC, UwUPlusUwU commented
Right, thanks.

2019-10-20 03:17 UTC, closed without merging

2019-10-20 08:37 UTC, despong commented on code/modules/opo/bee.dm
> +/datum/ert/janitor
janny ert