Logs Check Contents usage
BeeStation/BeeStation-Hornet pull request #5987
Opened 2021-12-18 03:54 UTC by Ivniinvi

## About The Pull Request
Usage of Check Contents is now logged, and the log shows what the contents were at the time of the check.

## Why It's Good For The Game
Far, far easier to process powergaming appeals now.

## Changelog
:cl:
admin: Contents are now logged when a Check Contents occurs
/:cl:

2021-12-19 02:35 UTC, ike709 commented on code/modules/admin/verbs/randomverbs.dm
> +	log_game("[key_name(usr)] checked the contents of [key_name(M)], which were [M.get_contents()]")
```suggestion
	log_admin("[key_name(usr)] checked the contents of [key_name(M)], which were [M.get_contents()]")
```

2021-12-19 02:36 UTC, ike709 commented
I'm not sure how I feel about dumping the entire contents into it. Also do you really need to call the proc a second time? You should just `jointext()` the list.

2021-12-23 12:34 UTC, Archanial requested changes

2021-12-23 12:34 UTC, Archanial commented on code/modules/admin/verbs/randomverbs.dm
> +	log_game("[key_name(usr)] checked the contents of [key_name(M)], which were [M.get_contents()]")
You are running get contents twice.

2021-12-23 17:34 UTC, ike709 commented on code/modules/admin/verbs/randomverbs.dm
> +	log_game("[key_name(usr)] checked the contents of [key_name(M)], which were [M.get_contents()]")
Dupe of my comment.

2022-01-03 23:24 UTC, ike709 commented
Stale. Address my comment.

2022-01-03 23:25 UTC, PowerfulBacon commented
Also printing the list directly won't work, it will just put /list into the log

2022-01-09 01:10 UTC, closed without merging