Adds living hour requirement for antags
BeeStation/BeeStation-Hornet pull request #5996
Opened 2021-12-19 04:46 UTC by Ivniinvi

## About The Pull Request
All roundstart antags now require a certain number of living hours. These have been classed into one of three categories:

Showrunner (Wizard, Nuclear Operative): 200 hours
Team (Head Revolutionary, Clockwork Cultist, Cultist, Incursionist (Roundstart Only)): 100 hours
All Other Roundstart Antags: 10 hours

## Why It's Good For The Game
Nukies that don't know which end of the C20-R points away from you are kinda dumb. Especially on a server where the primary round driver is antagonists.

## Changelog
:cl:
add: Antags now have living hour restrictions on rolling them.
/:cl:

2021-12-19 05:21 UTC, Kapu1178 commented
why is this a proc. just make it a macro. waste of CPU power.

2021-12-19 09:23 UTC, PowerfulBacon commented
holy shit 100 hours of playing before you can start to have some more fun? That's just insane.
If I was recommending servers for new players, a server with a 10 hour barrier for solo antags and 100 hour for anything else would be the second to last server I would recommend after the furry erp servers.

2021-12-19 10:28 UTC, TotallyNotChief commented
hahaha what

2021-12-19 11:41 UTC, Archanial commented
No way this gonna pass with 200 hours lol

2021-12-19 13:47 UTC, AnCopper commented
What the FUCK.

2021-12-19 16:13 UTC, Ivniinvi commented
I deliberately put these values in as extreme. I stand by the ten hour one, but the 100 and 200 ones were meant to probably be changed. I am trying to get the highest hour count that will pass review to be the final values.

However:
An experience I've witnessed:
Three nukies, one of them has 2000h, one has 147h and one has 189h. The 2000h one has to spend literally twenty minutes teaching the other nukies how guns and uplinks work. On arrival to the station, Mr. 147 blows himself up with a c4 and dies. Mr. 189 sets his jetpack as his internals, and dies. The 2000h player proceeds to carry the entire round with a discounted Mauler and win. Because of this 20m of explaining, there was practically nothing happening on the station for the first 25 minutes.

2021-12-19 16:16 UTC, Ivniinvi commented
Also re: Bacon, the 100h limit on non solo antags is only for the Roundstart ones. You can totally be converted regardless of hour count. This is solely to prevent cultists that do literally nothing, or shaft miner head revs that just take the shuttle roundstart. The only one that is 100% blocked until the 100h mark is Incursion.

2021-12-19 18:29 UTC, DatBoiTim commented
A 10/20/30 hour layout would be a bit more palatable.

Still weird that you can become a head before an antag...

2021-12-19 20:44 UTC, PowerfulBacon commented
> Also re: Bacon, the 100h limit on non solo antags is only for the Roundstart ones. You can totally be converted regardless of hour count. This is solely to prevent cultists that do literally nothing, or shaft miner head revs that just take the shuttle roundstart. The only one that is 100% blocked until the 100h mark is Incursion.

I mean yea, but it still takes 100 hours to become a head and 200 hours to become a nukie or a wizard. Something way better I could suggest would be some kind of antag progression / unlock system. Once you been traitor a few times, you unlock new antags to play etc.

2021-12-19 20:46 UTC, PowerfulBacon commented
> I deliberately put these values in as extreme. I stand by the ten hour one, but the 100 and 200 ones were meant to probably be changed. I am trying to get the highest hour count that will pass review to be the final values.
> 
> However: An experience I've witnessed: Three nukies, one of them has 2000h, one has 147h and one has 189h. The 2000h one has to spend literally twenty minutes teaching the other nukies how guns and uplinks work. On arrival to the station, Mr. 147 blows himself up with a c4 and dies. Mr. 189 sets his jetpack as his internals, and dies. The 2000h player proceeds to carry the entire round with a discounted Mauler and win. Because of this 20m of explaining, there was practically nothing happening on the station for the first 25 minutes.

Yea but this is one round, I have had a round where my entire team was new and we absolutely dominated the station since I just told the people to follow me and we stuck together. The one round where I was the only experienced player in a team of new players, I found it much better than having a team of experienced players since the new players listened and went along with our plan. We were in and out in about 5 minutes. (sure all but one of them died fighting sec off while I got away with the disk but they still were great teammates to have)

2021-12-20 13:31 UTC, Archanial requested changes
I see benefit of all antagonists having minimum time of maximum 10 hours.
Merge that second pr into this and set team antagonist leaders or roundstart roles to minimum 25h (revs, both cults, nukies).

2022-01-03 23:27 UTC, PowerfulBacon requested changes
I think only the team antags need hours of somewhere with 25 as an upper bound.

2022-01-09 01:10 UTC, closed without merging