Typing Indicator Improvements
BeeStation/BeeStation-Hornet pull request #6130
Opened 2022-01-06 20:17 UTC by Kapu1178

## About The Pull Request
See CL. Very simple.

## Why It's Good For The Game
Better looking and better functioning game

## Changelog
:cl:
add: All mobs can now have a typing indicator
imageadd: Typing Indicator is now animated
/:cl:

2022-01-06 20:31 UTC, PowerfulBacon commented
what does it look like now?

2022-01-06 20:34 UTC, Archanial requested changes
Pictures please

2022-01-06 20:41 UTC, Kapu1178 commented
![l4XG7w26vF](https://user-images.githubusercontent.com/75460809/148448863-9476c19d-d16c-4c9f-b7d0-7b1d80e8282a.gif)

2022-01-06 21:00 UTC, PowerfulBacon submitted a review, later dismissed

2022-01-08 13:01 UTC, KubeRoot requested changes

2022-01-08 13:01 UTC, KubeRoot commented on code/modules/mob/typing_indicator.dm
>  ///Human Typing Indicators///
Update the comment?

2022-01-08 13:01 UTC, KubeRoot commented on code/modules/client/verbs/input_box.dm
>  		winset(src, "[id]_macro_return", "parent=persist_[id]_macro;name=Return;command=\".winset \\\"[id].is-visible=false\\\"\"")
The `escape` macro in the else clause needs to have the input cleared too.

2022-01-08 13:01 UTC, KubeRoot commented on code/modules/client/verbs/input_box.dm
>  		winset(src, "[id].accept", "command=\".winset \\\"command=\\\"[accept_verb] \\\\\\\"\[\[[id].input.text as escaped\]\]\\\";[id].is-visible=false\\\"\"")
This needs to clear the input, otherwise it'll stick around if you press the OK button with your mouse.

2022-01-08 13:01 UTC, KubeRoot commented on code/modules/client/verbs/input_box.dm
> +		winset(src, "[id]_macro_return", "parent=persist_[id]_macro;name=Return;command=\".winset \\\"command=\\\"[cancel_verb]\\\";[id].is-visible=false\\\";[id].input.text=\\\"\\\"\"")
The `return` macro shouldn't need to clear the input, since it only runs when the input is already empty. Might not hurt to have it just in case, though.

2022-01-08 13:01 UTC, KubeRoot commented on code/modules/client/verbs/input_box.dm
>  		winset(src, "[id]_macro_return", "parent=persist_[id]_macro;name=Return;command=\".winset \\\"[id].is-visible=false\\\"\"")
I also just realised, the `else` clause doesn't give the `cancel` button any command, meaning it'll do nothing if there's no cancel verb - whoops, my fault!
Should probably do `winset(src, "[id].cancel", "command=\".winset \\\"[id].is-visible=false\\\"\"")` here

2022-01-08 13:06 UTC, KubeRoot commented
I have some concerns over how well this works with other mobs - both in terms of placement of the typing indicator, and if some mob might `cut_overlays` to remove all overlays - for example, the morph.

Also, generally, could you provide some screenshots of what it looks like with some other mobs this might affect? Like sentient animals, xenos, nar'sie and ratvar constructs. I wouldn't expect gifs, just pictures to show the placement.

2022-01-08 18:05 UTC, Kapu1178 commented
> I have some concerns over how well this works with other mobs - both in terms of placement of the typing indicator, and if some mob might `cut_overlays` to remove all overlays - for example, the morph.
> 
> Also, generally, could you provide some screenshots of what it looks like with some other mobs this might affect? Like sentient animals, xenos, nar'sie and ratvar constructs. I wouldn't expect gifs, just pictures to show the placement.

It looks exactly the same as it does normally. If people wish, they can override the procs and use a different iconstate, even if that means just copying and lowering the existing one.

2022-01-08 18:22 UTC, KubeRoot commented on code/modules/client/verbs/input_box.dm
> +		winset(src, "[id].cancel", "command=\".winset \\\"[id].is-visible=false\\\"\"")
Forgot to include it in my copypasted code, this should also clear the input.

2022-01-08 21:54 UTC, KubeRoot approved these changes
I haven't tested this myself, and I'd still like to see screenshots of what it looks like on other mobs, and I'm still worried this might break completely on some mobs (I think morphs will lose the indicator when dropping disguise)... But other than that, code looks good.

2022-01-26 15:13 UTC, Archanial approved these changes

2022-01-26 15:15 UTC, Archanial commented
if this breaks I blame kube

2022-01-26 15:15 UTC, merged