Ports GAGS
BeeStation/BeeStation-Hornet pull request #6204
Opened 2022-01-17 20:37 UTC by Archanial

## About The Pull Request

This PR ports GAGS system from TG

(Most of the) Ported PRs:
https://github.com/tgstation/tgstation/pull/58337
https://github.com/tgstation/tgstation/pull/58487
https://github.com/tgstation/tgstation/pull/58515
https://github.com/tgstation/tgstation/pull/58567
https://github.com/tgstation/tgstation/pull/58794
https://github.com/tgstation/tgstation/pull/58854
https://github.com/tgstation/tgstation/pull/58602
https://github.com/tgstation/tgstation/pull/59114
https://github.com/tgstation/tgstation/pull/59271
https://github.com/tgstation/tgstation/pull/59330
https://github.com/tgstation/tgstation/pull/59524
https://github.com/tgstation/tgstation/pull/59884
https://github.com/tgstation/tgstation/pull/60819
https://github.com/tgstation/tgstation/pull/63957

So far ported canister and scredrivers. Rest of the gagified sprites will be ported in future PRs.

## Why It's Good For The Game

## Testing Photographs and Procedure

<summary>
![obraz](https://user-images.githubusercontent.com/37456678/149834021-441b79c9-de82-4f57-bec9-672b176e9f4f.png)
![obraz](https://user-images.githubusercontent.com/37456678/149834070-cddf59c1-a7f7-4e01-8986-da10be2d7c94.png)
![obraz](https://user-images.githubusercontent.com/37456678/149834103-2bf4d718-6d45-4f0b-b210-86bddd3ed31f.png)
![obraz](https://user-images.githubusercontent.com/37456678/149834203-cef08e90-f299-4d71-82db-861ed0e896a5.png)
![obraz](https://user-images.githubusercontent.com/37456678/149834222-4d839a39-7dc1-4429-9a99-65746eaf8b0c.png)
![obraz](https://user-images.githubusercontent.com/37456678/149834241-8a57099c-bb8c-4e08-b73c-4abf804f52a1.png)
![obraz](https://user-images.githubusercontent.com/37456678/149834256-d7426d08-40b0-45dc-b5aa-36b6f5a43fdf.png)
![obraz](https://user-images.githubusercontent.com/37456678/149834282-3cac013e-6d89-4e5b-8ef3-771cc44e579b.png)

</summary>

Put screenshots and Videos documenting testing and execution of intended behaviors here

</details>

## Changelog
:cl:
add: Added GAGS system, for generating colored icons.
add: GAGS for canisters and screwdrivers.
/:cl:

2022-01-17 20:39 UTC, Archanial commented
Known issues:
- greyscale menu will runtime when changing from sprite with less colors to a sprite with more colors (for example from canister to proto canister). Issue also present on TG.
- proto canister's third layer won't get recolored, issue present on TG.

2022-01-18 00:02 UTC, KubeRoot requested changes

2022-01-18 00:02 UTC, KubeRoot commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	icon_state = "purple"
Should probably not have `icon_state` anymore

2022-01-18 00:02 UTC, KubeRoot commented on code/modules/atmospherics/machinery/portable/canister.dm
> +	icon_state = "blue"
Should probably not have `icon_state` anymore

2022-01-18 00:02 UTC, KubeRoot commented on tgui/packages/tgui/components/LabeledList.tsx
> + };
Unnecessary preceding whitespace here

2022-01-18 00:02 UTC, KubeRoot commented on tgui/packages/tgui/components/LabeledList.tsx
> + };
Unnecessary preceding whitespace here too

2022-01-18 00:02 UTC, KubeRoot commented on tgui/packages/tgui/components/LabeledList.tsx
> + };
Unnecessary preceding whitespace here too

2022-01-18 00:03 UTC, KubeRoot commented
Additionally, seems to add (presumably unused) sprites for tiered canisters, which we do not have: 
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/6917698/149849476-ac5f5a7d-60a9-4030-8708-89e991c4935b.png)

</summary>

I don't know what `can-0` through `3` refer to here, might be unrelated, but `tier1` through `3` are almost certainly for tiered canisters.

2022-01-18 00:47 UTC, lordScrubling commented
can-0-3 show the pressure inside the canister and should be kept

2022-01-26 15:09 UTC, Archanial commented
Nothing broke during testing.

2022-01-31 21:24 UTC, merged