Prevents lings from stinging IPCs.
BeeStation/BeeStation-Hornet pull request #621
Opened 2019-10-23 08:15 UTC by St0rmC4st3r

There is no logic or effect in stinging robots.
It is not that organic chemicals can affect electronics.

2019-10-23 08:18 UTC, despong commented
based and realistic

2019-10-23 10:31 UTC, zeskorion commented
Nah

All of ipcs issues already came from gay realism in muh 2d spessmens

Besides, radiation should affect them, considering it actually damages machines, and lingstings'll just inject chems

2019-10-23 13:46 UTC, St0rmC4st3r commented
I know, but this PR actually helps lings to save chemicals, since IPCs are not affected by most stings.

2019-10-23 20:15 UTC, ike709 commented on code/modules/antagonists/changeling/powers/tiny_prick.dm
> +	if(isipc(target))
```suggestion
	if(NOTRANSSTING in target.dna.species.species_traits)
```

IPCs should already have the `NOTRANSSTING` trait.

2019-10-23 20:16 UTC, ike709 commented on code/modules/antagonists/changeling/powers/tiny_prick.dm
> +		to_chat(user, "<span class='notice'>We cannot find any living tissue or blood in [target.name].</span>")
```suggestion
		to_chat(user, "<span class='notice'>Our sting would be ineffective against [target.name].</span>")
```

2019-10-23 20:17 UTC, ike709 commented
Add a CL.

2019-10-23 20:17 UTC, ike709 requested changes
Accept the suggested changes and add a CL.

2019-11-07 01:20 UTC, Crossedfall commented
Closing as stale. Please re-open when you've addressed the above suggestions and have added a proper CL.

2019-11-07 01:20 UTC, closed without merging