Makes used grenades slightly more obvious. Also prevents DOSing admins.
BeeStation/BeeStation-Hornet pull request #6321
Opened 2022-02-07 16:24 UTC by Dejaku51

## About The Pull Request
requested here by ike https://github.com/BeeStation/BeeStation-Hornet/projects/2#card-77266273 (i had nothing to do so i checked what is there to do)
Port of https://github.com/tgstation/tgstation/pull/64643
Adds a variable to track whether a grenade has already been used.
If it has it prevents the grenade from detonating again until the grenade has been reset. (Resetting only implemented for chemical grenades.)
It also prevents priming the grenade/pulsing the grenades wires from messaging admins (but still lets them log) because there's no point in telling the admins if the grenade isn't going to do anything.
The status of the grenade shows up in the examine text.

## Why It's Good For The Game

1. Makes it slightly more obvious that the cleaner grenades in the halls have already been used.
2. Prevents DOSing admins with grenade logging spam.

## Changelog
:cl:
qol: Used grenades now look used when examined.
fix: It should no longer be possible to DC admins by spamming grenades.
/:cl:

2022-02-08 01:26 UTC, KubeRoot commented
> If it has it prevents the grenade from detonating again until the grenade has been reset. (Resetting only implemented for chemical grenades.)

Seems to me like you didn't port the resetting here?

2022-02-08 16:18 UTC, Dejaku51 commented
woops, i'll check everything again

2022-02-08 17:06 UTC, Dejaku51 commented
Done

2022-02-08 18:30 UTC, mcmeiler requested changes

2022-02-08 18:30 UTC, mcmeiler commented on code/game/objects/items/grenades/chem_grenade.dm
> +				to_chat(user, "<span class='notice'>You reset the trigger</span>")
```suggestion
				to_chat(user, "<span class='notice'>You reset the trigger.</span>")
```
Very minor typo, missing a period.

2022-03-28 07:44 UTC, Archanial approved these changes

2022-03-28 07:44 UTC, merged