Looping Rods: The Return
BeeStation/BeeStation-Hornet pull request #6345
Opened 2022-02-10 07:01 UTC by Ivniinvi

## About The Pull Request
Rods now have a 1% chance of being a looping rod.

## Why It's Good For The Game
Looping rods are a primordial terror unlike nothing else, that provide an interesting threat dimension to the game. They do have a major impact though, which is why they're so rare. Additionally, the looping rod is well telegraphed, with a wave-of-dread message similar to a god battle or a chain inertia delamination. Finally, the Feat of Strength achievement is for all intents and purposes impossible without looping rods.

## Testing Photographs and Procedure

<details>

<summary>Screenshots&Videos</summary>

Put screenshots and Videos documenting testing and execution of intended behaviors here

</details>

## Changelog
:cl:
tweak: Immovable rods now have a one percent chance to loop.
/:cl:

2022-02-10 09:16 UTC, EvilDragonfiend commented
I wanted them back as they're interesting. by the way, 1% looks too lower. rods are already low chance.
also, I wonder... does it loop regardless of which side is looping?

2022-02-10 12:46 UTC, Archanial commented on code/modules/events/immovable_rod.dm
> +		to_chat(world, "<span class='userdanger'>You feel a wave of dread wash over you.</span>")
No

2022-02-10 21:32 UTC, Archanial commented on code/modules/events/immovable_rod.dm
> +		rod = new /obj/effect/immovablerod(startT, endT, C.special_target)
```suggestion
	var/looping = FALSE
	if(prob(1))
		looping = TRUE
	var/obj/effect/immovablerod/rod = new /obj/effect/immovablerod(startT, endT, C.special_target, looping)
```

2022-02-10 21:32 UTC, Archanial commented on code/modules/events/immovable_rod.dm
> +		previous_distance = get_dist(src, destination)
don't really like logic here, you are checking loc == destination twice and looping twice 🥴

2022-02-11 18:47 UTC, Archanial commented on code/modules/events/immovable_rod.dm
> +			qdel(src)
shouldn't you early return at the end here?

2022-02-13 12:29 UTC, PowerfulBacon requested changes
Good to have a completely uncounterable rod that cuts the entire station in half.
At least make it only possible when there is a research director in the game, since nobody can stop it apart from the RD.
The achievement is meant to be difficult, the majority of players don't know you can do this so even with an RD in the game this will most likely just exist forever, constantly cutting the station in half until an admin deletes it.

2022-02-13 13:48 UTC, Archanial commented
> Good to have a completely uncounterable rod that cuts the entire station in half. At least make it only possible when there is a research director in the game, since nobody can stop it apart from the RD. The achievement is meant to be difficult, the majority of players don't know you can do this so even with an RD in the game this will most likely just exist forever, constantly cutting the station in half until an admin deletes it.

Objectively untrue and massive skills issue.
Just play RD and be gamer.

2022-02-14 18:36 UTC, Ivniinvi commented
The rod now checks if your ID is registered as Research Director, instead of your roundstart job, to allow for acting heads and for there to be a counter if there is no RD.

2022-02-15 01:13 UTC, Sinestia commented
I swear it's counterable with holobarriers but that might be a schizopost

2022-02-17 12:43 UTC, williamcll commented
> 

As far as I know only SM can destroy a rod.

2022-02-17 13:40 UTC, Wilchenx commented
> > 
> 
> As far as I know only SM can destroy a rod.

No it just gets stuck in it

2022-02-21 21:52 UTC, PowerfulBacon commented
this PR is slowly making less and less sense, to counter the rod being uncounterable now you gain the ability to surplex a rod for just wearing the RDs ID? Also being counterable =/= being balanced, it will still be near impossible to stop and will just be an admin delete thing, reported as a bug and then removed.

2022-02-21 22:26 UTC, Ivniinvi commented
> this PR is slowly making less and less sense, to counter the rod being uncounterable now you gain the ability to surplex a rod for just wearing the RDs ID? Also being counterable =/= being balanced, it will still be near impossible to stop and will just be an admin delete thing, reported as a bug and then removed.

I've changed it back to roundstart RD, and I'm going to leave it as spawnable with no RD until either another maintainer weighs in or you and Archanial agree on whether or not this condition should apply.

2022-02-22 01:55 UTC, ike709 commented
I'm not really a fan of increasing the usage of BYOND `walk()` procs without porting TG's refactor, but the probability on this is so low that it probably doesn't matter

2022-02-27 15:24 UTC, PowerfulBacon commented
🗝️

2022-03-14 18:10 UTC, ike709 commented
A much better rod buff would be to add a generator to predispose it towards the center of the zlevel so it's actually liable to hit the station

🔑

2022-03-14 18:10 UTC, closed without merging