probably fixes body size runtime
BeeStation/BeeStation-Hornet pull request #6411
Opened 2022-02-22 16:49 UTC by Kapu1178

## About The Pull Request
I don't know if this actually works because I cannot reproduce the bug locally.

## Why It's Good For The Game
Invisible people bad lol

## Testing Photographs and Procedure

<details>

<summary>Screenshots&Videos</summary>

Put screenshots and Videos documenting testing and execution of intended behaviors here

</details>

## Changelog
:cl:
fix: Body sizes work 100% of the time probably
/:cl:

2022-02-22 16:52 UTC, Crossedfall commented
Nondescript CL. Also, if you didn't do any testing, just remove the block.

2022-02-22 16:53 UTC, Archanial commented on code/datums/dna.dm
> +		return
```suggestion
	if(!holder || !features["body_size"])
		return
```

2022-02-22 21:20 UTC, PowerfulBacon requested changes, later dismissed
code/_HELPERS/mobs.dm -> proc/random_features results in features["body_size"] breaking, which breaks the preferences and date_body_size()

code\modules\mining\lavaland\necropolis_chests.dm line 953 {/obj/item/dragons_blood/attack_self(mob/living/carbon/human/user)}
also needs updating

2022-02-27 14:22 UTC, Archanial approved these changes

2022-02-27 14:22 UTC, merged