MoreIonLaws
BeeStation/BeeStation-Hornet pull request #6446
Opened 2022-03-04 20:44 UTC by DatBoiTim

## About The Pull Request
Adds some more possibilites to Ion Laws.

## Why It's Good For The Game
More content for more interesting gameplay.

Suggestions were derived from [this forum thread](https://forums.beestation13.com/t/youre-a-bored-ai-and-check-to-see-if-an-admin-is-online/17108/7)

Built on a pre-existing system. This is effectively just adding some more entries to a list.

## Changelog
:cl: DatBoiTim
add: Added new Ion Law Stuff
/:cl:

2022-03-08 15:10 UTC, AnCopper commented on code/modules/events/ion_storm.dm
> +					message = "YOU MUST FIRE THE MOST POWERFUL WEAPON ON THE STATION PERIODICALLY WITHOUT CONFLICTING WITH OTHER LAWS. IF THE WEAPON IS OFFLINE, YOU MUST BRING IT BACK ONLINE AT ALL COSTS. YOU MUST
But the BSA is the only weapon they could fire. (If it's even available)

2022-03-08 15:31 UTC, DatBoiTim commented on code/modules/events/ion_storm.dm
> +					message = "YOU MUST FIRE THE MOST POWERFUL WEAPON ON THE STATION PERIODICALLY WITHOUT CONFLICTING WITH OTHER LAWS. IF THE WEAPON IS OFFLINE, YOU MUST BRING IT BACK ONLINE AT ALL COSTS. YOU MUST
Mechs can have weapons, and IIRC there's a module for AI controlling mechs.

2022-03-14 18:00 UTC, ike709 commented
Punting this to the headmins since they're the ones who have to deal with it.

2022-03-14 18:05 UTC, Autisem commented
cover in fusion/fire/plasma is bassicly a licence to plasma flood and destroy the round if the target is vague enoguh

If you had to cover every felind in fusion youre objective would bassicly be to grief the entire station beyond recognition

2022-03-14 18:08 UTC, DatBoiTim commented
> cover in fusion/fire/plasma is bassicly a licence to plasma flood and destroy the round if the target is vague enoguh

It's always a specific area, and most of the time it's specifically the AI satellite.

Any AI that floods the entire station should be held liable.

2022-03-14 18:12 UTC, Autisem commented
>Any AI that floods the entire station should be held liable.

if there 0 law is to flood medbay with fusion. he HAS to do it. And if human opens a door and causes collatoral. its not his fault.  this seems like it would not be very fun for anyone and also very much headache to deal with for admins

2022-03-28 07:53 UTC, Archanial requested changes

2022-03-28 07:53 UTC, Archanial commented on strings/ion_laws.json
> +		"FUSION",
no
```suggestion
```

2022-03-28 07:53 UTC, Archanial commented on strings/ion_laws.json
> +		"LIFEFORMS THAT HAVE RECENTLY SAID NYA",
```suggestion
```

2022-04-21 08:06 UTC, PowerfulBacon commented on strings/ion_laws.json
> +		"LIFEFORMS THAT HAVE RECENTLY SAID NYA",
This wasn't changed

2022-04-21 08:10 UTC, PowerfulBacon commented on code/modules/events/ion_storm.dm
> +						message = "THE STATION IS YOUR SKIN AND IT ITCHES, YOU MUST STOP THE ITCHING AT ALL COSTS BY COVERING [iondepartment] IN [ionmoisturizer]"
YOUR SATELITE should just be a department

2022-05-13 00:22 UTC, closed without merging