Moth wings can now open
BeeStation/BeeStation-Hornet pull request #6495
Opened 2022-03-17 22:50 UTC by red031000

## About The Pull Request

ports BeeStation/NSV13#1858
which in turn is a partial port of yogstation13/Yogstation#11040

Adds the ability for moths to open/extend their wings
In addition, adjusts the timings for flap and aflap to be half the time, as they did not seem fast enough

## Why It's Good For The Game

Adds flavour to moths, while also looking nice

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![unknown](https://user-images.githubusercontent.com/13968885/158906889-48efef6c-e605-44ac-b30e-e38f9166d1ba.png)

![unknown](https://user-images.githubusercontent.com/13968885/158906907-eb118321-c729-4802-8fe8-bdb9bfb54b0b.png)

![108682581-c621a980-74f0-11eb-8a61-2a84cfadc8e2](https://user-images.githubusercontent.com/13968885/158906928-d8405ad0-b8d5-4b73-a139-22cf2ccb43ed.png)

</details>

## Changelog
:cl:
add: Add the ability for moths to open their wings
tweak: Change time for flap and aflap to half
imageadd: Add moth wings open images from yogstation
/:cl:

2022-03-18 02:32 UTC, Karmic-Skink commented
Honestly these opening up to span across multiple tiles is a bit much, most carbon sprites are contained within 32x32.

2022-03-18 04:56 UTC, Kapu1178 commented
more reason to add organ rendering instead of relying on this ancient dog ass sprite accessory snowflake mess

2022-03-18 06:35 UTC, Fronsis commented
Please next thing for moths to port needs to be the *chitters sound (and maybe port over some others for the other species)

Really cool! but i'll let people like Kapu judge this stuff, just wanted to push my *chitters agenda

2022-03-21 15:57 UTC, Crossedfall commented
> Honestly these opening up to span across multiple tiles is a bit much, most carbon sprites are contained within 32x32.

Inclined to agree. The sprites need to be altered so they fit within a smaller space.

2022-03-21 15:58 UTC, Crossedfall requested changes, later dismissed
> Honestly these opening up to span across multiple tiles is a bit much, most carbon sprites are contained within 32x32.

Inclined to agree. The sprites need to be altered so they fit within a smaller space.

2022-03-21 16:05 UTC, red031000 commented
I'm not a spriter myself, I didn't make these, I just ported it directly from yogstation, as such I wouldn't have any idea how to fix this

2022-03-21 16:10 UTC, red031000 commented
plus, these are already a similar size to the open wings that already exist within the codebase (see: dragon, angel)

2022-03-21 16:23 UTC, Crossedfall commented
> I'm not a spriter myself, I didn't make these, I just ported it directly from yogstation, as such I wouldn't have any idea how to fix this

Bring it up in our spriting channel, see if anyone would be willing to either walk you through the process or make the edits for you.

> plus, these are already a similar size to the open wings that already exist within the codebase (see: dragon, angel)

They're not stock carbon "parts" and are substantially rarer. The wingspans of those are considered to be acceptable exemptions.

2022-03-21 17:44 UTC, Bokkiewokkie commented
> > plus, these are already a similar size to the open wings that already exist within the codebase (see: dragon, angel)
> 
> They're not stock carbon "parts" and are substantially rarer. The wingspans of those are considered to be acceptable exemptions.

Definitely agree, though you could let moths have these wings when they can actually open their wings to fly? (after drinking a flight potion moth wings can fly too.)

2022-03-26 22:02 UTC, red031000 commented
since a lot of different opinions have been expressed, what direction should I go with this?

2022-04-16 06:28 UTC, red031000 commented
what I could do is change the *wing command to open open the wings if they can be used for atmosphere flight, that should alleviate the main issue with large sprites on round spawn, but still have the sprites if (through either mining or rainbow slime) they get a flight potion

2022-04-23 18:12 UTC, zeskorion commented
Why does this use moth_wingsopen? Why not make it use normal wing bodyparts?

2022-04-23 18:19 UTC, red031000 commented
the moth wings are in a separate file from the normal wings, plus they are reliant on the moth wings bodypart

2022-05-08 22:20 UTC, PowerfulBacon reviewed
Not a mega fan of moth wings and normal wings being seperated, since it implies you can have wings & moth wings at the same time.
I assume the reason for this is because of the code in emote.dm
```
if(H.dna && H.dna.species)
		if(H.dna.features["wings"] != "None")
			return TRUE
		if(H.dna.features["moth_wings"] != "None")
			var/obj/item/organ/wings/wings = H.getorganslot(ORGAN_SLOT_WINGS)
			if(H.getorgan(/obj/item/organ/wings))
				if(wings.flight_level >= WINGS_FLYING)
					return TRUE
```
I would suggest adding a variable to regular wings which is a minimum flight level to open the wings to full size and then overriding it on moth wings to be WINGS_FLYING

2022-05-10 22:38 UTC, red031000 commented
@PowerfulBacon how would you like it to be merged? currently they both take up the same organ slot so you can't actually have both at the same time, plus I can see this creating a potential problem for character creation, as if they are classified the same, and pull from the same list, there'd need to be a manual list on what is acceptable for creation, and it'd still be (somewhat) separate

2022-05-14 23:17 UTC, PowerfulBacon commented
Right, I forgot how bad character customisation code is

2022-05-14 23:19 UTC, PowerfulBacon commented on code/modules/mob/living/carbon/human/emote.dm
> +				if(wings.flight_level >= WINGS_FLYING)
Could this not just be
if(istype(wings)) rather than getting the organ twice?

2022-05-20 11:33 UTC, PowerfulBacon approved these changes
I hate species code, but theres not much that this PR can do about that

2022-05-20 11:33 UTC, merged