Removes some bitflag defines
BeeStation/BeeStation-Hornet pull request #6523
Opened 2022-03-20 22:56 UTC by TheFakeElon

## About The Pull Request

All of these bitflag defines had less than ~7 implementations each and are literally just a define to use an inbuilt operator. Bitflag operators are easy to use and do not require abstraction to be accessible, even for very inexperienced programmers. 
Adds a reference in comments for common bitflag operations in place where the define was used, in case anyone was using them for that

Doesn't remove the CHECK_MULTIPLE_BITFLAGS define as that is the only one I can feasibly imagine giving some people a hard time

## Changelog
:cl:
code: removes some bitflag defines
/:cl:

2022-03-21 08:42 UTC, Archanial approved these changes

2022-03-21 14:11 UTC, ike709 requested changes
These existing costs you nothing.

2022-03-21 22:01 UTC, utilbird commented
> These existing costs you nothing.

https://github.com/BeeStation/BeeStation-Hornet/pull/5950#issuecomment-993705506

2022-03-22 00:54 UTC, ike709 commented
\> using the excuse I used to close a pointless global find & replace

You got anything better than that?

2022-03-25 05:26 UTC, TheFakeElon commented
I really don't want to (and shouldn't need to) write an essay about why having a define for a single operator is stupid, in fact I'm pretty sure I already *have* written one in #development before, so if you're really attached to these defines for whatever reason, I can dig that up. 
Also what do you mean "you got anything better than that?", did you read the PR description? Not only are these defines stupid and shouldn't exist in the first place but they're almost never used.

2022-04-05 10:21 UTC, Mat05usz commented
This also breaks #6602 now since I used the defines.

2022-04-05 15:17 UTC, closed without merging