[PORT] Refactor cult dagger rune drawing and null rod rune clearing into components + minor rune / blood magic tweaks
BeeStation/BeeStation-Hornet pull request #6532
Opened 2022-03-21 19:06 UTC by Ivniinvi

## About The Pull Request
- tgstation/tgstation#62918
The act of inscribing runes, anchoring / unanchoring cult structures, deconstructing cult girders, and purging cultists of holy water have all been moved off of the cult dagger itself and onto a component, cult_ritual_item.

The act of destroying a cult rune or heretic rune with the null rod have been moved off of their respective items and onto the nullrod itself.

Added a signal, COMSIG_ITEM_ATTACK_EFFECT, for the above purposes.
Various cult spells and dagger interactions have had their code improved slightly.

## Why It's Good For The Game
Cult dagger stuff was all over the place, same with null rod cleansing. This brings it all together and unified the behavior, also allowing more than daggers to inscribe runes and work with cult items eventually.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: Melbert
refactor: Refactored cult rune inscribing into a component
refactor: Refactored null rod rune clearing into a component
/:cl:

2022-04-11 09:02 UTC, Archanial requested changes

2022-04-11 09:02 UTC, Archanial commented on code/datums/action.dm
> +			held_item.attack_self(owner)
you can iterate over a specified type instead of doing anything then checking for dagger

2022-04-11 09:02 UTC, Archanial commented on code/datums/components/cult_ritual_item.dm
> +		COMSIG_PARENT_EXAMINE,
doesn't this runtime if there was no examine signal registered?

2022-05-21 19:11 UTC, Archanial requested changes

2022-05-21 19:11 UTC, Archanial commented on code/datums/action.dm
> +			held_item.attack_self(owner)
This isn't really resolved. Make it typed loop instead.

2022-05-29 08:51 UTC, PowerfulBacon approved these changes
Seems okay

2022-05-29 08:52 UTC, PowerfulBacon requested changes

2022-05-29 08:52 UTC, PowerfulBacon commented on code/datums/action.dm
> +		return
This won't work as() disables type checking on for loops

2022-06-01 07:36 UTC, PowerfulBacon approved these changes
lgtm

2022-06-16 05:51 UTC, closed without merging