Improved Immovable Rod Targeting
BeeStation/BeeStation-Hornet pull request #6568
Opened 2022-03-29 04:01 UTC by Ivniinvi

## About The Pull Request
Immovable Rod now has a much higher chance to actually hit the station.

## Why It's Good For The Game
Whiffed rods are boring for everyone involved

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Tested with fifty rods, five missed.

</details>

## Changelog
:cl:
tweak: Immovable Rod is much more likely to hit the station
/:cl:

2022-03-29 15:20 UTC, ike709 requested changes
Literally just make a generator to bias it towards the center of the zlevel.

2022-03-29 15:20 UTC, ike709 commented
http://www.byond.com/docs/ref/#/proc/generator

2022-03-29 18:11 UTC, Ivniinvi commented
Retested, 18 critical hits out of 20 rods fired post generatorification.

2022-03-29 21:24 UTC, ike709 commented on code/game/gamemodes/meteor/meteors.dm
> +	var/generator/G = generator("num", TRANSITIONEDGE + 1, world.maxx - (TRANSITIONEDGE + 1), "NORMAL_RAND")
`NORMAL_RAND` is a macro, not a string.

2022-03-29 21:24 UTC, ike709 commented on code/game/gamemodes/meteor/meteors.dm
> +	var/generator/G = generator("num", TRANSITIONEDGE + 1, world.maxx - (TRANSITIONEDGE + 1), "NORMAL_RAND")
```suggestion
	var/generator/G = generator("num", TRANSITIONEDGE + 1, world.maxx - (TRANSITIONEDGE + 1), NORMAL_RAND)
```

2022-03-30 06:21 UTC, ImSynthex commented
you should probably link this issue

- https://github.com/BeeStation/BeeStation-Hornet/issues/6467

2022-03-31 08:59 UTC, ike709 approved these changes

2022-04-02 19:40 UTC, merged