Fusion Rebalance: April Fools edition
BeeStation/BeeStation-Hornet pull request #6591
Opened 2022-03-31 21:06 UTC by TeomanTheGreat

## About The Pull Request
As we all know fusion is inherently weak and deserves a buff so I have concocted this pr to remedy this. 

For obvious reasons, this should only be merged on April fools for maybe a few rounds to see the funny rads. For those attempting to contain a fusion of this magnitude, I would recommend checking what the fusion particles now pass through and don't pass through to find some form of a solution. 

## Why It's Good For The Game
![the sun (2)](https://user-images.githubusercontent.com/55861563/161148652-bca0d5f0-7d76-4465-9af5-7c19a723b0fd.jpg)

## Testing Photographs and Procedure

<details>
I found this dog (I'm assuming I don't need to show testing procedure and photographs since this is a meme pr intended for like a few rounds on April fools) 

![Mammoth](https://user-images.githubusercontent.com/55861563/161148852-bc8c6ffa-3f63-440c-bb72-4f25e1c313a1.jpg)

</details>

## Changelog
:cl: Phil Smith, Allah
tweak: Try fusion at your own risk (APRIL FOOLS!!)
/:cl:

2022-03-31 21:34 UTC, athena413 commented
yes

2022-03-31 22:14 UTC, MNarath1 requested changes

2022-03-31 22:14 UTC, MNarath1 commented on code/modules/projectiles/projectile/energy/nuclear_particle.dm
> +	irradiate = INFINITY // trolle!!
```suggestion
	irradiate = custompower // trolle!!
```

2022-03-31 22:14 UTC, MNarath1 commented on code/modules/projectiles/projectile/energy/nuclear_particle.dm
> +	irradiate = INFINITY // trolle!!
Actually even with this that high nuclear particle won't deal more than 30 damage look at the switch below still applies crazy rads trough

2022-03-31 22:14 UTC, MNarath1 commented on code/modules/projectiles/projectile/energy/nuclear_particle.dm
> +	irradiate = INFINITY //:)
```suggestion
	irradiate = 2500 //enough to knockdown and induce vomiting
```

2022-03-31 22:14 UTC, MNarath1 commented on code/modules/projectiles/projectile/energy/nuclear_particle.dm
> +	irradiate = INFINITY //:)
You already modify the radiation to its crazy level in the proc below.

2022-03-31 22:23 UTC, MNarath1 requested changes

2022-03-31 22:23 UTC, MNarath1 commented on code/modules/projectiles/projectile/energy/nuclear_particle.dm
> +/atom/proc/fire_nuclear_particle(angle = rand(0,360), customize = FALSE, custompower = INFINITY) //used by fusion to fire random nuclear particles. Fires one particle in a random direction.
```suggestion
/atom/proc/fire_nuclear_particle(angle = rand(0,360), customize = FALSE, custompower = 1e12) //used by fusion to fire random nuclear particles. Fires one particle in a random direction.
```

2022-03-31 22:23 UTC, MNarath1 commented on code/modules/projectiles/projectile/energy/nuclear_particle.dm
> +/atom/proc/fire_nuclear_particle(angle = rand(0,360), customize = FALSE, custompower = INFINITY) //used by fusion to fire random nuclear particles. Fires one particle in a random direction.
Just don't bother this is probably beeing overwriten by the proccal anyways so lets just apply infinity down the procchain instead

2022-04-02 06:36 UTC, TeomanTheGreat commented
Since no maintainer man has looked at this and its 2 am in my timezone (no longer april fools) I shall close this.

2022-04-02 06:36 UTC, closed without merging