Adds Omega alert.
BeeStation/BeeStation-Hornet pull request #6614
Opened 2022-04-05 20:58 UTC by AnCopper

## About The Pull Request

Adds the Omega alert level.

Partly ports this: https://github.com/yogstation13/Yogstation/pull/9244

## Why It's Good For The Game

This is intended to be used as an RP mechanic by admins when they plan to send in a Death Squad or anything else close to that.

It doesn't actually do anything, but I think it's good for flavor and giving you the "Oh fuck" feeling when you hear the distinct siren.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://streamable.com/4krft9

</details>

## Changelog
:cl: swissloaf AnCopper
add: Added omega alert.
/:cl:

2022-04-05 22:39 UTC, Kapu1178 commented
didnt someone already try to do this and got told "This is just delta alert"

2022-04-05 23:52 UTC, Mat05usz commented
> didnt someone already try to do this and got told "This is just delta alert"

I think so, and they were correct. Delta alert is basically 'fuck, we're done'.

2022-04-06 05:23 UTC, Fronsis commented
> > didnt someone already try to do this and got told "This is just delta alert"
> 
> I think so, and they were correct. Delta alert is basically 'fuck, we're done'.
> 
> Edit: Deathsquad is so rarely called I don't think it even matters. We rarely get CC inspectors, or even low alert ERT, so that's just a cool, but pointless addition imo.
> 
> Edit2: #5215 I think this is the PR with alerts from Yog. Omega makes more sense than those but still kinda eeh.

Those are also nice! I'm personally a fan of the ones that you can declare for medical and engineer emergencies, a couple of tg downstreams have it, i don't remember if there's any others besides those (and standards green blue red delta)

2022-04-07 22:40 UTC, zeskorion commented
just use delta

2022-04-08 02:56 UTC, DatBoiTim commented
I still think it's worth having other non-doomsday alert levels.

Think like Bay's Orange alert for engineering emergencies, ~~purple~~violet alert for biological(xenobio/viro/mass casualty), could probably add one for science specifically.

But aside from that doomsday alert levels are moot.

2022-04-11 00:57 UTC, Daridine commented
> If you really want to provide admin only alert levels, make a system where they can name the alert level on their own and give it meaning.

I would LOVE this.

2022-04-11 07:48 UTC, Archanial requested changes
code looks mostly good at firsts glance. I'll ask admins if they want this feature or not.

2022-04-11 07:48 UTC, Archanial commented on code/modules/security_levels/security_levels.dm
> +				pod.admin_controlled = FALSE
?

2022-04-11 07:48 UTC, Archanial commented on code/controllers/configuration/entries/game_options.dm
> +	config_entry_value = "Attention, Code Omega has been initiated. Consider all employment contracts terminated, effective immediately."
We don't need to bloat the config even more.
Just make it static string

2022-04-11 07:57 UTC, Autisem commented
If possible, make the alert message settable by admins on being called, some extra configuration stuff on runtime could make this from being delta+ to a wild card alert level for either adminbus or reflecting cool thematics of the station

2022-04-11 07:57 UTC, Archanial commented on code/controllers/configuration/entries/game_options.dm
> +	config_entry_value = "Attention, Code Omega has been initiated. Consider all employment contracts terminated, effective immediately."
Actually make this alert message be able to be set by admin upon trying to change the alert to this and keep this as default value or wharever

2022-04-21 08:41 UTC, PowerfulBacon commented on code/modules/security_levels/security_levels.dm
> +				pod.admin_controlled = FALSE
Allows escape pods to be flown

2022-05-07 14:41 UTC, PowerfulBacon commented
I dislike this, since it has the same effect as delta and bloats the alert code. If more alerts are going to be added, we need a better alert system with something like a /datum/alert_level rather than if(1), if(2) etc. etc.

2022-05-13 00:22 UTC, closed without merging