Removes Nar'sie plushie cheese
BeeStation/BeeStation-Hornet pull request #6641
Opened 2022-04-10 19:44 UTC by Mat05usz

## About The Pull Request

Apparently it was possible to bypass all interaction with fellow cult members by placing a Nar'sie plushie on a cult rune and invoke like this. The plushie would count towards the invokers so you can easily and stealthy (without a second person and/or using the summon ghost rune) convert people, or do other stuff that requires more than one person.

## Why It's Good For The Game

Cheese is bad (at least the inedible type).

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
balance: You can no longer use Nar'Sie plushie to invoke cult runes.
/:cl:

2022-04-10 19:46 UTC, PowerfulBacon commented
Aren't they meant to be difficult to get though and only available from hacked chaplain vendors?

2022-04-10 19:48 UTC, Mat05usz commented
> Aren't they meant to be difficult to get though and only available from hacked chaplain vendors?

Hacking chaplain vendor means it's difficult to obtain? There is one wire to hack all vendors on the map.

2022-04-10 20:22 UTC, AnCopper commented
It's just a funny gimmick, I have never seen it used anyway.

2022-04-10 20:57 UTC, Fronsis commented
It's one of the few ways to convert/try to do a comeback for when a single cultist is left alive

Also it's a funny and cute gimmick

If the issue is a cultist member completely ignoring the other then that's something that should be bwoinkable/reportable

2022-04-10 21:20 UTC, Mat05usz commented
> It's just a funny gimmick, I have never seen it used anyway.

Apparently it's new meta? 

> It's one of the few ways to convert/try to do a comeback for when a single cultist is left alive
It's a way to completely ignore the fact that you gotta cooperate within cult and just rush stuff.

> Also it's a funny and cute gimmick
How is cheesing the game mode funny and cute lmao

> If the issue is a cultist member completely ignoring the other then that's something that should be bwoinkable/reportable
And who's supposed to do the bwoinking, and even if there is admin on, how are you supposed to assume with logs (there are none) that said person didn't do that out of just wanting to win?

2022-04-10 21:35 UTC, zeskorion commented
oh hey i awanted to do this for awhile thanks

2022-04-11 00:28 UTC, Daridine commented
I'll lead with this First:
Basing a trimming of a fun interaction on some random mento claiming its meta is very bad.

Continuing now:
I solidly disagree with this removal. 
It provide a fun way for cults to get their feet back when down, there's nothing wrong with stealthy conversions and involves breaking into an arguably dangerous place for cultists to be. It also isn't relying on ghosts.

Also, even if one person is being quiet and doing conversions solo with this, the point of the blood cult is to grow, so the other cult members will end up talking to eachother and interacting.

2022-04-11 04:37 UTC, EvilDragonfiend commented
If me, I would set it usage limit. Like you can only use 1~3 times.

2022-04-11 19:55 UTC, Tsar-Salat commented
`The plushie would count towards the invokers so you can easily and stealthy (without a second person and/or using the summon ghost rune) convert people, or do other stuff that requires more than one person.
`

AFAIK this is intended game mechanics.

2022-04-12 18:41 UTC, Mat05usz commented
> Basing a trimming of a fun interaction on some random mento claiming its meta is very bad.

Meta was meant to be put in "". I don't really care what cheese is popular at any given moment, only if it allows unfair advantage with no negatives.

> It provide a fun way for cults to get their feet back when down

It sure is fun, but I don't think it's worth it.

> there's nothing wrong with stealthy conversions

I agree 100%, but this isn't about it being stealthy as much as it is about requiring literally no other player in a gamemode focused around teamwork. 

> breaking into an arguably dangerous place for cultists to be

Lol

> It also isn't relying on ghosts

Relying on ghosts means relying on other player, which again this gamemode is focused around.

> Also, even if one person is being quiet and doing conversions solo with this, the point of the blood cult is to grow, so the other cult members will end up talking to eachother and interacting.

It allows one robust person to do conversions basically anywhere, since all they need to do is have a rune drawn and plushie around, no need to scream and wait for other person to come around, or draw a rune to poll ghosts, both taking precious time and increasing the risk of getting caught. 

Very easy, very sneaky snowball that requires no other players.

> If me, I would set it usage limit. Like you can only use 1~3 times.

Maaaybe I could see that as a one time use item, wouldn't be too bad since after converting like that you'd have a second person to do more converting with you. 3 is too many.

2022-04-14 12:29 UTC, SerketIrish commented
Hello, I am the mentor that "abuses" the narsie plushie for my own sick and twisted gaming needs, and here's why.

I roll roundstart cult a LOT and am usually the only one doing conversions as all the other members are either new and don't know how to use cult chat or lock themselves in xenobio for some autism project that'll be done forty minutes into the round. Whenever I don't get a reply to "anyone wanna convert with me?" I grab the plushie. Right now the plushies just a fairer version of the spirit rune in my opinion. All cultists can solo convert with the spirit rune but there's never a guarantee it'll actually work if there aren't any ghosts available. I got caught with my pants down once getting a convert at the five minute mark in maints and no ghost appearing so I had to cuff and locker the poor fuck until I could find one of the newer cultists and drag them to me. The narsie plushie is also cute and very likable. 

Good feature, please no remove, me like plushie. 

> Relying on ghosts means relying on other player, which again this game mode is focused around.

""""Relying on ghosts"""" is just an rng gambit for someone you dont even talk to. If youve ever seen a spirit rune conversion you know the ghost is there for literally one second and then gone. The most I remember a ghost I summoned saying was "AAAAAA" and disappear. I have no idea how that's supposed to be more fun then just using a plushie. 

> no need to scream and wait for other person to come around, or draw a rune to poll ghosts, both taking precious time and increasing the risk of getting caught.

Again I don't really see this as a bad thing, usually the narsie plushie is only grabbed by a competent cultist round start if no one wants to convert with them, and since getting another narsie plushie by restocking the chaplain vendor is so much more difficult then just using spirit runes 99 times out of 100 they are the only ones that have it. It makes cult growing much more common and makes it a lot harder to get caught and steamrolled round start. 

> Maaaybe I could see that as a one time use item, wouldn't be too bad since after converting like that you'd have a second person to do more converting with you. 3 is too many.

This good compromise, me like.

2022-04-22 11:09 UTC, EvilDragonfiend commented
> Maaaybe I could see that as a one time use item, wouldn't be too bad since after converting like that you'd have a second person to do more converting with you. 3 is too many.

Then you have two options.
1. Make it always functional when there is only one cultist.
2. Make it only one time usable.
3. Or... 1+2. It is automatically charged when there is only one cultist.

For the usage limit, you can make it an examine text when a cultist or a chaplain examine them.
* `This plushie looks perfectly fine.` when nobody used it.
* `This plushie looks like drained...`(red text) when it is 0 charge left.

2022-04-22 21:01 UTC, Mat05usz commented
> I roll roundstart cult a LOT and am usually the only one doing conversions as all the other members are either new and don't know how to use cult chat or lock themselves in xenobio for some autism project that'll be done forty minutes into the round.

> I don't get a reply to "anyone wanna convert with me?" I grab the plushie

> Good feature, please no remove, me like plushie.

> """"Relying on ghosts"""" is just an rng gambit for someone you dont even talk to. If youve ever seen a spirit rune conversion you know the ghost is there for literally one second and then gone

Your entire reply is how cool is it to skip the thing that makes the cult weak, working with others.

> Again I don't really see this as a bad thing, usually the narsie plushie is only grabbed by a competent cultist round start if no one wants to convert with them

But that's the gamemode you know, if cultists are shit then I'm sorry but you're gonna lose, there shouldn't be any cheats enabling robust players to completely avoid being thwarted by incompetence and keep cheesing their way to victory.

2022-04-22 21:22 UTC, Mat05usz commented
If you believe that it's okay to have a way to ignore any and all interactions between players in a gamemode on a RP server, then go ahead and close this PR.

2022-04-26 19:11 UTC, PowerfulBacon requested changes
Sentiment seems generally against this PR.
Points that get brought up is that there are a lot easier ways to get an extra person to perform rituals, such as spirit realm for example, this is a pretty niche item and can only be accessed from a hacked chaplain vendor (limiting it to 1).

I would recommend making the plushie rarer in some way (If somehow there were additional ways to get it introduced) if you wish to continue with nerfing the Nar'Sie plushie.

2022-04-27 17:47 UTC, PowerfulBacon commented
:key: key also if another maint wants to close, otherwise Why its good for the game still needs to be updated

2022-04-28 22:47 UTC, Mat05usz commented
I'll respond to your points tomorrow.

2022-05-01 14:37 UTC, Penwin0 commented
Was recently abused to achieve Halos in complete stealth 10 minutes in it is also not hard to obtain at all

2022-05-01 14:39 UTC, Mat05usz commented
> Was recently abused to achieve Halos in complete stealth 10 minutes in it is also not hard to obtain at all

Bruh, I didn't expect it's that fucking bad.

2022-05-01 15:10 UTC, St0rmC4st3r commented
Are you sure those pushes didn't come from cargo?

2022-05-01 17:52 UTC, KennyBadrige commented
This is a cheese interaction that shouldnt have existed in the first place.

2022-05-01 18:52 UTC, Mat05usz commented
> Are you sure those pushes didn't come from cargo?

Does it matter where plushies come from?

2022-05-02 00:08 UTC, SerketIrish commented
> Your entire reply is how cool is it to skip the thing that makes the cult weak - working with others.

I know I'm absolutely evil for not liking when a team game mode gets cut short when new players don't know what to do. I'm actually the Joker from batman and I just wanted to ruin your teamwork skills, you caught me. 

> But that's the gamemode you know, if cultists are shit then I'm sorry but you're gonna lose, there shouldn't be any cheats enabling robust players to completely avoid being thwarted by incompetence and keep cheesing their way to victory.

I mean imo its not really a "Cheat to cheese to victory" its much more "avoiding getting stomped at round start before cult can even do that much". I mean obviously Im not the person to be talking to about balance because I played xeno for 100 hours at least, but I personally think a conversion antag like cult could use with a buff round start that gets taken away or looses its usefulness as the round goes on. It makes sec steamrolling much less common which is good because one side or another getting steam rolled is boring. It would be really cool if it was an actual feature instead of a weird niche item that only the super nerdy of us know. [although this is a bad idea right now because cult is already in a really strong mid and late game state]

Anyways after that rant, I think the narsie plushie actually fits a very useful game design model that's really cool, I get that "teamwork is the gamemode" and I do agree but I feel like the way the narsie plushie effects cult games is better then without. I think nerfing it would be a lot better then a flat out removal, but what do I know I dont even own coder socks. Thanks for coming to my ted talk, this whole thing is pointless anyways because the narsie plushie barely effects gameplay, but Ill still fight for my child.

2022-05-31 03:14 UTC, pavl1ko commented
Just limit the plushie to a one time use.
I see way too many cultists rushing it shift start even when teammates exist and are 2 tiles away asking to come to help convert

2022-06-01 07:34 UTC, closed without merging