Fixes crew monitors and implements global suit sensors list
BeeStation/BeeStation-Hornet pull request #6645
Opened 2022-04-11 16:17 UTC by Archanial

## About The Pull Request

it turns out dummies have no loc
console working

## Why It's Good For The Game

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Added global suit sensors list
fix: fixed crew monitor
/:cl:

2022-04-11 16:17 UTC, Archanial commented
![obraz](https://user-images.githubusercontent.com/37456678/162785270-0666751c-4408-4efc-8f33-1d4d7b309758.png)

2022-04-11 16:52 UTC, ike709 commented on code/game/machinery/computer/crew.dm
> +			stack_trace("Null in suit sensors list")
This should never pass? The typed loop should skip nulls.

2022-04-11 17:00 UTC, ike709 approved these changes, later dismissed

2022-04-11 19:38 UTC, ike709 approved these changes, later dismissed

2022-04-12 01:57 UTC, Fronsis commented
It's seems they're broke atm and don't show anyone

2022-04-12 08:13 UTC, PowerfulBacon approved these changes

2022-04-12 08:14 UTC, PowerfulBacon requested changes

2022-04-12 08:14 UTC, PowerfulBacon commented on code/modules/mob/living/carbon/human/human.dm
> +			U.update_sensors(NO_SENSORS)
This should just remove them from the global list since GLOB.suit_sensors_list can add a mob to it through nanites as well

2022-04-14 09:35 UTC, PowerfulBacon commented on code/game/machinery/computer/crew.dm
This should remove H from the suit sensors list so it doesn't cause a stack trace every single time

2022-04-16 11:47 UTC, PowerfulBacon commented on code/modules/research/nanites/nanite_programs/utility.dm
> +	REMOVE_TRAIT(host_mob, TRAIT_NANITE_SENSORS, TRACKED_SENSORS_TRAIT)
Remove the trait before you check if they have the trait

2022-04-16 14:10 UTC, Archanial commented on code/modules/mob/living/carbon/human/human.dm
> +			U.update_sensors(NO_SENSORS)
```suggestion
	GLOB.suit_sensors_list -= src
```

2022-04-16 14:16 UTC, PowerfulBacon approved these changes

2022-04-16 14:21 UTC, merged