Update clockcult.dm
BeeStation/BeeStation-Hornet pull request #6651
Opened 2022-04-11 20:14 UTC by Jockeybane

Changes the Check_Finished method to first check to see if the Blood Cult is active, and doesn't roundend if one exists. This allows the Blood Cult to succeed in rounds where they co-exist with Clockies, as without this change, Blood Cult cannot summon Nar'sie while the Gateway is active, but destroying the Gateway ends the round immediately, preventing the Blood Cult from being able to summon.

Also adds an announcement to tell the crew of this vaguely as people will know why the round isn't over anyways.

## About The Pull Request

## Why It's Good For The Game

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-04-12 08:09 UTC, PowerfulBacon reviewed
Since the blood cult Nar'Sie summoning rune activates the gateway, if the clockcult gets destroyed and the blood cult rune triggered the gateway then it should summon nar'sie automatically.

2022-04-13 04:06 UTC, williamcll commented
Has this ever been proven on the live server?

2022-04-13 08:26 UTC, PowerfulBacon commented
> Has this ever been proven on the live server?

Yes, however this only ever happens as a result of admins spawning it (and once due to a bug)

2022-04-22 08:27 UTC, PowerfulBacon requested changes
If the gateway was opened due to Nar'sie rune being activated, Nar'sie should automatically be summoned

2022-04-28 00:24 UTC, closed without merging