Makes tongues control the say mods instead of species
BeeStation/BeeStation-Hornet pull request #6658
Opened 2022-04-12 18:40 UTC by ivanmixo

## About The Pull Request

A lizard tongue makes you hiss, an apid tongue makes you buzz instead of it being your species.

![image](https://user-images.githubusercontent.com/22431091/163030763-cbd068e0-61b4-4aca-90e2-9bcfbc1a2019.png)

## Why It's Good For The Game

You hissing while you talk should be governed by your tongue, not your species datum.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

Spawned in as all the species, got drunk, took tongue out, put different species tongue into a person, they started meowing. It just works.

</details>

## Changelog
:cl:
add: added a bunch of new tongues
tweak: moved saymods off species datums and onto tongues
/:cl:

2022-04-12 19:06 UTC, DatBoiTim requested changes
Looks good but you should probably remove say_mod from the species definition as well since now that var is entirely unused.

2022-04-12 19:13 UTC, DatBoiTim approved these changes
Excellent.

Share the sprites tho 😳 👉 👈

2022-04-12 19:45 UTC, Mat05usz commented
Murdering simplemob cats only to give humans proper say_mod incoming 😳

2022-04-15 09:50 UTC, PowerfulBacon approved these changes

2022-05-14 11:10 UTC, merged