Fixes whiteships and other shuttle ruins not loading
BeeStation/BeeStation-Hornet pull request #6667
Opened 2022-04-13 09:22 UTC by PowerfulBacon

## About The Pull Request

Fixes post-round shuttle loading.

TODO:
 - Allow for multiple of the same shuttle type to be loaded (find that dynamic shuttle PR I did a while back)

## Why It's Good For The Game

Shuttle templates do not load post-roundstart, causing whiteship and the ruin to break.

## Testing Photographs and Procedure

![image](https://user-images.githubusercontent.com/26465327/163144233-c1e6eba4-d63d-494c-abce-b0665fe39073.png)

## Changelog
:cl:
fix: Fixes post round shuttle loading.
/:cl:

2022-04-13 20:15 UTC, PowerfulBacon commented
Works fine in testmerge

2022-04-14 07:37 UTC, PowerfulBacon commented
Docking works fine

2022-04-14 20:50 UTC, Fronsis commented
Bless, thanks Bacon i'll try to see if i can find em today and check on their performances

2022-04-21 17:07 UTC, Crossedfall requested changes, later dismissed
FastDMM is no longer supported. Mappers should switch to https://github.com/SpaiR/StrongDMM

2022-04-21 17:07 UTC, Crossedfall commented on code/_compile_options.dm
> +#if !defined(CBT) && !defined(SPACEMAN_DMM) && !defined(FASTDMM)
```suggestion
#if !defined(CBT) && !defined(SPACEMAN_DMM)
```

Pull the FASTDMM stuff, that editor is no longer supported.

2022-04-22 16:59 UTC, Mails-z commented
It has been so long since I saw the white ship. I suspected it was not appearing since I could not saw it in the signals

2022-04-23 16:29 UTC, PowerfulBacon commented on code/modules/shuttle/shuttle.dm
> +
```suggestion
```

2022-04-23 16:29 UTC, PowerfulBacon commented on code/modules/shuttle/shuttle.dm
> +
```suggestion
```

2022-05-03 11:28 UTC, Archanial approved these changes

2022-05-03 11:28 UTC, merged