readds an accidentally removed feature
BeeStation/BeeStation-Hornet pull request #6756
Opened 2022-04-27 05:55 UTC by zeskorion

## About The Pull Request
re-adds anomaly core activation effects. These were added in #1218, but were later removed, i assume by accident, by #1623

## Why It's Good For The Game
readds a missing feature, noticed it was missing when checking the code for it

## Changelog
:cl:
fix: anomaly cores now have assembly activation effects again
/:cl:

2022-04-27 06:54 UTC, Tsar-Salat commented
Ah, I assumed it was simply nerfed or something.

Anomaly core in bomb assembly just reform as anomalies yes?

2022-04-27 07:26 UTC, Kapu1178 requested changes

2022-04-27 07:26 UTC, Kapu1178 commented on code/modules/assembly/signaler.dm
> +	B.Destroy()
???????????????????????

2022-04-27 10:28 UTC, Archanial commented on code/modules/assembly/signaler.dm
> +	var/type = src.anomaly_type
Why do you need src here?

2022-04-27 10:28 UTC, Archanial commented on code/modules/assembly/signaler.dm
> +	B.Destroy()
Wtf

2022-04-27 10:44 UTC, PowerfulBacon commented on code/modules/assembly/signaler.dm
> +	B.anomalyEffect()
This requires the deltaTime parameter

2022-04-27 15:41 UTC, zeskorion commented
Bleh, i just copypasted the code from the original pr,will look later

2022-04-27 16:54 UTC, PowerfulBacon commented
> Bleh, i just copypasted the code from the original pr,will look later

Original code is no longer compatible due to deltaTime changes

2022-04-29 09:13 UTC, PowerfulBacon requested changes
Address reviews

2022-05-13 00:22 UTC, closed without merging