Lighteater is now recursive
BeeStation/BeeStation-Hornet pull request #6912
Opened 2022-05-19 17:52 UTC by PowerfulBacon

## About The Pull Request

The light eater will now recursively break lights inside of things.

## Why It's Good For The Game

Someone with a flashlight in their bag will no longer be immune to nightmares/

## Testing Photographs and Procedure

testing it right now, but need to eat dinner so will update afterwards

## Changelog
:cl:
fix: Nightmare's arm blade will now destroy lights inside backpacks
/:cl:

2022-05-19 18:46 UTC, FriendlyContractor commented
Suggestion - make it also work on an item person is pulling. Its practically impossible to click on tiny light source being pulled by someone while they are moving and very cheesy way to fight nightmare. Also does this work on hardhats being worn by cyborgs ?

2022-05-19 19:02 UTC, PowerfulBacon commented
> Suggestion - make it also work on an item person is pulling. Its practically impossible to click on tiny light source being pulled by someone while they are moving and very cheesy way to fight nightmare. Also does this work on hardhats being worn by cyborgs ?

It does

2022-05-19 19:53 UTC, AnCopper commented
Small thing, but can you fix the thing where the light eater does a whack sound instead of a cutting sound? It's a blade.

2022-05-19 20:13 UTC, dannydonk commented
Does this fix helmet lights and gunlights not being broken by lighteater?

2022-05-19 20:37 UTC, PowerfulBacon commented
> Does this fix helmet lights and gunlights not being broken by lighteater?

Yes

2022-05-20 14:04 UTC, Archanial requested changes

2022-05-20 14:04 UTC, Archanial commented on code/game/atoms.dm
> +	for(var/atom/A in src)
Check contents

2022-05-20 14:50 UTC, PowerfulBacon commented on code/game/atoms.dm
> +	for(var/atom/A in src)
Isn't this the same thing?

2022-05-22 18:24 UTC, PowerfulBacon commented
uhhhhhhhhh thats a lot of signals actually
Perhaps this should just have component lights register a signal to their holder

2022-05-30 08:58 UTC, Autisem commented
Does this work with my light eater PR? may wana check that.

2022-06-02 18:23 UTC, PowerfulBacon commented
This is a terrible version of https://github.com/BeeStation/BeeStation-Hornet/pull/7014

2022-06-02 18:23 UTC, closed without merging