Simplifies and improves lone op counter
BeeStation/BeeStation-Hornet pull request #6931
Opened 2022-05-22 23:53 UTC by Rukofamicom

## About The Pull Request

Changes the lone ops counter to go up by five after five minutes of disk inactivity, instead of constantly firing abysmal chances to increase every two seconds (or not even firing chances at all when the server is lagging, because even slight lag seems to cause the disk to completely skip processing for minutes at a time)

Prevents the lone op weight from increasing until at least 30 minutes have passed, so they cannot trigger early spawns on rounds with no captain to claim disk immediately. 

## Why It's Good For The Game
Steady counter is better than whatever this nonsense was about, especially considering the disk seems prone to not processing consistently for some reason.

`

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/9547572/169721093-8ca817db-178f-44b1-874b-b4ca852790a8.png)

</details>

## Changelog
:cl:
tweak: simplified how lone op counter increments when nuclear disk is stationary
/:cl:

2022-05-23 00:03 UTC, Howluinb commented
Good pr, disk always felt like it was up to pure random chance whether it affected anything or not - i've seen many times a disk with 1 hour left alone get no lone op roll - enough to believe it isn't just bad luck.

Five minute seems a bit too slow tho. Unless the value upped by that is very high. wouldn't it be better to be every minute? Makes securing it more important as it should be ?

2022-05-23 00:19 UTC, Rukofamicom commented
> Five minute seems a bit too slow tho. Unless the value upped by that is very high. wouldn't it be better to be every minute? Makes securing it more important as it should be ?

The value goes up by 5 every five minutes. 
This means by 10 minutes idle lone op is equal to other random events. by 30 minutes it's three times as likely. 

The event will still not be guaranteed to happen if the disk is left alone (which is good), but it will more consistently present a risk if it isn't being carried around by someone, and it will start to present that risk earlier. 

`prob((world.time - 5000 - last_disk_move)*0.0001))`

This meant the disk had to be idle for almost 25 minutes before the chance even really started going up.

2022-05-23 12:33 UTC, Archanial requested changes

2022-05-23 12:33 UTC, Archanial commented on code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
> +		if(last_disk_move < world.time - 3000 && world.time > 18000)
Use time defines

2022-05-23 16:23 UTC, DerpiestBruh commented
ided

2022-05-23 16:48 UTC, Rukofamicom commented
I.. what?

I'm not even remotely sure how you can think this is an ided PR. This changes spawnrate from exponential and prone to not even incrementing into a linear growth.

2022-05-23 21:24 UTC, DerpiestBruh commented
🙂

2022-05-24 05:18 UTC, ike709 approved these changes

2022-05-24 09:08 UTC, Archanial approved these changes

2022-05-24 09:08 UTC, merged