EMP nerfs
BeeStation/BeeStation-Hornet pull request #7029
Opened 2022-06-05 16:46 UTC by PowerfulBacon

## About The Pull Request

The time that EMPs disable guns and stun batons for has been updated:
Light EMP: 0 to 10 seconds
Heavy EMP: 0 to 20 seconds

## Why It's Good For The Game

A single EMP can make any member of security unable to fight back for a very long time. This makes EMP temporarilly disable them during a fight, so that you can get a short upper hand however the other person can fight back after at most 20 seconds rather than 2 minutes.
A lot of complaints that this required the use of shotgun meta, so this should make it so you can still fight against someone with EMPs with the user of regular weapons.

## Testing Photographs and Procedure

Will do after this round.

## Changelog
:cl:
balance: Light EMPs will disable energy weapons and batons for 0-10 seconds as opposed to 30-60 seconds.
balance: Heavy EMPs will disable energy weapons and batons for 0-20 seconds as opposed to 60-120 seconds.
/:cl:

2022-06-05 17:04 UTC, AnCopper commented
> A single EMP can make any member of security unable to fight back for a very long time. 

This is literally the EXACT reason why EMP's didn't affect stun batons as much until you changed it, this is literally a problem that you yourself have created with #6135

2022-06-05 18:05 UTC, PowerfulBacon commented
Well one of the most powerful weapons in the game should have some pretty powerful downsides too. This is overall a better solution than the original.

2022-06-05 18:29 UTC, KennyBadrige commented
speedmerge

2022-06-06 07:30 UTC, Archanial requested changes, later dismissed
You can't call timers with 0 time

2022-06-06 07:30 UTC, Archanial commented on code/game/objects/items/stunbaton.dm
> +		addtimer(CALLBACK(src, .proc/emp_reset), rand(0, 200 / severity))
Possible runtime

2022-06-06 07:30 UTC, Archanial commented on code/modules/projectiles/guns/energy.dm
> +		addtimer(CALLBACK(src, .proc/emp_reset), rand(0, 200 / severity))
Possible runtine

2022-06-06 07:50 UTC, PowerfulBacon commented on code/modules/projectiles/guns/energy.dm
> +		addtimer(CALLBACK(src, .proc/emp_reset), rand(0, 200 / severity))
How?

2022-06-06 07:50 UTC, PowerfulBacon commented on code/modules/projectiles/guns/energy.dm
> +		addtimer(CALLBACK(src, .proc/emp_reset), rand(0, 200 / severity))
Oh 0 length timers

2022-06-06 07:50 UTC, PowerfulBacon commented on code/game/objects/items/stunbaton.dm
> +		addtimer(CALLBACK(src, .proc/emp_reset), rand(0, 200 / severity))
```suggestion
		addtimer(CALLBACK(src, .proc/emp_reset), rand(1, 200 / severity))
```

2022-06-06 07:51 UTC, PowerfulBacon commented on code/modules/projectiles/guns/energy.dm
> +		addtimer(CALLBACK(src, .proc/emp_reset), rand(0, 200 / severity))
```suggestion
		addtimer(CALLBACK(src, .proc/emp_reset), rand(1, 200 / severity))
```

2022-06-06 15:44 UTC, Kratairo commented
Oh no sec main pr 😔

2022-06-21 10:14 UTC, WrillWasTaken commented
I'm personally a big fan of making EMPs less common against security, it's already annoying enough when you try play IPC security and the frequent EMPing just kills you.

2022-06-23 19:42 UTC, Isy232 commented
I agree the previous was too much, but I think 0-10 or 0-20 is too little.

Perhaps 10-20 and 20-30 would be superior

Remember that EMP's used to drain energy guns almost entirely making them useless until recharged. If a heavy EMP has the chance to disable an energy gun for only a single second, most antagonists will likely not wish to use them based on their inconsistency.

There's already a lot of things that are inconsistent with antagonists, perhaps they shouldn't have to worry about their EMP not working at all.

2022-06-26 18:15 UTC, FortSumter commented
Or just give security glocks like NSV and like... you know...

Real police....

2022-06-28 07:59 UTC, PowerfulBacon commented
> Remember that EMP's used to drain energy guns almost entirely making them useless until recharged. If a heavy EMP has the chance to disable an energy gun for only a single second, most antagonists will likely not wish to use them based on their inconsistency.

Considering how powerful EMPs are, a nerf that will make people less likely to use them is a good thing in my opinion.
You are guaranteed to disable their weapons for at least a single hit, allowing you to get the upper hand, however an EMP won't immediately decide the outcome of the battle. If someone is robust and has a lot of weapons, one of their weapons is likely to reactivate very quickly, allowing them to switch to that weapon and use it (even if its not the first one they would have chosen for the situation).

2022-06-28 18:08 UTC, Rukofamicom approved these changes
Code checks out, only two lines actually changed with the rest of the "changed" lines just being cleanup of empty space. 
This review means nothing, but I feel bad about it sitting here for so long and want to see it merged :P

Regarding the balance: Extremely hard counters bad. Softer counters good.

2022-06-29 20:33 UTC, PowerfulBacon commented
What a great PR, and very good balance changes. I put my official approval on this PR :+1:

2022-07-04 17:53 UTC, ike709 approved these changes

2022-07-04 17:53 UTC, merged