Players who suicide or cryo are not elegible for Antagonist roles for 5 minutes
BeeStation/BeeStation-Hornet pull request #7156
Opened 2022-06-30 18:48 UTC by Miliviu

## About The Pull Request

When a player dies or cryogenizes, or simply ghosts themselves they cannot participate in voting to be an antagonist for 5 minutes.

## Why It's Good For The Game

Preventing people from committing suicide when a round of Nukies is announced

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
![image](https://user-images.githubusercontent.com/45698448/176753320-842cb62c-2351-4dda-925e-64ef09ce8178.png)
After ghosting I can't see the Poll to be Wizard

![image](https://user-images.githubusercontent.com/45698448/176754663-a6a3bbd6-78c4-484d-81e2-5283adf6ae2c.png)
A few minutes later I'm able to vote Yes in the poll!

(If more testing is needed lmk and I will record some videos)
</details>

## Changelog
:cl:
add: 5 Minutes check to be elegible in Ghost Roles
/:cl:

2022-06-30 18:55 UTC, PowerfulBacon commented on code/__HELPERS/game.dm
> +		if(G.creation_time + 3000  < world.time) // Prevents people who have just died from becoming Antagonists
This should probably be a config setting

2022-06-30 18:59 UTC, Miliviu commented on code/__HELPERS/game.dm
> +		if(G.creation_time + 3000  < world.time) // Prevents people who have just died from becoming Antagonists
I can do that, yeah

2022-06-30 20:00 UTC, PowerfulBacon commented on code/__HELPERS/game.dm
> +		var/cooldown_time = (CONFIG_GET(number/cooldown_antag_time) * 60) * 10
```suggestion
		var/cooldown_time = CONFIG_GET(number/cooldown_antag_time) MINUTES
```

2022-06-30 20:00 UTC, PowerfulBacon commented on code/controllers/configuration/entries/game_tweaks.dm
> +	min_val = 1
3000 would be 3000 minutes.
Default value should be 0.
Minimum value should be 0 (disabled).

2022-06-30 20:03 UTC, Miliviu commented on code/controllers/configuration/entries/game_tweaks.dm
> +	min_val = 1
OH, yeah, you are totally right, I missed this file in the last commit, tysm

2022-06-30 21:12 UTC, mcmeiler commented
????

You realize antag positions as ghosts are so god damn rare this is pointless?

Additionally, cryoing or suiciding with the explicit purpose to roll for ghost antags is against the rules.

2022-06-30 21:45 UTC, Miliviu commented
> ????
> 
> You realize antag positions as ghosts are so god damn rare this is pointless?
> 

Although this works for all Ghost Antags, I believe Bacon explicitly requested it for the Nukies rounds.

> Additionally, cryoing or suiciding with the explicit purpose to roll for antags is against the rules.

Yes, I know! I imagine this suicide thing is a common problem in nukies war rounds, and to avoid an admin having to waste time looking at who "commits suicide" is a positive change! (all this is my opinion ofc)

> 
> Ghost roles also take more than 5 minutes to appear on average.

I think you are totally right, and the time can be increased if necessary.


And if you all, from the administrative team see that it is an unnecessary/negative change, then I'll close the PR happily!
Thanks for the feedback!

2022-06-30 22:27 UTC, MNarath1 requested changes

2022-06-30 22:27 UTC, MNarath1 commented on code/__HELPERS/game.dm
> +		if(G.creation_time + cooldown_time < world.time) // Prevents people who have just died from becoming Antagonists
Use the cooldown macro instead here

2022-06-30 22:27 UTC, MNarath1 commented on code/__HELPERS/game.dm
> +		if(G.creation_time + cooldown_time < world.time) // Prevents people who have just died from becoming Antagonists
it does the same stuff but is way better here for this usecase you can find it in the cooldown.dm file under `code\__DEFINES\cooldowns.dm` from line 63 to end use those instead.

2022-06-30 23:19 UTC, mcmeiler commented
> Yes, I know! I imagine this suicide thing is a common problem in nukies war rounds, and to avoid an admin having to waste time looking at who "commits suicide" is a positive change! (all this is my opinion ofc)

I've done this whole adminning thing for a decent while now. I've literally never once seen a person suicide on a nuke op round.

> I think you are totally right, and the time can be increased if necessary.

What I'm saying is, this is pointless to begin with. This sort of behavior will still be punished either way.

2022-07-01 05:50 UTC, Miliviu commented
> > Yes, I know! I imagine this suicide thing is a common problem in nukies war rounds, and to avoid an admin having to waste time looking at who "commits suicide" is a positive change! (all this is my opinion ofc)
> 
> I've done this whole adminning thing for a decent while now. I've literally never once seen a person suicide on a nuke op round.

Yeah, you are the Head Admin here! tysm for the feedback again!

> 
> > I think you are totally right, and the time can be increased if necessary.
> 
> What I'm saying is, this is pointless to begin with. This sort of behavior will still be punished either way.

Awesome then! @PowerfulBacon should I close this?

2022-07-01 05:54 UTC, mcmeiler commented
Quick reminder, this is just my opinion. I have no authority over code related things. All I'm saying is pointless suicide and/or antag rolling will still get you punished, even with this in place.

2022-07-01 06:07 UTC, Miliviu commented
> Quick reminder, this is just my opinion. I have no authority over code related things. All I'm saying is pointless suicide and/or antag rolling will still get you punished, even with this in place.

Yeah! I know! but what you are saying makes a lot of sense! and it is a VERY administration related topic, so you and other members of the team are the best people to give your opinion on this topic!

2022-07-01 07:21 UTC, PowerfulBacon commented
The reason for the issue being made I'd because I saw this happening, it wasn't out of the blue.
It is very difficult to tell if someone is going to cryo on war ops because they are antag rolling instead of them just not wanting to play war ops. I've seen this happening multiple times without admins noticing usually because war ops is interesting and admins are also trying to play, so aren't looking out for things like this and because there is almost no way that they can tell someone is doing this if they just type ghost because its invisible.
The other advantages of this is that characters will have a 5 minute period where they won't be recently dead then change body during revival and ghosts that are there for longer will get the antag positions rather than someone who recently died.
Worst comes to worst, there isn't a reason not to have this, especially since its a config option.

2022-07-01 08:42 UTC, PowerfulBacon reviewed
Just did some thinking, and this probably shouldn't affect people who observe from roundstart.

2022-07-01 08:48 UTC, Miliviu commented
> Just did some thinking, and this probably shouldn't affect people who observe from roundstart.

nukies do not usually call for reinforcements in the first 5 minutes of the round...

I'll think a fix anyway

2022-07-01 09:19 UTC, MNarath1 requested changes

2022-07-01 09:19 UTC, MNarath1 commented on code/__HELPERS/game.dm
> +		if(G.creation_time + cooldown_time < world.time) // Prevents people who have just died from becoming Antagonists
```suggestion
		if(COOLDOWN_FINISHED(G, creation_time)) // Prevents people who have just died from becoming Antagonists
```

2022-07-01 09:19 UTC, MNarath1 commented on code/modules/mob/dead/observer/observer.dm
> +	var/creation_time
```suggestion
	COOLDOWN_DECLARE(creation_time)
```

2022-07-01 09:19 UTC, MNarath1 commented on code/__HELPERS/game.dm
> +		var/cooldown_time = CONFIG_GET(number/cooldown_antag_time) MINUTES
```suggestion
```

2022-07-01 09:19 UTC, MNarath1 commented on code/modules/mob/dead/observer/observer.dm
> +	creation_time = world.time
```suggestion
	 COOLDOWN_START(src, creation_time , (CONFIG_GET(number/cooldown_antag_time) MINUTES))
```

2022-07-01 09:19 UTC, MNarath1 commented on code/modules/mob/dead/observer/observer.dm
> +	creation_time = world.time
i still don't quite like the CONFIG_GET here maybe you could instead make it a static variable on the observer and grab it only once with an if instead but except for that i think this should be a better solution.

2022-07-01 09:30 UTC, MNarath1 commented on code/modules/mob/dead/observer/observer.dm
> +	creation_time = world.time
now this should not be an issue anymore

2022-07-01 10:06 UTC, PowerfulBacon approved these changes

2022-07-03 13:30 UTC, Crossedfall approved these changes
Config applied

2022-07-03 13:31 UTC, merged