Ports Antagonist tips from Hippie Station
BeeStation/BeeStation-Hornet pull request #716
Opened 2019-11-04 11:41 UTC by Cenrus

https://github.com/HippieStation/HippieStation/pull/12023

Far better than our current system, and actually functions as a tutorial. I'll add more tutorials for each antagonist in the future.

:cl: Steamp0rt and Lunaman
add: Improved antagonist tutorial
/:cl:

2019-11-04 15:27 UTC, Cenrus commented
Needs review

2019-11-04 17:10 UTC, MarkSuckerberg requested changes
Some things I think need addressed

2019-11-04 17:10 UTC, MarkSuckerberg commented on code/modules/antagonists/_common/antag_popup.dm
> -	popup_title = "You are a blob!"
Some of these should be either left, or new pages need to be added as not all bee antags have pages, and although some don't really need individual pages, others such as blob do. What was here already at least includes a wiki page, which is better than nothing.

2019-11-04 17:10 UTC, MarkSuckerberg commented on html/antagtips/abductor.html
> +	<p>People wearing <b>tinfoil hats</b> are immune to abductor batons.</p>
Would be nice to include a wiki page link here in my opinion

2019-11-13 23:01 UTC, ike709 approved these changes

2019-11-13 23:13 UTC, Crossedfall commented
Test merged onto Golden

2019-11-14 00:08 UTC, Crossedfall approved these changes
Worked within the test merge

2019-11-14 00:08 UTC, merged