Derelict Shuttle Ruins - Custom shuttle persistance (Reborn edition)
BeeStation/BeeStation-Hornet pull request #7184
Opened 2022-07-03 17:21 UTC by PestoVerde322

## About The Pull Request

This PR aims at bringing back a PR done by @PowerfulBacon (https://github.com/BeeStation/BeeStation-Hornet/pull/5367) since now the Cross-server communication is alive again.

All you need to know about this is in the link, so check it out!

## Why It's Good For The Game

Hard work can persist across multiple rounds, new ruin types that are truely random and you never know what you might come across, and hey, maybe with the supercruise, you can scrap some shuttles you come across for... fun!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Soon, I'm still sorting out how to put the PR's details down, it's still in draft after all!

</details>

## Changelog
:cl:
add: Adds in derelict shuttle ruins, custom shuttles from previous rounds
code: Significantly improves the map save proc.
config: Adds in new config options related to shuttle saving.
/:cl:

2022-07-03 17:23 UTC, PowerfulBacon commented
This didn't actually rely on cross-server comms, it uses local files for storage

2022-07-10 18:17 UTC, Crossedfall commented
reloading checks

2022-07-10 19:25 UTC, PowerfulBacon commented
Does saving ignore holographic items?

2022-07-12 11:05 UTC, PowerfulBacon commented
This basically worked when last testmerged, so I'm fine to put it on again.
There are some things that need consideration:

 - Changes to typepaths / things being deleted that are saved.
 - APCs creating millions of terminals

2022-07-12 11:27 UTC, PowerfulBacon commented on config/config.txt
> +
(This was never actually removed from config, so config changes don't need to be applied.)

2022-07-12 11:48 UTC, PowerfulBacon requested changes
We need to check all map files and ensure that there are no invalid typepaths in any of the maps. Any maps that have invalid paths need to be deleted.
This should be done on init.

2022-07-12 11:58 UTC, PowerfulBacon requested changes
Some things I noticed.
This needs a script to check that flags aren't being overriden accidentally for review.

2022-07-12 11:58 UTC, PowerfulBacon commented on code/modules/clothing/shoes/colour.dm
> +	return ..()
This is weird

2022-07-12 11:58 UTC, PowerfulBacon commented on code/__DEFINES/flags.dm
> +#define SAVE_SAFE_1					(1<<17)		//! Marks an item as being safe to save. Anything ridiculous or will not work if spawned on a map should not be given this flag.
This is invalid, needs to be 1<<19

2022-07-12 20:23 UTC, PestoVerde322 commented on code/modules/clothing/shoes/colour.dm
> +	return ..()
This is very likely a leftover from the pre-gags era.

2022-07-31 09:22 UTC, PestoVerde322 commented
Reminder that this needs strong TMing before being merged.

2022-08-10 18:29 UTC, PowerfulBacon commented
What are we doing about the old maps that contain outdated things in them?

2022-09-29 13:15 UTC, PowerfulBacon commented
time for this to die again :pensive:

2022-10-05 00:30 UTC, closed without merging