Mixing meth and mannitol now makes toxin (This time without pushing to the master)
BeeStation/BeeStation-Hornet pull request #7200
Opened 2022-07-04 20:31 UTC by PestoVerde322

## About The Pull Request

Makes mixing meth and mannitol synthesize a brand new drug, Methnitol, while it is the bridge between abusing massive amount of methamphetamines and mannitol, this new drug packs it all in one chem, at the cost of a dramatic addiction and a soulcrushing overdose.

## Why It's Good For The Game

This aims to address at the current meta for chemists where they make pills of 9u meth + as much mannitol as they can pack for good measure. This makes the mix not only more dangerous, but also more tricky and limited to use.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

![immagine](https://user-images.githubusercontent.com/75247747/177210722-2f632d92-a853-4e6a-ab6d-d2b956125294.png)

![immagine](https://user-images.githubusercontent.com/75247747/177210753-d83b8d94-7c5a-4bb9-9611-338bacb613f1.png)

</details>

## Changelog
:cl:
add: Added a brand new chem, Methnitol, a mix of 1:1 of meth and mannitol
/:cl:

2022-07-04 20:33 UTC, ivanmixo commented on code/modules/cargo/bounties/reagent.dm
> +		/datum/chemical_reaction/methnitol,\
Needs the datum for the reagent, not the reagent reaction.

2022-07-04 22:37 UTC, EvilDragonfiend commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	M.adjustToxLoss(1, 0)
Flag True toxin for oozelings? (Including other lines)

2022-07-04 22:37 UTC, EvilDragonfiend commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			step(M, pick(GLOB.cardinals))
It will force you to move every tick. Need prob.

2022-07-04 22:37 UTC, EvilDragonfiend commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	..()
Why are you calling the parents at the middle of the metabolisation?

2022-07-04 22:37 UTC, EvilDragonfiend commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	M.confused = (2)
This will make confused fixed to 2. Misplaced equal operator?

2022-07-04 22:37 UTC, EvilDragonfiend commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			step(M, pick(GLOB.cardinals))
Same above.

2022-07-04 22:37 UTC, EvilDragonfiend commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			step(M, pick(GLOB.cardinals))
Same above

2022-07-04 22:37 UTC, EvilDragonfiend commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	var/high_message = pick("You feel hyper, yet focused.", "You feel like you need to go faster, yet concentrated.", "You feel like you can run the world, yet be knowledgable.")
I think i wojld put declare this inside of the if prob

2022-07-04 22:37 UTC, EvilDragonfiend commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	. = 1
Why do you need to return 1?

2022-07-05 00:35 UTC, DerpiestBruh commented
based.

2022-07-05 05:27 UTC, heepox commented
new chem good.

2022-07-09 21:19 UTC, FortSumter commented
Can't wait to fill the cryo tubes with it.

2022-07-23 08:12 UTC, PowerfulBacon requested changes
See [EvilDragonfiend](https://github.com/EvilDragonfiend)'s reviews

2022-10-05 00:30 UTC, closed without merging

2022-10-05 00:37 UTC, EvilDragonfiend commented
Actually the game needs chem refactor first.