Fixes duplication bug that allows to obtain infinite glass and cable by disassembling and reassembling Disco Tiles
BeeStation/BeeStation-Hornet pull request #7216
Opened 2022-07-06 20:54 UTC by Miliviu

## About The Pull Request

fixes #7206
Now, when assembling a Disco Tile, the wired tile disappears after being used.

## Why It's Good For The Game

We don't want infinite glass and cable coil!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
Before: 

https://user-images.githubusercontent.com/45698448/177639819-a50cb2ca-898c-4258-8ee9-7fd24cca6788.mp4

After:

https://user-images.githubusercontent.com/45698448/177639957-a6e57932-b46d-45cc-b25b-33e1de55d1aa.mp4

</details>

## Changelog
:cl:
fix: Fixed being able to get infinite glass and wires disassembling Disco Tiles
/:cl:

2022-07-08 09:29 UTC, Dejaku51 reviewed
wouldn't this delete entire stack?

2022-07-09 18:34 UTC, PowerfulBacon requested changes
See Dejaku's review

2022-07-09 18:38 UTC, Miliviu commented
> See Dejaku's review

I'm aware and I'll post the fix soon!

2022-07-29 18:34 UTC, PowerfulBacon commented
fix was never posted 😔

2022-07-29 19:42 UTC, Miliviu commented
> fix was never posted 😔

I forgor 💀

2022-08-04 00:22 UTC, closed without merging

2022-08-04 00:31 UTC, itsmeow commented
why was this closed

2022-08-04 00:50 UTC, Dejaku51 commented
because it was stale