Security level change is now handled by signals
BeeStation/BeeStation-Hornet pull request #7234
Opened 2022-07-09 10:12 UTC by Dejaku51

## About The Pull Request
Makes it so security alert changes are handled by signal instead of just looping multiple times
Also changes set_security_level() code so it has early return instead of entire code being in if statement

Closes #6757 
## Why It's Good For The Game
Requested by @PowerfulBacon 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

1. Change security level to blue
2. Fire alarm light turns blue
3. Change security level to green
4. Fire alarm light turns green

## Changelog
:cl:
code: set_security_level() now uses signals instead of multiple loops
/:cl:

2022-07-09 18:33 UTC, PowerfulBacon requested changes

2022-07-09 18:33 UTC, PowerfulBacon commented on code/modules/shuttle/emergency.dm
> +	admin_controlled = (new_alert > SEC_LEVEL_RED)
Is this right?

2022-07-09 18:33 UTC, PowerfulBacon commented on code/game/machinery/doors/door.dm
> +	if(new_alert <= SEC_LEVEL_RED )
Is this correct?

2022-07-09 22:00 UTC, Dejaku51 commented on code/modules/shuttle/emergency.dm
> +	admin_controlled = (new_alert > SEC_LEVEL_RED)
wait... fuck

2022-07-09 22:18 UTC, Dejaku51 commented
i hate myself

2022-07-09 22:18 UTC, Dejaku51 commented on code/game/machinery/doors/door.dm
> +	if(new_alert <= SEC_LEVEL_RED )
should be good now

2022-07-09 22:18 UTC, Dejaku51 commented on code/modules/shuttle/emergency.dm
> +	admin_controlled = (new_alert > SEC_LEVEL_RED)
should be good now

2022-07-10 09:14 UTC, PowerfulBacon approved these changes
Looks good :+1:

2022-07-10 18:54 UTC, merged