Allow invisible mobs to hear speech in range
BeeStation/BeeStation-Hornet pull request #7241
Opened 2022-07-10 09:02 UTC by itsmeow

## About The Pull Request

Fixes #6587
Fixes #7240

- Fixes invisible mobs being unable to hear speech (AI with surveillance upgrade, revenant)

## Why It's Good For The Game

Invisible mobs not being able to hear speech is bad

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

**AI Eye speech**
![image](https://user-images.githubusercontent.com/10366817/178137946-44e8df8f-a091-4255-9d9a-b51445b38984.png)

**AI eye speech (out of range)**
![image](https://user-images.githubusercontent.com/10366817/178137951-853f9a26-8078-49a5-85f6-451d816eef6f.png)

**Revenant**
![image](https://user-images.githubusercontent.com/10366817/178137965-469b766a-8b1a-4449-a9ee-58b538971959.png)

Tested ghost speech as well, it's unaffected by this and still obeys user preference including range preference.
</details>

## Changelog
:cl:
fix: Invisible mobs can now hear speech (includes revenant, AI eye with surveillance upgrade)
/:cl:

2022-07-10 09:12 UTC, PowerfulBacon commented on code/modules/mob/living/say.dm
>  		listening |= M
Isn't this redundant now?

2022-07-10 09:13 UTC, PowerfulBacon commented on code/modules/mob/living/say.dm
>  		listening |= M
Nvm, its not since ghosts can hear at any range

2022-07-10 09:14 UTC, PowerfulBacon approved these changes

2022-07-10 09:24 UTC, itsmeow commented
Not sure if this would have unintended effects on blob overmind or clockcult eminence eyes

2022-07-10 09:25 UTC, PowerfulBacon commented
Blob overmind and eminence should be able to hear

2022-07-10 09:30 UTC, itsmeow commented
![image](https://user-images.githubusercontent.com/10366817/178139125-da8b3299-9e3b-4ed0-b276-0ffb83fab722.png)
Appears over head but not in chat, not sure if intended

2022-07-10 10:04 UTC, PowerfulBacon commented
That's probably not intended, most likely a quirk with the overhead chat system. The overmind I don't think is meant to hear actually.

2022-07-10 10:18 UTC, itsmeow commented
Should I attempt to fix or leave it? Not sure if it happens without the changes

2022-07-10 18:23 UTC, PowerfulBacon commented
I think it should be fixed, since it should be overriding the Hear() anyway.

2022-07-12 19:39 UTC, PowerfulBacon requested changes
Blob overmind having weird interactions needs to be fixed

2022-07-13 20:13 UTC, LodedDiper69 commented
Does this work with imaginary friends too? They're also having the same bug

2022-07-13 20:45 UTC, itsmeow commented
Unexpected behavior due to the `say`ing atom lacking a client, therefore blob functions as expected and can hear. Should be GTM

2022-07-13 20:47 UTC, itsmeow commented
@LodedDiper69 I have no conceivable way of testing this locally but it should hopefully work

2022-07-16 07:56 UTC, PowerfulBacon approved these changes

2022-07-16 07:56 UTC, merged