Facehuggers now work on corpses
BeeStation/BeeStation-Hornet pull request #7265
Opened 2022-07-13 22:28 UTC by Rukofamicom

## About The Pull Request

Makes facehuggers work on dead players to invalidate the metagame-y strategy of suicide/succumbing early. 

## Why It's Good For The Game

Metagaming antags bad

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/9547572/178847377-fc33ae82-48d6-46b0-a46b-dd4725566df7.png)

</details>

## Changelog
:cl:
tweak: facehuggers now work on dead crew members. Suicide is not badass, it's metagaming. 
/:cl:

2022-07-13 23:02 UTC, AnCopper commented
Well, on CM and TGMC they negate this issue by not having a succumb mechanic in the first place.

2022-07-13 23:05 UTC, ivanmixo commented
Straight up a lie, but okay.

2022-07-13 23:08 UTC, EvilDragonfiend commented
use death timer, and make it available when its death happened within 3~5 minutes

2022-07-13 23:15 UTC, zeskorion commented
> ## About The Pull Request
> Makes facehuggers work on dead players to invalidate the metagame-y strategy of suicide/succumbing early.
> 
> ## Why It's Good For The Game
> Metagaming antags bad. Was requested on the forums [here](https://forums.beestation13.com/t/xenomorphs/18933?u=ruko) (There's some relevant back and forth discussion in the thread)
> 
> ## Testing Photographs and Procedure
> Screenshots&Videos
> ## Changelog
> 🆑 tweak: facehuggers now work on dead crew members. Suicide is not badass, it's metagaming. /🆑

this is a bad idea. Right now, xenos are incentivized to capture players alive, especially with their nonlethal takedowns, leading to interesting and tense gameplay. This will incentivize xenos to kill players, because corpses cannot escape, leading to disengaging gameplay for players

2022-07-14 01:43 UTC, Pirill commented
Not a big fan. Facehugging someone makes them vulnerable for a good while during which they can be easily captured alive and, even ignoring that, you can practically permanently stun someone you're dragging with tackles from what I recall. Succumbing because they beat you into crit first is cheap but at that point it's kind of a skill issue on the xenos' part.

2022-07-14 02:02 UTC, itsmeow commented
Better idea: Deathgasp enables a 1 minute timer where they can still be facehugged instead

2022-07-14 02:38 UTC, Sinestia requested changes
I think a better way to do this would be to check organ integrity so that *very* recent deads can still be hugged, but older corpses past a couple minutes would be unusable.

2022-07-14 04:04 UTC, silencer-pl commented
> Well, on CM and TGMC they negate this issue by not having a succumb mechanic in the first place.

The hugging and death mechanics on CM at least are way different than just this to serve as a point of comparison. No xeno with decent experience on their hands on CM would waste their time hugging someone in hardcrit (whey then can deathgasp) anyway since permaing while implanted kills the embryo. In fact while capping as xeno you need to SPECIFICALLY be careful not to hit them too much because you don't want them to crit. Deathgasping would actually make it easier for xenos to tell they are not going to make it and have them not have to bother with their near dead body.

This somewhat long prelude leads me to my main gripe with this:

I'm not sure why xenos need an ever easier time at getting more numbers. I would say that if you cannot incapacitate your prey to hug and nest them without hardcritting them, its a moderate skill issue and is intended. I haven't actually played Xeno on Bee because I get enough of xenomorph related shenanigans on CM but hugging seems to work the same way? Tackle someone, throw a facehugger, drag off to hive while they are incapacitated by the face hugger to nest. If you do it right, the victim is boned the moment you trip him the first time.

2022-07-14 05:27 UTC, bluezorua commented
xenos are an awful fucking antag and should just be nuked from the codebase

2022-07-14 09:44 UTC, Rukofamicom commented
> Right now, xenos are incentivized to capture players alive,

I'd argue that right now Xenos are just encouraged to heavily rely on monkeys actually. Targetting players for infection isn't preferable at all despite the faster gestation, and it's not even viable for Xenos to get started without relying on both heavy stealth and monkeys at the beginning because of the continual nerfs to Xeno combat capabilities. 

> should just be nuked from the codebase

Says the mentor who directly advocates metagaming them with succumbing 🤡

---

Going through alternative ideas in addition to what's been mentioned here right now.

2022-07-14 18:37 UTC, FortSumter commented
How about instead we:
1. Nerf using monkies as hosts even harder
2. Allow xenos to throw everything a human can 
3. Add a CD to the xenos tackling someone so they can't permastun
4. Make xenos more resistant to fire or at least heat damage
5. Make people who suicide incapable of taking ghost spawns for ~5 minutes
6. Make xenos not entirely space immune so they can't just hang out in the void forever
7. Give xenos limbs so we can properly shoot their limbs off
8. Make it take WAY longer for a drone to become a queen when after the first queen died

Xenos are a midround antag and can be brought to the station by explorer crew or anyone with a shuttle and enough determination. I don't think their job should be any easier considering how common they are and I really hate how they're an automatic shuttle call because killing the queen doesn't mean anything when it takes them only 3 minutes or so to have a new queen ready to stop the shuttle from leaving and force the crew to spend half an hour chasing it down to finally kill it. 

What they need is a complete rebalance and I'd even consider removing them temporarily until some does rebalance them.

2022-07-17 16:04 UTC, Oscari-pog commented
> 7. Give xenos limbs so we can properly shoot their limbs off

If a xeno loses a leg and manages to somehow get away are they just done for? Because, unlike crew, you cant just screw on a new leg.

2022-07-17 16:35 UTC, PowerfulBacon commented
This is too much, if you want to remove succumb cheese, add a time limit for succumbing after you go crit (You need to wait 30 seconds before succumbing). Succumb cheesing affects more than just xenos and is pretty bad for the game if someone isn't trying to kill you, but at the same time we don't want to block people who are stuck in crit and not dying.

2022-07-17 16:35 UTC, closed without merging