Revenants can strip again, but it makes them visible
BeeStation/BeeStation-Hornet pull request #7280
Opened 2022-07-15 22:32 UTC by Rukofamicom

## About The Pull Request

* Allows specifically revenants to strip people again, but doing so makes them visible for at least as long as the item would take to strip, even if the stripping is interrupted. 
* Revenants are unable to strip more than one item at a time. 

## Why It's Good For The Game

This was a really fun bug, as shown by the feedback when it was fixed. I definitely agree a counterbalance needed to be added for the ability to remain however, and so I've done that by making the revenant vulnerable while stripping and reducing their ability to fullstrip people who look away for just a moment. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Double checked and other mobs still can't strip during jaunts, no image to show since... there's nothing to show for this at all

### Revenant strip demonstration:
* Shoes take less time to strip than the minimum reveal time: so revenant stays revealed after stripping for a bit
* Carapace takes longer to strip than minimum reveal time: Revenant stays revealed just long enough to strip it
* Stripping is interrupted: Revenant stays revealed for the full duration they were committed to. 
* Revenant cannot strip multiple items at once
 
 ![8l4EqbKWFk](https://user-images.githubusercontent.com/9547572/179319648-e5520839-188b-4798-a9a4-898f0f8ded81.gif)

</details>

## Changelog
:cl:
add: Revenant stripping bug is now a feature! However, revenants are revealed while stripping items and can only strip one item at a time. 
/:cl:

2022-07-15 22:47 UTC, EvilDragonfiend commented
I think they should reveal when they success to strip, not during stripping.

2022-07-16 09:43 UTC, PowerfulBacon requested changes
This method won't fly, it's too much snowflake code with the code handling all mobs having a specific check for revenants.

2022-07-16 09:43 UTC, PowerfulBacon commented on code/datums/elements/strippable.dm
> +		ghostie.reveal(max(item.strip_delay, 25))
This is pure snowflake code

2022-07-16 09:43 UTC, PowerfulBacon commented on code/datums/elements/strippable.dm
> +		if(L.incorporeal_move && !isrevenant(L))
And this

2022-07-16 19:09 UTC, Rukofamicom commented
Is there a particular way you want me to implement it instead? Make a dedicated ability specific to revenants with copy/pasted item stripping code?

2022-07-17 08:10 UTC, PowerfulBacon commented
Whatever the method it should be somewhat contained within the revenant file.
An ability that works like the light shock would probably be best, since then you have a little bit of range to not get undtantly punched to death

2022-07-17 20:35 UTC, Mat05usz commented
> I think they should reveal when they succeed to strip, not during stripping.

No, if you choose to actually ineract with the material world, you should be revealed. Fuck people who spam stripping just to annoy the fuck out of you for 20 minutes.

2022-07-17 21:06 UTC, Rukofamicom commented
> No, if you choose to actually ineract with the material world, you should be revealed.

I strongly agree with this. 

If I have to make it a dedicated ability, it's going to make you visible while it's in progress, not after it has done its effect.

2022-07-17 21:37 UTC, Rukofamicom commented
I think I'm just going to make the jaunt toggleable, drafting while that's in progress.

2022-07-17 22:01 UTC, Rukofamicom commented
Actually nah, I'm just gonna start fresh.

2022-07-17 22:01 UTC, closed without merging