Abductees no longer get deep rooted trauma once given objectives
BeeStation/BeeStation-Hornet pull request #7311
Opened 2022-07-19 19:44 UTC by Hardly3D

## About The Pull Request

This PR removes the random deep rooted trauma abductees gain from being sent back to the station by abductors.

## Why It's Good For The Game

It's just not fun for the abductee to end up having to deal with traumas that are most likely going to impair them, making them stutter, dumb, have cough fits or muscles spasms for the rest of the round unless they rush to medbay for a lobotomy surgery which will confirm the existence of abductors most of the time.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: Hardly
tweak: Abductees no longer get random deep rooted traumas
/:cl:

2022-07-19 19:46 UTC, Oscari-pog commented
Wait so are you making the traumas mild, and therefore treatable instantly with Neurine, or am I reading this wrong

2022-07-19 19:55 UTC, Hardly3D commented
> Wait so are you making the traumas mild, and therefore treatable instantly with Neurine, or am I reading this wrong

Nope, it's been outright removed, you can still get traumas from the trauma gland however.

Might as well edit the PR for better wording.

2022-07-19 22:22 UTC, FortSumter commented
I like this change. It didn't make sense to me that they gave you debilitating traumas on top of making you insane.

2022-07-22 10:18 UTC, Sapfearon commented
Maybe this makes abductors less cancer. Right now about 50% of abductor victums just ghost after being cuffed, since random DEEP ROOTED OR PERMANENT trauma can pretty much round remove you anyway.

2022-07-22 17:34 UTC, FortSumter commented
I dont think there's much anyone can do to not make them cancerous xD

2022-07-29 18:03 UTC, PowerfulBacon requested changes
Requires testing evidence

2022-09-01 06:22 UTC, itsmeow commented
Considering it's been a month and no testing evidence, and that it's a two line change that shouldn't really need testing (it's very obvious) - I say in this one case we can waive the testing requirement...

2022-09-01 06:23 UTC, itsmeow approved these changes

2022-09-04 08:22 UTC, PowerfulBacon approved these changes

2022-09-04 08:23 UTC, merged