Adds a few new emotes
BeeStation/BeeStation-Hornet pull request #7316
Opened 2022-07-20 02:38 UTC by etherware-novice

## About The Pull Request
Adds 3 new emotes I felt were needed for good roleplaying (thumbs up, down, and whistle)

## Why It's Good For The Game
immersion

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Added the 3 new emotes
/:cl:

2022-07-20 07:16 UTC, Fronsis commented
Do we have already have the one where you can *slap a table? [As seen here time stamped in the video](https://youtu.be/zVyvUF25pgg?t=1215) Or the one where you crack your knuckles! those two are very good imo

2022-07-20 14:24 UTC, etherware-novice commented
i could add them to this if they arent already in? i just added a few i would like

2022-07-21 17:19 UTC, PowerfulBacon requested changes
PR body is incomplete. All sections must be filled out with appropriate information. Testing evidence is required even for small PRs.

2022-07-21 17:20 UTC, etherware-novice commented
what should i put for testing evidence?

2022-07-22 16:59 UTC, PowerfulBacon commented
Just a screenshot of you using them and the output in the chat.

2022-07-22 19:30 UTC, LodedDiper69 commented
You should let people not be able to thumbs up when they have no arms

2022-07-22 21:51 UTC, PowerfulBacon approved these changes, later dismissed

2022-07-22 21:52 UTC, PowerfulBacon commented on code/modules/mob/living/emote.dm
> +	return 'sound/items/megaphone.ogg'
This probably will sound very strange in game, since its an electronic sound rather than a whistle sound.

2022-07-23 00:42 UTC, etherware-novice commented
> You should let people not be able to thumbs up when they have no arms

hhow do i do that?

2022-07-29 18:02 UTC, PowerfulBacon commented
Not sure, there should be an emote saying can use. Check high five or another arm emote like salute

2022-07-31 09:14 UTC, PowerfulBacon approved these changes

2022-07-31 09:14 UTC, merged