Fix buckling crew
BeeStation/BeeStation-Hornet pull request #7353
Opened 2022-07-24 09:46 UTC by itsmeow

## About The Pull Request

Cannot buckle people, bad

## Why It's Good For The Game

Fix bug

## Testing Photographs and Procedure

![image](https://user-images.githubusercontent.com/10366817/180641495-c8dfc93f-6462-4064-9b91-a9826b5513ce.png)

## Changelog
:cl:
fix: Can buckle people to stuff again
/:cl:

2022-07-24 09:54 UTC, PowerfulBacon requested changes
Fix the can_buckle proc or remove it entirely

2022-07-24 09:56 UTC, itsmeow commented
`can_buckle` is intended for use when ACTUALLY BUCKLING someone, not BEING buckled

2022-07-24 10:38 UTC, PowerfulBacon commented
![image](https://user-images.githubusercontent.com/26465327/180643314-84767067-014d-4d60-93b8-cfe8e42810a7.png)

Can buckle checks if it can be buckled to something, the variable can_buckle indicates if something can be buckled to it (Which is very confusing).

2022-07-24 15:01 UTC, itsmeow commented
Tested on new code, works

2022-07-24 16:07 UTC, PowerfulBacon commented on code/modules/mob/living/living.dm
>  	return TRUE
Just remove this

2022-07-25 06:54 UTC, PowerfulBacon approved these changes

2022-07-25 06:54 UTC, merged