Adds inspect text for the title screen
BeeStation/BeeStation-Hornet pull request #7367
Opened 2022-07-25 15:53 UTC by etherware-novice

## About The Pull Request
You can now inspect the title/splash screen for a nice little set of messages

## Why It's Good For The Game
Adds something to do while the game is loading, also more examine text is always nice

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![titleinspect](https://user-images.githubusercontent.com/73374039/180821481-78232c88-a2ec-4d2d-8887-0b240d284596.png)

</details>

## Changelog
:cl:
add: Added inspect text for the splashscreen turf
/:cl:

2022-07-25 15:54 UTC, PowerfulBacon commented
can new_players even examine?

2022-07-25 15:55 UTC, etherware-novice commented
if you right click and hit examine yea

2022-07-25 17:45 UTC, FortSumter commented
I like Easter eggs

2022-07-25 20:10 UTC, etherware-novice commented
same ^^

2022-07-26 17:01 UTC, Crossedfall requested changes
Convert your list into a string file and pick from that instead. Similar to tips and other configurable string files https://github.com/BeeStation/BeeStation-Hornet/blob/ef0cbd8ddcea727048bde01b0f44d7a3a6cd7471/code/__DEFINES/configuration.dm#L23-L42

2022-07-26 17:47 UTC, Crossedfall requested changes
Partway there. I linked to how I wanted you to do it. Make the file a JSON, set it as a config DEFINE, and then pull from it. Added examples below.

https://github.com/BeeStation/BeeStation-Hornet/blob/master/strings/redpill.json
https://github.com/BeeStation/BeeStation-Hornet/blob/ef0cbd8ddcea727048bde01b0f44d7a3a6cd7471/code/__DEFINES/configuration.dm#L35
https://github.com/BeeStation/BeeStation-Hornet/blob/0c500f3c39509c98a0d5c931b81c45333624148f/code/modules/reagents/reagent_containers/pill.dm#L52

2022-07-27 11:43 UTC, Crossedfall commented on strings/splash.json
> +	"splashes": ["Paved by the tears of coders.",
Drop the first string into its own line and indent accordingly

2022-07-29 08:25 UTC, PowerfulBacon requested changes

2022-07-29 08:25 UTC, PowerfulBacon commented on strings/splash.json
> +		"The only 'popular' game on BYOND.",
We probably don't want to get on the bad side of byond. I'd remove these ones.
The second one can be replaced with "It's a mircale it(/we) hasn't crashed yet"

2022-07-29 18:15 UTC, PowerfulBacon approved these changes, later dismissed

2022-08-01 03:02 UTC, Crossedfall requested changes
Some minor grammar stuff. Otherwise it's ready

2022-08-01 03:02 UTC, Crossedfall commented on strings/splash.json
> +		"Featuring ian!",
```suggestion
		"Featuring Ian!",
```

2022-08-01 03:02 UTC, Crossedfall commented on strings/splash.json
> +		"AI LAW 2 START GAME",
```suggestion
		"AI LAW 2, START THE GAME",
```

2022-08-01 03:02 UTC, Crossedfall commented on strings/splash.json
> +		"Greytide Stationwide.",
```suggestion
		"Greytide station wide.",
```

2022-08-01 03:02 UTC, Crossedfall commented on strings/splash.json
> +		"Ignore what poly says.",
```suggestion
		"Ignore what Poly says.",
```

2022-08-01 03:02 UTC, Crossedfall commented on strings/splash.json
> +		"Turn on ya damn suit sensors!",
```suggestion
		"Turn on your damn suit sensors!",
```

2022-08-01 03:02 UTC, Crossedfall commented on strings/splash.json
> +		"Celebrating 20 years of Nanotrasen.",
```suggestion
		"Celebrating 20+ years of Nanotrasen.",
```

2022-08-01 03:02 UTC, Crossedfall commented on strings/splash.json
> +		"13th time the charm.",
```suggestion
		"13th time's the charm.",
```

2022-08-01 06:42 UTC, Crossedfall approved these changes

2022-08-01 06:42 UTC, merged