fixes an ancient viro exploit
BeeStation/BeeStation-Hornet pull request #7371
Opened 2022-07-26 04:57 UTC by zeskorion

## About The Pull Request
regenerative coma and superficial healing had a weird threshold inherited from a parent that changed their effects at 6 speed, which has been removed

## Why It's Good For The Game

fix

## Testing Photographs and Procedure
![image](https://user-images.githubusercontent.com/49600480/180926544-0695a0d8-8a61-4c90-90ba-e65aa666f924.png)

## Changelog
:cl:
fix: fixes an exploit involving superficial healing and regen coma
/:cl:

2022-07-28 21:27 UTC, PowerfulBacon commented on code/datums/diseases/advance/symptoms/heal.dm
>  	return TRUE //For super calls of subclasses
Threshold descriptions are now incorrect. You may be fixing an exploit, but you are simultanously fixing something completely intended.

2022-07-31 22:55 UTC, zeskorion commented on code/datums/diseases/advance/symptoms/heal.dm
>  	return TRUE //For super calls of subclasses
alright, ill remove the threshold description from the unused healing symptom, then

2022-08-02 15:57 UTC, PowerfulBacon requested changes
Update PR body and changelog to reflect balance changes.

2022-08-02 18:09 UTC, zeskorion commented
> Update PR body and changelog to reflect balance changes.

done

2022-08-03 17:46 UTC, PowerfulBacon approved these changes

2022-08-03 17:46 UTC, merged