Improves the ahelp resolution message
BeeStation/BeeStation-Hornet pull request #7376
Opened 2022-07-26 14:35 UTC by PowerfulBacon

## About The Pull Request

Improves the adminhelp resolution message:
 - It now is a large message in chat, indicating that the adminhelp has been resolved.
 - The message now contains text saying that appropriate action has been taken if required (Users don't know what was taken, but should know that action *may* have been taken even if they don't know it).
 - The ckey of the handling administrator is now included in the resolution box, making it easier to know who handled a ticket (Useful for following up handling of bad tickets).

## Why It's Good For The Game

Players will be informed that action has been taken if required, they should know that even if they aren't explicitly told what happened to the other person, something did happen.
Better ability for players to follow up on poor ticket handling, admins that are handling tickets improperly can be trained and talked to.

## Testing Photographs and Procedure

![image](https://user-images.githubusercontent.com/26465327/181034427-ba9c247d-e8fd-456b-8e35-d2c4759b6d71.png)
![image](https://user-images.githubusercontent.com/26465327/181034772-27f7933b-87bd-42a7-a6ff-924ea1015192.png)

## Changelog
:cl:
admin: The adminhelp resolution message has been updated.
/:cl:

2022-07-26 21:04 UTC, Fronsis commented
Admemes still have the chance to hide their ckey right? Or with this it's gonna go away and enforce clarity? I remember some ahelps i've done in which the admin was: Admin which i reckon it's from when they're in hidden mode, i'd like for the clarity thing tbh

2022-07-27 06:16 UTC, PowerfulBacon commented
Once a ticket is resolved, the real ckey will display even in stealth mode

2022-07-28 19:42 UTC, itsmeow requested changes

2022-07-28 19:42 UTC, itsmeow commented on code/modules/admin/verbs/adminhelp.dm
> +	var/final_output = "<span class='adminhelp_conclussion'><span class='big'><b>Adminhelp [status]</b></span><br />"
conclussion?

2022-07-28 19:42 UTC, itsmeow commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +  margin-left: 20px;
`margin: 10px 20px` is more concise

2022-07-28 19:42 UTC, itsmeow commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +  border: solid;
`border: 2px solid red`

2022-07-28 21:33 UTC, PowerfulBacon commented on code/modules/admin/verbs/adminhelp.dm
> +	var/final_output = "<span class='adminhelp_conclussion'><span class='big'><b>Adminhelp [status]</b></span><br />"
Crap, it's spelt wrong isn't it

2022-08-28 14:45 UTC, ro5490 commented
Might be a good idea to append a line to the ahelp resolved message that links to the Admin Feedback area(or specific admin thread) on the forums, as feedback posts dont get enough love really

2022-09-29 10:41 UTC, PowerfulBacon commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +  margin-left: 20px;
Its less clear but whatever idc

2022-10-11 22:53 UTC, itsmeow approved these changes

2022-10-11 22:53 UTC, merged