Monkey re-sprite & Bonus procedural monkey clothing
BeeStation/BeeStation-Hornet pull request #7394
Opened 2022-07-28 09:52 UTC by DrDuckedGoose

## About The Pull Request

Updates monkey sprites to a semi-modern standard. 

Gives monkeys the option to wear jumpsuits, or any type of ``i_clothing``. 
This is done by clipping down the human worn-sprite and making some slight adjustments through shifting & stretching. This is also applied to hats, bags & masks. 

Monkey-icons are only generated if a monkey tries to equip a piece of clothing. Once an icon has been generated, all similar items will use that icon, instead of making their own, when a monkey equips them.

Additionally introduces a new gimmick role, Experiment. This role will have the player spawn as a monkey with a science outfit & ID.

## Why It's Good For The Game

Improves crusty sprites & emphasizes monkey RP without introducing any force-rp mechanics.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/40559528/181476462-50c83fff-a1c4-45ed-bcdd-f88e5cbe75a6.png)
![image](https://user-images.githubusercontent.com/40559528/181476382-7e833fec-0296-47c5-84cc-45d455208f5a.png)
![image](https://user-images.githubusercontent.com/40559528/181476175-dd9f84e8-a3ab-41a4-83dc-3aba5103bcda.png)
![image](https://user-images.githubusercontent.com/40559528/181476093-de2bc74b-7247-48ce-a6eb-8ddc165e155b.png)
![image](https://user-images.githubusercontent.com/40559528/181475983-fc507530-f9b1-4221-946b-bd52083503f3.png)
![image](https://user-images.githubusercontent.com/40559528/181475792-fc888308-6d43-414b-b9cb-9f99ab9a1b8e.png)

</details>

## Changelog
:cl:
add: New monkey sprites
tweak: Tweaks monkey inventory update - procs interface with ``monkey_icon``
add: Add ``i_clothing`` slot to monkey equipment slots
tweak: Allow monkeys to equip ``i_clothing``
/:cl:

2022-07-28 09:58 UTC, DrDuckedGoose commented
My git-head must be fucked, pulling commits from old PRs

2022-07-28 15:33 UTC, mcmeiler commented
This looks more like goon monkeys than anything. Pass from me.

2022-07-28 17:26 UTC, Isy232 commented
Great, now monkeys dont look so obviously 2 dimensional

2022-07-28 17:32 UTC, dwasint commented
I like it sans the sideways sprite, but than again making them true 3/4th would not be in scope for this pr

2022-07-28 22:30 UTC, FortSumter commented
Monkey station

2022-07-30 03:31 UTC, DerpiestBruh commented
YES DUDE YESSSSSSSSSSSSS

2022-07-30 10:03 UTC, Fronsis commented
Monke with da drip will become real in FIVE SECONDS

Though i'd keep the original color eyes

2022-08-09 05:01 UTC, ophaq commented
If this got merged into TG I'd probably make monkey station at some point for funny.

2022-08-31 00:53 UTC, itsmeow requested changes

2022-08-31 00:53 UTC, itsmeow commented on code/_onclick/hud/monkey.dm
> +//	inv_box.icon_full = "template"
commented code

2022-08-31 00:53 UTC, itsmeow commented on code/modules/jobs/job_types/gimmick.dm
> +	title = "Experiment"
JOB_NAME_EXPERIMENT

2022-08-31 00:53 UTC, itsmeow commented on code/modules/jobs/job_types/gimmick.dm
> +	department_head = list("Research Director")
`JOB_NAME_RESEARCH_DIRECTOR`

2022-08-31 00:53 UTC, itsmeow commented on code/modules/mob/living/carbon/update_icons.dm
> +
useless whitespace addition

2022-08-31 12:07 UTC, itsmeow submitted a review, later dismissed

2022-08-31 21:16 UTC, itsmeow commented
check machine broke

```
code/__DEFINES/jobs.dm, line 200, column 9:
 warning: macro redefined: JOB_NAME_EXPERIMENT
- 134:9: previous definition of JOB_NAME_EXPERIMENT
- ```

2022-09-04 23:33 UTC, itsmeow submitted a review, later dismissed

2022-09-04 23:33 UTC, itsmeow commented
bleh
```
file ./code/__DEFINES/misc.dm is missing a trailing newline
```

2022-09-21 11:38 UTC, dwasint commented
Few things,
1. I think de hard coding the path would be worthwhile as gag items are usually in their own files for easy of editing
2. This probably doesn't support gag items period, and having yet another reason to not have gags is kinda eh

2022-09-22 07:22 UTC, DrDuckedGoose commented
> Few things,
> 
> 1. I think de hard coding the path would be worthwhile as gag items are usually in their own files for easy of editing
> 2. This probably doesn't support gag items period, and having yet another reason to not have gags is kinda eh

It's almost like GAGs is a shitty system to work with 🤔

2022-09-25 02:01 UTC, DrDuckedGoose commented
Wait, it already, kinda, does?
![image](https://user-images.githubusercontent.com/40559528/192125051-3fb8924d-19e5-4cd2-bb4e-fd1fa95ff592.png)
**MY WORK HERE IS DONE!**

2022-09-25 14:33 UTC, dwasint commented
> > Few things,
> > 
> > 1. I think de hard coding the path would be worthwhile as gag items are usually in their own files for easy of editing
> > 2. This probably doesn't support gag items period, and having yet another reason to not have gags is kinda eh
> 
> It's almost like GAGs is a shitty system to work with 🤔

Gags is a great system to work with once you play around with it, being able to recolor certain parts of items instead of having like 30 different color combos bloating sprites is great

2022-09-29 14:02 UTC, PowerfulBacon approved these changes

2022-09-29 14:04 UTC, PowerfulBacon requested changes
Actually, there is no way there should be a roundstart monkey gimmick job. Having a 25% chance to have an unplayable round apart from being forced to go to genetics is dumb, especially since you can't choose

2022-10-02 10:38 UTC, PowerfulBacon approved these changes

2022-10-02 10:38 UTC, merged

2022-10-11 00:06 UTC, itsmeow commented
Runtime
![image](https://user-images.githubusercontent.com/10366817/194970237-865195f0-8097-4696-abaf-d78ecf52c758.png)