Fixes corgium lasting forever
BeeStation/BeeStation-Hornet pull request #7402
Opened 2022-07-29 09:45 UTC by PowerfulBacon

## About The Pull Request

Shapeshift holders apply no_transform, which in turn disables life() which disables reagent metabolism. This makes corgium last forever.
Instead of doing that, we will use timers instead to force call the restore proc after the reagents should have worn off.

## Why It's Good For The Game

Corgium should not be infinite, as funny as it is.

## Testing Photographs and Procedure

![image](https://user-images.githubusercontent.com/26465327/181732660-ff5ada5b-9cce-41ce-a5d6-3388c28b48f9.png)

![image](https://user-images.githubusercontent.com/26465327/181732690-55c214ec-e6c7-414b-a743-bc61362e95e4.png)

## Changelog
:cl:
fix: Corgium will no longer last forever and will no longer affect people with damaged livers forever.
/:cl:

2022-07-29 10:16 UTC, RDS88-beeman commented
I was about to say "what about Calomel and other reagents that purge from the bloodstream"
but then I realised
how do you get those things into a corgi.

2022-07-31 05:05 UTC, Archanial commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> -	ADD_TRAIT(L, TRAIT_MUTE, CORGIUM_TRAIT)
Is the corgium trait still used?

2022-07-31 07:50 UTC, PowerfulBacon commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> -	ADD_TRAIT(L, TRAIT_MUTE, CORGIUM_TRAIT)
no

2022-08-08 16:58 UTC, itsmeow approved these changes

2022-08-12 22:25 UTC, ike709 commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> -	ADD_TRAIT(L, TRAIT_MUTE, CORGIUM_TRAIT)
...So remove it.

2022-08-30 21:13 UTC, itsmeow requested changes
Remove `CORGIUM_TRAIT`

2022-09-22 23:44 UTC, ike709 commented
Remove corgium trait I beg you

2022-09-29 10:36 UTC, PowerfulBacon commented
okay

2022-10-04 02:11 UTC, itsmeow approved these changes

2022-10-11 23:03 UTC, merged