Engineering Once Again Gets Generic Circuit Imprinters
BeeStation/BeeStation-Hornet pull request #7410
Opened 2022-07-30 05:36 UTC by Isy232

## About The Pull Request

Changes all maps with engineering circuit imprinters to generic circuit imprinters.
Delta, Kilo and Corg already had generic circuit imprinters in engineering, so have not been changed except...
Delta for some reason had 2 circuit imprinters on the same tile, so I removed the extra engineering circuit imprinter.

## Why It's Good For The Game

The reason engineering had a generic circuit imprinter was to allow for engineers to repair damaged departments. If a plasmafire burns down chemistry or R&D, the engineers will be able to print the board required to repair it.

This doesn't really make antagonist engineers any stronger, as they could just take the boards they wanted from tech storage without having to wait for research. However tech storage only has 1 of each board, not enough to repair cryo or chemistry up to its previous functionality.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
tweak: Engineering circuit imprinters are once again generic.
/:cl:

2022-07-30 13:07 UTC, PowerfulBacon commented
Is there actually a difference between them? I thought the engineering printer had more

2022-07-30 13:07 UTC, PowerfulBacon requested changes
If you are removing ir, remove the entire object

2022-07-30 15:47 UTC, Isy232 commented
> If you are removing ir, remove the entire object

Done

2022-07-30 15:50 UTC, Isy232 commented
> Is there actually a difference between them? I thought the engineering printer had more

Engineering specifically can ONLY print engineering related boards like thermomachines or rad collectors.

Unable to print ore silo boards, cryo tube boards, ect.

2022-07-30 16:13 UTC, Isy232 reviewed
did I just review my own pr

why do I not know how github works

bacon is there anything I have to do to like, close your change request since its completed or is that something you do?

2022-07-30 17:13 UTC, PowerfulBacon commented
Looking into it further:

```
/obj/machinery/rnd/production/circuit_imprinter/department/science
	name = "department circuit imprinter (Science)"
	circuit = /obj/item/circuitboard/machine/circuit_imprinter/department/science
	allowed_department_flags = DEPARTMENTAL_FLAG_ALL|DEPARTMENTAL_FLAG_SCIENCE
	department_tag = "Science"

/obj/machinery/rnd/production/circuit_imprinter/department/engineering
	name = "department circuit imprinter (Engineering)"
	circuit = /obj/item/circuitboard/machine/circuit_imprinter/department/engineering
	allowed_department_flags = DEPARTMENTAL_FLAG_ALL|DEPARTMENTAL_FLAG_ENGINEERING
	department_tag = "Engineering"
```
Since both of them have DEPARTMENTAL_FLAG_ALL, the engineering and science part doesn't actually do anything since both of them already have engineering and science. This means that circuit printers can print all circuit boards no matter where they are.
The only thing that is different between both boards is the department_tag (Which is unused).

As such, this PR doesn't actually do anything and is kind of pointless. Departmental circuit imprinters should either be fixed to not print everything, or removed entirely.

2022-07-31 09:46 UTC, Penwin0 commented
> DEPARTMENTAL_FLAG_ALL

That flag doesn't actually make them able to print everything its just given to every circuit imprinter

2022-07-31 09:47 UTC, Penwin0 commented
`#define DEPARTMENTAL_FLAG_ALL			(1<<6)			//NO THIS DOESN'T ALLOW YOU TO PRINT EVERYTHING, IT'S FOR ALL DEPARTMENTS!`

2022-07-31 16:21 UTC, Isy232 commented
> Since both of them have DEPARTMENTAL_FLAG_ALL, the engineering and science part doesn't actually do anything since both of them already have engineering and science. This means that circuit printers can print all circuit boards no matter where they are.
> The only thing that is different between both boards is the department_tag (Which is unused).

I know this is not true due to ingame testing.

I am no code man, but I think penwin explained it well enough.

Personally, I know science is unable to print chem machine and ore silo boards (as they probably shouldnt be able to do so).

_However they can print a generic circuit imprinter board, build that, then print whatever chem machine/ore silo board they want._

2022-08-01 16:58 UTC, PowerfulBacon commented
> `#define DEPARTMENTAL_FLAG_ALL (1<<6) //NO THIS DOESN'T ALLOW YOU TO PRINT EVERYTHING, IT'S FOR ALL DEPARTMENTS!`

Oh what a stupid name

2022-08-01 16:58 UTC, PowerfulBacon reviewed
Wouldn't they lose the ability to print engineering only circuits (if there are any?)

2022-08-01 19:54 UTC, Isy232 commented
> Wouldn't they lose the ability to print engineering only circuits (if there are any?)

No, unregistered circuit imprinters and protolathes instead are able to print items from all departments.

2022-08-05 05:44 UTC, zeskorion commented
wouldnt this let engineers build big powergame rooms with all the machines again?

2022-08-05 20:18 UTC, Isy232 commented
> wouldnt this let engineers build big powergame rooms with all the machines again?

They already do that with tech storage so they dont even have to wait for research, so this wont change anything.

Science also has the ability to make a generic circuit imprinter so I dont see any problems with giving engineering, a generally less OP department, one too.

2022-08-09 08:48 UTC, PowerfulBacon commented
This will let them print stuff like AI upload boards and stuff they shouldn't have access to though. What machines are actually restricted with the engi-printer that science gets?

2022-08-11 18:21 UTC, Isy232 commented
> This will let them print stuff like AI upload boards and stuff they shouldn't have access to though. What machines are actually restricted with the engi-printer that science gets?

With the engi printer, they're only able to print engineering boards like rad collectors and TEG's. So medical boards like chemistry, sleepers or cryo are unavailable, same for science boards like xenobiology consoles, AI uploads, ect.

I think thats what your asking, sorry I dont really understand the wording.

2022-08-14 08:40 UTC, PowerfulBacon approved these changes

2022-08-14 08:40 UTC, merged