Adds New Medieval Mutation
BeeStation/BeeStation-Hornet pull request #7476
Opened 2022-08-11 01:52 UTC by 12Oreos

## About The Pull Request
As the title says

## Why It's Good For The Game
I noticed some other code bases had a medieval mutation so made my own for beestation. plus i think genetics could use some more mutations anyway

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

![Capture1](https://user-images.githubusercontent.com/40776384/184051784-a2738fcd-d94c-4727-ad6f-1e068be2669b.PNG)

![2](https://user-images.githubusercontent.com/40776384/184051802-3b195763-9d8c-43a7-8954-c312cb92b08d.PNG)

![3](https://user-images.githubusercontent.com/40776384/184051820-2fc2eefe-e15d-4221-94c4-ba90874ad322.PNG)

</details>

## Changelog
:cl:
add: Medieval Mutation that modifies speech when applied
/:cl:

2022-08-13 18:58 UTC, 12Oreos commented
Made some minor errors in capitalization, also shortened some replacement words

2022-08-30 21:08 UTC, itsmeow requested changes

2022-08-30 21:08 UTC, itsmeow commented on code/datums/mutations/speech.dm
> +	text_lose_indication = "<span class='notice'>You no longer feel like seeking anything</span>"
add a period

2022-09-03 03:18 UTC, 12Oreos reviewed
Oops forgot that

2022-09-03 06:11 UTC, itsmeow approved these changes

2022-09-19 09:30 UTC, PowerfulBacon approved these changes

2022-09-19 09:30 UTC, merged