MMIs/Posibrains and Blood Brother implants properly format text
BeeStation/BeeStation-Hornet pull request #7505
Opened 2022-08-13 23:08 UTC by itsmeow

## About The Pull Request

Adds auto-capitalization and auto-punctuation to brains and blood brother implants.

## Why It's Good For The Game

These being missing makes text from them look weird and also ruins immersion.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/10366817/184516203-927aad3b-937a-4ac0-b8e3-bb8317c86bec.png)

![image](https://user-images.githubusercontent.com/10366817/184516204-586d773a-92a9-4a8d-81d2-cda4ec73d6fc.png)

</details>

## Changelog
:cl:
tweak: MMIs, Posibrains, and Blood Brother implants now properly capitalize and punctuate text.
/:cl:

2022-08-17 18:15 UTC, PowerfulBacon requested changes

2022-08-17 18:15 UTC, PowerfulBacon commented on code/game/objects/items/implants/implant_bb.dm
> +		input = capitalize(input)
We should just make this its own proc

2022-08-23 19:07 UTC, itsmeow commented
Need to include cult commune in this

2022-08-23 22:22 UTC, RDS88-beeman commented
Of anything in the game isn't this the one thing that shouldn't be capitalized by default? If a character thinks in lowercase no punctuation (like I'd guess most people do), I get the feeling that would come across in telepathy.

While I understand 99% of people are just going to use all lowercase because it's faster, this PR removes the option to have that character moment, of thinking with punctuation.

This only matters to me, and even then I probably won't notice, but this isn't a a costless change.

MMI's are though, and that should really get done.

2022-08-23 23:35 UTC, itsmeow commented
PDA messages and such don't enforce this because they are actually "texting", but telepathy is "heard" according to ingame lore ("you hear a voice in your head")

Therefore it should follow convention for heard speech.

2022-08-24 08:51 UTC, RDS88-beeman commented
Some telepathy is heard (genetics, revenant spell) but the vast majority just shows up (pretty much any concrete dialogue). I would even argue heard is just an attempt to get across something English doesn't really have a word for. "You sense a voice in your head" just doesn't sound right. Besides, what are you even hearing? There is, by definition, no sound to hear.

If you're concrete on this reasoning, are admin subtlemessages managed in this way?

2022-08-24 08:54 UTC, itsmeow commented
yeah, I don't think that being able to think to each other with bad grammar is an important feature in any way, and having more consistency and formatting improves people's sense of "You should be RPing in this chat and not typing lol"

2022-08-27 17:36 UTC, PowerfulBacon requested changes

2022-08-27 17:36 UTC, PowerfulBacon commented on code/modules/mob/living/carbon/human/species_types/jellypeople.dm
> +		msg = H.treat_message_min(H)
This is wrong

2022-08-27 19:56 UTC, itsmeow commented on code/modules/mob/living/carbon/human/species_types/jellypeople.dm
> +		msg = H.treat_message_min(H)
good catch, thanks

2022-08-30 10:30 UTC, PowerfulBacon approved these changes

2022-08-30 10:30 UTC, merged