Adds a new, sick way to unmount a skateboar
BeeStation/BeeStation-Hornet pull request #7507
Opened 2022-08-14 06:17 UTC by etherware-novice

## About The Pull Request
Adds a new ui action for the skateboard, for a kickflip. On use, you will jump in place and "catch" the skateboard in midair, putting it in your hands.

## Why It's Good For The Game
Unmounting skateboards is TEDIOUS, the sprite is too small to reliably click drag it. Considering you can quickly mount a skateboard from the held item version, it makes sense that you can have an option to quickly get it in your hands.
Its also slick as hell.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Nanotrasen has implemented kickflip skills into all employees, in an attempt to boost skateboard sales.
/:cl:

2022-08-14 06:17 UTC, etherware-novice commented
testing files coming, obs is being very difficult rn

2022-08-14 07:46 UTC, Fronsis commented
Damn that looks dope, guess it's missing the sound and maybe an arrow pointing downwards to differentiate from the 1st button?

2022-08-14 08:18 UTC, RDS88-beeman commented
My mechanics senses are tingling, what happens if a xeno kickflips a skateboard. Does it go into their hands?

2022-08-14 16:59 UTC, etherware-novice commented
> Damn that looks dope, guess it's missing the sound and maybe an arrow pointing downwards to differentiate from the 1st button?

i dobt know how to edit the sprite to look belivable so no

2022-08-14 16:59 UTC, etherware-novice commented
> My mechanics senses are tingling, what happens if a xeno kickflips a skateboard. Does it go into their hands?

it calls the skateboards local pickup proc so i think they cant

2022-08-14 20:05 UTC, itsmeow commented
Add the kickflip sound please

2022-08-15 00:08 UTC, ivanmixo requested changes

2022-08-15 00:08 UTC, ivanmixo commented on code/modules/vehicles/vehicle_actions.dm
> +	L.visible_message("[L] does a neat kickflip and catches [L.p_their()] board in midair.", "<span class='notice'>You do a sick kickflip, catching the board in midair! Stylish.")
```suggestion
	L.visible_message("[L] does a neat kickflip and catches [L.p_their()] board in midair.", "<span class='notice'>You do a sick kickflip, catching the board in midair! Stylish.</span>")
```

2022-08-15 00:08 UTC, ivanmixo commented on code/modules/vehicles/vehicle_actions.dm
> +	desc = "Do a sweet kickflip to dismount..in style."
```suggestion
	desc = "Do a sweet kickflip to dismount... in style."
```
Nitpick but please.

2022-08-15 16:19 UTC, itsmeow commented
Does this have a failure chance like the ollie? It probably should

2022-08-15 16:21 UTC, etherware-novice commented
the ollie always succeeds unless you hit max stamina damage, so maybe ill just make it use 5 stam to kickflip?

2022-08-15 21:44 UTC, itsmeow commented
yeah it should use stam like ollies

2022-08-16 16:50 UTC, itsmeow commented
Don't add brute damage, please...

2022-08-16 16:51 UTC, etherware-novice commented
how about a 5-10 percent chance to cause brute

2022-08-16 16:51 UTC, itsmeow requested changes

2022-08-16 16:51 UTC, itsmeow commented on code/modules/vehicles/vehicle_actions.dm
> +		L.visible_message("[L] does a neat kickflip and catches [L.p_their()] board in midair.", "<span class='notice'>You do a sick kickflip, catching the board in midair! Stylish.")
The visible message should say sick or sweet, not neat

2022-08-16 16:51 UTC, itsmeow commented on code/modules/vehicles/vehicle_actions.dm
> +		L.adjustBruteLoss(10)  // thats gonna leave a mark
no

2022-08-16 18:05 UTC, etherware-novice commented on code/modules/vehicles/vehicle_actions.dm
> +		L.adjustBruteLoss(10)  // thats gonna leave a mark
5-10% chance?

2022-08-16 22:20 UTC, ivanmixo commented on code/modules/vehicles/vehicle_actions.dm
> +		L.adjustBruteLoss(10)  // thats gonna leave a mark
This is good, wdym lol

2022-08-17 18:13 UTC, PowerfulBacon commented on code/modules/vehicles/vehicle_actions.dm
> +		L.visible_message("[L] does a neat kickflip and catches [L.p_their()] board in midair.", "<span class='notice'>You do a sick kickflip, catching the board in midair! Stylish.")
Close your spans and add a span for the first one.

2022-08-18 15:03 UTC, itsmeow approved these changes

2022-08-28 22:46 UTC, ike709 approved these changes

2022-08-30 21:10 UTC, Archanial approved these changes

2022-08-30 21:10 UTC, merged

2022-08-30 21:19 UTC, itsmeow commented
# The skateboar is real

![image](https://user-images.githubusercontent.com/10366817/187545221-e45291eb-dfbf-4d1a-88f4-8b6141498373.png)