Adds the militaristic captain set
BeeStation/BeeStation-Hornet pull request #7523
Opened 2022-08-17 23:00 UTC by bluezorua

## About The Pull Request
as title says, sprites done by thatguythere03

## Why It's Good For The Game
someone wanted a more militaristic captain outfit and someone else made the sprites but doesn't know how git works so I did the git work

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
![Military Cap drip](https://user-images.githubusercontent.com/54711687/185258063-178b81d4-7206-447c-bbc8-9f0846012439.png)

</details>

## Changelog
:cl: thatguythere03 for the sprites, Toasterban for the codework
add: Military-styled cap uniform,jacket and hat
/:cl:

2022-08-18 01:20 UTC, zeskorion commented
>milrp nerds
ugh

2022-08-18 05:31 UTC, AnCopper commented
We have an issue of the Captain having like 4 sets of high grades Armour in their locker, honestly it should be replaced with a vendor.

2022-08-18 19:53 UTC, PestoVerde322 commented
As much as the spritework looks nice and all, I gotta agree with AnCopper, we've far far too many sets of high grade armor in the cap's locker, and really, we might have actually one too many outfits at this point.

2022-08-18 20:25 UTC, bluezorua commented
alright makes sense, thoughts about making the outfit a colouriser instead?

2022-08-18 21:09 UTC, PestoVerde322 commented
> alright makes sense, thoughts about making the outfit a colouriser instead?

That might actually work, maybe as a variant to the parade outfit I think.

2022-08-20 21:11 UTC, bluezorua commented
made it a colouriser and refracted colourisers slightly to allow multiple uses

2022-08-21 08:43 UTC, EvilDragonfiend commented on code/game/objects/items/colorizers/clothing.dm
> +	name = "Captain's Clothes Colourizer (Military)"
What's this abomination of British and American grammar?

2022-08-21 08:43 UTC, EvilDragonfiend commented on code/modules/client/loadout/loadout_colorizers.dm
> +    display_name = "Captain's Clothes Colourizer (Military)"
this too

2022-08-25 09:21 UTC, bluezorua commented
wait I fucked something up

2022-08-25 09:21 UTC, bluezorua commented
wait I fucked something up

2022-08-30 21:01 UTC, itsmeow requested changes

2022-08-30 21:01 UTC, itsmeow commented on code/game/objects/items/colorizers/colorizer.dm
> +    if(uses_left == 0)
!uses_left

2022-08-30 21:01 UTC, itsmeow commented on code/game/objects/items/colorizers/clothing.dm
> +/obj/item/colorizer/militarycapuniform
change the type path to `captain_military_uniform`

2022-08-30 21:01 UTC, itsmeow commented on code/modules/clothing/head/jobs.dm
> -
random line removal

2022-08-30 21:01 UTC, itsmeow commented on code/modules/clothing/under/jobs/command.dm
> +
random line addition

2022-09-29 14:18 UTC, PowerfulBacon approved these changes

2022-09-29 14:18 UTC, merged