Adds a flash pen disguised as a medical holopen
BeeStation/BeeStation-Hornet pull request #7524
Opened 2022-08-17 23:48 UTC by etherware-novice

## About The Pull Request
Tators in the medical field can get a flash disguised as a medical holopen now! it costs 6 tc

## Why It's Good For The Game
more stealth opprotunities?

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/73374039/185262901-bd52e8ac-7061-4b86-af3c-35700ee2f0d7.png)

</details>

## Changelog
:cl:
add: flash holopen tator item
/:cl:

2022-08-18 01:31 UTC, EvilDragonfiend commented
Shouldn't it be specifically a holopen? Adding a specific item doesn't make you stealthy, and it should use chameleon feature instead.

2022-08-18 11:11 UTC, FriendlyContractor commented
Its worse than easily available "common"l flash. Very expensive for what it is and gives away that you are a traitor.

2022-08-18 15:01 UTC, itsmeow requested changes

2022-08-18 15:01 UTC, itsmeow commented on code/modules/assembly/flash.dm
> +/obj/item/assembly/flash/pen/suicide_act(mob/living/carbon/human/user)
Why add this? Is it from the parent holopen? Honestly just remove if so.

2022-08-18 15:01 UTC, itsmeow commented on code/modules/uplink/uplink_items.dm
> +	cost = 6
Cost is a bit high, maybe 4-5TC?

2022-08-19 16:10 UTC, ivanmixo commented on code/modules/uplink/uplink_items.dm
> +	cost = 6
This is barely worth 2, lol

2022-08-19 19:55 UTC, itsmeow approved these changes

2022-08-29 11:04 UTC, PowerfulBacon commented
Why would I use this over the infinite hypnoflash?

2022-09-29 14:21 UTC, PowerfulBacon requested changes
This is just a flash in the uplink really, I don't think its unique enough unlike stuff like the rad scanner which has its own special effects. Already not a fan of flashes due to their function being instant combat victory or being entirely useless. This is too expensive none the less

2022-10-01 15:48 UTC, Penwin0 commented
Quite expensive for what is a retextured flash, a bit of a boring item for a job-special or traitor item in general. This PR has been sitting here since August without the issues pointed out being resolved

2022-10-01 15:48 UTC, closed without merging