Restricts PKA to off-station
BeeStation/BeeStation-Hornet pull request #7552
Opened 2022-08-24 19:42 UTC by TeomanTheGreat

## About The Pull Request
Adds the off-station firing pin to PKAs

## Why It's Good For The Game
The current miner antag strat is getting spaceproof and then going to space with PKAs then depressurizing sec to fight them and easily curb stomp them. PKAs are not balanced for non-mining combat. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/55861563/186508097-54d5d059-4b37-4cfd-9615-5b3e2b73a5a2.png)
![image](https://user-images.githubusercontent.com/55861563/186508112-1892b8aa-11a7-4411-970e-9dc14cfe3132.png)

</details>

## Changelog
:cl: Phil Smith
balance: The PKAs now have off-station firepins. 
/:cl:

2022-08-24 19:47 UTC, itsmeow commented
or just make PKAs balanced on the station z level. I don't think this is the answer

2022-08-24 19:59 UTC, TeomanTheGreat commented
> or just make PKAs balanced on the station z level. I don't think this is the answer

If the miner really wants to use his PKA on the station z-level they can steal a fire pin from sec. There is a box of them.

2022-08-24 20:02 UTC, PowerfulBacon commented
Problem is they can just emag it (Or should be able to at least), limiting this to just traitor miners which doesn't solve the antga problem you are trying to solve.

2022-08-24 20:02 UTC, PowerfulBacon commented
They should be most effective at low pressures and weak at high or no pressure environments.

2022-08-24 20:12 UTC, TeomanTheGreat commented
> They should be most effective at low pressures and weak at high or no pressure environments.

Spacing an area will leave a window in which there is low pressure so that wont change much.

2022-08-24 20:15 UTC, TeomanTheGreat commented
> Problem is they can just emag it (Or should be able to at least), limiting this to just traitor miners which doesn't solve the antga problem you are trying to solve.

Just tried emagging the PKA. Didn't work.

2022-08-24 20:16 UTC, DerpiestBruh commented
People are complaining about PKAs working like they should its unreal lol

2022-08-24 20:20 UTC, zeskorion commented
what if we just kinda
rebalance mining stuff numbers to be on-line with station stuff?

2022-08-24 20:21 UTC, DerpiestBruh commented
> Also you could just disable the low pressure damage buff on the station z

doesnt make sense

2022-08-24 22:09 UTC, DingleFlop commented
Ided, plz nerf

2022-08-24 23:44 UTC, Sinestia commented
> They should be most effective at low pressures and weak at high or no pressure environments.

This


Find what pressure lavaland is at and take the absolute value of wherever you are. If it deviates much then make it weak as hell.

2022-08-24 23:58 UTC, DerpiestBruh commented
> capable of deleting entire sec force.

lol?

> Mmm yes I love seeing tot skeleton miner in drake armor with PKA, hiero staff, BS crystals, cores, guardian from uplink and whatever other bullshit there is killing seccies in space

cores are a xenobio issue, space adapt is a genetics issue too. Also skill issue.

2022-08-25 00:12 UTC, Fronsis commented
> > capable of deleting entire sec force.
> 
> lol?
> 
> > Mmm yes I love seeing tot skeleton miner in drake armor with PKA, hiero staff, BS crystals, cores, guardian from uplink and whatever other bullshit there is killing seccies in space
> 
> cores are a xenobio issue, space adapt is a genetics issue too. Also skill issue.

For cores they meant the legion scores that insta-heals you (and they can buy the stabilized one as well)

They also don't need space adapt since they're a skeleton, i've seen the exact setup he described THREE times, two yesterday and one today, with small variations

Sure, there's a point when certain things are an ''ided'' or a ''skill issue'' moment, but a meth-speed skeleton with ashdrake, hiero staff, kpa, etc it's a little.. unbalanced. It's only fun for le antag that goes around killing all opposing force.

In any case i'm not sure if PKA should be restricted to off station but mostly because they're a very good tool to fight blobs, but... seeing the current antag meta i'd say the bad outweights the good.

2022-08-25 10:50 UTC, Sinestia commented
> In any case i'm not sure if PKA should be restricted to off station but mostly because they're a very good tool to fight blobs, but... seeing the current antag meta i'd say the bad outweights the good.

they trivialize blobs in the most braindead way lol

2022-08-25 13:48 UTC, Isy232 commented
> what if we just kinda
> rebalance mining stuff numbers to be on-line with station stuff?

Holy shit I actually agree with zesko.

Yeah, IF YOUR UP TO IT.

The better solution is to nerf PKA damage but also nerf the health of all lavaland creatures so that the PKA retains its effectiveness on lavaland while being weaker on the station.

Also please take a look at PKA dual wielding. Unless that was removed, miners can dual wield PKA's which is really OP.

2022-08-25 13:51 UTC, DerpiestBruh commented
> miners can dual wield PKA's which is really OP.

its really slow to reload and if im not wrong REALLY inaccurate with the gun wielding system

2022-08-25 18:10 UTC, PowerfulBacon commented
> > Problem is they can just emag it (Or should be able to at least), limiting this to just traitor miners which doesn't solve the antga problem you are trying to solve.
> 
> Just tried emagging the PKA. Didn't work. 

That's a bug with gun emagging not transferring to firing pins and should be the case. This is subject to change.

2022-08-25 18:11 UTC, PowerfulBacon commented
The low pressure buff will be like 3 tiles since outside it is no pressure and inside is high pressure.

2022-08-25 18:12 UTC, PowerfulBacon requested changes
A much nicer solution would be to make it so the damage buff is low pressure but not 0 zero pressure (minimum as well as a maximum).

2022-08-29 06:26 UTC, Kratairo commented
People getting mad about security not auto winning every fight, lets just make it so security gets notified who is antag instantly so they can just redtext them right there! Game much more fun that way

2022-08-29 07:11 UTC, PowerfulBacon requested changes

2022-08-29 07:11 UTC, PowerfulBacon commented on code/__HELPERS/game.dm
> +	if(pressure <= LAVALAND_EQUIPMENT_EFFECT_PRESSURE & pressure > 0)
Use a define for this and make it slightly below the minimum lavaland pressure rather than 0 (1kPa shouldnt count too)

2022-08-29 09:34 UTC, Fronsis commented
> People getting mad about security not auto winning every fight, lets just make it so security gets notified who is antag instantly so they can just redtext them right there! Game much more fun that way

You certainly fail to see issue of balance that a miner is with the * example gear provided on the comments above with antagonist status* has.

2022-08-29 21:21 UTC, AnCopper commented
Yog did this:
https://github.com/yogstation13/Yogstation/pull/15470

2022-09-02 23:57 UTC, benbot16 commented
Wouldn't this also mess with miners mining on asteroids? It's not too too common, but it is a thing that happens, and there are asteroid monsters that are pretty beefy.

2022-09-10 13:49 UTC, PowerfulBacon requested changes

2022-09-10 13:49 UTC, PowerfulBacon commented on code/__HELPERS/game.dm
> +	if(pressure <= MAXIMUM_LAVALAND_EQUIPMENT_EFFECT_PRESSURE & pressure >= MINIMUM_LAVALAND_EQUIPMENT_EFFECT_PRESSURE)
Wrong operator. This is a bit & operator, not a logical & operator. Use &&

2022-09-28 21:56 UTC, PowerfulBacon commented on code/__HELPERS/game.dm
> +	if(pressure <= MAXIMUM_LAVALAND_EQUIPMENT_EFFECT_PRESSURE & pressure >= MINIMUM_LAVALAND_EQUIPMENT_EFFECT_PRESSURE)
```suggestion
	if(pressure <= MAXIMUM_LAVALAND_EQUIPMENT_EFFECT_PRESSURE && pressure >= MINIMUM_LAVALAND_EQUIPMENT_EFFECT_PRESSURE)
```

2022-09-28 21:58 UTC, PowerfulBacon approved these changes

2022-09-28 22:03 UTC, merged