You can't withdraw credits from budget card anymore
BeeStation/BeeStation-Hornet pull request #7578
Opened 2022-08-29 21:22 UTC by EvilDragonfiend

## About The Pull Request

## Why It's Good For The Game
extremely amount of money shouldn't be that easily accessible, but also heads should utilise their console to give payment bonus, not just withdraw money from the budget card.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/87972842/187300989-ad2b7931-1c8f-4183-8cb9-70124b23c1bf.png)

You can't withdraw

![image](https://user-images.githubusercontent.com/87972842/187301048-4cac078f-bf68-4f5a-b313-2b95305f1d1c.png)

![image](https://user-images.githubusercontent.com/87972842/187301198-6c1b52aa-e412-41e8-bf2b-b7c4b36635c7.png)

emag can make it withdrew

</details>

## Changelog
:cl:
tweak: budget card is locked and you can't withdraw credits from it. You can when you emag the cards.
/:cl:

2022-08-29 22:20 UTC, Dejaku51 commented
now i can't ask other departaments to loan money to make station goal :tragedy:

2022-08-29 22:21 UTC, EvilDragonfiend commented
> now i can't ask other departaments to loan money to make station goal :tragedy:

hmm, maybe budget-budget transfer feature

2022-08-30 03:58 UTC, EvilDragonfiend commented
This PR should be merged with https://github.com/BeeStation/BeeStation-Hornet/pull/7559 together

2022-08-30 10:26 UTC, Archanial commented on code/game/objects/items/cards_ids.dm
> +	..()
```suggestion
	return ..()
```

2022-08-30 10:26 UTC, Archanial commented on code/game/objects/items/cards_ids.dm
> +	else
redundant else

2022-08-30 14:56 UTC, PowerfulBacon commented on code/game/objects/items/cards_ids.dm
> +	..()
Does alt click return?

2022-08-30 22:19 UTC, EvilDragonfiend commented on code/game/objects/items/cards_ids.dm
> +	..()
It doesn't return any value though

2022-08-31 07:33 UTC, PowerfulBacon commented on code/game/objects/items/cards_ids.dm
> +	..()
Don't return then

2022-08-31 07:34 UTC, PowerfulBacon commented
This is interesting and I can think of individual, very specific situations for and against this, but what's the main intent of this PR? What do you want to change as a result of this change?

2022-08-31 10:48 UTC, EvilDragonfiend commented
> This is interesting and I can think of individual, very specific situations for and against this, but what's the main intent of this PR? What do you want to change as a result of this change?

Reasons:
* For heads, they'll be no longer allowed to directly withdraw the budget money. If they want to give bonus to their underlings, they'll have to use their payment console to give. (main reason)
* But also, if they want to use money directly, they'll still have to use a payment console for giving a lot of bonus to themself.
* If a person wants to steal credits in a budget card, they'll have to steal the whole card instead of just pulling out all credits. (or emag it) so, a thief will have to keep the budget card all day if they want to abuse it.
* and last, I am writing a code to track how the credits go. I don't like a case that withdraws credits from a budget card.

2022-08-31 12:28 UTC, itsmeow commented
FINANCE LOGS FOR THE LOG VIEWER ?!?!

2022-08-31 12:35 UTC, EvilDragonfiend commented
> FINANCE LOGS FOR THE LOG VIEWER ?!?!

I am trying to add "INVESTIGATE_ECONOMY_CREDITS" to investigate log.

2022-08-31 15:27 UTC, NormalAnomaly commented
I am still unclear at the actual intent and practical implications of this considering most of my gameplay experience suggests that most of the cases money is taken out of a budget is not malicious.

Heads have never made strong use of their console, ever, in any capacity.  To the point that I've met more than one that had no idea they had it.  Even among those that do know its there and know its function, for job transfers "Go see the hop" is still the usual answer.

Heads very rarely ever give bonuses, with console or directly, or even hand out the medals.  The idea of giving a financial reward is the sort of thing that might happen a handful of times a week, I'd wager easily below 5% of shifts.  Making it take more steps will not benefit this.  Heads that actually reward workers with more than "Cool" or "Good Job" are not the norm by far.

Thieves do steal the whole budget card pretty often, in part to abuse its access for private ordered goods if they plan to even do anything with the money.  If they do leave the card, then the card will continue to gain funds over the course of the shift and the rightful user might still make use of it later.  And, as a corner case example, I've stopped teslagriefers ordering parts or funnymen ordering 30 snake crates by withdrawing credits.  The QM should at least retain the ability to freeze transactions.

"extreme amount of money shouldn't be that easily accessible"  Why and what difference does it make?
Stealing head lockers is arguably too easy, though the budget should probably be carried by the head so its an IC issue to a degree that it gets stolen out of the lockers if there is an active head or a problem with command gameplay/population if the head slot is empty.  Its enough cash to buy a few crates, is that an extreme amount (cargo budget aside)?  Cash has no practical value other than cargo orders, and in my QM time, most of the stolen budget funds have just been used by a clown to try to get a gimmick crate.  And since the cargo consoles just take directly from the cargo budget, anyone who breaks into cargo functionally has access to the cargo budget.

2022-08-31 15:29 UTC, Archanial requested changes
I want to see some method traitors can use to withdraw money, that doesn't rely on emag alone, but in return takes more time (perhaps acid?).

2022-08-31 16:00 UTC, EvilDragonfiend commented
> I want to see some method traitors can use to withdraw money, that doesn't rely on emag alone, but in return takes more time (perhaps acid?).

I will think about it.

2022-09-02 17:41 UTC, EvilDragonfiend commented
this PR should be merged after the PR I linked here. It will be set to draft until the primary PR is merged.

2022-09-23 14:00 UTC, Kenionatus commented
Disclaimer: not a Bee player, instead playing on NSV (Bee downstream)
I would argue that heads and other non-antag crew members having direct access to the money and being able to embezzle it is actually a good thing. It gives one more opportunity for IC conflict. As @NormalAnomaly said: clown buying meme crate with a department's money.
Another downside of this PR is that buying from a budget card increases the cost in the same way that buying from a personal budget does, as far as I can tell (unless the interface is lying). Even if transferring to the cargo budget through the head's console is possible that would be another hoop to jump through, which imo doesn't really add significant gameplay.

2022-09-25 17:57 UTC, EvilDragonfiend commented
I will not cancel this basic idea, but I will do that when the game can cover things a lot. The game needs more mechanics to support this feature.
I am not against embezzlement, but I don't like how easy it is.

2022-09-25 17:57 UTC, closed without merging