Voice changer randomizes your name if emp'd
BeeStation/BeeStation-Hornet pull request #7600
Opened 2022-09-02 19:53 UTC by etherware-novice

## About The Pull Request
If your voice changer mask is emp'd, it generates a random name every message.

## Why It's Good For The Game
Gives a unique effect for the voice changer emp (it currently does nothing), can also be seen as a positive if you want to cause chaos over the radio

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/73374039/188226913-cf9b676b-bc52-49b8-91da-d833fd00ffd0.png)

</details>

## Changelog
:cl:
tweak: voice changer now randomizes your name when emp'd
/:cl:

2022-09-03 07:43 UTC, EvilDragonfiend commented
You need failsafe to give a name when it failed to give a name. I.e.) when speces nane file has nothing.

2022-09-03 12:49 UTC, Penwin0 commented
What Dragon said, have a failsafe if it fails to get a name

2022-09-03 21:13 UTC, Archanial requested changes

2022-09-03 21:13 UTC, Archanial commented on code/modules/clothing/chameleon.dm
> +	var/rname_cooldown = 0
Please use cooldown defines

2022-09-03 21:13 UTC, Archanial commented on code/modules/mob/living/carbon/human/say.dm
> +				return randomize | "John Doe"  // fallback
```suggestion
				return randomize ?? "John Doe"  // fallback
```

2022-09-04 09:10 UTC, Penwin0 requested changes
Cooldown defines are used incorrectly, please look at their use in other code

2022-09-04 14:16 UTC, etherware-novice commented
yk you could just tell me whats wrong instead of being vauge? i dont see anything done wrong here

2022-09-10 08:38 UTC, PowerfulBacon requested changes

2022-09-10 08:38 UTC, PowerfulBacon commented on code/modules/mob/living/carbon/human/say.dm
> +			if(COOLDOWN_FINISHED(V, rname_cooldown))
Shouldn't it be if the cooldown hasn't finished?

2022-09-14 17:40 UTC, PowerfulBacon commented on code/modules/clothing/chameleon.dm
> +	rname_cooldown = INFINITY  // mulligan
Ironically, EMPing this will fix it, since it will get set to 2 mins instead of infinity.

2022-10-05 00:32 UTC, etherware-novice commented
@PowerfulBacon can you reopen

2022-10-11 17:49 UTC, closed without merging