Ports examine boxes from tg and probably other servers too
BeeStation/BeeStation-Hornet pull request #7611
Opened 2022-09-04 00:48 UTC by etherware-novice

## About The Pull Request
https://github.com/tgstation/tgstation/pull/67937

examine blocks, we all love em, and now theyre comin to bee!

## Why It's Good For The Game
visauls look good :)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/73374039/188292450-c1c40f28-3d41-4136-a5d0-5e0494d8edaf.png)

</details>

## Changelog
:cl:
add: examine boxes are a comin
/:cl:

2022-09-04 19:42 UTC, Penwin0 reviewed
I haven't gone through the whole thing yet

2022-09-04 19:42 UTC, Penwin0 commented on code/modules/mob/living/silicon/ai/examine.dm
> +// no idea what this does but the original pr has it so
Bad comment

2022-09-04 19:42 UTC, Penwin0 commented on code/__DEFINES/chat.dm
> +
```suggestion
/// Adds a generic box around whatever message you're sending in chat. Really makes things stand out.
```
You left this comment out from the original PR

2022-09-26 08:20 UTC, Penwin0 reviewed
You missed changes to atoms.dm /atom/proc/examine(mob/user)

2022-09-26 08:23 UTC, Penwin0 commented on code/modules/mob/living/silicon/ai/examine.dm
> -	. = list("<span class='info'>*---------*\nThis is [icon2html(src, user)] <EM>[src]</EM>!")
Is this span purposefully removed?

2022-09-26 08:23 UTC, Penwin0 commented on code/modules/mob/living/silicon/ai/examine.dm
> +// no idea what this does but the original pr has it so
It's still a bad comment even if you resolved the previous conversation

2022-10-03 15:06 UTC, PowerfulBacon requested changes
Changes requested, see above

2022-10-04 08:21 UTC, PowerfulBacon approved these changes

2022-10-04 08:21 UTC, PowerfulBacon commented
Needs better PR body completion in future

2022-10-04 08:21 UTC, merged

2022-10-04 12:40 UTC, PowerfulBacon commented on tgui/packages/tgui-panel/styles/goon/chat-light.scss
> +}
... why would you make it black on light more