Refactors mood events (again) to generate spans from mood changes
BeeStation/BeeStation-Hornet pull request #7630
Opened 2022-09-05 05:55 UTC by etherware-novice

## About The Pull Request
Makes the spans autogenerate based on the mood_effect amount. You can still manually set a span with var/span. 

below -5, and above 5, the text will be bolded
0 is now gray, in case there were any gray moods.

also theres now a green bolded for super good moodlets

## Why It's Good For The Game
Makes the mood code cleaner and consistent, also makes it easier for the player to estimate their mood levels

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/73374039/188369644-6e51b78f-a59b-47eb-bf2b-04f39d5c6053.png)

</details>

## Changelog
:cl:
refactor: mood_event now generates span on New()
/:cl:

2022-09-05 07:20 UTC, EvilDragonfiend commented
```
/proc/generate_mood_span(adjust)
    switch(mood_change)
        if(-BOLD_LIMIT to -1)
            span = "warning"
        if(-INFINITY to -BOLD_LIMIT)
            span = "boldwarning"
        if(0)
            span = "emote"  // nice grey color
        if(1 to BOLD_LIMIT)
            span = "nicegreen"
        if(BOLD_LIMIT to INFINITY)
            span = "greenannounce"
```

2022-09-05 18:41 UTC, itsmeow requested changes
Remove the `\n` from each one

2022-09-05 22:19 UTC, etherware-novice commented
then it will break the newline thing

2022-10-11 06:08 UTC, itsmeow commented
You can do it on the side that actually uses the description, as in the mood button should just add a \n on its own.

2022-10-11 18:05 UTC, closed without merging