HOLY MILK AND HOLY BILK
BeeStation/BeeStation-Hornet pull request #7654
Opened 2022-09-08 21:24 UTC by etherware-novice

## About The Pull Request
Adds holy milk and holy bilk, as well as a crafting recipie for holy bilk using holy milk and beer.

## Why It's Good For The Game
Offers multiple options for "blessed liquids", allows oozelings (slime!!!!!!!!) to be purified without having to deal with water debuffs

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/73374039/189228568-fdc2cc68-a945-40d7-9c06-58adf9734ffa.png)

</details>

## Changelog
:cl:
add: holy milk and holy bilk
/:cl:

2022-09-08 21:51 UTC, itsmeow requested changes
I don't like the way this is done, adding a bunch of ORs. It should be a var on regeant or something, or a signal, or a component, or an interface...

2022-09-08 21:51 UTC, itsmeow commented on code/datums/components/cult_ritual_item.dm
> +	if(!target.reagents.get_reagent(/datum/reagent/water/holywater) || !target.reagents.get_reagent(/datum/reagent/water/holywater/milk) || !target.reagents.get_reagent(/datum/reagent/water/holywater/bi
does get_reagent not include subtypes?

2022-09-08 22:47 UTC, etherware-novice reviewed
wait i did review by accident

2022-09-08 22:47 UTC, etherware-novice commented on code/datums/components/cult_ritual_item.dm
> +	if(!target.reagents.get_reagent(/datum/reagent/water/holywater) || !target.reagents.get_reagent(/datum/reagent/water/holywater/milk) || !target.reagents.get_reagent(/datum/reagent/water/holywater/bi
its just in case

2022-09-09 10:27 UTC, bluezorua commented
iirc oozelings dieing to holy water is an intentional feature and a part about their design

2022-09-09 21:29 UTC, Crossedfall commented
Continuing to believe that 'bilk' is a bit out of place here. :key:

2022-09-09 22:08 UTC, etherware-novice commented
then remove bilk

2022-09-10 01:47 UTC, ike709 commented
🔑 bloat

2022-09-10 01:47 UTC, closed without merging