PDA can now sort by name or job
BeeStation/BeeStation-Hornet pull request #767
Opened 2019-11-13 23:40 UTC by AWalton

https://github.com/tgstation/tgstation/pull/47638

## About The Pull Request

Removes the PDA- from the PDA names, makes the list easier to read. Added default sorting by owner name instead of item name to avoid scrambling the list during RPGloot event. Added toggleable sort by job.
## Why It's Good For The Game

Sorting good
## Changelog
 
:cl: Skoglol
add: PDA can now sort by owner name or job instead of item name.
/:cl:

2019-11-13 23:44 UTC, ike709 commented
Will review once the TG pull request is merged.

2019-11-22 02:25 UTC, ike709 commented
Doesn't compile.

2019-11-27 23:22 UTC, MarkSuckerberg requested changes
Fix the things

2019-11-27 23:22 UTC, MarkSuckerberg commented on code/__HELPERS/cmp.dm
> +	return sorttext(initial(b.name),initial(a.name))
Capitalize the a and b in (a.name/b.name)

2019-11-27 23:22 UTC, MarkSuckerberg commented on code/game/objects/items/devices/PDA/PDA.dm
> +			to_chat(L, "[icon2html(src)] <b>PDA message from [hrefstart][signal.data["name"]] ([signal.data["job"]])[hrefend], </b>[inbound_message] [reply]")
Change this line back to what it was before, it's throwing errors and works perfectly fine as is.

2019-12-03 22:08 UTC, ike709 commented
This will soon be closed as stale.

2019-12-06 02:15 UTC, ike709 commented
Stale.

2019-12-06 02:15 UTC, closed without merging