Cyborgs get radio for their module
BeeStation/BeeStation-Hornet pull request #7675
Opened 2022-09-11 19:31 UTC by etherware-novice

## About The Pull Request
Cyborgs get radio keys for their job (ie miners get Supply, Science, and Explo (if they want to help explocrew)

## Why It's Good For The Game
Makes it far easier as a borgo to support your department, know where people are, etc

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/73374039/189545516-e463d783-31d9-4b87-9f99-a16fbba744f4.png)
![image](https://user-images.githubusercontent.com/73374039/189545620-75af3e88-fc82-45f8-8101-a8cd5d724acf.png)
![image](https://user-images.githubusercontent.com/73374039/189545647-62a9114e-9dd1-46e2-abfc-742b816c856e.png)

</details>

## Changelog
:cl:
add: borgs get relevant radio keys
/:cl:

2022-09-11 19:59 UTC, Sarchutar commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	radio_channels = (RADIO_CHANNEL_AI_PRIVATE)
```suggestion
	radio_channels = list(RADIO_CHANNEL_AI_PRIVATE)
```

2022-09-12 01:50 UTC, Rukofamicom commented
![Screenshot_20220911-204504](https://user-images.githubusercontent.com/9547572/189560181-84d55e49-31dd-4589-a25c-303745ab60be.png)

These are the channels borgs should be getting per #7458.

Civilian channel doesn't exist yet, but those specific borgs don't have any department affiliation and don't need any extra channels

2022-09-12 02:22 UTC, etherware-novice commented
but mining keys grant science..

2022-10-11 07:59 UTC, itsmeow requested changes

2022-10-11 07:59 UTC, itsmeow commented on code/game/objects/items/devices/radio/radio.dm
> +			channels[channel] = 1
this should be TRUE, not 1, right?

2022-10-11 07:59 UTC, itsmeow commented on code/game/objects/items/devices/radio/radio.dm
> +	if(istype(loc))
`istype(R)`

2022-10-11 07:59 UTC, itsmeow commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	radio_channels = list(RADIO_CHANNEL_SERVICE)  // temporary until civilian channel
just remove this

2022-10-11 07:59 UTC, itsmeow commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	radio_channels = list(RADIO_CHANNEL_SYNDICATE, RADIO_CHANNEL_MEDICAL)
remove med

2022-10-11 07:59 UTC, itsmeow commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	radio_channels = list(RADIO_CHANNEL_SYNDICATE, RADIO_CHANNEL_ENGINEERING)
remove eng

2022-10-11 07:59 UTC, itsmeow commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	radio_channels = list(RADIO_CHANNEL_COMMAND)  // to be kidnapped by the HoP
remove

2022-10-11 07:59 UTC, itsmeow commented on code/game/objects/items/devices/radio/radio.dm
> +	. = ..()
this doesn't clear channels, so if you change modules back you don't lose any channel

2022-10-11 08:18 UTC, etherware-novice commented on code/game/objects/items/devices/radio/radio.dm
> +			channels[channel] = 1
idk the original radio code used 1

2022-10-11 08:18 UTC, etherware-novice commented on code/game/objects/items/devices/radio/radio.dm
> +	. = ..()
well how do i fricking do that

2022-10-11 18:05 UTC, closed without merging