Dynamic Incursion: Fix restricted roles for excomms
BeeStation/BeeStation-Hornet pull request #7687
Opened 2022-09-14 08:22 UTC by itsmeow

## About The Pull Request

Small oopsie with the objective generation makes it so sec can be excom.

Bad!!

## Why It's Good For The Game

Fix bug

## Testing Photographs and Procedure

Also near impossible to test, but trust me it works ™️ 

## Changelog
:cl:
fix: Dynamic incursion will no longer allow security to be traitors.
/:cl:

2022-09-14 10:08 UTC, PowerfulBacon requested changes, later dismissed

2022-09-14 10:08 UTC, PowerfulBacon commented on code/modules/antagonists/incursion/incursion.dm
> +/datum/team/incursion/proc/forge_single_objective(difficulty=1, list, list/restricted_jobs)
You sure this works?

2022-09-14 10:10 UTC, itsmeow commented on code/modules/antagonists/incursion/incursion.dm
> +/datum/team/incursion/proc/forge_single_objective(difficulty=1, list, list/restricted_jobs)
got dammit smooth brain 5am moment

2022-09-22 23:33 UTC, ike709 approved these changes

2022-09-25 05:34 UTC, merged