Log admin supply pods
BeeStation/BeeStation-Hornet pull request #7690
Opened 2022-09-15 01:44 UTC by ike709

well that's a real oversight

This is untested, have fun

## Changelog
:cl:
add: Added new things
admin: Admin supply pod launches are now logged
/:cl:

2022-09-15 02:19 UTC, ike709 commented on code/modules/cargo/centcom_podlauncher.dm
> +				var/msg = "[key_name_admin(user)] launched a supply pod at [COORD(get_turf(target))]."
```suggestion
				var/msg = "[key_name_admin(user)] launched a supply pod at [AREACOORD(target)]"
```

2022-09-15 17:43 UTC, PowerfulBacon commented on code/modules/cargo/centcom_podlauncher.dm
> +	var/full_msg = "[key_name_admin(usr)] [msg] in [ADMIN_VERBOSEJMP(specificTarget)]."
JMP is going to look fucky in the logs since its some weird href

2022-10-21 14:41 UTC, ike709 commented on code/modules/cargo/centcom_podlauncher.dm
> +	log_game(full_msg)
```suggestion
	var/full_msg_admins = "[key_name_admin(usr)] [msg] in [ADMIN_VERBOSEJMP(specificTarget)]."
	var/full_msg_logs = "[key_name_admin(usr)] [msg] in [AREACOORD(specificTarget)]."
	message_admins(full_msg_admins)
	log_game(full_msg_logs)
```

2022-10-27 06:03 UTC, itsmeow requested changes

2022-10-27 06:03 UTC, itsmeow commented on code/modules/cargo/centcom_podlauncher.dm
> +				message_admins(msg)
this should use LOOKUP_ADMINFLW

2022-10-27 06:03 UTC, itsmeow commented on code/modules/cargo/centcom_podlauncher.dm
> +	var/full_msg_admins = "[key_name_admin(usr)] [msg] in [ADMIN_VERBOSEJMP(specificTarget)]."
same here

2022-11-15 00:22 UTC, closed without merging