Adds more adminbus smites to keep the admins happy
BeeStation/BeeStation-Hornet pull request #7703
Opened 2022-09-18 06:18 UTC by mystery3525

## About The Pull Request

Adds some new smites, Adminheal, Admindamage, Give Cookie, Give Stalker Trauma, Force Sleep, and Table on every table on the zlevel.

If we come up with any more ~~crapola~~ great ideas we'll add it.

## Why It's Good For The Game

May or may not be good for the game, but definitely great for admins

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/30960302/190888500-bbbd9895-1360-4485-bd8b-8f07027096c6.png)

https://cdn.discordapp.com/attachments/1006361975456010250/1020930475725959228/dreamseeker_prcuN69fLT.mp4
how do I embed mp4

</details>

## Changelog
:cl:
add: Several new admin smites
/:cl:

2022-09-18 06:27 UTC, EvilDragonfiend commented
Do not let this feature shove them onto glass tables

2022-09-18 06:29 UTC, Tyranicranger4 commented
> Do not let this feature shove them onto glass tables

Literally 1984.

2022-09-18 06:33 UTC, EvilDragonfiend commented
> > Do not let this feature shove them onto glass tables
> 
> Literally 1984.

unless an admin wants all random glass tables in the station broken lol

2022-09-18 09:46 UTC, Rukofamicom commented
Get a proper chrono legionaire smite up and running, remove players from the round in style.

2022-09-20 03:55 UTC, mystery3525 commented
> Get a proper chrono legionaire smite up and running, remove low-risk but offending players from the round in style.

what do you mean 😳

2022-09-20 12:07 UTC, Rukofamicom commented
It spawns someone outfitted in the Chrono Legionnaire equipment to hunt down the smited person. After hunting the person down, the Legionnaire vanishes themselves. Their equipment doesn't work on anyone except the hunted target and the player is removed "From the timeline entirely" which is to say the same as if they had cryo'd will occur to objectives and manifest.

It is usually used it to remove people with bad character names, such as Hitler or Minecraft Steve ("This isn't your universe" or "Your bloodline is a threat to the universe") but can be used to somewhat immersively remove any banned player in a way that's more interesting for the round, so long as the banned player isn't at risk of griefing in response to the ban. 

![image](https://user-images.githubusercontent.com/9547572/191253362-a7e44dcb-d9f8-49a3-b927-f9b455eba6df.png)

2022-09-22 02:44 UTC, mystery3525 commented
yeah we decided against that because 
1. legionnare is broken (or so I have been told)
2. Why would a griefer or someone named "BAN EVADER" ever actually roleplay meaningfully with someone meant to round remove them
3. creating a custom antagonist designed to hunt down a shitter is outside the scope of this pr

2022-09-23 04:24 UTC, Rukofamicom commented
> Why would a griefer or someone named "BAN EVADER" ever actually roleplay meaningfully with someone meant to round remove them

I can understand deciding against it, but this is downright insulting/bad faith.

2022-09-24 15:57 UTC, itsmeow commented
>     1. legionnare is broken (or so I have been told)

https://github.com/BeeStation/BeeStation-Hornet/pull/7673

2022-09-25 19:04 UTC, itsmeow requested changes

2022-09-25 19:04 UTC, itsmeow commented on code/modules/admin/verbs/randomverbs.dm
> -	if (!sender)
i hate this so much

2022-09-25 19:04 UTC, itsmeow commented on code/modules/admin/verbs/randomverbs.dm
> +	message_admins(msg)
message_admins should use ADMIN_LOOKUPFLW instead of key_name_admin

2022-09-28 22:37 UTC, FortSumter commented
"I understand the council has made a decision, but considering it's a stupid decision I've elected to ignore it"

Chrono legionnaire isn't meant to be entertaining for the offender, but for everyone else. It is a sad day when you can't even make banning someone fun.

2022-09-28 22:42 UTC, itsmeow commented
It's unrelated to the PR, it's not a "no" it's a "this is not part of the scope of the PR"

2022-10-02 12:55 UTC, PowerfulBacon requested changes, later dismissed

2022-10-02 12:55 UTC, PowerfulBacon commented on code/modules/admin/verbs/randomverbs.dm
> +	if(!sender)
Spaces between if statements should not be changed for no reason. See code standards for more details.

2022-10-27 03:50 UTC, mystery3525 commented
@itsmeow reopen please I have been resurrected and addressed the reviews in latest push

2022-10-27 03:53 UTC, itsmeow requested changes

2022-10-27 03:53 UTC, itsmeow commented on code/modules/admin/verbs/randomverbs.dm
> +	if( !msg )
wtf is this

2022-10-27 03:54 UTC, mystery3525 commented on code/modules/admin/verbs/randomverbs.dm
> +	if( !msg )
github fuckery

2022-10-27 03:54 UTC, itsmeow submitted a review, later dismissed

2022-10-27 04:03 UTC, itsmeow commented
```
code/modules/admin/verbs/randomverbs.dm, line 1307, column 19:
error: undefined var: "whom"

code/modules/admin/verbs/randomverbs.dm, line 1307, column 73:
error: undefined var: "whom"

code/modules/admin/verbs/randomverbs.dm, line 1308, column 70:
error: undefined var: "whom"

code/modules/admin/verbs/randomverbs.dm, line 1309, column 48:
error: undefined var: "whom"
```

2022-10-27 04:25 UTC, itsmeow approved these changes

2022-10-27 04:26 UTC, merged