Portasniffer
BeeStation/BeeStation-Hornet pull request #7720
Opened 2022-09-26 08:01 UTC by etherware-novice

## About The Pull Request
adds a portable ecto sniffer, that relays triggers from any sniffer in the map

## Why It's Good For The Game
endlessly helps robotics mains, as they can be alerted from *anywhere* of possible positronic brains. this also helps makes it easier to gte back in the game as a borg

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/73374039/192224127-98f3b9bd-d850-4b57-aaa4-423af3f3e8f0.png)
![image](https://user-images.githubusercontent.com/73374039/192224188-def254a0-1c30-4156-852e-e04319535e9f.png)

</details>

## Changelog
:cl:
add: ectoscopic sniffer portable edition
/:cl:

2022-09-26 12:45 UTC, Sarchutar commented on code/game/machinery/ecto_sniffer.dm
> +	var/on = TRUE
It's missing something to actually turn it off and on again. Right now it's permanently on.

2022-09-26 13:14 UTC, FriendlyContractor commented
Portasniffer should be paired with a specific sniffer rather than activate when any is used.

2022-09-27 05:19 UTC, etherware-novice commented
that would just make it harder for ghosts to get respawned, they might not know which ecto is linked, and it wouldnt change that much anyway

2022-10-11 07:26 UTC, itsmeow requested changes

2022-10-11 07:26 UTC, itsmeow commented on code/game/machinery/ecto_sniffer.dm
> +	desc = "A small handheld device that listens for electroscopic transmissions."
should be "ectoscopic"

2022-10-11 07:26 UTC, itsmeow commented on code/game/machinery/ecto_sniffer.dm
> +	var/clear_after = 5
this should directly the defines `5 MINUTES` instead of in the usage

2022-10-11 07:26 UTC, itsmeow commented on code/game/machinery/ecto_sniffer.dm
> +	if(last_trigger > world.time + clear_after MINUTES)  // only displays from the last 5 minutes
should wrap (world.time + clear_after) with parenthesis and remove `MINUTES` as said above

2022-10-11 07:26 UTC, itsmeow commented on code/game/machinery/ecto_sniffer.dm
> +		. += "It's last recorded trigger is [display_time], and will clear in [clear_after] minutes."
Should be "its", also use `\s` for "minutes"

2022-10-11 17:52 UTC, closed without merging