Pepperspray rework
BeeStation/BeeStation-Hornet pull request #775
Opened 2019-11-14 02:12 UTC by AWalton

https://github.com/tgstation/tgstation/pull/46342

## About The Pull Request

Volume increased to 50 for pepper spray, added knockdown of decreasing degree for decreasing importance pepper spray entrance organs, added confuse, blind, blur, slow down. Adds a new clothing flag for head and mouth, PEPPERPROOF, that will decide if you can be pepper-sprayed while wearing those. Decreases scope of pepperspray protection by a lot.
## Why It's Good For The Game
 
Pepper spray is not even worth using right now, and I routinely see sec officers throwing away their pepper spray for e-bolas, handcuffs or flashbangs. This PR will make pepper spray a viable option in the sec arsenal, but does account for the range and spam ability of pepper spray while still making it competitive. As we are moving away from hardstuns, I see it fit to replace the hard stun with some bad effects, slowdown and knockdown. Helmets, Hardsuits, Gas masks, and other things like that are pepperproof
## Changelog

:cl:
balance: increased volume of pepper sprays to 50
tweak: adds knockdown of 3 second for no protection, 3 for no mouth protection
tweak: Changes bluring and blindness of eyes
balance: Replaces Paralysis with blind
balance: vastly decreased the scope of pepperspray protection.
 add: New variable for pepperspray protection, PEPPERPROOF, decides if you can be pepperproof with certain equipment
:/cl:

2019-11-14 03:28 UTC, ike709 commented
![image](https://user-images.githubusercontent.com/5714543/68824448-7cdf7a80-065c-11ea-9e4b-22138d4ef66d.png)

2019-11-14 04:50 UTC, AWalton commented
Whoops added something that shouldn't be there.

2019-11-14 05:31 UTC, ike709 commented on code/modules/clothing/glasses/hud.dm
> +	var/hud_trait = null
Unrelated change?

2019-11-14 05:32 UTC, ike709 requested changes
Address the comment.

2019-11-14 13:04 UTC, AWalton commented on code/modules/clothing/glasses/hud.dm
> +	var/hud_trait = null
Ah yes, I'll remove.

2019-11-14 18:19 UTC, MarkSuckerberg commented
Have you tested it?

2019-11-15 07:42 UTC, Crossedfall approved these changes
Seems to work within the test merge

2019-11-15 07:42 UTC, merged