Make Birdboat not loop endlessly when it checks for food nor call stoplag()
BeeStation/BeeStation-Hornet pull request #7758
Opened 2022-10-01 17:21 UTC by Penwin0

## About The Pull Request
What it says on the tin

## Why It's Good For The Game
Birdboat refusing to eat shouldn't endlessly spam the chat and constantly call stoplag()

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![Screenshot_1287](https://user-images.githubusercontent.com/53474257/193420876-581c3117-05d9-464d-a3ce-837efbfb759d.png)

</details>

## Changelog
:cl:
code: Birdboat doesn't loop forever when checking for food and doesn't call stoplag() anymore
/:cl:

2022-10-01 17:46 UTC, PowerfulBacon approved these changes

2022-10-01 17:46 UTC, PowerfulBacon requested changes

2022-10-01 17:46 UTC, PowerfulBacon commented on code/modules/mob/living/simple_animal/hostile/goose.dm
> +	if (currentTurf == get_turf(src))
this check is useless

2022-10-01 18:05 UTC, Penwin0 commented on code/modules/mob/living/simple_animal/hostile/goose.dm
> +	if (currentTurf == get_turf(src))
You are right how didn't I see this lol

2022-10-02 10:09 UTC, PowerfulBacon approved these changes

2022-10-02 10:09 UTC, merged