Ports BoH bombing rework II
BeeStation/BeeStation-Hornet pull request #776
Opened 2019-11-14 04:29 UTC by AWalton

https://github.com/tgstation/tgstation/pull/45174

## About The Pull Request

Ever since the big BoH nerf, BoH bombing is kind of a joke. The damage it does is not really huge, and it's lame for traitors - it lacks emotion and their target may not even die, as they can use the ladders to get away.

So, what this does is add back some soul into BoH bombing, while not making it too round-ending and adding some degree of damage control for admins in case of griefing.
When BoH bombing, a stationary singulo with custom sprite will spawn. Its gravitational pull is REALLY strong, so people near it are probably going to get eaten, and there will be some real damage to the hull. The singulo will cease existing after 5 seconds.

For antags, I think this becomes much more interesting than the current BoH bombing. In the case of griefers, the damage to the station isn't too big because the singulo is stationary and fades away after some seconds. And then, admins can click a button in their chat to bring back everything the singulo ate into the game (the button expires in 10 minutes, however, but this can be changed if you think it is needed).

Settings like gravitational pull can be tweaked if yall find it to be too strong or something.
## Changelog

:cl:
tweak: BoH bombing changed again. Now it's more violent.
/:cl:

2019-11-14 05:29 UTC, ike709 requested changes
Fails travis.

2019-11-14 18:16 UTC, MarkSuckerberg requested changes
Some things I noticed

2019-11-14 18:16 UTC, MarkSuckerberg commented on code/game/area/areas/centcom.dm
> -/area/fabric_of_reality
If you delete this, make sure to delete it from the map.

2019-11-14 18:16 UTC, MarkSuckerberg commented on code/game/objects/structures/ladders.dm
> -/obj/structure/ladder/unbreakable/binary
I don't think all of these ladders should be removed.

2019-11-14 18:16 UTC, MarkSuckerberg commented on code/game/turfs/simulated/chasm.dm
> -/turf/open/chasm/magic
Need to remove this from maps too.

2019-11-14 18:16 UTC, MarkSuckerberg commented on code/modules/power/singularity/boh_tear.dm
> +	desc = "Your own comprehension of reality starts bending as you stare this."
Change to "...stare at it."

2019-11-14 18:16 UTC, MarkSuckerberg commented on tgstation.dme
> +// DM Environment file for tgstation.dme.
This isn't tgstation. Please modify beestation.dme.

2019-11-18 19:25 UTC, AWalton commented
I'll reopen at a later date when I can make these changes.

2019-11-18 19:25 UTC, closed without merging