Radio jammer component
BeeStation/BeeStation-Hornet pull request #7775
Opened 2022-10-02 11:09 UTC by PowerfulBacon

## About The Pull Request

Converts radio jamming to a component.

## Why It's Good For The Game

This provides no player facing changes.
This allows coders to create devices which act as radio jammers without requiring them to be a subtype of /obj/item/jammer. Requiring subtypes for functionalitites is bad, since if you have 2 things that work this way, you cannot create an item that combines the functionality of both without duplicating code, which is bad for maintainability.

## Testing Photographs and Procedure

## Changelog
:cl:
refactor: Radio jamming is now component based. (No player facing changes.)
/:cl:

2022-10-03 15:33 UTC, Zonespace27 commented on code/game/objects/items/devices/traitordevices.dm
> +	for(var/datum/component/radio_jamming/jammer in GLOB.active_jammers)
```suggestion
	for(var/datum/component/radio_jamming/jammer as anything in GLOB.active_jammers)
```

2022-10-03 15:33 UTC, Zonespace27 commented on code/datums/components/radio_jamming.dm
> +		to_chat(user,"<span class='notice'>You [!active ? "deactivate" : "activate"] [parent].</span>")
```suggestion
		to_chat(user, "<span class='notice'>You [!active ? "deactivate" : "activate"] [parent].</span>")
```

2022-10-03 16:09 UTC, PowerfulBacon commented on code/datums/components/radio_jamming.dm
> +		to_chat(user,"<span class='notice'>You [!active ? "deactivate" : "activate"] [parent].</span>")
Good spot

2022-10-03 16:09 UTC, PowerfulBacon commented on code/game/objects/items/devices/traitordevices.dm
> +	for(var/datum/component/radio_jamming/jammer in GLOB.active_jammers)
There should be no way for this to hard del and stay null, so this should be fine

2022-10-03 19:40 UTC, itsmeow requested changes

2022-10-03 19:40 UTC, itsmeow commented on code/datums/components/radio_jamming.dm
> +		disable(source, user, silent)
these methods don't have these args

2022-10-04 08:04 UTC, PowerfulBacon commented on code/datums/components/radio_jamming.dm
> +		enable(source, user, silent)
```suggestion
		disable()
	else
		enable()
```
They used to

2022-10-08 18:16 UTC, itsmeow approved these changes
Looks good although how would someone pass a range to the component's Initialize?

2022-10-09 10:07 UTC, PowerfulBacon commented
The same was you pass parameters to any component
AddComponent(/datum/component/whatever, 50)

2022-10-09 11:05 UTC, Penwin0 approved these changes

2022-10-09 11:06 UTC, merged