glue has a sudice now
BeeStation/BeeStation-Hornet pull request #7799
Opened 2022-10-03 07:42 UTC by etherware-novice

## About The Pull Request
glue can selfdie in a good way

## Why It's Good For The Gamey
yes

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: glue suidicdw
/:cl:

2022-10-03 08:11 UTC, itsmeow commented
> sudice

yes

2022-10-03 13:10 UTC, itsmeow requested changes
Please fix the awful grammar in the PR body and CL and fill out "Why it's good for the game" properly.

2022-10-03 13:10 UTC, itsmeow commented on code/game/objects/items/devices/glue.dm
> +	visible_message("<span class='suicide'>[M] is drinking the whole bottle of glue! It looks like [M.p_theyre()] trying to commit suicide!</span>")
should be `M.visible_message`

2022-10-03 15:10 UTC, PowerfulBacon commented
Sad it doesnt glue their throat shut, disabling their ability to breathe

2022-10-03 15:11 UTC, etherware-novice commented on code/game/objects/items/devices/glue.dm
> +	visible_message("<span class='suicide'>[M] is drinking the whole bottle of glue! It looks like [M.p_theyre()] trying to commit suicide!</span>")
thaats why its not displaying

2022-10-03 20:37 UTC, Penwin0 commented
Changelog is misspelt

2022-10-03 22:00 UTC, etherware-novice commented
alright can someone help? its still displaying the "getting too high on life" message

2022-10-04 06:16 UTC, hotimep commented
NEEDS TO BE FUNNIER!!!

2022-10-04 13:41 UTC, etherware-novice commented
> NEEDS TO BE FUNNIER!!!

oh shut up you memey dope be glad i dont quit outright

2022-10-11 06:49 UTC, itsmeow approved these changes

2022-10-11 17:53 UTC, merged