Martial arts QOL
BeeStation/BeeStation-Hornet pull request #7809
Opened 2022-10-03 20:41 UTC by CydiaLamiales

## About The Pull Request
Moves the text describing the combos of your current martial art from the chat to a separate window. Also adds coloring to the intents.

## Why It's Good For The Game
When you don't know the martial art combos by hand you either need to stop the chat from scrolling, which can make it hard to tell if you hand a combo, or constantly spam the button. This allows people to keep the chat scrolling while also keeping an eye out on the list of the moves.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
Karate moveset window :

![image](https://user-images.githubusercontent.com/110184118/193676287-f62120ad-f59d-496c-8543-a518aacacf60.png)
CQC moveset window : 

![image](https://user-images.githubusercontent.com/110184118/193676663-a621400b-4c25-40ab-ae54-90564af1559a.png)
Sleeping Carp moveset window:

![image](https://user-images.githubusercontent.com/110184118/193678064-1b02963e-4e26-45f4-85fd-c3cebd47832a.png)
Tribal Claw moveset window:

![image](https://user-images.githubusercontent.com/110184118/193678290-21b133d2-f357-465b-bfd4-f1e2ecfbeac8.png)
Plasma Fist moveset window:

![image](https://user-images.githubusercontent.com/110184118/193677163-9addda43-9050-4c92-80f4-cce2b1619b7c.png)

</details>

## Changelog
:cl:
add: Added colors to the intents listed in combo lists.
tweak: Made the "Recall your martial art moves" verbs output their text into a separate window rather than the chat
/:cl:

2022-10-03 20:51 UTC, Penwin0 requested changes

2022-10-03 20:51 UTC, Penwin0 commented on code/datums/martial/karate.dm
> +	/*
Don't leave commented code

2022-10-03 20:54 UTC, CydiaLamiales commented on code/datums/martial/karate.dm
> +	/*
Ah crap, I knew I forgot something.

2022-10-03 20:56 UTC, PowerfulBacon commented
Generally, UIs that are being newly added and didn't exist already should be made with TGUI rather than using browse()

2022-10-03 20:59 UTC, CydiaLamiales commented
I'm gonna be honest I've got no idea how TGUI works. But if need be I'll remake this PR.

2022-10-04 12:58 UTC, Archanial requested changes
This looks good but please make it use TGUI.
We're trying to move away from legacy UIs.

2022-11-05 00:24 UTC, closed without merging