[Port-ish]Buildable shutters, filling cabinet recipe and dedicated category for crafting structures
BeeStation/BeeStation-Hornet pull request #7813
Opened 2022-10-03 22:21 UTC by PestoVerde322

## About The Pull Request

This PR ports https://github.com/tgstation/tgstation/pull/56486, https://github.com/tgstation/tgstation/pull/61746, https://github.com/tgstation/tgstation/pull/58231 and implement a dedicated crafting tab for structures, where now stuff like the guillotine, curtains and the buildable shutters.

Future to do:
- [ ] Port or sprite anew the Radiation and the window shutter off https://github.com/tgstation/tgstation/pull/53861 and add their respective recipe 

## Why It's Good For The Game

More customization options, Ability to make your own "safe" area, fun for everyone!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![dreamseeker_GogHoT8gGP](https://user-images.githubusercontent.com/75247747/193694125-49a03b9d-e46c-4f4a-81fd-c4def94a9ce1.jpg)

![dreamseeker_oDHQPwP8sh](https://user-images.githubusercontent.com/75247747/193694130-0ffd5bc6-abe8-44cf-bd13-384d22f1b168.jpg)

</details>

## Changelog
:cl:
add: Added craftable filing cabinets that can be constructed for 2 iron sheets
add: Added blast doors and shutters to the crafting menu and blast door controllers to autolathes. As well as deconstruction steps.
tweak: new dedicated structures category, instead of misc for all structure things
/:cl:

2022-10-05 22:48 UTC, itsmeow requested changes

2022-10-05 22:48 UTC, itsmeow commented on code/game/machinery/doors/shutters.dm
> +	desc = "Depleted uranium-lined shutters with a radiation hazard symbol. Whilst this won't stop you getting irradiated, especially by a supermatter crystal, it will stop the majority of radiation tra
Remove "travelling as far"

2022-10-05 22:48 UTC, itsmeow commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +/datum/crafting_recipe/aquarium
looks like a mistake

2022-10-05 22:48 UTC, itsmeow commented on code/game/objects/structures/watercloset.dm
> +	name = "Plastic curtain"
lowercase

2022-10-05 22:48 UTC, itsmeow commented on code/modules/assembly/doorcontrol.dm
> +	var/change_id = input("Set the shutters/blast door/blast door controllers ID. It must be a number between 1 and 100.", "ID", id) as num|null
`controller's`. Also says blast door twice.

2022-10-05 22:48 UTC, itsmeow commented on code/game/machinery/doors/poddoor.dm
> +			var/change_id = input("Set the shutters/blast door/blast door controllers ID. It must be a number between 1 and 100.", "ID", id) as num|null
see other review

2022-10-06 19:23 UTC, itsmeow commented
Are you able to put the controllers into button casings?

2022-10-08 13:48 UTC, PowerfulBacon commented
Are shutters even breakable conventionally? Can you defeat them?

2022-10-10 06:38 UTC, PestoVerde322 commented
> Are you able to put the controllers into button casings?

Absolutely, you can build them by an autolathe, however I am considering to toss a bunch of them in tool storage and in engineering, or maybe in the vending machine for parts.

2022-10-10 06:38 UTC, PestoVerde322 commented
> Are shutters even breakable conventionally? Can you defeat them?

Depends, unless specified with the indestructible variant, they they're breakable by default (and constructible by "crafting" them as if you're building a guillotine).

2022-10-10 06:52 UTC, itsmeow commented
Also would appreciate if this was put on the Guide to Construction wiki page

2022-10-10 18:29 UTC, PestoVerde322 commented
> Also would appreciate if this was put on the Guide to Construction wiki page

Updated the wiki with the recipes for the shutters.

2022-10-10 18:40 UTC, PestoVerde322 commented
Also note to self, remove Flandstation from this, since Sp5 is in it's way

2022-10-11 10:19 UTC, PestoVerde322 commented
and rollback'd

2022-10-11 23:26 UTC, itsmeow requested changes
move aquarium to construction category

2022-10-13 20:11 UTC, itsmeow commented
What are the mapping changes?

2022-10-14 12:05 UTC, PestoVerde322 commented
> What are the mapping changes?

ah damn i forgot to add it in the CL, but it adds on all the maps but fland radshutters next to the SM.

2022-10-15 11:06 UTC, itsmeow approved these changes

2022-10-26 01:01 UTC, merged