Masks are hidden behind helmets
BeeStation/BeeStation-Hornet pull request #7831
Opened 2022-10-04 23:09 UTC by etherware-novice

## About The Pull Request

## Why It's Good For The Game

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-10-04 23:10 UTC, etherware-novice commented
I HIT ENTER ACCIDENTILLY OK

2022-10-08 11:37 UTC, Penwin0 requested changes

2022-10-08 11:37 UTC, Penwin0 commented on code/game/objects/items/holy_weapons.dm
> +	flags_inv = HIDEHAIR|HIDEFACE|HIDEEARS|HIDEMASK
Does this sprite really cover the face?

2022-10-08 11:37 UTC, Penwin0 commented on code/modules/antagonists/cult/cult_items.dm
> +	flags_inv = HIDEFACE|HIDEHAIR|HIDEEARS|HIDEMASK
Same here

2022-10-08 11:37 UTC, Penwin0 commented on code/modules/antagonists/cult/cult_items.dm
> +	flags_inv = HIDEFACE|HIDEHAIR|HIDEFACIALHAIR|HIDEEARS|HIDEEYES|HIDEMASK
Same here

2022-10-08 11:37 UTC, Penwin0 commented on code/modules/antagonists/cult/cult_items.dm
> +	flags_inv = HIDEHAIR|HIDEFACE|HIDEEARS|HIDEMASK
same here

2022-10-08 11:37 UTC, Penwin0 commented on code/modules/antagonists/cult/cult_items.dm
> +	flags_inv = HIDEHAIR|HIDEFACE|HIDEEARS|HIDEMASK
Same here

2022-10-08 11:37 UTC, Penwin0 commented on code/modules/clothing/head/hardhat.dm
> +	flags_inv = HIDEEYES | HIDEFACE | HIDEMASK
Shouldn't hide it by default, only when visor is down

2022-10-08 11:37 UTC, Penwin0 commented on code/modules/clothing/head/helmet.dm
> +	flags_inv = HIDEEARS|HIDEFACE|HIDEMASK
This sprite is transparent, it might look weird, do check

2022-10-08 11:37 UTC, Penwin0 commented on code/modules/clothing/head/misc.dm
> +	flags_inv = HIDEHAIR|HIDEFACE|HIDEEARS|HIDEMASK
Sombreros don't cover your mask area

2022-10-08 11:37 UTC, Penwin0 commented
You've also added it to a bunch of masks, which I don't think is necessary and might look weird, do check

2022-10-08 12:24 UTC, PowerfulBacon requested changes
Heads that don't fully cover the face shouldn't hide the mask

2022-10-11 06:43 UTC, closed without merging