Disable revolutionary gamemode
BeeStation/BeeStation-Hornet pull request #7986
Opened 2022-10-30 19:17 UTC by mystery3525

## About The Pull Request

Disables the Provocateur latejoin and Revolution roundstart dynamic rules, and sets the weight for the revolution gamemode to zero, effectively disabling it.

## Why It's Good For The Game

Typical revolutions devolve into the round ending within 20-30 minutes, or the round being dragged to 90+ minutes of nothing but trying to find the last head of staff or last head revolutionary being hidden or fuck off in space. This isn't an outright removal, but this just disables them unless someone can make this antagonist a little more fun/engaging.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Idk, check files? Also xenoarch is causing build errors.

</details>

## Changelog
:cl:
config: disables the revolutionary gamemode and dynamic rulesets
/:cl:

2022-10-30 19:39 UTC, CydiaLamiales commented
Finally someone did it, god bless.

2022-10-30 20:23 UTC, PowerfulBacon requested changes, later dismissed

2022-10-30 20:23 UTC, PowerfulBacon commented on code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
> +	weight = 0
Update these via the dynamic json

2022-10-30 20:30 UTC, FriendlyContractor commented
While i agree with round stalling being a problem i find myself greatly enjoying the gamemode. Are there really so few players enjoying revolution that its removal is warranted ?

2022-10-30 21:21 UTC, CydiaLamiales commented
> Are there really so few players enjoying revolution that its removal is warranted ?

I'd say yes. Most of the time it just turns into a NRP murderfest.

2022-10-30 22:54 UTC, Rukofamicom commented
> i find myself greatly enjoying gamemode majority of the time.

There's more to the equation than just being fun - there's a lot of things I enjoy that aren't a good fit for the server or conducive to an RP environment. I do mechanically enjoy team deathmatch and even FFA deathmatch (I especially love battle royale), But these aren't conducive to an RP setting at all. 

While it's good to factor how fun something is or can be into the equation, it needs to be weighed against the goals of the server and what sort of experience it wants to serve its players.

2022-10-31 08:58 UTC, PowerfulBacon commented
I'll sign off on this :+1:

2022-11-01 09:33 UTC, itsmeow commented
does the game start with this config though

2022-11-02 08:48 UTC, PowerfulBacon commented
Wdym? We have to update the config on the server when we merge it

2022-11-02 08:52 UTC, itsmeow commented
just wondering if weight:0 will cause issues with dynamic

2022-11-08 18:19 UTC, PowerfulBacon commented
We should add a boolean disabled value to this config

2022-11-12 04:28 UTC, mystery3525 commented
So is there any changes I need to do?

2022-11-18 07:47 UTC, PowerfulBacon commented
Add in a way to disable gamemodes properly to dynamic config

2022-11-18 11:26 UTC, itsmeow commented
The official way to disable gamemodes is setting cost to 110. Just remove weight: 0

The cost 110 thing is intended and already used for meteors.

2022-11-19 00:17 UTC, mystery3525 commented
👍

2022-11-19 05:15 UTC, itsmeow approved these changes

2022-11-22 07:45 UTC, PowerfulBacon commented
That is incredibly dumb and shouldn't be the official way to remove gamemodes

2022-11-22 17:06 UTC, itsmeow commented
out of scope

2022-11-29 01:56 UTC, itsmeow commented
Soul removed

2022-11-29 01:56 UTC, merged

2022-11-29 01:58 UTC, itsmeow commented
Config change applied