Adds myself to codeowners
BeeStation/BeeStation-Hornet pull request #7991
Opened 2022-10-30 20:52 UTC by Archanial

## About The Pull Request

yeah I codeown runechat now 😎 
also looked into the file itself and fixed two undefs

## Changelog
:cl:
add: Added myself as codeowner of runechat
/:cl:

2022-10-30 21:36 UTC, PowerfulBacon submitted a review, later dismissed

2022-10-30 23:24 UTC, Crossedfall requested changes
Don't mix PRs.

2022-10-30 23:24 UTC, Crossedfall commented on code/datums/chatmessage.dm
> +#undef COLOR_PERSON_UNKNOWN
```suggestion
```

2022-10-30 23:26 UTC, Crossedfall commented
I don't really see the need for a codeowner over runechat. What's to be gained from gatekeeping it? It doesn't seem so complex that we need a subject matter expert on it.

2022-11-04 15:33 UTC, Crossedfall commented
Closing per my prior statement. I don't see the need for this to be locked behind a single maintainer.

2022-11-04 15:33 UTC, closed without merging