Fix flammable & malfunction traits - xenoarch goof
BeeStation/BeeStation-Hornet pull request #8012
Opened 2022-11-03 04:54 UTC by DrDuckedGoose

## About The Pull Request

Another fix PR for the not broken xenoarchaeology.

Fixes flammable trait - The flammable trait at some point has been broken, I swear it worked last time I tested it. I assume this is either due to byond updates or code changes idk. No-one even told me it was broken, I just had to discover it did at some point while playing.

Fixes malfunctions (blacklist) - Classic gamer goof, malfunction blacklists weren't working properly on the explosive malfunction.

Fixes malfunctions (entity overflow) - The clone malfunction didn't have a cap, you could make infinite evil clones, now it has a cap of 5 at once. Swaps the bear limit over to this, it's better than destroying the artifact.

## Why It's Good For The Game

Bugs aren't great, neither is server stress. 

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/40559528/199649856-077a021f-ff23-481f-87cd-28d754e27db3.png)
![image](https://user-images.githubusercontent.com/40559528/199649973-5cb1398b-5fdd-4df2-86cd-6465d8c195d8.png)

</details>

## Changelog
:cl:
fix: Fix flammable trait not activating
fix: Fix blacklisting on explosive malfunction
tweak: Add limit to clone & bear malfunction.
/:cl:

2022-11-06 18:02 UTC, itsmeow requested changes

2022-11-06 18:02 UTC, itsmeow commented on code/modules/xenoarchaeology/traits/xenoartifact_malfunctions.dm
> +	if(bears.len >= XENOA_MAX_BEARS)
length(bears) pls

2022-11-06 18:02 UTC, itsmeow commented on code/modules/xenoarchaeology/traits/xenoartifact_malfunctions.dm
> +	var/mob/living/simple_animal/hostile/bear/new_bear = new(get_turf(X.loc))
this is jank put get_turf onto its own var, also no need to get the loc of X since get_turf finds the nearest turf anyway

2022-11-06 18:02 UTC, itsmeow commented on code/modules/xenoarchaeology/traits/xenoartifact_malfunctions.dm
> +	if(clones.len >= XENOA_MAX_CLONES)
length(clones)

2022-11-06 23:15 UTC, Archanial commented on code/modules/xenoarchaeology/traits/xenoartifact_malfunctions.dm
> +	new_bear.name = pick("Freddy", "Bearington", "Smokey", "Beorn", "Pooh", "Paddington", "Winnie", "Baloo", "Rupert", "Yogi", "Fozzie", "Boo") //Why not?
I believe Paddington is copyrighted

2022-11-07 03:18 UTC, DrDuckedGoose commented
Copyright moment

2022-11-08 00:52 UTC, itsmeow approved these changes

2022-11-08 08:55 UTC, merged