no 'Follow' ghost option to simple mob emotes
BeeStation/BeeStation-Hornet pull request #8090
Opened 2022-11-19 06:30 UTC by EvilDragonfiend

## About The Pull Request

no 'Follow' ghost option to simple mob emotes.
chat will not show `(F)` button on emotes when they have no mind

## Why It's Good For The Game
better chat readability for ghosts

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/87972842/202835696-366b252e-f3cc-41d4-88a2-74af13c8a49b.png)

![image](https://user-images.githubusercontent.com/87972842/202835703-d10d6fbd-de9f-4000-b166-7d34f2d8f2fc.png)

![image](https://user-images.githubusercontent.com/87972842/202835713-0524eb3e-e469-4a15-8417-1249a43aafab.png)

</details>

## Changelog
:cl:
tweak: ghost will not see (F) button on emotes that are done by mobs having no mind
/:cl:

2022-11-19 08:13 UTC, PowerfulBacon commented
What if I want to follow them? There is a preference to disable ghost vision, there should be a preference to disable ghost vision for mindless mobs instead (although diseases make it practically impossible to observe while on anyway)

2022-11-19 09:25 UTC, EvilDragonfiend commented
> What if I want to follow them? There is a preference to disable ghost vision, there should be a preference to disable ghost vision for mindless mobs instead (although diseases make it practically impossible to observe while on anyway)

I guess I will just use 'Jump To Mob'

2022-11-19 12:58 UTC, ivanmixo commented
Literally why? If we're going to have the line shown to us as a ghost we might as well have the 3 extra characters to follow.

2022-11-19 13:15 UTC, EvilDragonfiend commented
> Literally why? If we're going to have the line shown to us as a ghost we might as well have the 3 extra characters to follow.

first, it's annoying to misclick
second, It's a bit disruptive to read other chat lines since everything says (F), and having no it would easily make you it's not important.
third, it's mindless mob. why do you really need to track it?

2022-11-19 14:11 UTC, ivanmixo commented
Again, if we're going to print the line we might as well have the option to follow it. Just make a pref that disables emotes from mindless mobs for ghosts.

2022-11-21 05:22 UTC, EvilDragonfiend commented
added, but you'll need to toggle it back if you want to see (F) from all mobs due to how pref works.

2022-11-30 16:03 UTC, PowerfulBacon requested changes
I think using the term 'NPC' mobs is an easier and shorter way to describe mobs with no minds for players that do not know what a mind is in code.

2022-11-30 16:03 UTC, PowerfulBacon commented on code/modules/client/preferences_toggles.dm
> +	set name = "Toggle Ghost (F) Chat"
```suggestion
	set name = "Toggle NPC GhostFollow"
```

2022-11-30 16:03 UTC, PowerfulBacon commented on code/modules/client/preferences_toggles.dm
> +	set desc = "See All (F) feature in chat"
```suggestion
	set desc = "Toggle the visibility of the follow button for NPC messages and emotes."
```

2022-11-30 16:03 UTC, PowerfulBacon commented on code/modules/client/preferences_toggles.dm
> +	SSblackbox.record_feedback("nested tally", "preferences_verb", 1, list("Toggle Ghost (F) Chat", "[prefs.chat_toggles & CHAT_GHOSTFOLLOWMINDLESS ? "Enabled" : "Disabled"]"))
```suggestion
	SSblackbox.record_feedback("nested tally", "preferences_verb", 1, list("Toggle NPC GhostFollow", "[prefs.chat_toggles & CHAT_GHOSTFOLLOWMINDLESS ? "Enabled" : "Disabled"]"))
```

2022-11-30 16:03 UTC, PowerfulBacon commented on code/modules/client/preferences_toggles.dm
> +	to_chat(usr, "As a ghost, you will now [(prefs.chat_toggles & CHAT_GHOSTFOLLOWMINDLESS) ? "see <span class='notice'>(F)</span> from all mobs" : "see <span class='notice'>(F)</span> from only mobs ha
```suggestion
	to_chat(usr, "As a ghost, you will [(prefs.chat_toggles & CHAT_GHOSTFOLLOWMINDLESS) ? "now" : "no longer"] see the follow button for NPC mobs.")
```

2022-11-30 22:35 UTC, ivanmixo commented
This is still super dumb... Why not make the pref just disable printing of emotes from mindless mobs for ghosts instead of it just removing 3 characters and directly downgrading the line being output? (if you don't want to be able to follow them then why see it at all?)

2022-12-04 11:36 UTC, EvilDragonfiend commented
> This is still super dumb... Why not make the pref just disable printing of emotes from mindless mobs for ghosts instead of it just removing 3 characters and directly downgrading the line being output? (if you don't want to be able to follow them then why see it at all?)

because the main point of this PR is to solve some clicking issues, not seeing emotes from random mobs.

2022-12-04 19:48 UTC, ivanmixo commented
Never seen a bigger non issue in my life

2023-01-20 08:24 UTC, PowerfulBacon approved these changes

2023-01-20 08:25 UTC, merged