Adjustements to the IV Drip, Anesthetic Tank Holder, Defibrillator Wall Mount and other wall-mounted items.
BeeStation/BeeStation-Hornet pull request #8111
Opened 2022-11-23 15:02 UTC by CydiaLamiales

## About The Pull Request
Adds deconstruction tips to the defibrillator wall mount, allows for said wall mount to be crowbarred off the wall, allows for deconstruction of the Anesthetic Tank Holder back into an IV drip, makes the defib wall mount, the IV drip and the Anesthetic Tank Holder drop their contents upon being smashed to pieces.

## Why It's Good For The Game
It's kind of inconsistent how you can make an IV drip into the tank holder but not the other way around, so this resolves that. Also allows people to 'normally' remove defib wall mounts of the wall instead of smashing them apart. Also more in-game accessibility through tips in the item descriptions is good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
New defib wall mount description:

![image](https://user-images.githubusercontent.com/110184118/203540957-d45c8d08-a70d-4d1b-a8e5-25f3fab8cc72.png)

Defib wall mount being pried off the wall:

https://user-images.githubusercontent.com/110184118/203541006-cdf233b1-102b-49e0-a6fe-b65e0d6b2b5d.mp4

Defib wall mount with an emagged defib inside being smashed apart, the defib dropping on the floor and keeping the emagged state:

https://user-images.githubusercontent.com/110184118/203541028-60099a82-0ec8-4f16-947a-d4f786b709c7.mp4

New Fire Extinguisher Cabinet tooltip while examining:

![image](https://user-images.githubusercontent.com/110184118/203541067-65d16820-35fa-4ee7-8b4a-61a2f30d2601.png)

IV Drip dropping its contents on the floor upon being destroyed:

https://user-images.githubusercontent.com/110184118/203541126-77fffe83-e7ac-43e2-b699-dc8f5a23903d.mp4

The Anaesthetic Tank Holder being de-converted into an IV Drip:

https://user-images.githubusercontent.com/110184118/203541177-f462e76d-b5ad-4190-87b7-994dbdf6bdc2.mp4

New Anaesthetic Tank Holder description that shows the attached tank and the volume/pressure inside of the tank :

![image](https://user-images.githubusercontent.com/110184118/203541101-c3323c84-f5e3-41d2-888e-7ea92c60c7dd.png)

Anaesthetic Tank Holder dropping its contents on the floor upon being destroyed:

https://user-images.githubusercontent.com/110184118/203541200-155a0b7a-ce8f-4813-a60f-e3c14b8a69e7.mp4

</details>

## Changelog
:cl:
add: Added deconstruction tooltops to the
add: Added more things
tweak: tweaked a few things
fix: Fixed the defibrillator not updating its icon upon being emagged
/:cl:

2022-11-23 17:10 UTC, Penwin0 commented
Good PR, kudos on the Testing portion.

I dislike the tool that needs to be used being named outright in examining, it is inconsistent with the rest of the game.

2022-11-23 17:16 UTC, Penwin0 commented
Yes, that sort of thing would be preferable

2022-11-23 17:28 UTC, EvilDragonfiend commented
how about the IV contents are thrown onto its tile when IV is broken? packs will be fine, but beakers will be spilled.

2022-11-23 17:30 UTC, CydiaLamiales commented
> how about the IV contents are thrown onto its tile when IV is broken? 
Oh I'm gonna need some help here, no idea how I'd do that.

2022-11-23 17:30 UTC, EvilDragonfiend commented
well, actually nevermind. might be out of the scope.

2022-11-23 17:36 UTC, CydiaLamiales commented
> I dislike the tool that needs to be used being named outright in examining, it is inconsistent with the rest of the game.

Okay, I've remoted that and updated the screenshots too.

2022-11-24 19:00 UTC, itsmeow approved these changes

2022-11-24 19:19 UTC, itsmeow requested changes

2022-11-24 19:19 UTC, itsmeow commented on code/game/machinery/defibrillator_mount.dm
> +				"[user.name] has pried [src] off the wall with [W].",\
this needs to use present tense. also is spanless

2022-11-24 19:19 UTC, itsmeow commented on code/game/machinery/defibrillator_mount.dm
> +		user.visible_message("[user.name] starts prying the [src] off the wall.", \
spanless

2022-11-28 17:18 UTC, itsmeow approved these changes

2022-11-28 17:18 UTC, merged