Makes nanites forced speech / skull echo not spammable + send skull echo message to ghosts
BeeStation/BeeStation-Hornet pull request #8112
Opened 2022-11-23 18:51 UTC by EvilDragonfiend

## About The Pull Request
did some nanites codes
* Force speech + skull echo is not spammable anymore. they share cooldown now.
* these are still allowed to have more than one program. This is because these are supposed to have multiple answer by given message, but it shouldn't say all things in a short time.
* Cloud number is recorded in investigation
* sends nanites message to ghosts so they can read it too
* add `check_if_time_passed` proc to manage time thing simply

## Why It's Good For The Game
about the pull request almost explained why we need this.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
![image](https://user-images.githubusercontent.com/87972842/203625197-d0bf5cab-6047-4ba7-a587-9bda7083b9c8.png)

you have 4 Nya programs, but only single Nay will be said.

![image](https://user-images.githubusercontent.com/87972842/203625268-d2218f87-6d6c-4a06-b545-ffa8c1c3c91d.png)

This is not spammable too, and ghosts can see message

</details>

## Changelog
:cl:
code: check_if_time_passed proc
tweak: Nanites programs 'force speech' and 'skull echo' now share its cooldown with other same programs.
add: ghosts now can read nanites skull echo messages.
/:cl:

2022-11-23 18:53 UTC, CydiaLamiales commented
Wait, does this mean no more ASCII art with nanites?
![image](https://user-images.githubusercontent.com/110184118/203625776-fd3a6dd2-2530-4041-9c5f-40176971d84f.png)

2022-11-23 18:55 UTC, EvilDragonfiend commented
> Wait, does this mean no more ASCII art with nanites? ![image](https://user-images.githubusercontent.com/110184118/203625831-67666e3a-de1f-4795-9fec-edf9f92a2c90.png)

yeah it doesn't make sense :trollface:

2022-11-24 18:57 UTC, itsmeow approved these changes

2022-11-24 19:18 UTC, itsmeow requested changes

2022-11-24 19:18 UTC, itsmeow commented on code/modules/research/nanites/nanite_programs/suppression.dm
> +	if(!check_if_time_passed(last_time_notified, 2 SECONDS))
Use cooldowns for this, they're the same thing but wrappered

2022-11-25 00:37 UTC, EvilDragonfiend commented
changed

2022-11-29 01:13 UTC, itsmeow approved these changes

2022-11-29 01:13 UTC, merged