Makes the Mjolnir even more legendary
BeeStation/BeeStation-Hornet pull request #8173
Opened 2022-12-05 21:32 UTC by PowerfulBacon

## About The Pull Request

Makes the Mjollnir more like its legends, the wielder of the Mjollnir gains immeasurable strength.

 - When dropped the Mjollnir will smash into the ground and anchor itself, being able to be picked up by non-wizards.
 - When thrown the Mjollnir will accelerate out of the wielders hands and towards targets. It will smash through windows and structures on the way. If it hits a wizard, the wizard will catch it, otherwise it will send the mob flying.

## Why It's Good For The Game

I've always thought the Mjollnir was lacking compared the legends, how comes non-wizards can pick this up? The Mjollnir is pretty cool in that they thought about anti-powergaming when they came up with the legend by making it so greytiders are unable to lift it.

## Testing Photographs and Procedure

![image](https://user-images.githubusercontent.com/26465327/205745973-1fca81d0-7589-401e-bb1f-d73e3ce271f3.png)

![image](https://user-images.githubusercontent.com/26465327/205746053-49ca4837-4285-408f-ab2e-a7bb320f750b.png)

![image](https://user-images.githubusercontent.com/26465327/205746074-ecf98276-9d80-47cb-afd7-bb4af4d75571.png)

![image](https://user-images.githubusercontent.com/26465327/205746095-3fdead11-4591-49a7-9acf-99cfc297bf01.png)

![image](https://user-images.githubusercontent.com/26465327/205746265-ea916869-0688-46f2-a12e-3554f7428edf.png)

![image](https://user-images.githubusercontent.com/26465327/205746623-a5eeace1-cec8-4520-9840-359bb6a95b7b.png)

## Changelog
:cl:
balance: Mjollnir can only be picked up by wizards.
balance: Mjollnir can be thrown with immeasurable strength.
/:cl:

2022-12-05 21:39 UTC, Tsar-Salat commented
amazing. Very nice work.

Could do with a resprite though, its looking a bit dated

2022-12-05 21:48 UTC, PowerfulBacon commented
I kinda wanna buff the singularity hammer too but I got no ideas

2022-12-05 22:04 UTC, Ivniinvi commented
inconsistent spelling - mjolnir vs mjollnir

2022-12-06 01:51 UTC, EvilDragonfiend commented
The real spelling Mjölnir is cooler

2022-12-06 05:45 UTC, Fronsis commented
Hmm, It might be me but the level of screen shake might be a little too much? Bah, i can imagine a fight being a little hard on the eyes, I imagine a Wiz constantly throwing-recalling vs a couple of security members and it would result in a very.. non pleasant spam of shake as if you were bombarded by mini-meteors(not to add that the wiz also has some other explosive spells that are too visual) In fact just grab+q+grab+q would already be an annoying spam(imagine the first five seconds of the video but spammed)

I get that you're trying to portray the might and legendary status of the hammer, the sound is already good i'm just not too fond of the shake.

Also i agree that the sprite certainly didn't age well

2022-12-14 06:55 UTC, itsmeow requested changes, later dismissed
rename all instances of mjollnir to mjolnir please

2023-02-25 19:10 UTC, PestoVerde322 approved these changes
Approved, will fix icon name post-merge.

2023-02-25 19:10 UTC, PestoVerde322 commented on code/game/objects/items/mjolnir.dm
> +	icon_state = "mjollnir0"
Fix the icon state's name here to avoid typos and whatnot.

Also other instances too.

2023-02-25 19:14 UTC, merged