Map config settings for planetary based maps
BeeStation/BeeStation-Hornet pull request #8178
Opened 2022-12-07 18:08 UTC by PowerfulBacon

## About The Pull Request

Adds in some new mapping config options:
 - planetary_station (Set to 1 to enable planetary maps): Will reskin the station on supercruise maps to have the planet rendering mode. Will also enable planettary meteors for the station
 - planet_name: Sets a prefix to the name of the station object on the maps. Only takes effect if planetary_station is enabled.
 - planet_mass: Sets the mass of the planet, if planettary station is enabled. (Lavaland has a mass of 10000 for reference. This affects the gravitational pull of the planet. This will most likely result in all supercruise objects going fucking crazy since they are setup with velocities to orbit around lavaland and not your planet)
 - planet_radius: Sets the radius of the supercruise map object for the station. Does nothing else.

Planetary meteors now work as the following:
 - They will spawn at the turf with the highest Z value on multi-z maps.
 - If they impact an openspace turf, they will fall down and then repeat the falling animation.
 - If they impact a normal turf, they will trigger 6-10 bumps and then do their effect if they got destroyed. Otherwise they will fall through the ceiling and travel to the turf below.
 - If they reach the bottom, they automatically blow up.

## Why It's Good For The Game

Allows mappers to create planetary maps.

## Testing Photographs and Procedure

![image](https://user-images.githubusercontent.com/26465327/206262033-b124edef-3b38-4f97-8d2c-dbee53c0df41.png)

![image](https://user-images.githubusercontent.com/26465327/206262081-0ef7bf6c-5347-436c-8687-f3d9e7d43f62.png)

![image](https://user-images.githubusercontent.com/26465327/206262219-9ad5f1d1-79a3-48e4-ada4-ceee3ab4a423.png)

## Changelog
:cl:
add: Adds in new config settings for mappers that allow for the creation of planetary based maps on the supercruise map. See PR #8178 for more details.
add: Planetary meteors will now spawn on the highest z-level and drop down until they hit the bottom or explode.
fix: Planetary meteors will no longer only spawn mini rocks
/:cl:

2022-12-07 18:27 UTC, itsmeow commented
Amazing, glow station success

2022-12-07 18:30 UTC, itsmeow requested changes

2022-12-07 18:30 UTC, itsmeow commented on code/datums/map_config.dm
> +	var/planettary_station = FALSE
Planetary, not planettary

2022-12-07 18:30 UTC, itsmeow commented on code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/space_station.dm
> +			name = "[SSmapping.config.planet_name] (Outpost 13)"
bad placeholder?

2022-12-07 18:40 UTC, PowerfulBacon commented on code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/space_station.dm
> +			name = "[SSmapping.config.planet_name] (Outpost 13)"
Better than space station 13

2022-12-07 19:36 UTC, kit-katz commented on code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/space_station.dm
> +			name = "[SSmapping.config.planet_name] (Outpost 13)"
lmao

2022-12-07 19:38 UTC, itsmeow commented on code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/space_station.dm
> +			name = "[SSmapping.config.planet_name] (Outpost 13)"
yeah but is the station name not defined at this point?

2022-12-07 21:53 UTC, PowerfulBacon commented on code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/space_station.dm
> +			name = "[SSmapping.config.planet_name] (Outpost 13)"
I think the orbital map always says SS13 until it gets renamed by the captain, it doesn't take the initial name of the station that is randomly generated

2022-12-07 22:51 UTC, EvilDragonfiend commented on code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/space_station.dm
> +			name = "[SSmapping.config.planet_name] (Outpost 13)"
it's good since it is really difficult to recognise station name when captains are giving crazy name to their station

2022-12-08 10:01 UTC, kit-katz commented
wait i just realized a question... HOW DOES THE METEOR SHIELD WORK

2022-12-08 10:20 UTC, PowerfulBacon commented
It doesn't

2022-12-18 22:55 UTC, itsmeow requested changes

2022-12-18 22:55 UTC, itsmeow commented on tgui/packages/tgui/components/OrbitalMapSvg.js
> +class planetaryBody extends RenderableObjectType {
Capital P 😔

2022-12-18 23:08 UTC, itsmeow approved these changes

2022-12-18 23:08 UTC, merged