Maint hoodies
BeeStation/BeeStation-Hornet pull request #8193
Opened 2022-12-09 22:41 UTC by PestoVerde322

## About The Pull Request

This PR adds hoodies in the game, in many colours and also, including a Durathread craftable variant

## Why It's Good For The Game

Done on bacon's request as extra drip is required.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

I.O.U a screen, i forgot to take one.

</details>

## Changelog
:cl:
add: Added hoodies, avviable via the beecoin shop, in-game vendors or crafting
add: Added Durathread hoodies, avviable only via crafting
/:cl:

2022-12-09 22:51 UTC, Fronsis commented
Another goated Pigeon W PR

2022-12-09 22:54 UTC, PowerfulBacon commented
![image](https://user-images.githubusercontent.com/26465327/206808508-985b11a5-3c0a-49ac-b06e-07e0ef193e8c.png)
Is the hood over the backpack while on the head?

2022-12-09 23:02 UTC, PestoVerde322 commented
> Is the hood over the backpack while on the head?

apparently so, will check

2022-12-09 23:56 UTC, PowerfulBacon approved these changes, later dismissed

2022-12-10 01:02 UTC, Tsar-Salat commented
This shit's nice. 

Maybe using wirecutters on it makes it sleeveless? That'd be sick for engie's showing off their gains.

Or possibly one's with departmental colors?

2022-12-10 03:18 UTC, itsmeow commented
could you move the pocket on the item sprite down one pixel? it looks like the fuckin among us helmet protrusion as it is

2022-12-10 06:21 UTC, Fronsis commented
> could you move the pocket on the item sprite down one pixel? it looks like the fuckin among us helmet protrusion as it is

among us and it's consequences on society + brainrot

2022-12-10 08:56 UTC, PestoVerde322 commented
> could you move the pocket on the item sprite down one pixel? it looks like the fuckin among us helmet protrusion as it is

now that you mentioned it, i won't change it.

2022-12-10 08:57 UTC, Tsar-Salat commented
im going to port these to tg and call them "among us" hoodies and see what happens

2022-12-11 02:39 UTC, Archanial requested changes

2022-12-11 02:39 UTC, Archanial commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	new/datum/stack_recipe("durathread hoodie",						/obj/item/clothing/suit/hooded/hoodie/durathread, 5, time = 50), \
use time defines

2022-12-11 02:39 UTC, Archanial commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +
```suggestion
```

2022-12-23 16:31 UTC, PestoVerde322 commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	new/datum/stack_recipe("durathread hoodie",						/obj/item/clothing/suit/hooded/hoodie/durathread, 5, time = 50), \
Fixed to all the files under stack.

2022-12-23 17:02 UTC, PowerfulBacon approved these changes
It arrived

2022-12-23 23:48 UTC, Archanial approved these changes

2023-01-01 11:06 UTC, merged