Adds clarity to the initial pirate payoff message
BeeStation/BeeStation-Hornet pull request #8213
Opened 2022-12-13 18:36 UTC by Harranhall

## About The Pull Request

A short IC addition to the pirate's initial ransom/payoff note.

## Why It's Good For The Game

It appears that the payoff coming from the cargo budget isn't common knowledge, even amongst command/AI players. This creates a situation where command/AI players that think they are choosing one thing, actually choose the opposite, since if you click "we'll pay" without the necessary funds in the cargo budget it actually just makes the pirate attack happen sooner.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![Screenshot 2022-12-13 181856](https://user-images.githubusercontent.com/39484008/207416583-45ae7744-24f8-4d67-8446-f00aca9067f3.png)

Thanks to Tyranicranger4 and LodedDiper for the assistance on the initial concept.
</details>

## Changelog
:cl:
tweak: added some text to the "Business proposition" message that appears on the communication console before pirates show up.
/:cl:

2022-12-13 18:49 UTC, Penwin0 approved these changes, later dismissed

2022-12-13 20:11 UTC, FriendlyContractor commented
Suggestion - gray out pay option if budget does not have sufficient funds.

2022-12-13 21:00 UTC, itsmeow requested changes

2022-12-13 21:00 UTC, itsmeow commented on code/modules/events/pirates.dm
> +	threat.content = "This is [ship_name]. Pay up [payoff] credits or you'll walk the plank. We'll pilfer it from yer cargo budget. don't try and cheat us, make sure it's all there!"
Capitalize `don't`

2022-12-13 22:09 UTC, Harranhall commented on code/modules/events/pirates.dm
> +	threat.content = "This is [ship_name]. Pay up [payoff] credits or you'll walk the plank. We'll pilfer it from yer cargo budget. don't try and cheat us, make sure it's all there!"
Ah, thanks!

2022-12-13 22:13 UTC, Harranhall commented on code/modules/events/pirates.dm
> +	threat.content = "This is [ship_name]. Pay up [payoff] credits or you'll walk the plank. We'll pilfer it from yer cargo budget. don't try and cheat us, make sure it's all there!"
Made this change, has it come through to the PR ok? Seems fine on my end.

2022-12-13 22:15 UTC, Harranhall commented
> Suggestion - gray out pay option if budget does not have sufficient funds.

A bit more work, but I'm game! I'll give it a try tomorrow evening after work. Are there any communications console messages with a similar mechanic that I can use as a guide?

2022-12-14 03:42 UTC, itsmeow commented
> Suggestion - gray out pay option if budget does not have sufficient funds.

I do not like this idea, part of the fun is not knowing what the budget is. If you hit We'll pay without knowing, suffer the consequences.

2022-12-14 07:07 UTC, silencer-pl commented
So I looked at this and "This is Space Privateer!" seems to not be proper English. How about the whole message is punched up, I spitballed and came up with:

"Arr, this be the Captain of [ship_name]. Yer land lubbers are on our space turf. Immediately transfer [payoff] space doubloons from your Cargo budget or we will make you walk the plank." (And yes "immediately transfer space dubloons" is a intended Futurama reference but it seems in line with all the goody scifi references ss13 makes)

Or at the very least I'd suggest changing the first part to make it seem like its the Captain of the ship that's sending the message, not the ship itself or alternatively add a "the" before [ship_name] though with some of the combos that still seems iffy (as in not everything is obviously a ship name)

2022-12-14 07:10 UTC, Harranhall commented
I like this! I'll write something up when I get home from work in approx. 10 hours.
________________________________
From: silencer-pl ***@***.***>
Sent: Wednesday, December 14, 2022 7:07:50 AM
To: BeeStation/BeeStation-Hornet ***@***.***>
Cc: Liver ***@***.***>; Author ***@***.***>
Subject: Re: [BeeStation/BeeStation-Hornet] Adds clarity to the initial pirate payoff message (PR #8213)


So I looked at this and "This is Space Privateer!" seems to not be proper English. How about the whole message is punched up, I spitballed and came up with:

"Arr, this be the Captain of [ship_name]. Yer land lubbers are on our space turf. Immediately transfer [payoff] space doubloons from your Cargo budget or we will make you walk the plank." (And yes "immediately transfer space dubloons" is a intended Futurama reference but it seems in line with all the goody scifi references ss13 makes)

Or at the very least I'd suggest changing the first part to make it seem like its the Captain of the ship that's sending the message, not the ship itself or alternatively add a "the" before [ship_name] though with some of the combos that still seems iffy (as in not everything is obviously a ship name)

—
Reply to this email directly, view it on GitHub<https://github.com/BeeStation/BeeStation-Hornet/pull/8213#issuecomment-1350513616>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJNHU2BXZVPEW6EDB3C6H2DWNFW4NANCNFSM6AAAAAAS5RIALY>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-12-14 11:40 UTC, Harranhall commented
> > Suggestion - gray out pay option if budget does not have sufficient funds.
> 
> I do not like this idea, part of the fun is not knowing what the budget is. If you hit We'll pay without knowing, suffer the consequences.

You know I think I like this more. It puts actual responsibility on the command staff.
I'll make some further wording changes drawing from what silencer suggested, and after that I'll let this PR pass or fail on it's current merits.

2022-12-14 18:09 UTC, Harranhall commented
Alright so after some looking, the list contains both ship names starting with "the" and ship names not starting with "the".
I've got around this by making the message preface it with "Our fine ship _ship name_", which flows well regardless.
I also made the ship name italicised and made the message feel a little bit more pirate-y, like Silencer suggested.
![image](https://user-images.githubusercontent.com/39484008/207673308-a2c8a10d-43c6-446a-b922-53fa4d36fb93.png)

2022-12-14 23:07 UTC, ike709 approved these changes

2022-12-15 01:33 UTC, itsmeow approved these changes
Great improvement!

2022-12-15 01:33 UTC, merged