Removes an unwanted description from chicken sandwiches
BeeStation/BeeStation-Hornet pull request #8222
Opened 2022-12-16 11:49 UTC by Tsar-Salat

## About The Pull Request
Renames the chicken sandwich to reference the dystopian future, instead of a political reference that makes players uncomfortable

## Why It's Good For The Game
I think we are past this

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Added new things
tweak: made chicken sandwiches more dystopian and less political
/:cl:

2022-12-16 11:50 UTC, Tsar-Salat commented
I thought i would reference the long history of the chicken sandwiches so-called "original creator" considering how many white haired men with a thick southern accent have claimed it

2022-12-16 12:52 UTC, Harranhall commented
What does poultry bread cage mean?

2022-12-16 12:53 UTC, Tsar-Salat commented
> What does poultry bread cage mean?

I asked beecord #general what the description for a chicken sandwhich was.

2022-12-16 12:59 UTC, Harranhall commented
Ah, thought it might be a pop culture reference. Will this description stand the test of time? I agree it needs to change (sheesh) but maybe something funnier? Spitballing here:
'Now with real "chicken"!'
'Factory farm to plate in no time!*'
This is a great chance to lean into the whole dystopian future thing we have going on, I agree!

________________________________
From: Tsar-Salat ***@***.***>
Sent: Friday, December 16, 2022 12:53:58 PM
To: BeeStation/BeeStation-Hornet ***@***.***>
Cc: Liver ***@***.***>; Comment ***@***.***>
Subject: Re: [BeeStation/BeeStation-Hornet] Removes an unwanted description from chicken sandwiches (PR #8222)


What does poultry bread cage mean?

I asked beecord #general what the description for a chicken sandwhich was.

—
Reply to this email directly, view it on GitHub<https://github.com/BeeStation/BeeStation-Hornet/pull/8222#issuecomment-1354724600>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJNHU2H3Q7BN463G3NETU5TWNRQ6NANCNFSM6AAAAAATA2KPZA>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-12-16 16:25 UTC, PowerfulBacon commented
Good change, but just remove the meme taste

2022-12-16 22:38 UTC, zeskorion commented
fuck chick fil a tho

2022-12-17 03:23 UTC, itsmeow approved these changes, later dismissed
1. do people in europe actually call this a chicken burger
2. Chik-Fil-A is so mid, let this be known, my primary goal as maintainer is to eliminate Chik-Fil-A from the codebase

2022-12-29 17:00 UTC, PowerfulBacon requested changes

2022-12-29 17:00 UTC, PowerfulBacon commented on code/modules/food_and_drinks/food/snacks_burgers.dm
> +	tastes = list("bun" = 2, "chicken" = 4, "A smiling white-haired man's deep accent" = 1)
```suggestion
	tastes = list("bun" = 2, "chicken" = 4)
```

2023-01-01 11:06 UTC, PowerfulBacon approved these changes

2023-01-01 11:06 UTC, merged