Ports TGUI for cryopod consoles
BeeStation/BeeStation-Hornet pull request #8262
Opened 2022-12-28 03:04 UTC by LemonLimeSoda

## About The Pull Request

Ports the TGUI interface for cryopod consoles from tgstation [#58025](https://github.com/tgstation/tgstation/pull/58025)

## Why It's Good For The Game

TGUI good; the cryopod console interface no longer looks ancient and using it is easier

## Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![image](https://user-images.githubusercontent.com/35978630/209750024-b9163715-2313-4564-98b1-98030e35c9e8.png)

</details>

The jobs for the final 3 show up as unassigned because they were spawned & given equipment - this should not be the case for any actual crew members, such as the captain on the top of the list. In addition, it displays the proper name of the user as long as they have an ID with an associated bank account - [REDACTED] is the fallback for those without a proper ID & account.

## Changelog
:cl:LemonLimeSoda, jlsnow301
add: The cryopod console now has a sleek tgui interface
/:cl:

2022-12-28 21:12 UTC, itsmeow requested changes

2022-12-28 21:12 UTC, itsmeow commented on code/game/machinery/cryopod.dm
> +			visible_message("<span class='notice'>[src] beeps happily as it disgorges [item].</span>")
"disgorges"
what the hell lmao
Change it to "release" and remove "happily", it's a machine, it can't happily release an item.

2022-12-28 21:12 UTC, itsmeow commented on code/game/machinery/cryopod.dm
> +/obj/machinery/computer/cryopod/ui_interact(mob/user, datum/tgui/ui)
I think this is the default behaviour of ui_interact on /obj/machinery? Check?
Just call ..(), then the ui open stuff

2022-12-28 21:12 UTC, itsmeow commented on code/game/machinery/cryopod.dm
> +		control_computer.frozen_crew += list(crew_member)
I don't think `list()` is necessary here, you can just add crew_member directly

2022-12-28 21:12 UTC, itsmeow commented on tgui/packages/tgui/interfaces/CryopodConsole.js
> +                      content="Drop"
"Drop" just seems like eh here, probably change it to "Release"

2022-12-29 12:56 UTC, EvilDragonfiend commented on code/game/machinery/cryopod.dm
> +		data["account_name"] = current_user.account_holder
```suggestion
		data["card_assignment"] = "Unregistered"
		if(id_card?.assignment)
				data["card_assignment"] = id_card.assignment
```
replace 72-75 to this. Using bank as your character information should be avoided.

2022-12-29 12:56 UTC, EvilDragonfiend commented on tgui/packages/tgui/interfaces/CryopodConsole.js
> +  const { account_name, allow_items } = data;
```suggestion
  const { card_assignment, allow_items } = data;
```

2022-12-29 12:56 UTC, EvilDragonfiend commented on tgui/packages/tgui/interfaces/CryopodConsole.js
> +  const welcomeTitle = `Hello, ${account_name || '[REDACTED]'}!`;
```suggestion
  const welcomeTitle = `Hello, ${card_assignment || '[REDACTED]'}!`;
```

2022-12-29 13:05 UTC, EvilDragonfiend commented on code/game/machinery/cryopod.dm
> +		data["account_name"] = current_user.account_holder
```suggestion
	data["user_name"] = "\[REDACTED\]"
	if(issilicon(user))
		data["user_name"] = user.name
	else if(isliving(user))
		id_card = user.get_idcard()
		if(id_card)
			data["user_name"] = id_card.registered_name
```
change 67-75 to this. using bank account as main should be avoided in general.

2022-12-29 13:05 UTC, EvilDragonfiend commented on tgui/packages/tgui/interfaces/CryopodConsole.js
> +  const { account_name, allow_items } = data;
```suggestion
  const { user_name, allow_items } = data;
```

2022-12-29 13:05 UTC, EvilDragonfiend commented on tgui/packages/tgui/interfaces/CryopodConsole.js
> +  const welcomeTitle = `Hello, ${account_name || '[REDACTED]'}!`;
```suggestion
  const welcomeTitle = `Hello, ${user_name}!`;
```

2023-01-14 23:59 UTC, ike709 commented
Stale?

2023-01-15 18:19 UTC, LemonLimeSoda commented
> Stale?

I've just been very busy the past few weeks - I have time today and will resolve what I can. Apologies.

2023-01-21 00:19 UTC, closed without merging