Belt for botanists.
BeeStation/BeeStation-Hornet pull request #8265
Opened 2022-12-30 23:50 UTC by CydiaLamiales

## About The Pull Request
Adds a belt for botanists can can hold sprays, bottles, beakers, syringes, wrenches, hatchets, spades, cultivators, plant analyzers, botanist gloves, floral somatorays, seeds, lighters, rolling papers, cigs and plant gene disks.

## Why It's Good For The Game
Less inventory clutter for Botany players is nice.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/110184118/210118487-000447f2-e729-43b7-9f73-4a5f3a618a56.png)

![image](https://user-images.githubusercontent.com/110184118/210118488-864916fa-c621-4924-91b1-3c58b24f697f.png)

![image](https://user-images.githubusercontent.com/110184118/210118490-d1c1945b-8cbf-4b6b-8fad-e68bcc24ac54.png)

![image](https://user-images.githubusercontent.com/110184118/210118494-56622a83-c06c-465e-ad00-2940a4930a50.png)

![image](https://user-images.githubusercontent.com/110184118/210118500-1bd2d5f1-6662-4986-bac9-e0634855bcab.png)

![image](https://user-images.githubusercontent.com/110184118/210118504-4c73b7f2-6fd9-49b2-a899-7514d9b6b02d.png)

![image](https://user-images.githubusercontent.com/110184118/210118506-c73649bf-a4d8-4216-a35f-1891a9b63e6f.png)

![image](https://user-images.githubusercontent.com/110184118/210118508-37457bb8-429e-4507-bfac-1673bbc6bc8e.png)

Belt icons : 

![image](https://user-images.githubusercontent.com/110184118/210118567-1895bb44-40a7-4881-8e63-3f4b331ba7cd.png)

Belt with all icon overlays : 

![image](https://user-images.githubusercontent.com/110184118/210118628-8b30150e-c15a-473e-afea-352006f48af6.png)

</details>

## Changelog
:cl:
add: Added a new Botanical belt
add: Added the botanical belt to the Botany lockers and the Biogenerator
imageadd: Added icons for the Botanical belt
imageadd: Added belt icons for the Plant Analyzer, Pest Spray, Hatchet, Spade and Cultivator
/:cl:

2022-12-31 13:53 UTC, PestoVerde322 reviewed
Icon and code looks fine, do the belt need to be spawned on the maps or it has to be obtained?

2022-12-31 14:06 UTC, CydiaLamiales commented
> Icon and code looks fine, do the belt need to be spawned on the maps or it has to be obtained?

It's like the medibelt, it spawns in the department lockers. ~~smh didn't read the changelog~~

2022-12-31 14:08 UTC, PestoVerde322 approved these changes, later dismissed
After i got some eyedrops, it's good to go, the item spawn in the lockers.
Approved.

2023-01-15 08:39 UTC, Archanial requested changes

2023-01-15 08:39 UTC, Archanial commented on code/game/objects/items/storage/belt.dm
> +	STR.can_hold = typecacheof(list(
make this static

2023-01-15 09:07 UTC, Archanial approved these changes

2023-01-15 09:15 UTC, CydiaLamiales commented on code/game/objects/items/storage/belt.dm
> +	STR.can_hold = typecacheof(list(
Done

2023-01-15 09:16 UTC, merged