Adds more medibot skins
BeeStation/BeeStation-Hornet pull request #8304
Opened 2023-01-11 08:59 UTC by EvilDragonfiend

## About The Pull Request
* Adds more medibot skins

## Why It's Good For The Game
consistent appearance is good

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/87972842/211761895-2ec662f4-e439-4be1-84b6-ef62d5d600a4.png)

![image](https://user-images.githubusercontent.com/87972842/211761806-5ce32eec-11a0-42d8-8039-7a2ecdf03db4.png)

sorry for my spriting ability if these look bad, but it can be changed someday...

</details>

## Changelog
:cl:
tweak: medibots have more skins based on which first aid kit was used when it's made. These currently have no speicla ability by its shape which means these are just skins.
imageadd: more medibot skins (advanced, rad, syndi, doctors roundstart kit)
/:cl:

2023-01-12 11:45 UTC, Penwin0 approved these changes, later dismissed
I like it, looks good

2023-01-12 11:45 UTC, Penwin0 commented on code/__DEFINES/bot_defines.dm
> +#define MEDBOT_SKIN_BRUTE "brute"
Add a comment

2023-01-12 15:14 UTC, EvilDragonfiend commented on code/__DEFINES/bot_defines.dm
> +#define MEDBOT_SKIN_BRUTE "brute"
added

2023-01-22 11:51 UTC, itsmeow requested changes
pretty epic

2023-01-22 11:51 UTC, itsmeow commented on code/game/objects/items/storage/firstaid.dm
> +			skin_type = MEDBOT_SKIN_BRUTE
add a field to all medkits, called medibot_skin or whatever instead

2023-01-23 07:18 UTC, EvilDragonfiend commented
changed

2023-01-25 20:01 UTC, itsmeow requested changes

2023-01-25 20:01 UTC, itsmeow commented on code/game/objects/items/storage/firstaid.dm
> +		to_chat(user, "<span class='warning'>[src] seems to be incompatible to make a medibot!</span>")
[src] cannot be used to make a medibot!

2023-01-30 13:17 UTC, itsmeow approved these changes

2023-01-30 13:17 UTC, merged