Geneticist is now med
BeeStation/BeeStation-Hornet pull request #8307
Opened 2023-01-11 19:39 UTC by Rukofamicom

## About The Pull Request

Adjusts the code behind the Geneticist to bring them in line with [url=https://wiki.beestation13.com/view/Department_Standard_Operating_Procedure:_Medical#Geneticist]Beestation SOP[/url], which means placing them solely under the medical department. 
* Removes the wide array of science access from them, as they don't need this to perform their job
* Changes their paycheck to come exclusively out of the medical budget
* Changes their blurb to only reference the Chief Medical Officer

## Why It's Good For The Game

Code mismatching server policies and staff expectations is bad. 
Giving a job that has such a high potential to attract shitters so much potential access kinda seems like a bad idea.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/9547572/211901648-70cab1c2-711f-4f8f-8ad5-10c16036189f.png)

![image](https://user-images.githubusercontent.com/9547572/211901680-9eae63e1-3ee6-4657-97db-36d25dfbc54e.png)

</details>

## Changelog
:cl:
fix: Geneticist flavor blurb now matches current Beestation SOP
tweak: Geneticist is no longer partially paid by Science and no longer has science departmental access
/:cl:

2023-01-11 19:45 UTC, Rukofamicom commented
> Might as well just completely remove the headset from the code tbh.

Yeah, tbh I probably should do that with this. I realized I missed the radio because of your forum comment 😆

2023-01-11 20:12 UTC, Poivre-Vert commented
Scientist, roboticist, and RD still have access to genetics on their cards, either during skeleton or normal crew.

2023-01-11 21:42 UTC, PowerfulBacon commented
They are medical research

2023-01-11 22:35 UTC, Rukofamicom commented
> They are medical research

So is Viro. 
Botany is Plant research
Engineering can generate research points
Mining can rapidly generate discovery points

2023-01-12 02:19 UTC, EvilDragonfiend requested changes

2023-01-12 02:19 UTC, EvilDragonfiend commented on code/modules/jobs/job_types/geneticist.dm
> +		ACCOUNT_MED_ID = PAYCHECK_MEDIUM //Geneticist is under only medbay here
redundant comment. just remove it.

2023-01-12 02:19 UTC, EvilDragonfiend commented on code/game/objects/items/devices/radio/headset.dm
> +
please remove 2 empty lines.

2023-01-12 02:20 UTC, EvilDragonfiend commented
code is fine, but not sure the idea.

2023-01-12 05:28 UTC, EvilDragonfiend commented
Note that this code doesn't change RD's access for the genetics.

2023-01-12 07:35 UTC, PowerfulBacon commented
I mean it's fine if guess since all maps have genetics in medical now anyway, from an SOP stand point this is one of the ones where is it wasn't for that we might as well change the SOP to make sense.
Since they don't actually practically answer to the RD then it's fine, something like brig phys is a role that should answer to both since they are practically responding to both.

2023-01-12 08:06 UTC, CydiaLamiales commented
> Note that this code doesn't change RD's access for the genetics.

It did though?
![image](https://user-images.githubusercontent.com/110184118/212011873-ac30c170-93f7-4dbf-9654-4fbc83a22ffc.png)

2023-01-12 10:25 UTC, EvilDragonfiend commented
> > Note that this code doesn't change RD's access for the genetics.
> 
> It did though? ![image](https://user-images.githubusercontent.com/110184118/212011873-ac30c170-93f7-4dbf-9654-4fbc83a22ffc.png)

in their access management.

2023-01-12 15:29 UTC, Rukofamicom commented
> Since they don't actually practically answer to the RD then it's fine, something like brig phys is a role that should answer to both since they are practically responding to both.

I can't deny that, and yet they are told via rules and in-game text both that they solely answer to the CMO. There is rarely a case where *any* med staff refuses requests from pretty much anyone regardless of rank on the station though.

> in their access management.

Whoops, I'll get to looking into that.

2023-01-12 15:50 UTC, Rukofamicom commented
![image](https://user-images.githubusercontent.com/9547572/212114364-734fa482-9961-4f97-b031-d54c9e5a0919.png)

2023-01-22 10:17 UTC, itsmeow approved these changes
Effectively geneticist is a medical role with a ton of extra access, which is kinda meh because they do not need the access for any reason whatsoever.

2023-01-30 13:26 UTC, merged