Adds IPC only surgery - clone damage fix
BeeStation/BeeStation-Hornet pull request #8309
Opened 2023-01-13 05:36 UTC by EvilDragonfiend

## About The Pull Request
* Adds IPC only surgery that fixes clone damage "repair prosthesis anomaly damage"

## Why It's Good For The Game
it is supposed to not happen generally, but zams sinful virology doomed their fate

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/87972842/212245047-37d96b20-1fd3-46bf-8ff9-4fe6f0bc1952.png)

![image](https://user-images.githubusercontent.com/87972842/212245060-991c6a09-2ab0-4278-b12e-24609412e014.png)

after trying this, I was able to fully fix IPC's clone damage

</details>

## Changelog
:cl:
add: IPC only new surgery "repair prosthesis anomaly damage" - can fix their clone damage
/:cl:

2023-01-13 06:44 UTC, bluezorua commented
probably shouldn't need to use biological surgery tools (hemostat) to repair IPCs

2023-01-13 06:57 UTC, EvilDragonfiend commented
> probably shouldn't need to use biological surgery tools (hemostat) to repair IPCs

sadly the real IPC surgery isn't that maintained, and hemostat is 'to pull out' something but I don't know which mechanic tool can be replaceable for it.

2023-01-13 10:11 UTC, lowwy commented
> sadly the real IPC surgery isn't that maintained, and hemostat is 'to pull out' something but I don't know which mechanic tool can be replaceable for it.

Maybe an empty hand? I think one of the other surgeries on IPC also uses an empty hand.

2023-01-13 10:44 UTC, EvilDragonfiend commented
> > sadly the real IPC surgery isn't that maintained, and hemostat is 'to pull out' something but I don't know which mechanic tool can be replaceable for it.
> 
> Maybe an empty hand? I think one of the other surgeries on IPC also uses an empty hand.

since surgery steps are a bit shitcode, it requires more refactoring if it should need hands.

2023-01-13 14:01 UTC, Penwin0 commented
> It is supposed to not happen generally, but zams sinful virology doomed their fate

I'd rather that instead of adding a very specific surgery not really for a snowflake type of damage they aren't supposed to take in the first place that whatever viro symptom causes this to stop doing so on IPCs

2023-01-13 20:08 UTC, Tsar-Salat commented
> but I don't know which mechanic tool can be replaceable for it

Crowbar. You leverage stuff out with it. (Tiles, glass screens on consoles, etc.)

2023-01-18 13:47 UTC, EvilDragonfiend commented
> I'd rather that instead of adding a very specific surgery not really for a snowflake type of damage they aren't supposed to take in the first place that whatever viro symptom causes this to stop doing so on IPCs

well, maybe it might be enough reason to close this PR since they shouldn't play such weird behavior...

but for me, IPC as cell damage is interpreted as 'atom integrity & stability damage'. so I believe IPC having this damage isn't really 'not makes sense'

2023-01-25 05:49 UTC, EvilDragonfiend commented
okay, what if IPC takes 3x brute damage from cell damage? 1 cell damage will be replaced as 3 brute damage to IPC.

2023-02-08 15:59 UTC, PowerfulBacon requested changes
Should we fix IPCs getting clone damage in the first place?

2023-02-08 15:59 UTC, PowerfulBacon commented on code/modules/surgery/ipc_surgery.dm
> +	name = "repair prosthesis anomaly damage"
Capitalise this like the other surgeries

2023-02-08 15:59 UTC, PowerfulBacon commented on code/modules/surgery/ipc_surgery.dm
> +		/datum/surgery_step/mechanic_close // 15
This is an insane amount of steps

2023-02-08 15:59 UTC, PowerfulBacon commented on code/modules/surgery/ipc_surgery.dm
> +		"[user] begins to adjust small bolts in [target]'s [parse_zone(target_zone)].")
Should these have spans?

2023-02-08 15:59 UTC, PowerfulBacon commented on code/modules/surgery/ipc_surgery.dm
> +		"[user] begins to carefully calibrate functional bolts in [target]'s [parse_zone(target_zone)].")
Here too

2023-02-08 15:59 UTC, PowerfulBacon commented on code/modules/surgery/mechanic_steps.dm
> +	tool.amount -= 10
This should use use() rather than subtracting amount, so you don't result with 0 amount stacks

2023-02-09 04:58 UTC, EvilDragonfiend commented
> Should we fix IPCs getting clone damage in the first place?

Yeah, that's questionable since only it's virology fuckery. So, I am thinking of dealing 3x brute damage conversion per clone damage in case they take.

2023-03-27 00:19 UTC, closed without merging