Better debug items and debug outfit
BeeStation/BeeStation-Hornet pull request #8315
Opened 2023-01-14 11:42 UTC by EvilDragonfiend

## About The Pull Request
* Makes more debug items
* Makes debug outfit more better
* plasmaman 'debug' no longer suffers from oxygen tank

## Why It's Good For The Game
more debugging tools are good

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/87972842/212470055-61e9e4e2-342e-4458-8edf-9d1726aafc27.png)

no more raw materials. these are better in a box.

---------

![image](https://user-images.githubusercontent.com/87972842/212470067-96f10200-7ef5-4a7d-9d5f-112a05d61aec.png)

`orb of power` debug item. it makes you survive from hazard situations

--------

![image](https://user-images.githubusercontent.com/87972842/212470092-2550a083-6cb1-4759-90cc-4c227ff5f78e.png)

debug hardsuit now has 300 protection, which can make you take no damage from excessive situations.

--------

![image](https://user-images.githubusercontent.com/87972842/212470119-74809ac0-e027-4505-b0d9-a14ff602d8f5.png)
![image](https://user-images.githubusercontent.com/87972842/212470121-9e348abe-e0df-4d39-a1ee-eee942b3679e.png)
![image](https://user-images.githubusercontent.com/87972842/212470127-aa78ea0e-30b5-40cc-9a61-d9595bfcd1f1.png)

ranged debug tools

-------

![image](https://user-images.githubusercontent.com/87972842/212470133-fe6f7399-7d39-406a-a478-733a1cc0fb85.png)

debug card budget now gets VIP budget instead of cargo

---------

![image](https://user-images.githubusercontent.com/87972842/212470139-e89740cd-1d69-4792-9058-f2a04c3678f6.png)

if you learned spells from a debug spell book, the spells you learned don't need robes

</details>

## Changelog
:cl:
code: fixed some RPD code
add: added more debug items
code: made debugging items better
code: changed some item paths from 'obj/.../admin' to 'obj/.../debug'
tweak: admin RCD is now ranged
/:cl:

2023-01-14 15:58 UTC, CydiaLamiales commented
Very nice stuff!

2023-01-23 08:49 UTC, Archanial requested changes

2023-01-23 08:49 UTC, Archanial commented on code/game/objects/items/RPD.dm
> +		))
put this together with declaration
it will be initialized once

2023-01-23 08:49 UTC, Archanial commented on code/game/objects/items/RPD.dm
> +	var/static/list/atmos_constructs = typecacheof(list(/obj/machinery/atmospherics, /obj/structure/transit_tube))
move this list to the obj declaration

2023-02-10 13:47 UTC, Archanial approved these changes

2023-02-10 13:47 UTC, merged