Fixed deconstructing railings not dropping iron rods
BeeStation/BeeStation-Hornet pull request #8325
Opened 2023-01-16 18:09 UTC by Tsar-Salat

## About The Pull Request
It was clearly set up to drop them, but it QDEL'd them instead of placing them properly.

## Why It's Good For The Game
Bugfix. No other wirecutter interaction doesnt give your rods back (catwalk, grille, etc.)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![unfastened](https://user-images.githubusercontent.com/62388554/212742550-7b4f7619-af0d-4840-a9d6-83b36d41337a.PNG)

</details>

## Changelog
:cl: RKz
fix: Railings now correctly drop their iron rod components when deconstructed
/:cl:

2023-01-17 01:23 UTC, itsmeow commented
This is fixed in #8044 as well

2023-01-18 08:01 UTC, Tsar-Salat commented
Thats from 2 months ago

2023-01-19 10:37 UTC, Penwin0 approved these changes
> This is fixed in #8044 as well

I don't see any reason not to merge this one, other is likely to take longer to get processed and the solution is identical.

2023-01-22 03:53 UTC, itsmeow requested changes, later dismissed
Would appreciate if all these changes were implemented
https://github.com/BeeStation/BeeStation-Hornet/pull/8044/files#diff-759cb0b0989788d7b72cfd7e261ea68c1ba50ed0a102579eb46b88b6d5f1a75d

2023-01-22 05:24 UTC, Tsar-Salat commented
> Would appreciate if all these changes were implemented https://github.com/BeeStation/BeeStation-Hornet/pull/8044/files#diff-759cb0b0989788d7b72cfd7e261ea68c1ba50ed0a102579eb46b88b6d5f1a75d

Why are you requesting changes on my pr?

This is meant to be a one item simple fix that doesnt get bogged down.

If you want your changes implemented, that is a conversation that needs to be had with other maintainers

2023-01-22 05:35 UTC, itsmeow commented
It's like 5 lines of changes to the same item for a fix that shouldn't have really been in my PR anyway. It's a favor I'm asking for.

2023-01-22 05:39 UTC, itsmeow commented
This is not me trying to evade my PR not being merged yet or forcing you to do things, it's simple request for organizational purposes implementing a necessary change into a PR doing almost the same thing. If you aren't inclined to, fine.

2023-01-23 03:22 UTC, merged