moves rcd content to its proper layer
BeeStation/BeeStation-Hornet pull request #8339
Opened 2023-01-20 13:22 UTC by dwasint

## About The Pull Request
previously i accidently overwrote the rcd buttons to the background layer instead of content this fixes that

## Why It's Good For The Game

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
/:cl:

2023-01-20 13:33 UTC, PowerfulBacon reviewed
Add testing evidence and changelog

2023-01-30 12:56 UTC, itsmeow commented
please

2023-02-01 00:38 UTC, itsmeow requested changes
all i want for christmas is a properly CL'd and tested PR that works

2023-03-03 01:50 UTC, itsmeow approved these changes
Finally...

2023-03-03 02:02 UTC, merged