Suit storage adjustments.
BeeStation/BeeStation-Hornet pull request #8400
Opened 2023-01-28 18:37 UTC by CydiaLamiales

## About The Pull Request
Makes the Suit Storage Unit circuitboards researchable, adds stock parts to the Suit Storage Unit. Makes the burn damage of the decontamination process scale with the tier of the micro laser. Also adds the ablity to crowbar open depowered suit storage units.

## Why It's Good For The Game
It's nice to have more roundstart machinery that's replicable, and that also that uses machine parts. Also getting your items out of a depowered suit storage unit is a pain since you need to smash it apart, which takes a long while. This PR remedies that.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Suit Storage Unit research : 

![image](https://user-images.githubusercontent.com/110184118/215284887-5508e0bc-8df0-46e7-8567-ca68d851450e.png)

![image](https://user-images.githubusercontent.com/110184118/215285036-5cb6b066-7440-4985-a0a4-8fde8f9acd53.png)

Prying open a depowered suit storage and prying its contents out :

https://user-images.githubusercontent.com/110184118/215284643-e438fb36-1d22-4bbf-84e4-5f6edabf4da8.mp4

Non-hacked decontamination damage with stock parts : 
![image](https://user-images.githubusercontent.com/110184118/215284383-4b55b26b-8492-44be-bfdb-75a1c60b18c7.png)

With t4 parts :
![image](https://user-images.githubusercontent.com/110184118/215284399-bf867631-cb8e-48ac-a7ad-bf712853950f.png)

Hacked/emagged decontamination damage with stock parts :

![image](https://user-images.githubusercontent.com/110184118/215284479-e9bce601-b360-4c33-8c53-d79f9fc971a8.png)

With t4 parts :

![image](https://user-images.githubusercontent.com/110184118/215284505-43bf9100-c9c5-4674-847c-f012291b2223.png)

</details>

## Changelog
:cl:
add: Added research for a Suit Storage Unit circuit board
add: Added the ability to build and deconstruct Suit Storage Units
add: Added machine parts to the Suit Storage Unit
add: Added the ability to crowbar open and pry the items out of a depowered Suit Storage Unit on harm intent
balance: Suit storage unit's decontamination damage is lower by default when unhacked
/:cl:

2023-01-28 22:59 UTC, Fronsis commented
Nice having them as a craftable is neat tbh!

Do higher-parts mean the rad decontamination % increases? Because as a CMO i've often used it on Engineers who don't want to stand on a shower and chug a beaker for 30 minutes when they have 6000 rads but if they come with 50k it can take a couple of decontamination tries.

Example for my question:
Dude comes with 10k rads

If i ask for my CMO decontainment unit to be upgraded, do the rad-decontamination value goes up?(for example let's say based is 2k and t4 is 4k thus it will take less decontaminaton uses to clear the rads out of them)

2023-01-29 10:47 UTC, CydiaLamiales commented
> Nice having them as a craftable is neat tbh!
> 
> Do higher-parts mean the rad decontamination % increases? Because as a CMO i've often used it on Engineers who don't want to stand on a shower and chug a beaker for 30 minutes when they have 6000 rads but if they come with 50k it can take a couple of decontamination tries.
> 
> Example for my question: Dude comes with 10k rads
> 
> If i ask for my CMO decontainment unit to be upgraded, do the rad-decontamination value goes up?(for example let's say based is 2k and t4 is 4k thus it will take less decontaminaton uses to clear the rads out of them)

That's odd, the decontamination should completely remove the radiation
![image](https://user-images.githubusercontent.com/110184118/215321062-d19a3662-758f-426a-9416-2081a81b1118.png)

2023-01-29 21:50 UTC, Fronsis commented
> That's odd, the decontamination should completely remove the radiation. ![image](https://user-images.githubusercontent.com/110184118/215321062-d19a3662-758f-426a-9416-2081a81b1118.png) Also rads get removed at the end of the procedure, not gradually. Hmm, I could maybe speed it up depending on the matter bin level?

Hmm the last time i tried it it was with a player who had probably between 30 or 60k rads and it only removed a couple of thousands of rads for each attempt and another player who was with me told me that it had a cap on how much it rad it took for each use, so we gave up since it was a lot of rads and the irradiated player already died, i guess it got bugged  (unless somehow i hacked it incorrectly?)

Alas if it works now then that's nice! The speed it up could be a good mini encouragment to look for the upgrades.

2023-01-29 22:36 UTC, CydiaLamiales commented
> > That's odd, the decontamination should completely remove the radiation. ![image](https://user-images.githubusercontent.com/110184118/215321062-d19a3662-758f-426a-9416-2081a81b1118.png) Also rads get removed at the end of the procedure, not gradually. Hmm, I could maybe speed it up depending on the matter bin level?
> 
> Hmm the last time i tried it it was with a player who had probably between 30 or 60k rads and it only removed a couple of thousands of rads for each attempt and another player who was with me told me that it had a cap on how much it rad it took for each use, so we gave up since it was a lot of rads and the irradiated player already died, i guess it got bugged (unless somehow i hacked it incorrectly?)
> 
> Alas if it works now then that's nice! The speed it up could be a good mini encouragment to look for the upgrades.

Oh, I know why. If the safeties get disabled and the strength gets increased while hacking then rads won't get removed. Don't know if it's intentional or not, but this PR makes it null the rads no matter what.

2023-02-05 21:07 UTC, itsmeow requested changes

2023-02-05 21:07 UTC, itsmeow commented on code/game/machinery/suit_storage_unit.dm
> +	var/laser_strength_hacked =  20
there's a space here that must go

2023-02-05 21:07 UTC, itsmeow commented on code/game/machinery/suit_storage_unit.dm
> +	return empty
no need for the var, just return the expression

2023-02-05 21:07 UTC, itsmeow commented on code/game/machinery/suit_storage_unit.dm
> +	if(uv_super || (obj_flags & EMAGGED))
you could use a ternary here `var/burn_damage = uv_super || (obj_flags & EMAGGED) ? laser_strength_hacked : laser_strength`

2023-02-05 21:07 UTC, itsmeow commented on code/game/machinery/suit_storage_unit.dm
> +				storage.take_damage(burn_damage * 10,BURN,"fire")
this should also probably remove the rads

2023-02-05 23:31 UTC, itsmeow approved these changes

2023-02-05 23:32 UTC, merged