Welding lock an airlock now is logged
BeeStation/BeeStation-Hornet pull request #8414
Opened 2023-01-31 07:50 UTC by EvilDragonfiend

## About The Pull Request
Welding lock an airlock now is logged

## Why It's Good For The Game
logging good

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/87972842/215698709-5c944558-4168-46ab-a9fc-c143bb5277b9.png)
![image](https://user-images.githubusercontent.com/87972842/215698732-a529790f-e22e-47d5-8ef9-86d4edf46785.png)
![image](https://user-images.githubusercontent.com/87972842/215698740-b134aaf5-33b5-4748-8549-8f41a6f62f98.png)

</details>

## Changelog
:cl:
admin: welding/unwelding an airlock will be logged
/:cl:

2023-01-31 08:23 UTC, PowerfulBacon reviewed
Is this actually logged to server files though?

2023-01-31 08:30 UTC, itsmeow requested changes

2023-01-31 08:30 UTC, itsmeow commented on code/game/machinery/doors/airlock.dm
> +				message_admins("[key_name_admin(user)] has [welded? "welded shut":"unwelded"] [src] which is located at [AREACOORD(src)].")
you do not need to message admins for this

2023-01-31 08:30 UTC, itsmeow commented on code/game/machinery/doors/airlock.dm
> +				investigate_log("[key_name(user)] has [welded? "welded shut":"unwelded"] [src] which is located at [AREACOORD(src)].", INVESTIGATE_AIRLOCKS)
this should be `user.log_game`

2023-01-31 08:56 UTC, EvilDragonfiend commented
> Is this actually logged to server files though?

I think it's not logged, but I will ask admins to make sure

2023-01-31 10:42 UTC, EvilDragonfiend commented
confirmed by Tyranicranger, it's not logged.
also, review addressed, and new test evidence attached

2023-02-01 14:56 UTC, itsmeow approved these changes

2023-02-01 14:57 UTC, merged