Easily replaceable power cells in machines (mainly dispensers related) + nanite console restriction
BeeStation/BeeStation-Hornet pull request #8418
Opened 2023-01-31 23:46 UTC by MatiAvanti

## About The Pull Request

Just what the title says, being able to replace power cell in a machine without actually breaking it. 

## Why It's Good For The Game
 It feels bad that you have to disassemble whole machine apart to replace a power cell. Power cell should be considered an easily replaceable part, its replacement should be less complicated.
This will lessen needs for tools for other departments such as botany/chemistry/bar and make their life's easier.
Power cells could be replaced by clicking on a machine with a battery in hand with  its maintenance hatch open.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/58709092/215908458-7b88b96b-652d-49e1-99b2-ebe1e1ed63cc.mp4

https://user-images.githubusercontent.com/58709092/215908777-21b6d966-b545-43c4-a085-7d0b2fc3d822.mp4

https://user-images.githubusercontent.com/58709092/215909336-823f490a-e183-4fc8-99b1-679170a3180f.mp4

</details>

## Changelog
:cl:
add: Added Nanite restricted acccess
add: Added Power Cell swapping.
del: Removed Nanite restricted acccess (one feature per PR they say)
/:cl:

2023-01-31 23:53 UTC, Tsar-Salat commented
can we restrict this until after #8372

2023-02-01 14:06 UTC, BriggsIDP commented
This is a really nice QOL change for maybe jobs. Thanks!

2023-02-01 18:26 UTC, MatiAvanti commented
I honestly suggest version without the need to use screwdriver. Power cells in my opinion should be replaceable without "specialized equipment" and it should be relatively simple to perform without professional knowledge.

2023-02-02 00:25 UTC, WrillWasTaken commented
> del: Removed Nanite restricted acccess (one feature per PR they say)

if this was part of your PR previously and not part of the game already then there's no need to mention it in the changelog.

2023-02-08 16:33 UTC, PowerfulBacon requested changes

2023-02-08 16:33 UTC, PowerfulBacon commented on code/game/machinery/_machinery.dm
> +		locate(/obj/item/circuitboard/machine) in component_parts
You are locating a circuitboard here and then doing nothing with it. Locate returns a value. What was the intent of this code?

2023-02-08 16:33 UTC, PowerfulBacon commented on code/game/machinery/_machinery.dm
> +					to_chat(user, "<span class='notice'>you replaced [capitalize(P.name)]  with [C.name] via power cell socket.</span>")
```suggestion
					to_chat(user, "<span class='notice'>You replace [P.name] with [C.name].</span>")
```
Should be in present tense, capitalisation is inconsistent and in the middle of the sentance, capitalisation is missed at the start of the sentence.

2023-02-08 16:33 UTC, PowerfulBacon commented on code/game/machinery/_machinery.dm
> +		..()
```suggestion
					return
	..()
```

2023-02-08 16:33 UTC, PowerfulBacon commented on code/game/machinery/_machinery.dm
> +		..()
Does attackby return?

2023-02-13 16:27 UTC, MatiAvanti commented on code/game/machinery/_machinery.dm
> +		locate(/obj/item/circuitboard/machine) in component_parts
My bad, thought locate also modifies component_parts. Checked again and feature is still working.

2023-02-25 14:21 UTC, PowerfulBacon approved these changes

2023-02-25 14:26 UTC, merged