Station traits are more chosen randomly
BeeStation/BeeStation-Hornet pull request #8424
Opened 2023-02-02 08:01 UTC by EvilDragonfiend

## About The Pull Request
Station traits are more chosen randomly
Positive station traits are always chosen first, and it blacklists the traits that'll come up later.
This means the traits that come up later will not be chosen, and it's not against the nature of randomness.

as a result of this, the chance of some neg station traits will appear slightly more than before,
while some neg traits that are not affected by this will have lower chance to appear than before.

## Why It's Good For The Game
more equalised randomness good.

## Testing Photographs and Procedure

<details>
It's hard to tell the difference as a screenshot.
local test has been done with no runtime error, and I checked it through `world.log << picked`

## Changelog
:cl:
tweak: Station traits are now chosen with more equalised randomness.
/:cl:

2023-02-02 12:12 UTC, Rukofamicom commented
This sounded great until I got to:

> intern announcer will appear slightly more than before

And now I want your PR to burn.

2023-02-05 20:59 UTC, itsmeow requested changes

2023-02-05 20:59 UTC, itsmeow commented on code/controllers/subsystem/processing/station.dm
> +		var/picked = pick(possible_types)
use `pick_n_take` insetead

2023-02-07 09:00 UTC, EvilDragonfiend commented
done

2023-02-08 14:53 UTC, PowerfulBacon approved these changes

2023-02-08 20:44 UTC, itsmeow approved these changes

2023-02-08 20:44 UTC, merged