Pinpointer refactor: z tracking, more indicator sprites, better crew monitor code
BeeStation/BeeStation-Hornet pull request #8433
Opened 2023-02-03 07:40 UTC by EvilDragonfiend

## About The Pull Request
Pinpointer refactor:
* z tracking
* more indicator sprites
* better crew monitor code

## Why It's Good For The Game
z-level should be trackable as long as it's considered to be the same z-group (i.e. multi-floored station)

## Testing Photographs and Procedure

<details>

![image](https://user-images.githubusercontent.com/87972842/216540565-43fb8287-4516-4f17-be49-faf49d35b885.png)

new sprites

</details>

https://youtu.be/R1a0odwESeo
https://youtu.be/K4QN94KI9UA
https://youtu.be/O9layFnUE78

can't test fugitive. I don't know how to do that

## Changelog
:cl:
tweak: simple/carbon mobs with monitoring nanites are now trackable by pinpointer (as long as they have mind...)
add: pinpointer is now trackable z-levels as long as those z-levels are in the same group (i.e. multi-floored station). Orange means target z-level is within the same group. Purple means target z-level is far far from their z-level (station - lavaland).
tweak: crew pinpointer is more vulnerable against jamming
imageadd: some pinpointer indicating sprites
refactor: 
/:cl:

2023-02-03 07:47 UTC, PowerfulBacon commented on code/controllers/subsystem/processing/orbits.dm
> +	return O.name
There should be documentation that confirms this is a virtual z-level.
This also needs handling for cases where O is null (return null?)

2023-02-03 07:47 UTC, PowerfulBacon commented on code/game/objects/items/pinpointer.dm
> +		if(SSorbits.get_orbital_map_name_from_z(here.get_virtual_z_level()) != SSorbits.get_orbital_map_name_from_z(there.get_virtual_z_level()))
If either is null, then they shouldn't be considered the same group

2023-02-03 08:35 UTC, EvilDragonfiend commented
Z-level tracking is a bit changed at this push
* If you are too far away, z-indictator will show only up/down arrows
* If you are in the same type z-levels, z-indicator will be orange bar

2023-02-04 20:39 UTC, itsmeow commented
If you are in a different zgroup, it should not show a directional arrow at all, and simply show something like "Z" or be examinable to show the orbital map location.
If you are in the same zgroup, it should show a bar of the same color as the arrow either above or below the arrow based on its relative position to you.

2023-02-04 20:40 UTC, itsmeow commented
Should also probably do some work on the Lifeline and nukie tracking program

2023-02-05 04:08 UTC, EvilDragonfiend commented
> If you are in a different zgroup, it should not show a directional arrow at all, and simply show something like "Z" or be examinable to show the orbital map location.

fair points

> If you are in the same zgroup, it should show a bar of the same color as the arrow either above or below the arrow based on its relative position to you.

`a bar of the same color as the arrow` is a bad idea because 
* the sprite window is very limited
* seeing 'the same colour' with the same colour of the arrow is cringe. You will not recognise, and that's why it's orange.
* z value difference will not be that greater since we don't really move too far between z levels

> Should also probably do some work on the Lifeline and nukie tracking program

I dunno how that works it's damn TGUI, but I will check and tell you if I can do

2023-02-10 03:11 UTC, EvilDragonfiend commented
can't focus on this right now. I will reopen this later or someone can take mine

2023-04-17 00:47 UTC, EvilDragonfiend commented
<details>

![image](https://user-images.githubusercontent.com/87972842/232353870-5184fd26-1a18-43ca-9b3e-1924f94057ea.png)
![image](https://user-images.githubusercontent.com/87972842/232353874-20ceb3af-51c4-4317-ac02-e5ae274c7597.png)
![image](https://user-images.githubusercontent.com/87972842/232353883-8cc761dc-a832-420b-af0a-207486b8ff63.png)
![image](https://user-images.githubusercontent.com/87972842/232353890-e1ff6175-3bb2-4b08-9221-2a553a3bbeb0.png)
![image](https://user-images.githubusercontent.com/87972842/232353897-83d68afb-610c-4b07-b0f6-549b4c9f48ba.png)
![image](https://user-images.githubusercontent.com/87972842/232353901-4bbe9f1a-95d6-45af-92f9-00c50918e852.png)
![image](https://user-images.githubusercontent.com/87972842/232353908-5fcb20fa-77cb-415b-9e7d-b6fabdbf506f.png)
![image](https://user-images.githubusercontent.com/87972842/232353925-c71ea2c9-1fde-443c-ae03-a380c2306562.png)
![image](https://user-images.githubusercontent.com/87972842/232353913-c0e40209-3b24-49b0-8e7a-b62b7518567a.png)
![image](https://user-images.githubusercontent.com/87972842/232353917-44cd79c8-ddac-431c-8497-f92dee3a6e57.png)
![image](https://user-images.githubusercontent.com/87972842/232353919-cc6f5e77-8e63-4841-a6a7-94547303380d.png)


</details>

2023-04-17 01:06 UTC, itsmeow requested changes

2023-04-17 01:06 UTC, itsmeow commented on code/game/objects/items/pinpointer.dm
> +/proc/compare_z(here_z, there_z)
there's a multiz __helpers file this could go in, it's the same one with `get_step_multiz`

2023-04-17 01:06 UTC, itsmeow commented on code/game/objects/items/pinpointer.dm
> +		. += "Pinpointer informs its target is [z_level_direction]."
```suggestion
		. += "A display reads that the target is [z_level_direction]."
```

2023-04-17 01:06 UTC, itsmeow commented on code/game/objects/items/pinpointer.dm
> +			z_level_direction = "located at a floor [pin_z_result] here"
```suggestion
			z_level_direction = "located [abs(there_zlevel - here_zlevel)] floors [pin_z_result]"
```

2023-04-17 01:06 UTC, itsmeow commented on code/modules/modular_computers/file_system/programs/radar.dm
> +	return locate(selected) in GLOB.suit_sensors_list //currently we dont have a list of humanoids so this'll have to do
```suggestion
	return locate(selected) in GLOB.suit_sensors_list
```

2023-04-17 01:08 UTC, EvilDragonfiend commented on code/game/objects/items/pinpointer.dm
> +/proc/compare_z(here_z, there_z)
I think it's a different function. compare_z returns `FALSE` when these are not in the same group.

2023-04-17 01:09 UTC, itsmeow commented
> can't test fugitive. I don't know how to do that

Force the fugitives event with Round -> Trigger Events, take the ghost role
Then ghost, run global Debug verb: Advanced Proccall `spawn_hunters`, hunters will spawn instantly

Then the shuttle will spawn, if you spawn the pinpointer it now points to the shuttle

2023-04-17 01:20 UTC, EvilDragonfiend commented
![image](https://user-images.githubusercontent.com/87972842/232356471-7ac4754c-6928-4c84-a5a5-2b2adb9ce5a0.png)

I don't know why but it seems glowstation has some issue... I can't test as this.

2023-04-17 01:32 UTC, Pirill commented
Big request maybe, but the one big issue I had with the pinpointer UI was a lack of search and an alphabetical list where applicable. Those would both make it a lot more attractive if it's possible.

2023-04-17 01:33 UTC, EvilDragonfiend commented
> Big request maybe, but the one big issue I had with the pinpointer UI was a lack of search and an alphabetical list where applicable. Those would both make it a lot more attractive if it's possible.

sorry I don't want to do this more than I made

2023-04-17 02:37 UTC, EvilDragonfiend commented
hunter pinpointer is good too

2023-04-29 07:48 UTC, PowerfulBacon commented
For multi-z different group tracking it should point in the direction of the orbital object like it did in beeship tbh rather than to some arbritrary location that has no meaning on that z-level

2023-04-29 07:49 UTC, EvilDragonfiend commented
> For multi-z different group tracking it should point in the direction of the orbital object like it did in beeship tbh rather than to some arbritrary location that has no meaning on that z-level

I don't think I know how to do that...

2023-04-29 07:50 UTC, PowerfulBacon approved these changes

2023-04-29 12:03 UTC, itsmeow approved these changes

2023-05-14 07:22 UTC, merged

2023-05-15 06:36 UTC, Rukofamicom commented
Why did this PR remove device.dmi?