Adds a cooldown to farting, plus a bonus for clowns
BeeStation/BeeStation-Hornet pull request #8453
Opened 2023-02-07 11:27 UTC by Rukofamicom

## About The Pull Request
* Adds a two minute cooldown to farting
* Attempting to fart again while this cooldown is active gives an appropriate error message
* Attempting to fart while this is on cooldown *with the clumsy trait* has a 20% chance to succeed at the cost of shitting out an organ. Honk.

## Why It's Good For The Game
Spamming fart is LRP behavior and doesn't generally belong on the server. 
Clowns deserve better than just a cooldown on their farts, however. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

As a clown
![image](https://user-images.githubusercontent.com/9547572/217232269-b1fd9d95-95c2-4cf2-b4d9-3750e57b30ce.png)
![image](https://user-images.githubusercontent.com/9547572/217232081-d6e43075-e2c1-4fd5-ba02-b339a3c149f1.png)
![image](https://user-images.githubusercontent.com/9547572/217232178-7d39b1fc-ece0-45f9-9170-bf0ff73f71de.png)

Meanwhile as a non-clown:
![image](https://user-images.githubusercontent.com/9547572/217232333-ce63294e-2cf9-4e31-b29e-b69c8330cae6.png)
![image](https://user-images.githubusercontent.com/9547572/217232359-0e59a078-e1a7-46fd-b43b-fc86b32dd38a.png)
</details>

## Changelog
:cl:
tweak: Farting now has a two minute cooldown for most players. Clowns have a potentially costly exception to this cooldown if they try hard enough. 
/:cl:

2023-02-07 11:39 UTC, CydiaLamiales commented
Make the crew lactose intolerant and reduce the cooldown if there's milk in your system (unless you're a skellie)

2023-02-07 11:40 UTC, EvilDragonfiend commented
you're just making a clown farts organs.

2023-02-07 12:28 UTC, Rukofamicom commented
Even clowns still can't really spam it because it's not a guaranteed proc. They'll (usually) have to try a few times with no success or sounds if they really want to shit organs out, and even that isn't something that can be spammed due to rapidly becoming lethal for the clown.

2023-02-07 13:00 UTC, EvilDragonfiend commented
> Even clowns still can't really spam it because it's not a guaranteed proc. 

spam farts to spew organs for clowns. I don't think it's a good idea.

2023-02-07 13:35 UTC, bluezorua commented
>clown walks up to me
>farts once
>stands there for 15 seconds 
>shits their brain out

2023-02-07 18:00 UTC, PestoVerde322 commented
Add a chance to fart a really small amount of plasma like in goon or it's no deal.

2023-02-07 20:06 UTC, zeskorion commented
the organ farts should have a very low chance, and clowns should be able to just strain out farts normally 20% of the time, but with juuuust a 1 in 50 or so chance of shitting their lungs out

2023-02-07 20:07 UTC, itsmeow commented
THIS IS THE BEST PR I HAVE EVER FUCKING SEEN

2023-02-07 20:08 UTC, itsmeow requested changes
Fucking hilarious, but there needs to be a prob(10) or something on the organ fart

2023-02-07 21:34 UTC, Sinestia commented
Is this really it? Is this how Beestation dies?

2023-02-07 21:39 UTC, PowerfulBacon requested changes
There is no way we are adding the ability to fart out organs

2023-02-07 23:32 UTC, itsmeow commented
bad take. organ farts are real, and may impact your family. be sure to call a doctor if you experience spontaneous organ farts

2023-02-08 05:42 UTC, Sinestia commented
BeeStation is a democracy (Crossed 834) so clearly the organ fart should be a vote.

2023-02-08 06:05 UTC, Tyranicranger4 commented
> spam farts to spew organs for clowns. I don't think it's a good idea.

I agree, it's not a good idea, *it's an amazing one*.

2023-02-08 06:54 UTC, itsmeow requested changes

2023-02-08 06:54 UTC, itsmeow commented on code/modules/mob/living/carbon/human/emote.dm
> +			if(prob(20) && HAS_TRAIT(fartee, TRAIT_CLUMSY))
prob(5) or no deal

2023-02-08 06:55 UTC, itsmeow requested changes

2023-02-08 06:55 UTC, itsmeow commented on code/modules/mob/living/carbon/human/emote.dm
> +				fartee.visible_message("[fartee] sprays a bloody mess out of their rear!", "<span class='notice'>You manage to strain out more than just a fart!</span>")
spanless

2023-02-08 06:58 UTC, Fronsis commented
> There is no way we are adding the ability to fart out organs

We have virologists that puke random organs with their gamer virus, clowns deserves the chance to give medbay stuff to do!!!!111one

2023-02-08 08:27 UTC, Rukofamicom commented on code/modules/mob/living/carbon/human/emote.dm
> +			if(prob(20) && HAS_TRAIT(fartee, TRAIT_CLUMSY))
:+1:

2023-02-08 08:35 UTC, Rukofamicom commented on code/modules/mob/living/carbon/human/emote.dm
> +				fartee.visible_message("[fartee] sprays a bloody mess out of their rear!", "<span class='notice'>You manage to strain out more than just a fart!</span>")
:+1:

2023-02-08 08:37 UTC, itsmeow approved these changes, later dismissed
Peak performance

2023-02-08 16:32 UTC, Rukofamicom commented
![image](https://user-images.githubusercontent.com/9547572/217591981-2de45fc8-1ca7-4237-948b-94f0285bdc57.png)

![image](https://user-images.githubusercontent.com/9547572/217591917-09ce43f6-a439-4da7-93ec-f4f5733624e1.png)

2023-02-08 16:42 UTC, PowerfulBacon approved these changes

2023-02-08 16:45 UTC, merged

2023-02-08 20:41 UTC, itsmeow commented
BOOOOO

2023-02-08 21:09 UTC, imsynthex commented
this is NOT what i voted for, i want my money back

2023-02-08 22:30 UTC, DatBoiTim commented
I feel robbed.

Let clowns fart their brains out!

2023-02-09 00:02 UTC, Rukofamicom commented
I just wanna make sure I don't get flogged for this one, so I'm gonna make sure nobody missed these:

![image](https://user-images.githubusercontent.com/9547572/217679538-1e429693-9199-47b9-a5c1-ddafa923705e.png)

![image](https://user-images.githubusercontent.com/9547572/217679506-c33cd074-2a1b-49f2-ac6c-ddca4bd0bbef.png)