Conveyor QOL
BeeStation/BeeStation-Hornet pull request #8460
Opened 2023-02-08 03:15 UTC by benbot16

## About The Pull Request

This adds multitool-based conveyor linking functionality to conveyors. It also lets you use a screwdriver to change conveyor switches from two-way to one-way mode for both directions.

## Why It's Good For The Game

This should hopefully make conveyor construction less tedious, especially if you forget to link your switch before-hand.
This also means you can make one-way switches in-game, instead of having them be mapping-only.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/9423435/217419616-b460c9e3-6f20-47f9-bf5f-e576d5a3fc5f.mp4

</details>

## Changelog
:cl:
add: Conveyors may now be linked to conveyor switches using a multitool.
add: Using a screwdriver on a conveyor switch will now toggle it between one-way and two-way mode.
/:cl:

2023-02-08 14:54 UTC, PowerfulBacon requested changes

2023-02-08 14:54 UTC, PowerfulBacon commented on code/modules/recycling/conveyor.dm
> +	to_chat(user, "<span class='notice'>You set the conveyor switch to [newdirtext] mode.")
```suggestion
	to_chat(user, "<span class='notice'>You set the conveyor switch to [newdirtext] mode.</span>")
```

2023-02-09 20:42 UTC, itsmeow approved these changes

2023-02-13 22:15 UTC, PowerfulBacon approved these changes

2023-02-13 22:16 UTC, merged