Basic Elevators
BeeStation/BeeStation-Hornet pull request #8478
Opened 2023-02-11 02:23 UTC by DrDuckedGoose

## About The Pull Request

Adds basic elevators for mappers to use on multi-z maps.

It's pretty neat, it's animated. The elevator, and it's contents, shrink and grow as it traverses levels.
It can crush people and throw them out of the way, pretty sick.
Creation is pretty easy too. You physically build it in the map file, you don't have to mess with spawners.

## Why It's Good For The Game

Adds an alternative to the god-awful current solution.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

My internet sucks right now, I couldn't get any video stuff.

![image](https://user-images.githubusercontent.com/40559528/218232393-fc35fd76-ccf9-444c-ad86-7b06cdca6a39.png)
![image](https://user-images.githubusercontent.com/40559528/218232412-518a7f0a-aac8-41ec-adc0-8e2d78b87cdd.png)
![image](https://user-images.githubusercontent.com/40559528/218232416-e9e76234-ec12-4327-930b-38ce1db3e1c8.png)
![image](https://user-images.githubusercontent.com/40559528/218233555-7f459696-1c33-4233-bf09-d91eb8d0defe.png)

</details>

- [ ] Make TGUI for elevator interface

## Changelog
:cl:
add: ``signals_elevator.dm`` - signals for elevators
add: ``elevator_controller.dm`` - SS for elevators
add: ``elevator_indicator.dm`` - Level indicator for elevators and z-levels
add: ``elevator_interface.dm`` - controller interface for elevators
add: ``elevator_segment.dm`` - Converts turfs and their decals into elevator structures
add: ``elevator.dmi`` - Pretty icons for elevator stuff
tweak: Replaces the elevator on multi-z debug with new presets
/:cl:

2023-02-11 02:24 UTC, DrDuckedGoose commented
I will remove the debug map from the map prefs when I mark it ready for review.

2023-02-11 05:24 UTC, EvilDragonfiend commented
If elevator comes to the bottom and there's a person, do they get gibbed?
Does the elevator have a ceiling?
If some tiling is placed above the elevator, will it block the elevator?

2023-02-11 05:46 UTC, DrDuckedGoose commented
> If elevator comes to the bottom and there's a person, do they get gibbed?
They recieve 15 brute and are thrown very far away.
> Does the elevator have a ceiling?
No.
> If some tiling is placed above the elevator, will it block the elevator?
Not at the moment, no. Should it?

2023-02-11 07:40 UTC, PowerfulBacon commented
What happened to the working elevators already in the codebase (turbolifts)?

2023-02-11 07:42 UTC, DrDuckedGoose commented
Not maintained. They don't spawn in properly or respond to prompts.

2023-02-21 02:25 UTC, Ivniinvi commented on config/maps.txt
> +	enabled
Debug map enabled
```suggestion
	disabled
```

2023-02-21 02:26 UTC, DrDuckedGoose commented
Whoops.
Thanks mate.

2023-03-07 21:33 UTC, itsmeow requested changes

2023-03-07 21:33 UTC, itsmeow commented on code/modules/elevator/elevator_controller.dm
> +	if((abs(destination_z - S.z) > 1 || destination_z > S.z))
all `.z` should be `.get_virtual_z_level()`

2023-03-07 21:33 UTC, itsmeow commented on code/modules/elevator/elevator_segment.dm
> +			playsound(i, 'sound/effects/splat.ogg', 50, TRUE)
use the squash component, it'll be funny

2023-03-07 21:33 UTC, itsmeow commented on code/modules/elevator/elevator_segment.dm
> +	animate(target, pixel_y = oy, time = calltime / 2 || 1 SECONDS, flags = ANIMATION_PARALLEL)
this is going to break the shit out of any scaled mobs or items, we should either accept that and continue or not do it for mobs

Most important for dwarfism/giant mobs

2023-03-07 21:46 UTC, itsmeow commented
![image](https://user-images.githubusercontent.com/10366817/223560287-6c3a5bf7-087d-4828-98c8-3e7bf83719c0.png)
pressing the call button should not also open the UI for the outside type, only the inside should have buttons

2023-03-07 21:46 UTC, itsmeow commented
![image](https://user-images.githubusercontent.com/10366817/223560427-5b5ac74e-f850-40f0-92dd-b915031fd0dd.png)
somehow this didn't break my "resize", and for that I applaud you

2023-03-07 21:47 UTC, itsmeow commented on code/modules/elevator/elevator_segment.dm
> +	animate(target, pixel_y = oy, time = calltime / 2 || 1 SECONDS, flags = ANIMATION_PARALLEL)
nevermind apparently

2023-03-07 21:49 UTC, itsmeow commented
There's no door on the shaft if the elevator is not on that floor... this seems bad
![image](https://user-images.githubusercontent.com/10366817/223561043-6e9116df-fe7e-4d6d-999f-dd1d78a75cca.png)

2023-03-07 23:01 UTC, itsmeow commented
https://user-images.githubusercontent.com/10366817/223573643-9a344394-8bfe-4984-abda-99319239e4e4.mp4

2023-03-08 00:02 UTC, itsmeow commented
Make it play `sound/effects/turbolift/elevatormusic.ogg` while it moves. Also it should shake the screen slightly when moving and have a rumble and an impact sound when it lands

2023-03-08 01:34 UTC, Tsar-Salat commented
> Make it play `sound/effects/turbolift/elevatormusic.ogg` while it moves. Also it should shake the screen slightly when moving and have a rumble and an impact sound when it lands

If doing this, I recommend getting rid of the door sounds and bolt noises, maybe use a resprited firelock instead?

Otherwise they will take away from the elevator effect you may be going for (Personally they just sound kinda janky here)

2023-03-09 00:29 UTC, itsmeow requested changes
Delete turbolift code and icons from the game

2023-03-09 08:13 UTC, DrDuckedGoose commented
Done-zo

2023-03-09 09:05 UTC, itsmeow commented
The music doesn't seem to trigger when moving from floor 3 to floor 1 on multiz debug

2023-03-09 09:10 UTC, itsmeow commented
If possible... It would be very cool if the music just played anytime you were *in* the elevator, since the transit time is pretty short and the tracks are pretty long

2023-03-09 10:40 UTC, itsmeow requested changes

2023-03-09 10:40 UTC, itsmeow commented on code/modules/elevator/elevator_segment.dm
> +	var/list/music_files = list('sound/effects/turbolift/elevatormusic.ogg', 'sound/effects/turbolift/elevator_loop.ogg')
one last thing, initializing typecaches and lists or empty lists outside of `Initialize` is bad for performance, you should move all list assignments and typecache inits to that. same applies to the other new code. subsystems I think are an exception case

2023-03-09 10:41 UTC, itsmeow commented
also mapping errors, appears there were two leftover turbolift things

2023-03-09 12:54 UTC, itsmeow commented
Initialize must call parent

2023-03-10 02:30 UTC, itsmeow commented
The second (new) ambiance is too loud

Also, if you can, pan the sound spatially so it sounds like it's coming from the right

2023-03-10 02:33 UTC, itsmeow requested changes

2023-03-10 02:33 UTC, itsmeow commented on code/modules/elevator/elevator_indicator.dm
> +	icon = 'icons/obj/elevator.dmi'
this needs a desc, and it should probably also list the text on it when examined

2023-03-10 02:33 UTC, itsmeow commented on code/modules/elevator/elevator_indicator.dm
> +	icon = 'icons/obj/elevator.dmi'
control panel also needs a desc

2023-03-10 05:05 UTC, DrDuckedGoose commented
Each music track now has it's own volume define. I don't think I can play the sound file in a specific ear, however.
I'm not aware of anyway to change the sound channel stuff like that.

2023-03-10 07:08 UTC, itsmeow commented
the `sound()` proc has args for x y and z, you just put x as like 5 and it plays as if it was 5 to your right

2023-03-10 07:09 UTC, itsmeow approved these changes
Yeah I like this a lot, it works well ingame from my testing.

2023-03-11 04:37 UTC, itsmeow commented
Needs new proc refs

2023-03-11 04:38 UTC, itsmeow commented
that was fast

2023-03-11 04:39 UTC, DrDuckedGoose commented
Did it in -2 minutes

2023-03-11 04:40 UTC, itsmeow approved these changes

2023-03-11 04:40 UTC, itsmeow approved these changes

2023-03-11 04:47 UTC, merged