Beecoin store jumpsuits change to jumpskirts based on active character preference.
BeeStation/BeeStation-Hornet pull request #8521
Opened 2023-02-18 18:32 UTC by CydiaLamiales

Makes the jumpsuits in the beecoin store change into jumpskirts depending on the active character uniform preference.
## About The Pull Request

## Why It's Good For The Game
More customization good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/110184118/219882429-c3ee25d0-b326-48b8-a4c5-e88cbab5eac6.mp4

Couldn't really get testing footage of spawning in with a skirt because I don't have a local database set up.

</details>

## Changelog
:cl:
add: Made the jumpsuits in the beecoin store change into jumpskirts depending on the active character preference
add: Added a unique description to jumpskirts
/:cl:

2023-02-22 10:53 UTC, imsynthex requested changes

2023-02-22 10:53 UTC, imsynthex commented on code/modules/client/loadout/loadout_uniform.dm
> +	skirt_display_name = "grey jumpskirt"
```suggestion
	skirt_display_name = "blue jumpskirt"
```

2023-02-22 11:03 UTC, CydiaLamiales commented on code/modules/client/loadout/loadout_uniform.dm
> +	skirt_display_name = "grey jumpskirt"
Huh, how did that even happen

2023-04-04 07:11 UTC, PowerfulBacon commented
Frozen due to @itsmeow 's preference rework

2023-04-04 07:16 UTC, itsmeow commented
No don't do that, it'll take loads of time and it's not much work to implement

2023-04-04 07:52 UTC, PowerfulBacon approved these changes

2023-04-04 07:58 UTC, merged