Minor buff to Chem Master, and saline glucose
BeeStation/BeeStation-Hornet pull request #8533
Opened 2023-02-20 03:22 UTC by EvilDragonfiend

## About The Pull Request
* Chem Master will now hold 200 units
* Saline glucose will metabolise 3x more units, and 3x produced when mixed

## Why It's Good For The Game
Since a lot of chems are nerfed, making some advanced chem is painful in this state.
We'll likely merge the sleeper PR, but adjusting chem ratio is difficult. I am going to make this easy to produce, so that chemists can put things into a chem they made for chemical deconcentration.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/87972842/220001615-a159bda6-a440-47e1-9b6d-618489c460ef.png)

</details>

## Changelog
:cl:
balance: ChemMaster now can hold 200 units
balance: Saline-glucose will be produced by x3 amount, and metabolised with x3 more units than before.
balance: Medbay vending machine will sell 20 bottles of saline-glucose from 4 bottles
/:cl:

2023-02-23 02:21 UTC, Isy232 commented
> Chem Master now holds 200 units

Oh, great, you have made it so chemists no longer have to upgrade their chem masters as much by having them start with large beakers instead of small beakers...

Oh.... oh no.... they just take 4 beakers to make now...

I'm not against it, but would it not be easier to keep the current 2 beaker chem masters but have the ones that spawn at roundstart include large beakers instead of small ones?

I dont know machine code well enough, if this is the best way then go ahead.

2023-02-23 23:53 UTC, EvilDragonfiend commented
> > Chem Master now holds 200 units
> 
> Oh, great, you have made it so chemists no longer have to upgrade their chem masters as much by having them start with large beakers instead of small beakers...
> 
> Oh.... oh no.... they just take 4 beakers to make now...
> 
> I'm not against it, but would it not be easier to keep the current 2 beaker chem masters but have the ones that spawn at roundstart include large beakers instead of small ones?
> 
> I dont know machine code well enough, if this is the best way then go ahead.

hmm, maybe I should just increase it by a fixated value regardless of beaker level. machine code for beakers are specifically bullshit.

2023-03-05 13:26 UTC, EvilDragonfiend commented
Okay, I changed it to 2 large beakers, and I checked it's working well locally.

2023-04-04 07:18 UTC, PowerfulBacon requested changes
Since you are saying this is a buff, I want to point out that this will make saline glucose 3x less effective, as it now metabolizes 3x faster but performs its effect at the exact same rate. This means that you need 90u of saline to do the same thing as 30u before. The title and body of the PR seem to portray this as a buff.

2023-04-04 07:19 UTC, PowerfulBacon requested changes
I don't get the point of making saline 3x bigger in everything

2023-04-04 07:19 UTC, PowerfulBacon commented on code/modules/reagents/chemistry/recipes/medicine.dm
> +	results = list(/datum/reagent/medicine/salglu_solution = 9)
This doesn't make any sense.

2023-04-07 04:45 UTC, EvilDragonfiend commented
the PR is now limited to chemmaster. The idea about saline seems to be done after some chem changes...

2023-05-14 07:17 UTC, PowerfulBacon approved these changes

2023-05-14 07:29 UTC, merged