fixes artifact holding using robo access on Fland
BeeStation/BeeStation-Hornet pull request #8538
Opened 2023-02-20 21:39 UTC by spockye

## About The Pull Request
Fland currently uses "29" on its artifact windoor, which is robotics access. It should be using "47"

## Why It's Good For The Game
Mapping errors = bad

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/79304582/220202159-82427b54-e13e-45c1-a5b8-cc3d627d25ec.png)

</details>

## Changelog
:cl:
fix: fixed wrong access_txt on the artifact containment windoor (FlandStation)
/:cl:

2023-02-20 23:42 UTC, ike709 approved these changes, later dismissed

2023-02-21 06:43 UTC, PestoVerde322 approved these changes
How the hell did i miss that, Approved.

2023-02-21 07:01 UTC, PestoVerde322 requested changes
Wait, remove this spare windoor under the light before merging

![immagine](https://user-images.githubusercontent.com/75247747/220271193-42e74140-d352-4556-b3c2-b94081c81a46.png)

2023-02-21 11:40 UTC, spockye commented
> Wait, remove this spare windoor under the light before merging
> 
> ![immagine](https://user-images.githubusercontent.com/75247747/220271193-42e74140-d352-4556-b3c2-b94081c81a46.png)

fixed

2023-02-21 19:04 UTC, PestoVerde322 approved these changes

2023-02-21 20:58 UTC, merged