[PORT] Updates the Smelter UI into a TGUI format
BeeStation/BeeStation-Hornet pull request #8601
Opened 2023-03-03 17:23 UTC by Bobbanz1

## About The Pull Request
Ports the following PR from downstream: 
* https://github.com/BeeStation/NSV13/pull/2326

Said PR literally just updates the Smelter UI into a TGUI version

## Why It's Good For The Game
No more constantly updating HTML Interface for the Smelter.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/59128051/222785911-520d9bf1-8384-4ec7-8abb-121459cceda8.mp4

![Screenshot 2023-03-03 181315](https://user-images.githubusercontent.com/59128051/222785859-9661bbb0-1041-4dfd-b956-026ccbcb7c27.png)

</details>

## Changelog
:cl:
refactor: Refactors the Smelter User Interface into a TGUI Version
/:cl:

2023-03-03 20:39 UTC, itsmeow requested changes

2023-03-03 20:39 UTC, itsmeow commented on tgui/packages/tgui/interfaces/Smelter.js
> +          onClick={() => onRelease(amount)} />
passing amount here does nothing

2023-03-03 20:53 UTC, Bobbanz1 commented on tgui/packages/tgui/interfaces/Smelter.js
> +          onClick={() => onRelease(amount)} />
Fixed

2023-03-03 21:20 UTC, itsmeow approved these changes

2023-03-06 20:48 UTC, itsmeow requested changes

2023-03-06 20:48 UTC, itsmeow commented on tgui/packages/tgui/interfaces/Smelter.js
> +    amount,
this state seems unused?

2023-03-07 07:48 UTC, Bobbanz1 commented on tgui/packages/tgui/interfaces/Smelter.js
> +    amount,
Done

2023-03-07 21:00 UTC, itsmeow approved these changes

2023-03-07 21:12 UTC, merged