Better crab-17 behavior and better code
BeeStation/BeeStation-Hornet pull request #8611
Opened 2023-03-04 07:17 UTC by EvilDragonfiend

## About The Pull Request
Better crab-17 behavior and better code
Crab-17 will teleport within its z-level instead of teleporting across z-levels (good at multi-z-level station)
and changed the code better

## Why It's Good For The Game
code cleaning

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/87972842/222881212-a522611f-b783-417d-be60-ff0810cf98d9.png)

</details>

## Changelog
:cl:
code: touched crab-17 code a little better. It'll be logged too.
balance: crab-17 will teleport within the same z-level of it.
/:cl:

2023-03-04 07:22 UTC, CydiaLamiales commented
Could you maybe make it self-destruct again? After 12 minutes maybe.

2023-03-04 09:05 UTC, EvilDragonfiend commented
> Could you maybe make it self-destruct again? After 12 minutes perhaps .

I changed it better at low pop
but also, I don't want to self-destruction just hoping it'll be gone naturally, so I took your opinion partly. It will deal damage to intself until it has 25 HP, and a player will be needed to finish it.

2023-03-04 09:09 UTC, EvilDragonfiend commented
also, the new commit is tested in my local too.

2023-03-07 20:57 UTC, itsmeow requested changes

2023-03-07 20:57 UTC, itsmeow commented on code/game/objects/items/crab17.dm
> +			if(targetturf.z == src.z)
use `get_virtual_z_level`

2023-03-08 07:26 UTC, EvilDragonfiend commented
addressed

2023-03-26 10:36 UTC, itsmeow requested changes

2023-03-26 10:36 UTC, itsmeow commented on code/game/objects/items/crab17.dm
> +			if(targetturf.z == src.get_virtual_z_level())
you need to do it for both zs

2023-03-27 08:10 UTC, EvilDragonfiend commented on code/game/objects/items/crab17.dm
> +			if(targetturf.z == src.get_virtual_z_level())
addressed

2023-04-09 11:44 UTC, itsmeow approved these changes

2023-04-09 11:50 UTC, merged