[WIP] Ports TGUI Crew manifest
BeeStation/BeeStation-Hornet pull request #8612
Opened 2023-03-04 09:12 UTC by Tsar-Salat

Ports: 
- https://github.com/tgstation/tgstation/pull/58275
- https://github.com/tgstation/tgstation/pull/58300

## About The Pull Request
It ports the TGUI crew manifest

## Why It's Good For The Game
Pretty

~~Holy shit save us from this decade old UI~~

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: RKz, celotajstg, Mothblocks
add: Adds TGUI crew manifest 
/:cl:

2023-03-04 09:34 UTC, Tsar-Salat commented
It is time.

2023-03-04 12:33 UTC, itsmeow commented
Something I would like: Job HUD icons like in the orbit menu (should be based on the content on manifest NOT their actual job)

2023-03-04 19:59 UTC, Tsar-Salat commented
> Job HUD icons like in the orbit menu

 Ehhh, those really only fit the orbit menu because the orbit menu is, by nature, unsorted. 

The crew manifest is already sorted and has symbols for seniority in this TGUI, not sure how we could add the HUD symbols to this without making it look kinda crowded

2023-03-06 16:37 UTC, Pirill commented
Does this also include the real time updates for it or do you have to close and reopen it every time you wanna check it?

2023-03-06 16:39 UTC, Tsar-Salat commented
> Does this also include the real time updates for it or do you have to close and reopen it every time you wanna check it?

Difficult to test that specifically. Signs point to yes so far.

2023-03-06 17:36 UTC, itsmeow commented
> as it is an IC thing technically compared to Orbits which is OOC.

Keep in mind job HUDs are already IC as they display on sechuds

I mean as a replacement for the seniority icons it would look nice, plus we already have the code for it in tgui so it's an easy add

2023-03-07 22:34 UTC, Tsar-Salat commented
> I mean as a replacement for the seniority icons it would look nice, plus we already have the code for it in tgui so it's an easy add

~~But I dont wanna replace them...~~

If you think it'll look good, I will write it up

2023-03-10 01:33 UTC, itsmeow commented
The job names should be right-aligned. They look weird because the individual sections do not share flex widths, and so the text looks like it's randomly floating around.

2023-03-26 10:40 UTC, itsmeow requested changes

2023-03-26 10:40 UTC, itsmeow commented on code/datums/datacore.dm
> +				if (rank == "Captain" || (department != "Command" && (rank in heads)))
This and "Quartermaster" need to use JOB_NAME defines

2023-03-26 10:40 UTC, itsmeow commented on code/modules/mob/dead/new_player/new_player.dm
> +
useless space addition

2023-03-26 10:40 UTC, itsmeow commented on tgui/packages/tgui/interfaces/CrewManifest.js
> +  'Chief Medical Officer',
I reaaalllly don't like this. It should use ui_static_data and pass it from DM as JOB_NAME defines or the command_positions global

2023-03-26 10:40 UTC, itsmeow commented on tgui/packages/tgui/interfaces/CrewManifest.js
> +                    {crewMember.rank === 'Captain' && (
I don't like that this is hardcoded for the captain at all - but since we lack JOB_KEY atm I'm gonna allow it

2023-04-23 22:48 UTC, closed without merging