Faster windoors
BeeStation/BeeStation-Hornet pull request #8620
Opened 2023-03-05 15:28 UTC by imsynthex

## About The Pull Request

Speeds windoors opening and closing up approx. 2x

## Why It's Good For The Game

Current windoors are obnoxiously slow when compared to regular doors, seeing as they're used a lot for applications that require you to walk through them (such as HoP and captain's offices on metastation, as seen on the video), it makes sense for them to be faster as to not get in the way as much

## Testing Photographs and Procedure

[Video of testing above](https://user-images.githubusercontent.com/81387903/222968942-ad35daa3-10ad-45e3-975a-46512e3201cb.mp4)

## Changelog
:cl:
tweak:windoors are now twice as fast
/:cl:

2023-03-05 15:30 UTC, PowerfulBacon requested changes, later dismissed
The animation needs fixing, in the video it opens half way before teleporting open

2023-03-05 15:43 UTC, imsynthex commented
> The animation needs fixing, in the video it opens half way before teleporting open

Changed the animation to be smoother and added a new video (this time with audio) to the PR body

2023-03-05 17:48 UTC, Tsar-Salat commented
Currently, windoors don't respect Jaws of Life, which doesnt make sense that it takes more effort to open a glass pane than a airlock with 1k ibs of pressure behind it.

Can you implement:
- https://github.com/tgstation/tgstation/pull/71733

If you think it would fit with your PR.

2023-03-05 21:21 UTC, imsynthex commented
> Currently, windoors don't respect Jaws of Life, which doesnt make sense that it takes more effort to open a glass pane than a airlock with 1k ibs of pressure behind it.
> 
> If you think it would fit with your PR.

For whatever reason porting it didn't work, not going to look into it, just made another implementation for the same thing

2023-03-06 01:14 UTC, Tsar-Salat commented
Very nice

2023-03-06 20:39 UTC, itsmeow requested changes

2023-03-06 20:39 UTC, itsmeow commented on code/game/machinery/doors/windowdoor.dm
> +	if(!(ismob(AM)))
unnecessary parenthesis around ismob

2023-03-06 20:39 UTC, itsmeow commented on code/game/machinery/doors/windowdoor.dm
> +	if(!(SSticker))
unnecessary parenthesis again. also SSticker can't be null lmao, delete this tomfoolery

2023-03-06 20:39 UTC, itsmeow commented on code/game/machinery/doors/windowdoor.dm
> +	if(!hasPower() || HAS_TRAIT(I, TRAIT_DOOR_PRYER))
Door prying for regular airlocks has a do_after that takes like 5 seconds, it should do the same

2023-03-07 00:04 UTC, itsmeow approved these changes

2023-03-07 21:06 UTC, merged