No MMI Test For You
BeeStation/BeeStation-Hornet pull request #8629
Opened 2023-03-06 19:46 UTC by DatBoiTim

## About The Pull Request
Gibs people who MMI Test Lings.

Its about sending a message. Ling players who abuse this should similarly be banned for banbaiting because this does notify admins and will likely result in a bwoink to the person with the MMI.

## Why It's Good For The Game
Code Oversight for metagaming bad

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![GibbedLMAO](https://user-images.githubusercontent.com/68963748/223214557-f5687aef-84ec-4784-b4a0-b2508c1b4896.png)
Rulebreakers will be gibbed. Laugh at them. When you're done laughing, ban them.

</details>

## Changelog
:cl: DatBoiTim
tweak: Added a Check to MMIs for ling testing. If you ling test someone you get gibbed.
/:cl:

2023-03-06 19:48 UTC, Tsar-Salat commented
Honestly, I was leaning towards dusting to round remove the cringe. 

This works too though

2023-03-06 19:55 UTC, DatBoiTim commented
> Honestly, I was leaning towards dusting to round remove the cringe.
> 
> This works too though

Doesn't send enough of a message IMO.

Dusting is great for permanently round removing someone yes, but seeing someone reduced to a pile of gore after a rulebreak really sends a message.

2023-03-07 01:58 UTC, mystery3525 commented on code/modules/mob/living/brain/MMI.dm
> +			message_admins("[key_name(user)] was gibbed for trying to ling test someone with an MMI")
```suggestion
			message_admins("[key_name(user)] tried to ling test someone with an MMI")
```

2023-03-07 01:58 UTC, mystery3525 commented on code/modules/mob/living/brain/MMI.dm
> +			message_admins("[key_name(user)] was gibbed for trying to ling test someone with an MMI")
I'm against using code to enforce policy, especially in this way, its a serious immersion-break when someone just explodes into a million if they put what they think is a brain into a machine; but you CAN totally add logging for stuff like this

2023-03-07 05:47 UTC, Rukofamicom commented on code/modules/mob/living/brain/MMI.dm
> +			message_admins("[key_name(user)] was gibbed for trying to ling test someone with an MMI")
I don't disagree that it shouldn't happen in such an immersion breaking way way, but code should always enforce policy when possible. 

The no-ling testing policy is absolute - there is never a time when it is allowed, so it is a perfect candidate for something that should just be outright prevented by code.

2023-03-07 06:30 UTC, Rukofamicom requested changes

2023-03-07 06:30 UTC, Rukofamicom commented on code/modules/mob/living/brain/MMI.dm
> +
```suggestion
		if(newbrain.decoy_override)
			user.visible_message("<span class='warning'>[newbrain] contorts violently, whipping a sharp skewer through [user]'s head!</span>", "<span class='warning'>[newbrain] contorts violently, whipping a sharp skewer through your head!</span>", "<span class='italics'>You hear organic matter ripping and tearing!</span>")
			to_chat(user, "<span class='userdanger'>Performing changeling tests with an MMI is not allowed on this server. Admins have been notified</span>")
			message_admins("[key_name(user)] was removed from the round for trying to place a changeling brain into an MMI")
			playsound(newbrain, 'sound/magic/demon_consume.ogg', 50, 1)
			if(iscarbon(user))
				var/mob/living/carbon/C = user
				var/obj/item/bodypart/affecting
				affecting = C.get_bodypart(BODY_ZONE_HEAD)
				C.adjustOrganLoss(ORGAN_SLOT_BRAIN, 200)
				affecting.receive_damage(150)
			else //Failsafe, but should never almost never trigger
				user.gib()
			user.ghostize(FALSE) //Player is removed from the round permanently, even if they receive medical care.
			return

```

![image](https://user-images.githubusercontent.com/9547572/223339267-718c1c8c-525f-49bc-88d3-b7ceec44f29d.png)

Here's a much more immersive way to accomplish the same goal.

2023-03-07 13:54 UTC, DatBoiTim commented on code/modules/mob/living/brain/MMI.dm
> +			message_admins("[key_name(user)] was gibbed for trying to ling test someone with an MMI")
I'm with Ruko on this as far as round removing people who do stuff like this. MMI testing is an exploit resulting from a code oversight. 

That's why it became a "admin issue". While there is no 100% fix without completely reworking lings, an exploit is something that can be addressed with both code and admin work.

I'll take his option, if it means we make progress on getting this merged.

2023-03-07 17:24 UTC, tontyGH commented
"Oh damn this dude's body is super fucked up lemme put his brain in an MMI so I can ask him what--"

2023-03-07 17:33 UTC, mystery3525 commented
Or changelings maliciously asking to be borged :trollface:

2023-03-07 17:39 UTC, Tsar-Salat commented
> Oh damn this dude's body is super fucked up lemme put his brain in an MMI so I can ask him what--"

A down and out ling has either:
1. Just been killed by sec and is getting dragged to incinerator
2. Doesn't know their basic ling powers
3. Is trying to abuse this feature 

There are not many instances where a ling would bother staying dead, and most doctors aren't gonna mmi you. They are gonna try to patch you up for 10 minutes in surgery then clone you.

2023-03-07 17:53 UTC, Rukofamicom commented
> to see if it is an actual issue worth addressing

It 100% is though @mystery3525, let me go over some points:
* Bee used to have actual ling tests in its code that got removed
* Other servers (TG for instance) freely allow players to utilized mmi testing
* We have more than one thread about ling testing on our own forums, one literally made this year trying to argue (in good faith!) that admins are dumb for acting like MMI testing is against the rules. 

It might be *very* clear to you as an administrator of this server that MMI testing is not permissible, but it is only apparent to players after they have been told. An automated system of telling them and actively discouraging it is the best way to accomplish this.

2023-03-07 19:14 UTC, tontyGH commented
Okay real input to this, tl;dr this is the worst band-aid fix I have ever seen in my life

Permanently killing someone for trying to put a fake brain in an MMI is not only an incredibly unimmersive and excessive punishment, all this does is punish people who don't know either don't know about the no testing rules (like ruko mentionned) or **don't know that the brain is from a ling at all**, which you hope they wouldn't as the changeling

All this does is tip off the surrounding (now annoyed from having their coworker RRed) staff that the brain is from a changeling, their cover is blown, and we're back to square one, this does nothing but fuck up one persons round

> Most doctors won't MMI a ling

Just because most don't do it doesn't mean that the people that do it should just suck up having their round being **permanently ended** just for trying it. It's not even the only context for someone to be MMI'd, there's also forced cyborgization for example

Are the ruined rounds of well-intentioned people worth it to catch the one guy who actually wanted to metagame?

And what is this punishment? This is lazy and uncreative, why not make the MMI itself explode? Or make it emit a screech to stun everyone and let the ling escape? Or **literally anything from this**

Go in and fix the MMI testing method itself if you want to stop MMI testing this is Not it

2023-03-07 19:16 UTC, tontyGH commented
But this is really funny so merge this

2023-03-07 20:54 UTC, Penwin0 commented
I don't like this PR, I feel like the cure is worse than the poison here, it's really inmersion breaking, I can easily see it being abused or being triggered on accident, doesn't even prevent ling tests at all, you just need one more person as a sacrifice now.

2023-03-07 21:52 UTC, LodedDiper69 commented
Doing ling tests to exploit the game code are more immersion breaking than this PR ever would be. I'm giving this the unofficial open key 🔑

2023-03-07 22:39 UTC, tontyGH commented
damn I got pissed wtf

2023-03-07 23:29 UTC, Fronsis commented
Yeah i think people missed the point this is a half-joke half-wake up call pr to give in  a big bold caps a message that says : " MMI TEST IS AGAINST THE RULES STOP" Though at this point i'd said the majority of our players on the sec/command area is aware

It's true that sometimes it feels like you need a method to get the "haha gotcha ling!!!"  But if the player(ling) played their cards correctly they shouldn't be outed by a single "easy" process

So i always have mixed feelings wether we need a system to help identify a changeling or not. It depends a lot on each shift tbh

2023-03-08 00:43 UTC, Rukofamicom commented
> maybe a message on #announcement would be enough to call it a day or add it to the relevant wiki.

The majority of not only our players, but all game players do not interact with the the community on the level dedicated players do

This would raise awareness but not on the same level as this PR. I don't think it's immersion breaking in the sense that the changeling can shapeshift and control its body in magical ways.

The forced round removal would affect people, at most, once in their playtime and serve to function as a powerful lesson that what they attempted is not allowed on this server.

2023-03-08 00:49 UTC, Rukofamicom commented
I can see the reasoning that this is too extreme, but it absolutely does need to be at least q huge red message for players attempting it at a minimum, even if it doesn't harm or round remove them.

It needs to be very clear to the person attempting that it is not allowed to do what they are attempting in that moment **WITHOUT** needing an admin present. This is not an issue that can wait for an admin to intervene.

If it breaks their immersion for legitimately attempting to do a long test - **BOO FUCKING HOO, THEY WERE ALREADY METAGAMING**.

2023-03-09 08:10 UTC, PowerfulBacon commented
I think this is far too verbose

2023-03-09 08:10 UTC, closed without merging

2023-03-09 08:47 UTC, itsmeow commented
yeah that's the right call here