[PORT] Remove code/__DEFINES/misc.dm
BeeStation/BeeStation-Hornet pull request #8633
Opened 2023-03-06 23:40 UTC by mystery3525

## About The Pull Request

Ports: https://github.com/tgstation/tgstation/pull/63879/

Yet another monster code re-structuring, this time defines!

> This removes code/__DEFINES/misc.dm and moves all the defines to either:
>
> - another existing define file
> - new define file
> - local .dm file if the define was only used in one file

> I also deleted defines that were not being used and added documentation to all of the ones that were moved out of misc.dm

I also moved code/__DEFINES/research/anomalies.dm out of it's snowflake folder that it had for no apparent reason

## Why It's Good For The Game

> Why was this needed? People were basically using the misc.dm file as a dumpster to toss all their defines into that was creating one giant mess. The defines have been organized into their proper groups and files now

This also follows our code standards much more better with more specific files.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

it compiles 🤯

</details>

## Changelog
:cl: timothymtorres ported by mystery3525
code: Move defines to their local .dm files
code: Remove code/__DEFINES/misc.dm
code: Moved code/__DEFINES/research/anomalies.dm
refactor: Adds some documentation to defines
/:cl:

2023-03-07 20:49 UTC, itsmeow commented on code/__DEFINES/mobs.dm
> +#define EGG_LAYING_MESSAGES list("lays an egg.","squats down and croons.","begins making a huge racket.","begins clucking raucously.")
this is the best thing ive seen all day, just wanted to share that

2023-03-07 20:51 UTC, itsmeow commented on code/modules/events/pirates.dm
> +#define PIRATE_RESPONSE_PAY "pirate_answer_pay"
I could've sworn I needed this in another file, ah well

2023-03-07 20:51 UTC, itsmeow approved these changes
incredibly based

literally moves code around and fixes some bad spelling

2023-03-07 20:52 UTC, itsmeow requested changes

2023-03-07 20:52 UTC, itsmeow commented on code/game/objects/items/stacks/stack.dm
> +#define STACK_CHECK_ADJACENT "adjacent"
these don't appear to be undefined

2023-03-08 04:10 UTC, itsmeow approved these changes

2023-03-08 05:19 UTC, mystery3525 commented
bruh rerun the tests?

2023-03-08 05:40 UTC, merged