Default to human for active character slot when there is no database
BeeStation/BeeStation-Hornet pull request #8653
Opened 2023-03-09 11:36 UTC by itsmeow

## About The Pull Request

Closes #7863

Characters default to human when no database is attached.

## Why It's Good For The Game

Spawning as a plasmaman in debug is super annoying if you're the type to not bother setting up a database. This change only affects development.

## Testing Photographs and Procedure

Tested by starting the game 5 times without a database. Each time, the first character slot was human. The rest were random.

## Changelog
:cl:
add: Added fallback species config option, for use when there is no database attached.
/:cl:

2023-03-09 15:25 UTC, Crossedfall approved these changes

2023-03-09 16:23 UTC, PowerfulBacon commented
My hero

2023-03-10 06:22 UTC, Crossedfall requested changes
Actually, I'd still kind of like a way have fully random characters as an option.

2023-03-10 06:25 UTC, itsmeow commented
All characters are still fully random *if there is a database*.

And it also only affects the first slot, on first init.

This is only for if there is no database.

Considering that running a production form of the server without a database would be an impossible nightmare, I consider this a non-issue.

2023-03-10 06:28 UTC, itsmeow commented
I've done it anyway, there

2023-03-10 06:32 UTC, Crossedfall approved these changes

2023-03-10 06:45 UTC, merged

2023-03-10 10:06 UTC, Tsar-Salat commented
> Characters default to human when no database is attached.

There goes my hero.

Watch him as he goes