Optimizes solar panel code
BeeStation/BeeStation-Hornet pull request #8658
Opened 2023-03-09 17:30 UTC by Chirynnn

## About The Pull Request
Directly ports https://github.com/tgstation/tgstation/pull/48110, from the Things to Port list.

## Why It's Good For The Game
Better code go brrr (I think the animations got lost in the process, but as cool as they were, I think optimisation is the main focus here)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/77589317/224107846-b0553224-7645-491e-b415-45f5c81f9892.mp4

</details>

## Changelog
:cl:

code: Reworked some of the solar panel code into a better variant
/:cl:

2023-03-10 01:23 UTC, itsmeow commented
The video doesn't render at all

2023-03-10 01:27 UTC, itsmeow commented
This is also not an optimization. It's more a collection of code modernizations. It's actaully probably a bit less performant now since it uses vis_contents objects

2023-03-10 10:17 UTC, Chirynnn commented
I'm pretty sure the PR mentioned it being more performant, but meh.. I'll get a new video soon, encoding it in h265 was probably a bad idea

2023-03-10 19:06 UTC, Chirynnn commented
Updated the video

2023-04-04 07:30 UTC, PowerfulBacon requested changes

2023-04-04 07:30 UTC, PowerfulBacon commented on code/modules/power/solar.dm
> +	vis_contents += panel
Lets not use vis contents if we can.
A better solution would be to use an overlay with a rotation applied in update_icon() and then calling update_icon() to update that overlay when it moves.
Or alternatively, just having the solar panel as an object on top of this object.

2023-04-04 07:30 UTC, PowerfulBacon commented on code/modules/power/solar.dm
>  /obj/machinery/power/solar/Destroy()
Destroy the panel in here

2023-04-04 07:30 UTC, PowerfulBacon commented on code/modules/power/solar.dm
> +#if DM_VERSION <= 512
You already have the better code for solar panels implemented, just remove the >= 513 stuff, since mutable appearances are better than vis contents.

2023-04-04 07:30 UTC, PowerfulBacon commented on code/modules/power/solar.dm
> +	needs_to_update_solar_exposure = TRUE //updating right away would be wasteful if we're also turning later
```suggestion
/obj/machinery/power/solar/proc/queue_update_solar_exposure()
	SIGNAL_HANDLER
	needs_to_update_solar_exposure = TRUE //updating right away would be wasteful if we're also turning later
```

2023-04-04 07:30 UTC, PowerfulBacon commented on code/modules/power/tracker.dm
> +	setDir(angle2dir(azimuth))
```suggestion
/obj/machinery/power/tracker/proc/sun_update(datum/source, azimuth)
	SIGNAL_HANDLER
	setDir(angle2dir(azimuth))
```

2023-05-23 00:19 UTC, closed without merging