Ports Drastic Lag Mitigation Subsystem: SSlag_switch
BeeStation/BeeStation-Hornet pull request #8674
Opened 2023-03-11 18:11 UTC by Chirynnn

## About The Pull Request
Ports https://github.com/tgstation/tgstation/pull/59717/, adding a new admin tool for hopefully mitigating lag to an extent during busy shifts. Unfortunately, I couldn't find a method to automatically add TRAIT_BYPASS_MEASURES to admin observers/players, so they are not exempt from the bottom options as of yet, I hope someone can help me with this.

## Why It's Good For The Game
Admeme tool for less lag good

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/77589317/224504805-870c7db9-4bb9-4715-926b-20c173f8f369.mp4

</details>

## Changelog
:cl:

admin: Added a lag mitigation panel in the Admin tab
/:cl:

2023-03-11 19:02 UTC, itsmeow commented
you can iterate over the player list, check if they have a `holder`, and then add the trait

2023-03-11 19:04 UTC, itsmeow commented
or just attached it to holder init and destroy

2023-03-11 19:04 UTC, Chirynnn commented
i have no idea what that means but you got it

2023-04-04 07:49 UTC, PowerfulBacon requested changes

2023-04-04 07:49 UTC, PowerfulBacon commented on code/__HELPERS/icons.dm
> +	if(SSlag_switch.measures[DISABLE_USR_ICON2HTML] && usr && !HAS_TRAIT(usr, TRAIT_BYPASS_MEASURES))
Use target.mob instead of usr (Make sure to null check)

2023-04-04 07:49 UTC, PowerfulBacon commented on code/__HELPERS/icons.dm
> +	if(SSlag_switch.measures[DISABLE_USR_ICON2HTML] && usr && !HAS_TRAIT(usr, TRAIT_BYPASS_MEASURES))
Same here, use target instead of usr

2023-04-04 07:49 UTC, PowerfulBacon commented on code/controllers/subsystem/lag_switch.dm
> +	for(var/i = 1, i <= measures.len, i++)
```suggestion
	for(var/i = 1 to length(measures))
```

2023-04-04 07:49 UTC, PowerfulBacon commented on code/controllers/subsystem/lag_switch.dm
> +	var/slowmode_cooldown = 3 SECONDS
Slowmode should be like 0.5 seconds imo, 3 seconds affects gameplay way too much

2023-05-27 00:20 UTC, closed without merging