Tweaks sleeper - accepts chem bag
BeeStation/BeeStation-Hornet pull request #8722
Opened 2023-03-18 20:43 UTC by EvilDragonfiend

## About The Pull Request
Tweaks sleeper
* Accepts chem bag
* Minor code improvement

## Why It's Good For The Game
these were supposed to go with the sleeper PR. there aren't much balance aspect here.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/87972842/226136724-7f0ed767-505d-4087-a555-db7df526d3b3.png)

pre-defined chem bag at first
roundstart chems after it. anti-toxin is ignored since it reached max vial size (6)
also, sorting order is now inserted chem's order, not alphabetical order

![image](https://user-images.githubusercontent.com/87972842/226136846-e5111b3e-aaf3-4b0a-b247-75dc4d1a6a82.png)

chem bag details (the later one has name. it's fixed)

![image](https://user-images.githubusercontent.com/87972842/226136890-8bdcc208-3288-4a64-9f27-59f779497cca.png)

when re-inserted those above.

</details>

## Changelog
:cl:
code: touched sleeper code slightly better
tweak: sleeper accepts chemical bag
tweak: sleeper now roundstarts with chem bag(max 200u) instead of 30u bottle
tweak: default sleeper has 80u of roundstart chems with 120u saline glucose. other sleepers have similar behavior.
tweak: sleeper vials are now sorted by inserted order, not alphabetical order
/:cl:

2023-03-19 17:05 UTC, Eric-01 commented
> also, sorting order is now inserted chem's order, not alphabetical order

Is this change really necessary? I like that currently the order is always the same, so I don't have to wonder where chem X is this time.

2023-03-19 17:15 UTC, Eric-01 commented
> also, sorting order is now inserted chem's order, not alphabetical order

Is this change really necessary? I like that currently the order is always the same, so I don't have to wonder where chem X is this time after the chemist fiddled with the sleeper.

2023-03-20 01:58 UTC, EvilDragonfiend commented
> > also, sorting order is now inserted chem's order, not alphabetical order
> 
> Is this change really necessary? I like that currently the order is always the same, so I don't have to wonder where chem X is this time after the chemist fiddled with the sleeper.

It becomes very inconsistent when you put customised chems. For example, Bicaridine will be first if there are no chems. But if there is antitoxin, Bicaridine will be second. If a cusrom chem that named as "Amazing chem", antitoxin will be second and bicaridine will be 3rd. If you put antitoxin-v2, anti(original) will be still there, and bicaridine will go 4th.
Seeing already existingn chems moving makes me really difficult to remember where to hit whenever chems are newly added, and these are not where I expect there are at.

2023-03-20 02:03 UTC, EvilDragonfiend commented
I mean

"Old"

2023-03-20 13:10 UTC, PowerfulBacon requested changes

2023-03-20 13:10 UTC, PowerfulBacon commented on code/game/machinery/Sleeper.dm
> +			beaker.reagents.add_reagent(/datum/reagent/medicine/salglu_solution, beaker.volume - beaker.reagents.total_volume) // the rest will be saline glucose
I don't think the reagents should be mixed with other reagents

2023-03-20 13:10 UTC, PowerfulBacon commented on code/game/machinery/Sleeper.dm
>  	)
How comes there are 2 different things here if they all go into chem bags anyway. Personally I think if we want to add more of a specific reagent then roundstart_chems should instead be an assoc list with the value being the reagent amount

```
	var/list/roundstart_chems = list(
		/datum/reagent/medicine/epinephrine = 80,
		/datum/reagent/medicine/morphine = 120,
		/datum/reagent/medicine/perfluorodecalin = 80,
		/datum/reagent/medicine/bicaridine = 80,
		/datum/reagent/medicine/kelotane = 80,
		/datum/reagent/medicine/antitoxin = 80
	)
```

2023-03-20 13:10 UTC, PowerfulBacon commented on tgui/packages/tgui/interfaces/Sleeper.js
> +            {data.chems.map(chem => (
Instead of doing this, add chems to the block of code that says 
```js
const {
    open,
    occupant = {},
    occupied,
} = data;

2023-03-20 13:10 UTC, PowerfulBacon commented
Ping on discord with PR link for quicker re-review

2023-03-20 17:14 UTC, PowerfulBacon approved these changes

2023-03-20 17:24 UTC, merged