Throatslicing, take II
BeeStation/BeeStation-Hornet pull request #875
Opened 2019-11-30 22:24 UTC by MarkSuckerberg

## About The Pull Request
https://github.com/BeeStation/BeeStation-Hornet/projects/2#card-29406288
Port:tgstation/tgstation#46838
Lets you cut someone's throat under certain conditions. Higher damage weapons get the job done faster. Weapon must be sharp, of course.

* Neck grab
* Critical
* Unconsciousness

The bleeding rate is 2.5x Heparin, for comparison.

For me at least, it is a little annoying that there is no way to execute someone in a quick, decisive action with a melee weapon and I am instead stuck stabbing them until they go horizontal. I can go get a gun and do the special execution action, but that's no fun.

## Why It's Good For The Game
It's cool, and it's a much needed way to execute someone a bit faster besides the long and lengthy gun execution.

## Changelog
:cl: Fhaxiris, Mark Suckerberg
add: You cut slice peoples throats now. Select the head on harm intent while they are sleeping, in critical, or neck grabbed.
/:cl:

2019-11-30 22:49 UTC, MarkSuckerberg commented
feck

2019-12-01 01:32 UTC, ike709 commented
Tested?

2019-12-01 01:48 UTC, qwertyquerty requested changes

2019-12-01 01:48 UTC, qwertyquerty commented on code/__DEFINES/components.dm
> +	#define COMPONENT_ITEM_NO_ATTACK 1
spaces beforeer

2019-12-01 02:58 UTC, ike709 commented on code/__DEFINES/components.dm
> +	#define COMPONENT_ITEM_NO_ATTACK 1
Intentional.

2019-12-01 05:22 UTC, MarkSuckerberg commented
Yes, tested, and it works as intended.

2019-12-01 07:07 UTC, merged