no-respawn config is disabled during debug mod
BeeStation/BeeStation-Hornet pull request #8831
Opened 2023-04-09 04:18 UTC by EvilDragonfiend

## About The Pull Request
* Disables no-respawn config automatically when game runs debug mode

## Why It's Good For The Game
QoL

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/87972842/230754157-438c9020-bd51-4802-8e76-0b0d1c2cadef.png)

![image](https://user-images.githubusercontent.com/87972842/230754158-db6ddb34-5037-4471-b7ef-d9901adf8b95.png)

![image](https://user-images.githubusercontent.com/87972842/230754159-0e1fef70-95da-4d3a-879d-65b9f6ebff9b.png)

</details>

## Changelog
:cl:
code: debug mode only - if a debug DEFINE is defined, no-resapwn will be automatically disabled.
/:cl:

2023-04-09 06:35 UTC, PowerfulBacon commented
Just make admins bypass the flag, theres no need for all the debug mode stuff on top

2023-04-09 21:14 UTC, ike709 commented on code/modules/mob/mob.dm
> +			log_game("[key_name(usr)] bypassed the respawn lock through the admin privilege.")
```suggestion
			log_admin("[key_name(usr)] bypassed the respawn lock through the admin privilege.")
```

2023-04-10 22:10 UTC, itsmeow requested changes

2023-04-10 22:10 UTC, itsmeow commented on code/modules/mob/mob.dm
> +			to_chat(usr, "<span class='boldnotice'>Respawning in this server is disabled.</span>")
```suggestion
			to_chat(usr, "<span class='boldnotice'>Respawning is disabled.</span>")
```

2023-04-10 22:10 UTC, itsmeow commented on code/modules/mob/mob.dm
> +		else if("Yes" == alert(src, "Do you want to use your admin privilege to respawn? (Respawning is currently disabled)", "Options", "Yes", "No"))
No need for the additional log message, and this is cleaner (don't actually commit this directly)

```suggestion
		else if(alert(src, "Do you want to use your admin privilege to respawn? (Respawning is currently disabled)", "Options", "Yes", "No") != "Yes)
		    return
```

2023-04-22 21:34 UTC, PowerfulBacon commented on code/modules/mob/mob.dm
> +		if(!check_rights_for(usr.client, R_ADMIN))
```suggestion
		if(!check_rights_for(client, R_ADMIN))
```
We are being called from a mob, so we don't need to go through usr since usr = src.

2023-04-22 21:35 UTC, PowerfulBacon commented
This should message admins, the same way that respawning as an admin already does (Through player panel -> send to lobby)

2023-04-23 06:53 UTC, EvilDragonfiend commented
addressed

2023-04-29 07:34 UTC, PowerfulBacon approved these changes

2023-05-18 03:36 UTC, itsmeow approved these changes

2023-05-18 03:43 UTC, merged