Brand Intelligence event is no more miserable (mimic venders)
BeeStation/BeeStation-Hornet pull request #8881
Opened 2023-04-16 08:42 UTC by EvilDragonfiend

## About The Pull Request
Brand Intelligence event is no more miserable (mimic venders)
this means animating venders will return stuff

## Why It's Good For The Game
It's super annoying event

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/87972842/232287154-264dfa3c-e8b6-48a5-b20e-ebf5701a4988.png)

dead mimics

</details>

## Changelog
:cl:
code: made mimic code less bad
tweak: mimic mobs (especially, animating venders) will become back to how it was. For Brand Intelligence event, dead mimics will become a destroyed vending machine
/:cl:

2023-05-17 11:07 UTC, itsmeow requested changes

2023-05-17 11:07 UTC, itsmeow commented on code/modules/mob/living/simple_animal/hostile/mimic.dm
> +		var/obj/structure/closet/crate = new spawaning_obj_type(turf_to_spawn)
what if it's not a closet? nothing is created?

2023-05-17 11:07 UTC, itsmeow commented on code/modules/events/brand_intelligence.dm
> +					M.desc += " By the way, this seems to be robust..."
```suggestion
					M.desc += " This one seems extra robust..."
```

2023-05-17 11:07 UTC, itsmeow commented on code/modules/events/brand_intelligence.dm
> +					M.desc += " By the way, this seems to be hurting..."
```suggestion
					M.desc += " This one seems extra painful..."
```

2023-05-17 11:07 UTC, itsmeow commented on code/modules/events/brand_intelligence.dm
> +					M.desc += " By the way, this is obviously faster."
```suggestion
					M.desc += " This one seems more agile..."
```

2023-05-17 14:06 UTC, EvilDragonfiend commented on code/modules/mob/living/simple_animal/hostile/mimic.dm
> +		var/obj/structure/closet/crate = new spawaning_obj_type(turf_to_spawn)
nothing will be created. it's specified when a mimic is crate and they should remain a crate as broken after they die

2023-05-18 02:17 UTC, itsmeow approved these changes
Brand Intelligence is one of those events that makes me annoyed every time I see it and yet I need to roleplay like it's some brand new fresh thing, and that makes me hate it. This should make it less awful for everyone involved.

2023-05-18 02:23 UTC, merged