Fixes Meteors Being Too Slow
BeeStation/BeeStation-Hornet pull request #8920
Opened 2023-04-23 01:00 UTC by Wisemonster

## About The Pull Request
* Fixes #8725
Fixes meteors moving at a snails pace, so that they will now arrive at a reasonable time.

## Why It's Good For The Game
Bug bad

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
This is the normal 10 minute meteor event.

![Earth Observatory Gamma 4_22_2023 8_55_34 PM](https://user-images.githubusercontent.com/87689371/233813658-3fb98df3-1bf6-4e37-8766-dcf303ccddc5.png)

</details>

## Changelog
:cl:
fix: Fixed meteors being too slow to reach the station in a timely manner.
/:cl:

2023-04-23 14:06 UTC, itsmeow approved these changes

2023-04-24 09:41 UTC, PowerfulBacon requested changes
I was wrong on discord when I said that this was the fix, the actual problem was that end_tick is being incorrectly assigned to in `/datum/round_event/meteor_wave/tick()` in the file `code/modules/events/meteor_wave.dm`, as it uses world time instead of SSorbits.times_fired.
The line of code on 48 should read `meteor.end_tick = SSorbits.time_fired + (meteor_time / SSorbits.wait)`
This solution technically works but only because it is 2 errors cancelling each other out.

2023-04-24 13:46 UTC, Wisemonster commented
Ok, implemented changes suggested by Bacon, considering they actually fix the problem.

2023-04-24 18:38 UTC, PowerfulBacon approved these changes
Thanks for making these changes

2023-04-24 18:44 UTC, merged