Prevents stabilized metal crossbreeds from being able to replicate TC
BeeStation/BeeStation-Hornet pull request #9015
Opened 2023-05-12 11:55 UTC by Tyranicranger4

## About The Pull Request
Alternative PR of #9010 
Fixes #8995 

Prevents the stabilized metal crossbreed in xenobiology from replicating Telecrystals.

## Why It's Good For The Game
Telecrystals shouldn't be producable in round, definitely not in potentially infinite amounts.

I don't believe that leaving this in game in any capacity as proposed in #9010 is a good idea.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

A sheet of metal, glass, and reinforced glass were placed within the same bag. I then waited a few minutes.
No telecrystals were created. Other materials were created as expected.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/80382633/45af8547-b2b6-4f51-abcd-a492b17f5f83)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/80382633/8706e229-8030-4182-831e-1a519e88c896)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/80382633/fae1ea1e-334e-4a9c-a201-0937419c52fa)

</details>

## Changelog
:cl:
fix: Fixes Stabilized Metal crossbreeds from being able to replicate telecrystals.
/:cl:

2023-05-12 12:02 UTC, EvilDragonfiend requested changes

2023-05-12 12:02 UTC, EvilDragonfiend commented on code/modules/research/xenobiology/crossbreeding/_status_effects.dm
> +			if(S.amount < S.max_amount && S.type != /obj/item/stack/sheet/telecrystal)
It's still duplicable because telecrystal isn't a single path. use `istype()` instead.

2023-05-12 12:26 UTC, Tyranicranger4 commented on code/modules/research/xenobiology/crossbreeding/_status_effects.dm
> +			if(S.amount < S.max_amount && S.type != /obj/item/stack/sheet/telecrystal)
Right. Because the five stack and so on are subtypes of it, no? Thank you.

2023-05-12 12:31 UTC, EvilDragonfiend commented on code/modules/research/xenobiology/crossbreeding/_status_effects.dm
> +			if(S.amount < S.max_amount && S.type != /obj/item/stack/sheet/telecrystal)
the condition only checks if the thing is **exactly** `/obj/item/stack/sheet/telecrystal` path, not its subtypes of it.

2023-05-13 06:14 UTC, PowerfulBacon approved these changes

2023-05-13 06:19 UTC, merged