Refactors access system - access checking, desc, etc
BeeStation/BeeStation-Hornet pull request #9027
Opened 2023-05-15 14:09 UTC by EvilDragonfiend

## About The Pull Request
Refactors access checking system
every access was checked through `ACCESS in card_access` and it's bad for the time complexity.
Although it's not much deal in our codebase as we really don't have much accesses in a card access, but it slightly annoyed me when I see the nature of how this works lol
also, cleaned up some bad coding

## Why It's Good For The Game
code & performance improvement

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/80248a0e-ed23-4886-abd8-2f00c270d25b)

card console is fine

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/03e065b2-a047-41cd-92cb-bb116974151b)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/323e2966-01c6-4de6-9095-1c031b017e1d)

wallet gets combined acceess well

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/fda1f621-a400-4019-bfbd-2e2bcc2df605)

I can ride on a syndi mech with a wallet

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/a1bfc7ee-10f7-43d4-83ab-b2826a3df9b1)

access desc display is sane

</details>

## Changelog
:cl:
code: cleaned up some bad coding
refactor: refactored access checking system. checking access is slightly faster
/:cl:

2023-05-17 10:17 UTC, itsmeow requested changes

2023-05-17 10:17 UTC, itsmeow commented on code/modules/jobs/access.dm
> +/proc/grant_accesses_to_card(list/referenced_target_access, list/access_list)
don't explicitly type access_list if the type varies

2023-05-17 10:17 UTC, itsmeow commented on code/modules/jobs/access.dm
> +	if(!islist(access_list)) // do not change the check to 'isnum()' because text/number comes
istext || isnum works

2023-05-17 14:51 UTC, EvilDragonfiend commented
* review addressed
* HoP fax is merged, and changed the access check code

2023-05-18 03:16 UTC, itsmeow approved these changes
This is real sus (I feel like it could break something) but given it's mostly a reformatting and works in testing.... ok your speedmerge privileges have been granted

2023-05-18 03:21 UTC, EvilDragonfiend commented
thank you ❤️❤️❤️❤️❤️

2023-05-18 03:23 UTC, merged

2023-05-18 07:26 UTC, PowerfulBacon commented
After doing some checks with ?compile and running both in and access check proc for 5 seconds:

|Input Size|in count|access check count|
|-|-|-|
|1|9402889|3758713|
|2|9468313|3820412|
|5|9426707|3854456|
|10|6566330|2646274|
|100|6204513|2781983|
|1000|5668724|2743046|

(I ran multiple bot commands at once for 10-1000, so there are less overall. The ratio is what is important hr)

So as for performance, this performs worse. Care should be taken when using big O notation, specifically the fact that Big O notation is a measure for how well an algorithm scales, not how well it performs. Also keep in mind we are byond and byond does weird things. In the majority of cases things that should be slower are faster due to having direct implementations in the underlying engine language (C?), which gets performance we couldn't dream of in byondland.
In addition to this, the added complexity of code and reduction of portability probably isn't worth slightly better performance on cold paths.

Part of the reason for the lower performance, is due to calling a proc. Proc calls have quite a bit of overhead when compared to functions that are almost nothing such as this.

<details>
```
/world
  loop_checks = 0

/proc/test1(i)
  var/start = world.timeofday
  var/list/a = list()
  for (var/j in 1 to i)
    a += j
  var/out
  var/count = 0
  while (world.timeofday < start + 50)
    out += (rand(1, 10) in a)
    count ++
  world.log << "Completed: [count ], Total: [out]"

/proc/test2(i)
  var/start = world.timeofday
  var/list/a = list()
  for (var/j in 1 to i)
    a["[j]"] = 1
  var/out
  var/count = 0
  while (world.timeofday < start + 50)
    out += check_access(a, "[rand(1,10)]")
    count ++
  world.log << "Completed: [count ], Total: [out]"

/proc/check_access(card, acc)
  return card["[acc]"]

/proc/main()
  test1(1)
  test2(1)
```
</details>

Considering this makes the code far more complex and will cause conflicts, I am going to recommend a revert for this PR (I'll make it when I get some free time).