Potential fix for singularity eating itself
BeeStation/BeeStation-Hornet pull request #9029
Opened 2023-05-16 05:03 UTC by itsmeow

## About The Pull Request

The singulo ate itself last round. I think this is how? Also adds some logging and sanity checks.

## Why It's Good For The Game

Fixes a bug.

## Testing Photographs and Procedure

The cause of this is really hard to identify, it has to move onto a turf it's queued to eat. Not sure how to test this.

## Changelog
:cl:
fix: Potentially fix singularities eating themselves.
/:cl:

2023-05-17 09:37 UTC, PowerfulBacon commented
Did it explode or just disappear? If it just disappears then its probably due to singularities losing mass over time.

2023-05-17 09:39 UTC, PowerfulBacon commented on code/datums/components/singularity.dm
>  			consume(src, current_turf)
This should be impossible unless something inside singularity_act sleeps, unless consuming a turf causes everything on it to be consumed too

2023-05-17 09:39 UTC, PowerfulBacon commented
Logging for when a singularity eats another singularity is good though

2023-05-17 11:11 UTC, PowerfulBacon commented
It most likely just ran out of energy rather than ate itself, especially if it was at the minimum level. I wasn't there to see it. I still think the changes are good for logging it, but the check inside moved() is pointless so long as its synchronous which it should be

2023-05-18 02:31 UTC, itsmeow commented
> It most likely just ran out of energy rather than ate itself, especially if it was at the minimum level. I wasn't there to see it. I still think the changes are good for logging it, but the check inside moved() is pointless so long as its synchronous which it should be

Running out of energy is logged. I checked logs and there was no log. It broke containment, ate a containment field generator and a portion of the floor, and then boom it was gone.

2023-05-18 07:38 UTC, PowerfulBacon requested changes
Crash is better if we want to return null since it won't result in the logs being combined into a single place

2023-05-18 07:38 UTC, PowerfulBacon commented on code/modules/power/singularity/singularity.dm
> +		return
```suggestion
		CRASH("consume() called on self by singularity [src]")
```

2023-05-18 09:56 UTC, PowerfulBacon approved these changes

2023-05-28 21:00 UTC, merged