Removes SUPERMATTER_IGNORE_1 flag
BeeStation/BeeStation-Hornet pull request #9030
Opened 2023-05-16 05:45 UTC by EvilDragonfiend

## About The Pull Request
Removes SUPERMATTER_IGNORE_1 flag
atom flag that is used in a small specific case is not good

## Why It's Good For The Game
snip

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
code: removed SUPERMATTER_IGNORE_1 atom flag. SM has a static list that checks if it should not consume an atom.
/:cl:

2023-05-16 20:18 UTC, itsmeow requested changes

2023-05-16 20:18 UTC, itsmeow commented on code/modules/power/supermatter/supermatter.dm
> +	else if(consume_protected[AM.type])
typecaches use `isintypecache`.

2023-05-16 20:19 UTC, itsmeow commented on code/modules/power/supermatter/supermatter.dm
> +	var/static/list/consume_protected = list()
Better to have this be empty (null) since its gonna be replaced anyway

2023-05-17 01:07 UTC, EvilDragonfiend commented
review addressed.
also, changed to check typecheck earlier so that it won't call consume() or not show unnecessary messages.

2023-05-17 04:15 UTC, imsynthex requested changes

2023-05-17 04:15 UTC, imsynthex commented on code/__DEFINES/flags.dm
>  /// Does the supermatter skip over this atom?
```suggestion

```

2023-05-17 04:15 UTC, imsynthex commented on code/modules/power/supermatter/supermatter.dm
> +	var/static/list/consume_protected
`not_dustable` would be a better, more descriptive name

2023-05-17 04:41 UTC, EvilDragonfiend commented on code/__DEFINES/flags.dm
>  /// Does the supermatter skip over this atom?
oh yeah I forgot it

2023-05-17 12:00 UTC, itsmeow requested changes

2023-05-17 12:00 UTC, itsmeow commented on code/modules/power/supermatter/supermatter.dm
> +		if(!HAS_TRAIT(l, TRAIT_MADNESS_IMMUNE) || !HAS_TRAIT(l.mind, TRAIT_MADNESS_IMMUNE))
```suggestion
		if(HAS_TRAIT(l, TRAIT_MADNESS_IMMUNE) || HAS_TRAIT(l.mind, TRAIT_MADNESS_IMMUNE))
```

2023-05-17 12:02 UTC, EvilDragonfiend commented on code/modules/power/supermatter/supermatter.dm
> +		if(!HAS_TRAIT(l, TRAIT_MADNESS_IMMUNE) || !HAS_TRAIT(l.mind, TRAIT_MADNESS_IMMUNE))
Oh shit I missed it lol

2023-05-17 12:03 UTC, itsmeow approved these changes

2023-05-17 12:13 UTC, merged