Makes anomalies and wormholes spawn harvested pierced realities
BeeStation/BeeStation-Hornet pull request #9046
Opened 2023-05-19 21:01 UTC by CydiaLamiales

## About The Pull Request
Makes several anomalies and the wormhole vent spawn harvested pierced realities.

## Why It's Good For The Game
This introduces more false positives to the game. Heretics already leave plenty of clues to their presence, and harvested Pierced Realities being able to appear 'naturally' forces crew to investigate into them further rather than calling out their presence solely based on Harvested Realities existing.
(Same thing happened with the Xeno room on Corg, people starged to put in more effort instead of instantly calling out xenos)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/b7e9173d-c353-4472-819a-a07ab18dc41e)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/541bceba-891a-415e-ac9c-0870dbd5d0de)

</details>

## Changelog
:cl:
add: Made several Anomalies and Wormholes create harvested pierced realities upon expiring
code: Added a turf proc for generating harvested pierced realities
/:cl:

2023-06-01 09:10 UTC, itsmeow requested changes

2023-06-01 09:10 UTC, itsmeow commented on code/game/turfs/turf.dm
> +		spawned ++
```suggestion
		spawned++
```

2023-06-11 09:24 UTC, EvilDragonfiend requested changes, later dismissed
I think these will be spawned in open space or densified turf.
but also appearing time should be a bit desynced from the creation of anomalies.

For example, `addtime(generate_fake_pierced_realities(), rand(0, 300) SECONDS)`

2023-06-17 19:12 UTC, EvilDragonfiend commented on code/game/turfs/turf.dm
> +	new new /obj/effect/visible_heretic_influence(F)
new new...?
also, please put a line.

2023-06-17 19:13 UTC, CydiaLamiales commented on code/game/turfs/turf.dm
> +	new new /obj/effect/visible_heretic_influence(F)
Already fixed it

2023-07-22 03:02 UTC, itsmeow commented on code/game/turfs/turf.dm
> +		spawned ++
You did not resolve this bestie

2023-07-22 03:03 UTC, itsmeow approved these changes
Very good addition

2023-07-22 03:16 UTC, merged