The end of Pubbystation (and Glowstation aswell)
BeeStation/BeeStation-Hornet pull request #9065
Opened 2023-05-21 20:05 UTC by PestoVerde322

## About The Pull Request

This PR just removes Pubbystation and Glowstation from the code, after a prolonged discussion within the dev group.

Also expunged as many reference from pubby as possible, Aside for the shuttles, no latient content that refeer to something that no longer exist.

## Why It's Good For The Game

First and foremost, this PR is being done due to streamline the process on updating maps if any sort of gameplay update happens (remember when almost all of the viros had to be updated?)

Second off, Pubby is a poorly maintained map, with an even poorer layout; while Glow is kinda underbaked as it stands right now (may come in a different form if kat decides to make a better, more stable version).

Lastly, It's for the mental sake of all the map maintainers to just work around maps better and give room to more home built maps like Radstation.

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

N/A, what i should show if it's just gone?

It's the end of Pubbystation as we know it, and i feel fine (also current glow, but not for long hopefully).

</details>

## Changelog
:cl:
del: Removed Pubby station off the rotation
del: Removed Glow station off the rotation
/:cl:

2023-05-21 20:09 UTC, imsynthex approved these changes
I don't know whose idea it was but I approve

2023-05-21 20:20 UTC, PowerfulBacon commented
_maps/shuttles/exploration/exploration_fland.dmm:197:error: undefined type: /obj/machinery/vending/boozeomat/pubby_maint
_maps/shuttles/exploration/exploration_fland.dmm:200:error: unknown type

2023-05-21 20:23 UTC, Crossedfall commented
This seems wrong
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26130695/5d9b5da3-c3e9-4ad8-96d8-25ba3971f8a6)

2023-05-21 20:30 UTC, Crossedfall approved these changes
The booze-o-mat shows up on local (so I've been told). I'm good with the changes. This will need wiki updates.

2023-05-21 20:54 UTC, Tsar-Salat commented
> This will need wiki updates.

Recommend the creation of a new legacy maps page for strictly-Beestation maps. There we can put Glow and Pubby's pages in their entirety. This will let us easily replace Glow's wikipage again if someone decides to readd it.

2023-05-21 21:33 UTC, PowerfulBacon approved these changes
This will be merged later, upon the merging of RadStation

2023-05-22 02:56 UTC, itsmeow commented
This also should update the README which has a map list

2023-05-22 05:35 UTC, itsmeow requested changes

2023-05-22 05:35 UTC, itsmeow commented on code/modules/vending/medical_wall.dm
> +/obj/machinery/vending/wallmed/Lite
don't capitalize typepaths

2023-05-22 05:35 UTC, itsmeow commented on _maps/map_files/CorgStation/CorgStation.dmm
> +/obj/machinery/vending/boozeomat/captain ,
space here

2023-05-22 08:38 UTC, PowerfulBacon commented
how is the readme conflicting 💀

2023-05-25 19:58 UTC, Crossedfall commented on code/modules/vending/boozeomat.dm
> +/obj/machinery/vending/boozeomat/captain//Captain's quarters variant
```suggestion
/obj/machinery/vending/boozeomat/captain //Captain's quarters variant
```

I actually prefer comments above the object, but, this keeps it consistent.

2023-05-25 20:02 UTC, itsmeow approved these changes

2023-05-26 05:46 UTC, Crossedfall approved these changes

2023-05-29 10:52 UTC, merged