Fixes orbit panel shows a mob twice
BeeStation/BeeStation-Hornet pull request #9074
Opened 2023-05-23 02:39 UTC by EvilDragonfiend

## About The Pull Request
Fixes orbit panel shows a mob twice

This is because a mob is added to `mob_list` and `poi_list` at the same time when its `var/playable` is set to TRUE
a mob that's added to `poi_list` will not be removed because a mob key is automatically given by code but it's not occupied by players.
I added a new proc `delayed_set_playable()` which will be used in mob init().

## Why It's Good For The Game
bug fix

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/7a2e901c-7495-42a6-b73e-177737f2de98)

</details>

## Changelog
:cl:
fix: Fixed orbit panel shows a mob twice
/:cl:

2023-05-24 16:07 UTC, itsmeow requested changes

2023-05-24 16:07 UTC, itsmeow commented on code/modules/mob/living/living_sentience.dm
> +	set waitfor = 0 // I didn't want to use 'addtimer(CALLBACK(), 2 SECONDS)' so I tried this instead
i don't like this proc, use addtimer or move the proccall after key assignment

2023-05-28 06:04 UTC, EvilDragonfiend commented on code/modules/mob/living/living_sentience.dm
> +	set waitfor = 0 // I didn't want to use 'addtimer(CALLBACK(), 2 SECONDS)' so I tried this instead
change to addtimer.

2023-05-28 18:21 UTC, itsmeow requested changes

2023-05-28 18:21 UTC, itsmeow commented on code/modules/mob/living/living.dm
> +		delayed_set_playable()	//announce to ghosts
you don't need a new proc for something done only once

2023-05-29 09:45 UTC, EvilDragonfiend commented
review addressed

2023-05-30 08:39 UTC, itsmeow approved these changes

2023-05-30 08:45 UTC, merged