Abductors now have a smartfridge instead of their old fridge
BeeStation/BeeStation-Hornet pull request #9097
Opened 2023-05-28 05:50 UTC by EvilDragonfiend

## About The Pull Request
Abductors now have a smartfridge instead of their old fridge
That you don't know which container has which organ is one of reasons why abductors are usually annoying. They just put shits into people randomly.
This will let them have a choice of what they'll put into people.

Also, buffs gland generation amounts.

## Why It's Good For The Game
removing tedious-ism.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/4fbbf872-6fb0-41c1-a868-3754a80ffb02)

</details>

## Changelog
:cl:
tweak: abductor gland storage now uses smartfridge UI instead of too-alieny-UI.
tweak: abductor gland storage now has 10~15 glands at starting.
add: broken glands will be restored once you put these into a new storage (old one doesn't work)
tweak: antagonists can open abductor gland storage
/:cl:

2023-05-28 08:34 UTC, Tsar-Salat commented
> This will let them have a choice of what they'll put into people.

Put balance in the changelog. It's going to have round ramifications.

2023-05-28 08:37 UTC, WrillWasTaken commented
> Recommend putting balance in the changelog. It's going to have round ramifications

The scientist can already see the organ names and pick the one they want, they just have to try every single slot. All this changes is removing the tediousness.

2023-05-28 12:25 UTC, EvilDragonfiend commented
> > Recommend putting balance in the changelog. It's going to have round ramifications
> 
> The scientist can already see the organ names and pick the one they want, they just have to try every single slot. All this changes is removing the tediousness.

At least agent can see names through this, but wouldn't be that matter, I think.

2023-05-28 12:26 UTC, EvilDragonfiend commented
actually I forgot to put that it in CL

2023-05-31 08:55 UTC, PowerfulBacon requested changes
Lower the gland generation amounts so that you have to actually put different glands in people, make the fridge fit the abductor theme.

Is this a good change, should abductors be able to know easilly what they are putting in people?

2023-06-02 16:27 UTC, PowerfulBacon commented
Did you push?

2023-06-03 02:52 UTC, EvilDragonfiend commented
> Did you push?

I forgor 💀

2023-07-27 17:17 UTC, PowerfulBacon commented on code/modules/antagonists/abductor/machinery/dispenser.dm
> +	if(!isabductor(user) && !user.mind.has_antag_datum(/datum/antagonist) && !isobserver(user))
```suggestion
	if(!isabductor(user) && !isobserver(user))
```
Don't specifically check for antagonist status, just checking for the species is fine. If someone becomes an abductor and gets aboard the abductor ship then taking the stuff isn't too bad (They can read the language now after all)

2023-07-30 14:50 UTC, EvilDragonfiend commented
addressed

2023-08-11 16:28 UTC, PestoVerde322 approved these changes
All good to go, approved

2023-08-18 04:48 UTC, itsmeow approved these changes

2023-08-20 16:09 UTC, PowerfulBacon approved these changes

2023-08-20 16:21 UTC, merged