Removes yet another xenobio exploit
BeeStation/BeeStation-Hornet pull request #9135
Opened 2023-05-31 17:16 UTC by Dejaku51

## About The Pull Request
extract do_after was attached to the turf player was on instead of the extract so it didn't cancel when extract was deleted resulting in a lot of pylons if spammed. This PR fixes it.
Also someone could place another pylon while yours was being constructed because it checked for pylons only before the progress bar

## Why It's Good For The Game
Xenobio exploits bad

## Testing Photographs and Procedure
- Try to spam xenobio crystalline pylons
- Progressbars vanish/cancel when one pylon gets created

<details>
<summary>Screenshots&Videos</summary>

Current master behavior:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/40302913/411a4b7f-4ff0-43fa-a2bf-659103502cc8)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/40302913/6be59778-b99c-488b-afba-ea109fa0739d)

This PR behavior:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/40302913/74c5a400-ca90-44c8-8bef-7a76001e1cb2)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/40302913/d8f8297b-cc0d-4053-ad9e-6153cdd9aabf)

</details>

## Changelog
:cl:
fix: Fixed xenobio infinite pylons exploit that could potentially crash the server
/:cl:

2023-05-31 17:17 UTC, PowerfulBacon commented on code/modules/research/xenobiology/crossbreeding/crystalized.dm
> +	if(C)
Check if src is qdeleted too

2023-05-31 17:18 UTC, PowerfulBacon approved these changes

2023-05-31 17:37 UTC, PowerfulBacon requested changes
There isn't spacing between functions and this solution is kind of ugly.
Just do
```
if(locate(/obj/structure/slime_crystal) in range(6,get_turf(user)))
	to_chat(user,"<span class='notice'>You can't build crystals that close to each other!</span>")
```

2023-06-01 06:58 UTC, PowerfulBacon requested changes

2023-06-01 06:58 UTC, PowerfulBacon commented on code/modules/research/xenobiology/crossbreeding/crystalized.dm
>  	var/obj/structure/slime_crystal/C = locate(/obj/structure/slime_crystal) in range(6,get_turf(user))
Unused variable

2023-06-06 16:16 UTC, Dejaku51 commented on code/modules/research/xenobiology/crossbreeding/crystalized.dm
>  	var/obj/structure/slime_crystal/C = locate(/obj/structure/slime_crystal) in range(6,get_turf(user))
fixed

2023-06-07 06:40 UTC, PowerfulBacon approved these changes

2023-06-07 06:46 UTC, merged