Separate Curse of Madness into two rituals: Brain curse, Curse of Twisted Reality
BeeStation/BeeStation-Hornet pull request #9140
Opened 2023-06-01 06:16 UTC by EvilDragonfiend

## About The Pull Request
Separate Curse of Madness into two rituals:
* **Brain curse**: Everyone gets a special trauma for 20% chance, and magical trauma for 80% chance. Curable by Brain Recalibration.
* **Curse of Twisted Reality** : You write a message, and wait for an admin's approval. It works to similar to brainwash, but it will need to be creative to be approved. for example:
  * Captain is the lowest rank in Chain of Command.
  * Nanotrasen is a subcompany of Syndicate.
  * Hugging someone means I want to kill you and I will kill you.
  * Everyone is clown.
  
  It shouldn't work as a lame brainwash objective like `serve X, help them for their objectives.`, and that's why it has admin approval.
  This is also castable multiple times.

## Why It's Good For The Game
It's a ritual that nobody actually uses and a possible noob trap.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/e13d4149-ebdb-4698-bb4e-f0335ccb2230)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/6e543a05-159b-4acf-b1ff-3f23952dd792)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/e93178dc-8f1b-481f-99ff-a05caab2e5f7)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/2fc75d2f-8149-411b-bdcf-ba8b16c60b01)

latejoin suffering

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/aa55a21e-e5b7-46a8-bcbf-71979f3af520)

posibrain

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/b0121cce-8ebd-46bf-81de-522e6b23e9ad)

round end

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/5c65ccfd-bad1-4785-81fd-60b939414bde)

approval chat

</details>

## Changelog
:cl:
balance: curse of madness wizard ritual is now Brain Curse - 2 spell points. Curable by Brain Recalibration. Doesn't send a message of madness. 20% chance to get special trauma, 80% chance to get magical trauma.
add: new ritual - curse of twisted reality. It works as a mass brainwash, but it needs admin approval. 2 spell points. Late joiners will get the same suffering. Also, castable multiple times.
/:cl:

2023-06-01 06:23 UTC, Absolucy requested changes

2023-06-01 06:23 UTC, Absolucy commented on code/modules/antagonists/wizard/equipment/spellbook.dm
> +	to_chat(user, "<span class='notice'>Wizard Federation rejected your ritual.</span>")
```suggestion
	to_chat(user, "<span class='notice'>The Wizard Federation rejected your ritual.</span>")
```

2023-06-01 06:23 UTC, Absolucy commented on code/modules/antagonists/wizard/equipment/spellbook.dm
> +	to_chat(user, "<span class='notice'>The twisted reality has been manipulated!</span>")
```suggestion
	to_chat(user, "<span class='notice'>Reality has been twisted!</span>")
```

2023-06-01 06:23 UTC, Absolucy commented on code/modules/antagonists/wizard/equipment/spellbook.dm
> +	to_chat(user, "<span class='notice'>Wizard Federation will evaluate your declaration: [message]. \
```suggestion
	to_chat(user, "<span class='notice'>The Wizard Federation will evaluate your declaration: [message]. \
```

2023-06-01 06:23 UTC, Absolucy commented on code/modules/antagonists/wizard/equipment/spellbook.dm
> +	var/message = stripped_input(user, "Declare the new fact to twist the reality of everyone.", "Twisting the reality")
```suggestion
	var/message = tgui_text_input(user, "Declare the new fact to twist the reality of everyone.", "Twisting the reality")
```
note: tgui_text_input automatically encodes/trims/etc.

2023-06-01 06:23 UTC, Absolucy commented on code/modules/antagonists/wizard/equipment/spellbook.dm
> +	var/wait_time = 600
```suggestion
	var/wait_time = 1 MINUTES
```

2023-06-01 06:23 UTC, Absolucy commented on code/datums/mind.dm
> +		output += "<br>Your mind is imprinted with the fact of the twisted reality:<BR>"
```suggestion
		output += "<br>Your mind is imprinted with the fact[length(GLOB.curse_of_twisted_reality_messages) > 1 ? "s" : ""] of the twisted reality:<BR>"
```

2023-06-01 06:26 UTC, EvilDragonfiend commented
Thanks for the grammar corrections lol

2023-06-01 06:28 UTC, Absolucy commented
Glad to help. This seems like a really fun idea, especially since admin approval makes this hard to abuse. I hope it gets through (and I hope I manage to roll wizard one day)

2023-06-01 06:56 UTC, PowerfulBacon requested changes
Requiring admin approval for something is indicative of poor design. If you are going to require admin approval it shouldn't be something like "must be creative", rather "must not be a rule break".

Also I don't really understand how this is good for the game. The reasoning in the PR body is that nobody buys it, which is untrue, but even if that was the case wouldn't splitting it into 2 spells make ot objectively worse and less likely to be purchased?

2023-06-01 07:26 UTC, EvilDragonfiend commented
Also, the required message manner to the ritual is ion laws style. It shouldn't be just typical brainwash message, but people will not understand how they should write a thing.

2023-06-01 09:44 UTC, PowerfulBacon commented
The current curse of madness isn't brainwashing, people don't get brainwashed by it. It is a message inside their heads which drives them mad and applies the magical traumas to everyone.

2023-06-01 10:56 UTC, JixS4v commented
Maybe implement a suggestion system that lets the player select some pre defined brainwashes that are similar to the expected player-provided curses?

2023-06-08 19:28 UTC, PowerfulBacon commented
I think giving the wizard the ability to just brainwash everyone is a bad idea, the current curse is a message and not a brainwash. Especially since this requires strict admin moderation on top of it to function.

2023-06-08 19:28 UTC, closed without merging