Fix roundstart operating computers not linking properly
BeeStation/BeeStation-Hornet pull request #9158
Opened 2023-06-03 00:59 UTC by Absolucy

## About The Pull Request

Roundstart op computers sometimes only do a "half" link, where it's linked but patient info won't appear on the operating computer. This should fix that.

## Why It's Good For The Game

bugfix

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![23-06-02-1685753881-dreamseeker](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/688e9d00-ef4b-480e-a9f5-f2c087cafeb9)

</details>

## Changelog
:cl:
fix: Fixed roundstart operating computers only partially linking to their given stasis bed/operating table.
/:cl:

2023-06-04 09:43 UTC, EvilDragonfiend requested changes
I think `initial_link()` should be called from another object after it detects an object to be paired, not letting two objects have the same but a bit different code.


Edit:
stasis bed one should be `detect_operating_computer()` and it should find an operating computer nearby, and call `lnitial_link()` of the operating computer.

2023-06-07 22:56 UTC, Archanial commented on code/game/machinery/stasis.dm
> +	for(var/direction in GLOB.alldirs)
by the time this is invoked you may have already been linked.
Also applied to initial link bellow.

2023-06-08 11:08 UTC, PowerfulBacon commented on code/game/machinery/computer/Operating.dm
> +		return INITIALIZE_HINT_LATELOAD
Doesn't late load get called instantly if not in mapload anyway?

2023-06-09 07:37 UTC, EvilDragonfiend approved these changes
seems fine except for the parameter names.

2023-06-09 07:37 UTC, EvilDragonfiend commented on code/game/machinery/computer/Operating.dm
> +		src.table = table
that reads confusing. parameter names should be different.

2023-06-13 04:01 UTC, EvilDragonfiend commented on code/game/machinery/computer/Operating.dm
> +	new_sbed = new_sbed || find_sbed()
I think `find()` procs will unintendingly happen when you only want `new_table` or `new_sbed` linked to that.
`find()` proc shouldn't be triggered if it already has linked object.

2023-06-13 04:06 UTC, EvilDragonfiend approved these changes

2023-06-13 07:06 UTC, PowerfulBacon approved these changes

2023-06-13 07:13 UTC, merged