Ghosts can now see normally hidden implants and viruses when health scanning someone
BeeStation/BeeStation-Hornet pull request #9161
Opened 2023-06-03 04:50 UTC by Absolucy

## About The Pull Request

This makes it so ghosts can see hidden (but not dormant) viruses and hidden cybernetic implants when health scanning someone.

## Why It's Good For The Game

QoL for ghosts that makes it easier for ghosts to know when shenanigans are happening.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![23-06-03-1685767831-dreamseeker](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/59d46aea-6e75-4b1f-88cf-d7c1044b4b4b)

</details>

## Changelog
:cl:
add: Ghosts can now see stealthy viruses and hidden cybernetic implants when health scanning someone. 
/:cl:

2023-06-03 10:15 UTC, Rukofamicom reviewed
I'm not sure there's a case where having this information before it was already apparent makes the round more entertaining for ghosts, so I'd like more elaboration on why you think this is good for the game: What are some examples where this measurably improves the game for observers (or otherwise) and how does that compare to the risk of potential abuse?

Code looks good, though.

2023-06-03 18:11 UTC, Absolucy commented
It's just to satisfy curiosity as a ghost, honestly.

2023-06-03 20:29 UTC, Fronsis commented
While it might be entertaining to see "Oh damn John Doe got a macrobomb implant and a stealth one let's follow him" it could also just be used to meta-knowledge stuff by our most gamers individuals that still lurk near, maybe that John Doe wants to use his implant on Cap but Cap died randomly to vines and heard the shenanigans of d-chat so he might be a little OOC aware than if he didn't

Though in the end it falls on players good sportmanship, followage of rules and so to not metagame while dead but inevitable it can happen specially on lowpop when no admins are on and it's hard to prove making them get away with their little gamer maneuver

2023-06-04 09:35 UTC, EvilDragonfiend requested changes
ghost only information should have a different colour so that they can notice the information is hidden in IC.

2023-06-04 15:24 UTC, Rukofamicom commented
I'm gonna have to put a key on this, I think the extra knowledge is far more liability than it's worth - observers will not be able to see actual action any sooner with this knowledge. 🔑

2023-06-05 00:32 UTC, Crossedfall commented
Seems like it'd be the root of a lot of future problems for little gain. Closing per the two-key rule.

2023-06-05 00:32 UTC, closed without merging