Gives the comms agent a megaphone
BeeStation/BeeStation-Hornet pull request #9225
Opened 2023-06-12 20:02 UTC by CydiaLamiales

## About The Pull Request
Gives the comms agent a megaphone.
Makes the megaphones have a defined cooldown.

## Why It's Good For The Game
Allows for communication agents to impersonate command staff.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Comms agent starting with a megaphone

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/505c6f91-af66-45a1-a4f9-ff366680e8af)

</details>

## Changelog
:cl:
add: Gave the Lavaland Comms Agent a megaphone with an increased cooldown
/:cl:

2023-06-12 23:39 UTC, Fronsis commented
I feel like i agree to what Bacon said on the other PR, the most annoying and spammer character below the clown is the syndie comms agent, while it might be good to impersonate from time to time a command officer i feel like the other 90% of the time it's going to be loud mode saying nonsense and compared to the VIP/Clown (who you can arrest and take it off them) you'll need a lot of preparation to assault that base, even if you specifically target their t-comms array with a bomb or something

Considering that they now have a higher spawn rate it's quite annoying to have an unfilterable spam of someone being ''rude and obnoxious'' and the reality is.. only a few of them do an actual good job of trying to cause chaos before resorting to bickering the general or sec comms

2023-06-13 04:24 UTC, CydiaLamiales commented
That's why get they get a version with a 30 second coolsown between messages, so they can't just spam it.

2023-06-15 19:01 UTC, Rukofamicom commented
Once every 30 seconds is still quite spammable

2023-06-29 04:39 UTC, EvilDragonfiend requested changes
* Megaphone should tell how much time you should wait to reuse that.
* Increase the cooldown time to between 90-120s, or even it should be longer than this.
* If you want to make it spammable in short period, charge version would work. (like it's charged for ever 2 minutes, and maximum charge is 5.) This would make the thing you want (impersonate a head) while not allowing them spamming this too much.
other method to recharge is that it can be fully recharged for every 10 minutes.

I wonder if you have ever seen my VIP gimmick. People get ear damage extremely when I say a lot of stuff in short time in loudmode.. I like comms agent being annoying, but they shouldn't disrupt the radio every 30 seconds. it's still too short.

2023-06-29 14:08 UTC, Rukofamicom commented
5 charges, two minutes per charge seems like a nice balance between good impersonation and spam prevention.

I don't believe the cooldowns or charges need to be readily visible to the player though. I even think it would be better if they had a permanent burnout function like security masks if overused, with a vague warning message when close. (This is not a requested change, just some thoughts)

2023-07-24 20:06 UTC, Rukofamicom approved these changes

2023-07-25 10:18 UTC, EvilDragonfiend requested changes
I believe these two reviews are enough to tell what I am thinking. Ping me if you're not sure.

2023-07-25 10:18 UTC, EvilDragonfiend commented on code/game/objects/items/devices/megaphone.dm
> +	var/available_charges = 5
```suggestion
	var/list/charges_list = list()
	var/maximum_charge = 5
```
make it like this.

2023-07-25 10:18 UTC, EvilDragonfiend commented on code/game/objects/items/devices/megaphone.dm
> +	available_charges = charges
```suggestion
	var/current_index = 0
	while(++current_index < length(charges_list))
		if(charges_list[current_index] < world.time)
			charges_list.Remove(current_index)
			current_index--
```

2023-07-25 10:30 UTC, EvilDragonfiend requested changes

2023-07-25 10:30 UTC, EvilDragonfiend commented on code/game/objects/items/devices/megaphone.dm
> +			I++
```suggestion
	if(length(charges_list) < maximum_charge)
		charges_list.Add(world.time + cooldown)
```

2023-07-25 11:02 UTC, EvilDragonfiend requested changes

2023-07-25 11:02 UTC, EvilDragonfiend commented on code/game/objects/items/devices/megaphone.dm
> +			charges_list.Remove(current_index)
```suggestion
			charges_list.Cut(current_index, current_index+1)
```

2023-07-25 11:11 UTC, EvilDragonfiend approved these changes
Maybe `addtimer()` would have been better but I am not sure which one is expensive. I will just merge it anyway.

2023-07-25 11:27 UTC, merged