Be Polite! No pushing on walk intent
BeeStation/BeeStation-Hornet pull request #9248
Opened 2023-06-17 08:38 UTC by Tsar-Salat

Ports:
- https://github.com/tgstation/tgstation/pull/68493

## About The Pull Request

When on walk intent, you wont push or displace people when moving towards them.

## Why It's Good For The Game

Saw this PR a while back on TG, thought it would be cool to implement here, building on the idea of #8371 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: RKz, Guillaume Prata
tweak: Be Polite! Walk intent prevents you from displacing or moving mobs when moving towards them
/:cl:

2023-06-17 09:02 UTC, bluezorua commented
isn't the point of help intent that you swap places with someone?

2023-06-17 11:20 UTC, Rustyfoxb commented
If you don't want to swap places with folks just use any other intent, this would make it really annoying since now all intents block the movement of someone or something trying to walk in the same direction you are

2023-06-17 11:42 UTC, Tsar-Salat commented
> this would make it really annoying since now all intents block the movement of someone or something trying to walk in the same direction you are

I don't get it. This doesn't change the 4 intents at all. This just makes it so if you run, you push past people, and if you walk, you don't. 

It doesn't "block the movement of someone" or affect other people pushing past you, it strictly affects how you yourself move.

2023-06-18 10:46 UTC, LodedDiper69 commented
Why do coders hate running? Thats bad for RP because????

2023-06-18 10:54 UTC, Tsar-Salat commented
> Why do coders hate running? Thats bad for RP because????

This doesnt affect running. Running remains unchanged. This just makes walking more situationally useful.

2023-06-29 04:26 UTC, EvilDragonfiend requested changes
My personal preference for this is that you should invoke a do_after(2 seconds) and then walk onto the tile that's occupied rather than this. (I personally tried this, but do_after is a bit glitchy, meh.)
it's because you should lay down first and raise up, and it takes time.

2023-06-29 04:43 UTC, Tsar-Salat commented
> My personal preference for this is that you should invoke a do_after(2 seconds) and then walk onto the tile that's occupied rather than thi

So like a "John Greytide carefully walks by (occupier)!" ?

Would this include some sort of animation as they move by? Should there be some kind of HUD alert for someone very obviously starting the do_after?

> (I personally tried this, but do_after is a bit glitchy, meh. implementing it as my suggested idea can be challenging.)


Tbh I would rather not get too advanced with this, right now it's just 2 lines of code, fulfilling a really minute usecase. Walking has exactly 1 single mechanical impact besides slower movespeed, in that you just don't slip on water. 2 seconds is kinda a short period, Doctors assisting in surgery could still bump by accident.

I feel like if someone needs to get somewhere and needs to go through people, they aren't going to bother engaging with the do_after. I personally like segregating walking into being "I'm very aware of my surroundings and the people around me", and running into "I'm going fast"




> it's because you should lay down first and raise up, and it takes time.

Is this a scenario with an immovable person or group of people? Personally I would just keep that as a manual crawl like it is now

Really interesting idea though! Tell me if you have any other ideas. I feel like walking is really underutilized in our coderbase

2023-07-16 18:37 UTC, Rukofamicom commented
Not that many people walk in the first place but this will only discourage using it even further, won't it?

If I am on walk and someone else is on run can they swap with me?

2023-07-17 02:52 UTC, Tsar-Salat commented
> Not that many people walk in the first place but this will only discourage using it even further, won't it?

This is a leading question, not really sure why you are pushing it this way, but I'll answer honestly.

No, its not going to discourage using it even further. The point is to give a simple mechanical usage to a grossly underutilized feature.
As I said before, walking has a single usecase, which is poor design. Either it should be removed, or we should seek to bolster it and give it additional purpose.

> If I am on walk and someone else is on run can they swap with me?
Yes.

2023-07-17 02:59 UTC, Rukofamicom commented
Either it should be removed, or we should seek to bolster it and give it additional purpose.

Its purpose should be default move speed and sprinting should cost stamina

2023-07-17 03:01 UTC, Tsar-Salat commented
> Either it should be removed, or we should seek to bolster it and give it additional purpose.

Yes. Directly relevant to this pr.

I dont understand what you are trying to get out of my two line pr.

2023-07-17 03:06 UTC, Rukofamicom commented
> I dont understand what you are trying to get out of my two line pr.

I'm trying to understand why you think, by itself, this is an improvement when it might actively discourage the very few people who currently walk from doing so.

It will make me less likely to stick to walking speed as I have to toggle to move around people now.

2023-07-17 03:07 UTC, Tsar-Salat commented
> Its purpose should be default move speed and sprinting should cost stamina imo

That is the natural evolution, yes.

When that comes to pass, we can certainly modify this further to displace people in a way consistent with someone barreling through the hallway and pushing past you.

2023-07-17 03:09 UTC, Rukofamicom commented
🔑 

Any change that is reliant on a future PR that may not exist for months or years is not worth adding until the mythical future PR is also here.

By itself this PR only makes the game worse, albeit slightly so.

2023-07-17 03:10 UTC, Tsar-Salat commented
> It will make me less likely to stick to walking speed as I have to toggle to move around people now. I've never seen the swap as anything other than shuffling past each other.

alright, i think ive written about the do_after interruptions and being careful in the workplace enough, im not really interested in pursuing this if thats not going to be addressed at all

2023-07-17 03:11 UTC, closed without merging