Forces cooldowns on martial arts items
BeeStation/BeeStation-Hornet pull request #9301
Opened 2023-06-24 15:19 UTC by PowerfulBacon

## About The Pull Request

Martial arts will now force click cooldowns, preventing them from being sped up when combined with gloves of the north star or the DNA vault attack speed improvements.

## Why It's Good For The Game

This combo is incredibly powerful and impossible to deal with, these items were not made with the idea of them being combined since sleeping carp gives you insanely high damage per attack and north star gives you almost no attack cooldown and aimlock.
Note that you will still get the aimlock from north star gloves when combined with sleeping carp, but not 0 cooldown.

## Testing Photographs and Procedure

## Changelog
:cl:
balance: Martial art attacks now force a click cooldown which cannot be overriden by gloves of the north star. (No more gloves of the north star + sleeping carp combo)
/:cl:

2023-06-24 16:30 UTC, EvilDragonfiend commented
I think it shouldn't cooldown clicks. martial arts activation should have the cooldown.

2023-06-24 18:44 UTC, PowerfulBacon commented
I did that originally but I thought that makes a lot less sense, since you can perform an action and have no idea which ones registered due to the fact you need to chain them together. Click cooldowns are a much better solution.

2023-06-24 23:04 UTC, Rukofamicom commented
Won't this pretty much cause the gloves to always fail to function as intended if someone knows martial arts? 

1. Equip gloves
2. Try to attack in harm intent repeatedly
3. Every martial art has at least one combo that starts with harm intent, resulting in a full click cooldown after every swing. 

I want to see further testing evidence that shows this isn't the case, or else this needs a different approach, such as the gloves temporarily disabling martial arts while equipped.

2023-06-25 07:32 UTC, PowerfulBacon commented
Yes, this is the case

2023-06-25 12:41 UTC, Rukofamicom requested changes
I agree the gloves should not work with martial arts, but the gloves should not entirely fail to function just because someone knows martial arts.

This needs a different implementation where the gloves prevent martial arts rather than martial arts preventing the gloves.

2023-06-29 04:22 UTC, EvilDragonfiend commented
maybe the harm intent should be only allowed to have this feature

2023-07-03 18:24 UTC, closed without merging