Admins without R_ADMIN perm are sorted in another section in staff_who
BeeStation/BeeStation-Hornet pull request #9321
Opened 2023-06-30 04:36 UTC by EvilDragonfiend

## About The Pull Request
Admins without R_ADMIN perm are sorted in another section in staff_who
See the test evidence

## Why It's Good For The Game
some people think I can handle tickets

## Testing Photographs and Procedure

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/857e49ad-4ce9-4ade-981f-392426d7bc26)

## Changelog
:cl:
admin: Admins without R_ADMIN perm are sorted in another section in staff_who, so that people will not believe coders can handle adminhelps.
/:cl:

2023-06-30 04:37 UTC, EvilDragonfiend commented
Another idea:
* Make another flag `R_NOT_ADMIN`, and give it to headcoder and coders?

2023-06-30 05:46 UTC, Ivniinvi commented on code/modules/client/verbs/who.dm
> +			msg += "\t(Note: non-admin staffs can't handle adminhelp tickets.)\n"
```suggestion
			msg += "\t(Note: non-admin staff are unable to handle adminhelp tickets.)\n"
```

2023-06-30 05:47 UTC, EvilDragonfiend commented
thanks for the grammar correction lol

2023-06-30 11:38 UTC, WrillWasTaken commented
Wouldn't it be better to have a coder/maintainer category? This seems unclear, mentors are technically non-admin staff who can't handle tickets too.

2023-06-30 12:22 UTC, EvilDragonfiend commented
> Wouldn't it be better to have a coder/maintainer category? This seems unclear, mentors are technically non-admin staff who can't handle tickets too.

unlike how mentor works, maintainers get 'debug' permission from admin datum, and doing as you suggested needs greater work.

2023-06-30 15:35 UTC, Crossedfall commented
> and doing as you suggested needs greater work.

Not really. They're suggesting that you use a different name for the grouping. I'm inclined to agree with them that the current naming is confusing.

2023-06-30 16:01 UTC, EvilDragonfiend commented
> > and doing as you suggested needs greater work.
> 
> Not really. They're suggesting that you use a different name for the grouping. I'm inclined to agree with them, the current naming is confusing.

the most issue is that the only condition is if you have R_ADMIN or not in admin group. mentors aren't in GLOB.admin, and they're in GLOB.mentors so they're fine with this issue, but coders are mixed within GLOB.admin.

2023-07-01 21:21 UTC, Rukofamicom requested changes

2023-07-01 21:21 UTC, Rukofamicom commented on code/modules/client/verbs/who.dm
> +			msg += "<b>Current Non-admin staffs:</b>\n"
```suggestion
			msg += "<b>Other Staff:</b>\n"
```

2023-07-01 21:24 UTC, Rukofamicom commented on code/modules/client/verbs/who.dm
> +			msg += "<b>Current Non-admin staffs:</b>\n"
Currently there are only three branches of staff: 
* Admin Team
* Coding Team
* Mentor Team

There's no reason to label this as "non-admin staff" separate from mentors. It contains exclusively maintainers and one head coder.

2023-07-02 23:38 UTC, Rukofamicom approved these changes
Looks good to me now

2023-07-22 02:40 UTC, itsmeow commented on code/modules/client/verbs/who.dm
> +			msg += "\t(Note: non-admin staff are unable to handle adminhelp tickets.)\n"
```suggestion
			msg += "\t<span class='info'>Non-admin staff are unable to handle adminhelp tickets</span>\n"
```

2023-07-22 03:16 UTC, itsmeow approved these changes

2023-07-22 03:46 UTC, merged