[PORT] Brings UpdatePaths uptodate
BeeStation/BeeStation-Hornet pull request #9338
Opened 2023-07-04 23:46 UTC by mystery3525

## About The Pull Request

Ports the following:
- https://github.com/tgstation/tgstation/pull/75892
- https://github.com/tgstation/tgstation/pull/70806
- https://github.com/tgstation/tgstation/pull/68436
- https://github.com/tgstation/tgstation/pull/67489
- https://github.com/tgstation/tgstation/pull/67241 (in principle)
- https://github.com/tgstation/tgstation/pull/66916
- https://github.com/tgstation/tgstation/pull/66506
- https://github.com/tgstation/tgstation/pull/66469
- https://github.com/tgstation/tgstation/pull/62595
- https://github.com/tgstation/tgstation/pull/56573 (one line change)

Various fixes and improvements to update paths over the years, gives us really good tooling for massive refactors and ports.

## Why It's Good For The Game

This allows us to do a wide variety of changes to all maps, all at once, instead of having to manually map change for simple repaths, etc. Also fixes UpdatePaths as it didn't work at all before.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
not really sure how I can test this?

</details>

## Changelog
:cl: AnturK, esainane, MrMelbert, Son-of-Space, san7890, Ghommie, ported by mystery3525
fix: Various fixes to the UpdatePaths tool
fix: UpdatePaths will now handle lists that contain strings.
code: Adds support for simple subtype repathing, outright deletion,  for UpdatePaths scripts
code: Orginizes UpdatePaths folder and adds a well-documented readme.md
/:cl:

2023-07-04 23:52 UTC, Tsar-Salat commented
oh thank god

2023-07-04 23:56 UTC, mystery3525 commented
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/30960302/9d3fb48d-7209-4ab1-9927-4cac252cb142)

2023-07-05 06:32 UTC, itsmeow commented on tools/mapmerge2/dmm.py
> +        with open(fname, 'w', newline='\r\n', encoding=ENCODING) as f:
why?

2023-07-05 12:20 UTC, mystery3525 commented on tools/mapmerge2/dmm.py
> +        with open(fname, 'w', newline='\r\n', encoding=ENCODING) as f:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/30960302/d40186e0-28b5-445e-b28f-938b2b0ae1bf)


![image](https://github.com/BeeStation/BeeStation-Hornet/assets/30960302/eb4e2ab0-2ea5-4bcc-a490-7a3426ce78db)

2023-07-05 12:20 UTC, mystery3525 commented on tools/mapmerge2/dmm.py
> +        with open(fname, 'w', newline='\r\n', encoding=ENCODING) as f:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/30960302/489bab91-1eaa-497b-accb-c1f7723ba350)

2023-07-06 15:29 UTC, itsmeow approved these changes

2023-07-22 03:47 UTC, itsmeow commented
@Crossedfall

2023-08-10 23:32 UTC, Crossedfall requested changes
Wow, this file is pretty terrible. For the most part your changes look fine, I made some minor suggestions. We should probably look at normalizing *.dmm files. I don't recall why we skipped those.

2023-08-10 23:32 UTC, Crossedfall commented on tools/UpdatePaths/__main__.py
> +                out = path_start + match.group('subtype')
```suggestion
                path_start = new_path[ :-len("/@SUBTYPES")]
                out = path_start + match.group("subtype")
```

2023-08-10 23:32 UTC, Crossedfall commented on tools/UpdatePaths/__main__.py
> +        new_value = tuple(y for x in def_value for y in get_result(x) if y != None)
```suggestion
        new_value = tuple(y for x in def_value for y in get_result(x) if y is not None)
```

2023-08-10 23:32 UTC, Crossedfall commented on tools/mapmerge2/dmm.py
> +        with open(fname, 'w', newline='\r\n', encoding=ENCODING) as f:
Mmm, I don't like this, but it's something we can fix in a separate PR.

2023-08-10 23:32 UTC, Crossedfall commented on tools/mapmerge2/dmm.py
> +            del self.dictionary[key]
```suggestion
        for key in unused_keys:
            self.dictionary.pop(key, None)
```

This is safer and a bit faster

2023-08-21 00:55 UTC, Crossedfall approved these changes

2023-08-21 01:10 UTC, merged