Sets a hard minimum population for Incursion.
BeeStation/BeeStation-Hornet pull request #9344
Opened 2023-07-06 06:16 UTC by Absolucy

## About The Pull Request

Sets the hard minimum popcount of dynamic Incursion to 24 - just like blood and clock cult.

## Why It's Good For The Game

lowpop incursion sucks ass.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
tweak: Incursion now requires a hard minimum of 24 people to roll.
/:cl:

2023-07-06 06:28 UTC, PowerfulBacon commented
I think the algorithm that determines how big the teams should be also changed with dynamic, but I'm not sure. the teams seem way bigger than they used to be

2023-07-06 06:41 UTC, PowerfulBacon requested changes
The minimum players should be 22 like the gamemode and the antag spawn rates need to be fixed.
This is how they look with and without dynamic.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/e0c2ad12-e64f-4f6e-84dd-5a969dbf527e)

Changing denominator to be 26 will give you this instead
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/4d6253d9-b269-4cd3-9862-43e886b6fbdf)
Which is much closer to the original

2023-07-06 06:41 UTC, PowerfulBacon commented on code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
> +	minimum_players = 24
```suggestion
	antag_cap = list("denominator" = 26, "offset" = 1)
	minimum_players = 22
```

2023-07-06 06:42 UTC, PowerfulBacon approved these changes
Add changes to CL and its good

2023-07-06 06:44 UTC, Absolucy commented
done.,

2023-07-22 03:47 UTC, itsmeow approved these changes
Good denominator change

2023-07-22 04:05 UTC, merged