Buffs the Poisoned Knife
BeeStation/BeeStation-Hornet pull request #9398
Opened 2023-07-12 20:44 UTC by CydiaLamiales

## About The Pull Request
Buffs the poisoned Knife by decreasing its TC cost and increasing it's reagent transfer amount to 5, 10 or 20.

## Why It's Good For The Game
The poisoned combat knife barely sees any use due to it being an extremely subpar tool for injecting chemicals. Partially because it's heavily overshadowed by the sleepy pen, but that's another issue.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/b7a47e96-2ae8-4ea6-a9ee-796a7ee65379)
This PR aims to make the knife a more appealing option for the traitors who wish to engage in chemical warfare.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/ff3f50b6-75ab-47d8-b2d6-c205607e3ca0

</details>

## Changelog
:cl:
balance: Decreased the price of the Poisoned Knife from 8 TC to 6
balance: Increased the maximum amount of reagents the poisoned knife can transfer per hit to 20
/:cl:

2023-07-12 22:21 UTC, Rukofamicom reviewed
Aside from typo looks good. 20u is kind of a lot, but it's still only half the capacity of sleepy pen and in a much less conspicuous package.

2023-07-12 22:21 UTC, Rukofamicom commented on code/modules/uplink/uplink_items.dm
> +	desc = "A knife that is made of two razor sharp blades, it has a secret compartment in the handle to store liquids which are injected when stabbing something. Can hold up to fourty units of reagents
```suggestion
	desc = "A knife that is made of two razor sharp blades, it has a secret compartment in the handle to store liquids which are injected when stabbing something. Can hold up to forty units of reagents but comes empty."
```

2023-07-12 22:53 UTC, DarnTheMarn commented
The poisoned knife is still pretty bad after this tbh. Why spend any amount of TC on the knife when you can easily grab a syringe gun from medbay, load up a normal syringe, and have the ability to shoot chemicals at range while only losing out on 5u capacity? If the knife is AP, I'm not sure if it is, then you lose out on 10u if you use piercing syringes. Another problem with the knife is that it outs you as 100% being a traitor/excom/incursion/antag unlike a normal syringe gun.

2023-07-13 03:58 UTC, Rukofamicom commented
An item being somewhat better does not invalidate the poison knife.

Syringe gun is better at deploying reagents specifically, but the poison knife is a hybrid tool that is both a decent pure damage weapon and also capable of delivering reagents even against protected targets.

2023-07-13 04:06 UTC, CydiaLamiales commented
> The item flavor and versatility mentioned above both made the poison knife probably my favorite reagent tool.

It can only transfer five reagents per hit. It costs the same 8 TC as an esword, and comes empty. The pen is so much better than this it's not even funny,

2023-07-13 04:31 UTC, Rukofamicom commented
The pen is yes.
Syringe gun no.

2023-07-13 06:07 UTC, Fronsis commented
> The pen is yes. Syringe gun no.
> 
> I'd still take knife over sleepy pen just for flavor currently though, it's just a much cooler item.

It also has a different aproach than the sleepy pen/syringe gun, if you start slashing someone they would react differently, play more cautious, stay away, etc giving you more chances to take the upperhand on the scenario and if that fails you can retreat and if they  decide to chase you it's just a matter of time until the person that blindly chased you succumbs/gets slowed in front of you allowing you to have an advantage or they can retreat knowing they've been poisoned, seems like a very good buff and it would be nice to start seeing this more rather than funny ''you feel a tiny prick''

2023-07-14 11:53 UTC, Rukofamicom approved these changes

2023-07-15 12:46 UTC, Isy232 commented
I'd want the knife down to 5 TC like sleepy pen is/was.

2023-07-15 12:48 UTC, CydiaLamiales commented
> I'd want the knife down to 5 TC like sleepy pen is/was.

Why? It costs 1 more because it's reusable and does some damage on its own.

2023-07-15 13:37 UTC, Isy232 commented
> Why? It costs 1 more because it's reusable and does some damage on its own.

The damage on its own isn't very significant, 15 damage melee weapons are plentiful on the station.
Damaging in the same hit as injecting is good, but not amazing.
If you consider the sleepy pen used to be 5 TC, 45u, refillable and stealthy this poisoned knife is a lot worse.

I agree the old sleepy pen was too powerful, however the current proposed buffed poison knife is still too much of a downgrade from what the sleepy pen used to be.
The poison knife doesn't come with reagents, requiring purchasing the 7 TC poison kit or mixing your own which eats up a significant amount of the limited time you have in a round.

If you'd consider decreasing the cost of the poison kit to 4 TC so combined these cost 10 TC instead of a massive 13 TC that'd also be fine.

2023-07-15 22:20 UTC, Rukofamicom commented
> I agree the old sleepy pen was too powerful, however the current proposed buffed poison knife is still too much of a downgrade from what the sleepy pen used to be.

Nothing should be on par with what the sleepy-pen was before the recent nerf.

This is a pretty big buff to the knife, and I have some mild concerns that 20u will prove to be too much to inject in one click.

2023-07-15 22:34 UTC, DarnTheMarn commented
What is the attack text for the poisoned knife? Making it the same as a normal knife would make it a bit more stealthy but not too stealthy since if you get busted people can plainly see its a traitor knife.

2023-07-16 03:55 UTC, CydiaLamiales commented
> What is the attack text for the poisoned knife? Making it the same as a normal knife would make it a bit more stealthy but not too stealthy since if you get busted people can plainly see its a traitor knife.

The attack messages already are the same as a normal knife.

2023-07-16 04:06 UTC, Rukofamicom commented
While the same attack text is used, the poisoned knife does not have a covert name so it cannot pass as any other kind of knife after being seen attacking with it.

I don't think this is an issue for the record, just pointing out that it isn't entirely accurate to say it has the same attack text.

2023-07-21 21:09 UTC, Archanial requested changes

2023-07-21 21:09 UTC, Archanial commented on code/game/objects/items/kitchen.dm
> +	possible_transfer_amounts = list(5,10,20)
```suggestion
	possible_transfer_amounts = list(5, 10, 20)
```

2023-07-21 21:09 UTC, Archanial commented on code/game/objects/items/kitchen.dm
> +	var/amount_per_transfer_from_this = 20
20 is too much in my opinion. I'd reduce TC cost further and keep it at 10.
20 means you would transfer the entire amount in just 2 hits, which is too quick.

2023-07-30 19:52 UTC, Archanial approved these changes
cool :sunglasses:

2023-07-30 20:04 UTC, merged