Patched up the jank of LOOC
BeeStation/BeeStation-Hornet pull request #9407
Opened 2023-07-14 20:45 UTC by Absolucy

## About The Pull Request

This patches up jankiness with LOOC, such as mobs inside containers (lockers, split personalities, recalled holoparas, etc etc) being unable to hear or talk on LOOC, and observers also being completely unable to hear LOOC.

## Why It's Good For The Game

jank bad. work good.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![23-07-14-1689367359-dreamseeker](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/d6bc4d6b-9381-4d61-94c9-8ab226e64383)

</details>

## Changelog
:cl:
fix: LOOC is much less janky now. You can properly both talk on and hear LOOC while in a locker or something, now!
/:cl:

2023-07-14 20:47 UTC, CydiaLamiales commented
Does this fix certain mobs like xenos not being able to use LOOC at all?

2023-07-14 20:48 UTC, Absolucy commented
Hm, I didn't know that was an issue at all. I'll have to test that.

2023-07-14 21:16 UTC, itsmeow commented
Ghosts should not be able to LOOC with living players unless they are adminned.

2023-07-14 21:35 UTC, Absolucy commented on code/modules/client/verbs/looc.dm
> +			return
@itsmeow non-admin ghosts still can't talk over LOOC, it's just that this allows them to _hear_ LOOC

2023-07-15 00:45 UTC, itsmeow approved these changes
Does what it says

2023-07-18 01:33 UTC, EvilDragonfiend commented
It's the actual linter failure. Fix that.

2023-07-18 09:27 UTC, PowerfulBacon requested changes

2023-07-18 09:27 UTC, PowerfulBacon commented on code/modules/client/verbs/looc.dm
> +	if(is_banned_from(mob.ckey, "OOC"))
Use a define for ooc bans here

2023-07-18 09:27 UTC, PowerfulBacon commented on code/modules/client/verbs/looc.dm
> +	for(var/atom/movable/thingymajig in view(get_turf(mob)))
Use appropriate variable names which give information about what is being targeted by this list

2023-07-18 09:27 UTC, PowerfulBacon commented on code/modules/client/verbs/looc.dm
> +	for(var/atom/movable/thingymajig in view(get_turf(mob)))
Would it be quicker to loop through all clients and check their distance rather than recursively check all atoms in view?

2023-07-27 17:37 UTC, PowerfulBacon approved these changes
I am fine with this, but looking at it again the define should either be not used or used fully across the SQL banning system although that could cause inconsistencies

2023-07-27 17:41 UTC, itsmeow commented
There's only two cases where OOC bans are directly checked, the banning menu has it hardcoded. I'd say it should just be in a bigger refactor

2023-07-31 20:14 UTC, merged