Slime potion QoL + fixes
BeeStation/BeeStation-Hornet pull request #9429
Opened 2023-07-18 02:32 UTC by Absolucy

## About The Pull Request

This does some QoL changes and fixes to some slime potions:

### General Changes

- Cleaned up the code a bit, getting rid of a bunch of single-letter variable names in exchange for more descriptive names.
- Cleaned up to_chat/visible_messages a bit.

### Renaming Potion

- You can now rename mobs yourself if they have no mind or player in control.
- Added feedback messages as to why a rename failed (chose to not rename, target died, name forbidden by filter, target moved away from you, etc).
- Trying to offer a renaming potion to a player mob with a disconnected or AFK client will not use the potion, and tell you to try again later.
- Renaming times out after 2 minutes.

### Speed Potions

- You can no longer waste potions on something that has no slowdown anyways.
- Using a speed potion on something that isn't an item or vehicle will just normally interact with it - allowing you to now properly place the potions on tables or in lockers, for example.

### Bluespace Radio Potions

- You can now use radio potions on unconscious (but not dead) mobs.

## Why It's Good For The Game

- it is _not_ fun to waste a slime speed potion by trying to put it down on a table, or using it on something without slowdown anyways.
- you should be able to rename playerless+mindless mobs
- it's nice for renaming potions to have better feedback on why nothing happened
- tgui input good

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![23-07-17-1689646866-dreamseeker](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/f08341f5-5dc7-48ee-98a5-319f351638ba)
![23-07-17-1689646883](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/1410bcda-e529-4374-afa9-aadd50c977e4)
![23-07-17-1689646934-dreamseeker](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/3c0a8447-8322-4b1e-8290-9cedb4c497ea)
![23-07-17-1689646919](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/de5c300d-ad21-4547-afef-2fd3c41300d4)
![23-07-17-1689646968-dreamseeker](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/ecc2574a-2ec4-473f-be26-81bf874535d4)
![23-07-17-1689646983-dreamseeker](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/d0461a61-c137-4a08-b74e-55870052e2cc)

</details>

## Changelog
:cl:
fix: You can now properly place slime speed potions on tables, in lockers, etc.
tweak: Using a slime speed potion on something that has no slowdown in the first place will no longer waste it.
add: Slime renaming potions will now offer better feedback as to why a rename didn't occur.
add: Slime renaming potions now let you rename playerless, mindless mobs.
tweak: Slime renaming potion prompts now use tgui input.
tweak: Slime renaming potion prompts now time out after 2 minutes, so you can't just deadlock the potion forever.
tweak: Offering a slime speed potion to a player mob whose client is either disconnected or AFK will just tell you to try again later.
/:cl:

2023-07-22 07:06 UTC, PowerfulBacon requested changes

2023-07-22 07:06 UTC, PowerfulBacon commented on code/modules/research/xenobiology/xenobiology.dm
> +	target.fully_replace_character_name(newname = new_name)
Add a message_admins thing here

2023-07-30 19:52 UTC, Rukofamicom approved these changes

2023-07-31 20:03 UTC, itsmeow requested changes

2023-07-31 20:03 UTC, itsmeow commented on code/modules/research/xenobiology/xenobiology.dm
> +		"<span class='userdanger'><span class='name'>[user] starts to feed you [src]!</span>")
unclosed span

2023-08-05 09:11 UTC, PowerfulBacon approved these changes

2023-08-13 21:35 UTC, itsmeow approved these changes

2023-08-13 21:45 UTC, merged