Morph UI search + food digesting
BeeStation/BeeStation-Hornet pull request #9434
Opened 2023-07-18 11:09 UTC by Absolucy

## About The Pull Request

This adds a search bar to the morph stomach UI, and allows morphs to digest food items for small amounts of healing. Said healing is rather small, and is _capped_ - a morph can only heal 20% of its max health over the course of 2.5 minutes using food.

## Why It's Good For The Game

Searching through items is _very_ useful when you've eaten like 500 things.

Food digesting gives morphs a way to patch minor wounds without having to waste a monkey or station pet on it.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![23-07-18-1689678148](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/21ba4968-0f3d-46b8-a6ca-490dc2fccd60)

https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/77650c7a-211e-42cf-894d-c667f7c49842

</details>

## Changelog
:cl:
add: Added a search bar to the morph stomach UI.
add: Morphs can now digest food to recover small amounts of health, however this healing is capped - a morph can only recover up to 20% of its health over the course of 2.5 minutes by digesting food.
/:cl:

2023-07-19 05:00 UTC, itsmeow approved these changes

2023-07-22 04:02 UTC, itsmeow commented
Needs a search icon to make it more obvious
also wider search bar, it's super tiny

2023-07-31 19:31 UTC, itsmeow requested changes
above

2023-08-05 05:30 UTC, Absolucy commented
@itsmeow 
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/eda4ca35-2db4-4655-8a0d-6da21382a624)

2023-08-05 08:40 UTC, itsmeow commented on tgui/packages/tgui/interfaces/Morph.js
> +export const Morph = (_props, _context) => {
these are useless, why add them

2023-08-05 08:41 UTC, Absolucy commented on tgui/packages/tgui/interfaces/Morph.js
> +export const Morph = (_props, _context) => {
force of habit

2023-08-09 11:05 UTC, itsmeow approved these changes

2023-08-09 11:13 UTC, merged