DRAFT : fixes the Aurora Caelus event
BeeStation/BeeStation-Hornet pull request #9466
Opened 2023-07-20 11:50 UTC by CydiaLamiales

## About The Pull Request
Fixes the Aurora Caelus event by making it 

## Why It's Good For The Game
The event that's supposed to make starts shine on the station, actually gives light

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Sped up version : 

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/cc158d5c-66dd-4e70-8ff3-da07b269ab2b

</details>

## Changelog
:cl:
fix: Fixed the Aurora Caelus event not creating lights
code: added a global list of station windows
/:cl:

2023-07-20 17:13 UTC, TerryTehCoder commented
Hasn't this been broken for a loong time? I feel I've never actually seen what it was supposed to look like.

2023-07-20 17:18 UTC, CydiaLamiales commented
> Hasn't this been broken for a loong time? I feel I've never actually seen what it was supposed to look like.

It was, it creates a light with 3x the light radius of a previous light on a space tile... except space tiles never had any light to begin with, so it doesn't create one.

2023-07-20 23:44 UTC, EvilDragonfiend requested changes
This needs to include fake space tiles

2023-07-21 07:51 UTC, CydiaLamiales commented
Will add that when I get home

2023-07-21 11:46 UTC, EvilDragonfiend requested changes, later dismissed
This event is a bit heavy because it handles too many atoms, so that it should use ASYNC. I will tell you what you should do further once these change requests are addressed.

2023-07-21 11:46 UTC, EvilDragonfiend commented on code/modules/events/aurora_caelus.dm
> +				affected_turfs += T
this should be in a separate proc.

2023-07-21 11:46 UTC, EvilDragonfiend commented on code/modules/events/aurora_caelus.dm
> +
the whole codes in tick() here should be in a separate proc, and that proc should be called by ASYNC()

2023-07-21 11:46 UTC, EvilDragonfiend commented on code/modules/events/aurora_caelus.dm
> +				M.playsound_local(M, 'sound/ambience/aurora_caelus.ogg', 20, FALSE, pressure_affected = FALSE)
this should be in a separated proc too.

2023-08-25 07:09 UTC, PowerfulBacon commented
This will be depreciated by the starlight rework, do you want to keep the mood changes?

2023-08-25 07:11 UTC, CydiaLamiales commented
> This will be depreciated by the starlight rework, do you want to keep the mood changes?

Mood and color changes, yes.

2023-09-04 04:44 UTC, CydiaLamiales commented
Well, since Bacon basically "fixed" the event by adding starlight in another PR, this will instead just be a color tweak + mood addition.

2023-09-04 14:27 UTC, CydiaLamiales commented on code/game/turfs/turf.dm
> +
```suggestion
```

2023-09-04 14:27 UTC, CydiaLamiales commented on code/game/objects/structures/window.dm
>  	)
```suggestion
	)

```

2023-09-04 14:27 UTC, Rukofamicom approved these changes

2023-09-04 14:48 UTC, merged