Adds proper logging to emagged recycler crushing
BeeStation/BeeStation-Hornet pull request #9530
Opened 2023-07-27 14:19 UTC by Tyranicranger4

## About The Pull Request
Adds proper logging to someone being crushed by a recycler. Previously this was only really doable by checking for forced say logs triggered by a recycler crushing someone, which isn't ideal.

## Why It's Good For The Game
Ooooooh you want proper logging in your atmospheric simulator.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>
The "by nobody" line is due to admin proc calls and shouldn't happen under normal circumstances.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/80382633/a32f9f10-0ff4-4d23-8ecd-c3716cd6067c)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/80382633/42cb3606-7eef-41ba-9c4e-48973ba32487)

</details>

## Changelog
:cl:
admin: Adds logging for when people are crushed by an emagged recycler
/:cl:

2023-07-27 14:39 UTC, Rukofamicom approved these changes

2023-07-27 14:47 UTC, EvilDragonfiend requested changes

2023-07-27 14:47 UTC, EvilDragonfiend commented on code/game/machinery/recycler.dm
> +	L.log_message("has been crushed by a recycler that was emagged by [(emagged_by ? emagged_by : "nobody")]", LOG_ATTACK, color="red")
```suggestion
	L.log_message("has been crushed by a recycler that was emagged by [(emagged_by || "nobody")]", LOG_ATTACK, color="red")
```
`||` does the same behaviour. If left one is false or null, right one will be given.

2023-07-27 17:39 UTC, Rukofamicom commented on code/game/machinery/recycler.dm
> +	L.log_message("has been crushed by a recycler that was emagged by [(emagged_by ? emagged_by : "nobody")]", LOG_ATTACK, color="red")
? : is definitely the more frequent use case in our code right now, what is the benefit to using the other?

2023-07-28 08:06 UTC, EvilDragonfiend commented on code/game/machinery/recycler.dm
> +	L.log_message("has been crushed by a recycler that was emagged by [(emagged_by ? emagged_by : "nobody")]", LOG_ATTACK, color="red")
I believe my suggestion should be more standard, but not a big deal as the current version works anyway.
I will remain my suggestion anyway, but feel free to dismiss mine if you don't think it's that necessary (and it's true lol)

2023-07-29 03:19 UTC, Tyranicranger4 commented on code/game/machinery/recycler.dm
> +	L.log_message("has been crushed by a recycler that was emagged by [(emagged_by ? emagged_by : "nobody")]", LOG_ATTACK, color="red")
I don't really see a reason to change it unless there's a notable advantage for doing so.

2023-07-31 22:39 UTC, itsmeow commented on code/game/machinery/recycler.dm
> +	L.log_message("has been crushed by a recycler that was emagged by [(emagged_by ? emagged_by : "nobody")]", LOG_ATTACK, color="red")
This version is less verbose and should be the standard in this case. I'd say just commit it

2023-08-01 07:08 UTC, EvilDragonfiend approved these changes

2023-08-01 07:17 UTC, merged