Adds some admin tools relating to chemical grenades
BeeStation/BeeStation-Hornet pull request #9569
Opened 2023-08-01 01:28 UTC by Absolucy

## About The Pull Request

This adds some admin tools (read: a smite) relating to chemical grenades, allowing admins to permanently change what happens whenever a certain player uses a chemical grenade.
These changes are _undetectable_ until they actually try to set off a grenade, as the changes only occur during the actual grenade activation process.

In addition, these changes are 'sticky', and will apply to any grenades with the following criteria:
- Any grenades armed by the target user.
- Any grenades within the target user's contents at the time of smite.
- Any grenades that have been 'finished' by the target user.

The following grenade effects are available:
- **Nothing**: just makes the grenade do nothing and disappear whenever it's set off
- **Nothing (but it honks)**: same as Nothing... but it also does a clown honk whenever it disappears.
- **Marked Grenade**: the grenade copies the beakers from whatever grenade the admin had set as their marked datum (wiping out all other reagents in the grenade)
- **Cluwneify**: the target gets turned into a cluwne whenever the grenade gets set off.
- **Nugget**: the target gets nuggeted (or just gibbed if they're not a carbon) whenever the grenade gets set off
- **Colorful Reagent (Rainbow) Foam**: The contents of the grenade are replaced with colorful reagent foam, which has no effect other than randomly changing the colors of anything caught in said foam
- **Carpet Foam**: The contents of the grenade are replaced with carpet foam, which just makes the floor in the foam's area into nice-looking carpet.

## Why It's Good For The Game

hehe funny prank to waste griffman's time

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/ad00a6ba-3055-400c-9e74-7c6ba1d298ee

</details>

## Changelog
:cl:
admin: Adds some admin tools relating to chemical grenades.
/:cl:

2023-08-01 09:25 UTC, Tyranicranger4 commented
This is absolutely devious and I love it.

2023-08-01 09:29 UTC, Absolucy commented
@Tyranicranger4 I came up with this idea a while back, after I believe Megaddd manually replaced a griffer's grenades with colorful reagent foam... I just didn't code it til now. Credit them for the idea!

2023-08-07 20:41 UTC, JixS4v commented
You should make one where it sticks to their hand as if glued upon activation

2023-08-13 23:26 UTC, itsmeow requested changes
needs logging at explosion time if a sabotage was used as well, describing which sabotage and from what admin

2023-08-13 23:26 UTC, itsmeow commented on code/game/objects/items/grenades/chem_grenade.dm
> +	if(sabotage && !sabotage.Invoke(src))
the nothing grenade won't call the log_game or update_mob if you just qdel

2023-08-25 19:07 UTC, closed without merging