(No more invisible visible layer adaptors) "Don The Invisibility Adaptor"
BeeStation/BeeStation-Hornet pull request #9591
Opened 2023-08-03 15:21 UTC by HowToLoLu

## About The Pull Request

Apparently visible layer adaptors aren't actually visible... for at least the past 5 months.

## Why It's Good For The Game

Adaptors that say they're visible should be... you know- visible?

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

#### For the past 5 months:

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/b11c8b3f-5475-4baf-8b43-170d53ad5a2a)

#### One line of code later.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/50469919-f03b-46dd-8904-05072f8e060e)

</details>

## Changelog
:cl:
fix: Maps with Layer Adaptors that were meant to be above tiles are now actually above tiles.
/:cl:

2023-08-03 17:19 UTC, Tsar-Salat commented
> Apparently visible layer adaptors aren't actually visible... for at least the past 5 months.

Yes.

#8865 fixes it, but this works too.

2023-08-03 17:21 UTC, Tsar-Salat requested changes

2023-08-03 17:21 UTC, Tsar-Salat commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +	hide = 0
```suggestion
	hide = FALSE
```

Boolean false

2023-08-04 07:08 UTC, EvilDragonfiend approved these changes

2023-08-25 07:23 UTC, merged