Fix roundstart lighting not properly turning on
BeeStation/BeeStation-Hornet pull request #9593
Opened 2023-08-03 17:36 UTC by Absolucy

## About The Pull Request

So, turns out I should've been using `GLOB.areas`, because I don't _need_ sorted areas, plus `GLOB.sortedAreas` _usually hasn't been calculated at this point!_

## Why It's Good For The Game

bug fix 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![23-08-03-1691084091-dreamseeker](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/0d6c8e01-3b63-4c4d-992f-da09159af875)

</details>

## Changelog
:cl:
fix: Fixed roundstart lighting not properly turning on.
/:cl:

2023-08-04 07:09 UTC, EvilDragonfiend requested changes

2023-08-04 07:09 UTC, EvilDragonfiend commented on code/controllers/subsystem/ticker.dm
> -	for(var/area/area as() in typecache_filter_list(GLOB.sortedAreas, lightup_area_typecache))
is using `as()` necessary here..?

2023-08-05 02:54 UTC, itsmeow approved these changes

2023-08-05 04:03 UTC, EvilDragonfiend approved these changes

2023-08-05 04:12 UTC, merged