Adds an admin verb for turning all lights on or off
BeeStation/BeeStation-Hornet pull request #9609
Opened 2023-08-05 06:32 UTC by CydiaLamiales

## About The Pull Request
Adds an admin verb for turning all lights on or off

## Why It's Good For The Game
Allows for more adminbus + for easier local testing when messing around with lighting.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/d0802986-77ff-4aff-a06e-dd2162d92a65

</details>

## Changelog
:cl:
admin: Added a new verb for toggling all lights on or off, found in the Secrets panel
/:cl:

2023-08-05 07:02 UTC, EvilDragonfiend requested changes

2023-08-05 07:02 UTC, EvilDragonfiend commented on code/modules/admin/secrets.dm
> +			var/val = alert(usr, "Do you want to turn all lights on or off?", "Light Manipulation", "On", "Off")
the selection option should be 3: on, off, cancel.

2023-08-05 07:02 UTC, EvilDragonfiend commented on code/modules/admin/secrets.dm
> +					set_to = FALSE
put an early return for cancel option.

2023-08-05 07:50 UTC, EvilDragonfiend approved these changes

2023-08-05 08:05 UTC, itsmeow commented on code/modules/admin/secrets.dm
> +			switch(val)
The default case is not handled here

2023-08-05 19:51 UTC, Dejaku51 commented
just learn sdql smh

2023-08-06 13:35 UTC, itsmeow approved these changes

2023-08-06 13:45 UTC, merged