Adds a specific preference for AI VOX announcements
BeeStation/BeeStation-Hornet pull request #9689
Opened 2023-08-16 17:51 UTC by Absolucy

## About The Pull Request

This adds a specific preference for AI VOX announcements, allowing you to still hear normal announcement sounds, while ignoring AI TTS, or vice versa.

## Why It's Good For The Game

Because almost nothing of value is ever said over AI VOX, and I _don't want to hear it._

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Adds a specific preference to enable/disable AI VOX (text-to-speech) announcements.
/:cl:

2023-08-17 06:39 UTC, itsmeow approved these changes
Huh, I didn't know that the sound_announcement pref disabled this already. Guess that makes sense. It definitely should be separate though.

2023-08-17 09:38 UTC, Absolucy commented
@Fronsis Default for all toggles (unless otherwise specified for a specific one) is enabled 👍🏻

2023-08-18 02:49 UTC, EvilDragonfiend requested changes, later dismissed
This should display a vox text when it's disabled.
Also, If a person is deaf, the text should not be displayed in the chat.

2023-08-18 05:30 UTC, itsmeow commented
VOX text is unreliable since many VOX does meta stuff like `scensor` or `voxtest`. This is out of scope

2023-08-19 00:38 UTC, Rukofamicom commented
The **only** reason I don't disagree with this being out of scope is the fact players can currently turn this off anyway. 

VOX should absolutely go to text if this is disabled.

2023-08-19 00:39 UTC, Rukofamicom approved these changes
While this does highlight what I consider to be a major oversight, I do agree this is an improvement over current preferences.

2023-08-20 10:30 UTC, merged