Click cooldown refactor
BeeStation/BeeStation-Hornet pull request #9690
Opened 2023-08-16 18:16 UTC by PowerfulBacon

## About The Pull Request

Refactors click cooldowns to have a lot more versatility. This makes it significantly easier to increase the action cooldown during the attack chain since you don't have to figure out a way to apply it after the initial cooldown is applied.
This also allows you to add cooldowns which won't be overriden by certain sources, for example mech attacks won't be sped up by a mob having a higher action speed modifier for their user actions.

## Why It's Good For The Game

See above. Needed for other code projects I am working on.

## Testing Photographs and Procedure

Tested regular attacking, toy guardians being fast and gloves of the north star being fast.

See unit test results for proof of all of the functions working.

https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/1840396a-35b5-4a0b-923f-821d1c8ee833

## Changelog
:cl:
code: Click cooldown refactoring.
/:cl:

2023-09-08 15:29 UTC, itsmeow commented on code/__DEFINES/cooldown.dm
> +#define CD_GROUP_TELEKENISIS 2	// Telekenetic actions
```suggestion
#define CD_GROUP_TELEKINESIS 2	// Telekinetic actions
```

2023-11-06 12:44 UTC, Rukofamicom requested changes
Fix merge conflict and commit Kat's change, then will merge.

2023-11-06 13:23 UTC, PowerfulBacon commented
Conflicts resolved, worked in testing. Wasn't able to properly test holoparasites due to requiring 2 people and having no easilly accessible debugging tools that I could find in VV

2023-11-06 18:28 UTC, Rukofamicom approved these changes
I'm sure we'll hear about it soon if holopara breaks lol

2023-11-06 18:45 UTC, Rukofamicom commented
Ah rip lol

2023-11-06 18:47 UTC, PowerfulBacon commented
This will need a proper deconflict since it moved a CD cooldown to another place.

2023-12-19 11:49 UTC, itsmeow commented
```
code/game/turfs/turf_integrity.dm, line 190, column 6:
error: undefined proc: "changeNext_move" on /mob/living

code/game/turfs/turf_integrity.dm, line 278, column 6:
error: undefined proc: "changeNext_move" on /mob
```

2024-02-16 12:35 UTC, Rukofamicom commented
coming up on two months conflicted now

2024-02-22 00:18 UTC, closed without merging