AFK players now show up as SSD on examine (+ soft ping port)
BeeStation/BeeStation-Hornet pull request #9705
Opened 2023-08-18 20:13 UTC by Absolucy

## About The Pull Request

This makes it so that AFK players will appear as SSD. The amount of time that it'll take for this message to show up is configurable per-player.

Although perhaps a different message could be shown for AFK players as opposed to SSD players? I'm open to suggestions, I'm not that good at coming up with flavor text.

Also ports https://github.com/tgstation/tgstation/pull/66299, which fixes inactivity/`is_afk` not working, as uh, that kinda needs to work for this.

## Why It's Good For The Game

Makes it less likely for me to be killed when I'm AFK (but not disconnected) because I had to go use the bathroom or do some chores, due to someone not being able to tell I'm AFK when examining me.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

## Soft-ping
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/d8d89bb3-987b-4467-b60f-7c634f20750f)

## AFK examine (+ working `is_afk`)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/65794972/28fc2407-abbe-431b-9fed-e3a5e76eb8f8)

</details>

## Changelog
:cl: Absolucy, ninjanomnom
add: AFK players will now have flavor text indicating that they're AFK when examined.
fix: AFK detection now works properly again.
/:cl:

2023-08-18 20:51 UTC, PowerfulBacon commented
Why would we want to let players adjust how long until they are registered as being AFK? This should be a config setting and set entirely by the server.

2023-08-18 20:52 UTC, Absolucy commented
Ah, fair. I'm not sure why I thought of that.

Should it be a separate config option or just the `INACTIVITY_PERIOD` config?

2023-08-18 20:53 UTC, PowerfulBacon commented
oh yea, inactivity period is probably fine

2023-08-18 21:36 UTC, Absolucy commented
Aight, I changed it to just use the default `is_afk` arguments, which is the inactivity period configured by the server.

2023-08-30 11:10 UTC, itsmeow commented
This should also show on MedHUDs

2023-09-04 00:54 UTC, Absolucy commented
@itsmeow like as in the "dead, distant soul" medhud?

2023-09-04 00:55 UTC, itsmeow commented
the yellow question mark

2023-09-05 23:05 UTC, Absolucy commented
@itsmeow done

2023-09-06 16:21 UTC, PowerfulBacon requested changes, later dismissed

2023-09-06 16:21 UTC, PowerfulBacon commented on code/controllers/subsystem/ping.dm
> +	..("P:[length(GLOB.clients)]")
This function needs to return a value

2023-09-06 23:26 UTC, itsmeow commented
You have to actually call medhud update status when the afk value changes or it won't actually show.

2023-09-15 12:10 UTC, Absolucy commented
@itsmeow What'd be the best way to handle that? Since `is_afk` is polled, rather than being constantly checked...

2023-10-19 00:43 UTC, itsmeow approved these changes
Looks good.

2023-10-19 06:03 UTC, merged