Ports "Emergency Shuttle Emag Rebalance" from Monkestation
BeeStation/BeeStation-Hornet pull request #9714
Opened 2023-08-19 17:36 UTC by CydiaLamiales

## About The Pull Request
Ports https://github.com/Monkestation/MonkeStation/pull/982
Reworks shuttle emagging so that instead of it reducing the time left to 10 seconds, it will halve the remaining time each usage. You can keep halving the remaining time until it has reached 10 seconds, the emag effect has a 2 second cooldown.

While reworking this I also noticed that hijacking was not working as intended; there was supposed to be a cooldown between attempts at increasing hijack stages, but was not implemented correctly. While this does fix that, I feel that 5 seconds may be too big of a nerf from being able to spam it, so as a slight compromise, it'll be 2 seconds, just like the emag.

I'd be happy to adjust these numbers for balance reasons as well.

## Why It's Good For The Game
Emags launching the shuttle within 12 seconds of it landing is incredibly lame and OP.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/bcada573-2c8c-40d2-8083-bade4d0fc500

</details>

## Changelog
:cl:lmenvs,CydiaLamiales
balance: Emagging the emergency shuttle now halves remaining timer. You can further reduce the timer by using the emag again (every 2 seconds).
fix: Hijacking stage increases now properly have a cooldown (2 seconds).
/:cl:

2023-08-20 14:27 UTC, Rukofamicom reviewed
This will just re-introduce the exact problem #8580 aimed to fix, enabling non-murderbone antagonists to cause a major shuttle kerfuffle just because they feel like it. While I still personally believe this is okay, the final decision on the linked PR set a code-level precedent that it wasn't imo.

2023-08-20 14:31 UTC, Rukofamicom requested changes
Unless #8580 is being considered for reversion, the emag interaction with shuttle consoles should simply be removed because I agree it is both a boring and powerful card for an antagonist to pull, enabling a hijack with minimal or no interaction for the crew. 

If there is no reason for non-hijack antagonists to create a fight on the shuttle at round end, that should extend to players using an emag.

2023-08-20 15:01 UTC, EvilDragonfiend requested changes, later dismissed

2023-08-20 15:01 UTC, EvilDragonfiend commented on code/modules/shuttle/emergency.dm
> -		authorized += ID
I believe at least one random name should be added to the list so that it can qualify as one of the early launch auths

2023-08-20 16:02 UTC, Rukofamicom commented
Talked with Dragon for a moment and if you want to add a new effect to emagging the shuttle that's perfectly fine, but we do both agree that it shouldn't result in any form of early departure or hijacking equivalent. 

Ideas for what it could do if you feel so inclined:
* Delay shuttle launch once (Buy some time for a teammate to accomplish something)
* Override safety causing the shuttle to launch everyone when it takes off (current behavior, just removing the hijack and timers

2023-08-20 18:24 UTC, CydiaLamiales commented
> Talked with Dragon for a moment and if you want to add a new effect to emagging the shuttle that's perfectly fine, but we do both agree that it shouldn't result in any form of early departure or hijacking equivalent.
> 
> Ideas for what it could do if you feel so inclined:
> 
> * Delay shuttle launch once (Buy some time for a teammate to accomplish something)
> * Override safety causing the shuttle to launch everyone when it takes off (current behavior, just removing the hijack and timers

How long should the delay be?

2023-08-20 18:39 UTC, EvilDragonfiend commented
> > Talked with Dragon for a moment and if you want to add a new effect to emagging the shuttle that's perfectly fine, but we do both agree that it shouldn't result in any form of early departure or hijacking equivalent.
> > Ideas for what it could do if you feel so inclined:
> > 
> > * Delay shuttle launch once (Buy some time for a teammate to accomplish something)
> > * Override safety causing the shuttle to launch everyone when it takes off (current behavior, just removing the hijack and timers
> 
> How long should the delay be?

90 seconds no matter it's docked or escaping.

2023-08-31 05:44 UTC, itsmeow requested changes
I'm not sure what Ruko means by allowing nonmurderbone antags to make a kerfuffle. From what I understand nonmurderbone antags already can't hijack the shuttle.

2023-08-31 05:44 UTC, itsmeow commented on code/modules/shuttle/emergency.dm
> +		say("Error - Catastrophic software error detected. Input is currently on timeout.")
this should just be a to_chat to the user since it's extremely spammable

2023-08-31 05:44 UTC, itsmeow commented on code/modules/shuttle/emergency.dm
> +	if((obj_flags & EMAGGED))
You need to adjust can_emag to allow this to happen, you shouldn't check conditions like this in on_emag. our emag code is a little different

2023-08-31 05:44 UTC, itsmeow commented on code/modules/shuttle/emergency.dm
> -	if(!..() || ENGINES_STARTED)
what does the super call do here? Why is it removed?

2023-08-31 05:45 UTC, itsmeow commented
Also you could use the emag popup from computers to add some flavor here if you want

2023-08-31 11:18 UTC, Rukofamicom commented
> From what I understand nonmurderbone antags already can't hijack the shuttle.

Emagging the console is effectively forcing the same situation, and anyone with an emag (antag or not) can cause this interaction mechanically.

2023-09-06 03:35 UTC, CydiaLamiales commented
So, what should I do here?

2023-09-06 11:22 UTC, PowerfulBacon commented
Honestly the emag behaviour on the console should be changed entirely. Having to press it 4 times instead just makes 4 really loud and annoying bleeps change and raises the timer to like 20 seconds instead of 10.

2023-09-08 17:38 UTC, CydiaLamiales commented
Meh, this isn't going anywhere.

2023-09-08 17:38 UTC, closed without merging