Makes crafting items put the result on a rack/table in front of the user if the user's hands are full
BeeStation/BeeStation-Hornet pull request #9730
Opened 2023-08-23 18:47 UTC by CydiaLamiales

## About The Pull Request
Makes crafting items put the result on a rack/table in front of the user if the user's hands are full

## Why It's Good For The Game
It would make sense that you'd put something on a table after making it instead of dropping it on the floor.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/34a23317-75e2-45f3-8dae-08af2822a74a

</details>

## Changelog
:cl:
tweak: Made crafting an item be put on a table or rack in front of the user if their hands are full
/:cl:

2023-08-23 19:07 UTC, PowerfulBacon reviewed
Make it only happen for crafted items and not structures

2023-08-23 19:09 UTC, CydiaLamiales commented
> Make it only happen for crafted items and not structures

There's an isitem(result) check before the code, line 201

2023-08-23 19:14 UTC, EvilDragonfiend commented
I think you can put an item behind a directional window

2023-08-23 19:31 UTC, CydiaLamiales commented
> I think you can put an item behind a directional window

Fixed

2023-08-24 04:42 UTC, EvilDragonfiend requested changes
variables are not used. just doing it in `if()` and having || is better because you won't calculate more unnecessary things.

2023-08-24 04:42 UTC, EvilDragonfiend commented on code/datums/components/crafting/crafting.dm
> +					if(found_rack || found_table)
```suggestion
					if((locate(/obj/structure/rack) in front_turf) || (locate(/obj/structure/table) in front_turf))
```

2023-08-24 14:34 UTC, EvilDragonfiend approved these changes

2023-09-02 09:05 UTC, merged