Fix flaky operating computer linking test
BeeStation/BeeStation-Hornet pull request #9734
Opened 2023-08-23 22:55 UTC by Absolucy

## About The Pull Request

This just makes stasis beds / operating computers / operating tables initialize immediately during the unit test

## Why It's Good For The Game

unit tests are good when they work

## Testing Photographs and Procedure

Hard to test due to inconsistency of errors; let's see if the tests here pass

## Changelog
:cl:
fix: Fixed the unit test for operating computer linking.
/:cl:

2023-08-24 01:39 UTC, itsmeow approved these changes
This seems reasonable

2023-08-28 07:08 UTC, PowerfulBacon commented
These should be called inside of Initialize(), manually calling them again seems like it defeats the point of the test. New will call initialize always and this unit test hasn't been having random failure issues so far, so any failures are a result of the PR breaking the initialization chain for these objects.

2023-08-28 07:49 UTC, itsmeow commented
This PR has been having random failures.

2023-08-28 09:47 UTC, PowerfulBacon commented
Which PRs?

2023-08-30 11:05 UTC, itsmeow commented
> Which PRs? There are none that are currently open and failing this test. The only example I can find of a failing test regarding these things is on this PR, and that is due to runtime exceptions during mapload rather than during the test.

It failed on a two of my PRs. none of them have an open failure because the error disappears on rerun. I don't have a link

2023-08-31 22:16 UTC, PowerfulBacon commented
Weird, I don't really see how this would result in random failures and haven't seen this test randomly failing in any recent PRs at all. The only recent random failures I have seen are from MapDiffBot2

2023-08-31 22:20 UTC, PowerfulBacon commented
https://github.com/BeeStation/BeeStation-Hornet/actions/runs/5815459983/job/15767050082

2023-08-31 22:35 UTC, PowerfulBacon commented
Is it possible for byond to context switch when first calling a waitfor function to be false? If so then the failure is happening because LateInitialise has waitfor = false and it is context switching back to the unit test before it actually runs the linking proc.

2023-08-31 22:38 UTC, PowerfulBacon commented
I don't see why any of this has to late initialize if every individual component links with its surroundings, so it doesnt matter if you initialise 1 before placing and initialising the next. The simple fact that this unit tests passes shows that we don't need LateInitialize at all because LateInitialize doesn't exist outside of maploading and you aren't in a maploading context when you create the 3 components, so LateInitialize will just run immediately after Initialize.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/2dfaac1e-9c66-4090-921b-060f20014be2)

2023-08-31 22:38 UTC, PowerfulBacon requested changes
See above, making these not LateInitialize will have no behavioural changes on this test and should solve the extremely rare case of not waiting for LateInitialize to complete.

2023-09-04 11:06 UTC, PowerfulBacon approved these changes
This should work

2023-09-04 11:17 UTC, merged