Allows Obsessed crewmemebrs to open the mail of their obsession targets
BeeStation/BeeStation-Hornet pull request #9737
Opened 2023-08-24 15:13 UTC by CydiaLamiales

## About The Pull Request
Allows Obsessed crewmemebrs to open the mail of their obsession targets.

## Why It's Good For The Game
Allows players to lean more into creepy stalker aspect of Obsessed. Afterall, why would a psychotic stalker care about morality when they have a piece of mail addressed to their beloved?

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/21a1a33e-78b9-4ac1-aa9f-2a8379365803)

</details>

## Changelog
:cl:
add: Added the ability for Obsessed people to open the mail addressed to their obsessions
/:cl:

2023-08-24 15:26 UTC, EvilDragonfiend requested changes
try this for a cleaner code
```DM
var/can_open = FALSE
var/datum/antagonist/obsessed/obs_datum = locate() in user?.mind?.antag_datums
if(obs_datum)
	if(obs_datum.trauma.obsession.name != recipient.name)
		to_chat(user, "<span class='notice'>This <em>worthless</em> piece of parchment isn't adressed to your beloved!</span>")
		return
	can_open = TRUE
if(user.real_name != recipient.name && !can_open)
	//...
```

2023-08-24 15:43 UTC, CydiaLamiales commented
Yep, that works

2023-08-24 15:48 UTC, EvilDragonfiend approved these changes

2023-09-01 13:53 UTC, Penwin0 approved these changes

2023-09-01 14:06 UTC, merged