Holodeck Stage
BeeStation/BeeStation-Hornet pull request #9740
Opened 2023-08-24 23:06 UTC by MarkusLarsson421

## About The Pull Request
Varo wanted it. lol

Related forum thread.
https://forums.beestation13.com/t/put-a-threatre-in-the-holodeck/23785/

Adds a stage holodeck with 18 seats in the front, back stage area and curtains separating the two. Several costumes and some items can also be found in the back.

<details>
<summary>All Items</summary>

- Black and Red Space Suit Replica

- Black Space-Helmet Replica

- Spacepol Mask

- CentCom Officers Jumpsuit

- CentCom Hat

- CentCom ID

- 3x Random costume sets

- Fake Emag

- Fake Handcuffs

- Toy Crate

</details>

## Why It's Good For The Game
Clowns, **Stage** Magicians and other people might want a place to put up a proper show. Could also be used for auctions, public executions and other events too.

Added a few costumes that they could use for a interesting theatrical performance and some items. They are deleted when they leave the holodeck and don't have much use whilst inside.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Map overview.
![2023-08-25 00 50 11](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/0faec132-d7ae-4043-a5bc-5c01050c05ee)

Stage put in use.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/903734d3-ebfd-4322-8403-f8a1b098437e)

Some items.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/dce0de1c-0c39-470f-9009-574526a0885c)

Some other items.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/d8826b54-61eb-43b0-8afe-da08f845afc8)

</details>

## Changelog
:cl:
add: Added the Stage holodeck.
/:cl:

2023-08-25 00:27 UTC, EvilDragonfiend requested changes
Instead of adding a lot of items, add a single chest that contains those items, so that we don't have to edit maps additionally, but only do that to the chest when we want to add more toy items

2023-08-25 00:29 UTC, EvilDragonfiend commented
Also map layout change:
* curtains should be at sides, not at the middle: it will leak everythong when curtains are open

2023-09-25 19:10 UTC, EvilDragonfiend commented
Are you working on it? Tell me again if you don't know how to make a subtype of a crate.

2023-09-28 21:33 UTC, MarkusLarsson421 commented
Sort of forgot about this. I'll spend some time on this tomorrow and DM you on Discord if I need assistance, thank you for checking! ^-^

2023-10-21 08:12 UTC, PowerfulBacon commented
Failing checks

2023-10-27 00:17 UTC, closed without merging