Adds automatic chat highlighting + a toggle for a sound playing when someone mentions the AI on the radio.
BeeStation/BeeStation-Hornet pull request #9776
Opened 2023-09-03 12:51 UTC by CydiaLamiales

## About The Pull Request
Makes any variation of "AI" plus the AI's name and name with dots removed, be automatically highlighted in the chat for AI players.
Adds a toggle for a sound playing whenever "AI" or the AI's name is mentioned for the AI player.

## Why It's Good For The Game
Allows AI players to more easily notice people calling for their attention.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/c3fb21c3-8846-432d-a931-dea99cb7e691

</details>

## Changelog
:cl:
add: Added automatic chat highlighting for AI players that includes "AI" and the AI player's name
add: Added a toggle for a sound playing whenever the AI player hears "AI" or their name
/:cl:

2023-09-03 14:30 UTC, CydiaLamiales commented on code/modules/mob/living/silicon/ai/ai.dm
> +		playsound_local(get_turf(src), 'sound/machines/twobeep.ogg', 50)
```suggestion
		playsound_local(get_turf(src), 'sound/machines/twobeep.ogg', 25)
```

2023-10-06 06:45 UTC, PowerfulBacon commented on code/modules/mob/living/silicon/ai/ai.dm
> +	UnregisterSignal(src, COMSIG_MOVABLE_HEAR, PROC_REF(handle_hearing))
Signals are automatically unregistered on Destroy() but I guess it doesn't hurt to explicitly unregister it.

2023-10-06 06:48 UTC, PowerfulBacon requested changes

2023-10-06 06:48 UTC, PowerfulBacon commented on code/modules/mob/living/silicon/ai/ai.dm
> +	message = ai_chat_highlights.Replace(message, "<span style='color:pink'>$1</span>")
This should use one of the new colour spans like cfc_pink

2023-10-06 06:48 UTC, PowerfulBacon commented on code/modules/mob/living/silicon/ai/ai.dm
> +			break
This is a very strange way to run a regex, simply early return if regex.Find(message) returns false.

2023-10-06 06:48 UTC, PowerfulBacon commented on code/modules/mob/living/silicon/ai/ai.dm
> +			break
https://www.byond.com/docs/ref/#/regex/proc/Find

2023-11-13 00:18 UTC, closed without merging