removed mystery meat from vegetarian burritos (and a typo fix)
BeeStation/BeeStation-Hornet pull request #9793
Opened 2023-09-05 22:23 UTC by boombaklops

## About The Pull Request
Removes the MEAT foodtype flag from burritos and cheesy burritos. The recipes don't call for meat, so the resulting food shouldn't have meat in it. Also fixes a typo.

## Why It's Good For The Game

No longer will poor moffs consume delicious burritos and be POISONED by FOUL MAGIC.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![breeto](https://github.com/BeeStation/BeeStation-Hornet/assets/116023863/92966c31-766c-4cfd-b617-3886f6db6a89)

</details>

## Changelog
:cl:
fix: removed mystery meat from vegetarian burritos and fixed a taste typo
/:cl:

2023-09-06 00:04 UTC, Rukofamicom requested changes

2023-09-06 00:04 UTC, Rukofamicom commented on code/modules/food_and_drinks/food/snacks_other.dm
>  	foodtype = GRAIN | MEAT
```suggestion
	tastes = list("tortilla" = 2, "hot peppers" = 1)
	foodtype = GRAIN
```

This burrito is also meatless when crafted.

2023-09-06 11:04 UTC, Rukofamicom approved these changes

2023-09-08 01:33 UTC, itsmeow approved these changes
lmao why do the vegetarian burritos have meat

2023-09-08 11:29 UTC, merged