Scav rifle
BeeStation/BeeStation-Hornet pull request #982
Opened 2019-12-11 12:18 UTC by Baldir-Odensen

## About The Pull Request

Adds the Scav rifle so that those who wich to make scav themed ruins and to when the scav ship is added give them a gun to use

## Why It's Good For The Game

gives the scavengers a unique gun that is slightly worse than most weapons so that they can have and buy guns without unbalancing the game by making it easy for them to get better weapons than station crew.

## Changelog
:cl:
add: added the scav rifle
/:cl:

2019-12-11 13:05 UTC, zeskorion commented
why do they even need guns at all?

2019-12-11 14:52 UTC, Baldir-Odensen commented
It's to be able to figth the hostile mobs in space. It will also be used for the scav contractor simple mob that might be put into new space ruins.

2019-12-15 04:01 UTC, ike709 commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +/obj/item/gun/ballistic/automatic/scav
Needs a line of whitespace before it.

2019-12-15 13:04 UTC, Baldir-Odensen commented
Ok I'll do that

2019-12-16 00:58 UTC, ike709 commented
Honestly this should just be a surplus rifle subtype. Or just, y'know, use surplus rifles.

2019-12-16 06:11 UTC, Baldir-Odensen commented
The surplus rifle is useless. It's supposed to get its own sprite but I can't sprite so I'll let people who know how to do it do it later. Also it has no stat in common with the surplus rifle except sprite so the amount of code would be the same

2019-12-16 20:51 UTC, ike709 commented
Actually, everything should match the surplus rifle except the name, desc, fire_delay, and mag_type. Your weapon is just missing various flags that it should have, which the surplus rifle does.

2019-12-16 21:14 UTC, Baldir-Odensen commented
It's not supposed to have things like heavy and huge. It's supposed to be something like a pipe smg (sten gun, grease gun) so something smallish not huge and bulky. It's supposed to be like the sec auto rifle but slightly worse.

2020-01-02 03:37 UTC, qwertyquerty requested changes

2020-01-02 03:37 UTC, qwertyquerty commented on code/modules/projectiles/boxes_magazines/external/rifle.dm
> -/obj/item/ammo_box/magazine/m10mm/rifle
You changed the line endings in this file. Fix.

2020-01-02 03:37 UTC, qwertyquerty commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	name = "Scav gun"
Lowercase scav

2020-01-29 16:58 UTC, qwertyquerty commented
@Baldir-Odensen ?

2020-02-24 19:31 UTC, qwertyquerty commented
@Baldir-Odensen

2020-02-25 16:23 UTC, qwertyquerty commented
stale

2020-02-25 16:23 UTC, closed without merging