Finally fixed that AI node to meta
BeeStation/BeeStation-Hornet pull request #9892
Opened 2023-09-25 08:24 UTC by PestoVerde322

## About The Pull Request

This PR At last adress an AI node error in meta, where all the AI bots would get stuck in front off the Telecomms.

## Why It's Good For The Game

It finally address this insaneley annoying stuff on meta

![dreamseeker_CUvKGVvKTT](https://github.com/BeeStation/BeeStation-Hornet/assets/75247747/5fc5165f-ffa5-4053-88af-fa81aee10a78)

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>
The medibot is finally free to leave the node hell that it used to be.

![dreamseeker_RXQLRkYXo9](https://github.com/BeeStation/BeeStation-Hornet/assets/75247747/4cf88caa-0d6d-4361-a7a3-0f051feb5ae7)

</details>

## Changelog
:cl:
fix:[Metastation] finally adressed the bug related to bots getting stuck in front off telecomms
/:cl:

2023-09-25 08:33 UTC, itsmeow requested changes

2023-09-25 08:33 UTC, itsmeow commented on _maps/map_files/MetaStation/MetaStation.dmm
> +	name = "Sir debugger"
What

2023-09-25 08:33 UTC, itsmeow commented on _maps/map_files/MetaStation/MetaStation.dmm
> +	name = "Sir debugger"
What the fuck is this

2023-09-25 08:34 UTC, itsmeow commented
oh lol

2023-09-25 08:34 UTC, itsmeow commented
Mistake
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/10366817/45a001df-9b9f-4095-94ab-92e33ec15707)

2023-09-29 07:33 UTC, PowerfulBacon approved these changes

2023-10-02 19:50 UTC, Penwin0 approved these changes

2023-10-03 02:15 UTC, itsmeow approved these changes

2023-10-03 02:25 UTC, merged