removes some dangerous foods from silver extracts
BeeStation/BeeStation-Hornet pull request #9936
Opened 2023-09-30 15:06 UTC by bluezorua

## About The Pull Request
adds the following to the silver slime extract blacklist, previously limited only to parent foods that shouldn't be seen ingame at all:
- esword cakes (and their slices)
- gatfruit
- cherry bombs
- roburgers (and the big variant)

## Why It's Good For The Game
xenobio shouldn't have access to these for free, xenobio is argueably one of the most powerful subsepartments in the game

## Testing Photographs and Procedure
hard to photograph something that should be removed

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: Toasterban
del: Removed the chance for silver slime extracts to spawn gatfruits, energy cakes, cherry bombs or roburgers
/:cl:

2023-09-30 15:20 UTC, Tsar-Salat commented
> hard to photograph something that should be removed

Photograph your tests not failing 
:trollface:

2023-09-30 15:45 UTC, bluezorua commented
> > hard to photograph something that should be removed
> 
> Photograph your tests not failing :trollface:
alright 
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/54711687/d2c785f7-3a43-454b-8be3-5fbc23b8152c)

2023-09-30 16:27 UTC, EvilDragonfiend commented
It removes the only way to get cherry bomb seeds from the whole game. I am not sure about that one.

2023-09-30 17:04 UTC, CydiaLamiales commented
> It removes the only way to get cherry bomb seeds from the whole game. I am not sure about that one.

They spawn on the Lifebringer ship, same as Gatfruit seeds.

2023-09-30 18:05 UTC, bluezorua commented
> It removes the only way to get cherry bomb seeds from the whole game. I am not sure about that one.

could add them to the botanist traitor uplink if you wish

2023-09-30 19:03 UTC, Fronsis commented
> > It removes the only way to get cherry bomb seeds from the whole game. I am not sure about that one.
> 
> could add them to the botanist traitor uplink if you wish

Would be mega strong since they get unlimited bombs/guns for X TC

Anyway back to the pr, yeah as Lamiales said it spawns on the Lifebringer ship and sometimes you get them to trade with you or some miners get it by breaking in, certainly the extract of random food having it appear encourages some powergaming (or a traitor who likes rng) 

Good fix imo!

2023-09-30 19:10 UTC, St0rmC4st3r commented
I highly disagree. This removes a lot of cool stuff that allows for fun gameplay. Yes, sometimes it can be abused by bad actors, but that is an administrative issue, and should not remove opportunity for good gameplay for proper players.

2023-09-30 19:12 UTC, CydiaLamiales commented
> I highly disagree. This removes a lot of cool stuff that allows for fun gameplay. Yes, sometimes it can be abused by bad actors, but that is an administrative issue, and should not remove opportunity for good gameplay for proper players.

What "fun gameplay" comes out of non-antag Xenobiologists being able to get uplink items?

2023-09-30 19:16 UTC, St0rmC4st3r commented
> > I highly disagree. This removes a lot of cool stuff that allows for fun gameplay. Yes, sometimes it can be abused by bad actors, but that is an administrative issue, and should not remove opportunity for good gameplay for proper players.
> 
> What "fun gameplay" comes out of non-antag Xenobiologists being able to get uplink items and rare lavaland spawns?

Gatfruit requires high levels of cooperation. If your concern is energy cakes, they should be nerfed, not the silver extracts.

2023-09-30 19:21 UTC, CydiaLamiales commented
Why should we nerf an item that's otherwise only obtainable through the uplink and costs 8 TC, rather than an item that can mass produce them for free? You're not making any sense here.

2023-09-30 22:19 UTC, Rukofamicom commented
Gatfruit is the only item on the list I'd approve removing.

None of the rest of these even remotely present a balance issue.

2023-09-30 22:26 UTC, Rukofamicom requested changes
Gatfruit is the only item on the list I'd approve removing. None of the rest of these even remotely present a balance or gameplay issue, 

cherry bombs will explode with all the force of a wet fart without hydroponics support.

The cake might be hard to obtain otherwise because it requires an esword, but the cake is in no way a powerful weapon and the sword can not be retrieved. The worst you can do with it is make a special cake hat for an 18 damage weapon - barely better than a welder.

I'm not gonna get heavily into roburgers, but I don't see them as anything of an issue for the level of effort they take to obtain and weapons compared to other reagents accessible to players in general.

2023-10-01 15:18 UTC, Rukofamicom approved these changes

2023-10-02 04:42 UTC, boombaklops commented
> The cake might be hard to obtain otherwise because it requires an esword, but the cake is in no way a powerful weapon and the sword can not be retrieved. The worst you can do with it is make a special cake hat for an 18 damage weapon - barely better than a welder.

turning it into a hat is a mistake. a non-hat energy cake does 35 damage (on harm intent), fits in a pocket, is quieter than the esword, doesn't need to be turned on or off, and has no in-hand sprite. it's definitely better than the normal esword

2023-10-02 11:25 UTC, Rukofamicom commented
I see I've misread the code on the energy cake. I'm of the same mind as @St0rmC4st3r in that case, the cake itself is the issue because it's meant to be a joke item (even when made through conventional means) rather than an actual upgrade.

2023-10-04 08:31 UTC, PowerfulBacon commented
I don't really have a problem with the gatfruits being in xenobiology but I also don't have a problem with removing them. They aren't really usable in a plan for a strategy due to the random nature of obtaining them, so these will basically only exist for powergamers.
While writing this message, I convinced myself that I don't like them so merging.

2023-10-04 08:58 UTC, merged