Rebalances Meteor Shields, more of them and faster deployment
BeeStation/BeeStation-Hornet pull request #9959
Opened 2023-10-04 16:11 UTC by mystery3525

## About The Pull Request

Doubles the meteor shield satellite crate supply amount to 4 (totaling 28 shield satellites if all of them are deployed), and makes the deployment time 3 seconds (down from 10 seconds).

## Why It's Good For The Game

With https://github.com/BeeStation/BeeStation-Hornet/pull/9239 keyed, it is stated that meteor satellite deployment should be made easier, this makes it way more easier to rapidly acquire and deploy meteor satellites in the very limited amount of time we're forcing everyone to have to prepare. 10 seconds per satellite to deploy is ludicrous in my opinion, and is objectively worse than just dragging around a meteor crate from before. I have also added more supply to the meteor satellites, as it should not be as supply limited as other items due to the imminent emergency, no one is scalping the sats off the market.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Only cooldown and supply changes for now, if I need to prove this works in game then we aren't trusting the rest of the code to work.

</details>

## Changelog
:cl:
balance: Meteor shield satellites now take 3 seconds to deploy, down from 10.
balance: Meteor shield satellites now have double the supply, up to 4 packs of 28 total, from 2 packs of 14.
/:cl:

2023-10-04 16:32 UTC, EvilDragonfiend commented
Although I introduced the feature, I don't care about the adjustment here. I will put this to other maints since I usually don't set meteor shields so that I don't know how ludicrous it is...

2023-10-05 00:21 UTC, Rukofamicom commented
Since you have cherry-picked part of what was said on the other PR, let me slap both of them on here in full detail:

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/9547572/ab25f05f-6c98-4cbf-b6f2-2cacfa038a15)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/9547572/e60b807b-f731-4238-8a5a-15ce9e946e94)

Reducing the time it takes to deploy them is fine, 10 seconds is admittedly excessive, however doubling the available amount goes explicitly against what I outlined in mine.

>  It is intended for the station to prioritize the most important areas and evacuate crew into shielded areas.

🔑

2023-10-05 00:24 UTC, Rukofamicom requested changes

2023-10-05 00:24 UTC, Rukofamicom commented on code/modules/cargo/packs.dm
> +	max_supply = 4
```suggestion
	max_supply = 2
```

I will remove my key and approve if this is reverted.

2023-10-05 03:03 UTC, EvilDragonfiend commented
I agree with Ruko to reduce the time, but not increasing the stock amount. If you want to prepare meteor shielding perfectly, you should have purchased crates, not being capable of buying a lot in a single move.

2023-10-07 10:43 UTC, PowerfulBacon commented
The biggest improvement to meteor shields would be to set them up using a prox monitor so they can actually shoot down meteors outside of process()

2023-11-07 01:43 UTC, Rukofamicom commented
Been a month with no movement.

2023-11-10 20:56 UTC, closed without merging