https://github.com/tgstation/tgstation/pull/53354
BeeStation/BeeStation-Hornet pull request #9975
Opened 2023-10-06 20:48 UTC by Tsar-Salat

Ports:
- https://github.com/tgstation/tgstation/pull/53354

## About The Pull Request

Converts suit storage units to use radials instead of ugly list inputs

![dreamseeker_Fvq2lWm07S](https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/f1c36ffb-2d2a-469a-ab4c-636360319eaa)

## Why It's Good For The Game

Modsuit port atomization

Looks a lot cleaner, less ugly white boxes on the screen the better

Basic things that you can only put a really limited amount of items in should use Radials. It is a complete waste to put them into lists. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/8fd8e0f5-7868-4d3e-8a4d-1f0ad2998627

</details>

## Changelog
:cl: rkz, Mothblocks
add: Suit Storage Units now use radials!
rscadd: SSU radials
/:cl:

2023-10-06 22:22 UTC, itsmeow approved these changes
yesyeyesyesyesyseyseyes

2023-10-06 22:23 UTC, itsmeow requested changes

2023-10-06 22:23 UTC, itsmeow commented on code/game/machinery/suit_storage_unit.dm
> -		ui = new(user, src, "SuitStorageUnit")
remove the SuitStorageUnit file

2023-10-06 22:24 UTC, itsmeow commented
Do magboots still fit in it?

2023-10-07 16:35 UTC, Tsar-Salat commented
> Do magboots still fit in it?

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/6a7d3c13-cca4-4110-bb46-f3aaa6fcc392)

Yes.

I also took the liberty of updating the file to update_appearance standards, and removing all the ui_update calls. 

It doesnt use TGUI anymore, so those are unecessary.

2023-10-07 18:59 UTC, Tsar-Salat commented on code/game/machinery/suit_storage_unit.dm
> -		ui = new(user, src, "SuitStorageUnit")
removed in 648bc2c

2023-10-10 19:01 UTC, itsmeow approved these changes
Looks good to me. Thanks for the update_appearance refactor.

2023-10-10 19:20 UTC, PestoVerde322 approved these changes
It good.

2023-10-10 19:51 UTC, merged