Fixes the syndicate balloon's moodlet not linebreaking
BeeStation/BeeStation-Hornet pull request #9976
Opened 2023-10-06 22:17 UTC by PestoVerde322

## About The Pull Request

This PR just fixes the Syndicate balloon's moodlet not linebreaking and drammatically break the immersion.

## Why It's Good For The Game

Fix this from happening:

![dreamseeker_rKCdSFNcDt](https://github.com/BeeStation/BeeStation-Hornet/assets/75247747/bddff3ee-9bb6-4956-b67e-a26903dad940)

## Changelog
:cl:
fix: Fixed the moodlet on the Syndicate Balloon
/:cl:

2023-10-06 22:28 UTC, itsmeow requested changes, later dismissed

2023-10-06 22:28 UTC, itsmeow commented on code/datums/mood_events/generic_positive_events.dm
> +	description = "I'm a fucking badass and everyone around me knows it. Just look at them; they're all fucking shaking at the mere thought of me around.\n"
What dumbass coded it this way. Yeet this nonsense convention

2023-10-12 15:36 UTC, tontyGH reviewed
This works, but you could replicate how `mob/examinate()` does it and make `msg` a list to store all the messages, and then do `jointext(msg, "\n")` so you can get rid of every `\n` in `datum/component/mood.dm` as well

2023-10-13 10:01 UTC, PestoVerde322 commented
> This works, but you could replicate how `mob/examinate()` does it and make `msg` a list to store all the messages, and then do `jointext(msg, "\n")` so you can get rid of every `\n` in `datum/component/mood.dm` as well

I think the whole examinate call is totally different than what you're explaining here, but i'll see what i can come up with.

Example of examinate on a mob:

![immagine](https://github.com/BeeStation/BeeStation-Hornet/assets/75247747/7d5e3129-f4fe-4108-97c3-f912ac5db736)

2023-11-07 01:47 UTC, Rukofamicom approved these changes
That's a lot of \n removals. 
This was kind of a headache to review and I hope I didn't miss something.

2023-11-07 02:05 UTC, merged