Finally finishes movespeed modifiers after 5 years.
BeeStation/BeeStation-Hornet pull request #9992
Opened 2023-10-08 17:31 UTC by Tsar-Salat

Ports:
- https://github.com/tgstation/tgstation/pull/48747
- https://github.com/tgstation/tgstation/pull/50095

## About The Pull Request

Refactors movespeed modifiers to be datum/movespeed_modifier(s) rather than lists.
adds a new proc for adding/updating variable movespeed modifiers as opposed to static movespeed modifiers which are now cached for performance/efficiency

## Why It's Good For The Game

Movespeed modifiers were first introduced in https://github.com/tgstation/tgstation/pull/39181, 5 years ago.

While we have been very close to completing this system on Bee, it was never actually completed to be completely modular.

After work in this PR and the completed PRs #9356, and #9391, it will be just that

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl: rkz, silicons, Rohesie
refactor: movespeed modifiers are now datums and not lists and support global caching.
fix ignore_slowdown works correctly
/:cl:

2023-10-12 07:16 UTC, PowerfulBacon commented on code/datums/components/mood.dm
> +			master.remove_movespeed_modifier(MOVESPEED_ID_SANITY)
Instead of using strings, you should be able to pass in the supertype like `/datum/movespeed_modifier/sanity` and have that automatically remove all subtypes.

2023-10-12 07:16 UTC, PowerfulBacon commented on code/modules/movespeed/_movespeed_modifier.dm
> +			type_or_datum = new type_or_datum
Do we actually need to create instances of them? Couldn't we use initial and save ourselves from ever having to create these datums to begin with? (Unless I am missing a case where they are modified from the initial values)

2023-10-12 08:16 UTC, Tsar-Salat commented on code/modules/movespeed/_movespeed_modifier.dm
> +			type_or_datum = new type_or_datum
I believe this is the case with Stabilized sepia extracts. When in the mobs inventory, it adds a Randomized movespeed modifier between 1 and -1 every two seconds

2023-10-12 20:39 UTC, PowerfulBacon commented on code/modules/movespeed/_movespeed_modifier.dm
> +			type_or_datum = new type_or_datum
Oh I see, the actual slowdown is on the datum itself. Jetpacks also use variable slowdown rates

2023-10-14 04:18 UTC, Tsar-Salat commented on code/datums/components/mood.dm
> +			master.remove_movespeed_modifier(MOVESPEED_ID_SANITY)
oh, i just forgot to convert these, my b

2023-10-14 04:20 UTC, Tsar-Salat commented on code/modules/movespeed/_movespeed_modifier.dm
> +			type_or_datum = new type_or_datum
> Jetpacks also use variable slowdown rates

Yes, I think I converted your jetpack speedcheck correctly. It tested alright. Let me know if it looks wrong.

2023-10-21 07:54 UTC, PowerfulBacon commented on code/datums/components/mood.dm
> +			master.remove_movespeed_modifier(MOVESPEED_ID_SANITY)
Thinking about it, the differentiation of types could be handy for showing clearly that we are doing something else.

2023-10-21 07:54 UTC, PowerfulBacon approved these changes

2023-10-21 07:55 UTC, PowerfulBacon requested changes
This PR should ideally have a unit test that confirms new movespeed modifiers being added work and are using the new system properly

2023-10-24 15:30 UTC, Tsar-Salat commented
> This PR should ideally have a unit test that confirms new movespeed modifiers being added work

Metabolizing unit test already checks if movespeed is modified correctly with meth, so it should be good to go!

2023-10-26 15:35 UTC, Tsar-Salat commented on code/datums/components/mood.dm
> +			master.remove_movespeed_modifier(MOVESPEED_ID_SANITY)
Yeah, I really hated the way how every line could have a different value or movetype. Putting it all in one .dm is definitely the sane option imo

2023-11-22 03:37 UTC, Tsar-Salat commented
bump

2023-11-26 00:46 UTC, itsmeow commented
How come some modifiers still use the ID defines and some use typepath?

2023-11-28 06:46 UTC, Tsar-Salat commented
> How come some modifiers still use the ID defines and some use typepath?

All movespeed-addition calls should generally be typepaths, unless they have some special snowflake code around them.

Remvoals are the opposite. If it makes sense & we have the opportunity, we should convert movespeed modifier removals to use IDs. If we have multiple move-speed additions, we can register them all to the same ID and just use a single movespeed-remove call.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/b1378b20-bd58-4d31-a6e0-dbc0c826027f)

In this example, we have multiple different typepaths, but all the typepaths share the `MOVESPEED_ID_SANITY` ID. This way calling the ID for removal would remove any related typepath registered to it.

2024-01-18 18:14 UTC, Tsar-Salat commented
Going to wait until #core

> Checks failing

G2G

2024-03-03 18:17 UTC, PowerfulBacon approved these changes
Seems fine

2024-03-19 23:06 UTC, Rukofamicom commented
Breaks combat tab for unknown reasons:

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/9547572/ac668f13-8f74-4f31-806b-5ba818e7a1de)

Confirmed to be this TM because the panel was working again after removing the TM.

2024-03-20 22:17 UTC, PowerfulBacon commented
@Rukofamicom 
What was the round ID, since that is likely runtime related.

2024-03-22 11:32 UTC, Rukofamicom commented
#48077

2024-03-26 14:37 UTC, Rukofamicom approved these changes
If this hasn't caused issues by this weekend and remains testmerged, I think we're clear to say it passed without issue.

2024-03-28 02:17 UTC, Rukofamicom commented
Bumping this up in schedule slightly.

2024-03-28 02:24 UTC, merged