Ports the RBMK from NSV
BeeStation/BeeStation-Hornet pull request #9993
Opened 2023-10-08 21:20 UTC by XeonMations

## About The Pull Request

Adds in the RBMK nuclear reactor from NSV.

## Why It's Good For The Game

With the recent atmos bugs going on and general engineering incompetence, why not add another engine for engineering to fuck up and blow a hole in the engineering department with.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/2b621880-aee0-4b34-ae57-7a201f8c6804)
![image-1](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/a4a38da7-bc0f-43a4-8442-3d71fb138f5a)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/ab5b8afd-fb2f-434e-8e86-e7cf397694a9)
![image-1](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/44e79701-2b5f-4821-842d-fbe18cfabb30)

</details>

## Changelog
:cl: Xeonmations, Aramix
add: Added the RBMK reactor, ported from NSV.
/:cl:

2023-10-09 18:11 UTC, Penwin0 commented on code/game/objects/effects/decals/cleanable/misc.dm
> +
```suggestion
```

2023-10-09 18:23 UTC, Penwin0 commented
DNM until proper mapping gets done

2023-10-10 00:47 UTC, francinum commented
Why.

2023-10-17 12:00 UTC, Rukofamicom commented
God those are some ugly sprites
I don't know what I want a nuclear reactor to look like, but it isn't this. 

I do, on the other hand, want this reactor.

2023-10-19 18:05 UTC, Tsar-Salat commented
> God those are some ugly sprites
> I don't know what I want a nuclear reactor to look like, but it isn't this.

Its my understanding that it intends to look like the real-life RBMK control rod & reactor lid.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/163c23ff-6342-4f55-834c-d8b5eb196aaa)

2023-10-21 07:58 UTC, PowerfulBacon commented
This shouldn't be mapped in alongside the SM (If it is roundstart mapped it needs to replace the SM, however I would prefer if we stuck to a single roundstart engine type for maps since we know how the SM works and can fix it if things about it don't work), ideally it would be something like a cargo replacement for the antimatter reactor

2023-10-28 22:05 UTC, francinum commented
> > Why would you want this mess.
> 
> Better to have a not bugged engine than one that explodes due to atmospherics being bugged! 

Give players a singularity or a tesla if this is an immediate, priority concern. Layering fresh code and an entirely new engine that is immanipulable as equipment like the gravity gen is not a good idea.

2023-11-05 19:10 UTC, JixS4v requested changes

2023-11-05 19:10 UTC, JixS4v commented on code/modules/power/rbmk/rbmk.dm
> +		if(vessel_integrity >= 350)
```suggestion
		if(vessel_integrity >= 0.875*initial(vessel_integrity))
```
Seems a bit weird to base some stuff on the initial vessel integrity and other stuff on absolute values, better to standardize.

2023-11-05 19:10 UTC, JixS4v commented on code/modules/power/rbmk/rbmk.dm
> +			if(vessel_integrity >= 350)	//They might've stacked doafters
```suggestion
			if(vessel_integrity >= 0.875*initial(vessel_integrity))	//They might've stacked doafters
```

2023-12-18 09:11 UTC, PowerfulBacon commented
I mean, I'm fine with this being buildable to replace something like the TEG, but the supermatter must be the standard engine for all maps.

2023-12-20 21:51 UTC, closed without merging